--------------------------------------------------------
--  DDL for Index GOODS_INCIDENTS_UI2
--------------------------------------------------------

  CREATE UNIQUE INDEX "SDBMGR"."GOODS_INCIDENTS_UI2" ON "SDBMGR"."GOODS_INCIDENTS" (CASE "STATUS_CONTROL" WHEN 'P' THEN "INC_ID" WHEN 'C' THEN "INC_ID" ELSE NULL END , CASE "STATUS_CONTROL" WHEN 'P' THEN "GOODS_ITEM_ID" WHEN 'C' THEN "GOODS_ITEM_ID" ELSE NULL END , CASE "STATUS_CONTROL" WHEN 'P' THEN "DEST_COUNTRY_ID" WHEN 'C' THEN "DEST_COUNTRY_ID" ELSE NULL END , CASE "STATUS_CONTROL" WHEN 'P' THEN "BATCH_ID" WHEN 'C' THEN "BATCH_ID" ELSE NULL END ) 
  ;
