--------------------------------------------------------
--  DDL for Index XV_WB_ACTIONS_IDX1100
--------------------------------------------------------

  CREATE INDEX "XVIEWMGR"."XV_WB_ACTIONS_IDX1100" ON "XVIEWMGR"."XV_WB_ACTIONS_DATA" ("WBA_ID_CURRENT", "ACTION_MNEM_CURRENT", "ACTION_CATEGORY_CURRENT", "ACTION_PROMPT_CURRENT", "ACTIVITY_DATA_UREF_CURRENT", "BS_ID_CURRENT", "WORKBASKET_UREF_CURRENT", "ACTION_CONFIRM_CURRENT") 
  ;
