--------------------------------------------------------
--  DDL for Table ADVICE_SELECTION_TYPES
--------------------------------------------------------

  CREATE TABLE "BPMMGR"."ADVICE_SELECTION_TYPES" 
   (	"CRITERIA_CODE" VARCHAR2(20 BYTE), 
	"DESCRIPTION" VARCHAR2(100 BYTE), 
	"TRUE_INFO_MESSAGE" VARCHAR2(250 BYTE), 
	"FALSE_INFO_MESSAGE" VARCHAR2(250 BYTE), 
	"TRUE_MESSAGE_ICON" VARCHAR2(100 BYTE), 
	"FALSE_MESSAGE_ICON" VARCHAR2(100 BYTE), 
	"START_DATETIME" DATE, 
	"END_DATETIME" DATE, 
	"STATUS_CONTROL" VARCHAR2(1 BYTE)
   ) ;
  GRANT SELECT ON "BPMMGR"."ADVICE_SELECTION_TYPES" TO "SPIREMGR";
  GRANT SELECT ON "BPMMGR"."ADVICE_SELECTION_TYPES" TO "APPENV";
