--------------------------------------------------------
--  DDL for Table ADVICE_ADVISORY_COMMUNITIES
--------------------------------------------------------

  CREATE TABLE "BPMMGR"."ADVICE_ADVISORY_COMMUNITIES" 
   (	"ID" NUMBER(12,0), 
	"AAB_ID" NUMBER(12,0), 
	"AC_ID" NUMBER(12,0), 
	"AB_ID" NUMBER(12,0), 
	"ADVICE_TYPE" VARCHAR2(30 BYTE), 
	"TOP_LEVEL_RECEIVE_FLAG" VARCHAR2(5 BYTE), 
	"TOP_LEVEL_ADVISOR_FLAG" VARCHAR2(5 BYTE), 
	"BATCH_ADVISOR_FLAG" VARCHAR2(5 BYTE), 
	"SUB_ADVISOR_FLAG" VARCHAR2(5 BYTE), 
	"SUB_ADVISOR_METHOD" VARCHAR2(10 BYTE), 
	"SUB_ADVISOR_FORMAT" VARCHAR2(10 BYTE), 
	"BATCH_COORDINATOR_FLAG" VARCHAR2(5 BYTE), 
	"NOMINATE_RFI_RECIPIENT" VARCHAR2(50 BYTE), 
	"REMOTE_INTERFACE_FLAG" VARCHAR2(5 BYTE), 
	"REVIEW_ITEM_CODE_LIST" VARCHAR2(4000 BYTE), 
	"XML_DATA" "BPMMGR"."XMLTYPE", 
	"ASSIGN_OVERRIDE_METHOD" VARCHAR2(20 BYTE), 
	"DEFAULT_PICKABLE_AAC_FLAG" VARCHAR2(5 BYTE)
   ) ;

   COMMENT ON TABLE "BPMMGR"."ADVICE_ADVISORY_COMMUNITIES"  IS 'Intersection table from Advisory Communities to Advice Advisory Bodies to control the community to body to type access';
