--------------------------------------------------------
--  DDL for Table APP_ERRORS
--------------------------------------------------------

  CREATE TABLE "FOXMGR"."APP_ERRORS" 
   (	"ID" NUMBER, 
	"SYSTEM_DOMAIN_ID" NUMBER, 
	"SEVERITY" VARCHAR2(50 BYTE), 
	"ERROR_MSG" VARCHAR2(4000 BYTE), 
	"ERROR_INFO" CLOB, 
	"STATUS" VARCHAR2(20 BYTE), 
	"RAISED_BY_WUA_ID" NUMBER, 
	"CLEARED_BY_WUA_ID" NUMBER, 
	"RAISED_DATETIME" DATE, 
	"CLEARED_DATETIME" DATE, 
	"RAISING_MODULE" VARCHAR2(500 BYTE), 
	"MESSAGE_SENT" CHAR(1 BYTE)
   ) 
 LOB ("ERROR_INFO") STORE AS BASICFILE "APP_ERROR_ERROR_INFO_CLOB"(ENABLE STORAGE IN ROW CHUNK 8192 RETENTION 
  NOCACHE LOGGING ) ;
