--------------------------------------------------------
--  DDL for Table APPLICATION_AMENDMENTS
--------------------------------------------------------

  CREATE TABLE "SDBMGR"."APPLICATION_AMENDMENTS" 
   (	"ELA_GRP_ID" NUMBER, 
	"ELA_ID" NUMBER, 
	"CASE_TYPE" VARCHAR2(100 BYTE), 
	"CASE_SUB_TYPE" VARCHAR2(100 BYTE), 
	"CASE_PROCESSING_TIME" NUMBER, 
	"AMENDMENT_CLOSED_DATE" DATE, 
	"WITHHELD_STATUS" VARCHAR2(30 BYTE), 
	"BATCH_ID" NUMBER, 
	"ALLOW_RELEASE_OF_BATCH_ID" NUMBER, 
	"WITHHELD_REASON_CODE" VARCHAR2(30 BYTE), 
	"XML_DATA" "SYS"."XMLTYPE" 
   ) 
 XMLTYPE COLUMN "XML_DATA" STORE AS SECUREFILE BINARY XML "APP_AMEND_XML_DATA"(DISABLE STORAGE IN ROW CHUNK 8192
  CACHE  NOCOMPRESS  KEEP_DUPLICATES ) ALLOW NONSCHEMA DISALLOW ANYSCHEMA ;
