--------------------------------------------------------
--  DDL for Table APPLICATIONS
--------------------------------------------------------

  CREATE TABLE "SDBMGR"."APPLICATIONS" 
   (	"ELA_GRP_ID" NUMBER(*,0), 
	"CASE_TYPE" VARCHAR2(100 BYTE), 
	"CASE_SUB_TYPE" VARCHAR2(100 BYTE), 
	"INITIAL_PROCESSING_TIME" NUMBER, 
	"CASE_CLOSED_DATE" DATE, 
	"WITHHELD_STATUS" VARCHAR2(30 BYTE), 
	"BATCH_ID" NUMBER(*,0), 
	"XML_DATA" "SDBMGR"."XMLTYPE", 
	"EXTERNAL_APPLICATION_ID" NUMBER(*,0), 
	"ALLOW_RELEASE_OF_BATCH_ID" NUMBER(*,0), 
	"WITHHELD_REASON_CODE" VARCHAR2(30 BYTE), 
	"ELA_ID" NUMBER
   ) ;
