--------------------------------------------------------
--  DDL for Table APPLICATIONS_FIV5411
--------------------------------------------------------

  CREATE TABLE "SAVEMGR"."APPLICATIONS_FIV5411" 
   (	"ELA_GRP_ID" NUMBER(*,0), 
	"CASE_TYPE" VARCHAR2(100 BYTE), 
	"CASE_SUB_TYPE" VARCHAR2(100 BYTE), 
	"INITIAL_PROCESSING_TIME" NUMBER, 
	"CASE_CLOSED_DATE" DATE, 
	"WITHHELD_STATUS" VARCHAR2(30 BYTE), 
	"BATCH_ID" NUMBER(*,0), 
	"XML_DATA" "SYS"."XMLTYPE" , 
	"EXTERNAL_APPLICATION_ID" NUMBER(*,0), 
	"ALLOW_RELEASE_OF_BATCH_ID" NUMBER(*,0), 
	"WITHHELD_REASON_CODE" VARCHAR2(30 BYTE), 
	"ELA_ID" NUMBER
   ) ;

   COMMENT ON TABLE "SAVEMGR"."APPLICATIONS_FIV5411"  IS 'Save of "SDBMGR"."APPLICATIONS" at 27-APR-2018 14:52:55';
  GRANT SELECT ON "SAVEMGR"."APPLICATIONS_FIV5411" TO "SDBMGR";
