--------------------------------------------------------
--  DDL for Table AUDIT_RATING
--------------------------------------------------------

  CREATE TABLE "WARP_OWNER"."AUDIT_RATING" 
   (	"CHANGE_TYPE" VARCHAR2(1 BYTE), 
	"CASE_ID" NUMBER(10,0), 
	"DETAIL_ID" NUMBER(10,0), 
	"CHANGE_DATE" DATE, 
	"CHANGE_BY" VARCHAR2(3 BYTE), 
	"RATING" VARCHAR2(20 BYTE), 
	"MODEL_NO_TYPE" VARCHAR2(150 BYTE), 
	"MANUFACTURER" VARCHAR2(150 BYTE), 
	"EMBARGO_STATUS" VARCHAR2(3 BYTE), 
	"LICENCE_REQUIRED" VARCHAR2(3 BYTE), 
	"PERSON_RATING" VARCHAR2(3 BYTE), 
	"MTCR" VARCHAR2(6 BYTE), 
	"NSG" VARCHAR2(6 BYTE), 
	"AUS_GROUP" VARCHAR2(6 BYTE), 
	"CHEM_WEAPON_FLAG" VARCHAR2(1 BYTE)
   ) ;
