--------------------------------------------------------
--  DDL for Table AUTO_REVIEW_ADVICE_AAC_MATRIX
--------------------------------------------------------

  CREATE TABLE "SPIREMGR"."AUTO_REVIEW_ADVICE_AAC_MATRIX" 
   (	"ID" NUMBER, 
	"ARR_ID" NUMBER, 
	"AAC_ID" NUMBER, 
	"ADVICE_TYPE" VARCHAR2(20 BYTE)
   ) ;
  GRANT SELECT ON "SPIREMGR"."AUTO_REVIEW_ADVICE_AAC_MATRIX" TO "APPENV";
  GRANT SELECT ON "SPIREMGR"."AUTO_REVIEW_ADVICE_AAC_MATRIX" TO "BPMMGR";
