--------------------------------------------------------
--  DDL for Table AUTO_REVIEW_RULES
--------------------------------------------------------

  CREATE TABLE "SPIREMGR"."AUTO_REVIEW_RULES" 
   (	"ID" NUMBER, 
	"AC_ID" NUMBER, 
	"COUNTRY_LIST_XML" "SYS"."XMLTYPE" , 
	"STATUS_CONTROL" VARCHAR2(1 BYTE), 
	"START_DATETIME" DATE, 
	"END_DATETIME" DATE, 
	"CREATED_BY_WUA_ID" NUMBER
   ) 
 XMLTYPE COLUMN "COUNTRY_LIST_XML" STORE AS SECUREFILE BINARY XML "AUTO_REVIEW_RULES_COUNTRIES"(DISABLE STORAGE IN ROW CHUNK 8192
  CACHE  NOCOMPRESS  KEEP_DUPLICATES ) ALLOW NONSCHEMA DISALLOW ANYSCHEMA ;
  GRANT REFERENCES ON "SPIREMGR"."AUTO_REVIEW_RULES" TO "XVIEWMGR";
  GRANT SELECT ON "SPIREMGR"."AUTO_REVIEW_RULES" TO "APPENV";
