--------------------------------------------------------
--  DDL for Table BPM_WB_ENTRIES_TEMP
--------------------------------------------------------

  CREATE GLOBAL TEMPORARY TABLE "BPMMGR"."BPM_WB_ENTRIES_TEMP" 
   (	"WB_TYPE" VARCHAR2(30 BYTE) DEFAULT 'WORK', 
	"CHECKBOX_SELECTED" VARCHAR2(5 BYTE) DEFAULT 'false', 
	"UREF_TYPE" VARCHAR2(6 BYTE), 
	"UREF_ID_COMPONENT" VARCHAR2(50 BYTE), 
	"WUA_ID" NUMBER(12,0), 
	"WBA_ID" NUMBER(12,0), 
	"ACTION_MNEM" VARCHAR2(200 BYTE), 
	"SELECTED_FLAG" VARCHAR2(1 BYTE), 
	"CATEGORY_NAME" VARCHAR2(40 BYTE), 
	"USER_COMMENT" VARCHAR2(200 BYTE), 
	"ACCESSED_DAYS_COUNT" NUMBER(12,0), 
	"USER_REMOVED_DATETIME" DATE, 
	"WORKBASKET_UREF" VARCHAR2(50 BYTE), 
	"ACTION_PROMPT" VARCHAR2(200 BYTE), 
	"LAST_ACCESSED_DATETIME" DATE, 
	"ACTION_ORDER" NUMBER(5,0), 
	"VIEWER_WUA_ID" NUMBER(12,0)
   ) ON COMMIT DELETE ROWS ;
