--------------------------------------------------------
--  DDL for Table BPM_LOG_STEP
--------------------------------------------------------

  CREATE TABLE "BPMMGR"."BPM_LOG_STEP" 
   (	"BLM_ID" NUMBER(20,0), 
	"STEP_NO" NUMBER(6,0), 
	"STEP_TIMESTAMP" TIMESTAMP (6), 
	"DESCRIPTION" VARCHAR2(4000 BYTE), 
	"XML_DATA" "SYS"."XMLTYPE" 
   ) 
 XMLTYPE COLUMN "XML_DATA" STORE AS SECUREFILE BINARY XML "BPM_LOG_STEP_XML"(ENABLE STORAGE IN ROW CHUNK 8192
  CACHE  NOCOMPRESS  KEEP_DUPLICATES ) ALLOW NONSCHEMA DISALLOW ANYSCHEMA ;
