--------------------------------------------------------
--  DDL for Table BUSINESS_PROCESS_DEFINITIONS_5
--------------------------------------------------------

  CREATE TABLE "SAVEMGR"."BUSINESS_PROCESS_DEFINITIONS_5" 
   (	"ID" NUMBER(12,0), 
	"BP_ID" NUMBER(12,0), 
	"START_DATETIME" DATE, 
	"END_DATETIME" DATE, 
	"XML_DATA" "SYS"."XMLTYPE" 
   ) ;

   COMMENT ON TABLE "SAVEMGR"."BUSINESS_PROCESS_DEFINITIONS_5"  IS 'Save of "BPMMGR"."BUSINESS_PROCESS_DEFINITIONS" at 09-SEP-2009 19:43:04';
  GRANT SELECT ON "SAVEMGR"."BUSINESS_PROCESS_DEFINITIONS_5" TO "BPMMGR";
