--------------------------------------------------------
--  DDL for Table BUSINESS_PROCESS_DEFINITIONS_4
--------------------------------------------------------

  CREATE TABLE "SAVEMGR"."BUSINESS_PROCESS_DEFINITIONS_4" 
   (	"ID" NUMBER(12,0), 
	"BP_ID" NUMBER(12,0), 
	"START_DATETIME" DATE, 
	"END_DATETIME" DATE, 
	"XML_DATA" "SYS"."XMLTYPE" 
   ) ;

   COMMENT ON TABLE "SAVEMGR"."BUSINESS_PROCESS_DEFINITIONS_4"  IS 'Save of "BPMMGR"."BUSINESS_PROCESS_DEFINITIONS" at 09-SEP-2009 19:34:20';
  GRANT SELECT ON "SAVEMGR"."BUSINESS_PROCESS_DEFINITIONS_4" TO "BPMMGR";
