--------------------------------------------------------
--  DDL for Table BUSINESS_PROCESS_DEFINITIONS_3
--------------------------------------------------------

  CREATE TABLE "SAVEMGR"."BUSINESS_PROCESS_DEFINITIONS_3" 
   (	"ID" NUMBER(12,0), 
	"BP_ID" NUMBER(12,0), 
	"START_DATETIME" DATE, 
	"END_DATETIME" DATE, 
	"XML_DATA" "SYS"."XMLTYPE" 
   ) ;

   COMMENT ON TABLE "SAVEMGR"."BUSINESS_PROCESS_DEFINITIONS_3"  IS 'Save of "BPMMGR"."BUSINESS_PROCESS_DEFINITIONS" at 31-JUL-2009 19:27:24';
  GRANT SELECT ON "SAVEMGR"."BUSINESS_PROCESS_DEFINITIONS_3" TO "BPMMGR";
