--------------------------------------------------------
--  DDL for Table BUSINESS_PROCESS_DEFINITIONS_8
--------------------------------------------------------

  CREATE TABLE "SAVEMGR"."BUSINESS_PROCESS_DEFINITIONS_8" 
   (	"ID" NUMBER(12,0), 
	"BP_ID" NUMBER(12,0), 
	"START_DATETIME" DATE, 
	"END_DATETIME" DATE, 
	"XML_DATA" "SYS"."XMLTYPE" 
   ) ;

   COMMENT ON TABLE "SAVEMGR"."BUSINESS_PROCESS_DEFINITIONS_8"  IS 'Save of "BPMMGR"."BUSINESS_PROCESS_DEFINITIONS" at 19-OCT-2009 20:57:14';
  GRANT SELECT ON "SAVEMGR"."BUSINESS_PROCESS_DEFINITIONS_8" TO "BPMMGR";
