--------------------------------------------------------
--  DDL for Table BUSINESS_ASSIGNMENT_DETAILS
--------------------------------------------------------

  CREATE TABLE "SAVEMGR"."BUSINESS_ASSIGNMENT_DETAILS" 
   (	"ID" NUMBER(12,0), 
	"BAS_ID" NUMBER(12,0), 
	"START_DATETIME" DATE, 
	"END_DATETIME" DATE, 
	"DELEGATION" VARCHAR2(100 BYTE), 
	"XML_DATA" "SYS"."XMLTYPE" , 
	"UPDATE_WUA_ID" NUMBER(12,0), 
	"BP_ID" NUMBER(12,0)
   ) ;

   COMMENT ON TABLE "SAVEMGR"."BUSINESS_ASSIGNMENT_DETAILS"  IS 'Save of "BPMMGR"."BUSINESS_ASSIGNMENT_DETAILS" at 24-APR-2009 23:20:26';
  GRANT SELECT ON "SAVEMGR"."BUSINESS_ASSIGNMENT_DETAILS" TO "BPMMGR";
