--------------------------------------------------------
--  DDL for Table BUSINESS_PROCESS_DEFINITION_15
--------------------------------------------------------

  CREATE TABLE "SAVEMGR"."BUSINESS_PROCESS_DEFINITION_15" 
   (	"ID" NUMBER(12,0), 
	"BP_ID" NUMBER(12,0), 
	"START_DATETIME" DATE, 
	"END_DATETIME" DATE, 
	"XML_DATA" "SYS"."XMLTYPE" 
   ) ;

   COMMENT ON TABLE "SAVEMGR"."BUSINESS_PROCESS_DEFINITION_15"  IS 'Save of "BPMMGR"."BUSINESS_PROCESS_DEFINITIONS" at 22-FEB-2010 21:17:13';
  GRANT SELECT ON "SAVEMGR"."BUSINESS_PROCESS_DEFINITION_15" TO "BPMMGR";
