--------------------------------------------------------
--  DDL for Table BUSINESS_ACTIVITIES
--------------------------------------------------------

  CREATE TABLE "BPMMGR"."BUSINESS_ACTIVITIES" 
   (	"ID" NUMBER(12,0), 
	"BT_ID" NUMBER(12,0), 
	"XML_DATA" "SYS"."XMLTYPE" , 
	"START_OPERATION_ID" NUMBER(12,0), 
	"START_DATETIME" DATE, 
	"END_OPERATION_ID" NUMBER(12,0), 
	"END_DATETIME" DATE
   ) ;
  GRANT SELECT ON "BPMMGR"."BUSINESS_ACTIVITIES" TO "SPMIGUSER";
  GRANT REFERENCES ON "BPMMGR"."BUSINESS_ACTIVITIES" TO "XVIEWMGR";
  GRANT SELECT ON "BPMMGR"."BUSINESS_ACTIVITIES" TO "DECMGR";
  GRANT UPDATE ON "BPMMGR"."BUSINESS_ACTIVITIES" TO "APPENV";
  GRANT SELECT ON "BPMMGR"."BUSINESS_ACTIVITIES" TO "APPENV";
  GRANT INSERT ON "BPMMGR"."BUSINESS_ACTIVITIES" TO "APPENV";
