--------------------------------------------------------
--  DDL for Table BUSINESS_PROCESS_DEFINITIONS_2
--------------------------------------------------------

  CREATE TABLE "SAVEMGR"."BUSINESS_PROCESS_DEFINITIONS_2" 
   (	"ID" NUMBER(12,0), 
	"BP_ID" NUMBER(12,0), 
	"START_DATETIME" DATE, 
	"END_DATETIME" DATE, 
	"XML_DATA" "SYS"."XMLTYPE" 
   ) ;

   COMMENT ON TABLE "SAVEMGR"."BUSINESS_PROCESS_DEFINITIONS_2"  IS 'Save of "BPMMGR"."BUSINESS_PROCESS_DEFINITIONS" at 24-JUL-2009 20:08:41';
  GRANT SELECT ON "SAVEMGR"."BUSINESS_PROCESS_DEFINITIONS_2" TO "BPMMGR";
