--------------------------------------------------------
--  DDL for Table BUSINESS_CONTEXTS
--------------------------------------------------------

  CREATE TABLE "BPMMGR"."BUSINESS_CONTEXTS" 
   (	"ID" NUMBER(12,0), 
	"PARENT_BC_ID" NUMBER(12,0), 
	"XML_DATA" "BPMMGR"."XMLTYPE"
   ) ;
  GRANT SELECT ON "BPMMGR"."BUSINESS_CONTEXTS" TO "SPIREMGR";
  GRANT UPDATE ON "BPMMGR"."BUSINESS_CONTEXTS" TO "BISAPIMGR";
  GRANT SELECT ON "BPMMGR"."BUSINESS_CONTEXTS" TO "BISAPIMGR";
  GRANT UPDATE ON "BPMMGR"."BUSINESS_CONTEXTS" TO "PVEXMGR";
  GRANT SELECT ON "BPMMGR"."BUSINESS_CONTEXTS" TO "PVEXMGR";
  GRANT REFERENCES ON "BPMMGR"."BUSINESS_CONTEXTS" TO "XVIEWMGR";
  GRANT SELECT ON "BPMMGR"."BUSINESS_CONTEXTS" TO "APPENV";
