--------------------------------------------------------
--  DDL for Table BUSINESS_ASSIGNMENT_DETAILS
--------------------------------------------------------

  CREATE TABLE "BPMMGR"."BUSINESS_ASSIGNMENT_DETAILS" 
   (	"ID" NUMBER(12,0), 
	"BAS_ID" NUMBER(12,0), 
	"START_DATETIME" DATE, 
	"END_DATETIME" DATE, 
	"DELEGATION" VARCHAR2(100 BYTE), 
	"XML_DATA" "BPMMGR"."XMLTYPE", 
	"UPDATE_WUA_ID" NUMBER(12,0), 
	"BP_ID" NUMBER(12,0)
   ) ;
  GRANT SELECT ON "BPMMGR"."BUSINESS_ASSIGNMENT_DETAILS" TO "BISAPIMGR" WITH GRANT OPTION;
  GRANT SELECT ON "BPMMGR"."BUSINESS_ASSIGNMENT_DETAILS" TO "APPENV";
  GRANT REFERENCES ON "BPMMGR"."BUSINESS_ASSIGNMENT_DETAILS" TO "XVIEWMGR";
  GRANT SELECT ON "BPMMGR"."BUSINESS_ASSIGNMENT_DETAILS" TO "SPIREMGR";
