--------------------------------------------------------
--  DDL for Table BUSINESS_PROCESS_DEFINITIONS_7
--------------------------------------------------------

  CREATE TABLE "SAVEMGR"."BUSINESS_PROCESS_DEFINITIONS_7" 
   (	"ID" NUMBER(12,0), 
	"BP_ID" NUMBER(12,0), 
	"START_DATETIME" DATE, 
	"END_DATETIME" DATE, 
	"XML_DATA" "SYS"."XMLTYPE" 
   ) ;

   COMMENT ON TABLE "SAVEMGR"."BUSINESS_PROCESS_DEFINITIONS_7"  IS 'Save of "BPMMGR"."BUSINESS_PROCESS_DEFINITIONS" at 19-OCT-2009 20:40:22';
  GRANT SELECT ON "SAVEMGR"."BUSINESS_PROCESS_DEFINITIONS_7" TO "BPMMGR";
