--------------------------------------------------------
--  DDL for Table BUSINESS_UNAVAILABLE_DETAILS
--------------------------------------------------------

  CREATE TABLE "BPMMGR"."BUSINESS_UNAVAILABLE_DETAILS" 
   (	"ID" NUMBER(12,0), 
	"BU_ID" NUMBER(12,0), 
	"ENTRY_ID" NUMBER(12,0), 
	"TYPE" VARCHAR2(30 BYTE), 
	"STATUS" VARCHAR2(30 BYTE), 
	"CANCEL_REASON" VARCHAR2(200 BYTE), 
	"SCOPE_UREF" VARCHAR2(100 BYTE), 
	"START_INCLUSIVE_DATEONLY" DATE, 
	"END_INCLUSIVE_DATEONLY" DATE, 
	"EXCEPT_BETWEEN_FROM_TIME" VARCHAR2(4 BYTE), 
	"EXCEPT_BETWEEN_TO_TIME" VARCHAR2(4 BYTE), 
	"COMMENTS" VARCHAR2(2000 BYTE), 
	"CREATED_BY" VARCHAR2(200 BYTE), 
	"CREATED_DATETIME" DATE, 
	"UPDATED_BY" VARCHAR2(200 BYTE), 
	"UPDATED_DATETIME" DATE
   ) ;
  GRANT SELECT ON "BPMMGR"."BUSINESS_UNAVAILABLE_DETAILS" TO "APPENV";
