--------------------------------------------------------
--  DDL for Table BUSINESS_PROCESS_DEFINITIONS_6
--------------------------------------------------------

  CREATE TABLE "SAVEMGR"."BUSINESS_PROCESS_DEFINITIONS_6" 
   (	"ID" NUMBER(12,0), 
	"BP_ID" NUMBER(12,0), 
	"START_DATETIME" DATE, 
	"END_DATETIME" DATE, 
	"XML_DATA" "SYS"."XMLTYPE" 
   ) ;

   COMMENT ON TABLE "SAVEMGR"."BUSINESS_PROCESS_DEFINITIONS_6"  IS 'Save of "BPMMGR"."BUSINESS_PROCESS_DEFINITIONS" at 09-SEP-2009 19:45:07';
  GRANT SELECT ON "SAVEMGR"."BUSINESS_PROCESS_DEFINITIONS_6" TO "BPMMGR";
