--------------------------------------------------------
--  DDL for Table BUSINESS_PROCESS_DEFINITION_10
--------------------------------------------------------

  CREATE TABLE "SAVEMGR"."BUSINESS_PROCESS_DEFINITION_10" 
   (	"ID" NUMBER(12,0), 
	"BP_ID" NUMBER(12,0), 
	"START_DATETIME" DATE, 
	"END_DATETIME" DATE, 
	"XML_DATA" "SYS"."XMLTYPE" 
   ) ;

   COMMENT ON TABLE "SAVEMGR"."BUSINESS_PROCESS_DEFINITION_10"  IS 'Save of "BPMMGR"."BUSINESS_PROCESS_DEFINITIONS" at 29-NOV-2009 11:47:16';
  GRANT SELECT ON "SAVEMGR"."BUSINESS_PROCESS_DEFINITION_10" TO "BPMMGR";
