--------------------------------------------------------
--  DDL for Table BUSINESS_PROCESS_DEFINITIONS
--------------------------------------------------------

  CREATE TABLE "BPMMGR"."BUSINESS_PROCESS_DEFINITIONS" 
   (	"ID" NUMBER(12,0), 
	"BP_ID" NUMBER(12,0), 
	"START_DATETIME" DATE, 
	"END_DATETIME" DATE, 
	"XML_DATA" "SYS"."XMLTYPE" 
   ) ;
  GRANT REFERENCES ON "BPMMGR"."BUSINESS_PROCESS_DEFINITIONS" TO "XVIEWMGR";
  GRANT UPDATE ON "BPMMGR"."BUSINESS_PROCESS_DEFINITIONS" TO "APPENV";
  GRANT SELECT ON "BPMMGR"."BUSINESS_PROCESS_DEFINITIONS" TO "APPENV";
