--------------------------------------------------------
--  DDL for Table BUSINESS_PROCESS_DEFINITIONS
--------------------------------------------------------

  CREATE TABLE "SAVEMGR"."BUSINESS_PROCESS_DEFINITIONS" 
   (	"ID" NUMBER(12,0), 
	"BP_ID" NUMBER(12,0), 
	"START_DATETIME" DATE, 
	"END_DATETIME" DATE, 
	"XML_DATA" "SYS"."XMLTYPE" 
   ) ;

   COMMENT ON TABLE "SAVEMGR"."BUSINESS_PROCESS_DEFINITIONS"  IS 'Save of "BPMMGR"."BUSINESS_PROCESS_DEFINITIONS" at 08-OCT-2007 06:27:14';
  GRANT SELECT ON "SAVEMGR"."BUSINESS_PROCESS_DEFINITIONS" TO "BPMMGR";
