--------------------------------------------------------
--  DDL for Table BUSINESS_PROCESS_DEFINITION_12
--------------------------------------------------------

  CREATE TABLE "SAVEMGR"."BUSINESS_PROCESS_DEFINITION_12" 
   (	"ID" NUMBER(12,0), 
	"BP_ID" NUMBER(12,0), 
	"START_DATETIME" DATE, 
	"END_DATETIME" DATE, 
	"XML_DATA" "SYS"."XMLTYPE" 
   ) ;

   COMMENT ON TABLE "SAVEMGR"."BUSINESS_PROCESS_DEFINITION_12"  IS 'Save of "BPMMGR"."BUSINESS_PROCESS_DEFINITIONS" at 29-JAN-2010 20:25:55';
  GRANT SELECT ON "SAVEMGR"."BUSINESS_PROCESS_DEFINITION_12" TO "BPMMGR";
