--------------------------------------------------------
--  DDL for Table BUSINESS_PROCESSES
--------------------------------------------------------

  CREATE TABLE "BPMMGR"."BUSINESS_PROCESSES" 
   (	"ID" NUMBER(12,0), 
	"SHORT_NAME" VARCHAR2(30 BYTE)
   ) ;
  GRANT SELECT ON "BPMMGR"."BUSINESS_PROCESSES" TO "BISAPIMGR" WITH GRANT OPTION;
  GRANT SELECT ON "BPMMGR"."BUSINESS_PROCESSES" TO "SPIREMGR";
  GRANT SELECT ON "BPMMGR"."BUSINESS_PROCESSES" TO "APPENV";
