--------------------------------------------------------
--  DDL for Table BUSINESS_PROCESS_DEFINITION_13
--------------------------------------------------------

  CREATE TABLE "SAVEMGR"."BUSINESS_PROCESS_DEFINITION_13" 
   (	"ID" NUMBER(12,0), 
	"BP_ID" NUMBER(12,0), 
	"START_DATETIME" DATE, 
	"END_DATETIME" DATE, 
	"XML_DATA" "SYS"."XMLTYPE" 
   ) ;

   COMMENT ON TABLE "SAVEMGR"."BUSINESS_PROCESS_DEFINITION_13"  IS 'Save of "BPMMGR"."BUSINESS_PROCESS_DEFINITIONS" at 22-FEB-2010 19:00:54';
  GRANT SELECT ON "SAVEMGR"."BUSINESS_PROCESS_DEFINITION_13" TO "BPMMGR";
