--------------------------------------------------------
--  DDL for Table BUSINESS_ROUTINE_ASSIGNMENTS
--------------------------------------------------------

  CREATE TABLE "BPMMGR"."BUSINESS_ROUTINE_ASSIGNMENTS" 
   (	"ID" NUMBER(12,0), 
	"BRC_ID" NUMBER(12,0), 
	"ASSIGNMENT" VARCHAR2(100 BYTE), 
	"BAS_ID" NUMBER(12,0)
   ) ;
  GRANT SELECT ON "BPMMGR"."BUSINESS_ROUTINE_ASSIGNMENTS" TO "BISAPIMGR" WITH GRANT OPTION;
  GRANT SELECT ON "BPMMGR"."BUSINESS_ROUTINE_ASSIGNMENTS" TO "APPENV";
  GRANT SELECT ON "BPMMGR"."BUSINESS_ROUTINE_ASSIGNMENTS" TO "SPIREMGR";
