--------------------------------------------------------
--  DDL for Table CLCAS_WITHDRAW_LOG
--------------------------------------------------------

  CREATE TABLE "SPIREMGR"."CLCAS_WITHDRAW_LOG" 
   (	"ELA_ID" NUMBER, 
	"CASE_REF" VARCHAR2(4000 BYTE), 
	"WITHDRAW_STATUS" VARCHAR2(20 BYTE), 
	"CONTEXT_XML" "SYS"."XMLTYPE" , 
	"ERROR_MSG" CLOB
   ) 
 XMLTYPE COLUMN "CONTEXT_XML" STORE AS SECUREFILE BINARY XML "CLC_WITHDRAW_CONTEXT_XML"(DISABLE STORAGE IN ROW CHUNK 8192
  CACHE  NOCOMPRESS  KEEP_DUPLICATES ) ALLOW NONSCHEMA DISALLOW ANYSCHEMA ;
