--------------------------------------------------------
--  DDL for Table COMPLIANCE_ACTIVITIES
--------------------------------------------------------

  CREATE TABLE "SPIREMGR"."COMPLIANCE_ACTIVITIES" 
   (	"ID" NUMBER(12,0), 
	"VISIT_ID" NUMBER
   ) ;
  GRANT SELECT ON "SPIREMGR"."COMPLIANCE_ACTIVITIES" TO "APPENV";
  GRANT REFERENCES ON "SPIREMGR"."COMPLIANCE_ACTIVITIES" TO "BPMMGR";
  GRANT SELECT ON "SPIREMGR"."COMPLIANCE_ACTIVITIES" TO "BPMMGR";
  GRANT INDEX ON "SPIREMGR"."COMPLIANCE_ACTIVITIES" TO "BPMMGR";
