--------------------------------------------------------
--  DDL for Table COMPLIANCE_VISITS
--------------------------------------------------------

  CREATE TABLE "SPIREMGR"."COMPLIANCE_VISITS" 
   (	"ID" NUMBER, 
	"XML_DATA" "SYS"."XMLTYPE" 
   ) ;
  GRANT REFERENCES ON "SPIREMGR"."COMPLIANCE_VISITS" TO "BPMMGR";
  GRANT SELECT ON "SPIREMGR"."COMPLIANCE_VISITS" TO "BPMMGR";
  GRANT INDEX ON "SPIREMGR"."COMPLIANCE_VISITS" TO "BPMMGR";
  GRANT UPDATE ON "SPIREMGR"."COMPLIANCE_VISITS" TO "APPENV";
  GRANT SELECT ON "SPIREMGR"."COMPLIANCE_VISITS" TO "APPENV";
  GRANT REFERENCES ON "SPIREMGR"."COMPLIANCE_VISITS" TO "XVIEWMGR";
