--------------------------------------------------------
--  DDL for Table COMPLIANCE_PROFILE
--------------------------------------------------------

  CREATE TABLE "SPIREMGR"."COMPLIANCE_PROFILE" 
   (	"ID" NUMBER, 
	"SITE_ID" NUMBER, 
	"COMPLIANCE_LEVEL" VARCHAR2(20 BYTE), 
	"REASON" VARCHAR2(1000 BYTE), 
	"START_DATETIME" DATE, 
	"END_DATETIME" DATE, 
	"STATUS" VARCHAR2(20 BYTE), 
	"SET_BY_NAME" VARCHAR2(100 BYTE), 
	"SET_BY_WUA_ID" NUMBER, 
	"APPROVED_BY_NAME" VARCHAR2(100 BYTE), 
	"APPROVED_BY_WUA_ID" NUMBER
   ) ;
