--------------------------------------------------------
--  DDL for Table COMPLIANCE_PROFILE
--------------------------------------------------------

  CREATE TABLE "SAVEMGR"."COMPLIANCE_PROFILE" 
   (	"ID" NUMBER, 
	"SITE_ID" NUMBER, 
	"COMPLIANCE_LEVEL" VARCHAR2(20 BYTE), 
	"REASON" VARCHAR2(1000 BYTE), 
	"START_DATETIME" DATE, 
	"END_DATETIME" DATE, 
	"WUA_ID" NUMBER, 
	"STATUS" VARCHAR2(20 BYTE), 
	"SET_BY_NAME" VARCHAR2(100 BYTE), 
	"SET_BY_WUA_ID" NUMBER, 
	"APPROVED_BY_NAME" VARCHAR2(100 BYTE), 
	"APPROVED_BY_WUA_ID" NUMBER
   ) ;

   COMMENT ON TABLE "SAVEMGR"."COMPLIANCE_PROFILE"  IS 'Save of "SPIREMGR"."COMPLIANCE_PROFILE" at 05-JUL-2008 00:24:48';
  GRANT SELECT ON "SAVEMGR"."COMPLIANCE_PROFILE" TO "SPIREMGR";
