--------------------------------------------------------
--  DDL for Table CONFIG_PARAMETERSP3800
--------------------------------------------------------

  CREATE TABLE "SAVEMGR"."CONFIG_PARAMETERSP3800" 
   (	"PARAM_NAME" VARCHAR2(32 BYTE), 
	"PARAM_DESCRIPTION" VARCHAR2(240 BYTE), 
	"PARAM_VALUE" VARCHAR2(4000 BYTE), 
	"LAST_DML_DATE" DATE, 
	"LAST_DML_BY" VARCHAR2(30 BYTE)
   ) ;

   COMMENT ON TABLE "SAVEMGR"."CONFIG_PARAMETERSP3800"  IS 'Save of "PORTALMGR"."CONFIG_PARAMETERS" at 05-AUG-2007 17:32:59';
  GRANT SELECT ON "SAVEMGR"."CONFIG_PARAMETERSP3800" TO "PORTALMGR";
