--------------------------------------------------------
--  DDL for Table CONS
--------------------------------------------------------

  CREATE TABLE "WARP_OWNER"."CONS" 
   (	"DETAIL_ID" NUMBER(10,0), 
	"CASE_ID" NUMBER(10,0), 
	"MODEL_NO_TYPE" VARCHAR2(150 BYTE), 
	"MANUFACTURER" VARCHAR2(150 BYTE), 
	"LIST_ITEM" VARCHAR2(3 BYTE), 
	"ITEM" VARCHAR2(4 BYTE), 
	"SUB_ITEM" VARCHAR2(10 BYTE), 
	"EMBARGO_STATUS" VARCHAR2(3 BYTE), 
	"LICENCE_REQUIRED" VARCHAR2(3 BYTE), 
	"PERSON_RATING" VARCHAR2(3 BYTE), 
	"MTCR" VARCHAR2(6 BYTE), 
	"NSG" VARCHAR2(6 BYTE), 
	"AUS_GROUP" VARCHAR2(6 BYTE), 
	"DATE_RATED" DATE, 
	"CHEM_WEAPON_FLAG" VARCHAR2(1 BYTE)
   ) ;
