--------------------------------------------------------
--  DDL for Table COUNTRY_GROUPS
--------------------------------------------------------

  CREATE TABLE "SDBPUBMGR"."COUNTRY_GROUPS" 
   (	"ID" NUMBER(*,0), 
	 CONSTRAINT "COUNTRY_GROUPS_PK" PRIMARY KEY ("ID") ENABLE
   ) ORGANIZATION INDEX NOCOMPRESS ;
  GRANT SELECT ON "SDBPUBMGR"."COUNTRY_GROUPS" TO "SDBMGR";
  GRANT INSERT ON "SDBPUBMGR"."COUNTRY_GROUPS" TO "SDBMGR";
  GRANT DELETE ON "SDBPUBMGR"."COUNTRY_GROUPS" TO "SDBMGR";
