--------------------------------------------------------
--  DDL for Table COUNTRY_LOADER_TEMP
--------------------------------------------------------

  CREATE TABLE "BPMMGR"."COUNTRY_LOADER_TEMP" 
   (	"COUNTRY_NAME" VARCHAR2(200 BYTE), 
	"COUNTRY_COMMENTS" VARCHAR2(400 BYTE), 
	"HMRC_CODE" VARCHAR2(20 BYTE), 
	"SFE_GREEN_LIST" VARCHAR2(1 BYTE) DEFAULT 'N', 
	"SFE_GREY_LIST" VARCHAR2(1 BYTE) DEFAULT 'N', 
	"SFE_RED_LIST" VARCHAR2(1 BYTE) DEFAULT 'N', 
	"RANGE_8_REVIEW" VARCHAR2(1 BYTE) DEFAULT 'N', 
	"CGEA" VARCHAR2(1 BYTE) DEFAULT 'N', 
	"WMD" VARCHAR2(1 BYTE) DEFAULT 'N', 
	"EU" VARCHAR2(1 BYTE) DEFAULT 'N', 
	"MEU" VARCHAR2(1 BYTE) DEFAULT 'N', 
	"COMMITMENTS" VARCHAR2(1 BYTE) DEFAULT 'N', 
	"RAD_SOURCES" VARCHAR2(1 BYTE) DEFAULT 'N', 
	"STATUS" VARCHAR2(20 BYTE) DEFAULT 'NEW', 
	"UPDATED_DATE" DATE DEFAULT SYSDATE, 
	"OLD_COUNTRY_NAME" VARCHAR2(200 BYTE)
   ) ;
