--------------------------------------------------------
--  DDL for Table COUNTRY_RESTRICTIONS
--------------------------------------------------------

  CREATE TABLE "SPIREMGR"."COUNTRY_RESTRICTIONS" 
   (	"ID" NUMBER, 
	"SHORT_CODE" VARCHAR2(30 BYTE), 
	"RESTRICTION_TYPE" VARCHAR2(20 BYTE), 
	"COUNTRY_ID" NUMBER, 
	"COUNTRY_SET_ID" VARCHAR2(15 BYTE), 
	"TITLE" VARCHAR2(200 BYTE), 
	"DESCRIPTION" VARCHAR2(1000 BYTE), 
	"START_DATETIME" DATE, 
	"END_DATETIME" DATE, 
	"LEGISLATION" VARCHAR2(500 BYTE), 
	"DESTINATIONS" VARCHAR2(500 BYTE)
   ) ;
