--------------------------------------------------------
--  DDL for Table DATAPATCH_SAR_MOVE14991
--------------------------------------------------------

  CREATE TABLE "SAVEMGR"."DATAPATCH_SAR_MOVE14991" 
   (	"APP_DETAIL_ID" NUMBER, 
	"CASE_DETAIL_ID" NUMBER, 
	"ELA_ID" NUMBER, 
	"DTI_REF" VARCHAR2(100 BYTE), 
	"CASE_SAR" NUMBER, 
	"CASE_SITE" NUMBER, 
	"APP_SAR" NUMBER, 
	"APP_SITE" NUMBER, 
	"APP_XML" "SYS"."XMLTYPE" 
   ) ;

   COMMENT ON TABLE "SAVEMGR"."DATAPATCH_SAR_MOVE14991"  IS 'Save of "SPIREMGR"."DATAPATCH_SAR_MOVE14991" at 30-MAY-2014 15:17:22';
  GRANT SELECT ON "SAVEMGR"."DATAPATCH_SAR_MOVE14991" TO "SPIREMGR";
