--------------------------------------------------------
--  DDL for Table DATAPATCH_SAR_MOVE12182
--------------------------------------------------------

  CREATE TABLE "SAVEMGR"."DATAPATCH_SAR_MOVE12182" 
   (	"APP_DETAIL_ID" NUMBER, 
	"CASE_DETAIL_ID" NUMBER, 
	"ELA_ID" NUMBER, 
	"DTI_REF" VARCHAR2(100 BYTE), 
	"CASE_SAR" NUMBER, 
	"CASE_SITE" NUMBER, 
	"APP_SAR" NUMBER, 
	"APP_SITE" NUMBER, 
	"APP_XML" "SYS"."XMLTYPE" 
   ) ;

   COMMENT ON TABLE "SAVEMGR"."DATAPATCH_SAR_MOVE12182"  IS 'Save of "SPIREMGR"."DATAPATCH_SAR_MOVE12182" at 22-APR-2014 16:46:24';
  GRANT SELECT ON "SAVEMGR"."DATAPATCH_SAR_MOVE12182" TO "SPIREMGR";
