--------------------------------------------------------
--  DDL for Table DATAPATCH_SAR_MOVE6432
--------------------------------------------------------

  CREATE TABLE "SAVEMGR"."DATAPATCH_SAR_MOVE6432" 
   (	"APP_DETAIL_ID" NUMBER, 
	"CASE_DETAIL_ID" NUMBER, 
	"ELA_ID" NUMBER, 
	"DTI_REF" VARCHAR2(100 BYTE), 
	"CASE_SAR" NUMBER, 
	"CASE_SITE" NUMBER, 
	"APP_SAR" NUMBER, 
	"APP_SITE" NUMBER, 
	"APP_XML" "SYS"."XMLTYPE" 
   ) ;

   COMMENT ON TABLE "SAVEMGR"."DATAPATCH_SAR_MOVE6432"  IS 'Save of "SPIREMGR"."DATAPATCH_SAR_MOVE6432" at 30-JAN-2018 11:17:54';
  GRANT SELECT ON "SAVEMGR"."DATAPATCH_SAR_MOVE6432" TO "SPIREMGR";
