--------------------------------------------------------
--  DDL for Table DATAPATCH_SAR_MOVE2333
--------------------------------------------------------

  CREATE TABLE "SAVEMGR"."DATAPATCH_SAR_MOVE2333" 
   (	"APP_DETAIL_ID" NUMBER, 
	"CASE_DETAIL_ID" NUMBER, 
	"ELA_ID" NUMBER, 
	"DTI_REF" VARCHAR2(100 BYTE), 
	"CASE_SAR" NUMBER, 
	"CASE_SITE" NUMBER, 
	"APP_SAR" NUMBER, 
	"APP_SITE" NUMBER, 
	"APP_XML" "SYS"."XMLTYPE" 
   ) ;

   COMMENT ON TABLE "SAVEMGR"."DATAPATCH_SAR_MOVE2333"  IS 'Save of "SPIREMGR"."DATAPATCH_SAR_MOVE2333" at 14-FEB-2014 14:44:48';
  GRANT SELECT ON "SAVEMGR"."DATAPATCH_SAR_MOVE2333" TO "SPIREMGR";
