--------------------------------------------------------
--  DDL for Table DATAPATCH_SAR_MOVE11023
--------------------------------------------------------

  CREATE TABLE "SAVEMGR"."DATAPATCH_SAR_MOVE11023" 
   (	"APP_DETAIL_ID" NUMBER, 
	"CASE_DETAIL_ID" NUMBER, 
	"ELA_ID" NUMBER, 
	"DTI_REF" VARCHAR2(100 BYTE), 
	"CASE_SAR" NUMBER, 
	"CASE_SITE" NUMBER, 
	"APP_SAR" NUMBER, 
	"APP_SITE" NUMBER, 
	"APP_XML" "SYS"."XMLTYPE" 
   ) ;

   COMMENT ON TABLE "SAVEMGR"."DATAPATCH_SAR_MOVE11023"  IS 'Save of "SPIREMGR"."DATAPATCH_SAR_MOVE11023" at 06-MAR-2014 16:18:50';
  GRANT SELECT ON "SAVEMGR"."DATAPATCH_SAR_MOVE11023" TO "SPIREMGR";
