--------------------------------------------------------
--  DDL for Table DATAPATCH_SAR_MOVE14611
--------------------------------------------------------

  CREATE TABLE "SAVEMGR"."DATAPATCH_SAR_MOVE14611" 
   (	"APP_DETAIL_ID" NUMBER, 
	"CASE_DETAIL_ID" NUMBER, 
	"ELA_ID" NUMBER, 
	"DTI_REF" VARCHAR2(100 BYTE), 
	"CASE_SAR" NUMBER, 
	"CASE_SITE" NUMBER, 
	"APP_SAR" NUMBER, 
	"APP_SITE" NUMBER, 
	"APP_XML" "SYS"."XMLTYPE" 
   ) ;

   COMMENT ON TABLE "SAVEMGR"."DATAPATCH_SAR_MOVE14611"  IS 'Save of "SPIREMGR"."DATAPATCH_SAR_MOVE14611" at 04-DEC-2013 11:58:35';
  GRANT SELECT ON "SAVEMGR"."DATAPATCH_SAR_MOVE14611" TO "SPIREMGR";
