--------------------------------------------------------
--  DDL for Table DATAPATCH_SAR_MOVE7495
--------------------------------------------------------

  CREATE TABLE "SAVEMGR"."DATAPATCH_SAR_MOVE7495" 
   (	"APP_DETAIL_ID" NUMBER, 
	"CASE_DETAIL_ID" NUMBER, 
	"ELA_ID" NUMBER, 
	"DTI_REF" VARCHAR2(100 BYTE), 
	"CASE_SAR" NUMBER, 
	"CASE_SITE" NUMBER, 
	"APP_SAR" NUMBER, 
	"APP_SITE" NUMBER, 
	"APP_XML" "SYS"."XMLTYPE" 
   ) ;

   COMMENT ON TABLE "SAVEMGR"."DATAPATCH_SAR_MOVE7495"  IS 'Save of "SPIREMGR"."DATAPATCH_SAR_MOVE7495" at 19-DEC-2013 16:11:41';
  GRANT SELECT ON "SAVEMGR"."DATAPATCH_SAR_MOVE7495" TO "SPIREMGR";
