--------------------------------------------------------
--  DDL for Table DATAPATCH_SAR_MOVE13302
--------------------------------------------------------

  CREATE TABLE "SAVEMGR"."DATAPATCH_SAR_MOVE13302" 
   (	"APP_DETAIL_ID" NUMBER, 
	"CASE_DETAIL_ID" NUMBER, 
	"ELA_ID" NUMBER, 
	"DTI_REF" VARCHAR2(100 BYTE), 
	"CASE_SAR" NUMBER, 
	"CASE_SITE" NUMBER, 
	"APP_SAR" NUMBER, 
	"APP_SITE" NUMBER, 
	"APP_XML" "SYS"."XMLTYPE" 
   ) ;

   COMMENT ON TABLE "SAVEMGR"."DATAPATCH_SAR_MOVE13302"  IS 'Save of "SPIREMGR"."DATAPATCH_SAR_MOVE13302" at 20-MAY-2016 10:32:09';
  GRANT SELECT ON "SAVEMGR"."DATAPATCH_SAR_MOVE13302" TO "SPIREMGR";
