--------------------------------------------------------
--  DDL for Table DATAPATCH_SAR_MOVE21482
--------------------------------------------------------

  CREATE TABLE "SAVEMGR"."DATAPATCH_SAR_MOVE21482" 
   (	"APP_DETAIL_ID" NUMBER, 
	"CASE_DETAIL_ID" NUMBER, 
	"ELA_ID" NUMBER, 
	"DTI_REF" VARCHAR2(100 BYTE), 
	"CASE_SAR" NUMBER, 
	"CASE_SITE" NUMBER, 
	"APP_SAR" NUMBER, 
	"APP_SITE" NUMBER, 
	"APP_XML" "SYS"."XMLTYPE" 
   ) ;

   COMMENT ON TABLE "SAVEMGR"."DATAPATCH_SAR_MOVE21482"  IS 'Save of "SPIREMGR"."DATAPATCH_SAR_MOVE21482" at 06-NOV-2019 10:24:15';
  GRANT SELECT ON "SAVEMGR"."DATAPATCH_SAR_MOVE21482" TO "SPIREMGR";
