--------------------------------------------------------
--  DDL for Table DATAPATCH_SAR_MOVE8224
--------------------------------------------------------

  CREATE TABLE "SAVEMGR"."DATAPATCH_SAR_MOVE8224" 
   (	"APP_DETAIL_ID" NUMBER, 
	"CASE_DETAIL_ID" NUMBER, 
	"ELA_ID" NUMBER, 
	"DTI_REF" VARCHAR2(100 BYTE), 
	"CASE_SAR" NUMBER, 
	"CASE_SITE" NUMBER, 
	"APP_SAR" NUMBER, 
	"APP_SITE" NUMBER, 
	"APP_XML" "SYS"."XMLTYPE" 
   ) ;

   COMMENT ON TABLE "SAVEMGR"."DATAPATCH_SAR_MOVE8224"  IS 'Save of "SPIREMGR"."DATAPATCH_SAR_MOVE8224" at 16-DEC-2013 17:14:55';
  GRANT SELECT ON "SAVEMGR"."DATAPATCH_SAR_MOVE8224" TO "SPIREMGR";
