--------------------------------------------------------
--  DDL for Table DB_DU_APPLICANTS
--------------------------------------------------------

  CREATE TABLE "XVIEWMGR"."DB_DU_APPLICANTS" 
   (	"DTI_REF" VARCHAR2(100 BYTE), 
	"ELA_ID" NUMBER, 
	"TO_EMAIL" VARCHAR2(4000 BYTE), 
	"APPLICANT_NAME" VARCHAR2(8001 BYTE), 
	"ADDRESS" VARCHAR2(700 BYTE), 
	"CONTACT_NAME" VARCHAR2(4000 BYTE), 
	"LETTER_BLOB" BLOB, 
	"CC_EMAIL" VARCHAR2(1 BYTE), 
	"EMAIL_SUBJECT" VARCHAR2(4000 BYTE), 
	"EMAIL_BODY" VARCHAR2(4000 BYTE)
   ) 
 LOB ("LETTER_BLOB") STORE AS SECUREFILE "SPIRE_LETTER_BLOB_DATA3"(ENABLE STORAGE IN ROW CHUNK 8192
  NOCACHE LOGGING  NOCOMPRESS  KEEP_DUPLICATES ) ;
