--------------------------------------------------------
--  DDL for Table DB_TAU_BYPASS_REPORT
--------------------------------------------------------

  CREATE TABLE "SPIREMGR"."DB_TAU_BYPASS_REPORT" 
   (	"DTI_REF" VARCHAR2(100 BYTE), 
	"COMPANY" VARCHAR2(4000 BYTE), 
	"COUNTRIES" VARCHAR2(32767 BYTE), 
	"ITEM_NO" NUMBER, 
	"DESCRIPTION" VARCHAR2(4000 BYTE), 
	"PART_NO" VARCHAR2(500 BYTE), 
	"COPIED_CE" VARCHAR2(32767 BYTE), 
	"FINAL_CE" VARCHAR2(32767 BYTE), 
	"SAME_FINAL_CE" VARCHAR2(5 BYTE), 
	"COPIED_ARS" VARCHAR2(32767 BYTE), 
	"FINAL_ARS" VARCHAR2(32767 BYTE), 
	"SAME_FINAL_ARS" VARCHAR2(5 BYTE), 
	"COPIED_REGIME" VARCHAR2(32767 BYTE), 
	"FINAL_REGIME" VARCHAR2(32767 BYTE), 
	"SAME_FINAL_REGIME" VARCHAR2(5 BYTE), 
	"COPIED_GOODS_CLASSIFICATIONS" VARCHAR2(32767 BYTE), 
	"FINAL_GOODS_CLASSIFICATIONS" VARCHAR2(32767 BYTE), 
	"SAME_FINAL_GOODS_CLASS" VARCHAR2(5 BYTE), 
	"BYPASS_COMPLETED_CORRECTLY" VARCHAR2(5 BYTE), 
	"COPIED_FROM_SPIRE_REF" VARCHAR2(32767 BYTE)
   ) ;
