--------------------------------------------------------
--  DDL for Table DB_VIEW_APP_STUCK_STAGES
--------------------------------------------------------

  CREATE TABLE "BPMMGR"."DB_VIEW_APP_STUCK_STAGES" 
   (	"BS_ID" NUMBER(12,0), 
	"START_DATETIME" DATE, 
	"END_DATETIME" DATE, 
	"BP_ID" NUMBER(12,0), 
	"BA_ID" NUMBER(12,0), 
	"BRC_ID" NUMBER(12,0), 
	"STAGE_LABEL" VARCHAR2(30 BYTE), 
	"STAGE_STATUS" VARCHAR2(200 BYTE), 
	"ACTION_DESC_STAGE" VARCHAR2(4000 BYTE), 
	"PRIMARY_DATA_UREF" VARCHAR2(200 BYTE), 
	"FINAL_SUPER_ROUTINE_STATUS" VARCHAR2(4000 BYTE), 
	"UREF" VARCHAR2(200 BYTE), 
	"UPDATE_COMPLETE" VARCHAR2(5 BYTE)
   ) ;
