--------------------------------------------------------
--  DDL for Table DENIAL_DETAILS
--------------------------------------------------------

  CREATE TABLE "SAVEMGR"."DENIAL_DETAILS" 
   (	"ID" NUMBER, 
	"D_ID" NUMBER, 
	"STATUS_CONTROL" VARCHAR2(1 BYTE), 
	"XML_DATA" "SYS"."XMLTYPE" , 
	"CREATED_DATETIME" DATE, 
	"CREATED_BY_NAME" VARCHAR2(200 BYTE), 
	"CREATED_BY_WUA_ID" NUMBER, 
	"ENDED_DATETIME" DATE, 
	"ENDED_BY_NAME" VARCHAR2(200 BYTE), 
	"ENDED_BY_WUA_ID" NUMBER
   ) ;

   COMMENT ON TABLE "SAVEMGR"."DENIAL_DETAILS"  IS 'Save of "SPIREMGR"."DENIAL_DETAILS" at 29-JAN-2010 19:16:40';
  GRANT SELECT ON "SAVEMGR"."DENIAL_DETAILS" TO "SPIREMGR";
