--------------------------------------------------------
--  DDL for Table DH_OIEL_SURVEY
--------------------------------------------------------

  CREATE TABLE "XVIEWMGR"."DH_OIEL_SURVEY" 
   (	"COMPANY_NAME" VARCHAR2(4000 BYTE), 
	"FULL_NAME" VARCHAR2(4000 BYTE), 
	"PRIMARY_EMAIL_ADDRESS" VARCHAR2(4000 BYTE), 
	"PRIMARY_CONTACT" VARCHAR2(10 BYTE), 
	"FORENAME" VARCHAR2(4000 BYTE), 
	"EMAIL_SUBJECT" VARCHAR2(4000 BYTE), 
	"EMAIL_BODY" CLOB, 
	"EMAIL_SENT" VARCHAR2(1 BYTE)
   ) ;
