--------------------------------------------------------
--  DDL for Table DIGITAL_CERTIFICATES
--------------------------------------------------------

  CREATE TABLE "DECMGR"."DIGITAL_CERTIFICATES" 
   (	"ID" NUMBER, 
	"CERTIFICATE_NAME" VARCHAR2(100 BYTE), 
	"CERTIFICATE_FILE" BLOB, 
	"PRIVATE_KEY_FILE" BLOB, 
	"EXPIRY_DATE" DATE, 
	"USAGE_WINDOW_START_DATE" DATE, 
	"USAGE_WINDOW_END_DATE" DATE, 
	"CACHE_TIMEOUT_MINS" NUMBER(6,0), 
	"CERTIFICATE_FILE_TYPE" VARCHAR2(20 BYTE)
   ) 
 LOB ("CERTIFICATE_FILE") STORE AS BASICFILE "CERT_FILE_LOB"(ENABLE STORAGE IN ROW CHUNK 8192 RETENTION 
  CACHE ) 
 LOB ("PRIVATE_KEY_FILE") STORE AS BASICFILE "PRIV_KEY_FILE_LOB"(ENABLE STORAGE IN ROW CHUNK 8192 RETENTION 
  CACHE ) ;
