--------------------------------------------------------
--  DDL for Table DOCUMENT_INSTANCES
--------------------------------------------------------

  CREATE TABLE "DECMGR"."DOCUMENT_INSTANCES" 
   (	"ID" NUMBER(12,0), 
	"DISPLAY_SEQUENCE" NUMBER(4,0), 
	"DP_ID" NUMBER(12,0), 
	"METADATA_XML" "SYS"."XMLTYPE" , 
	"XML_DATA" "SYS"."XMLTYPE" , 
	"STATUS" VARCHAR2(30 BYTE), 
	"LAST_SYSTEM_MESSAGE" VARCHAR2(4000 BYTE), 
	"CREATE_WUA_ID" NUMBER(12,0), 
	"DC_ID" NUMBER(12,0), 
	"COPY_OF_DI_ID" NUMBER(12,0)
   ) ;
  GRANT SELECT ON "DECMGR"."DOCUMENT_INSTANCES" TO "BISAPIMGR";
  GRANT SELECT ON "DECMGR"."DOCUMENT_INSTANCES" TO "PVEXMGR";
  GRANT INSERT ON "DECMGR"."DOCUMENT_INSTANCES" TO "PVEXMGR";
  GRANT INSERT ON "DECMGR"."DOCUMENT_INSTANCES" TO "BPMMGR";
  GRANT SELECT ON "DECMGR"."DOCUMENT_INSTANCES" TO "FOXMGR";
  GRANT SELECT ON "DECMGR"."DOCUMENT_INSTANCES" TO "ENVMGR";
  GRANT SELECT ON "DECMGR"."DOCUMENT_INSTANCES" TO "PORTALMGR";
  GRANT REFERENCES ON "DECMGR"."DOCUMENT_INSTANCES" TO "PORTALMGR";
  GRANT UPDATE ON "DECMGR"."DOCUMENT_INSTANCES" TO "REPORTMGR";
  GRANT INSERT ON "DECMGR"."DOCUMENT_INSTANCES" TO "REPORTMGR";
  GRANT REFERENCES ON "DECMGR"."DOCUMENT_INSTANCES" TO "SPIREMGR";
  GRANT INSERT ON "DECMGR"."DOCUMENT_INSTANCES" TO "SPIREMGR";
  GRANT SELECT ON "DECMGR"."DOCUMENT_INSTANCES" TO "SPIREMGR";
  GRANT REFERENCES ON "DECMGR"."DOCUMENT_INSTANCES" TO "XVIEWMGR";
  GRANT SELECT ON "DECMGR"."DOCUMENT_INSTANCES" TO "XVIEWMGR";
  GRANT SELECT ON "DECMGR"."DOCUMENT_INSTANCES" TO "BPMMGR";
  GRANT UPDATE ON "DECMGR"."DOCUMENT_INSTANCES" TO "APPENV";
  GRANT SELECT ON "DECMGR"."DOCUMENT_INSTANCES" TO "APPENV";
  GRANT INSERT ON "DECMGR"."DOCUMENT_INSTANCES" TO "APPENV";
  GRANT REFERENCES ON "DECMGR"."DOCUMENT_INSTANCES" TO "REPORTMGR";
