--------------------------------------------------------
--  DDL for Table DOCUMENT_SETS
--------------------------------------------------------

  CREATE TABLE "DECMGR"."DOCUMENT_SETS" 
   (	"ID" NUMBER(12,0), 
	"XML_DATA" "SYS"."XMLTYPE" 
   ) ;
  GRANT UPDATE ON "DECMGR"."DOCUMENT_SETS" TO "APPENV";
  GRANT SELECT ON "DECMGR"."DOCUMENT_SETS" TO "SPIREMGR";
  GRANT SELECT ON "DECMGR"."DOCUMENT_SETS" TO "APPENV";
  GRANT REFERENCES ON "DECMGR"."DOCUMENT_SETS" TO "XVIEWMGR";
  GRANT SELECT ON "DECMGR"."DOCUMENT_SETS" TO "XVIEWMGR";
  GRANT REFERENCES ON "DECMGR"."DOCUMENT_SETS" TO "BPMMGR";
  GRANT SELECT ON "DECMGR"."DOCUMENT_SETS" TO "BPMMGR";
  GRANT INSERT ON "DECMGR"."DOCUMENT_SETS" TO "BPMMGR";
  GRANT INDEX ON "DECMGR"."DOCUMENT_SETS" TO "BPMMGR";
