--------------------------------------------------------
--  DDL for Table DOCUMENT_COMPOSITIONS
--------------------------------------------------------

  CREATE TABLE "DECMGR"."DOCUMENT_COMPOSITIONS" 
   (	"ID" NUMBER(12,0), 
	"XML_DATA" "SYS"."XMLTYPE" , 
	"DS_ID" NUMBER
   ) ;
  GRANT SELECT ON "DECMGR"."DOCUMENT_COMPOSITIONS" TO "BISAPIMGR";
  GRANT SELECT ON "DECMGR"."DOCUMENT_COMPOSITIONS" TO "PVEXMGR";
  GRANT UPDATE ON "DECMGR"."DOCUMENT_COMPOSITIONS" TO "SPIREMGR";
  GRANT UPDATE ON "DECMGR"."DOCUMENT_COMPOSITIONS" TO "APPENV";
  GRANT REFERENCES ON "DECMGR"."DOCUMENT_COMPOSITIONS" TO "XVIEWMGR";
  GRANT SELECT ON "DECMGR"."DOCUMENT_COMPOSITIONS" TO "SPIREMGR";
  GRANT REFERENCES ON "DECMGR"."DOCUMENT_COMPOSITIONS" TO "BPMMGR";
  GRANT SELECT ON "DECMGR"."DOCUMENT_COMPOSITIONS" TO "BPMMGR";
  GRANT SELECT ON "DECMGR"."DOCUMENT_COMPOSITIONS" TO "APPENV";
  GRANT UPDATE ON "DECMGR"."DOCUMENT_COMPOSITIONS" TO "BPMMGR";
