--------------------------------------------------------
--  DDL for Table DOCUMENT_PACKS
--------------------------------------------------------

  CREATE TABLE "DECMGR"."DOCUMENT_PACKS" 
   (	"ID" NUMBER(12,0), 
	"DS_ID" NUMBER(12,0), 
	"XML_DATA" "SYS"."XMLTYPE" 
   ) ;
  GRANT SELECT ON "DECMGR"."DOCUMENT_PACKS" TO "BISAPIMGR";
  GRANT SELECT ON "DECMGR"."DOCUMENT_PACKS" TO "PVEXMGR";
  GRANT INSERT ON "DECMGR"."DOCUMENT_PACKS" TO "PVEXMGR";
  GRANT INSERT ON "DECMGR"."DOCUMENT_PACKS" TO "REPORTMGR";
  GRANT SELECT ON "DECMGR"."DOCUMENT_PACKS" TO "SPIREMGR";
  GRANT INSERT ON "DECMGR"."DOCUMENT_PACKS" TO "SPIREMGR";
  GRANT REFERENCES ON "DECMGR"."DOCUMENT_PACKS" TO "XVIEWMGR";
  GRANT SELECT ON "DECMGR"."DOCUMENT_PACKS" TO "XVIEWMGR";
  GRANT SELECT ON "DECMGR"."DOCUMENT_PACKS" TO "BPMMGR";
  GRANT INSERT ON "DECMGR"."DOCUMENT_PACKS" TO "BPMMGR";
  GRANT REFERENCES ON "DECMGR"."DOCUMENT_PACKS" TO "APPENV";
  GRANT UPDATE ON "DECMGR"."DOCUMENT_PACKS" TO "APPENV";
  GRANT SELECT ON "DECMGR"."DOCUMENT_PACKS" TO "APPENV";
  GRANT INSERT ON "DECMGR"."DOCUMENT_PACKS" TO "APPENV";
  GRANT DELETE ON "DECMGR"."DOCUMENT_PACKS" TO "APPENV";
