--------------------------------------------------------
--  DDL for Table DOCUMENT_COMPOSITION_PACKS
--------------------------------------------------------

  CREATE TABLE "DECMGR"."DOCUMENT_COMPOSITION_PACKS" 
   (	"ID" NUMBER(12,0), 
	"DS_ID" NUMBER(12,0), 
	"XML_DATA" "DECMGR"."XMLTYPE"
   ) ;
  GRANT UPDATE ON "DECMGR"."DOCUMENT_COMPOSITION_PACKS" TO "SPIREMGR";
  GRANT SELECT ON "DECMGR"."DOCUMENT_COMPOSITION_PACKS" TO "SPIREMGR";
  GRANT SELECT ON "DECMGR"."DOCUMENT_COMPOSITION_PACKS" TO "APPENV";
