--------------------------------------------------------
--  DDL for Table ELA_GROUPS
--------------------------------------------------------

  CREATE TABLE "SPIREMGR"."ELA_GROUPS" 
   (	"ID" NUMBER, 
	"FIRST_ELA_ID" NUMBER, 
	"LAST_ELA_ID" NUMBER, 
	"ELA_TYPE" VARCHAR2(20 BYTE) DEFAULT 'SPIRE', 
	"RENEWED_FROM_LICENCE_DETAIL_ID" NUMBER(12,0)
   ) ;
  GRANT SELECT ON "SPIREMGR"."ELA_GROUPS" TO "BISAPIMGR";
  GRANT INSERT ON "SPIREMGR"."ELA_GROUPS" TO "SDBMGR";
  GRANT REFERENCES ON "SPIREMGR"."ELA_GROUPS" TO "SDBMGR";
  GRANT SELECT ON "SPIREMGR"."ELA_GROUPS" TO "SDBMGR" WITH GRANT OPTION;
  GRANT SELECT ON "SPIREMGR"."ELA_GROUPS" TO "BPMMGR";
  GRANT SELECT ON "SPIREMGR"."ELA_GROUPS" TO "APPENV";
  GRANT REFERENCES ON "SPIREMGR"."ELA_GROUPS" TO "BPMMGR";
  GRANT INDEX ON "SPIREMGR"."ELA_GROUPS" TO "BPMMGR";
