--------------------------------------------------------
--  DDL for Table ELA_TEMPLATE_TYPE
--------------------------------------------------------

  CREATE TABLE "SPIREMGR"."ELA_TEMPLATE_TYPE" 
   (	"TYPE" VARCHAR2(50 BYTE), 
	"SUBTYPE" VARCHAR2(50 BYTE), 
	"MIN_PUBLISHED_TEMPLATES" NUMBER, 
	"MAX_PUBLISHED_TEMPLATES" NUMBER, 
	"AUTO_LOAD_YN" VARCHAR2(1 BYTE), 
	"TEMPLATE_TITLE" VARCHAR2(50 BYTE)
   ) ;
  GRANT REFERENCES ON "SPIREMGR"."ELA_TEMPLATE_TYPE" TO "BPMMGR";
  GRANT SELECT ON "SPIREMGR"."ELA_TEMPLATE_TYPE" TO "BPMMGR";
  GRANT INDEX ON "SPIREMGR"."ELA_TEMPLATE_TYPE" TO "BPMMGR";
  GRANT UPDATE ON "SPIREMGR"."ELA_TEMPLATE_TYPE" TO "APPENV";
  GRANT SELECT ON "SPIREMGR"."ELA_TEMPLATE_TYPE" TO "APPENV";
  GRANT INSERT ON "SPIREMGR"."ELA_TEMPLATE_TYPE" TO "APPENV";
