--------------------------------------------------------
--  DDL for Table ELC_PARTY
--------------------------------------------------------

  CREATE TABLE "WARP_OWNER"."ELC_PARTY" 
   (	"PARTY_ID" VARCHAR2(10 BYTE), 
	"TYPE" VARCHAR2(3 BYTE), 
	"FULL_NAME" VARCHAR2(50 BYTE), 
	"ADDRESS1" VARCHAR2(40 BYTE), 
	"ADDRESS2" VARCHAR2(40 BYTE), 
	"ADDRESS3" VARCHAR2(40 BYTE), 
	"ADDRESS4" VARCHAR2(40 BYTE), 
	"EXTERNAL_FLAG" VARCHAR2(1 BYTE), 
	"SURNAME" VARCHAR2(30 BYTE), 
	"CONT_ADDRESS1" VARCHAR2(40 BYTE), 
	"CONT_ADDRESS2" VARCHAR2(40 BYTE), 
	"CONT_ADDRESS3" VARCHAR2(40 BYTE), 
	"CONT_ADDRESS4" VARCHAR2(40 BYTE), 
	"TITLE" VARCHAR2(5 BYTE), 
	"INITIALS" VARCHAR2(3 BYTE), 
	"TELEPHONE" VARCHAR2(20 BYTE), 
	"JOB_TITLE" VARCHAR2(30 BYTE), 
	"INACTIVE_FROM_DATE" DATE, 
	"MAIL_STOP" VARCHAR2(1 BYTE), 
	"CONT_INDICATOR" VARCHAR2(1 BYTE), 
	"WATCH_LIST" VARCHAR2(1 BYTE), 
	"POSTCODE" VARCHAR2(10 BYTE), 
	"VAT_NO" VARCHAR2(10 BYTE), 
	"REGISTRATION_DATE" DATE, 
	"FAX_NO" VARCHAR2(20 BYTE), 
	"EMAIL_ADDRESS" VARCHAR2(50 BYTE)
   ) ;
