--------------------------------------------------------
--  DDL for Table ELC_CASE
--------------------------------------------------------

  CREATE TABLE "WARP_OWNER"."ELC_CASE" 
   (	"CASE_ID" NUMBER(10,0), 
	"YEAR" NUMBER(4,0), 
	"TYPE" VARCHAR2(4 BYTE), 
	"REF_NO" NUMBER(6,0), 
	"STATUS" NUMBER(2,0), 
	"HOLDER" VARCHAR2(3 BYTE), 
	"COUNTRY_CODE" VARCHAR2(3 BYTE), 
	"EXPORTER_ID" NUMBER(10,0), 
	"DATE_COMPLETED" DATE, 
	"APPLIC_DATE" DATE, 
	"APPLIC_RECEIVED" DATE, 
	"APPLIC_ENTERED" DATE, 
	"APPLIC_REFERRED_STATUS" VARCHAR2(1 BYTE), 
	"OTHER_REF_NO" VARCHAR2(12 BYTE), 
	"CUSTOMER_REF" VARCHAR2(50 BYTE), 
	"END_USER_ID" NUMBER(10,0), 
	"AGENT_NAME" VARCHAR2(50 BYTE), 
	"DATE_SENS_LETTER" DATE, 
	"DATE_NLR_LETTER" DATE, 
	"AWAIT_EXT_REFERRAL" VARCHAR2(1 BYTE), 
	"AWAIT_FURTHER_INFO" VARCHAR2(1 BYTE), 
	"DATE_WITHDRAWN" DATE, 
	"LAST_EVENT" DATE, 
	"RATED_BY" VARCHAR2(3 BYTE)
   ) ;
