--------------------------------------------------------
--  DDL for Table ELC_CASE_STATS
--------------------------------------------------------

  CREATE TABLE "WARP_OWNER"."ELC_CASE_STATS" 
   (	"CASE_ID" NUMBER(10,0), 
	"FI_FLAG" VARCHAR2(1 BYTE), 
	"OGD_FLAG" VARCHAR2(1 BYTE), 
	"COP_MEASURE" NUMBER(3,0), 
	"ECO_TOTAL" NUMBER(10,0), 
	"OGD_TOTAL" NUMBER(10,0), 
	"EXP_TOTAL" NUMBER(10,0), 
	"DAYS_TO_ASSIGN" NUMBER(10,0), 
	"DAYS_LEFT" NUMBER(10,0), 
	"ERROR_FLAG" NUMBER(2,0), 
	"RECORD_COUNT" NUMBER(10,0), 
	"TOTAL_WORK" NUMBER(10,0), 
	"SINCE_DATE" DATE, 
	"COP_TARGET" DATE, 
	"WITHDRAWN" DATE, 
	"SUBJECT" VARCHAR2(10 BYTE), 
	"RATED_BY" VARCHAR2(10 BYTE), 
	"TURN_AROUND_DAYS" NUMBER(4,0), 
	"DATE_COMPLETED" DATE, 
	"REFERENCE" VARCHAR2(50 BYTE), 
	"APPLIC_RECEIVED" DATE
   ) ;
