--------------------------------------------------------
--  DDL for Table EMAIL_RECIPIENTS
--------------------------------------------------------

  CREATE TABLE "PORTALMGR"."EMAIL_RECIPIENTS" 
   (	"ID" NUMBER(12,0), 
	"EMAIL_ADDRESSEE" VARCHAR2(255 BYTE), 
	"EMAIL_SUBJECT" VARCHAR2(200 BYTE), 
	"EMAIL_MESSAGE" CLOB, 
	"FIRST_REQUESTED_DATE" DATE, 
	"FIRST_REQUESTED_BY" VARCHAR2(30 BYTE), 
	"FIRST_SENT_DATE" DATE, 
	"FIRST_SENT_BY" VARCHAR2(30 BYTE), 
	"FIRST_SENT_RETRY_COUNT" NUMBER(9,0), 
	"RESEND_REQUESTED_DATE" DATE, 
	"RESEND_REQUESTED_BY" VARCHAR2(30 BYTE), 
	"RESEND_RETRY_COUNT" NUMBER(9,0), 
	"RESEND_LAST_SENT_DATE" DATE, 
	"RESEND_LAST_SENT_BY" VARCHAR2(30 BYTE), 
	"LAST_DML_DATE" DATE, 
	"LAST_DML_BY" VARCHAR2(30 BYTE)
   ) ;
