--------------------------------------------------------
--  DDL for Table ENFORCEMENT_CHECK2112_TAB
--------------------------------------------------------

  CREATE TABLE "XVIEWMGR"."ENFORCEMENT_CHECK2112_TAB" OF XMLTYPE 
 VARRAY "XMLDATA"."STAKEHOLDER" STORE AS TABLE "SYS_NTNd5yPPBU6VzgUwwgAArPgQ=="
 (
 VARRAY "SYS_XDBPD$" STORE AS SECUREFILE LOB ) RETURN AS LOCATOR
 VARRAY "XMLEXTRA"."NAMESPACES" STORE AS SECUREFILE LOB "NAMESPACES2115_L"
 VARRAY "XMLEXTRA"."EXTRADATA" STORE AS SECUREFILE LOB "EXTRADATA2114_L"
 VARRAY "XMLDATA"."SYS_XDBPD$" STORE AS SECUREFILE LOB "SYS_XDBPD$2113_L";
