--------------------------------------------------------
--  DDL for Table ENV_MAPSETS_BACKUP
--------------------------------------------------------

  CREATE TABLE "ENVMGR"."ENV_MAPSETS_BACKUP" 
   (	"DOMAIN" VARCHAR2(30 BYTE), 
	"DATA" CLOB, 
	"DESCRIPTION" VARCHAR2(200 BYTE)
   ) 
 LOB ("DATA") STORE AS BASICFILE "ENV_MAPSETS_DATA"(DISABLE STORAGE IN ROW CHUNK 8192 RETENTION 
  CACHE ) ;
  GRANT SELECT ON "ENVMGR"."ENV_MAPSETS_BACKUP" TO "BPMMGR";
  GRANT UPDATE ON "ENVMGR"."ENV_MAPSETS_BACKUP" TO "APPENV";
  GRANT SELECT ON "ENVMGR"."ENV_MAPSETS_BACKUP" TO "APPENV";
  GRANT INSERT ON "ENVMGR"."ENV_MAPSETS_BACKUP" TO "APPENV";
  GRANT DELETE ON "ENVMGR"."ENV_MAPSETS_BACKUP" TO "APPENV";
  GRANT UPDATE ON "ENVMGR"."ENV_MAPSETS_BACKUP" TO "APPBPM";
  GRANT SELECT ON "ENVMGR"."ENV_MAPSETS_BACKUP" TO "APPBPM";
  GRANT INSERT ON "ENVMGR"."ENV_MAPSETS_BACKUP" TO "APPBPM";
  GRANT DELETE ON "ENVMGR"."ENV_MAPSETS_BACKUP" TO "APPBPM";
