--------------------------------------------------------
--  DDL for Table EXPORT_LICENCE_USAGES
--------------------------------------------------------

  CREATE TABLE "SPIREMGR"."EXPORT_LICENCE_USAGES" 
   (	"ID" NUMBER(12,0), 
	"LD_ID" NUMBER(12,0), 
	"ELL_ID" NUMBER(12,0), 
	"QUANTITY" NUMBER(22,8), 
	"ORIGINATOR" VARCHAR2(20 BYTE), 
	"TYPE" VARCHAR2(10 BYTE), 
	"STATUS" VARCHAR2(20 BYTE), 
	"CREATED_BY_WUA_FULL_NAME" VARCHAR2(400 BYTE), 
	"CREATED_BY_WUA_ID" NUMBER(12,0), 
	"CREATED_DATETIME" DATE, 
	"UPDATED_BY_WUA_FULL_NAME" VARCHAR2(400 BYTE), 
	"UPDATED_BY_WUA_ID" NUMBER(12,0), 
	"UPDATED_DATETIME" DATE, 
	"DTI_COMMENT_XML" "SYS"."XMLTYPE" , 
	"EXPORTER_COMMENT_XML" "SYS"."XMLTYPE" , 
	"DECLARATION_UCR" VARCHAR2(100 BYTE), 
	"DECLARATION_PART" VARCHAR2(20 BYTE), 
	"CHIEF_PSEUDO_EXHAUST_FLAG" VARCHAR2(5 BYTE) DEFAULT 'false', 
	"CONTROL_DATE" DATE, 
	"WARNING_FLAG" VARCHAR2(30 BYTE), 
	"WARNING_MSG" VARCHAR2(4000 BYTE), 
	"MC_ID" NUMBER
   ) ;
  GRANT SELECT ON "SPIREMGR"."EXPORT_LICENCE_USAGES" TO "APPENV";
