--------------------------------------------------------
--  DDL for Table EXPORT_LICENCE_APPS
--------------------------------------------------------

  CREATE TABLE "SPIREMGR"."EXPORT_LICENCE_APPS" 
   (	"ID" NUMBER(*,0), 
	"PF_ID" NUMBER(12,0), 
	"PREVIOUS_ELA_ID" NUMBER(*,0), 
	"CASE_PROGRESS_STAGE" NUMBER(4,0), 
	"CURRENT_RFI_COUNTER" NUMBER(3,0), 
	"ELA_GRP_ID" NUMBER, 
	"CASE_PROGRESS_STAGE_DATE" DATE, 
	"SUSPENDED_FLAG" NUMBER DEFAULT 0, 
	"CASE_PROGRESS_BACKUP_STAGE" NUMBER(4,0)
   ) ;
  GRANT UPDATE ON "SPIREMGR"."EXPORT_LICENCE_APPS" TO "BPMMGR";
  GRANT REFERENCES ON "SPIREMGR"."EXPORT_LICENCE_APPS" TO "XVIEWMGR";
  GRANT SELECT ON "SPIREMGR"."EXPORT_LICENCE_APPS" TO "BISAPIMGR" WITH GRANT OPTION;
  GRANT REFERENCES ON "SPIREMGR"."EXPORT_LICENCE_APPS" TO "SDBMGR";
  GRANT SELECT ON "SPIREMGR"."EXPORT_LICENCE_APPS" TO "SDBMGR";
  GRANT SELECT ON "SPIREMGR"."EXPORT_LICENCE_APPS" TO "DECMGR";
  GRANT SELECT ON "SPIREMGR"."EXPORT_LICENCE_APPS" TO "APPENV";
  GRANT REFERENCES ON "SPIREMGR"."EXPORT_LICENCE_APPS" TO "BPMMGR";
  GRANT SELECT ON "SPIREMGR"."EXPORT_LICENCE_APPS" TO "BPMMGR";
  GRANT INDEX ON "SPIREMGR"."EXPORT_LICENCE_APPS" TO "BPMMGR";
