--------------------------------------------------------
--  DDL for Table EXPORT_LICENCE_APP_DETAILS
--------------------------------------------------------

  CREATE TABLE "SAVEMGR"."EXPORT_LICENCE_APP_DETAILS" 
   (	"ID" NUMBER(*,0), 
	"ELA_ID" NUMBER(*,0), 
	"START_DATE" DATE, 
	"END_DATE" DATE, 
	"XML_DATA" "SYS"."XMLTYPE" , 
	"SECURE_LOB_REF" REF "SECUREMGR"."SECURE_LOB" , 
	"STATUS" VARCHAR2(12 BYTE), 
	"ACCESS_EXTERNAL" VARCHAR2(1 BYTE), 
	"ACCESS_EXTERNAL_DATE" DATE, 
	"ACCESS_INTERNAL" VARCHAR2(1 BYTE)
   ) ;

   COMMENT ON TABLE "SAVEMGR"."EXPORT_LICENCE_APP_DETAILS"  IS 'Save of "SPIREMGR"."EXPORT_LICENCE_APP_DETAILS" at 18-OCT-2007 17:52:12';
