--------------------------------------------------------
--  DDL for Table EXPORT_LICENCE_COUNTRIES
--------------------------------------------------------

  CREATE TABLE "SPIREMGR"."EXPORT_LICENCE_COUNTRIES" 
   (	"LD_ID" NUMBER(12,0), 
	"COUNTRY_ID" NUMBER(12,0), 
	"ELCG_ID" NUMBER, 
	"TYPE" VARCHAR2(20 BYTE)
   ) ;
  GRANT SELECT ON "SPIREMGR"."EXPORT_LICENCE_COUNTRIES" TO "SDBMGR";
  GRANT SELECT ON "SPIREMGR"."EXPORT_LICENCE_COUNTRIES" TO "SPMIGUSER";
  GRANT INSERT ON "SPIREMGR"."EXPORT_LICENCE_COUNTRIES" TO "SPMIGUSER";
  GRANT DELETE ON "SPIREMGR"."EXPORT_LICENCE_COUNTRIES" TO "SPMIGUSER";
  GRANT SELECT ON "SPIREMGR"."EXPORT_LICENCE_COUNTRIES" TO "APPENV";
