--------------------------------------------------------
--  DDL for Table EXPORT_LICENCE_DETAILS_2
--------------------------------------------------------

  CREATE TABLE "SAVEMGR"."EXPORT_LICENCE_DETAILS_2" 
   (	"ID" NUMBER(12,0), 
	"L_ID" NUMBER(12,0), 
	"ELA_ID" NUMBER(12,0), 
	"ELA_DETAIL_ID" NUMBER(12,0), 
	"N_ID" NUMBER(12,0), 
	"START_DATE" DATE, 
	"END_DATE" DATE, 
	"XML_DATA" "SYS"."XMLTYPE" , 
	"LICENCE_TYPE" VARCHAR2(100 BYTE), 
	"LICENCE_SUB_TYPE" VARCHAR2(500 BYTE), 
	"OGL_ID" NUMBER(12,0), 
	"DI_ID" NUMBER(12,0), 
	"EXPIRY_DATE" DATE, 
	"LICENCE_REF" VARCHAR2(110 BYTE), 
	"LEGACY_FLAG" CHAR(1 BYTE)
   ) ;

   COMMENT ON TABLE "SAVEMGR"."EXPORT_LICENCE_DETAILS_2"  IS 'Save of "SPIREMGR"."EXPORT_LICENCE_DETAILS" at 04-JUL-2008 22:14:37';
  GRANT SELECT ON "SAVEMGR"."EXPORT_LICENCE_DETAILS_2" TO "SPIREMGR";
