--------------------------------------------------------
--  DDL for Table EXPORT_LICENCE_RETURNS
--------------------------------------------------------

  CREATE TABLE "SPIREMGR"."EXPORT_LICENCE_RETURNS" 
   (	"ID" NUMBER
   ) ;
  GRANT REFERENCES ON "SPIREMGR"."EXPORT_LICENCE_RETURNS" TO "SDBMGR";
  GRANT SELECT ON "SPIREMGR"."EXPORT_LICENCE_RETURNS" TO "SDBMGR";
  GRANT SELECT ON "SPIREMGR"."EXPORT_LICENCE_RETURNS" TO "APPENV";
