--------------------------------------------------------
--  DDL for Table EXPORT_LICENCE_APP_TYPES
--------------------------------------------------------

  CREATE TABLE "SPIREMGR"."EXPORT_LICENCE_APP_TYPES" 
   (	"APPLICATION_TYPE" VARCHAR2(50 BYTE), 
	"APPLICATION_SUB_TYPE" VARCHAR2(50 BYTE), 
	"MATRIX_PREFIX" VARCHAR2(50 BYTE), 
	"RETURNS_REQUIRED" VARCHAR2(5 BYTE)
   ) ;
  GRANT SELECT ON "SPIREMGR"."EXPORT_LICENCE_APP_TYPES" TO "APPENV";
