--------------------------------------------------------
--  DDL for Table EXPORT_LICENCE_LINES
--------------------------------------------------------

  CREATE TABLE "SAVEMGR"."EXPORT_LICENCE_LINES" 
   (	"ID" NUMBER(12,0), 
	"LD_ID" NUMBER(12,0), 
	"COUNTRY_ID" NUMBER(12,0), 
	"GOODS_ITEM_ID" NUMBER(12,0), 
	"LINE_NO" NUMBER(12,0), 
	"DESCRIPTION" VARCHAR2(4000 BYTE), 
	"VALUE" NUMBER(12,0), 
	"QUANTITY" NUMBER(12,0), 
	"QUANTITY_MEASURE" VARCHAR2(100 BYTE)
   ) ;

   COMMENT ON TABLE "SAVEMGR"."EXPORT_LICENCE_LINES"  IS 'Save of "SPIREMGR"."EXPORT_LICENCE_LINES" at 07-FEB-2008 21:52:58';
  GRANT SELECT ON "SAVEMGR"."EXPORT_LICENCE_LINES" TO "SPIREMGR";
