--------------------------------------------------------
--  DDL for Table EXPORT_LICENCES
--------------------------------------------------------

  CREATE TABLE "SAVEMGR"."EXPORT_LICENCES" 
   (	"ID" NUMBER(12,0), 
	"LICENCE_REF" VARCHAR2(100 BYTE), 
	"ELA_ID" NUMBER(12,0), 
	"STATUS" VARCHAR2(20 BYTE), 
	"START_DATE" DATE, 
	"EXPIRY_DATE" DATE, 
	"END_DATE" DATE, 
	"XML_DATA" "SYS"."XMLTYPE" 
   ) ;

   COMMENT ON TABLE "SAVEMGR"."EXPORT_LICENCES"  IS 'Save of "SPIREMGR"."EXPORT_LICENCES" at 04-JUL-2008 22:13:17';
  GRANT SELECT ON "SAVEMGR"."EXPORT_LICENCES" TO "SPIREMGR";
