--------------------------------------------------------
--  DDL for Table EXPORT_LICENCE_COUNTRIES_1
--------------------------------------------------------

  CREATE TABLE "SAVEMGR"."EXPORT_LICENCE_COUNTRIES_1" 
   (	"LD_ID" NUMBER(12,0), 
	"COUNTRY_ID" NUMBER(12,0), 
	"ELCG_ID" NUMBER, 
	"TYPE" VARCHAR2(20 BYTE)
   ) ;

   COMMENT ON TABLE "SAVEMGR"."EXPORT_LICENCE_COUNTRIES_1"  IS 'Save of "SPIREMGR"."EXPORT_LICENCE_COUNTRIES" at 24-FEB-2008 18:28:09';
  GRANT SELECT ON "SAVEMGR"."EXPORT_LICENCE_COUNTRIES_1" TO "SPIREMGR";
