--------------------------------------------------------
--  DDL for Table EXPORT_LICENCE_COUNTRIES
--------------------------------------------------------

  CREATE TABLE "SAVEMGR"."EXPORT_LICENCE_COUNTRIES" 
   (	"LD_ID" NUMBER(12,0), 
	"COUNTRY_ID" NUMBER(12,0)
   ) ;

   COMMENT ON TABLE "SAVEMGR"."EXPORT_LICENCE_COUNTRIES"  IS 'Save of "SPIREMGR"."EXPORT_LICENCE_COUNTRIES" at 07-FEB-2008 21:52:51';
  GRANT SELECT ON "SAVEMGR"."EXPORT_LICENCE_COUNTRIES" TO "SPIREMGR";
