--------------------------------------------------------
--  DDL for Table EXPORT_LICENCE_COUNTRY_GROUPS
--------------------------------------------------------

  CREATE TABLE "SAVEMGR"."EXPORT_LICENCE_COUNTRY_GROUPS" 
   (	"ID" NUMBER
   ) ;

   COMMENT ON TABLE "SAVEMGR"."EXPORT_LICENCE_COUNTRY_GROUPS"  IS 'Save of "SPIREMGR"."EXPORT_LICENCE_COUNTRY_GROUPS" at 24-FEB-2008 18:28:09';
  GRANT SELECT ON "SAVEMGR"."EXPORT_LICENCE_COUNTRY_GROUPS" TO "SPIREMGR";
