--------------------------------------------------------
--  DDL for Table EXPORT_LICENCE_COUNTRY_GROUPS
--------------------------------------------------------

  CREATE TABLE "SPIREMGR"."EXPORT_LICENCE_COUNTRY_GROUPS" 
   (	"ID" NUMBER, 
	"TYPE" VARCHAR2(20 BYTE)
   ) ;
  GRANT UPDATE ON "SPIREMGR"."EXPORT_LICENCE_COUNTRY_GROUPS" TO "SPMIGUSER";
  GRANT SELECT ON "SPIREMGR"."EXPORT_LICENCE_COUNTRY_GROUPS" TO "SPMIGUSER";
  GRANT INSERT ON "SPIREMGR"."EXPORT_LICENCE_COUNTRY_GROUPS" TO "SPMIGUSER";
  GRANT DELETE ON "SPIREMGR"."EXPORT_LICENCE_COUNTRY_GROUPS" TO "SPMIGUSER";
  GRANT SELECT ON "SPIREMGR"."EXPORT_LICENCE_COUNTRY_GROUPS" TO "APPENV";
