--------------------------------------------------------
--  DDL for Table EXPORT_LICENCE_STATUS_EVENTS
--------------------------------------------------------

  CREATE TABLE "SPIREMGR"."EXPORT_LICENCE_STATUS_EVENTS" 
   (	"ID" NUMBER(12,0), 
	"L_ID" NUMBER(12,0), 
	"ACTIVITY_TYPE" VARCHAR2(20 BYTE)
   ) ;
  GRANT SELECT ON "SPIREMGR"."EXPORT_LICENCE_STATUS_EVENTS" TO "SDBMGR";
  GRANT REFERENCES ON "SPIREMGR"."EXPORT_LICENCE_STATUS_EVENTS" TO "SDBMGR";
  GRANT SELECT ON "SPIREMGR"."EXPORT_LICENCE_STATUS_EVENTS" TO "BPMMGR";
  GRANT SELECT ON "SPIREMGR"."EXPORT_LICENCE_STATUS_EVENTS" TO "APPENV";
