--------------------------------------------------------
--  DDL for Table EXPORT_LICENCE_RETURN_DETAILS
--------------------------------------------------------

  CREATE TABLE "SPIREMGR"."EXPORT_LICENCE_RETURN_DETAILS" 
   (	"ID" NUMBER, 
	"ELR_ID" NUMBER, 
	"SUBMISSION_GROUP_ID" NUMBER, 
	"VERSION" NUMBER, 
	"SAVE_NO" NUMBER DEFAULT 0, 
	"STATUS_CONTROL" VARCHAR2(1 BYTE), 
	"CREATED_BY_WUA_ID" NUMBER, 
	"START_DATETIME" DATE, 
	"END_DATETIME" DATE, 
	"STATUS" VARCHAR2(25 BYTE), 
	"ELD_ID" NUMBER, 
	"END_COUNTRY_ID" NUMBER, 
	"END_USER_TYPE" VARCHAR2(5 BYTE), 
	"WITHDRAWN_REASON" VARCHAR2(1000 BYTE), 
	"ECO_COMMENT" VARCHAR2(1000 BYTE), 
	"NIL_RETURN" VARCHAR2(5 BYTE), 
	"RETURN_PERIOD_DATE" DATE, 
	"USAGE_COUNT" NUMBER(6,0), 
	"IS_VALID" VARCHAR2(8 BYTE) DEFAULT 'untested', 
	"REJECT_REASON" VARCHAR2(500 BYTE)
   ) ;
