--------------------------------------------------------
--  DDL for Table EXPORT_LICENCES
--------------------------------------------------------

  CREATE TABLE "SPIREMGR"."EXPORT_LICENCES" 
   (	"ID" NUMBER(12,0), 
	"LICENCE_REF" VARCHAR2(100 BYTE), 
	"START_DATE" DATE, 
	"END_DATE" DATE, 
	"XML_DATA" "SYS"."XMLTYPE" , 
	"ELA_GRP_ID" NUMBER, 
	"LICENCE_STATUS" VARCHAR2(20 BYTE)
   ) ;
  GRANT UPDATE ON "SPIREMGR"."EXPORT_LICENCES" TO "BISAPIMGR";
  GRANT SELECT ON "SPIREMGR"."EXPORT_LICENCES" TO "BISAPIMGR";
  GRANT INSERT ON "SPIREMGR"."EXPORT_LICENCES" TO "SDBMGR";
  GRANT REFERENCES ON "SPIREMGR"."EXPORT_LICENCES" TO "SDBMGR";
  GRANT SELECT ON "SPIREMGR"."EXPORT_LICENCES" TO "SDBMGR";
  GRANT SELECT ON "SPIREMGR"."EXPORT_LICENCES" TO "SPMIGUSER";
  GRANT INSERT ON "SPIREMGR"."EXPORT_LICENCES" TO "SPMIGUSER";
  GRANT DELETE ON "SPIREMGR"."EXPORT_LICENCES" TO "SPMIGUSER";
  GRANT REFERENCES ON "SPIREMGR"."EXPORT_LICENCES" TO "BPMMGR";
  GRANT SELECT ON "SPIREMGR"."EXPORT_LICENCES" TO "BPMMGR";
  GRANT INDEX ON "SPIREMGR"."EXPORT_LICENCES" TO "BPMMGR";
  GRANT SELECT ON "SPIREMGR"."EXPORT_LICENCES" TO "APPENV";
