--------------------------------------------------------
--  DDL for Table FILE_TRANSMISSIONS
--------------------------------------------------------

  CREATE TABLE "PORTALMGR"."FILE_TRANSMISSIONS" 
   (	"ID" NUMBER, 
	"STATUS" VARCHAR2(20 BYTE), 
	"TRANSMISSION_TYPE_MNEM" VARCHAR2(50 BYTE), 
	"TRANSMISSION_TYPE_CONFIG_ID" NUMBER, 
	"RETRY_OF_TRANSMISSION_ID" NUMBER, 
	"CREATED_DATETIME" DATE, 
	"SCHEDULED_DATETIME" DATE, 
	"STARTED_DATETIME" DATE, 
	"FINISHED_DATETIME" DATE, 
	"LOG_XML" "SYS"."XMLTYPE" , 
	"PARAM_XML" "SYS"."XMLTYPE" 
   ) ;
  GRANT SELECT ON "PORTALMGR"."FILE_TRANSMISSIONS" TO "APPENV";
