--------------------------------------------------------
--  DDL for Table FILE_FOLDER_TYPES
--------------------------------------------------------

  CREATE TABLE "DECMGR"."FILE_FOLDER_TYPES" 
   (	"FILE_FOLDER_TYPE" VARCHAR2(30 BYTE), 
	"XML_DATA" "SYS"."XMLTYPE" 
   ) ;
  GRANT UPDATE ON "DECMGR"."FILE_FOLDER_TYPES" TO "APPENV";
  GRANT INSERT ON "DECMGR"."FILE_FOLDER_TYPES" TO "APPENV";
  GRANT SELECT ON "DECMGR"."FILE_FOLDER_TYPES" TO "APPENV";
  GRANT REFERENCES ON "DECMGR"."FILE_FOLDER_TYPES" TO "XVIEWMGR";
