--------------------------------------------------------
--  DDL for Table FILE_VERSIONS
--------------------------------------------------------

  CREATE TABLE "DECMGR"."FILE_VERSIONS" 
   (	"ID" NUMBER(12,0), 
	"FFT_ID" NUMBER(12,0), 
	"STATUS" VARCHAR2(20 BYTE), 
	"VERSION" NUMBER(4,0), 
	"METADATA_XML" "SYS"."XMLTYPE" , 
	"SECURE_LOB_REF" REF "SECUREMGR"."SECURE_LOB" , 
	"CREATE_BY_WUA_ID" NUMBER(12,0), 
	"CREATE_START_DATETIME" DATE, 
	"CREATE_END_DATETIME" DATE, 
	"VIRUS_CHECK_DATETIME" DATE, 
	"SIGN_CHECK_DATETIME" DATE, 
	"STATUS_CONTROL" VARCHAR2(1 BYTE), 
	"LAST_SYSTEM_MESSAGE" VARCHAR2(4000 BYTE), 
	"FOX_FILE_ID" VARCHAR2(4000 BYTE), 
	SCOPE FOR ("SECURE_LOB_REF") IS "SECUREMGR"."SECURE_LOBS" 
   ) ;
