--------------------------------------------------------
--  DDL for Table FILE_FOLDER_USAGES
--------------------------------------------------------

  CREATE TABLE "DECMGR"."FILE_FOLDER_USAGES" 
   (	"FF_ID" NUMBER(12,0), 
	"UREF" VARCHAR2(50 BYTE), 
	"PURPOSE" VARCHAR2(30 BYTE), 
	"START_DATETIME" DATE, 
	"END_DATETIME" DATE
   ) ;
  GRANT SELECT ON "DECMGR"."FILE_FOLDER_USAGES" TO "BISAPIMGR";
  GRANT SELECT ON "DECMGR"."FILE_FOLDER_USAGES" TO "SPIREMGR";
  GRANT UPDATE ON "DECMGR"."FILE_FOLDER_USAGES" TO "SPIREMGR";
  GRANT SELECT ON "DECMGR"."FILE_FOLDER_USAGES" TO "BPMMGR";
  GRANT SELECT ON "DECMGR"."FILE_FOLDER_USAGES" TO "APPENV";
