--------------------------------------------------------
--  DDL for Table FOOTNOTES
--------------------------------------------------------

  CREATE TABLE "SDBPUBMGR"."FOOTNOTES" 
   (	"ID" NUMBER(*,0), 
	"TEXT" VARCHAR2(4000 BYTE), 
	"STATUS" VARCHAR2(30 BYTE)
   ) ;
  GRANT SELECT ON "SDBPUBMGR"."FOOTNOTES" TO "SDBMGR";
  GRANT UPDATE ON "SDBPUBMGR"."FOOTNOTES" TO "SDBMGR";
  GRANT INSERT ON "SDBPUBMGR"."FOOTNOTES" TO "SDBMGR";
  GRANT DELETE ON "SDBPUBMGR"."FOOTNOTES" TO "SDBMGR";
