--------------------------------------------------------
--  DDL for Table FOX_THREAD_TRACKS
--------------------------------------------------------

  CREATE TABLE "FOX5MGR"."FOX_THREAD_TRACKS" 
   (	"ID" VARCHAR2(50 BYTE), 
	"SERVER_HOSTNAME" VARCHAR2(500 BYTE), 
	"SERVER_CONTEXT" VARCHAR2(100 BYTE), 
	"TRACK_DATA" "XMLTYPE", 
	"REQUEST_ID" VARCHAR2(50 BYTE), 
	"OVERALL_TIME_MS" NUMBER, 
	"TRACK_WRITTEN_TIMESTAMP" TIMESTAMP (6), 
	"TRACK_OPEN_TIMESTAMP" TIMESTAMP (6), 
	"TRACK_CLOSE_TIMESTAMP" TIMESTAMP (6), 
	"THREAD_ID" VARCHAR2(100 BYTE), 
	"WUA_ID" NUMBER, 
	"WUS_ID" VARCHAR2(100 BYTE), 
	"THREAD_DESERIALISE_TIME_MS" NUMBER, 
	"MODULE_LOAD_TIME_MS" NUMBER, 
	"MODULE_START_NAME" VARCHAR2(500 BYTE), 
	"STATE_START_NAME" VARCHAR2(500 BYTE), 
	"RAMP_UP_TIME_MS" NUMBER, 
	"ACTION_TYPE" VARCHAR2(50 BYTE), 
	"ACTION_NAME" VARCHAR2(500 BYTE), 
	"ACTION_TIME_MS" NUMBER, 
	"RESPONSE_TYPE" VARCHAR2(50 BYTE), 
	"RESPONSE_TIME_MS" NUMBER, 
	"MODULE_END_NAME" VARCHAR2(500 BYTE), 
	"STATE_END_NAME" VARCHAR2(500 BYTE), 
	"RAMP_DOWN_TIME_MS" NUMBER, 
	"THREAD_SERIALISE_TIME_MS" NUMBER, 
	"DATABASE_TIME_MS" NUMBER, 
	"GET_CONNECTION_TIME_MS" NUMBER, 
	"THREAD_LOCK_MANAGEMENT_TIME_MS" NUMBER
   ) ;
