--------------------------------------------------------
--  DDL for Table FOX_COMPONENTS
--------------------------------------------------------

  CREATE TABLE "ENVMGR"."FOX_COMPONENTS" 
   (	"NAME" VARCHAR2(80 BYTE), 
	"TYPE" VARCHAR2(30 BYTE), 
	"DATA" CLOB, 
	"BINDATA" BLOB, 
	"ENGINE_MIRROR" VARCHAR2(1 BYTE)
   ) 
 LOB ("DATA") STORE AS BASICFILE "FOX_COMPONENTS_DATA"(DISABLE STORAGE IN ROW CHUNK 8192 RETENTION 
  CACHE ) 
 LOB ("BINDATA") STORE AS BASICFILE "FOX_COMPONENTS_BINDATA"(DISABLE STORAGE IN ROW CHUNK 8192 RETENTION 
  CACHE ) ;
  GRANT SELECT ON "ENVMGR"."FOX_COMPONENTS" TO "APPENV";
