--------------------------------------------------------
--  DDL for Table FOX_COMPONENTS_SPIRE_31
--------------------------------------------------------

  CREATE TABLE "SAVEMGR"."FOX_COMPONENTS_SPIRE_31" 
   (	"NAME" VARCHAR2(80 BYTE), 
	"TYPE" VARCHAR2(30 BYTE), 
	"DATA" CLOB, 
	"BINDATA" BLOB, 
	"ENGINE_MIRROR" VARCHAR2(1 BYTE)
   ) ;

   COMMENT ON TABLE "SAVEMGR"."FOX_COMPONENTS_SPIRE_31"  IS 'Save of "ENVMGR"."FOX_COMPONENTS_SPIRE" at 27-DEC-2012 14:33:29';
  GRANT SELECT ON "SAVEMGR"."FOX_COMPONENTS_SPIRE_31" TO "ENVMGR";
