--------------------------------------------------------
--  DDL for Table FOX_ENGINE_REQUESTS
--------------------------------------------------------

  CREATE TABLE "FOX5MGR"."FOX_ENGINE_REQUESTS" 
   (	"REQUEST_ID" NUMBER, 
	"ENVIRONMENT_KEY" VARCHAR2(400 BYTE), 
	"ENGINE_LOCATOR" VARCHAR2(4000 BYTE), 
	"WEB_SERVICE_CATEGORY" VARCHAR2(4000 BYTE), 
	"WEB_SERVICE_NAME" VARCHAR2(4000 BYTE), 
	"END_POINT_NAME" VARCHAR2(4000 BYTE), 
	"URL_PARAMS" VARCHAR2(4000 BYTE), 
	"REQUEST_URL" VARCHAR2(4000 BYTE), 
	"LAST_UPDATED_DATETIME" DATE, 
	"LAST_UPDATED_MESSAGE" CLOB, 
	"STATUS" VARCHAR2(100 BYTE), 
	"REQUEST_DATETIME" TIMESTAMP (6), 
	"RESPONSE_STATUS" VARCHAR2(100 BYTE), 
	"RESPONSE_MESSAGE" VARCHAR2(4000 BYTE), 
	"RESPONSE" CLOB, 
	"REQUEST_METHOD" VARCHAR2(100 BYTE), 
	"PARAMETERS" CLOB, 
	"TIMEOUT_SECONDS" NUMBER(*,0), 
	"ENGINE_REQUEST_METHOD" VARCHAR2(100 BYTE)
   ) ;
