--------------------------------------------------------
--  DDL for Table FOX_MODULE_CALL_FACETS
--------------------------------------------------------

  CREATE TABLE "FOX5MGR"."FOX_MODULE_CALL_FACETS" 
   (	"FACET_TYPE" VARCHAR2(200 BYTE), 
	"FACET_KEY" VARCHAR2(1000 BYTE), 
	"MODULE_CALL_ID" VARCHAR2(50 BYTE), 
	"FACET_OBJECT" BLOB, 
	"CREATED_DATETIME" DATE, 
	"LAST_UPDATED_DATETIME" DATE
   ) ;
  GRANT UPDATE ON "FOX5MGR"."FOX_MODULE_CALL_FACETS" TO "APPENV";
  GRANT SELECT ON "FOX5MGR"."FOX_MODULE_CALL_FACETS" TO "APPENV";
  GRANT INSERT ON "FOX5MGR"."FOX_MODULE_CALL_FACETS" TO "APPENV";
  GRANT DELETE ON "FOX5MGR"."FOX_MODULE_CALL_FACETS" TO "APPENV";
