--------------------------------------------------------
--  DDL for Table FOX_USER_THREAD_SESSIONS
--------------------------------------------------------

  CREATE TABLE "FOX5MGR"."FOX_USER_THREAD_SESSIONS" 
   (	"ID" VARCHAR2(100 BYTE), 
	"SESSION_DOM" "SYS"."XMLTYPE" , 
	"SESSION_DOM_CHANGE_NUMBER" VARCHAR2(50 BYTE)
   ) ;
  GRANT UPDATE ON "FOX5MGR"."FOX_USER_THREAD_SESSIONS" TO "APPENV";
  GRANT SELECT ON "FOX5MGR"."FOX_USER_THREAD_SESSIONS" TO "APPENV";
  GRANT INSERT ON "FOX5MGR"."FOX_USER_THREAD_SESSIONS" TO "APPENV";
  GRANT DELETE ON "FOX5MGR"."FOX_USER_THREAD_SESSIONS" TO "APPENV";
