--------------------------------------------------------
--  DDL for Table FOX_INTERNAL_DOMS
--------------------------------------------------------

  CREATE TABLE "FOX5MGR"."FOX_INTERNAL_DOMS" 
   (	"MODULE_CALL_ID" VARCHAR2(50 BYTE), 
	"DOCUMENT_NAME" VARCHAR2(100 BYTE), 
	"XML_DATA" "SYS"."XMLTYPE" 
   ) ;
  GRANT UPDATE ON "FOX5MGR"."FOX_INTERNAL_DOMS" TO "APPENV";
  GRANT SELECT ON "FOX5MGR"."FOX_INTERNAL_DOMS" TO "APPENV";
  GRANT INSERT ON "FOX5MGR"."FOX_INTERNAL_DOMS" TO "APPENV";
  GRANT DELETE ON "FOX5MGR"."FOX_INTERNAL_DOMS" TO "APPENV";
