--------------------------------------------------------
--  DDL for Table FOX_REQUEST_LOG
--------------------------------------------------------

  CREATE TABLE "FOX5MGR"."FOX_REQUEST_LOG" 
   (	"ID" VARCHAR2(50 BYTE), 
	"SERVER_HOSTNAME" VARCHAR2(500 BYTE), 
	"SERVER_CONTEXT" VARCHAR2(100 BYTE), 
	"REQUEST_URI" VARCHAR2(4000 BYTE), 
	"REQUEST_START_TIMESTAMP" TIMESTAMP (6), 
	"REQUEST_END_TIMESTAMP" TIMESTAMP (6), 
	"HTTP_METHOD" VARCHAR2(20 BYTE), 
	"QUERY_STRING" VARCHAR2(4000 BYTE), 
	"USER_AGENT" VARCHAR2(4000 BYTE), 
	"FOX_SESSION_ID" VARCHAR2(200 BYTE), 
	"ORIGIN_IP" VARCHAR2(20 BYTE), 
	"FORWARDED_FOR" VARCHAR2(4000 BYTE), 
	"RESPONSE_CODE" NUMBER, 
	"USER_EXPERIENCE_TIME_MS" NUMBER, 
	"USER_EXPERIENCE_DETAIL_XML" "XMLTYPE", 
	"LOG_CREATED_TIMESTAMP" TIMESTAMP (6), 
	"LOG_UPDATED_TIMESTAMP" TIMESTAMP (6)
   ) ;
