--------------------------------------------------------
--  DDL for Table FOX_MODULE_CALLS
--------------------------------------------------------

  CREATE TABLE "FOX5MGR"."FOX_MODULE_CALLS" 
   (	"CALL_ID" VARCHAR2(50 BYTE), 
	"STACK_POSITION" NUMBER(*,0), 
	"THREAD_ID" VARCHAR2(100 BYTE), 
	"APP_MNEM" VARCHAR2(50 BYTE), 
	"MODULE_NAME" VARCHAR2(80 BYTE), 
	"THEME_NAME" VARCHAR2(100 BYTE), 
	"STORAGE_LOCATIONS" CLOB, 
	"CALLBACK_HANDLERS" CLOB, 
	"SECURITY_SCOPE" CLOB, 
	"CREATED_DATETIME" DATE, 
	"LAST_UPDATED_DATETIME" DATE, 
	"XPATH_VARIABLES" BLOB
   ) ;
