--------------------------------------------------------
--  DDL for Table FOX_THREAD_LOG
--------------------------------------------------------

  CREATE TABLE "FOXMGR"."FOX_THREAD_LOG" 
   (	"NAME" VARCHAR2(80 BYTE), 
	"TYPE" VARCHAR2(30 BYTE), 
	"DATA" CLOB, 
	"BINDATA" BLOB, 
	"CREATED_BY" VARCHAR2(30 BYTE), 
	"CREATED_DATE" DATE, 
	"LAST_UPDATED_BY" VARCHAR2(30 BYTE), 
	"LAST_UPDATED_DATE" DATE, 
	"FOX_REQUEST_ID" NUMBER
   ) 
 LOB ("DATA") STORE AS BASICFILE "FOX_THREAD_LOG_DATA"(DISABLE STORAGE IN ROW CHUNK 8192 RETENTION 
  CACHE ) 
 LOB ("BINDATA") STORE AS BASICFILE "FOX_THREAD_LOG_BINDATA"(DISABLE STORAGE IN ROW CHUNK 8192 RETENTION 
  CACHE )  ENABLE ROW MOVEMENT ;
