--------------------------------------------------------
--  DDL for Table FOX_ENGINES
--------------------------------------------------------

  CREATE TABLE "FOX5MGR"."FOX_ENGINES" 
   (	"ENGINE_LOCATOR" VARCHAR2(4000 BYTE), 
	"ENVIRONMENT_KEY" VARCHAR2(100 BYTE), 
	"STATUS" VARCHAR2(30 BYTE), 
	"LAST_UPDATED_DATETIME" DATE, 
	"LAST_UPDATED_SYSTEM_MESSAGE" CLOB, 
	"NOT_RESPONDING_SINCE_DATETIME" DATE, 
	"SECURITY_TOKEN" VARCHAR2(4000 BYTE), 
	"ENGINE_ACCESS_URI" VARCHAR2(4000 BYTE)
   ) ;
