--------------------------------------------------------
--  DDL for Table FOX_DOWNLOAD_PARCELS
--------------------------------------------------------

  CREATE TABLE "FOX5MGR"."FOX_DOWNLOAD_PARCELS" 
   (	"ID" VARCHAR2(1000 BYTE), 
	"THREAD_ID" VARCHAR2(100 BYTE), 
	"DATA_CLOB" CLOB, 
	"CREATED_DATETIME" DATE
   ) ;
  GRANT UPDATE ON "FOX5MGR"."FOX_DOWNLOAD_PARCELS" TO "APPENV";
  GRANT SELECT ON "FOX5MGR"."FOX_DOWNLOAD_PARCELS" TO "APPENV";
  GRANT INSERT ON "FOX5MGR"."FOX_DOWNLOAD_PARCELS" TO "APPENV";
  GRANT DELETE ON "FOX5MGR"."FOX_DOWNLOAD_PARCELS" TO "APPENV";
