--------------------------------------------------------
--  DDL for Table FOX_THREADS
--------------------------------------------------------

  CREATE TABLE "FOX5MGR"."FOX_THREADS" 
   (	"THREAD_ID" VARCHAR2(100 BYTE), 
	"APP_MNEM" VARCHAR2(50 BYTE), 
	"USER_THREAD_SESSION_ID" VARCHAR2(100 BYTE), 
	"CHANGE_NUMBER" VARCHAR2(50 BYTE), 
	"THREAD_PROPERTY_MAP" BLOB, 
	"FIELD_SET" BLOB, 
	"AUTHENTICATION_CONTEXT" CLOB, 
	"CREATED_DATETIME" DATE, 
	"LAST_UPDATED_DATETIME" DATE, 
	"LOCKED_BY" VARCHAR2(500 BYTE), 
	"LOCKED_SINCE_DATETIME" DATE, 
	"FOX_SESSION_ID" VARCHAR2(128 BYTE)
   ) ;
  GRANT UPDATE ON "FOX5MGR"."FOX_THREADS" TO "APPENV";
  GRANT SELECT ON "FOX5MGR"."FOX_THREADS" TO "APPENV";
  GRANT INSERT ON "FOX5MGR"."FOX_THREADS" TO "APPENV";
  GRANT DELETE ON "FOX5MGR"."FOX_THREADS" TO "APPENV";
