--------------------------------------------------------
--  DDL for Table FOX_CONNECTIONS
--------------------------------------------------------

  CREATE TABLE "FOX5MGR"."FOX_CONNECTIONS" 
   (	"POOL_NAME" VARCHAR2(30 BYTE), 
	"ENGINE_LOCATOR" VARCHAR2(4000 BYTE), 
	"ENVIRONMENT_KEY" VARCHAR2(100 BYTE), 
	"USERNAME" VARCHAR2(30 BYTE), 
	"MIN_POOL_SIZE" NUMBER(*,0), 
	"MAX_POOL_SIZE" NUMBER(*,0), 
	"MAX_RECYCLES" NUMBER(*,0), 
	"CONNECTION_TIMEOUT_MS" NUMBER, 
	"CONNECTION_INIT_SQL" VARCHAR2(4000 BYTE), 
	"CONNECTION_CHECKOUT_SQL" VARCHAR2(4000 BYTE), 
	"CONNECTION_CHECKIN_SQL" VARCHAR2(4000 BYTE), 
	"DEFAULT_CONNECTION" VARCHAR2(5 BYTE)
   ) ;
