--------------------------------------------------------
--  DDL for Table FOX_COMPONENTS_SPIRE_30
--------------------------------------------------------

  CREATE TABLE "SAVEMGR"."FOX_COMPONENTS_SPIRE_30" 
   (	"NAME" VARCHAR2(80 BYTE), 
	"TYPE" VARCHAR2(30 BYTE), 
	"DATA" CLOB, 
	"BINDATA" BLOB, 
	"ENGINE_MIRROR" VARCHAR2(1 BYTE)
   ) ;

   COMMENT ON TABLE "SAVEMGR"."FOX_COMPONENTS_SPIRE_30"  IS 'Save of "ENVMGR"."FOX_COMPONENTS_SPIRE" at 17-OCT-2012 15:45:35';
  GRANT SELECT ON "SAVEMGR"."FOX_COMPONENTS_SPIRE_30" TO "ENVMGR";
