--------------------------------------------------------
--  DDL for Table FOX_REQUESTS
--------------------------------------------------------

  CREATE TABLE "FOXMGR"."FOX_REQUESTS" 
   (	"ID" NUMBER, 
	"HOSTNAME" VARCHAR2(100 BYTE), 
	"CONTEXT" VARCHAR2(100 BYTE), 
	"APP_NAME" VARCHAR2(50 BYTE), 
	"URI" VARCHAR2(4000 BYTE), 
	"METHOD" VARCHAR2(10 BYTE), 
	"USER_AGENT" VARCHAR2(4000 BYTE), 
	"XFSESSIONID" VARCHAR2(40 BYTE), 
	"ORIGINID" VARCHAR2(40 BYTE), 
	"JSESSIONID" VARCHAR2(120 BYTE), 
	"WUS_ID" VARCHAR2(40 BYTE), 
	"THREAD_REF" VARCHAR2(50 BYTE), 
	"START_DATETIME" DATE, 
	"END_DATETIME" DATE, 
	"XML_DATA" "FOXMGR"."XMLTYPE", 
	"CLIENT_INFO_NVP" VARCHAR2(4000 BYTE)
   ) ;
  GRANT UPDATE ON "FOXMGR"."FOX_REQUESTS" TO "APPENV";
  GRANT SELECT ON "FOXMGR"."FOX_REQUESTS" TO "APPENV";
  GRANT INSERT ON "FOXMGR"."FOX_REQUESTS" TO "APPENV";
