--------------------------------------------------------
--  DDL for Table FOX_UPLOAD_LOG
--------------------------------------------------------

  CREATE TABLE "FOXMGR"."FOX_UPLOAD_LOG" 
   (	"FILE_ID" VARCHAR2(20 BYTE), 
	"APP_MNEM" VARCHAR2(50 BYTE), 
	"APP_HOST" VARCHAR2(100 BYTE), 
	"WUA_ID" NUMBER, 
	"MODULE" VARCHAR2(255 BYTE), 
	"STATE" VARCHAR2(255 BYTE), 
	"FILE_APPROX_SIZE" NUMBER, 
	"FILE_CONTENT_TYPE" VARCHAR2(100 BYTE), 
	"STARTED_DATE" DATE, 
	"COMPLETED_DATE" DATE, 
	"FAILED_DATE" DATE, 
	"FAIL_REASON" CLOB, 
	"UPLOAD_WINDOW_ID" VARCHAR2(25 BYTE), 
	"CLIENT_IP" VARCHAR2(25 BYTE), 
	"MAGIC_MIME_TYPES" VARCHAR2(200 BYTE), 
	"FILENAME" VARCHAR2(200 BYTE), 
	"XML_DATA" "FOXMGR"."XMLTYPE"
   ) 
 LOB ("FAIL_REASON") STORE AS BASICFILE "CLOB"(ENABLE STORAGE IN ROW CHUNK 8192 RETENTION 
  NOCACHE LOGGING ) ;
