--------------------------------------------------------
--  DDL for Table FOX_TEMP_RESOURCES
--------------------------------------------------------

  CREATE TABLE "FOX5MGR"."FOX_TEMP_RESOURCES" 
   (	"ID" VARCHAR2(500 BYTE), 
	"DATA_CLOB" CLOB, 
	"DATA_BLOB" BLOB, 
	"CREATED_DATETIME" DATE, 
	"LAST_UPDATED_DATETIME" DATE
   ) ;
  GRANT UPDATE ON "FOX5MGR"."FOX_TEMP_RESOURCES" TO "APPENV";
  GRANT SELECT ON "FOX5MGR"."FOX_TEMP_RESOURCES" TO "APPENV";
  GRANT INSERT ON "FOX5MGR"."FOX_TEMP_RESOURCES" TO "APPENV";
  GRANT DELETE ON "FOX5MGR"."FOX_TEMP_RESOURCES" TO "APPENV";
