--------------------------------------------------------
--  DDL for Table GOODS_INCIDENTS
--------------------------------------------------------

  CREATE TABLE "SDBPUBMGR"."GOODS_INCIDENTS" 
   (	"ID" NUMBER(*,0), 
	"INC_ID" NUMBER(*,0), 
	"TYPE" VARCHAR2(30 BYTE), 
	"GOODS_ITEM_ID" NUMBER(*,0), 
	"DEST_COUNTRY_ID" NUMBER(*,0), 
	"SOURCE_COUNTRY_GRP_ID" NUMBER(*,0), 
	"REPORT_DATE" DATE, 
	"ELA_GRP_ID" NUMBER(*,0), 
	"START_DATE" DATE, 
	"VERSION_NO" NUMBER(*,0), 
	"BATCH_ID" NUMBER(*,0), 
	"STATUS_CONTROL" VARCHAR2(1 BYTE)
   ) ;
  GRANT UPDATE ON "SDBPUBMGR"."GOODS_INCIDENTS" TO "SDBMGR";
  GRANT SELECT ON "SDBPUBMGR"."GOODS_INCIDENTS" TO "SDBMGR";
  GRANT INSERT ON "SDBPUBMGR"."GOODS_INCIDENTS" TO "SDBMGR";
