--------------------------------------------------------
--  DDL for Table GOODS_CHECKER_ENTRY_DETAILS
--------------------------------------------------------

  CREATE TABLE "SPIREMGR"."GOODS_CHECKER_ENTRY_DETAILS" 
   (	"ID" NUMBER, 
	"GCE_ID" NUMBER, 
	"GCR_ID" NUMBER, 
	"LAST_MODIFIED_IN_REVISION" NUMBER, 
	"START_DATETIME" DATE, 
	"END_DATETIME" DATE, 
	"STATUS_CONTROL" VARCHAR2(1 BYTE), 
	"STATUS" VARCHAR2(10 BYTE), 
	"XML_DATA" "SYS"."XMLTYPE" , 
	"LAST_UPDATED_DATETIME" DATE, 
	"LAST_UPDATED_BY_WUA_ID" NUMBER
   ) 
 XMLTYPE COLUMN "XML_DATA" STORE AS SECUREFILE BINARY XML "GOODS_CHECKER_XML"(DISABLE STORAGE IN ROW CHUNK 8192
  CACHE  NOCOMPRESS  KEEP_DUPLICATES ) ALLOW NONSCHEMA DISALLOW ANYSCHEMA ;
