--------------------------------------------------------
--  DDL for Table GOODS_INCIDENTS_FIV5411
--------------------------------------------------------

  CREATE TABLE "SAVEMGR"."GOODS_INCIDENTS_FIV5411" 
   (	"ID" NUMBER(*,0), 
	"INC_ID" NUMBER(*,0), 
	"TYPE" VARCHAR2(30 BYTE), 
	"GOODS_ITEM_ID" NUMBER(*,0), 
	"DEST_COUNTRY_ID" NUMBER(*,0), 
	"SOURCE_COUNTRY_GRP_ID" NUMBER(*,0), 
	"REPORT_DATE" DATE, 
	"ELA_GRP_ID" NUMBER(*,0), 
	"START_DATE" DATE, 
	"VERSION_NO" NUMBER(*,0), 
	"STATUS_CONTROL" VARCHAR2(1 BYTE), 
	"BATCH_ID" NUMBER(*,0)
   ) ;

   COMMENT ON TABLE "SAVEMGR"."GOODS_INCIDENTS_FIV5411"  IS 'Save of "SDBMGR"."GOODS_INCIDENTS" at 27-APR-2018 14:52:57';
  GRANT SELECT ON "SAVEMGR"."GOODS_INCIDENTS_FIV5411" TO "SDBMGR";
