--------------------------------------------------------
--  DDL for Table GOODS_CHECKER_IMAGES
--------------------------------------------------------

  CREATE TABLE "SPIREMGR"."GOODS_CHECKER_IMAGES" 
   (	"FILE_ID" VARCHAR2(20 BYTE), 
	"FILE_CONTENT" BLOB, 
	"CREATED_DATE" DATE, 
	"CREATED_BY_WUA_ID" NUMBER
   ) ;
  GRANT UPDATE ON "SPIREMGR"."GOODS_CHECKER_IMAGES" TO "APPENV";
  GRANT SELECT ON "SPIREMGR"."GOODS_CHECKER_IMAGES" TO "APPENV";
  GRANT INSERT ON "SPIREMGR"."GOODS_CHECKER_IMAGES" TO "APPENV";
