--------------------------------------------------------
--  DDL for Table GRADING_BREAKDOWN_UPLOADS
--------------------------------------------------------

  CREATE TABLE "PVEXMGR"."GRADING_BREAKDOWN_UPLOADS" 
   (	"FILE_ID" VARCHAR2(30 BYTE), 
	"FILE_DESCRIPTION" VARCHAR2(4000 BYTE), 
	"FILE_CONTENT" BLOB, 
	"FILE_PARSED" "XMLTYPE", 
	"FILE_TRANSFORMED" "XMLTYPE", 
	"UPLOADED_DATE" DATE, 
	"UPLOADED_BY" NUMBER(12,0), 
	"PEA_ID" NUMBER, 
	"STATUS_CONTROL" VARCHAR2(1 BYTE), 
	"FILE_METADATA_XML" "SYS"."XMLTYPE" , 
	"VERSION_NO" NUMBER
   ) 
 XMLTYPE COLUMN "FILE_METADATA_XML" STORE AS SECUREFILE BINARY XML "GRADING_BREAKDOWN_XML_METADATA"(DISABLE STORAGE IN ROW CHUNK 8192
  CACHE  NOCOMPRESS  KEEP_DUPLICATES ) ALLOW NONSCHEMA DISALLOW ANYSCHEMA ;
