--------------------------------------------------------
--  DDL for Table INBOX
--------------------------------------------------------

  CREATE TABLE "JAMESMGR"."INBOX" 
   (	"MESSAGE_NAME" VARCHAR2(200 BYTE), 
	"REPOSITORY_NAME" VARCHAR2(255 BYTE), 
	"MESSAGE_STATE" VARCHAR2(30 BYTE), 
	"ERROR_MESSAGE" VARCHAR2(200 BYTE), 
	"SENDER" VARCHAR2(255 BYTE), 
	"RECIPIENTS" VARCHAR2(1000 BYTE), 
	"REMOTE_HOST" VARCHAR2(100 BYTE), 
	"REMOTE_ADDR" VARCHAR2(20 BYTE), 
	"MESSAGE_BODY" BLOB, 
	"MESSAGE_ATTRIBUTES" BLOB, 
	"LAST_UPDATED" DATE, 
	"MESSAGE_SUBJECT" VARCHAR2(80 BYTE)
   ) ;
