--------------------------------------------------------
--  DDL for Table INTENTION_SET_INTENTIONS
--------------------------------------------------------

  CREATE TABLE "BPMMGR"."INTENTION_SET_INTENTIONS" 
   (	"IS_ID" NUMBER(12,0), 
	"IN_ID" NUMBER(12,0), 
	"START_DATETIME" DATE, 
	"END_DATETIME" DATE, 
	"PURPOSE" VARCHAR2(30 BYTE)
   ) ;
  GRANT SELECT ON "BPMMGR"."INTENTION_SET_INTENTIONS" TO "BISAPIMGR";
  GRANT SELECT ON "BPMMGR"."INTENTION_SET_INTENTIONS" TO "PVEXMGR";
  GRANT SELECT ON "BPMMGR"."INTENTION_SET_INTENTIONS" TO "SPIREMGR";
  GRANT UPDATE ON "BPMMGR"."INTENTION_SET_INTENTIONS" TO "DECMGR";
  GRANT SELECT ON "BPMMGR"."INTENTION_SET_INTENTIONS" TO "DECMGR";
  GRANT INSERT ON "BPMMGR"."INTENTION_SET_INTENTIONS" TO "DECMGR";
  GRANT UPDATE ON "BPMMGR"."INTENTION_SET_INTENTIONS" TO "APPENV";
  GRANT SELECT ON "BPMMGR"."INTENTION_SET_INTENTIONS" TO "APPENV";
  GRANT INSERT ON "BPMMGR"."INTENTION_SET_INTENTIONS" TO "APPENV";
