--------------------------------------------------------
--  DDL for Table INTENTION_SETS
--------------------------------------------------------

  CREATE TABLE "BPMMGR"."INTENTION_SETS" 
   (	"ID" NUMBER(12,0), 
	"XML_DATA" "SYS"."XMLTYPE" , 
	"DC_ID" NUMBER, 
	"DOMAIN" VARCHAR2(30 BYTE), 
	"PRIMARY_DATA_UREF" VARCHAR2(50 BYTE), 
	"SECONDARY_DATA_UREF" VARCHAR2(50 BYTE)
   ) ;
  GRANT SELECT ON "BPMMGR"."INTENTION_SETS" TO "PVEXMGR";
  GRANT SELECT ON "BPMMGR"."INTENTION_SETS" TO "DECMGR";
  GRANT SELECT ON "BPMMGR"."INTENTION_SETS" TO "SPIREMGR";
  GRANT REFERENCES ON "BPMMGR"."INTENTION_SETS" TO "DECMGR";
  GRANT UPDATE ON "BPMMGR"."INTENTION_SETS" TO "APPENV";
  GRANT SELECT ON "BPMMGR"."INTENTION_SETS" TO "APPENV";
  GRANT INSERT ON "BPMMGR"."INTENTION_SETS" TO "APPENV";
  GRANT REFERENCES ON "BPMMGR"."INTENTION_SETS" TO "XVIEWMGR";
