--------------------------------------------------------
--  DDL for Table INTENTIONS
--------------------------------------------------------

  CREATE TABLE "BPMMGR"."INTENTIONS" 
   (	"ID" NUMBER(12,0), 
	"ORIGINAL_ID_ID" NUMBER(12,0)
   ) ;
  GRANT SELECT ON "BPMMGR"."INTENTIONS" TO "PVEXMGR";
  GRANT UPDATE ON "BPMMGR"."INTENTIONS" TO "DECMGR";
  GRANT SELECT ON "BPMMGR"."INTENTIONS" TO "DECMGR";
  GRANT INSERT ON "BPMMGR"."INTENTIONS" TO "DECMGR";
  GRANT SELECT ON "BPMMGR"."INTENTIONS" TO "SPIREMGR";
  GRANT UPDATE ON "BPMMGR"."INTENTIONS" TO "APPENV";
  GRANT SELECT ON "BPMMGR"."INTENTIONS" TO "APPENV";
  GRANT INSERT ON "BPMMGR"."INTENTIONS" TO "APPENV";
