--------------------------------------------------------
--  DDL for Table INTENTION_DETAILS
--------------------------------------------------------

  CREATE TABLE "BPMMGR"."INTENTION_DETAILS" 
   (	"ID" NUMBER(12,0), 
	"IN_ID" NUMBER(12,0), 
	"START_DATETIME" DATE, 
	"END_DATETIME" DATE, 
	"XML_DATA" "SYS"."XMLTYPE" 
   ) ;
  GRANT SELECT ON "BPMMGR"."INTENTION_DETAILS" TO "SPIREMGR";
  GRANT UPDATE ON "BPMMGR"."INTENTION_DETAILS" TO "DECMGR";
  GRANT SELECT ON "BPMMGR"."INTENTION_DETAILS" TO "DECMGR";
  GRANT INSERT ON "BPMMGR"."INTENTION_DETAILS" TO "DECMGR";
  GRANT UPDATE ON "BPMMGR"."INTENTION_DETAILS" TO "APPENV";
  GRANT SELECT ON "BPMMGR"."INTENTION_DETAILS" TO "APPENV";
  GRANT INSERT ON "BPMMGR"."INTENTION_DETAILS" TO "APPENV";
  GRANT REFERENCES ON "BPMMGR"."INTENTION_DETAILS" TO "XVIEWMGR";
