--------------------------------------------------------
--  DDL for Table KF_6596_2
--------------------------------------------------------

  CREATE TABLE "XVIEWMGR"."KF_6596_2" 
   (	"INTERNAL_ID" NUMBER, 
	"LICENSEE_COUNTRY" VARCHAR2(4000 BYTE), 
	"SPIRE_REF" VARCHAR2(100 BYTE), 
	"APPLICATION_TYPE_FORMATTED" VARCHAR2(100 BYTE), 
	"APPLICATION_SUB_TYPE" VARCHAR2(500 BYTE), 
	"LICENSEE" VARCHAR2(32767 BYTE), 
	"CASE_CLOSED_REASON" VARCHAR2(100 BYTE), 
	"CASE_CLOSED_DATETIME" DATE, 
	"LICENCE_STATUS" VARCHAR2(32767 BYTE), 
	"COMPANY_REG_NO" VARCHAR2(9 BYTE), 
	"COMPANY_VAT_NO" VARCHAR2(4000 BYTE)
   ) ;
