--------------------------------------------------------
--  DDL for Table KF_6596_1
--------------------------------------------------------

  CREATE TABLE "XVIEWMGR"."KF_6596_1" 
   (	"INTERNAL_ID" NUMBER, 
	"LICENSEE_COUNTRY" VARCHAR2(4000 BYTE), 
	"LICENCE_REF" VARCHAR2(110 BYTE), 
	"SPIRE_REF" VARCHAR2(100 BYTE), 
	"AMENDMENT_FLAG" VARCHAR2(5 BYTE), 
	"APPLICATION_TYPE_FORMATTED" VARCHAR2(100 BYTE), 
	"LICENSEE" VARCHAR2(32767 BYTE), 
	"OUTCOME" VARCHAR2(32767 BYTE), 
	"GOODS_ARS" CLOB, 
	"GOODS_RATING" VARCHAR2(32767 BYTE), 
	"END_USER_COUNTRIES" VARCHAR2(32767 BYTE), 
	"CASE_CLOSED_REASON" VARCHAR2(100 BYTE), 
	"CASE_CLOSED_DATETIME" DATE, 
	"VAT_NO_FROM_APP" VARCHAR2(32767 BYTE), 
	"COMPANY_REG_NO" VARCHAR2(32767 BYTE), 
	"COMPANY_VAT_NO" VARCHAR2(32767 BYTE)
   ) ;
