--------------------------------------------------------
--  DDL for Table KF_COMPLIANCE_DATA
--------------------------------------------------------

  CREATE TABLE "XVIEWMGR"."KF_COMPLIANCE_DATA" 
   (	"DTI_REF" VARCHAR2(100 BYTE), 
	"LICENCE_REF" VARCHAR2(100 BYTE), 
	"APPLICATION_TYPE" VARCHAR2(100 BYTE), 
	"APPLICATION_SUB_TYPE" VARCHAR2(500 BYTE), 
	"EXPIRY_DATE" DATE, 
	"LICENCE_STATUS" VARCHAR2(20 BYTE), 
	"APPLICANT_NAME" VARCHAR2(8001 BYTE), 
	"SITE_ID" NUMBER, 
	"NC_TOTAL" NUMBER, 
	"NC_2015" NUMBER, 
	"NC_2016" NUMBER, 
	"NC_2017" NUMBER, 
	"NC_2018" NUMBER
   ) ;
