--------------------------------------------------------
--  DDL for Table KF_DETAIL
--------------------------------------------------------

  CREATE TABLE "XVIEWMGR"."KF_DETAIL" 
   (	"A_ELA_GRP_ID" NUMBER(*,0), 
	"I_BATCH_ID" NUMBER(*,0), 
	"A_BATCH_ID" NUMBER(*,0), 
	"TYPE" VARCHAR2(30 BYTE), 
	"STAKEHOLDERS_CONFIRMED" VARCHAR2(5 BYTE), 
	"WITHHELD_STATUS" VARCHAR2(30 BYTE), 
	"STATUS" VARCHAR2(30 BYTE), 
	"EXTERNAL_APPLICATION_ID" NUMBER(*,0), 
	"END_DATE" DATE, 
	"ALLOW_RELEASE_OF_BATCH_ID" NUMBER(*,0), 
	"INCORPORATION_FLAG" NUMBER(*,0), 
	"REPORT_RATING" VARCHAR2(30 BYTE), 
	"UEU_ELA_GRP_ID" NUMBER(*,0), 
	"TP_ELA_GRP_ID" NUMBER(*,0), 
	"TP_ULTIMATE_END_USER_FLAG" NUMBER(*,0), 
	"UEU_ULTIMATE_END_USER_FLAG" NUMBER, 
	"CASE_TYPE" VARCHAR2(100 BYTE)
   ) ;
