--------------------------------------------------------
--  DDL for Table KF_FIV_10022
--------------------------------------------------------

  CREATE TABLE "XVIEWMGR"."KF_FIV_10022" 
   (	"ELA_DETAIL_ID" NUMBER, 
	"ELA_ID" NUMBER, 
	"DTI_REF" VARCHAR2(100 BYTE), 
	"CASE_CLOSED_REASON" VARCHAR2(100 BYTE), 
	"CASE_CLOSED_DATETIME" DATE, 
	"LICENSEE" VARCHAR2(32767 BYTE), 
	"END_USERS" VARCHAR2(32767 BYTE), 
	"CASE_OUTCOME" VARCHAR2(32767 BYTE), 
	"GOODS_OUTCOMES" VARCHAR2(32767 BYTE), 
	"APPLICATION_TYPE" VARCHAR2(100 BYTE), 
	"GOODS_RATING" VARCHAR2(32767 BYTE), 
	"GOODS_ARS" CLOB, 
	"SUBS_APPS_NOT_REFUSED_1" CLOB, 
	"SUBS_APPS_NOT_REFUSED_2" CLOB, 
	"SUBS_APPS_NOT_REFUSED_3" CLOB, 
	"SUBS_APPS_NOT_REFUSED_4" CLOB
   ) ;
