--------------------------------------------------------
--  DDL for Table KF_OFFICER_STAGE_DETAILS_2
--------------------------------------------------------

  CREATE TABLE "XVIEWMGR"."KF_OFFICER_STAGE_DETAILS_2" 
   (	"ELA_UREF" VARCHAR2(43 BYTE), 
	"APPLICATION_TYPE" VARCHAR2(100 BYTE), 
	"CASE_REF" VARCHAR2(100 BYTE), 
	"CASE_CLOSED_DATETIME" DATE, 
	"CASE_CLOSED_REASON" VARCHAR2(100 BYTE), 
	"FIRST_ASSIGNED_CASE_OFFICER" VARCHAR2(4000 BYTE), 
	"TOTAL_CASE_OFFICERS" NUMBER, 
	"STAGE_LABEL" VARCHAR2(200 BYTE), 
	"STAGE_TITLE" VARCHAR2(200 BYTE), 
	"STAGE_START" DATE, 
	"STAGE_END" DATE, 
	"STAGE_BUSINESS_HOURS" NUMBER, 
	"STAGE_CASE_OFFICER_HOURS" NUMBER, 
	"STAGE_RFI_HOURS" NUMBER, 
	"STAGE_REVIEW_HOURS" NUMBER, 
	"STAGE_ESCALATE_HOURS" NUMBER
   ) ;
