--------------------------------------------------------
--  DDL for Table KF_TEMP
--------------------------------------------------------

  CREATE TABLE "XVIEWMGR"."KF_TEMP" 
   (	"INC_ID" NUMBER(*,0), 
	"BATCH_ID" NUMBER(*,0), 
	"REPORT_QUARTER" VARCHAR2(6 BYTE), 
	"LICENCE_ID" NUMBER, 
	"INC_LICENCE_ID" NUMBER(*,0), 
	"ELA_GRP_ID" NUMBER(*,0), 
	"ELA_ID" NUMBER(*,0), 
	"CASE_TYPE" VARCHAR2(100 BYTE), 
	"CASE_SUB_TYPE" VARCHAR2(100 BYTE), 
	"TORTURE_FLAG" NUMBER(*,0), 
	"INCORPORATION_FLAG" NUMBER(*,0), 
	"P_CLASS" VARCHAR2(100 BYTE), 
	"P_CLASS_SUBTYPE" VARCHAR2(100 BYTE), 
	"TYPE" VARCHAR2(30 BYTE), 
	"S_CLASS" VARCHAR2(30 BYTE), 
	"T_CLASS" VARCHAR2(9 BYTE), 
	"LICENCE_CONVERSION_FLAG" NUMBER(*,0), 
	"TEMP_FLAG" VARCHAR2(4 BYTE), 
	"REPORT_DATE" DATE, 
	"GI_ID" NUMBER(*,0), 
	"GOODS_ITEM_ID" NUMBER(*,0), 
	"COUNTRY_NAME" VARCHAR2(4000 BYTE), 
	"COUNTRY_ID" NUMBER, 
	"DEST_COUNTRY_ID" NUMBER(*,0), 
	"ISSUED_ON_APPEAL" NUMBER, 
	"ISSUED_THEN_REVOKED" NUMBER, 
	"SOURCE_COUNTRIES" VARCHAR2(32767 BYTE)
   ) ;
