--------------------------------------------------------
--  DDL for Table MAPSETS_HISTORY_15
--------------------------------------------------------

  CREATE TABLE "SAVEMGR"."MAPSETS_HISTORY_15" 
   (	"ID" NUMBER(12,0), 
	"MAPSET_ID" NUMBER(12,0), 
	"DESCRIPTION" VARCHAR2(200 BYTE), 
	"DATA" "SYS"."XMLTYPE" , 
	"START_DATE" DATE, 
	"END_DATE" DATE, 
	"STATUS_CONTROL" VARCHAR2(1 BYTE), 
	"UPDATED_BY_WUA_ID" NUMBER(12,0)
   ) ;

   COMMENT ON TABLE "SAVEMGR"."MAPSETS_HISTORY_15"  IS 'Save of "ENVMGR"."MAPSETS_HISTORY" at 24-JUN-2011 14:08:27';
  GRANT SELECT ON "SAVEMGR"."MAPSETS_HISTORY_15" TO "ENVMGR";
