--------------------------------------------------------
--  DDL for Table MATRIX_FOLDER_TYPES
--------------------------------------------------------

  CREATE TABLE "DECMGR"."MATRIX_FOLDER_TYPES" 
   (	"XML_DATA" "SYS"."XMLTYPE" , 
	"ID" NUMBER(12,0), 
	"LAST_REFRESH" DATE
   ) ;
  GRANT REFERENCES ON "DECMGR"."MATRIX_FOLDER_TYPES" TO "XVIEWMGR";
  GRANT SELECT ON "DECMGR"."MATRIX_FOLDER_TYPES" TO "XVIEWMGR";
  GRANT REFERENCES ON "DECMGR"."MATRIX_FOLDER_TYPES" TO "BPMMGR";
  GRANT SELECT ON "DECMGR"."MATRIX_FOLDER_TYPES" TO "BPMMGR";
  GRANT UPDATE ON "DECMGR"."MATRIX_FOLDER_TYPES" TO "APPENV";
  GRANT SELECT ON "DECMGR"."MATRIX_FOLDER_TYPES" TO "APPENV";
  GRANT INSERT ON "DECMGR"."MATRIX_FOLDER_TYPES" TO "APPENV";
