--------------------------------------------------------
--  DDL for Table MATRIX_FOLDERS
--------------------------------------------------------

  CREATE TABLE "DECMGR"."MATRIX_FOLDERS" 
   (	"ID" NUMBER(12,0), 
	"XML_DATA" "SYS"."XMLTYPE" , 
	"MFT_ID" NUMBER(12,0), 
	"LAST_UPDATED_DATETIME" DATE
   ) ;
  GRANT REFERENCES ON "DECMGR"."MATRIX_FOLDERS" TO "XVIEWMGR";
  GRANT SELECT ON "DECMGR"."MATRIX_FOLDERS" TO "XVIEWMGR";
  GRANT REFERENCES ON "DECMGR"."MATRIX_FOLDERS" TO "BPMMGR";
  GRANT SELECT ON "DECMGR"."MATRIX_FOLDERS" TO "BPMMGR";
  GRANT UPDATE ON "DECMGR"."MATRIX_FOLDERS" TO "APPENV";
  GRANT SELECT ON "DECMGR"."MATRIX_FOLDERS" TO "APPENV";
  GRANT INSERT ON "DECMGR"."MATRIX_FOLDERS" TO "APPENV";
