--------------------------------------------------------
--  DDL for Table MATRIX_SERVICE_REC_TYPES
--------------------------------------------------------

  CREATE TABLE "DECMGR"."MATRIX_SERVICE_REC_TYPES" 
   (	"URI" VARCHAR2(100 BYTE), 
	"BEHAVIOUR_FILTER" VARCHAR2(10 BYTE), 
	"TYPE_RAW" VARCHAR2(100 BYTE), 
	"TYPE_DISPLAY" VARCHAR2(100 BYTE), 
	"TYPE_INTERNAL" VARCHAR2(100 BYTE), 
	"CREATED_BY" VARCHAR2(30 BYTE), 
	"CREATED_DATETIME" DATE, 
	"LAST_UPDATED_BY" VARCHAR2(30 BYTE), 
	"LAST_UPDATED_DATETIME" DATE
   ) ;
