--------------------------------------------------------
--  DDL for Table MATRIX_SERVICE_CONTROL
--------------------------------------------------------

  CREATE TABLE "DECMGR"."MATRIX_SERVICE_CONTROL" 
   (	"DATABASE_SID" VARCHAR2(30 BYTE), 
	"NODE_NAME" VARCHAR2(60 BYTE), 
	"MATRIX_SERVICE_NAME" VARCHAR2(100 BYTE), 
	"UREF_TYPE" VARCHAR2(6 BYTE), 
	"TRIM_URL" VARCHAR2(200 BYTE), 
	"TRIM_DOMAIN" VARCHAR2(30 BYTE), 
	"TRIM_USERNAME" VARCHAR2(30 BYTE), 
	"TRIM_PASSWORD" VARCHAR2(30 BYTE), 
	"TRIM_DATABASE_ID" VARCHAR2(100 BYTE), 
	"TRIM_LICENCE" VARCHAR2(100 BYTE), 
	"FILING_ENABLED" VARCHAR2(5 BYTE), 
	"CREATE_FOLDER_ENABLED" VARCHAR2(5 BYTE), 
	"OVERRIDE_FOLDER" VARCHAR2(100 BYTE), 
	"OVERRIDE_PREFIX" VARCHAR2(100 BYTE), 
	"MATRIX_MNEMONIC" VARCHAR2(100 BYTE), 
	"FILING_WINDOW_START" VARCHAR2(5 BYTE) DEFAULT '00:00', 
	"FILING_WINDOW_END" VARCHAR2(5 BYTE) DEFAULT '23:59', 
	"TRIM_VERSION" VARCHAR2(10 BYTE), 
	"LAST_FAILED" DATE, 
	"SEARCH_ENABLED" VARCHAR2(5 BYTE), 
	"SEARCH_WINDOW_START" VARCHAR2(5 BYTE) DEFAULT '00:00', 
	"SEARCH_WINDOW_END" VARCHAR2(5 BYTE) DEFAULT '23:59', 
	"CREATE_UNRESOLVED_FOLDER_ENBLD" VARCHAR2(5 BYTE)
   ) ;
