--------------------------------------------------------
--  DDL for Table MEDIA_FOOTNOTE_COUNTRIES
--------------------------------------------------------

  CREATE TABLE "SDBPUBMGR"."MEDIA_FOOTNOTE_COUNTRIES" 
   (	"ID" NUMBER, 
	"ELA_GRP_ID" NUMBER, 
	"MF_GRP_ID" NUMBER, 
	"COUNTRY_ID" NUMBER, 
	"COUNTRY_NAME" VARCHAR2(200 BYTE), 
	"STATUS_CONTROL" VARCHAR2(1 BYTE), 
	"START_DATETIME" DATE, 
	"END_DATETIME" DATE
   ) ;
  GRANT UPDATE ON "SDBPUBMGR"."MEDIA_FOOTNOTE_COUNTRIES" TO "SDBMGR";
  GRANT SELECT ON "SDBPUBMGR"."MEDIA_FOOTNOTE_COUNTRIES" TO "SDBMGR";
  GRANT INSERT ON "SDBPUBMGR"."MEDIA_FOOTNOTE_COUNTRIES" TO "SDBMGR";
