--------------------------------------------------------
--  DDL for Table MF_EU_BATCH_EVENTS_ERROR
--------------------------------------------------------

  CREATE TABLE "SAVEMGR"."MF_EU_BATCH_EVENTS_ERROR" 
   (	"ID" NUMBER(12,0), 
	"EVENT_DATETIME" DATE, 
	"EVENT_LABEL" VARCHAR2(30 BYTE), 
	"EVENT_XML_DATA" "SYS"."XMLTYPE" , 
	"RAISING_WUA_ID" NUMBER(12,0), 
	"RAISING_MODULE_CODE" VARCHAR2(4000 BYTE), 
	"RAISING_MODULE_COMMENT" VARCHAR2(4000 BYTE), 
	"RECONCILING_OPERATION_ID" NUMBER(12,0), 
	"STATUS" VARCHAR2(4000 BYTE), 
	"STATUS_DATETIME" DATE, 
	"UREF" VARCHAR2(50 BYTE)
   ) ;
