--------------------------------------------------------
--  DDL for Table MIGRATED_CONDITIONS
--------------------------------------------------------

  CREATE TABLE "SPIREMGR"."MIGRATED_CONDITIONS" 
   (	"ID" NUMBER, 
	"OGEL" NUMBER, 
	"CONDITION_NUMBER" NUMBER, 
	"CONDITION" VARCHAR2(4000 BYTE), 
	"CONDITION_QUESTION" VARCHAR2(255 CHAR), 
	"CONDITION_PLAIN_TEXT" VARCHAR2(4000 BYTE), 
	"CONDITION_SUMMARY" VARCHAR2(300 CHAR), 
	"CONDITION_LINK" VARCHAR2(1000 BYTE), 
	"LINK_TEXT" VARCHAR2(4000 BYTE), 
	"ANSWER" VARCHAR2(3 BYTE), 
	"QUESTION_HINT" VARCHAR2(1000 BYTE)
   ) ;
