--------------------------------------------------------
--  DDL for Table MIGRATED_LIST_ENTRIES_ORIG
--------------------------------------------------------

  CREATE TABLE "SPIREMGR"."MIGRATED_LIST_ENTRIES_ORIG" 
   (	"ENTRY_ID" NUMBER(5,0), 
	"ENTRY_TYPE" NUMBER(1,0), 
	"PARENT_ID" NUMBER(5,0), 
	"REVISION_ID" NUMBER(5,0), 
	"SORT_LIST" NUMBER(1,0), 
	"SORT_NUM" NUMBER(10,0), 
	"ENTRY_SHORT" VARCHAR2(100 BYTE), 
	"LIST_TITLE" CLOB, 
	"HTML_TITLE" CLOB, 
	"PLAIN_TITLE" CLOB, 
	"HTML_TEXT" CLOB, 
	"PLAIN_TEXT" CLOB, 
	"HTML_AFTER" CLOB, 
	"PLAIN_AFTER" VARCHAR2(4000 BYTE), 
	"PICTURE_KEY" VARCHAR2(4000 BYTE), 
	"TERM_CHOICE_SET" VARCHAR2(50 BYTE), 
	"LIST_DATE" DATE, 
	"ES" VARCHAR2(100 BYTE), 
	"CONTROL_RATING" VARCHAR2(5 BYTE), 
	"GCE_ID" NUMBER, 
	"GCE_CATEGORY" VARCHAR2(50 BYTE), 
	"GCE_ORDER_NUM" NUMBER
   ) ;
