--------------------------------------------------------
--  DDL for Table MONITOR_TESTS
--------------------------------------------------------

  CREATE TABLE "SERVICEMGR"."MONITOR_TESTS" 
   (	"ID" NUMBER, 
	"NAME" VARCHAR2(100 BYTE), 
	"DESCRIPTION" VARCHAR2(4000 BYTE), 
	"PLSQL" CLOB, 
	"LAST_FAIL_DATETIME" DATE, 
	"LAST_TEST_DATETIME" DATE, 
	"LAST_TEST_RESULT" VARCHAR2(10 BYTE), 
	"TEST_FREQUENCY" VARCHAR2(10 BYTE), 
	"ALERT_FREQUENCY" VARCHAR2(10 BYTE), 
	"ALERT_DOMAIN" VARCHAR2(100 BYTE), 
	"ALERT_NEW_SUCCESS" VARCHAR2(1 BYTE), 
	"ALERT_SEVERITY" VARCHAR2(20 BYTE), 
	"LAST_ALERT_DATETIME" DATE, 
	"STATUS" VARCHAR2(10 BYTE), 
	"FAIL_COUNT_FOR_ALERT" NUMBER DEFAULT 1, 
	"FAIL_COUNT" NUMBER DEFAULT 0
   ) ;
