--------------------------------------------------------
--  DDL for Table NAV_BAR_ACTION_CATEGORIES
--------------------------------------------------------

  CREATE TABLE "ENVMGR"."NAV_BAR_ACTION_CATEGORIES" 
   (	"MNEM" VARCHAR2(100 BYTE), 
	"XML_DATA" "SYS"."XMLTYPE" 
   ) 
 XMLTYPE COLUMN "XML_DATA" STORE AS SECUREFILE BINARY XML "NAV_BAR_ACTION_CATEGORIES_XML"(ENABLE STORAGE IN ROW CHUNK 8192
  CACHE  NOCOMPRESS  KEEP_DUPLICATES ) ALLOW NONSCHEMA DISALLOW ANYSCHEMA ;
  GRANT SELECT ON "ENVMGR"."NAV_BAR_ACTION_CATEGORIES" TO "SECUREMGR";
