--------------------------------------------------------
--  DDL for Table NAV_BAR_ACTION_GROUPS
--------------------------------------------------------

  CREATE TABLE "ENVMGR"."NAV_BAR_ACTION_GROUPS" 
   (	"MNEM" VARCHAR2(100 BYTE), 
	"XML_DATA" "SYS"."XMLTYPE" 
   ) 
 XMLTYPE COLUMN "XML_DATA" STORE AS SECUREFILE BINARY XML "NAV_BAR_ACTION_GROUPS_XML"(ENABLE STORAGE IN ROW CHUNK 8192
  CACHE  NOCOMPRESS  KEEP_DUPLICATES ) ALLOW NONSCHEMA DISALLOW ANYSCHEMA ;
