--------------------------------------------------------
--  DDL for Table NOTES
--------------------------------------------------------

  CREATE TABLE "DECMGR"."NOTES" 
   (	"ID" NUMBER, 
	"XML_DATA" "SYS"."XMLTYPE" 
   ) ;
  GRANT REFERENCES ON "DECMGR"."NOTES" TO "XVIEWMGR";
  GRANT REFERENCES ON "DECMGR"."NOTES" TO "BPMMGR";
  GRANT SELECT ON "DECMGR"."NOTES" TO "BPMMGR";
  GRANT INDEX ON "DECMGR"."NOTES" TO "BPMMGR";
  GRANT UPDATE ON "DECMGR"."NOTES" TO "APPENV";
  GRANT SELECT ON "DECMGR"."NOTES" TO "APPENV";
  GRANT INSERT ON "DECMGR"."NOTES" TO "APPENV";
