--------------------------------------------------------
--  DDL for Table NOTIFICATIONS
--------------------------------------------------------

  CREATE TABLE "DECMGR"."NOTIFICATIONS" 
   (	"ID" NUMBER(12,0), 
	"NS_ID" NUMBER(12,0), 
	"DP_ID" NUMBER(12,0), 
	"ORGAN_ID" NUMBER(12,0), 
	"XML_DATA" "SYS"."XMLTYPE" , 
	"PERSON_ID" NUMBER(12,0)
   ) ;
  GRANT UPDATE ON "DECMGR"."NOTIFICATIONS" TO "BISAPIMGR";
  GRANT SELECT ON "DECMGR"."NOTIFICATIONS" TO "BISAPIMGR";
  GRANT UPDATE ON "DECMGR"."NOTIFICATIONS" TO "BPMMGR";
  GRANT UPDATE ON "DECMGR"."NOTIFICATIONS" TO "SPIREMGR";
  GRANT SELECT ON "DECMGR"."NOTIFICATIONS" TO "SPIREMGR";
  GRANT REFERENCES ON "DECMGR"."NOTIFICATIONS" TO "SPIREMGR";
  GRANT REFERENCES ON "DECMGR"."NOTIFICATIONS" TO "XVIEWMGR";
  GRANT SELECT ON "DECMGR"."NOTIFICATIONS" TO "XVIEWMGR";
  GRANT REFERENCES ON "DECMGR"."NOTIFICATIONS" TO "BPMMGR";
  GRANT SELECT ON "DECMGR"."NOTIFICATIONS" TO "BPMMGR";
  GRANT INSERT ON "DECMGR"."NOTIFICATIONS" TO "BPMMGR";
  GRANT INDEX ON "DECMGR"."NOTIFICATIONS" TO "BPMMGR";
  GRANT UPDATE ON "DECMGR"."NOTIFICATIONS" TO "APPENV";
  GRANT SELECT ON "DECMGR"."NOTIFICATIONS" TO "APPENV";
  GRANT INSERT ON "DECMGR"."NOTIFICATIONS" TO "APPENV";
