--------------------------------------------------------
--  DDL for Table NOVATION_DETAILS
--------------------------------------------------------

  CREATE TABLE "PVEXMGR"."NOVATION_DETAILS" 
   (	"ID" NUMBER, 
	"N_ID" NUMBER, 
	"CREATED_DATETIME" DATE, 
	"END_DATETIME" DATE, 
	"STATUS_CONTROL" VARCHAR2(1 BYTE), 
	"XML_DATA" "SYS"."XMLTYPE" , 
	"PF_ID" NUMBER, 
	"STATUS" VARCHAR2(100 BYTE)
   ) 
 XMLTYPE COLUMN "XML_DATA" STORE AS SECUREFILE BINARY XML "NOVATION_DETAILS_XML_DATA"(DISABLE STORAGE IN ROW CHUNK 8192
  CACHE  NOCOMPRESS  KEEP_DUPLICATES ) ALLOW NONSCHEMA DISALLOW ANYSCHEMA ;
