--------------------------------------------------------
--  DDL for Table OGEL_EXPORTER
--------------------------------------------------------

  CREATE TABLE "WARP_OWNER"."OGEL_EXPORTER" 
   (	"ID" NUMBER(6,0), 
	"NAME" VARCHAR2(50 BYTE), 
	"ADDRESS1" VARCHAR2(40 BYTE), 
	"ADDRESS2" VARCHAR2(40 BYTE), 
	"ADDRESS3" VARCHAR2(40 BYTE), 
	"COUNTY" VARCHAR2(40 BYTE), 
	"POSTCODE" VARCHAR2(10 BYTE), 
	"COUNTRY" VARCHAR2(40 BYTE), 
	"PHONE_NO" CHAR(15 BYTE), 
	"FAX_NO" CHAR(15 BYTE), 
	"VAT_NO" VARCHAR2(20 BYTE), 
	"EMAIL_ADDRESS" VARCHAR2(50 BYTE), 
	"CONTACT_SURNAME" VARCHAR2(30 BYTE), 
	"CONTACT_TITLE" VARCHAR2(5 BYTE), 
	"CONTACT_JOB_TITLE" VARCHAR2(30 BYTE), 
	"CONTACT_INITIALS" VARCHAR2(3 BYTE), 
	"RECORD_LAST_UPDATED" DATE, 
	"CREATE_DATE" DATE, 
	"VISITED_DATE" DATE, 
	"COMMENTS" VARCHAR2(250 BYTE), 
	"NOT_ACTIVE" VARCHAR2(1 BYTE)
   ) ;
