--------------------------------------------------------
--  DDL for Table OGL_TYPE_CONDITION_DETAILS
--------------------------------------------------------

  CREATE TABLE "SPIREMGR"."OGL_TYPE_CONDITION_DETAILS" 
   (	"ID" NUMBER, 
	"OTC_ID" NUMBER, 
	"STATUS_CONTROL" VARCHAR2(1 BYTE), 
	"START_DATETIME" DATE, 
	"END_DATETIME" DATE, 
	"CREATED_BY_WUA_ID" NUMBER, 
	"XML_DATA" "SYS"."XMLTYPE" 
   ) ;
  GRANT SELECT ON "SPIREMGR"."OGL_TYPE_CONDITION_DETAILS" TO "XVIEWMGR";
  GRANT REFERENCES ON "SPIREMGR"."OGL_TYPE_CONDITION_DETAILS" TO "XVIEWMGR";
  GRANT SELECT ON "SPIREMGR"."OGL_TYPE_CONDITION_DETAILS" TO "APPENV";
