--------------------------------------------------------
--  DDL for Table OIELS_TBL_DESTINATION
--------------------------------------------------------

  CREATE TABLE "OIELS_OWNER"."OIELS_TBL_DESTINATION" 
   (	"DESTINATION_ID" NUMBER(37,0), 
	"SECTION_D_ID_REF" NUMBER(37,0), 
	"DESTINATION" VARCHAR2(100 BYTE), 
	"NEWDESTINATIONYN" NUMBER(1,0), 
	"MADESEILSAPPYN" NUMBER(1,0), 
	"NUMOFSEILS" VARCHAR2(40 BYTE), 
	"GOVDIRECTYN" NUMBER(1,0), 
	"GOVANDAGENCYYN" NUMBER(1,0), 
	"GOVANDCOMPYN" NUMBER(1,0), 
	"NOTGOVANDCOMPYN" NUMBER(1,0), 
	"OTHERYN" NUMBER(1,0), 
	"SPECIFY" VARCHAR2(4000 BYTE)
   ) ;
