--------------------------------------------------------
--  DDL for Table OIELS_TBL_SECTION_F
--------------------------------------------------------

  CREATE TABLE "OIELS_OWNER"."OIELS_TBL_SECTION_F" 
   (	"SECTION_F_ID" NUMBER(37,0), 
	"DTI_REFERENCE_ID_REF" NUMBER(37,0), 
	"ISCRYPTOGRAPHICYN" NUMBER(1,0), 
	"SPECIFYISCRYPTOGRP" VARCHAR2(4000 BYTE), 
	"ISNUCLEARYN" NUMBER(1,0), 
	"SPECIFYISNUCLEAR" VARCHAR2(4000 BYTE), 
	"ISMASSDESTRUCTIONYN" NUMBER(1,0), 
	"SPECIFYISMASSDESTRUC" VARCHAR2(4000 BYTE), 
	"MIGHTBEMASSDESTRUC_YN" NUMBER(1,0), 
	"SPECIFYMIGHTBEMASSDEST" VARCHAR2(4000 BYTE), 
	"ENDUSE" VARCHAR2(4000 BYTE), 
	"PARTOFPLANTYN" NUMBER(1,0), 
	"SPECIFYPARTOFPLANT" VARCHAR2(4000 BYTE)
   ) ;
