--------------------------------------------------------
--  DDL for Table OIELS_TBL_SECTION_E
--------------------------------------------------------

  CREATE TABLE "OIELS_OWNER"."OIELS_TBL_SECTION_E" 
   (	"SECTION_E_ID" NUMBER(37,0), 
	"DTI_REFERENCE_ID_REF" NUMBER(37,0), 
	"TEMPGOODSYN" NUMBER(1,0), 
	"DEMONSTRATIONYN" NUMBER(1,0), 
	"EXHIBITIONYN" NUMBER(1,0), 
	"REPAIRYN" NUMBER(1,0), 
	"RENTALYN" NUMBER(1,0), 
	"OTHERYN" NUMBER(1,0), 
	"SPECIFYOTHER" VARCHAR2(4000 BYTE), 
	"GOODSCONTROLYN" NUMBER(1,0), 
	"SPECIFYGOODCONTROL" VARCHAR2(4000 BYTE), 
	"OGDREPLYYN" NUMBER(1,0), 
	"SPECIFYOGDREPLY" VARCHAR2(4000 BYTE)
   ) ;
