--------------------------------------------------------
--  DDL for Table OIELS_TBL_GOODSITEM
--------------------------------------------------------

  CREATE TABLE "OIELS_OWNER"."OIELS_TBL_GOODSITEM" 
   (	"GOODSITEM_ID" NUMBER(37,0), 
	"SECTION_F_ID_REF" NUMBER(37,0), 
	"DESTINATION" VARCHAR2(100 BYTE), 
	"DESCRIPTIONOFGOODS" VARCHAR2(4000 BYTE), 
	"MILITARYGOODSYN" NUMBER(1,0), 
	"STATEMILCLASSIFICATION" VARCHAR2(100 BYTE), 
	"NAMEOFGOODITEM" VARCHAR2(4000 BYTE), 
	"SPECIFICAPPUSE" VARCHAR2(4000 BYTE), 
	"PRODUCTIONOFMILGOODSYN" NUMBER(1,0), 
	"SPECIFICPRODUCOFMILGOODS" VARCHAR2(4000 BYTE), 
	"SPECIFYEXPORTCONTROL" VARCHAR2(4000 BYTE), 
	"LICENCEDESCRIPTIONOFGOODS" VARCHAR2(4000 BYTE), 
	"REGIMERATING" VARCHAR2(4000 BYTE), 
	"GOODSTATUS" VARCHAR2(40 BYTE), 
	"MULTIPLE_DESTINATIONS" NUMBER(*,0)
   ) ;
