--------------------------------------------------------
--  DDL for Table OIELS_MIG_LICENCE_NUMBERS
--------------------------------------------------------

  CREATE TABLE "SAVEMGR"."OIELS_MIG_LICENCE_NUMBERS" 
   (	"DTI_REFERENCE_ID_REF" NUMBER(37,0), 
	"LICENCE_ID" NUMBER(37,0), 
	"EXPIRYDATE" VARCHAR2(10 BYTE), 
	"ISSUEDATE" VARCHAR2(10 BYTE), 
	"FINAL_STATUS" VARCHAR2(40 BYTE), 
	"LICENCE_NUMBER" VARCHAR2(40 BYTE)
   ) ;
  GRANT INSERT ON "SAVEMGR"."OIELS_MIG_LICENCE_NUMBERS" TO "OIELS_OWNER";
