--------------------------------------------------------
--  DDL for Table OIELS_TBL_ADVICERECIEVED
--------------------------------------------------------

  CREATE TABLE "OIELS_OWNER"."OIELS_TBL_ADVICERECIEVED" 
   (	"ADVICERECIEVED_ID" NUMBER(37,0), 
	"DTI_REFERENCE_ID_REF" NUMBER(37,0), 
	"OGD_PROVISO" VARCHAR2(4000 BYTE), 
	"COUNTRY" VARCHAR2(100 BYTE), 
	"ADVICE" VARCHAR2(100 BYTE), 
	"DATE_ADVICE_RECEIVED" VARCHAR2(10 BYTE), 
	"ADVISORLIST_ID_REF" NUMBER(37,0), 
	"ADVICESOUGHT_ID_REF" NUMBER(37,0)
   ) ;
