--------------------------------------------------------
--  DDL for Table OIELS_TBL_COMPANY_AUXINFO
--------------------------------------------------------

  CREATE TABLE "OIELS_OWNER"."OIELS_TBL_COMPANY_AUXINFO" 
   (	"AUXCOMPANYINFO_ID" NUMBER(37,0), 
	"MAINCOMPANYINFO_ID_REF" NUMBER(37,0), 
	"DTI_REFERENCE_ID_REF" NUMBER(37,0), 
	"JOBTITLE" VARCHAR2(40 BYTE), 
	"FAX" VARCHAR2(40 BYTE), 
	"TELEPHONE" VARCHAR2(40 BYTE), 
	"EMAILADDRESS" VARCHAR2(100 BYTE), 
	"WEBADDRESS" VARCHAR2(100 BYTE), 
	"AGENTDESTINATION" VARCHAR2(100 BYTE)
   ) ;
