--------------------------------------------------------
--  DDL for Table OIELS_TBL_COMPANY_MAININFO
--------------------------------------------------------

  CREATE TABLE "OIELS_OWNER"."OIELS_TBL_COMPANY_MAININFO" 
   (	"MAINCOMPANYINFO_ID" NUMBER(37,0), 
	"DTI_REFERENCE_ID_REF" NUMBER(37,0), 
	"ORG_NAME" VARCHAR2(100 BYTE), 
	"ADDRESS1" VARCHAR2(100 BYTE), 
	"ADDRESS2" VARCHAR2(100 BYTE), 
	"ADDRESS3" VARCHAR2(100 BYTE), 
	"ADDRESS4" VARCHAR2(100 BYTE), 
	"POSTCODE" VARCHAR2(10 BYTE), 
	"COUNTRY" VARCHAR2(100 BYTE), 
	"ORG_TYPE" VARCHAR2(100 BYTE)
   ) ;
