--------------------------------------------------------
--  DDL for Table OIELS_TBL_AUDITTRAIL
--------------------------------------------------------

  CREATE TABLE "OIELS_OWNER"."OIELS_TBL_AUDITTRAIL" 
   (	"DATETIMESTAMP" VARCHAR2(20 BYTE), 
	"DATESTAMP" VARCHAR2(20 BYTE), 
	"EVENTCODE" VARCHAR2(10 BYTE), 
	"AUTHOROFEVENT" VARCHAR2(100 BYTE), 
	"AUTHORDEPT" VARCHAR2(100 BYTE), 
	"AUTHORORG" VARCHAR2(100 BYTE), 
	"RECEIVEROFEVENT" VARCHAR2(100 BYTE), 
	"RECEIVERDEPT" VARCHAR2(100 BYTE), 
	"RECEIVERORG" VARCHAR2(100 BYTE), 
	"DATAASSOCIATED" VARCHAR2(100 BYTE), 
	"DTIREFERENCENUM" VARCHAR2(100 BYTE), 
	"AUDITTRAIL_ID" NUMBER(37,0)
   ) ;
