--------------------------------------------------------
--  DDL for Table ORGANISATION_UNIT_DETAILS
--------------------------------------------------------

  CREATE TABLE "DECMGR"."ORGANISATION_UNIT_DETAILS" 
   (	"ORGAN_ID" NUMBER(8,0), 
	"XML_DATA" "SYS"."XMLTYPE" , 
	"ID" NUMBER(12,0), 
	"START_DATETIME" DATE, 
	"END_DATETIME" DATE
   ) ;
  GRANT SELECT ON "DECMGR"."ORGANISATION_UNIT_DETAILS" TO "SPIREMGR";
  GRANT INSERT ON "DECMGR"."ORGANISATION_UNIT_DETAILS" TO "SPIREMGR";
  GRANT SELECT ON "DECMGR"."ORGANISATION_UNIT_DETAILS" TO "BISAPIMGR";
  GRANT REFERENCES ON "DECMGR"."ORGANISATION_UNIT_DETAILS" TO "XVIEWMGR";
  GRANT SELECT ON "DECMGR"."ORGANISATION_UNIT_DETAILS" TO "ENVMGR";
  GRANT UPDATE ON "DECMGR"."ORGANISATION_UNIT_DETAILS" TO "APPENV";
  GRANT SELECT ON "DECMGR"."ORGANISATION_UNIT_DETAILS" TO "APPENV";
  GRANT INSERT ON "DECMGR"."ORGANISATION_UNIT_DETAILS" TO "APPENV";
