--------------------------------------------------------
--  DDL for Table PAGE_CONTENT_TYPES
--------------------------------------------------------

  CREATE TABLE "DECMGR"."PAGE_CONTENT_TYPES" 
   (	"PAGE_CONTENT_TYPE" VARCHAR2(30 BYTE), 
	"TITLE" VARCHAR2(100 BYTE), 
	"PREVIEW_MODULE_NAME" VARCHAR2(80 BYTE), 
	"PREVIEW_ENTRY_THEME" VARCHAR2(80 BYTE)
   ) ;
  GRANT UPDATE ON "DECMGR"."PAGE_CONTENT_TYPES" TO "APPENV";
  GRANT SELECT ON "DECMGR"."PAGE_CONTENT_TYPES" TO "APPENV";
  GRANT INSERT ON "DECMGR"."PAGE_CONTENT_TYPES" TO "APPENV";
