--------------------------------------------------------
--  DDL for Table PATCHCORE04420A_BCK
--------------------------------------------------------

  CREATE TABLE "SAVEMGR"."PATCHCORE04420A_BCK" 
   (	"ELA_ID" NUMBER(12,0), 
	"ELA_DETAIL_ID" NUMBER(12,0), 
	"DTI_REF" VARCHAR2(30 BYTE), 
	"OLD_XML" "SYS"."XMLTYPE" , 
	"NEW_XML" "SYS"."XMLTYPE" , 
	"SECURE_LOB_REF" REF "SECUREMGR"."SECURE_LOB" , 
	"PROCESSED_DATETIME" DATE, 
	"RUN_NO" NUMBER, 
	"DIFFERENCE_FLAG" NUMBER, 
	"ERR_MSG" VARCHAR2(4000 BYTE), 
	SCOPE FOR ("SECURE_LOB_REF") IS "SECUREMGR"."SECURE_LOBS" 
   ) ;
