--------------------------------------------------------
--  DDL for Table PATCH_RUNS
--------------------------------------------------------

  CREATE TABLE "PROMOTEMGR"."PATCH_RUNS" 
   (	"ID" NUMBER, 
	"PATCH_LABEL" VARCHAR2(200 BYTE), 
	"PATCH_NUMBER" NUMBER, 
	"PATCH_DESCRIPTION" VARCHAR2(4000 BYTE), 
	"IGNORE_FLAG" VARCHAR2(1 BYTE), 
	"PROMOTION_RUN_ID" NUMBER, 
	"PROMOTION_LABEL" VARCHAR2(200 BYTE), 
	"PROMOTION_LOAD_SEQUENCE" NUMBER, 
	"START_TIMESTAMP" TIMESTAMP (6), 
	"END_TIMESTAMP" TIMESTAMP (6), 
	"STATUS" VARCHAR2(10 BYTE), 
	"FILE_HASH" VARCHAR2(1000 BYTE), 
	"FILE_VERSION" VARCHAR2(4000 BYTE), 
	"FILE_CONTENTS" CLOB, 
	"OUTPUT_LOG" CLOB
   ) ;
