--------------------------------------------------------
--  DDL for Table PORTAL_FOLDER_TYPES
--------------------------------------------------------

  CREATE TABLE "DECMGR"."PORTAL_FOLDER_TYPES" 
   (	"PORTAL_FOLDER_TYPE" VARCHAR2(30 BYTE), 
	"XML_DATA" "SYS"."XMLTYPE" 
   ) ;
  GRANT REFERENCES ON "DECMGR"."PORTAL_FOLDER_TYPES" TO "BPMMGR";
  GRANT SELECT ON "DECMGR"."PORTAL_FOLDER_TYPES" TO "BPMMGR";
  GRANT INDEX ON "DECMGR"."PORTAL_FOLDER_TYPES" TO "BPMMGR";
  GRANT REFERENCES ON "DECMGR"."PORTAL_FOLDER_TYPES" TO "XVIEWMGR";
  GRANT SELECT ON "DECMGR"."PORTAL_FOLDER_TYPES" TO "APPENV";
  GRANT INSERT ON "DECMGR"."PORTAL_FOLDER_TYPES" TO "APPENV";
