--------------------------------------------------------
--  DDL for Table PORTAL_SCHEDULE_TYPES
--------------------------------------------------------

  CREATE TABLE "DECMGR"."PORTAL_SCHEDULE_TYPES" 
   (	"PORTAL_SCHEDULE_TYPE" VARCHAR2(30 BYTE), 
	"XML_DATA" "SYS"."XMLTYPE" 
   ) ;
  GRANT UPDATE ON "DECMGR"."PORTAL_SCHEDULE_TYPES" TO "APPENV";
  GRANT SELECT ON "DECMGR"."PORTAL_SCHEDULE_TYPES" TO "APPENV";
  GRANT INSERT ON "DECMGR"."PORTAL_SCHEDULE_TYPES" TO "APPENV";
  GRANT REFERENCES ON "DECMGR"."PORTAL_SCHEDULE_TYPES" TO "BPMMGR";
  GRANT SELECT ON "DECMGR"."PORTAL_SCHEDULE_TYPES" TO "BPMMGR";
  GRANT INDEX ON "DECMGR"."PORTAL_SCHEDULE_TYPES" TO "BPMMGR";
