--------------------------------------------------------
--  DDL for Table PORTAL_FOLDER_ABSTRACTS
--------------------------------------------------------

  CREATE TABLE "DECMGR"."PORTAL_FOLDER_ABSTRACTS" 
   (	"ID" NUMBER(12,0), 
	"PF_ID" NUMBER(12,0), 
	"XML_DATA" "SYS"."XMLTYPE" 
   ) ;
  GRANT SELECT ON "DECMGR"."PORTAL_FOLDER_ABSTRACTS" TO "BPMMGR";
  GRANT INSERT ON "DECMGR"."PORTAL_FOLDER_ABSTRACTS" TO "BPMMGR";
  GRANT REFERENCES ON "DECMGR"."PORTAL_FOLDER_ABSTRACTS" TO "XVIEWMGR";
  GRANT SELECT ON "DECMGR"."PORTAL_FOLDER_ABSTRACTS" TO "APPENV";
