--------------------------------------------------------
--  DDL for Table PORTAL_SCHEDULE_EVENTS
--------------------------------------------------------

  CREATE TABLE "DECMGR"."PORTAL_SCHEDULE_EVENTS" 
   (	"ID" NUMBER(12,0), 
	"SCHEDULE_SUBJECT_ID" NUMBER(12,0), 
	"EVENT_MNEM" VARCHAR2(30 BYTE), 
	"START_DATE" DATE, 
	"STATUS" VARCHAR2(30 BYTE)
   ) ;
  GRANT UPDATE ON "DECMGR"."PORTAL_SCHEDULE_EVENTS" TO "APPENV";
  GRANT SELECT ON "DECMGR"."PORTAL_SCHEDULE_EVENTS" TO "APPENV";
  GRANT INSERT ON "DECMGR"."PORTAL_SCHEDULE_EVENTS" TO "APPENV";
  GRANT REFERENCES ON "DECMGR"."PORTAL_SCHEDULE_EVENTS" TO "BPMMGR";
  GRANT SELECT ON "DECMGR"."PORTAL_SCHEDULE_EVENTS" TO "BPMMGR";
  GRANT INDEX ON "DECMGR"."PORTAL_SCHEDULE_EVENTS" TO "BPMMGR";
