--------------------------------------------------------
--  DDL for Table PORTAL_FOLDERS
--------------------------------------------------------

  CREATE TABLE "DECMGR"."PORTAL_FOLDERS" 
   (	"ID" NUMBER(12,0), 
	"XML_DATA" "SYS"."XMLTYPE" 
   ) ;
  GRANT REFERENCES ON "DECMGR"."PORTAL_FOLDERS" TO "SPIREMGR";
  GRANT REFERENCES ON "DECMGR"."PORTAL_FOLDERS" TO "XVIEWMGR";
  GRANT REFERENCES ON "DECMGR"."PORTAL_FOLDERS" TO "ENVMGR";
  GRANT REFERENCES ON "DECMGR"."PORTAL_FOLDERS" TO "BPMMGR";
  GRANT SELECT ON "DECMGR"."PORTAL_FOLDERS" TO "BPMMGR";
  GRANT INDEX ON "DECMGR"."PORTAL_FOLDERS" TO "BPMMGR";
  GRANT UPDATE ON "DECMGR"."PORTAL_FOLDERS" TO "APPENV";
  GRANT SELECT ON "DECMGR"."PORTAL_FOLDERS" TO "APPENV";
  GRANT INSERT ON "DECMGR"."PORTAL_FOLDERS" TO "APPENV";
