--------------------------------------------------------
--  DDL for Table PORTAL_SCHEDULE_SUBJECTS
--------------------------------------------------------

  CREATE TABLE "DECMGR"."PORTAL_SCHEDULE_SUBJECTS" 
   (	"ID" NUMBER, 
	"PORTAL_SCHEDULE_INSTANCE" NUMBER, 
	"SCOPE_UREF" VARCHAR2(50 BYTE)
   ) ;

   COMMENT ON COLUMN "DECMGR"."PORTAL_SCHEDULE_SUBJECTS"."SCOPE_UREF" IS 'Reference to the uref implicated in this schedule';
  GRANT REFERENCES ON "DECMGR"."PORTAL_SCHEDULE_SUBJECTS" TO "BPMMGR";
  GRANT SELECT ON "DECMGR"."PORTAL_SCHEDULE_SUBJECTS" TO "BPMMGR";
  GRANT INDEX ON "DECMGR"."PORTAL_SCHEDULE_SUBJECTS" TO "BPMMGR";
  GRANT UPDATE ON "DECMGR"."PORTAL_SCHEDULE_SUBJECTS" TO "APPENV";
  GRANT SELECT ON "DECMGR"."PORTAL_SCHEDULE_SUBJECTS" TO "APPENV";
  GRANT INSERT ON "DECMGR"."PORTAL_SCHEDULE_SUBJECTS" TO "APPENV";
