--------------------------------------------------------
--  DDL for Table PORTAL_SCHEDULE_INSTANCES
--------------------------------------------------------

  CREATE TABLE "DECMGR"."PORTAL_SCHEDULE_INSTANCES" 
   (	"ID" NUMBER, 
	"ORIGIN_DATE" DATE, 
	"SCHEDULE_GROUP_ID" NUMBER(12,0), 
	"PF_ID" NUMBER(12,0)
   ) ;
  GRANT REFERENCES ON "DECMGR"."PORTAL_SCHEDULE_INSTANCES" TO "BPMMGR";
  GRANT SELECT ON "DECMGR"."PORTAL_SCHEDULE_INSTANCES" TO "BPMMGR";
  GRANT INDEX ON "DECMGR"."PORTAL_SCHEDULE_INSTANCES" TO "BPMMGR";
  GRANT UPDATE ON "DECMGR"."PORTAL_SCHEDULE_INSTANCES" TO "APPENV";
  GRANT SELECT ON "DECMGR"."PORTAL_SCHEDULE_INSTANCES" TO "APPENV";
  GRANT INSERT ON "DECMGR"."PORTAL_SCHEDULE_INSTANCES" TO "APPENV";
