--------------------------------------------------------
--  DDL for Table PRAGMA_RESPONSE_SESSIONS
--------------------------------------------------------

  CREATE TABLE "SECUREMGR"."PRAGMA_RESPONSE_SESSIONS" 
   (	"ID" VARCHAR2(100 BYTE), 
	"SESSION_DOM" "SYS"."XMLTYPE" 
   ) ;
  GRANT UPDATE ON "SECUREMGR"."PRAGMA_RESPONSE_SESSIONS" TO "APPENV";
  GRANT SELECT ON "SECUREMGR"."PRAGMA_RESPONSE_SESSIONS" TO "APPENV";
  GRANT INSERT ON "SECUREMGR"."PRAGMA_RESPONSE_SESSIONS" TO "APPENV";
