--------------------------------------------------------
--  DDL for Table PROMOTION_FILES
--------------------------------------------------------

  CREATE TABLE "PROMOTEMGR"."PROMOTION_FILES" 
   (	"ID" NUMBER, 
	"PROMOTION_RUN_ID" NUMBER, 
	"PROMOTION_LABEL" VARCHAR2(200 BYTE), 
	"FILE_PATH" VARCHAR2(4000 BYTE), 
	"IGNORE_FLAG" VARCHAR2(1 BYTE), 
	"PROMOTION_START_TIMESTAMP" TIMESTAMP (6), 
	"PROMOTION_END_TIMESTAMP" TIMESTAMP (6), 
	"STATUS" VARCHAR2(10 BYTE), 
	"LOAD_SEQUENCE" NUMBER, 
	"LOADER_NAME" VARCHAR2(500 BYTE), 
	"FILE_HASH" VARCHAR2(1000 BYTE), 
	"FILE_VERSION" VARCHAR2(4000 BYTE), 
	"FILE_INDEX" NUMBER
   ) ;
