--------------------------------------------------------
--  DDL for Table REF_REPORT_RATINGS
--------------------------------------------------------

  CREATE TABLE "SDBMGR"."REF_REPORT_RATINGS" 
   (	"RATING" VARCHAR2(30 BYTE), 
	"REPORT_RATING" VARCHAR2(30 BYTE), 
	 CONSTRAINT "REF_REPORT_RATINGS_PK" PRIMARY KEY ("RATING") ENABLE
   ) ORGANIZATION INDEX NOCOMPRESS ;
  GRANT SELECT ON "SDBMGR"."REF_REPORT_RATINGS" TO "APPENV";
