--------------------------------------------------------
--  DDL for Table REG_FILE_LIST
--------------------------------------------------------

  CREATE TABLE "WARP_OWNER"."REG_FILE_LIST" 
   (	"PREFIX_NAME" VARCHAR2(4 BYTE), 
	"THEME" VARCHAR2(3 BYTE), 
	"FILE_NUMBER" NUMBER(10,0), 
	"PART_NUMBER" VARCHAR2(10 BYTE), 
	"SUB_NO" VARCHAR2(10 BYTE), 
	"YEAR" NUMBER(4,0), 
	"FILE_TITLE" VARCHAR2(400 BYTE), 
	"END_DATE" DATE, 
	"START_DATE" DATE, 
	"SECURITY_CLASS" VARCHAR2(25 BYTE), 
	"PREVIOUS_PAPERS" VARCHAR2(50 BYTE), 
	"RELATED_PAPERS" VARCHAR2(50 BYTE), 
	"FILE_REQUESTOR" VARCHAR2(30 BYTE), 
	"CREATE_DATE" DATE, 
	"STATUS" VARCHAR2(50 BYTE), 
	"CURRENT_HOLDER" VARCHAR2(30 BYTE), 
	"CURRENT_HOLDER_SINCE_DATE" DATE, 
	"TO_CFS_DATE" DATE, 
	"FROM_CFS_DATE" DATE, 
	"WANG_FILE_FLAG" VARCHAR2(1 BYTE), 
	"COMMENTS" VARCHAR2(550 BYTE)
   ) ;
