--------------------------------------------------------
--  DDL for Table REPORT_DEFINITIONS
--------------------------------------------------------

  CREATE TABLE "REPORTMGR"."REPORT_DEFINITIONS" 
   (	"DOMAIN" VARCHAR2(40 BYTE), 
	"XML_DATA" "SYS"."XMLTYPE" 
   ) ;
  GRANT SELECT ON "REPORTMGR"."REPORT_DEFINITIONS" TO "SDBMGR";
  GRANT REFERENCES ON "REPORTMGR"."REPORT_DEFINITIONS" TO "XVIEWMGR";
  GRANT INDEX ON "REPORTMGR"."REPORT_DEFINITIONS" TO "BPMMGR";
  GRANT REFERENCES ON "REPORTMGR"."REPORT_DEFINITIONS" TO "BPMMGR";
  GRANT SELECT ON "REPORTMGR"."REPORT_DEFINITIONS" TO "BPMMGR";
  GRANT SELECT ON "REPORTMGR"."REPORT_DEFINITIONS" TO "APPENV";
