--------------------------------------------------------
--  DDL for Table REPORT_SCHEDULES
--------------------------------------------------------

  CREATE TABLE "REPORTMGR"."REPORT_SCHEDULES" 
   (	"ID" NUMBER, 
	"TITLE" VARCHAR2(200 BYTE), 
	"DESCRIPTION" VARCHAR2(4000 BYTE), 
	"RUN_REPEAT" VARCHAR2(5 BYTE) DEFAULT 'false', 
	"INTERVAL_MNEM" VARCHAR2(100 BYTE), 
	"REPORT_SIGNATURE" VARCHAR2(4000 BYTE), 
	"SCHEDULED_BY_WUA_ID" NUMBER(12,0), 
	"PRIVATE_FLAG" VARCHAR2(10 BYTE)
   ) ;
  GRANT SELECT ON "REPORTMGR"."REPORT_SCHEDULES" TO "SPIREMGR";
  GRANT SELECT ON "REPORTMGR"."REPORT_SCHEDULES" TO "APPENV";
  GRANT UPDATE ON "REPORTMGR"."REPORT_SCHEDULES" TO "APPENV";
