--------------------------------------------------------
--  DDL for Table REPORT_PARTS
--------------------------------------------------------

  CREATE TABLE "REPORTMGR"."REPORT_PARTS" 
   (	"ID" NUMBER, 
	"RR_ID" NUMBER, 
	"PART_LABEL" VARCHAR2(50 BYTE), 
	"REQUESTED_DATETIME" DATE, 
	"REQUESTED_FLAG" VARCHAR2(5 BYTE), 
	"START_DATETIME" DATE, 
	"FINISH_DATETIME" DATE, 
	"METADATA_XML" "REPORTMGR"."XMLTYPE", 
	"ROWS_FOR_PART" NUMBER, 
	"IPC_PUT_DATETIME" DATE
   ) ;
  GRANT REFERENCES ON "REPORTMGR"."REPORT_PARTS" TO "XVIEWMGR";
  GRANT SELECT ON "REPORTMGR"."REPORT_PARTS" TO "APPENV";
