--------------------------------------------------------
--  DDL for Table REPORT_RUNS
--------------------------------------------------------

  CREATE TABLE "REPORTMGR"."REPORT_RUNS" 
   (	"ID" NUMBER, 
	"DOMAIN" VARCHAR2(40 BYTE), 
	"SCHEDULED_DATETIME" DATE, 
	"RUN_DATETIME" DATE, 
	"RS_ID" NUMBER, 
	"STATUS" VARCHAR2(32 BYTE) DEFAULT 'PENDING', 
	"SYSTEM_MSG" VARCHAR2(4000 BYTE), 
	"REPORT_SERVICE_QUEUE" VARCHAR2(30 BYTE) DEFAULT NULL, 
	"SCN" NUMBER, 
	"SYSDATE_AT_RUN_TIME" DATE, 
	"START_DATETIME" DATE, 
	"COMPLETED_DATETIME" DATE, 
	"PARAMETER_XML" "SYS"."XMLTYPE" , 
	"REQUESTED_PART_XML" "SYS"."XMLTYPE" , 
	"DS_ID" NUMBER(12,0), 
	"DELETED_DATETIME" DATE, 
	"DELETED_BY_WUA_ID" NUMBER(12,0), 
	"PUBLISHED_TITLE" VARCHAR2(4000 BYTE), 
	"NOTIFY_COMPLETE_REQUIRED" VARCHAR2(1 BYTE), 
	"NOTIFY_COMPLETE_DATETIME" DATE, 
	"NOTIFY_DELETE_DUE_REQUIRED" VARCHAR2(1 BYTE), 
	"NOTIFY_DELETE_DUE_DATETIME" DATE, 
	"RETENTION_DAYS" NUMBER(*,0), 
	"MAPSET_TEMPLATE_XML" "REPORTMGR"."XMLTYPE", 
	"REPORT_PART_ATTACH_XML" "SYS"."XMLTYPE" , 
	"EMAIL_RECIPIENT_XML" "SYS"."XMLTYPE" , 
	"RETENTION_HOUSEKEEPING_DONE" VARCHAR2(1 BYTE)
   ) ;
  GRANT REFERENCES ON "REPORTMGR"."REPORT_RUNS" TO "SPIREMGR";
  GRANT SELECT ON "REPORTMGR"."REPORT_RUNS" TO "SPIREMGR";
  GRANT SELECT ON "REPORTMGR"."REPORT_RUNS" TO "SDBMGR";
  GRANT REFERENCES ON "REPORTMGR"."REPORT_RUNS" TO "SDBMGR";
  GRANT UPDATE ON "REPORTMGR"."REPORT_RUNS" TO "APPENV";
  GRANT REFERENCES ON "REPORTMGR"."REPORT_RUNS" TO "BPMMGR";
  GRANT SELECT ON "REPORTMGR"."REPORT_RUNS" TO "BPMMGR";
  GRANT INDEX ON "REPORTMGR"."REPORT_RUNS" TO "BPMMGR";
  GRANT SELECT ON "REPORTMGR"."REPORT_RUNS" TO "APPENV";
