--------------------------------------------------------
--  DDL for Table REPORT_PARTS_OUTPUTS
--------------------------------------------------------

  CREATE TABLE "REPORTMGR"."REPORT_PARTS_OUTPUTS" 
   (	"ID" NUMBER, 
	"RP_ID" NUMBER, 
	"OUTPUT_TYPE" VARCHAR2(15 BYTE), 
	"CLOB_DATA" CLOB, 
	"DI_ID" NUMBER(12,0), 
	"PUBLISHED_FLAG" VARCHAR2(10 BYTE), 
	"PUBLISHED_DATE" DATE, 
	"PUBLISHED_BY_WUA_ID" NUMBER(12,0), 
	"BLOB_DATA" BLOB
   ) 
 LOB ("BLOB_DATA") STORE AS BASICFILE "REPORT_PARTS_BLOB_DATA"(DISABLE STORAGE IN ROW CHUNK 8192 RETENTION 
  CACHE ) ;
  GRANT SELECT ON "REPORTMGR"."REPORT_PARTS_OUTPUTS" TO "APPENV";
  GRANT UPDATE ON "REPORTMGR"."REPORT_PARTS_OUTPUTS" TO "APPENV";
