--------------------------------------------------------
--  DDL for Table RESOURCE_ADDRESS_FULL_HISTORY
--------------------------------------------------------

  CREATE TABLE "DECMGR"."RESOURCE_ADDRESS_FULL_HISTORY" 
   (	"ID" NUMBER(12,0), 
	"POSTCODE_ZIP_COMPRESSED" VARCHAR2(30 BYTE), 
	"POSTCODE_ZIP_FULL" VARCHAR2(30 BYTE), 
	"ADDRESS" VARCHAR2(4000 BYTE), 
	"STATUS" VARCHAR2(12 BYTE), 
	"CREATED_BY" VARCHAR2(200 BYTE), 
	"CREATED_DATE" DATE, 
	"LAST_USED_DATE" DATE, 
	"DELETE_REASON" VARCHAR2(200 BYTE)
   ) ;
