--------------------------------------------------------
--  DDL for Table RESOURCE_PEOPLE_BATCH_LOAD
--------------------------------------------------------

  CREATE TABLE "DECMGR"."RESOURCE_PEOPLE_BATCH_LOAD" 
   (	"ORG_NAME" VARCHAR2(1000 BYTE), 
	"PERSON_NAME" VARCHAR2(1000 BYTE), 
	"TEL_NO" VARCHAR2(50 BYTE), 
	"EMAIL_ADDRESS" VARCHAR2(100 BYTE), 
	"STATUS" VARCHAR2(20 BYTE) DEFAULT 'UNPROCESSED', 
	"LAST_SYSTEM_MESSAGE" VARCHAR2(1000 BYTE), 
	"LAST_UPDATED_DATE" DATE, 
	"PERSON_TYPE" VARCHAR2(20 BYTE) DEFAULT 'OIL', 
	"RPD_ID" NUMBER
   ) ;
