--------------------------------------------------------
--  DDL for Table RESOURCE_TELE_COUNTRY_CODES
--------------------------------------------------------

  CREATE TABLE "DECMGR"."RESOURCE_TELE_COUNTRY_CODES" 
   (	"COUNTRY_CODE" VARCHAR2(8 BYTE), 
	"NDD_CODE" VARCHAR2(8 BYTE), 
	"STATUS" VARCHAR2(10 BYTE), 
	"COUNTRY_NAME" VARCHAR2(100 BYTE), 
	"CREATED_BY" VARCHAR2(200 BYTE), 
	"CREATED_DATETIME" DATE, 
	"COMMENTS" VARCHAR2(4000 BYTE), 
	"AUTO_STRIP_NDD_FROM_STD" VARCHAR2(1 BYTE), 
	"SHOW_NDD_IN_CANONICAL" VARCHAR2(1 BYTE), 
	"USE_NDD_IN_DIAL" VARCHAR2(1 BYTE)
   ) ;
