--------------------------------------------------------
--  DDL for Table RESOURCE_DETAILS
--------------------------------------------------------

  CREATE TABLE "DECMGR"."RESOURCE_DETAILS" 
   (	"ID" NUMBER(12,0), 
	"RES_ID" NUMBER(12,0), 
	"START_DATE" DATE, 
	"END_DATE" DATE, 
	"XML_DATA" "SYS"."XMLTYPE" , 
	"STATUS_CONTROL" VARCHAR2(1 BYTE), 
	"STATUS" VARCHAR2(12 BYTE), 
	"CREATED_BY_WUA_ID" NUMBER(12,0)
   ) 
 XMLTYPE COLUMN "XML_DATA" STORE AS BASICFILE CLOB "RESOURCE_DETAILS_SYS_NC00006$"(DISABLE STORAGE IN ROW CHUNK 8192 RETENTION 
  NOCACHE LOGGING ) ;
  GRANT SELECT ON "DECMGR"."RESOURCE_DETAILS" TO "SPIREMGR";
  GRANT REFERENCES ON "DECMGR"."RESOURCE_DETAILS" TO "XVIEWMGR";
  GRANT SELECT ON "DECMGR"."RESOURCE_DETAILS" TO "XVIEWMGR";
  GRANT UPDATE ON "DECMGR"."RESOURCE_DETAILS" TO "APPENV";
  GRANT SELECT ON "DECMGR"."RESOURCE_DETAILS" TO "APPENV";
  GRANT INSERT ON "DECMGR"."RESOURCE_DETAILS" TO "APPENV";
