--------------------------------------------------------
--  DDL for Table RESOURCE_USAGES
--------------------------------------------------------

  CREATE TABLE "DECMGR"."RESOURCE_USAGES" 
   (	"RES_ID" NUMBER(12,0), 
	"UREF" VARCHAR2(50 BYTE), 
	"START_DATETIME" DATE, 
	"END_DATETIME" DATE, 
	"PURPOSE" VARCHAR2(30 BYTE)
   ) ;
  GRANT INSERT ON "DECMGR"."RESOURCE_USAGES" TO "SPIREMGR";
  GRANT SELECT ON "DECMGR"."RESOURCE_USAGES" TO "PVEXMGR";
  GRANT SELECT ON "DECMGR"."RESOURCE_USAGES" TO "FOXMGR";
  GRANT SELECT ON "DECMGR"."RESOURCE_USAGES" TO "SPIREMGR";
  GRANT UPDATE ON "DECMGR"."RESOURCE_USAGES" TO "SPIREMGR";
  GRANT SELECT ON "DECMGR"."RESOURCE_USAGES" TO "ENVMGR";
  GRANT INSERT ON "DECMGR"."RESOURCE_USAGES" TO "ENVMGR";
  GRANT SELECT ON "DECMGR"."RESOURCE_USAGES" TO "BPMMGR";
  GRANT UPDATE ON "DECMGR"."RESOURCE_USAGES" TO "APPENV";
  GRANT SELECT ON "DECMGR"."RESOURCE_USAGES" TO "APPENV";
  GRANT INSERT ON "DECMGR"."RESOURCE_USAGES" TO "APPENV";
