--------------------------------------------------------
--  DDL for Table RESOURCE_ROLES
--------------------------------------------------------

  CREATE TABLE "DECMGR"."RESOURCE_ROLES" 
   (	"ID" NUMBER(12,0), 
	"RES_ID" NUMBER(12,0), 
	"ROLE_NAME" VARCHAR2(30 BYTE)
   ) ;
  GRANT SELECT ON "DECMGR"."RESOURCE_ROLES" TO "FOXMGR";
  GRANT REFERENCES ON "DECMGR"."RESOURCE_ROLES" TO "XVIEWMGR";
  GRANT REFERENCES ON "DECMGR"."RESOURCE_ROLES" TO "BPMMGR";
  GRANT SELECT ON "DECMGR"."RESOURCE_ROLES" TO "BPMMGR";
  GRANT INDEX ON "DECMGR"."RESOURCE_ROLES" TO "BPMMGR";
  GRANT SELECT ON "DECMGR"."RESOURCE_ROLES" TO "APPENV";
