--------------------------------------------------------
--  DDL for Table REVIEW_ADVISOR_SLOT_DETAILS
--------------------------------------------------------

  CREATE TABLE "BPMMGR"."REVIEW_ADVISOR_SLOT_DETAILS" 
   (	"ID" NUMBER(12,0), 
	"RAS_ID" NUMBER(12,0), 
	"INTENTION_SET_ID" NUMBER(12,0), 
	"NAME" VARCHAR2(255 BYTE), 
	"STATUS" VARCHAR2(30 BYTE), 
	"STATUS_MESSAGE" VARCHAR2(255 BYTE), 
	"STATUS_BY_WUA_ID" NUMBER, 
	"STATUS_DATE" DATE, 
	"UREF" VARCHAR2(50 BYTE), 
	"PURPOSE" VARCHAR2(30 BYTE), 
	"RESPONSE_DECISION" VARCHAR2(255 BYTE), 
	"RESPONSE_COMMENTS_XML" "BPMMGR"."XMLTYPE", 
	"RRUC_ID" NUMBER(12,0), 
	"START_DATETIME" DATE, 
	"END_DATETIME" DATE, 
	"STATUS_CONTROL" VARCHAR2(1 BYTE), 
	"FF_ID" NUMBER(*,0)
   ) ;
