--------------------------------------------------------
--  DDL for Table REVIEW_REMOTE_UPLOADS_BLOB
--------------------------------------------------------

  CREATE TABLE "BPMMGR"."REVIEW_REMOTE_UPLOADS_BLOB" 
   (	"FOX_FILE_ID" VARCHAR2(100 BYTE), 
	"BLOB_DATA" BLOB DEFAULT empty_blob()
   ) ;
  GRANT UPDATE ON "BPMMGR"."REVIEW_REMOTE_UPLOADS_BLOB" TO "APPENV";
  GRANT SELECT ON "BPMMGR"."REVIEW_REMOTE_UPLOADS_BLOB" TO "APPENV";
  GRANT INSERT ON "BPMMGR"."REVIEW_REMOTE_UPLOADS_BLOB" TO "APPENV";
  GRANT DELETE ON "BPMMGR"."REVIEW_REMOTE_UPLOADS_BLOB" TO "APPENV";
