--------------------------------------------------------
--  DDL for Table REVIEW_ADVISOR_SLOTS_OLD
--------------------------------------------------------

  CREATE TABLE "BPMMGR"."REVIEW_ADVISOR_SLOTS_OLD" 
   (	"ID" NUMBER(12,0), 
	"RA_ID" NUMBER(12,0), 
	"INTENTION_SET_ID" NUMBER(12,0), 
	"NAME" VARCHAR2(255 BYTE), 
	"STATUS" VARCHAR2(30 BYTE), 
	"STATUS_MESSAGE" VARCHAR2(255 BYTE), 
	"STATUS_BY_WUA_ID" NUMBER, 
	"STATUS_DATE" DATE, 
	"UREF" VARCHAR2(50 BYTE), 
	"PURPOSE" VARCHAR2(30 BYTE), 
	"RESPONSE_DECISION" VARCHAR2(255 BYTE), 
	"RESPONSE_COMMENTS_XML" "BPMMGR"."XMLTYPE", 
	"RRUC_ID" NUMBER(12,0)
   ) ;
  GRANT SELECT ON "BPMMGR"."REVIEW_ADVISOR_SLOTS_OLD" TO "SPIREMGR";
  GRANT SELECT ON "BPMMGR"."REVIEW_ADVISOR_SLOTS_OLD" TO "APPENV";
