--------------------------------------------------------
--  DDL for Table REVIEW_ADVISOR_SLOTS
--------------------------------------------------------

  CREATE TABLE "SAVEMGR"."REVIEW_ADVISOR_SLOTS" 
   (	"ID" NUMBER(12,0), 
	"RA_ID" NUMBER(12,0), 
	"INTENTION_SET_ID" NUMBER(12,0), 
	"NAME" VARCHAR2(255 BYTE), 
	"STATUS" VARCHAR2(30 BYTE), 
	"STATUS_MESSAGE" VARCHAR2(255 BYTE), 
	"STATUS_BY_WUA_ID" NUMBER, 
	"STATUS_DATE" DATE, 
	"UREF" VARCHAR2(50 BYTE), 
	"PURPOSE" VARCHAR2(30 BYTE), 
	"RESPONSE_DECISION" VARCHAR2(255 BYTE), 
	"RESPONSE_COMMENTS_XML" "SYS"."XMLTYPE" , 
	"RRUC_ID" NUMBER(12,0)
   ) ;

   COMMENT ON TABLE "SAVEMGR"."REVIEW_ADVISOR_SLOTS"  IS 'Save of "BPMMGR"."REVIEW_ADVISOR_SLOTS" at 24-JUL-2009 18:29:23';
  GRANT SELECT ON "SAVEMGR"."REVIEW_ADVISOR_SLOTS" TO "BPMMGR";
