--------------------------------------------------------
--  DDL for Table REVIEW_ADVISOR_SLOT_DETAILS
--------------------------------------------------------

  CREATE TABLE "SAVEMGR"."REVIEW_ADVISOR_SLOT_DETAILS" 
   (	"ID" NUMBER(12,0), 
	"RAS_ID" NUMBER(12,0), 
	"INTENTION_SET_ID" NUMBER(12,0), 
	"NAME" VARCHAR2(255 BYTE), 
	"STATUS" VARCHAR2(30 BYTE), 
	"STATUS_MESSAGE" VARCHAR2(255 BYTE), 
	"STATUS_BY_WUA_ID" NUMBER, 
	"STATUS_DATE" DATE, 
	"UREF" VARCHAR2(50 BYTE), 
	"PURPOSE" VARCHAR2(30 BYTE), 
	"RESPONSE_DECISION" VARCHAR2(255 BYTE), 
	"RESPONSE_COMMENTS_XML" "SYS"."XMLTYPE" , 
	"RRUC_ID" NUMBER(12,0), 
	"START_DATETIME" DATE, 
	"END_DATETIME" DATE, 
	"STATUS_CONTROL" VARCHAR2(1 BYTE)
   ) ;

   COMMENT ON TABLE "SAVEMGR"."REVIEW_ADVISOR_SLOT_DETAILS"  IS 'Save of "BPMMGR"."REVIEW_ADVISOR_SLOT_DETAILS" at 24-JUL-2009 20:24:27';
  GRANT SELECT ON "SAVEMGR"."REVIEW_ADVISOR_SLOT_DETAILS" TO "BPMMGR";
