--------------------------------------------------------
--  DDL for Table SCAN_PREFERENCE_TEMPLATES
--------------------------------------------------------

  CREATE TABLE "DECMGR"."SCAN_PREFERENCE_TEMPLATES" 
   (	"ID" NUMBER(12,0), 
	"XML_DATA" "SYS"."XMLTYPE" 
   ) ;
  GRANT REFERENCES ON "DECMGR"."SCAN_PREFERENCE_TEMPLATES" TO "BPMMGR";
  GRANT SELECT ON "DECMGR"."SCAN_PREFERENCE_TEMPLATES" TO "BPMMGR";
  GRANT INDEX ON "DECMGR"."SCAN_PREFERENCE_TEMPLATES" TO "BPMMGR";
  GRANT SELECT ON "DECMGR"."SCAN_PREFERENCE_TEMPLATES" TO "APPENV";
  GRANT REFERENCES ON "DECMGR"."SCAN_PREFERENCE_TEMPLATES" TO "XVIEWMGR";
