--------------------------------------------------------
--  DDL for Table SCHEMA_DEFINITION_DETAILS
--------------------------------------------------------

  CREATE TABLE "PVEXMGR"."SCHEMA_DEFINITION_DETAILS" 
   (	"ID" NUMBER, 
	"SD_ID" NUMBER, 
	"START_DATETIME" DATE, 
	"END_DATETIME" DATE, 
	"STATUS_CONTROL" VARCHAR2(1 BYTE), 
	"XML_DATA" "SYS"."XMLTYPE" 
   ) 
 XMLTYPE COLUMN "XML_DATA" STORE AS SECUREFILE BINARY XML "SD_DETAILS_XML_DATA"(DISABLE STORAGE IN ROW CHUNK 8192
  CACHE  NOCOMPRESS  KEEP_DUPLICATES ) ALLOW NONSCHEMA DISALLOW ANYSCHEMA ;
  GRANT SELECT ON "PVEXMGR"."SCHEMA_DEFINITION_DETAILS" TO "APPENV";
