--------------------------------------------------------
--  DDL for Table SECURITY_SYSTEM_RULES_6
--------------------------------------------------------

  CREATE TABLE "SAVEMGR"."SECURITY_SYSTEM_RULES_6" 
   (	"ID" NUMBER(12,0), 
	"DESCRIPTION" VARCHAR2(4000 BYTE), 
	"GRANTEE_UREF_TYPE" VARCHAR2(6 BYTE), 
	"SYSTEM_PRIVILEGE_LIST" VARCHAR2(4000 BYTE), 
	"SYSTEM_UREF_SELECT" CLOB, 
	"STATUS" VARCHAR2(10 BYTE)
   ) ;

   COMMENT ON TABLE "SAVEMGR"."SECURITY_SYSTEM_RULES_6"  IS 'Save of "BPMMGR"."SECURITY_SYSTEM_RULES" at 04-JUL-2008 23:05:42';
  GRANT SELECT ON "SAVEMGR"."SECURITY_SYSTEM_RULES_6" TO "BPMMGR";
