--------------------------------------------------------
--  DDL for Table SECURITY_OBJECT_RULES_6
--------------------------------------------------------

  CREATE TABLE "SAVEMGR"."SECURITY_OBJECT_RULES_6" 
   (	"ID" NUMBER(12,0), 
	"DESCRIPTION" VARCHAR2(4000 BYTE), 
	"GRANTEE_UREF_TYPE" VARCHAR2(6 BYTE), 
	"OBJECT_UREF_TYPE" VARCHAR2(6 BYTE), 
	"OBJECT_PRIVILEGE_LIST" VARCHAR2(4000 BYTE), 
	"OBJECT_UREF_SELECT" CLOB, 
	"STATUS" VARCHAR2(10 BYTE), 
	"APPLICATION_NAME" VARCHAR2(30 BYTE)
   ) ;

   COMMENT ON TABLE "SAVEMGR"."SECURITY_OBJECT_RULES_6"  IS 'Save of "BPMMGR"."SECURITY_OBJECT_RULES" at 04-JUL-2008 23:05:32';
  GRANT SELECT ON "SAVEMGR"."SECURITY_OBJECT_RULES_6" TO "BPMMGR";
