--------------------------------------------------------
--  DDL for Table SMS_TRANSMISSION_REQUEST_LOGS
--------------------------------------------------------

  CREATE TABLE "PORTALMGR"."SMS_TRANSMISSION_REQUEST_LOGS" 
   (	"ID" NUMBER, 
	"CONNECTION_STRING" VARCHAR2(4000 BYTE), 
	"MESSAGE" VARCHAR2(4000 BYTE), 
	"MESSAGE_FROM" VARCHAR2(4000 BYTE), 
	"MESSAGE_TO" VARCHAR2(4000 BYTE), 
	"STATUS" VARCHAR2(20 BYTE), 
	"RETURN_CODE" VARCHAR2(4000 BYTE), 
	"SENT_DATE_TIME" DATE, 
	"XML_DATA" "SYS"."XMLTYPE" 
   ) 
 XMLTYPE COLUMN "XML_DATA" STORE AS BASICFILE CLOB "XML_DATA"(DISABLE STORAGE IN ROW CHUNK 8192 RETENTION 
  CACHE ) ;
