--------------------------------------------------------
--  DDL for Table SPIRE_MIGRATE_NOMINATIONS
--------------------------------------------------------

  CREATE TABLE "SPIREMGR"."SPIRE_MIGRATE_NOMINATIONS" 
   (	"ID" NUMBER, 
	"SA_ID" NUMBER, 
	"STATUS" VARCHAR2(24 BYTE), 
	"SYSTEM_MESSAGE" VARCHAR2(400 BYTE), 
	"COMMENTS" VARCHAR2(4000 BYTE), 
	"CREATED_BY" VARCHAR2(4000 BYTE), 
	"CREATED_DATETIME" DATE, 
	"UPDATED_BY" VARCHAR2(4000 BYTE), 
	"UPDATED_DATETIME" DATE, 
	"APPLICATION_TYPE" VARCHAR2(8 BYTE), 
	"ELA_REF" NUMBER, 
	"LICENCE_NO" VARCHAR2(50 BYTE), 
	"APPLICATION_DATE" DATE, 
	"SIGNATORY_SURNAME" VARCHAR2(4000 BYTE)
   ) ;
