--------------------------------------------------------
--  DDL for Table SPIRE_ENHANCEMENT_DETAILS
--------------------------------------------------------

  CREATE TABLE "SPIREMGR"."SPIRE_ENHANCEMENT_DETAILS" 
   (	"ID" NUMBER, 
	"SE_ID" NUMBER, 
	"DESCRIPTION" VARCHAR2(4000 BYTE), 
	"STATUS_CONTROL" VARCHAR2(1 BYTE), 
	"START_DATETIME" DATE, 
	"END_DATETIME" DATE, 
	"XML_DATA" "SYS"."XMLTYPE" 
   ) 
 XMLTYPE COLUMN "XML_DATA" STORE AS SECUREFILE BINARY XML "SED_XML_DATA"(DISABLE STORAGE IN ROW CHUNK 8192
  CACHE  NOCOMPRESS  KEEP_DUPLICATES ) ALLOW NONSCHEMA DISALLOW ANYSCHEMA ;
