--------------------------------------------------------
--  DDL for Table SPIRE_FEEDBACK
--------------------------------------------------------

  CREATE TABLE "SPIREMGR"."SPIRE_FEEDBACK" 
   (	"ID" NUMBER, 
	"SUBMITTED_BY_WUA_ID" NUMBER, 
	"SUBMITTED_BY_NAME" VARCHAR2(4000 BYTE), 
	"SUBMITTED_DATETIME" DATE, 
	"SPIRE_REF" VARCHAR2(4000 BYTE), 
	"FEEDBACK_XML" "SYS"."XMLTYPE" 
   ) 
 XMLTYPE COLUMN "FEEDBACK_XML" STORE AS SECUREFILE BINARY XML "SPIRE_FEEDBACK_XML_DATA"(DISABLE STORAGE IN ROW CHUNK 8192
  CACHE  NOCOMPRESS  KEEP_DUPLICATES ) ALLOW NONSCHEMA DISALLOW ANYSCHEMA ;
  GRANT SELECT ON "SPIREMGR"."SPIRE_FEEDBACK" TO "APPENV";
