--------------------------------------------------------
--  DDL for Table SPIRE_APPLICANT_DETAILSJBPP
--------------------------------------------------------

  CREATE TABLE "SAVEMGR"."SPIRE_APPLICANT_DETAILSJBPP" 
   (	"ID" NUMBER(*,0), 
	"SA_ID" NUMBER(*,0), 
	"START_DATE" DATE, 
	"END_DATE" DATE, 
	"XML_DATA" "SYS"."XMLTYPE" , 
	"STATUS_CONTROL" VARCHAR2(1 BYTE), 
	"STATUS" VARCHAR2(12 BYTE)
   ) ;

   COMMENT ON TABLE "SAVEMGR"."SPIRE_APPLICANT_DETAILSJBPP"  IS 'Save of "SPIREMGR"."SPIRE_APPLICANT_DETAILS" at 02-OCT-2007 18:54:32';
  GRANT SELECT ON "SAVEMGR"."SPIRE_APPLICANT_DETAILSJBPP" TO "SPIREMGR";
