--------------------------------------------------------
--  DDL for Table SPIRE_APPLICANT_DETAILS
--------------------------------------------------------

  CREATE TABLE "SAVEMGR"."SPIRE_APPLICANT_DETAILS" 
   (	"ID" NUMBER(*,0), 
	"SA_ID" NUMBER(*,0), 
	"START_DATE" DATE, 
	"END_DATE" DATE, 
	"XML_DATA" "SYS"."XMLTYPE" , 
	"STATUS_CONTROL" VARCHAR2(1 BYTE), 
	"STATUS" VARCHAR2(12 BYTE)
   ) ;

   COMMENT ON TABLE "SAVEMGR"."SPIRE_APPLICANT_DETAILS"  IS 'Save of "SPIREMGR"."SPIRE_APPLICANT_DETAILS" at 15-JUN-2009 19:46:19';
  GRANT SELECT ON "SAVEMGR"."SPIRE_APPLICANT_DETAILS" TO "SPIREMGR";
