--------------------------------------------------------
--  DDL for Table SPIRE_ENHANCEMENT_DETAILS
--------------------------------------------------------

  CREATE TABLE "SAVEMGR"."SPIRE_ENHANCEMENT_DETAILS" 
   (	"ID" NUMBER, 
	"SE_ID" NUMBER, 
	"DESCRIPTION" VARCHAR2(4000 BYTE), 
	"STATUS_CONTROL" VARCHAR2(1 BYTE), 
	"START_DATETIME" DATE, 
	"END_DATETIME" DATE, 
	"XML_DATA" "SYS"."XMLTYPE" 
   ) ;

   COMMENT ON TABLE "SAVEMGR"."SPIRE_ENHANCEMENT_DETAILS"  IS 'Save of "SPIREMGR"."SPIRE_ENHANCEMENT_DETAILS" at 13-DEC-2017 18:43:59';
  GRANT SELECT ON "SAVEMGR"."SPIRE_ENHANCEMENT_DETAILS" TO "SPIREMGR";
