--------------------------------------------------------
--  DDL for Table SPIRE_APPLICATIONS
--------------------------------------------------------

  CREATE TABLE "SPIREMGR"."SPIRE_APPLICATIONS" 
   (	"ID" NUMBER, 
	"XML_DATA" "SYS"."XMLTYPE" 
   ) ;
  GRANT REFERENCES ON "SPIREMGR"."SPIRE_APPLICATIONS" TO "BPMMGR";
  GRANT SELECT ON "SPIREMGR"."SPIRE_APPLICATIONS" TO "BPMMGR";
  GRANT INDEX ON "SPIREMGR"."SPIRE_APPLICATIONS" TO "BPMMGR";
  GRANT UPDATE ON "SPIREMGR"."SPIRE_APPLICATIONS" TO "APPENV";
  GRANT SELECT ON "SPIREMGR"."SPIRE_APPLICATIONS" TO "APPENV";
