--------------------------------------------------------
--  DDL for Table STRUCTURED_CODE_TYPES
--------------------------------------------------------

  CREATE TABLE "SPIREMGR"."STRUCTURED_CODE_TYPES" 
   (	"SC_TYPE" VARCHAR2(20 BYTE), 
	"DESCRIPTION" VARCHAR2(200 BYTE)
   ) ;
  GRANT UPDATE ON "SPIREMGR"."STRUCTURED_CODE_TYPES" TO "APPENV";
  GRANT SELECT ON "SPIREMGR"."STRUCTURED_CODE_TYPES" TO "APPENV";
  GRANT INSERT ON "SPIREMGR"."STRUCTURED_CODE_TYPES" TO "APPENV";
