--------------------------------------------------------
--  DDL for Table STRUCT_CODE_BATCH_LOAD
--------------------------------------------------------

  CREATE TABLE "SPIREMGR"."STRUCT_CODE_BATCH_LOAD" 
   (	"LOAD_ID" NUMBER(12,0), 
	"STATUS" VARCHAR2(20 BYTE) DEFAULT 'NEW', 
	"COMMENTS" VARCHAR2(1000 BYTE), 
	"CONTROL_ENTRY" VARCHAR2(20 BYTE), 
	"REGIME_CSV" VARCHAR2(4000 BYTE), 
	"ARS_CSV" VARCHAR2(4000 BYTE), 
	"LAST_SYS_MESSAGE" VARCHAR2(1000 BYTE), 
	"CREATED_DATETIME" DATE DEFAULT SYSDATE, 
	"PROCESSED_DATETIME" DATE
   ) ;
