--------------------------------------------------------
--  DDL for Table STRUCT_CODE_ARS_PREF_BATCH_LD
--------------------------------------------------------

  CREATE TABLE "SPIREMGR"."STRUCT_CODE_ARS_PREF_BATCH_LD" 
   (	"LOAD_ID" NUMBER(12,0), 
	"STATUS" VARCHAR2(20 BYTE) DEFAULT 'NEW', 
	"COMMENTS" VARCHAR2(1000 BYTE), 
	"ARS_PREFIX" VARCHAR2(100 BYTE), 
	"SHORT_CODE" VARCHAR2(20 BYTE), 
	"LAST_SYS_MESSAGE" VARCHAR2(1000 BYTE), 
	"CREATED_DATETIME" DATE DEFAULT SYSDATE, 
	"PROCESSED_DATETIME" DATE, 
	"CODE_SEQ" NUMBER
   ) ;
