-- Unable to render TABLE DDL for object XVIEWMGR.SYS_NTNd5yPPBU6VzgUwwgAArPgQ== with DBMS_METADATA attempting internal generator.
CREATE TABLE XVIEWMGR."SYS_NTNd5yPPBU6VzgUwwgAArPgQ==" 
LOGGING 
TABLESPACE TBSDATA 
PCTFREE 10 
INITRANS 1 
STORAGE 
( 
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1 
  MAXEXTENTS UNLIMITED 
  BUFFER_POOL DEFAULT 
) 
NOCOMPRESS 
NOPARALLELCREATE UNIQUE INDEX XVIEWMGR.SYS_C00416972 ON XVIEWMGR."SYS_NTNd5yPPBU6VzgUwwgAArPgQ==" (NESTED_TABLE_ID ASC, SYS_NC_ARRAY_INDEX$ ASC) 
LOGGING 
TABLESPACE TBSDATA 
PCTFREE 10 
INITRANS 2 
STORAGE 
( 
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1 
  MAXEXTENTS UNLIMITED 
  BUFFER_POOL DEFAULT 
) 
NOPARALLEL
