--------------------------------------------------------
--  DDL for Table SYSTEM_DOMAINS
--------------------------------------------------------

  CREATE TABLE "FOXMGR"."SYSTEM_DOMAINS" 
   (	"ID" NUMBER, 
	"DOMAIN" VARCHAR2(300 BYTE)
   ) ;
  GRANT REFERENCES ON "FOXMGR"."SYSTEM_DOMAINS" TO "BPMMGR";
  GRANT SELECT ON "FOXMGR"."SYSTEM_DOMAINS" TO "BPMMGR";
  GRANT INDEX ON "FOXMGR"."SYSTEM_DOMAINS" TO "BPMMGR";
  GRANT DELETE ON "FOXMGR"."SYSTEM_DOMAINS" TO "BPMMGR";
  GRANT ALTER ON "FOXMGR"."SYSTEM_DOMAINS" TO "BPMMGR";
  GRANT SELECT ON "FOXMGR"."SYSTEM_DOMAINS" TO "APPENV";
