--------------------------------------------------------
--  DDL for Table TALLY_INTERPRETATIONS
--------------------------------------------------------

  CREATE TABLE "BPMMGR"."TALLY_INTERPRETATIONS" 
   (	"ID" NUMBER(12,0), 
	"TALLY_ID" NUMBER(12,0), 
	"SUBJECT_UREF" VARCHAR2(50 BYTE), 
	"ACCRUED_RUN_SEC" NUMBER, 
	"TARGET_RUN_SEC" NUMBER, 
	"TARGET_DT" DATE, 
	"FIRST_RUN_START_DT" DATE, 
	"NORMAL1_START_DT" DATE, 
	"NORMAL1_END_DT" DATE, 
	"NORMAL1_SWITCH" VARCHAR2(30 BYTE), 
	"NORMAL1_AVERAGE_DAILY_HOURS" NUMBER, 
	"NORMAL2_START_DT" DATE, 
	"NORMAL2_END_DT" DATE, 
	"NORMAL2_SWITCH" VARCHAR2(30 BYTE), 
	"NORMAL2_AVERAGE_DAILY_HOURS" NUMBER, 
	"NORMAL3_START_DT" DATE, 
	"NORMAL3_END_DT" DATE, 
	"NORMAL3_SWITCH" VARCHAR2(30 BYTE), 
	"NORMAL3_AVERAGE_DAILY_HOURS" NUMBER, 
	"TALLY_ENDED_FLAG" VARCHAR2(1 BYTE), 
	"ACCRUED_RUN_DAY" NUMBER, 
	"TARGET_RUN_DAY" NUMBER, 
	"SUBJECT_UREF_NN" VARCHAR2(50 BYTE) GENERATED ALWAYS AS (COALESCE("SUBJECT_UREF",'{NULL}')) VIRTUAL 
   ) ;
