--------------------------------------------------------
--  DDL for Table TALLY_EVENTS
--------------------------------------------------------

  CREATE TABLE "SAVEMGR"."TALLY_EVENTS" 
   (	"ID" NUMBER(12,0), 
	"BS_ID" NUMBER(12,0), 
	"TALLY_ID" NUMBER(12,0), 
	"EVENT" VARCHAR2(30 BYTE), 
	"SUBJECT_UREF" VARCHAR2(50 BYTE), 
	"TRIGGER_TALLY" VARCHAR2(30 BYTE), 
	"START_DT" DATE, 
	"END_DT" DATE, 
	"ACTION_SET_MNEM" VARCHAR2(50 BYTE), 
	"TCE_ID" NUMBER(12,0), 
	"TWPD_ID" NUMBER(12,0), 
	"BAS_ID" NUMBER(12,0), 
	"IS_ASSIGNED" NUMBER(12,0), 
	"CONTEXT_UREF" VARCHAR2(50 BYTE)
   ) ;

   COMMENT ON TABLE "SAVEMGR"."TALLY_EVENTS"  IS 'Save of "BPMMGR"."TALLY_EVENTS" at 07-AUG-2009 18:11:19';
  GRANT SELECT ON "SAVEMGR"."TALLY_EVENTS" TO "BPMMGR";
