--------------------------------------------------------
--  DDL for Table TALLY_INTERPRETATIONS
--------------------------------------------------------

  CREATE TABLE "SAVEMGR"."TALLY_INTERPRETATIONS" 
   (	"ID" NUMBER(12,0), 
	"TALLY_ID" NUMBER(12,0), 
	"SUBJECT_UREF" VARCHAR2(50 BYTE), 
	"CALENDAR_PROCESSED_TO_DT" DATE, 
	"WEEK_PLAN_PROCESSED_TO_DT" DATE, 
	"TALLY_STATUS" VARCHAR2(30 BYTE), 
	"LAST_RUN_END_DT" DATE, 
	"LAST_INT_END_DT" DATE, 
	"ACCRUED_RUN_SEC" NUMBER, 
	"TARGET_RUN_SEC" NUMBER, 
	"ELAPSED_RUN_DAYS" NUMBER, 
	"TARGET_DT" DATE, 
	"BASELINE_DT" DATE, 
	"NEXT_SIGNIFICANT_DT" DATE, 
	"FIRST_RUN_START_DT" DATE, 
	"FIRST_INT_START_DT" DATE
   ) ;

   COMMENT ON TABLE "SAVEMGR"."TALLY_INTERPRETATIONS"  IS 'Save of "BPMMGR"."TALLY_INTERPRETATIONS" at 07-AUG-2009 18:11:20';
  GRANT SELECT ON "SAVEMGR"."TALLY_INTERPRETATIONS" TO "BPMMGR";
