--------------------------------------------------------
--  DDL for Table TAU_SFE_COUNTRY_GROUPS
--------------------------------------------------------

  CREATE TABLE "SPIREMGR"."TAU_SFE_COUNTRY_GROUPS" 
   (	"SFE_COUNTRY_GROUP" VARCHAR2(30 BYTE), 
	"SHORT_NAME" VARCHAR2(5 BYTE), 
	"START_DATETIME" DATE, 
	"CREATED_BY_WUA_ID" NUMBER, 
	"END_DATETIME" DATE, 
	"ENDED_BY_WUA_ID" NUMBER
   ) ;
  GRANT UPDATE ON "SPIREMGR"."TAU_SFE_COUNTRY_GROUPS" TO "APPENV";
  GRANT SELECT ON "SPIREMGR"."TAU_SFE_COUNTRY_GROUPS" TO "APPENV";
