--------------------------------------------------------
--  DDL for Table TAU_GOODS_CLASSIFICATION_RULES
--------------------------------------------------------

  CREATE TABLE "SPIREMGR"."TAU_GOODS_CLASSIFICATION_RULES" 
   (	"XML_DATA" "SYS"."XMLTYPE" 
   ) 
 XMLTYPE COLUMN "XML_DATA" STORE AS SECUREFILE BINARY XML "SD_DETAILS_XML_DATA"(DISABLE STORAGE IN ROW CHUNK 8192
  CACHE  NOCOMPRESS  KEEP_DUPLICATES ) ALLOW NONSCHEMA DISALLOW ANYSCHEMA ;
