--------------------------------------------------------
--  DDL for Table TAU_RED_LIST_SARS
--------------------------------------------------------

  CREATE TABLE "SPIREMGR"."TAU_RED_LIST_SARS" 
   (	"SAR_ID" NUMBER, 
	"START_DATETIME" DATE, 
	"CREATED_BY_WUA_ID" NUMBER, 
	"END_DATETIME" DATE, 
	"ENDED_BY_WUA_ID" NUMBER, 
	"REASON_ADDED" VARCHAR2(4000 BYTE)
   ) ;
  GRANT UPDATE ON "SPIREMGR"."TAU_RED_LIST_SARS" TO "APPENV";
  GRANT SELECT ON "SPIREMGR"."TAU_RED_LIST_SARS" TO "APPENV";
  GRANT INSERT ON "SPIREMGR"."TAU_RED_LIST_SARS" TO "APPENV";
