--------------------------------------------------------
--  DDL for Table TEMPLATE_CLAUSE_DETAILS_1
--------------------------------------------------------

  CREATE TABLE "SAVEMGR"."TEMPLATE_CLAUSE_DETAILS_1" 
   (	"ID" NUMBER(12,0), 
	"TC_ID" NUMBER(12,0), 
	"STATUS" VARCHAR2(12 BYTE), 
	"STATUS_CONTROL" VARCHAR2(1 BYTE), 
	"XML_DATA" "SYS"."XMLTYPE" , 
	"START_DATETIME" DATE, 
	"END_DATETIME" DATE
   ) ;

   COMMENT ON TABLE "SAVEMGR"."TEMPLATE_CLAUSE_DETAILS_1"  IS 'Save of "BPMMGR"."TEMPLATE_CLAUSE_DETAILS" at 24-JUL-2009 18:37:34';
  GRANT SELECT ON "SAVEMGR"."TEMPLATE_CLAUSE_DETAILS_1" TO "BPMMGR";
