--------------------------------------------------------
--  DDL for Table TEMPLATE_CLAUSE_DETAILS
--------------------------------------------------------

  CREATE TABLE "SAVEMGR"."TEMPLATE_CLAUSE_DETAILS" 
   (	"ID" NUMBER(12,0), 
	"TC_ID" NUMBER(12,0), 
	"STATUS" VARCHAR2(12 BYTE), 
	"STATUS_CONTROL" VARCHAR2(1 BYTE), 
	"XML_DATA" "SYS"."XMLTYPE" , 
	"START_DATETIME" DATE, 
	"END_DATETIME" DATE
   ) ;

   COMMENT ON TABLE "SAVEMGR"."TEMPLATE_CLAUSE_DETAILS"  IS 'Save of "BPMMGR"."TEMPLATE_CLAUSE_DETAILS" at 19-SEP-2008 18:04:54';
  GRANT SELECT ON "SAVEMGR"."TEMPLATE_CLAUSE_DETAILS" TO "BPMMGR";
