--------------------------------------------------------
--  DDL for Table TOKEN_REQUESTS
--------------------------------------------------------

  CREATE TABLE "SECUREMGR"."TOKEN_REQUESTS" 
   (	"ID" NUMBER, 
	"TOKEN" VARCHAR2(32 BYTE), 
	"EXPIRY_DATE" DATE, 
	"USED" VARCHAR2(1 BYTE) DEFAULT 'N', 
	"PARAMS_XML" "SYS"."XMLTYPE" 
   ) 
 XMLTYPE COLUMN "PARAMS_XML" STORE AS SECUREFILE BINARY XML "TR_PARAMS_XML_DATA"(DISABLE STORAGE IN ROW CHUNK 8192
  CACHE  NOCOMPRESS  KEEP_DUPLICATES ) ALLOW NONSCHEMA DISALLOW ANYSCHEMA ;
