--------------------------------------------------------
--  DDL for Table TRANSMISSION_SET
--------------------------------------------------------

  CREATE TABLE "PORTALMGR"."TRANSMISSION_SET" 
   (	"MAIL_ID" NUMBER(12,0), 
	"REQUESTED_DATE" DATE, 
	"REQUESTED_BY" VARCHAR2(30 BYTE), 
	"ATT_CHECKSUM" NUMBER(3,0), 
	"METADATA" "SYS"."XMLTYPE" , 
	"STATUS" VARCHAR2(20 BYTE), 
	"STATUS_CHANGE_DATE" DATE, 
	"APP_KEY" VARCHAR2(100 BYTE), 
	"APP_DESC" VARCHAR2(1000 BYTE), 
	"APP_CONTENT_TYPE" VARCHAR2(4000 BYTE), 
	"GROUP_ID" NUMBER, 
	"DOMAIN" VARCHAR2(60 BYTE), 
	"SHOW_COPY_RECIPIENTS" VARCHAR2(5 BYTE)
   ) ;
