--------------------------------------------------------
--  DDL for Table TRANSMISSION_CONTENT
--------------------------------------------------------

  CREATE TABLE "PORTALMGR"."TRANSMISSION_CONTENT" 
   (	"MAIL_ID" NUMBER(10,0), 
	"ATT_SEQ" NUMBER(10,0), 
	"FILENAME" VARCHAR2(200 BYTE), 
	"MIMETYPE" VARCHAR2(200 BYTE), 
	"BINARY_ATTACHMENT" BLOB, 
	"TEXT_ATTACHMENT" CLOB, 
	"DI_ID" NUMBER DEFAULT NULL, 
	"DOC_TIMEOUT_TEXT" VARCHAR2(500 BYTE) DEFAULT NULL
   ) 
 LOB ("BINARY_ATTACHMENT") STORE AS BASICFILE "TRANS_CONT_BIN_ATT"(DISABLE STORAGE IN ROW CHUNK 8192 PCTVERSION 10
  CACHE ) 
 LOB ("TEXT_ATTACHMENT") STORE AS BASICFILE "TRANS_CONT_TEXT_ATT"(DISABLE STORAGE IN ROW CHUNK 8192 RETENTION 
  CACHE )  ENABLE ROW MOVEMENT ;
  GRANT SELECT ON "PORTALMGR"."TRANSMISSION_CONTENT" TO "SPMIGUSER";
  GRANT SELECT ON "PORTALMGR"."TRANSMISSION_CONTENT" TO "DECMGR";
  GRANT UPDATE ON "PORTALMGR"."TRANSMISSION_CONTENT" TO "APPENV";
  GRANT SELECT ON "PORTALMGR"."TRANSMISSION_CONTENT" TO "APPENV";
  GRANT INSERT ON "PORTALMGR"."TRANSMISSION_CONTENT" TO "APPENV";
