--------------------------------------------------------
--  DDL for Table UREF_TYPES
--------------------------------------------------------

  CREATE TABLE "BPMMGR"."UREF_TYPES" 
   (	"UREF_TYPE" VARCHAR2(6 BYTE), 
	"OBJECT_OWNER" VARCHAR2(30 BYTE), 
	"OBJECT_NAME" VARCHAR2(30 BYTE), 
	"OBJECT_PK_1_COLUMN_NAME" VARCHAR2(30 BYTE), 
	"OBJECT_PK_2_COLUMN_NAME" VARCHAR2(30 BYTE), 
	"UREF_FK1_COLUMN_NAME" VARCHAR2(30 BYTE), 
	"UREF_FK2_COLUMN_NAME" VARCHAR2(30 BYTE), 
	"DESCRIPTION" VARCHAR2(60 BYTE), 
	"EXPANDED_TYPE" VARCHAR2(30 BYTE), 
	"CONTROL_XML" "SYS"."XMLTYPE" , 
	"ENTER_COMMAND_HERE" VARCHAR2(10 BYTE), 
	"LAST_SYSTEM_MESSAGE" VARCHAR2(4000 BYTE), 
	"INTERNAL_NAME" VARCHAR2(20 BYTE), 
	"STRATEGY" VARCHAR2(8 BYTE) DEFAULT 'STANDARD'
   ) ;

   COMMENT ON COLUMN "BPMMGR"."UREF_TYPES"."ENTER_COMMAND_HERE" IS 'c=create, d=drop';
   COMMENT ON COLUMN "BPMMGR"."UREF_TYPES"."STRATEGY" IS 'This column is used to distinguish how to create uref records for a particular uref type.  Just in time "JIT" or "STANDARD".';
  GRANT REFERENCES ON "BPMMGR"."UREF_TYPES" TO "DECMGR";
  GRANT SELECT ON "BPMMGR"."UREF_TYPES" TO "ENVMGR";
  GRANT SELECT ON "BPMMGR"."UREF_TYPES" TO "APPENV";
  GRANT SELECT ON "BPMMGR"."UREF_TYPES" TO "APPBPM";
