--------------------------------------------------------
--  DDL for Table WEB_ORG_TYPES
--------------------------------------------------------

  CREATE TABLE "PORTALMGR"."WEB_ORG_TYPES" 
   (	"ID" NUMBER(12,0), 
	"TYPE_NAME" VARCHAR2(30 BYTE), 
	"TYPE_DESCRIPTION" VARCHAR2(240 BYTE), 
	"LAST_DML_DATE" DATE, 
	"LAST_DML_BY" VARCHAR2(240 BYTE)
   ) ;
  GRANT SELECT ON "PORTALMGR"."WEB_ORG_TYPES" TO "SPMIGUSER";
  GRANT SELECT ON "PORTALMGR"."WEB_ORG_TYPES" TO "SECUREMGR" WITH GRANT OPTION;
  GRANT SELECT ON "PORTALMGR"."WEB_ORG_TYPES" TO "FOXMGR";
  GRANT SELECT ON "PORTALMGR"."WEB_ORG_TYPES" TO "ENVMGR" WITH GRANT OPTION;
  GRANT SELECT ON "PORTALMGR"."WEB_ORG_TYPES" TO "DECMGR";
  GRANT SELECT ON "PORTALMGR"."WEB_ORG_TYPES" TO "BPMMGR";
  GRANT SELECT ON "PORTALMGR"."WEB_ORG_TYPES" TO "APPENV";
