--------------------------------------------------------
--  DDL for Table WEB_USER_ACCOUNT_MASTER
--------------------------------------------------------

  CREATE TABLE "SECUREMGR"."WEB_USER_ACCOUNT_MASTER" 
   (	"WUA_ID" NUMBER(12,0), 
	"LAST_LOGIN_DATE_TIME" DATE, 
	"LAST_LOGOUT_DATE_TIME" DATE
   ) ;
  GRANT REFERENCES ON "SECUREMGR"."WEB_USER_ACCOUNT_MASTER" TO "SPIREMGR";
  GRANT REFERENCES ON "SECUREMGR"."WEB_USER_ACCOUNT_MASTER" TO "SPMIGUSER";
  GRANT REFERENCES ON "SECUREMGR"."WEB_USER_ACCOUNT_MASTER" TO "XVIEWMGR";
  GRANT REFERENCES ON "SECUREMGR"."WEB_USER_ACCOUNT_MASTER" TO "ENVMGR";
  GRANT SELECT ON "SECUREMGR"."WEB_USER_ACCOUNT_MASTER" TO "ENVMGR";
  GRANT REFERENCES ON "SECUREMGR"."WEB_USER_ACCOUNT_MASTER" TO "DECMGR";
  GRANT REFERENCES ON "SECUREMGR"."WEB_USER_ACCOUNT_MASTER" TO "BPMMGR";
  GRANT SELECT ON "SECUREMGR"."WEB_USER_ACCOUNT_MASTER" TO "BPMMGR";
  GRANT INDEX ON "SECUREMGR"."WEB_USER_ACCOUNT_MASTER" TO "BPMMGR";
  GRANT REFERENCES ON "SECUREMGR"."WEB_USER_ACCOUNT_MASTER" TO "SURVEYMGR";
  GRANT SELECT ON "SECUREMGR"."WEB_USER_ACCOUNT_MASTER" TO "SURVEYMGR";
