--------------------------------------------------------
--  DDL for Table WEB_APPLICATIONS
--------------------------------------------------------

  CREATE TABLE "PORTALMGR"."WEB_APPLICATIONS" 
   (	"ID" NUMBER(12,0), 
	"NAME" VARCHAR2(240 BYTE), 
	"HOME_URL" VARCHAR2(240 BYTE), 
	"MNEMONIC" VARCHAR2(10 BYTE), 
	"WINDOW_NAME" VARCHAR2(10 BYTE), 
	"APP_TEXT" CLOB, 
	"LAST_DML_DATE" DATE, 
	"LAST_DML_BY" VARCHAR2(30 BYTE), 
	"DISPLAY_SEQ" NUMBER(12,0)
   ) 
 LOB ("APP_TEXT") STORE AS BASICFILE "WEB_APPLICATIONS_APP_TEXT"(DISABLE STORAGE IN ROW CHUNK 8192 RETENTION 
  CACHE ) ;
