--------------------------------------------------------
--  DDL for Table WORKBASKET_ACTIONS
--------------------------------------------------------

  CREATE TABLE "BPMMGR"."WORKBASKET_ACTIONS" 
   (	"ID" NUMBER(12,0), 
	"START_OPERATION_ID" NUMBER(12,0), 
	"START_DATETIME" DATE, 
	"END_OPERATION_ID" NUMBER(12,0), 
	"END_DATETIME" DATE, 
	"XML_DATA" "SYS"."XMLTYPE" , 
	"BA_ID" NUMBER(12,0), 
	"BS_ID" NUMBER(12,0)
   ) ;
  GRANT DELETE ON "BPMMGR"."WORKBASKET_ACTIONS" TO "SPMIGUSER";
  GRANT REFERENCES ON "BPMMGR"."WORKBASKET_ACTIONS" TO "XVIEWMGR";
  GRANT SELECT ON "BPMMGR"."WORKBASKET_ACTIONS" TO "ENVMGR";
  GRANT DELETE ON "BPMMGR"."WORKBASKET_ACTIONS" TO "DECMGR";
  GRANT SELECT ON "BPMMGR"."WORKBASKET_ACTIONS" TO "APPENV";
  GRANT SELECT ON "BPMMGR"."WORKBASKET_ACTIONS" TO "APPBPM";
