--------------------------------------------------------
--  DDL for Table WORKBASKETS
--------------------------------------------------------

  CREATE TABLE "BPMMGR"."WORKBASKETS" 
   (	"ID" NUMBER(12,0), 
	"SCOPE_UREF" VARCHAR2(20 BYTE), 
	"WB_TYPE" VARCHAR2(30 BYTE)
   ) ;
  GRANT SELECT ON "BPMMGR"."WORKBASKETS" TO "SPIREMGR";
  GRANT SELECT ON "BPMMGR"."WORKBASKETS" TO "ENVMGR";
  GRANT SELECT ON "BPMMGR"."WORKBASKETS" TO "APPENV";
  GRANT SELECT ON "BPMMGR"."WORKBASKETS" TO "APPBPM";
