--------------------------------------------------------
--  DDL for Table WORKBASKET_ACTION_PREFERENCES
--------------------------------------------------------

  CREATE TABLE "BPMMGR"."WORKBASKET_ACTION_PREFERENCES" 
   (	"ID" NUMBER(12,0), 
	"WBA_ID" NUMBER(12,0), 
	"WUA_ID" NUMBER(12,0), 
	"ACTION_MNEM" VARCHAR2(200 BYTE), 
	"SELECTED_FLAG" VARCHAR2(1 BYTE), 
	"HIDE_UNTIL_DATETIME" DATE, 
	"CATEGORY_NAME" VARCHAR2(40 BYTE), 
	"USER_COMMENT" VARCHAR2(200 BYTE), 
	"FIRST_DAY_ACCESS_DATETIME" DATE, 
	"ACCESSED_DAYS_COUNT" NUMBER(12,0), 
	"CHECKBOX_SELECTED" VARCHAR2(5 BYTE) DEFAULT 'false', 
	"USER_REMOVED_DATETIME" DATE, 
	"WB_TYPE" VARCHAR2(30 BYTE) DEFAULT 'WORK', 
	"WORKBASKET_UREF" VARCHAR2(50 BYTE), 
	"ACTION_PROMPT" VARCHAR2(200 BYTE), 
	"LAST_ACCESSED_DATETIME" DATE, 
	"ACTION_ORDER" NUMBER(5,0), 
	"VIEWER_WUA_ID" NUMBER(12,0)
   ) ;

   COMMENT ON COLUMN "BPMMGR"."WORKBASKET_ACTION_PREFERENCES"."WBA_ID" IS 'Foreign Key to workbasket_actions';
   COMMENT ON COLUMN "BPMMGR"."WORKBASKET_ACTION_PREFERENCES"."WUA_ID" IS 'Foreign key to web_user_accounts';
   COMMENT ON COLUMN "BPMMGR"."WORKBASKET_ACTION_PREFERENCES"."ACTION_MNEM" IS 'Foreign key to actions';
   COMMENT ON COLUMN "BPMMGR"."WORKBASKET_ACTION_PREFERENCES"."SELECTED_FLAG" IS 'Flag to indicate whether action is included in the user filtered view or not';
   COMMENT ON COLUMN "BPMMGR"."WORKBASKET_ACTION_PREFERENCES"."CATEGORY_NAME" IS 'System set category';
   COMMENT ON COLUMN "BPMMGR"."WORKBASKET_ACTION_PREFERENCES"."USER_COMMENT" IS 'User modifiable comment';
   COMMENT ON COLUMN "BPMMGR"."WORKBASKET_ACTION_PREFERENCES"."ACCESSED_DAYS_COUNT" IS 'Each day accessed count';
   COMMENT ON COLUMN "BPMMGR"."WORKBASKET_ACTION_PREFERENCES"."CHECKBOX_SELECTED" IS 'Tickbox selected in advanced mode';
  GRANT DELETE ON "BPMMGR"."WORKBASKET_ACTION_PREFERENCES" TO "SPMIGUSER";
  GRANT DELETE ON "BPMMGR"."WORKBASKET_ACTION_PREFERENCES" TO "DECMGR";
  GRANT UPDATE ON "BPMMGR"."WORKBASKET_ACTION_PREFERENCES" TO "APPENV";
