--------------------------------------------------------
--  DDL for Table WORKBASKET_ENTRIES
--------------------------------------------------------

  CREATE TABLE "BPMMGR"."WORKBASKET_ENTRIES" 
   (	"WBA_ID" NUMBER(12,0), 
	"WB_ID" NUMBER(12,0)
   ) ;
  GRANT DELETE ON "BPMMGR"."WORKBASKET_ENTRIES" TO "SPIREMGR";
  GRANT SELECT ON "BPMMGR"."WORKBASKET_ENTRIES" TO "SPIREMGR";
  GRANT INSERT ON "BPMMGR"."WORKBASKET_ENTRIES" TO "SPIREMGR";
  GRANT DELETE ON "BPMMGR"."WORKBASKET_ENTRIES" TO "SPMIGUSER";
  GRANT SELECT ON "BPMMGR"."WORKBASKET_ENTRIES" TO "ENVMGR";
  GRANT DELETE ON "BPMMGR"."WORKBASKET_ENTRIES" TO "DECMGR";
  GRANT SELECT ON "BPMMGR"."WORKBASKET_ENTRIES" TO "APPENV";
  GRANT SELECT ON "BPMMGR"."WORKBASKET_ENTRIES" TO "APPBPM";
