--------------------------------------------------------
--  DDL for Table WORKBASKET_ACTIONS
--------------------------------------------------------

  CREATE TABLE "SAVEMGR"."WORKBASKET_ACTIONS" 
   (	"ID" NUMBER(12,0), 
	"START_OPERATION_ID" NUMBER(12,0), 
	"START_DATETIME" DATE, 
	"END_OPERATION_ID" NUMBER(12,0), 
	"END_DATETIME" DATE, 
	"XML_DATA" "SYS"."XMLTYPE" , 
	"BA_ID" NUMBER(12,0), 
	"BS_ID" NUMBER(12,0)
   ) ;

   COMMENT ON TABLE "SAVEMGR"."WORKBASKET_ACTIONS"  IS 'Save of "BPMMGR"."WORKBASKET_ACTIONS" at 24-APR-2009 19:30:36';
  GRANT SELECT ON "SAVEMGR"."WORKBASKET_ACTIONS" TO "BPMMGR";
