--------------------------------------------------------
--  DDL for Table WORKING_TABLE
--------------------------------------------------------

  CREATE TABLE "PORTALMGR"."WORKING_TABLE" 
   (	"SESSION_ID" NUMBER(20,19), 
	"SEQUENCE_NO" NUMBER(12,0), 
	"STATUS" VARCHAR2(30 BYTE), 
	"DATA_TYPE" VARCHAR2(10 BYTE), 
	"SAVED_DATA" CLOB, 
	"DATA_IN_USE" VARCHAR2(1 BYTE), 
	"LAST_DML_DATE" DATE, 
	"LAST_DML_BY" VARCHAR2(30 BYTE)
   ) 
 LOB ("SAVED_DATA") STORE AS BASICFILE "WORKING_TABLE_SAVED_DATA"(DISABLE STORAGE IN ROW CHUNK 8192 RETENTION 
  CACHE ) ;
