--------------------------------------------------------
--  DDL for Table WUA_PREFERENCE_CATEGORIES
--------------------------------------------------------

  CREATE TABLE "SAVEMGR"."WUA_PREFERENCE_CATEGORIES" 
   (	"CATEGORY_NAME" VARCHAR2(50 BYTE), 
	"XML_DATA" "SYS"."XMLTYPE" 
   ) ;

   COMMENT ON TABLE "SAVEMGR"."WUA_PREFERENCE_CATEGORIES"  IS 'Save of "SECUREMGR"."WUA_PREFERENCE_CATEGORIES" at 19-FEB-2013 19:09:08';
  GRANT SELECT ON "SAVEMGR"."WUA_PREFERENCE_CATEGORIES" TO "SECUREMGR";
