--------------------------------------------------------
--  DDL for Table WUA_PREFERENCE_CATEGORIES
--------------------------------------------------------

  CREATE TABLE "SECUREMGR"."WUA_PREFERENCE_CATEGORIES" 
   (	"CATEGORY_NAME" VARCHAR2(50 BYTE), 
	"XML_DATA" "SYS"."XMLTYPE" 
   ) 
 XMLTYPE COLUMN "XML_DATA" STORE AS BASICFILE CLOB "WUA_PREF_CAT_XML_DATA"(DISABLE STORAGE IN ROW CHUNK 8192 RETENTION 
  CACHE ) ;
