--------------------------------------------------------
--  DDL for Table WUA_PREFERENCE_CATEGORIES_3
--------------------------------------------------------

  CREATE TABLE "SAVEMGR"."WUA_PREFERENCE_CATEGORIES_3" 
   (	"CATEGORY_NAME" VARCHAR2(50 BYTE), 
	"XML_DATA" "SYS"."XMLTYPE" 
   ) ;

   COMMENT ON TABLE "SAVEMGR"."WUA_PREFERENCE_CATEGORIES_3"  IS 'Save of "SECUREMGR"."WUA_PREFERENCE_CATEGORIES" at 27-JUN-2013 18:55:35';
  GRANT SELECT ON "SAVEMGR"."WUA_PREFERENCE_CATEGORIES_3" TO "SECUREMGR";
