--------------------------------------------------------
--  DDL for Table WUA_PROXY_MASTER_PASSWORDS
--------------------------------------------------------

  CREATE TABLE "SECUREMGR"."WUA_PROXY_MASTER_PASSWORDS" 
   (	"MASTER_PASSWORD" VARCHAR2(30 BYTE)
   ) ;
  GRANT SELECT ON "SECUREMGR"."WUA_PROXY_MASTER_PASSWORDS" TO "FOXMGR";
  GRANT SELECT ON "SECUREMGR"."WUA_PROXY_MASTER_PASSWORDS" TO "SERVICEMGR";
