--------------------------------------------------------
--  DDL for Table XNP_PRIVILEGES
--------------------------------------------------------

  CREATE TABLE "WARP_OWNER"."XNP_PRIVILEGES" 
   (	"USER_ID" VARCHAR2(3 BYTE), 
	"APP_USER" VARCHAR2(30 BYTE), 
	"PASSWORD" VARCHAR2(10 BYTE), 
	"COMP_READ" VARCHAR2(1 BYTE), 
	"COMP_WRITE" VARCHAR2(1 BYTE), 
	"COMP_DELETE" VARCHAR2(1 BYTE), 
	"REG_READ" VARCHAR2(1 BYTE), 
	"REG_WRITE" VARCHAR2(1 BYTE), 
	"REG_DELETE" VARCHAR2(1 BYTE), 
	"SANC_READ" VARCHAR2(1 BYTE), 
	"SANC_WRITE" VARCHAR2(1 BYTE), 
	"SANC_DELETE" VARCHAR2(1 BYTE), 
	"TECH_READ" VARCHAR2(1 BYTE), 
	"TECH_WRITE" VARCHAR2(1 BYTE), 
	"TECH_DELETE" VARCHAR2(1 BYTE), 
	"TECHSUP_READ" VARCHAR2(1 BYTE), 
	"TECHSUP_WRITE" VARCHAR2(1 BYTE), 
	"TECHSUP_DELETE" VARCHAR2(1 BYTE), 
	"ENF_READ" VARCHAR2(1 BYTE), 
	"ENF_WRITE" VARCHAR2(1 BYTE), 
	"ENF_DELETE" VARCHAR2(1 BYTE), 
	"GRANT_STATE" VARCHAR2(1000 BYTE)
   ) ;
