--------------------------------------------------------
--  DDL for Table XV_BPD_ACTSETDSPTS_DATA
--------------------------------------------------------

  CREATE TABLE "XVIEWMGR"."XV_BPD_ACTSETDSPTS_DATA" 
   (	"BPD_ID" NUMBER(12,0), 
	"ACTION_SET_MNEM" VARCHAR2(200 BYTE), 
	"STAGE_LABEL" VARCHAR2(50 BYTE), 
	"TALLY" VARCHAR2(200 BYTE), 
	"STYLE" VARCHAR2(50 BYTE), 
	"DISPLAY_ORDER" NUMBER(12,0)
   ) ;
  GRANT SELECT ON "XVIEWMGR"."XV_BPD_ACTSETDSPTS_DATA" TO "BPMMGR" WITH GRANT OPTION;
