--------------------------------------------------------
--  DDL for Table XV_BPD_TALLIES_DATA
--------------------------------------------------------

  CREATE TABLE "XVIEWMGR"."XV_BPD_TALLIES_DATA" 
   (	"BPD_ID" NUMBER(12,0), 
	"PROCESS_SHORT_NAME" VARCHAR2(30 BYTE), 
	"TALLY" VARCHAR2(30 BYTE), 
	"INTERNAL_TALLY" VARCHAR2(30 BYTE), 
	"BPD_TALLY_TYPE" VARCHAR2(20 BYTE), 
	"TALLY_TYPE_DEFINITION" VARCHAR2(4000 BYTE), 
	"ROOT_TALLY" VARCHAR2(30 BYTE), 
	"SWITCH" VARCHAR2(30 BYTE), 
	"STAGE_LABEL" VARCHAR2(200 BYTE), 
	"SUBROUTINE_SHORT_NAME" VARCHAR2(200 BYTE), 
	"QUERY" CLOB
   ) ;
  GRANT SELECT ON "XVIEWMGR"."XV_BPD_TALLIES_DATA" TO "BPMMGR" WITH GRANT OPTION;
