--------------------------------------------------------
--  DDL for Table XV_COMPL_ACT_DTLS_DATA
--------------------------------------------------------

  CREATE TABLE "XVIEWMGR"."XV_COMPL_ACT_DTLS_DATA" 
   (	"CAD_ID" NUMBER(12,0), 
	"CA_ID" NUMBER, 
	"START_DATETIME" DATE, 
	"END_DATETIME" DATE, 
	"STATUS_CONTROL" VARCHAR2(1 BYTE), 
	"STATUS" VARCHAR2(50 BYTE), 
	"FF_ID" NUMBER, 
	"CREATED_DATETIME" DATE, 
	"CREATED_BY_WUA_ID" NUMBER, 
	"CREATED_BY_FULL_NAME" VARCHAR2(400 BYTE), 
	"ACTIVATED_DATETIME" DATE, 
	"ACTIVATED_BY_WUA_ID" NUMBER, 
	"ACTIVATED_BY_FULL_NAME" VARCHAR2(400 BYTE), 
	"ACTIVITY_TYPE" VARCHAR2(50 BYTE), 
	"WARNING_NUMBER" NUMBER
   ) ;
