--------------------------------------------------------
--  DDL for Table XV_CLAUSE_TYPES_DATA
--------------------------------------------------------

  CREATE TABLE "XVIEWMGR"."XV_CLAUSE_TYPES_DATA" 
   (	"CLAUSE_TYPE_ID" VARCHAR2(30 BYTE), 
	"CLAUSE_TITLE" VARCHAR2(200 BYTE), 
	"CLASS_TYPE" VARCHAR2(30 BYTE), 
	"CLASS_TITLE" VARCHAR2(200 BYTE), 
	"CLASS_DESCRIPTION" VARCHAR2(500 BYTE), 
	"SEVERITY_CODE" VARCHAR2(30 BYTE), 
	"SEVERITY_TITLE" VARCHAR2(200 BYTE), 
	"SEVERITY_DESCRIPTION" VARCHAR2(500 BYTE), 
	"INTENTION_DEFAULT_STATUS" VARCHAR2(30 BYTE), 
	"REASON_REQUIRED" VARCHAR2(30 BYTE), 
	"DELETABLE" VARCHAR2(30 BYTE), 
	"EDITABLE" VARCHAR2(30 BYTE), 
	"CLEARABLE" VARCHAR2(30 BYTE), 
	"VOIDABLE" VARCHAR2(5 BYTE), 
	"EVENT_REQUEST" VARCHAR2(100 BYTE), 
	"EVENT_RESPOND" VARCHAR2(100 BYTE), 
	"EVENT_REJECT" VARCHAR2(100 BYTE), 
	"EVENT_REQUEST_CONFIRM_TEXT" VARCHAR2(400 BYTE), 
	"EVENT_RESPOND_CONFIRM_TEXT" VARCHAR2(400 BYTE), 
	"EVENT_REJECT_CONFIRM_TEXT" VARCHAR2(400 BYTE), 
	"INTENTION_TYPE" VARCHAR2(15 BYTE), 
	"DISPLAY_COLOUR" VARCHAR2(100 BYTE), 
	"REQUEST_DEFINE_OWN_CONTEXT" VARCHAR2(5 BYTE), 
	"RESPOND_DEFINE_OWN_CONTEXT" VARCHAR2(5 BYTE), 
	"REJECT_DEFINE_OWN_CONTEXT" VARCHAR2(5 BYTE), 
	"VOIDABLE_ANYTIME_BY_CREATOR" VARCHAR2(5 BYTE), 
	"DEFINE_COUNTERSIGN_RECIPIENT" VARCHAR2(5 BYTE), 
	"LINKED_ESCALATE_FLAG" VARCHAR2(30 BYTE), 
	"RFI_IMMEDIATELY_CLOSABLE" VARCHAR2(5 BYTE)
   ) ;
  GRANT SELECT ON "XVIEWMGR"."XV_CLAUSE_TYPES_DATA" TO "BPMMGR" WITH GRANT OPTION;
