--------------------------------------------------------
--  DDL for Table XV_CNTRY_GRP_ATTR_DATA
--------------------------------------------------------

  CREATE TABLE "XVIEWMGR"."XV_CNTRY_GRP_ATTR_DATA" 
   (	"CGD_ID" NUMBER(12,0), 
	"COUNTRY_SET_ID" VARCHAR2(15 BYTE), 
	"COUNTRY_GROUP_ID" VARCHAR2(15 BYTE), 
	"ATTR_SET_ID" NUMBER, 
	"GROUP_NAME" VARCHAR2(4000 BYTE), 
	"NAME" VARCHAR2(4000 BYTE), 
	"VALUE" VARCHAR2(4000 BYTE)
   ) ;
  GRANT SELECT ON "XVIEWMGR"."XV_CNTRY_GRP_ATTR_DATA" TO "BPMMGR" WITH GRANT OPTION;
