--------------------------------------------------------
--  DDL for Table XV_DENIAL_DETAILS_DATA
--------------------------------------------------------

  CREATE TABLE "XVIEWMGR"."XV_DENIAL_DETAILS_DATA" 
   (	"DD_ID" NUMBER, 
	"D_ID" NUMBER, 
	"STATUS_CONTROL" VARCHAR2(1 BYTE), 
	"ERROR_STATUS" VARCHAR2(10 BYTE), 
	"REGULATOR_REF" VARCHAR2(20 BYTE), 
	"OTHER_REF" VARCHAR2(100 BYTE), 
	"ISSUING_COUNTRY_ID" VARCHAR2(10 BYTE), 
	"CREATED_DATETIME" DATE, 
	"DENIAL_STATUS" VARCHAR2(10 BYTE), 
	"GOODS_DESCRIPTION" VARCHAR2(4000 BYTE), 
	"QUANTITY" VARCHAR2(70 BYTE), 
	"MEASURE" VARCHAR2(50 BYTE), 
	"VALUE" VARCHAR2(50 BYTE), 
	"CURRENCY" VARCHAR2(10 BYTE), 
	"STATED_END_USE" VARCHAR2(4000 BYTE), 
	"LEGACY_FLAG" VARCHAR2(10 BYTE), 
	"LEGACY_DENIAL_ID" NUMBER, 
	"FILE_FOLDER_ID" NUMBER
   ) ;
  GRANT SELECT ON "XVIEWMGR"."XV_DENIAL_DETAILS_DATA" TO "SPIREMGR" WITH GRANT OPTION;
