--------------------------------------------------------
--  DDL for Table XV_DN_REGIMES_DATA
--------------------------------------------------------

  CREATE TABLE "XVIEWMGR"."XV_DN_REGIMES_DATA" 
   (	"DD_ID" NUMBER, 
	"D_ID" NUMBER, 
	"REGIME_CODE" VARCHAR2(20 BYTE), 
	"DN_TYPE" VARCHAR2(5 BYTE), 
	"REGIME_REG_REF" VARCHAR2(100 BYTE), 
	"PROCESSED_REGIME_REG_REF" VARCHAR2(100 BYTE), 
	"POC_NUMBER" VARCHAR2(100 BYTE), 
	"ACTIVE_FROM_DATE" DATE, 
	"REGIME_DENIAL_STATUS" VARCHAR2(10 BYTE), 
	"RATING_REFS" VARCHAR2(100 BYTE), 
	"REGIME_REFS" VARCHAR2(1000 BYTE), 
	"REASON_FOR_REFUSAL" VARCHAR2(4000 BYTE), 
	"NOTIFICATION_COMMENTS" VARCHAR2(4000 BYTE), 
	"REVOKE_COM_OUTBOUND_REF" VARCHAR2(200 BYTE), 
	"REVOKE_COM_INBOUND_REF" VARCHAR2(200 BYTE), 
	"REVOKE_ISSUED_DATE" DATE, 
	"EXPIRED_DATE" DATE
   ) ;
  GRANT SELECT ON "XVIEWMGR"."XV_DN_REGIMES_DATA" TO "SPIREMGR" WITH GRANT OPTION;
