--------------------------------------------------------
--  DDL for Table XV_DN_ENTITIES_DATA
--------------------------------------------------------

  CREATE TABLE "XVIEWMGR"."XV_DN_ENTITIES_DATA" 
   (	"DD_ID" NUMBER, 
	"D_ID" NUMBER, 
	"ENTITY_ID" NUMBER, 
	"ENTITY_NAME" VARCHAR2(350 BYTE), 
	"ADDRESS" VARCHAR2(1000 BYTE), 
	"COUNTRY_ID" NUMBER, 
	"POSTCODE" VARCHAR2(20 BYTE), 
	"PROCESSED_ENTITY_DETAILS" VARCHAR2(1400 BYTE), 
	"TEL" VARCHAR2(30 BYTE), 
	"FAX" VARCHAR2(30 BYTE), 
	"END_USER_FLAG" VARCHAR2(10 BYTE), 
	"CONSIGNEE_FLAG" VARCHAR2(10 BYTE), 
	"OTHER_ROLE" VARCHAR2(200 BYTE)
   ) ;
  GRANT SELECT ON "XVIEWMGR"."XV_DN_ENTITIES_DATA" TO "SPIREMGR" WITH GRANT OPTION;
