--------------------------------------------------------
--  DDL for Table XV_DOC_DATA_DATA
--------------------------------------------------------

  CREATE TABLE "XVIEWMGR"."XV_DOC_DATA_DATA" 
   (	"DD_ID" NUMBER(12,0), 
	"DI_ID" NUMBER(12,0), 
	"STATUS" VARCHAR2(12 BYTE), 
	"DD_IMMUTABLE_ID" NUMBER(12,0), 
	"DISPLAY_SEQ" NUMBER(12,0), 
	"TITLE" VARCHAR2(4000 BYTE), 
	"CONTENT_TYPE" VARCHAR2(4000 BYTE), 
	"CONTENT_DESCRIPTION" VARCHAR2(4000 BYTE), 
	"SYSTEM_DOCUMENT" VARCHAR2(4000 BYTE), 
	"OU_ID" NUMBER(12,0), 
	"ORGAN_NAME" VARCHAR2(4000 BYTE), 
	"REGISTERED_NUMBER" VARCHAR2(4000 BYTE)
   ) ;
