--------------------------------------------------------
--  DDL for Table XV_DOC_TEMPLATE_DATA
--------------------------------------------------------

  CREATE TABLE "XVIEWMGR"."XV_DOC_TEMPLATE_DATA" 
   (	"TEMPLATE_NAME" VARCHAR2(60 BYTE), 
	"TITLE" VARCHAR2(4000 BYTE), 
	"HINT_TEXT" VARCHAR2(4000 BYTE)
   ) ;
  GRANT SELECT ON "XVIEWMGR"."XV_DOC_TEMPLATE_DATA" TO "SPMIGUSER" WITH GRANT OPTION;
  GRANT SELECT ON "XVIEWMGR"."XV_DOC_TEMPLATE_DATA" TO "DECMGR" WITH GRANT OPTION;
