--------------------------------------------------------
--  DDL for Table XV_ELA_GOODS_CHAR_DATA
--------------------------------------------------------

  CREATE TABLE "SAVEMGR"."XV_ELA_GOODS_CHAR_DATA" 
   (	"ELA_DETAIL_ID" NUMBER(12,0), 
	"ITEM_NO" NUMBER(12,0), 
	"TYPE" VARCHAR2(10 BYTE), 
	"VALUE" VARCHAR2(4000 BYTE), 
	"BASE_VALUE" VARCHAR2(4000 BYTE), 
	"QUANTITY" NUMBER, 
	"POSITION" NUMBER
   ) ;

   COMMENT ON TABLE "SAVEMGR"."XV_ELA_GOODS_CHAR_DATA"  IS 'Save of "XVIEWMGR"."XV_ELA_GOODS_CHAR_DATA" at 07-FEB-2009 17:35:05';
  GRANT SELECT ON "SAVEMGR"."XV_ELA_GOODS_CHAR_DATA" TO "XVIEWMGR";
