--------------------------------------------------------
--  DDL for Table XV_ELA_GOODS_DATA
--------------------------------------------------------

  CREATE TABLE "XVIEWMGR"."XV_ELA_GOODS_DATA" 
   (	"ELA_DETAIL_ID" NUMBER, 
	"ITEM_NO" NUMBER, 
	"DESCRIPTION" VARCHAR2(4000 BYTE), 
	"PART_NO" VARCHAR2(500 BYTE), 
	"EXPORT_CONTROL_ENTRY" VARCHAR2(4000 BYTE), 
	"GOODS_QUANTITY_MEASURE" VARCHAR2(100 BYTE), 
	"GOODS_QUANTITY" VARCHAR2(100 BYTE), 
	"GOODS_VALUE" VARCHAR2(100 BYTE), 
	"MANUFACTURERS_HOMEPAGE" VARCHAR2(500 BYTE), 
	"END_USE_INFORM_EXHAUSTED_FLAG" VARCHAR2(10 BYTE), 
	"FINAL_OUTCOME" VARCHAR2(4000 BYTE), 
	"ORIGINAL_FINAL_OUTCOME" VARCHAR2(4000 BYTE), 
	"REASON_FOR_REFUSAL" VARCHAR2(4000 BYTE), 
	"XML_DATA" "XVIEWMGR"."XMLTYPE", 
	"ITEM_NAME" VARCHAR2(4000 BYTE), 
	"DTI_COMMENT" VARCHAR2(4100 BYTE), 
	"LINE_NO" NUMBER, 
	"TECHNICAL_DESCRIPTION" CLOB
   ) ;
  GRANT SELECT ON "XVIEWMGR"."XV_ELA_GOODS_DATA" TO "SPIREMGR" WITH GRANT OPTION;
