--------------------------------------------------------
--  DDL for Table XV_ELA_GDS_CNTRY_DATA
--------------------------------------------------------

  CREATE TABLE "XVIEWMGR"."XV_ELA_GDS_CNTRY_DATA" 
   (	"ELA_DETAIL_ID" NUMBER(12,0), 
	"COUNTRY_ID" NUMBER(12,0), 
	"GOODS_ITEM_ID" NUMBER(12,0), 
	"DC_ID" NUMBER(12,0), 
	"SOURCE_FLAG" VARCHAR2(5 BYTE), 
	"DESTINATION_FLAG" VARCHAR2(5 BYTE), 
	"DESTINATION_OVERRIDE_FLAG" VARCHAR2(5 BYTE), 
	"OUTCOME" VARCHAR2(4000 BYTE), 
	"LD_ID" NUMBER(12,0), 
	"LICENCE_LINE_NUMBER" NUMBER(12,0), 
	"PRIOR_AMENDMENT_LD_ID" NUMBER
   ) ;
  GRANT SELECT ON "XVIEWMGR"."XV_ELA_GDS_CNTRY_DATA" TO "SPIREMGR" WITH GRANT OPTION;
