--------------------------------------------------------
--  DDL for Table XV_FOLDER_TYPES_DATA
--------------------------------------------------------

  CREATE TABLE "XVIEWMGR"."XV_FOLDER_TYPES_DATA" 
   (	"FILE_FOLDER_TYPE" VARCHAR2(30 BYTE), 
	"TITLE" VARCHAR2(4000 BYTE), 
	"DESCRIPTION" VARCHAR2(4000 BYTE), 
	"VERSION_CONTROL_ENABLED" VARCHAR2(100 BYTE), 
	"DOWNLOAD_FILES_ARE_HIDEABLE" VARCHAR2(5 BYTE), 
	"UPLOAD_PROMPT" VARCHAR2(4000 BYTE), 
	"DOWNLOAD_PROMPT" VARCHAR2(4000 BYTE), 
	"SHOW_TARGET_STATUS" VARCHAR2(4000 BYTE), 
	"INTERNAL_SCAN_ENABLED" VARCHAR2(5 BYTE), 
	"EXTERNAL_SCAN_ENABLED" VARCHAR2(5 BYTE), 
	"SCAN_TYPE" VARCHAR2(100 BYTE), 
	"PRIMARY_PURPOSE" VARCHAR2(100 BYTE), 
	"SECONDARY_PURPOSE" VARCHAR2(100 BYTE), 
	"DEFAULT_EMAIL_TARGET" VARCHAR2(4000 BYTE)
   ) ;
