--------------------------------------------------------
--  DDL for Table XV_INTENTION_DTLS_DATA
--------------------------------------------------------

  CREATE TABLE "XVIEWMGR"."XV_INTENTION_DTLS_DATA" 
   (	"ID_ID" NUMBER(12,0), 
	"IN_ID" NUMBER(12,0), 
	"STATUS" VARCHAR2(50 BYTE), 
	"START_DATETIME" DATE, 
	"END_DATETIME" DATE, 
	"CLAUSE_TYPE" VARCHAR2(50 BYTE), 
	"CLASS_TYPE" VARCHAR2(400 BYTE), 
	"SEVERITY" VARCHAR2(400 BYTE), 
	"REASON_CODE" VARCHAR2(50 BYTE), 
	"CLAUSE_ID" NUMBER(12,0), 
	"CLAUSE_STATUS" VARCHAR2(50 BYTE), 
	"DISPLAY_ORDER" NUMBER(12,0), 
	"DELETE_FLAG" VARCHAR2(10 BYTE), 
	"EDIT_FLAG" VARCHAR2(10 BYTE), 
	"CLEAR_FLAG" VARCHAR2(10 BYTE), 
	"CREATED_BY_WUA_ID" VARCHAR2(4000 BYTE), 
	"CREATED_BY_WUA_FULL_NAME" VARCHAR2(400 BYTE), 
	"CREATED_DATETIME" DATE, 
	"CLAUSE_TEXT" "XVIEWMGR"."XMLTYPE", 
	"RESPONSE_TEXT" "XVIEWMGR"."XMLTYPE", 
	"VOIDED_TEXT" "XVIEWMGR"."XMLTYPE", 
	"IGNORE_FLAG" VARCHAR2(10 BYTE), 
	"IGNORE_TEXT" VARCHAR2(200 BYTE)
   ) ;
  GRANT SELECT ON "XVIEWMGR"."XV_INTENTION_DTLS_DATA" TO "BPMMGR" WITH GRANT OPTION;
