--------------------------------------------------------
--  DDL for Table XV_MATRIX_FOLDERS_DATA
--------------------------------------------------------

  CREATE TABLE "XVIEWMGR"."XV_MATRIX_FOLDERS_DATA" 
   (	"MF_ID" NUMBER(12,0), 
	"MF_TYPE" VARCHAR2(255 BYTE), 
	"MATRIX_URI" VARCHAR2(15 BYTE), 
	"RECORD_NUMBER" VARCHAR2(30 BYTE), 
	"RECORD_TITLE" VARCHAR2(300 BYTE), 
	"RECORD_TYPE_URI" VARCHAR2(15 BYTE), 
	"RECORD_TYPE" VARCHAR2(30 BYTE), 
	"F_APPROVED" VARCHAR2(30 BYTE), 
	"CREATED_DT" DATE, 
	"CLOSED_DT" DATE, 
	"EXTERNAL_REFERENCE" VARCHAR2(4000 BYTE), 
	"REGISTERED_DT" DATE, 
	"NOTES" VARCHAR2(4000 BYTE), 
	"PAPER_FILE" VARCHAR2(5 BYTE), 
	"IS_UNRESOLVED" VARCHAR2(5 BYTE), 
	"CREATED_BY_WUA" NUMBER
   ) ;
