--------------------------------------------------------
--  DDL for Table XV_NOTIFICATION_DATA
--------------------------------------------------------

  CREATE TABLE "XVIEWMGR"."XV_NOTIFICATION_DATA" 
   (	"N_ID" NUMBER(12,0), 
	"NS_ID" NUMBER(12,0), 
	"DP_ID" NUMBER(12,0), 
	"ACKNOWLEDGEMENT_STATUS" VARCHAR2(30 BYTE), 
	"ACKNOWLEDGEMENT_BY" VARCHAR2(255 BYTE), 
	"ACKNOWLEDGEMENT_DATE" DATE, 
	"VIEW_STATUS" VARCHAR2(30 BYTE), 
	"OBJECTION_STATUS" VARCHAR2(30 BYTE), 
	"DTI_COMMENT" VARCHAR2(4000 BYTE), 
	"LAST_CANCELLED_BY" VARCHAR2(255 BYTE), 
	"LAST_CANCELLED_DATETIME" DATE, 
	"LAST_REQUESTED_AGAIN_BY" VARCHAR2(255 BYTE), 
	"LAST_REQUESTED_AGAIN_DATETIME" DATE, 
	"LAPSED_FLAG" VARCHAR2(5 BYTE)
   ) ;
