--------------------------------------------------------
--  DDL for Table XV_ORG_SIC_CODES_DATA
--------------------------------------------------------

  CREATE TABLE "XVIEWMGR"."XV_ORG_SIC_CODES_DATA" 
   (	"OD_ID" NUMBER(12,0), 
	"ORGAN_ID" NUMBER(8,0), 
	"SIC_CODE" VARCHAR2(10 BYTE), 
	"DESCRIPTION" VARCHAR2(500 BYTE)
   ) ;
  GRANT SELECT ON "XVIEWMGR"."XV_ORG_SIC_CODES_DATA" TO "SPMIGUSER" WITH GRANT OPTION;
  GRANT SELECT ON "XVIEWMGR"."XV_ORG_SIC_CODES_DATA" TO "DECMGR" WITH GRANT OPTION;
