--------------------------------------------------------
--  DDL for Table XV_OGL_TYPE_REV_DATA
--------------------------------------------------------

  CREATE TABLE "XVIEWMGR"."XV_OGL_TYPE_REV_DATA" 
   (	"OGL_TYPE_CONDITION_DETAIL_ID" NUMBER, 
	"OGL_TYPE_CONDITION_ID" NUMBER, 
	"STATUS_CONTROL" VARCHAR2(1 BYTE), 
	"REVISION_ID" NUMBER, 
	"REVISION_VERSION" NUMBER, 
	"NAME" VARCHAR2(4000 BYTE), 
	"START_DATE" DATE, 
	"END_DATE" DATE, 
	"INTANGIBLE_DECLARATION" VARCHAR2(5 BYTE), 
	"OGL_DESCRIPTION" "SYS"."XMLTYPE" , 
	"LINK_TO_OGL" VARCHAR2(1000 BYTE), 
	"OGL_TYPE" VARCHAR2(4000 BYTE), 
	"VIRTUAL_OGEL_FLAG" VARCHAR2(10 BYTE), 
	"OGL_ACTIVITY" VARCHAR2(50 BYTE), 
	"INCLUDE_IN_SEARCH" VARCHAR2(1 BYTE), 
	"CONDITION_LIST" "SYS"."XMLTYPE" , 
	"RATING_CONDITION_LIST" "SYS"."XMLTYPE" , 
	"MIGRATED_REVISION" VARCHAR2(5 BYTE), 
	"ENFORCED_DATE" DATE, 
	"EXPANDED_CONDITION_LIST" "SYS"."XMLTYPE" 
   ) ;
  GRANT SELECT ON "XVIEWMGR"."XV_OGL_TYPE_REV_DATA" TO "SPIREMGR" WITH GRANT OPTION;
