--------------------------------------------------------
--  DDL for Table XV_ORG_UNITS_DATA
--------------------------------------------------------

  CREATE TABLE "XVIEWMGR"."XV_ORG_UNITS_DATA" 
   (	"OD_ID" NUMBER(12,0), 
	"ORGAN_ID" NUMBER(8,0), 
	"SHORT_NAME" VARCHAR2(12 BYTE), 
	"NAME" VARCHAR2(200 BYTE), 
	"NATIONALITY" VARCHAR2(4 BYTE), 
	"CREATED_BY_DEPT" VARCHAR2(6 BYTE), 
	"COMMENTS" VARCHAR2(80 BYTE), 
	"CREATED_BY" VARCHAR2(30 BYTE), 
	"CREATED_DATE" DATE, 
	"LAST_UPDATED_BY" VARCHAR2(30 BYTE), 
	"LAST_UPDATED_DATE" DATE, 
	"REGISTERED_NUMBER" VARCHAR2(9 BYTE), 
	"FOREIGN_REGISTERED_NUMBER" VARCHAR2(100 BYTE), 
	"COUNTRY_OF_ORIGIN" VARCHAR2(4000 BYTE), 
	"ORIGIN_COUNTRY_CODE" VARCHAR2(4000 BYTE), 
	"START_DATE" DATE, 
	"END_DATE" DATE, 
	"GENERAL_INFO" VARCHAR2(4000 BYTE), 
	"WARNING_INFO" VARCHAR2(34 BYTE)
   ) ;
