--------------------------------------------------------
--  DDL for Table XV_OGL_TYPE_COND_DATA
--------------------------------------------------------

  CREATE TABLE "XVIEWMGR"."XV_OGL_TYPE_COND_DATA" 
   (	"OGL_TYPE_CONDITION_DETAIL_ID" NUMBER, 
	"OGL_TYPE_CONDITION_ID" NUMBER, 
	"REVISION_NAME" VARCHAR2(4000 BYTE), 
	"REVISION_ID" NUMBER, 
	"CONDITION_NO" NUMBER, 
	"RATINGS_LIST" "SYS"."XMLTYPE" , 
	"SECONDARY_RATINGS_LIST" "SYS"."XMLTYPE" , 
	"END_USER_TYPE_GOV" VARCHAR2(5 BYTE), 
	"END_USER_TYPE_COM" VARCHAR2(5 BYTE), 
	"END_USER_TYPE_IND" VARCHAR2(5 BYTE), 
	"END_USER_TYPE_OTHER" VARCHAR2(5 BYTE), 
	"STATUS_CONTROL" VARCHAR2(1 BYTE)
   ) ;
