--------------------------------------------------------
--  DDL for Table XV_PVEX_EX_ITEMS_DATA
--------------------------------------------------------

  CREATE TABLE "XVIEWMGR"."XV_PVEX_EX_ITEMS_DATA" 
   (	"PEAD_ID" NUMBER, 
	"ITEM_NO" NUMBER, 
	"ITEM_NAME" VARCHAR2(200 BYTE), 
	"ITEM_TYPE" VARCHAR2(20 BYTE), 
	"OTHER_PLEASE_SPECIFY" VARCHAR2(100 BYTE), 
	"IS_ID" NUMBER, 
	"DECISION" VARCHAR2(20 BYTE), 
	"FINAL_DECISION" VARCHAR2(20 BYTE)
   ) ;
  GRANT SELECT ON "XVIEWMGR"."XV_PVEX_EX_ITEMS_DATA" TO "PVEXMGR" WITH GRANT OPTION;
