--------------------------------------------------------
--  DDL for Table XV_PORTAL_FDR_ABST_DATA
--------------------------------------------------------

  CREATE TABLE "XVIEWMGR"."XV_PORTAL_FDR_ABST_DATA" 
   (	"PFA_ID" NUMBER(12,0), 
	"PF_ID" NUMBER(12,0), 
	"DATETIME" DATE, 
	"TITLE" VARCHAR2(4000 BYTE), 
	"WUA_ID" VARCHAR2(4000 BYTE), 
	"TRANSACTION_REF" VARCHAR2(4000 BYTE)
   ) ;
  GRANT SELECT ON "XVIEWMGR"."XV_PORTAL_FDR_ABST_DATA" TO "SPMIGUSER" WITH GRANT OPTION;
  GRANT SELECT ON "XVIEWMGR"."XV_PORTAL_FDR_ABST_DATA" TO "DECMGR" WITH GRANT OPTION;
