--------------------------------------------------------
--  DDL for Table XV_PF_MATRIX_USAGE_DATA
--------------------------------------------------------

  CREATE TABLE "XVIEWMGR"."XV_PF_MATRIX_USAGE_DATA" 
   (	"PF_ID" NUMBER(12,0), 
	"MF_ID" NUMBER(12,0), 
	"PURPOSE_TYPE" VARCHAR2(4000 BYTE)
   ) ;
  GRANT SELECT ON "XVIEWMGR"."XV_PF_MATRIX_USAGE_DATA" TO "SPMIGUSER" WITH GRANT OPTION;
  GRANT SELECT ON "XVIEWMGR"."XV_PF_MATRIX_USAGE_DATA" TO "DECMGR" WITH GRANT OPTION;
