--------------------------------------------------------
--  DDL for Table XV_PVEX_NOVA_DETS_DATA
--------------------------------------------------------

  CREATE TABLE "XVIEWMGR"."XV_PVEX_NOVA_DETS_DATA" 
   (	"ND_ID" NUMBER, 
	"N_ID" NUMBER, 
	"STATUS_CONTROL" VARCHAR2(1 BYTE), 
	"SAR_ID" NUMBER, 
	"PREVIOUS_COMPANY_NAME" VARCHAR2(4000 BYTE), 
	"CURRENT_COMPANY_NAME" VARCHAR2(4000 BYTE), 
	"REASON_FOR_CHANGE" VARCHAR2(4000 BYTE), 
	"CREATED_BY_WUA_ID" NUMBER, 
	"CREATED_DATETIME" DATE, 
	"COMPLETED_BY_WUA_ID" NUMBER, 
	"COMPLETED_DATETIME" DATE, 
	"STATUS" VARCHAR2(100 BYTE), 
	"NOVATION_REFERENCE" VARCHAR2(4000 BYTE), 
	"LETTER_DECISION" VARCHAR2(20 BYTE)
   ) ;
  GRANT SELECT ON "XVIEWMGR"."XV_PVEX_NOVA_DETS_DATA" TO "PVEXMGR" WITH GRANT OPTION;
