--------------------------------------------------------
--  DDL for Table XV_PVEX_SUB_ADV_DATA
--------------------------------------------------------

  CREATE TABLE "XVIEWMGR"."XV_PVEX_SUB_ADV_DATA" 
   (	"PEAD_ID" NUMBER, 
	"REVIEWER_NAME" VARCHAR2(100 BYTE), 
	"REVIEWER_CONTACT_DETAILS" VARCHAR2(254 BYTE), 
	"REVIEWER_QUESTION" VARCHAR2(254 BYTE), 
	"SENT_DATE" DATE, 
	"TARGET_WORKING_DAYS" NUMBER, 
	"RESPONSE_DATE" DATE, 
	"REVIEW_RESPONSE" VARCHAR2(4000 BYTE), 
	"REVIEW_SAVED" VARCHAR2(5 BYTE), 
	"TARGET_DAYS_REACHED" VARCHAR2(5 BYTE)
   ) ;
