--------------------------------------------------------
--  DDL for Table XV_RES_MEMBER_HIST_DATA
--------------------------------------------------------

  CREATE TABLE "XVIEWMGR"."XV_RES_MEMBER_HIST_DATA" 
   (	"RD_ID" NUMBER(12,0), 
	"RES_ID" NUMBER(12,0), 
	"RR_ID" NUMBER(12,0), 
	"RES_TYPE" VARCHAR2(30 BYTE), 
	"ROLE_NAME" VARCHAR2(100 BYTE), 
	"MEMBER_ID" NUMBER, 
	"STATUS_CONTROL" VARCHAR2(1 BYTE), 
	"STATUS" VARCHAR2(12 BYTE), 
	"START_DATE" DATE, 
	"END_DATE" DATE, 
	"RESOURCE_PERSON_ID" NUMBER, 
	"ADDRESS_ID" NUMBER, 
	"LOCATION_AT_ADDRESS" VARCHAR2(4000 BYTE), 
	"QUALIFYING_COMMENT" VARCHAR2(4000 BYTE), 
	"BRANCH_NUMBER" VARCHAR2(4000 BYTE), 
	"BRANCH_START_DATE" DATE, 
	"AUTHORISATION_DATE" DATE, 
	"AUTHORISATION_COMMENT" VARCHAR2(4000 BYTE), 
	"WORK_TELEPHONE_NO_LIST" VARCHAR2(4000 BYTE), 
	"FAX_NO_LIST" VARCHAR2(4000 BYTE), 
	"MOBILE_TEL_NO" VARCHAR2(4000 BYTE), 
	"WORK_EMAIL_ADDRESS" VARCHAR2(4000 BYTE), 
	"LEGACY_NOTIFICATION_METHOD" VARCHAR2(4000 BYTE), 
	"LEGACY_CREATED_BY" VARCHAR2(4000 BYTE), 
	"LEGACY_CREATED_DATE" DATE, 
	"LEGACY_LAST_UPDATED_BY" VARCHAR2(4000 BYTE), 
	"LEGACY_LAST_UPDATED_DATE" DATE, 
	"RESOURCE_PERSON_ID_CURRENT" NUMBER GENERATED ALWAYS AS (CASE  WHEN "END_DATE" IS NULL THEN "RESOURCE_PERSON_ID" ELSE NULL END) VIRTUAL , 
	"RR_ID_CURRENT" NUMBER GENERATED ALWAYS AS (CASE  WHEN "END_DATE" IS NULL THEN "RR_ID" ELSE NULL END) VIRTUAL 
   ) ;
  GRANT SELECT ON "XVIEWMGR"."XV_RES_MEMBER_HIST_DATA" TO "SPMIGUSER" WITH GRANT OPTION;
  GRANT SELECT ON "XVIEWMGR"."XV_RES_MEMBER_HIST_DATA" TO "DECMGR" WITH GRANT OPTION;
