--------------------------------------------------------
--  DDL for Table XV_REPORT_COL_META_DATA
--------------------------------------------------------

  CREATE TABLE "XVIEWMGR"."XV_REPORT_COL_META_DATA" 
   (	"RP_ID" NUMBER, 
	"COL_SEQ" NUMBER, 
	"ACTUAL_NAME" VARCHAR2(4000 BYTE), 
	"LOGICAL_NAME" VARCHAR2(4000 BYTE), 
	"DATA_TYPE" VARCHAR2(4000 BYTE), 
	"DATA_LENGTH" NUMBER, 
	"DATA_SCALE" NUMBER, 
	"DATA_PRECISION" NUMBER
   ) ;
  GRANT SELECT ON "XVIEWMGR"."XV_REPORT_COL_META_DATA" TO "REPORTMGR" WITH GRANT OPTION;
