--------------------------------------------------------
--  DDL for Table XV_RESOURCES_DATA
--------------------------------------------------------

  CREATE TABLE "XVIEWMGR"."XV_RESOURCES_DATA" 
   (	"RES_ID" NUMBER(12,0), 
	"RES_TYPE" VARCHAR2(4000 BYTE), 
	"RES_NAME" VARCHAR2(4000 BYTE), 
	"DESCRIPTION" VARCHAR2(4000 BYTE)
   ) ;
  GRANT SELECT ON "XVIEWMGR"."XV_RESOURCES_DATA" TO "SPMIGUSER" WITH GRANT OPTION;
  GRANT SELECT ON "XVIEWMGR"."XV_RESOURCES_DATA" TO "DECMGR" WITH GRANT OPTION;
