--------------------------------------------------------
--  DDL for Table XV_REVIEW_RUN_DETS_DATA
--------------------------------------------------------

  CREATE TABLE "XVIEWMGR"."XV_REVIEW_RUN_DETS_DATA" 
   (	"RRUND_ID" NUMBER(12,0), 
	"RRUN_ID" NUMBER(12,0), 
	"START_DATETIME" DATE, 
	"END_DATETIME" DATE, 
	"STATUS_CONTROL" VARCHAR2(1 BYTE), 
	"CREATED_BY_WUA_ID" NUMBER(12,0), 
	"REVIEW_OPENED_DATE" DATE, 
	"REVIEW_CLOSED_DATE" DATE, 
	"REVIEW_COMPLETED_DATE" DATE, 
	"REVIEW_RUN_STATUS" VARCHAR2(4000 BYTE), 
	"REVIEW_RUN_INSTRUCTIONS" VARCHAR2(4000 BYTE), 
	"DI_ID" NUMBER(12,0)
   ) ;
