--------------------------------------------------------
--  DDL for Table XV_RES_TYPE_ROLES_DATA
--------------------------------------------------------

  CREATE TABLE "XVIEWMGR"."XV_RES_TYPE_ROLES_DATA" 
   (	"RES_TYPE" VARCHAR2(30 BYTE), 
	"ROLE_NAME" VARCHAR2(200 BYTE), 
	"ROLE_XML" "XVIEWMGR"."XMLTYPE", 
	"ROLE_TITLE" VARCHAR2(200 BYTE), 
	"ROLE_DESCRIPTION" VARCHAR2(4000 BYTE), 
	"MIN_MEMS" NUMBER(8,0), 
	"MAX_MEMS" NUMBER(8,0), 
	"DISPLAY_SEQ" NUMBER(8,0), 
	"PERSON_REQUIRED" VARCHAR2(8 BYTE), 
	"PERSON_REQUIRES_ACTIVE_WUA" VARCHAR2(8 BYTE), 
	"ADDRESS_REQUIRED" VARCHAR2(8 BYTE), 
	"TELEPHONE_REQUIRED" VARCHAR2(8 BYTE), 
	"EMAIL_REQUIRED" VARCHAR2(8 BYTE), 
	"QUALIFYING_COMMENT_REQUIRED" VARCHAR2(8 BYTE), 
	"BRANCH_REQUIRED" VARCHAR2(8 BYTE), 
	"AUTHORISATION_REQUIRED" VARCHAR2(8 BYTE), 
	"NOTIFICATION_METHOD_REQUIRED" VARCHAR2(8 BYTE), 
	"ALLOW_SHARED_ACCOUNTS" VARCHAR2(5 BYTE)
   ) ;
