--------------------------------------------------------
--  DDL for Table XV_REVIEW_ADV_DETS_DATA
--------------------------------------------------------

  CREATE TABLE "SAVEMGR"."XV_REVIEW_ADV_DETS_DATA" 
   (	"RAD_ID" NUMBER(12,0), 
	"RA_ID" NUMBER(12,0), 
	"START_DATETIME" DATE, 
	"END_DATETIME" DATE, 
	"STATUS_CONTROL" VARCHAR2(1 BYTE), 
	"CREATED_BY_WUA_ID" NUMBER(12,0), 
	"LEVEL_SEQ" VARCHAR2(50 BYTE), 
	"STATUS" VARCHAR2(50 BYTE), 
	"AAC_ID" VARCHAR2(50 BYTE), 
	"PERSON_ID" VARCHAR2(50 BYTE), 
	"PARENT_RA_ID" VARCHAR2(50 BYTE), 
	"REVIEW_DELIVERED_DATE" DATE, 
	"REVIEW_COMPLETED_DATE" DATE, 
	"REVIEW_CLOSED_DATE" DATE, 
	"SUB_ADVISOR_FORMAT" VARCHAR2(4000 BYTE), 
	"INTENTION_SET_ID" NUMBER(12,0), 
	"REVIEW_DEADLINE_DATE" DATE
   ) ;

   COMMENT ON TABLE "SAVEMGR"."XV_REVIEW_ADV_DETS_DATA"  IS 'Save of "XVIEWMGR"."XV_REVIEW_ADV_DETS_DATA" at 07-JUN-2011 17:26:02';
  GRANT SELECT ON "SAVEMGR"."XV_REVIEW_ADV_DETS_DATA" TO "XVIEWMGR";
