--------------------------------------------------------
--  DDL for Table XV_RES_PEOPLE_DATA
--------------------------------------------------------

  CREATE TABLE "XVIEWMGR"."XV_RES_PEOPLE_DATA" 
   (	"RPD_ID" NUMBER(12,0), 
	"RP_ID" NUMBER(12,0), 
	"STATUS_CONTROL" VARCHAR2(1 BYTE), 
	"STATUS" VARCHAR2(12 BYTE), 
	"FULL_NAME" VARCHAR2(4000 BYTE), 
	"INFORMAL_NAME" VARCHAR2(4000 BYTE), 
	"TITLE" VARCHAR2(4000 BYTE), 
	"SURNAME" VARCHAR2(4000 BYTE), 
	"PREFERRED_FORENAME" VARCHAR2(4000 BYTE), 
	"FORENAME" VARCHAR2(4000 BYTE), 
	"ORG_ID" NUMBER, 
	"WORK_ADDRESS_ID" NUMBER, 
	"TELEPHONE_HASH_CODE" VARCHAR2(60 BYTE), 
	"FAX_HASH_CODE" VARCHAR2(60 BYTE), 
	"JOB_DESCRIPTION" VARCHAR2(4000 BYTE), 
	"ORACLE_USER_ID" VARCHAR2(4000 BYTE), 
	"UNIX_LOGIN_ID" VARCHAR2(4000 BYTE), 
	"CREATED_BY" VARCHAR2(4000 BYTE), 
	"CREATED_DATE" DATE, 
	"LAST_UPDATED_BY" VARCHAR2(4000 BYTE), 
	"LAST_UPDATED_DATE" DATE, 
	"SELF_UPDATED_DATE" DATE, 
	"PORTAL_EMAIL_ADDRESS" VARCHAR2(4000 BYTE), 
	"LOCATION_AT_ADDRESS" VARCHAR2(4000 BYTE), 
	"ORGANISATION_DESCRIPTION" VARCHAR2(4000 BYTE), 
	"DEPARTMENT_DESCRIPTION" VARCHAR2(4000 BYTE), 
	"SHARE_ADDRESS_INFO" VARCHAR2(4000 BYTE), 
	"PROCESSED_EMAIL_DOMAIN" VARCHAR2(4000 BYTE), 
	"PERSON_TYPE" VARCHAR2(4000 BYTE), 
	"SECURITY_QUESTION_FLAG" CHAR(1 BYTE), 
	"DOB_FLAG" VARCHAR2(1 BYTE), 
	"SHARED_ACC_FLAG" CHAR(1 BYTE)
   ) ;
