--------------------------------------------------------
--  DDL for Table XV_REPORT_PRT_STY_DATA
--------------------------------------------------------

  CREATE TABLE "XVIEWMGR"."XV_REPORT_PRT_STY_DATA" 
   (	"DOMAIN" VARCHAR2(40 BYTE), 
	"PART_LABEL" VARCHAR2(2000 BYTE), 
	"STYLE_NAME" VARCHAR2(2000 BYTE), 
	"ALIGNMENT_ATTRIBUTES" VARCHAR2(4000 BYTE), 
	"FONT_ATTRIBUTES" VARCHAR2(4000 BYTE), 
	"INTERIOR_ATTRIBUTES" VARCHAR2(4000 BYTE), 
	"NUMBER_FORMAT_ATTRIBUTES" VARCHAR2(4000 BYTE)
   ) ;
  GRANT SELECT ON "XVIEWMGR"."XV_REPORT_PRT_STY_DATA" TO "REPORTMGR" WITH GRANT OPTION;
