--------------------------------------------------------
--  DDL for Table XV_REVIEW_BAT_DETS_DATA
--------------------------------------------------------

  CREATE TABLE "XVIEWMGR"."XV_REVIEW_BAT_DETS_DATA" 
   (	"RBD_ID" NUMBER(12,0), 
	"RB_ID" NUMBER(12,0), 
	"START_DATETIME" DATE, 
	"END_DATETIME" DATE, 
	"STATUS_CONTROL" VARCHAR2(1 BYTE), 
	"CREATED_BY_WUA_ID" NUMBER(12,0), 
	"BATCH_START_DATE" DATE, 
	"BATCH_END_DATE" DATE, 
	"BATCH_STATUS" VARCHAR2(50 BYTE), 
	"BATCH_STATUS_DISPLAY" VARCHAR2(50 BYTE), 
	"ADVICE_TYPE" VARCHAR2(30 BYTE), 
	"REVIEW_TYPE" VARCHAR2(30 BYTE)
   ) ;
