--------------------------------------------------------
--  DDL for Table XV_RES_TYPE_PRIVS_DATA
--------------------------------------------------------

  CREATE TABLE "XVIEWMGR"."XV_RES_TYPE_PRIVS_DATA" 
   (	"RES_TYPE" VARCHAR2(30 BYTE), 
	"ROLE_NAME" VARCHAR2(60 BYTE), 
	"DEFAULT_SYSTEM_PRIV" VARCHAR2(60 BYTE)
   ) ;
  GRANT SELECT ON "XVIEWMGR"."XV_RES_TYPE_PRIVS_DATA" TO "SPMIGUSER" WITH GRANT OPTION;
  GRANT SELECT ON "XVIEWMGR"."XV_RES_TYPE_PRIVS_DATA" TO "DECMGR" WITH GRANT OPTION;
