--------------------------------------------------------
--  DDL for Table XV_REPORT_PRTS_DATA
--------------------------------------------------------

  CREATE TABLE "XVIEWMGR"."XV_REPORT_PRTS_DATA" 
   (	"PART_ID" NUMBER, 
	"DOMAIN" VARCHAR2(80 BYTE), 
	"PART_LABEL" VARCHAR2(4000 BYTE), 
	"PART_TITLE" VARCHAR2(4000 BYTE), 
	"SEQ" VARCHAR2(4000 BYTE), 
	"CATEGORY" VARCHAR2(4000 BYTE), 
	"VISIBILITY" VARCHAR2(4000 BYTE), 
	"REQUEST_STATUS" VARCHAR2(4000 BYTE), 
	"SPREADSHEET_GEN_THRESHOLD" VARCHAR2(4000 BYTE), 
	"WORKSHEET_TITLE" VARCHAR2(31 BYTE), 
	"SQL_STATEMENT" CLOB, 
	"DOCUMENT_TEMPLATE" VARCHAR2(4000 BYTE), 
	"WORKBOOK" VARCHAR2(5 BYTE), 
	"GLOBAL_DOMAIN" VARCHAR2(80 BYTE), 
	"GLOBAL_NAME" VARCHAR2(4000 BYTE), 
	"SUB_ROOT_DOC_ELEMENT" VARCHAR2(4000 BYTE), 
	"RECORD_TARGET_PATH" VARCHAR2(4000 BYTE), 
	"FETCH_MODE" VARCHAR2(20 BYTE), 
	"FILE_TRANSMISSION_FLAG" VARCHAR2(5 BYTE), 
	"FILE_TRANSM_OUTPUT_TYPE" VARCHAR2(10 BYTE), 
	"FILE_TRANSM_FILE_NAME" VARCHAR2(255 BYTE), 
	"FILE_TRANSM_FILE_NAME_SQL" VARCHAR2(4000 BYTE), 
	"FILE_TRANSM_HASH_FILE_NAME" VARCHAR2(255 BYTE), 
	"FILE_TRANSM_HASH_FILE_NAME_SQL" VARCHAR2(4000 BYTE), 
	"JASPER_DEFINITION" VARCHAR2(4000 BYTE), 
	"JASPER_OUTPUTS" "SYS"."XMLTYPE" , 
	"WORKSHEET_OPTIONS_RAW" CLOB, 
	"AUTOFILTER_FLAG" VARCHAR2(5 BYTE), 
	"ALL_BORDERS_FLAG" VARCHAR2(5 BYTE)
   ) ;
  GRANT SELECT ON "XVIEWMGR"."XV_REPORT_PRTS_DATA" TO "REPORTMGR" WITH GRANT OPTION;
