--------------------------------------------------------
--  DDL for Table XV_RES_TYPES_RESTR_DATA
--------------------------------------------------------

  CREATE TABLE "XVIEWMGR"."XV_RES_TYPES_RESTR_DATA" 
   (	"RES_TYPE" VARCHAR2(30 BYTE), 
	"UREF_TYPE" VARCHAR2(4000 BYTE), 
	"PURPOSE" VARCHAR2(4000 BYTE), 
	"MAX_UREFS" VARCHAR2(4000 BYTE), 
	"MIN_UREFS" VARCHAR2(4000 BYTE)
   ) ;
  GRANT SELECT ON "XVIEWMGR"."XV_RES_TYPES_RESTR_DATA" TO "SPMIGUSER" WITH GRANT OPTION;
  GRANT SELECT ON "XVIEWMGR"."XV_RES_TYPES_RESTR_DATA" TO "DECMGR" WITH GRANT OPTION;
