--------------------------------------------------------
--  DDL for Table XV_REV_INV_ITEMS_DATA
--------------------------------------------------------

  CREATE TABLE "SAVEMGR"."XV_REV_INV_ITEMS_DATA" 
   (	"RII_ID" NUMBER(28,0), 
	"RI_ID" NUMBER(12,0), 
	"RID_ID" NUMBER(12,0), 
	"PRIMARY_DATA_UREF" VARCHAR2(4000 BYTE), 
	"SECONDARY_DATA_UREF" VARCHAR2(4000 BYTE), 
	"TERIARY_DATA_UREF" VARCHAR2(4000 BYTE), 
	"ACKNOWLEDGE_REQUIRED" VARCHAR2(4000 BYTE), 
	"ACKNOWLEDGE_DISPLAYED" VARCHAR2(4000 BYTE), 
	"ACKNOWLEDGE_EDIT" VARCHAR2(4000 BYTE), 
	"DISPLAY_SEQ" NUMBER(12,0)
   ) ;

   COMMENT ON TABLE "SAVEMGR"."XV_REV_INV_ITEMS_DATA"  IS 'Save of "XVIEWMGR"."XV_REV_INV_ITEMS_DATA" at 07-JUN-2011 17:26:03';
  GRANT SELECT ON "SAVEMGR"."XV_REV_INV_ITEMS_DATA" TO "XVIEWMGR";
