--------------------------------------------------------
--  DDL for Table XV_REPORT_PRT_COL_DATA
--------------------------------------------------------

  CREATE TABLE "XVIEWMGR"."XV_REPORT_PRT_COL_DATA" 
   (	"DOMAIN" VARCHAR2(40 BYTE), 
	"PART_LABEL" VARCHAR2(2000 BYTE), 
	"COLUMN_NAME" VARCHAR2(2000 BYTE), 
	"COLUMN_TITLE" VARCHAR2(4000 BYTE), 
	"COLUMN_WIDTH" VARCHAR2(4000 BYTE), 
	"COLUMN_STYLE" VARCHAR2(4000 BYTE)
   ) ;
  GRANT SELECT ON "XVIEWMGR"."XV_REPORT_PRT_COL_DATA" TO "REPORTMGR" WITH GRANT OPTION;
