--------------------------------------------------------
--  DDL for Table XV_REVIEW_BAT_DETS_DATA
--------------------------------------------------------

  CREATE TABLE "SAVEMGR"."XV_REVIEW_BAT_DETS_DATA" 
   (	"RBD_ID" NUMBER(12,0), 
	"RB_ID" NUMBER(12,0), 
	"START_DATETIME" DATE, 
	"END_DATETIME" DATE, 
	"STATUS_CONTROL" VARCHAR2(1 BYTE), 
	"CREATED_BY_WUA_ID" NUMBER(12,0), 
	"BATCH_START_DATE" DATE, 
	"BATCH_END_DATE" DATE, 
	"BATCH_STATUS" VARCHAR2(4000 BYTE), 
	"BATCH_STATUS_DISPLAY" VARCHAR2(4000 BYTE), 
	"ADVICE_TYPE" VARCHAR2(4000 BYTE), 
	"REVIEW_TYPE" VARCHAR2(4000 BYTE)
   ) ;

   COMMENT ON TABLE "SAVEMGR"."XV_REVIEW_BAT_DETS_DATA"  IS 'Save of "XVIEWMGR"."XV_REVIEW_BAT_DETS_DATA" at 07-JUN-2011 17:26:02';
  GRANT SELECT ON "SAVEMGR"."XV_REVIEW_BAT_DETS_DATA" TO "XVIEWMGR";
