--------------------------------------------------------
--  DDL for Table XV_RESOURCE_TYPES_DATA
--------------------------------------------------------

  CREATE TABLE "XVIEWMGR"."XV_RESOURCE_TYPES_DATA" 
   (	"RES_TYPE" VARCHAR2(30 BYTE), 
	"RES_TYPE_TITLE" VARCHAR2(1000 BYTE), 
	"RES_TYPE_DESCRIPTION" VARCHAR2(1000 BYTE), 
	"RESOURCE_NAME_EDITABLE" VARCHAR2(5 BYTE), 
	"RESOURCE_NAME_HINT" VARCHAR2(1000 BYTE), 
	"SCOPED_WITHIN" VARCHAR2(20 BYTE), 
	"DAYS_BETWEEN_MAINTAIN" VARCHAR2(4000 BYTE)
   ) ;
  GRANT SELECT ON "XVIEWMGR"."XV_RESOURCE_TYPES_DATA" TO "DECMGR" WITH GRANT OPTION;
