--------------------------------------------------------
--  DDL for Table XV_REPORT_DEFS_DATA
--------------------------------------------------------

  CREATE TABLE "XVIEWMGR"."XV_REPORT_DEFS_DATA" 
   (	"DOMAIN" VARCHAR2(80 BYTE), 
	"TITLE" VARCHAR2(4000 BYTE), 
	"DESCRIPTION" VARCHAR2(4000 BYTE), 
	"CATEGORY_MNEM" VARCHAR2(4000 BYTE), 
	"GLOBAL_DEFINITION" VARCHAR2(5 BYTE), 
	"RUN_NOW" VARCHAR2(4000 BYTE), 
	"RUN_LATER" VARCHAR2(4000 BYTE), 
	"RUN_REPEAT" VARCHAR2(4000 BYTE), 
	"RUN_REPEAT_INTERVAL_MNEMS" VARCHAR2(4000 BYTE), 
	"RUN_REPEAT_INTERVAL_DEFAULT" VARCHAR2(4000 BYTE), 
	"DISPLAY_SCHEDULER" VARCHAR2(10 BYTE), 
	"CONFIG_PARAMETER_DOMAIN" VARCHAR2(50 BYTE), 
	"EMAIL_NOTIFICATION_ENABLED" VARCHAR2(10 BYTE), 
	"EMAIL_NOTIFICATION_MESSAGE" VARCHAR2(4000 BYTE), 
	"EMAIL_DEFAULT_NOTIFY_AUDIENCE" VARCHAR2(4000 BYTE), 
	"EMAIL_NOTIFY_AUDIENCE_QUERY" VARCHAR2(4000 BYTE), 
	"REPORT_PART_ATTACH_LIST" "SYS"."XMLTYPE" , 
	"NOTIFICATION_AUDIENCE_EDITABLE" VARCHAR2(4000 BYTE), 
	"NOTIFICATION_OPTIONAL" VARCHAR2(4000 BYTE), 
	"PUBLISH_ENABLED" VARCHAR2(10 BYTE), 
	"PRIVATE_ENABLED" VARCHAR2(10 BYTE), 
	"PRIVATE_ENFORCED" VARCHAR2(10 BYTE), 
	"DEFAULT_QUEUE" VARCHAR2(30 BYTE), 
	"DEFAULT_RETENTION_DAYS" NUMBER, 
	"RETENTION_PERIOD_EDITABLE" VARCHAR2(10 BYTE), 
	"MAXIMUM_RETENTION_DAYS" NUMBER, 
	"DELETION_WARNING_PERIOD_DAYS" NUMBER, 
	"DELETION_EMAIL_MESSAGE_TEXT" VARCHAR2(4000 BYTE), 
	"PARAMETER_XML" "SYS"."XMLTYPE" , 
	"MAPSET_TEMPLATE_XML" "SYS"."XMLTYPE" , 
	"FILE_TRANSMISSION_TYPE_MNEM" VARCHAR2(50 BYTE), 
	"FILE_TRANSMISSION_TIME_OFFSET" VARCHAR2(4000 BYTE), 
	"VISIBILITY" VARCHAR2(100 BYTE)
   ) ;
  GRANT SELECT ON "XVIEWMGR"."XV_REPORT_DEFS_DATA" TO "REPORTMGR" WITH GRANT OPTION;
