--------------------------------------------------------
--  DDL for Table XV_RES_ADVICE_TYPS_DATA
--------------------------------------------------------

  CREATE TABLE "XVIEWMGR"."XV_RES_ADVICE_TYPS_DATA" 
   (	"ADVICE_TYPE" VARCHAR2(30 BYTE), 
	"REVIEW_TYPE" VARCHAR2(30 BYTE), 
	"REVIEW_TYPE_TITLE" VARCHAR2(4000 BYTE), 
	"RESPONSE_DATA" VARCHAR2(4000 BYTE), 
	"RESPONSE_LONG_KEY" VARCHAR2(4000 BYTE), 
	"RESPONSE_KEY_POSTAMBLE" VARCHAR2(4000 BYTE), 
	"RESPONSE_SHORT_KEY" VARCHAR2(4000 BYTE)
   ) ;
  GRANT SELECT ON "XVIEWMGR"."XV_RES_ADVICE_TYPS_DATA" TO "BPMMGR" WITH GRANT OPTION;
