--------------------------------------------------------
--  DDL for Table XV_RES_ADVICE_TYPS_KEY_350
--------------------------------------------------------

  CREATE TABLE "XVIEWMGR"."XV_RES_ADVICE_TYPS_KEY_350" 
   (	"XVIEW_TRANSACTION_ID" VARCHAR2(100 BYTE), 
	"ADVICE_TYPE" VARCHAR2(30 BYTE), 
	 CONSTRAINT "PK_XV_RES_ADVICE_TYPS_KEY_350" PRIMARY KEY ("XVIEW_TRANSACTION_ID", "ADVICE_TYPE") ENABLE
   ) ORGANIZATION INDEX NOCOMPRESS ;
