--------------------------------------------------------
--  DDL for Table XV_SPIRE_APPLNTS_DATA
--------------------------------------------------------

  CREATE TABLE "XVIEWMGR"."XV_SPIRE_APPLNTS_DATA" 
   (	"SAD_ID" NUMBER, 
	"SA_ID" NUMBER, 
	"STATUS" VARCHAR2(12 BYTE), 
	"STATUS_CONTROL" VARCHAR2(1 BYTE), 
	"REG_STATUS" VARCHAR2(4000 BYTE), 
	"CREATED_DATETIME" DATE, 
	"CREATED_BY_WUA_ID" NUMBER, 
	"CREATED_BY_NAME" VARCHAR2(4000 BYTE), 
	"SUBMITTED_DATETIME" DATE, 
	"SUBMITTED_BY_WUA_ID" NUMBER, 
	"SUBMITTED_BY_NAME" VARCHAR2(4000 BYTE), 
	"APPLICANT_STATUS" VARCHAR2(4000 BYTE), 
	"APPLICANT_TYPE" VARCHAR2(4000 BYTE), 
	"RES_ID" NUMBER, 
	"FTF_ID" NUMBER, 
	"COMPANY_NAME" VARCHAR2(4000 BYTE), 
	"COMPANY_REG_NO" VARCHAR2(4000 BYTE), 
	"COMPANY_VAT_NO" VARCHAR2(4000 BYTE), 
	"COMPANY_EORI_NO" VARCHAR2(4000 BYTE), 
	"COMPANY_ADDRESS" VARCHAR2(4000 BYTE), 
	"DRAFT_PERSON_TITLE" VARCHAR2(20 BYTE), 
	"DRAFT_PERSON_FORENAME" VARCHAR2(4000 BYTE), 
	"DRAFT_PERSON_MIDDLE_INITIALS" VARCHAR2(4000 BYTE), 
	"DRAFT_PERSON_SURNAME" VARCHAR2(4000 BYTE), 
	"OU_ID" NUMBER, 
	"RP_ID" NUMBER, 
	"RESTRICT_APP_VIEW" VARCHAR2(10 BYTE), 
	"RESTRICT_APP_PREPARATION" VARCHAR2(10 BYTE), 
	"RESTRICT_APP_SUBMISSION" VARCHAR2(10 BYTE), 
	"REJECTION_REASON" VARCHAR2(4000 BYTE)
   ) ;
