--------------------------------------------------------
--  DDL for Table XV_SITES_DATA
--------------------------------------------------------

  CREATE TABLE "XVIEWMGR"."XV_SITES_DATA" 
   (	"SITE_ID" NUMBER, 
	"SITE_DETAIL_ID" NUMBER, 
	"STATUS" VARCHAR2(12 BYTE), 
	"STATUS_CONTROL" VARCHAR2(1 BYTE), 
	"SITE_STATUS" VARCHAR2(20 BYTE), 
	"OCCUPANCY_STATUS" VARCHAR2(4000 BYTE), 
	"DIVISION_TITLE" VARCHAR2(4000 BYTE), 
	"TURN_NUMBER" VARCHAR2(4000 BYTE), 
	"SPIRE_APPLICANT_ID" NUMBER, 
	"SPIRE_APPLICANT_UREF" VARCHAR2(4000 BYTE), 
	"STAKEHOLDER_ADDRESS" VARCHAR2(4000 BYTE), 
	"STAKEHOLDER_POSTCODE" VARCHAR2(4000 BYTE), 
	"COMMENTS" VARCHAR2(4000 BYTE), 
	"RES_ID" NUMBER, 
	"RESTRICT_APP_VIEW" VARCHAR2(4000 BYTE), 
	"RESTRICT_APP_PREPARATION" VARCHAR2(4000 BYTE), 
	"RESTRICT_APP_SUBMISSION" VARCHAR2(4000 BYTE)
   ) ;
