--------------------------------------------------------
--  DDL for Table XV_TRANSACTIONS_DATA
--------------------------------------------------------

  CREATE TABLE "XVIEWMGR"."XV_TRANSACTIONS_DATA" 
   (	"T_ID" NUMBER(12,0), 
	"PRIMARY_DATA_UREF" VARCHAR2(20 BYTE), 
	"TRANSACTION_REFERENCE" VARCHAR2(20 BYTE), 
	"TRANSACTION_TITLE" VARCHAR2(50 BYTE), 
	"TRANSACTION_TYPE" VARCHAR2(50 BYTE), 
	"TRANSACTION_SUBTYPE" VARCHAR2(50 BYTE), 
	"CURRENT_STATUS" VARCHAR2(20 BYTE), 
	"ACTION_DESC_TRANSACTION" VARCHAR2(50 BYTE), 
	"EVENT_DATE" DATE, 
	"TRANSACTION_COMMENTS" VARCHAR2(4000 BYTE), 
	"START_DATETIME" DATE, 
	"END_DATETIME" DATE
   ) ;
  GRANT SELECT ON "XVIEWMGR"."XV_TRANSACTIONS_DATA" TO "BPMMGR" WITH GRANT OPTION;
