--------------------------------------------------------
--  DDL for Table XV_TALLY_TYPE_CQRY_KEY_431
--------------------------------------------------------

  CREATE TABLE "XVIEWMGR"."XV_TALLY_TYPE_CQRY_KEY_431" 
   (	"XVIEW_TRANSACTION_ID" VARCHAR2(100 BYTE), 
	"TALLY_TYPE" VARCHAR2(30 BYTE), 
	 CONSTRAINT "PK_XV_TALLY_TYPE_CQRY_KEY_431" PRIMARY KEY ("XVIEW_TRANSACTION_ID", "TALLY_TYPE") ENABLE
   ) ORGANIZATION INDEX NOCOMPRESS ;
