--------------------------------------------------------
--  DDL for Table XV_TPL_CLAUSE_DTLS_DATA
--------------------------------------------------------

  CREATE TABLE "XVIEWMGR"."XV_TPL_CLAUSE_DTLS_DATA" 
   (	"TCD_ID" NUMBER(12,0), 
	"TC_ID" NUMBER(12,0), 
	"CLAUSE_TYPE_ID" VARCHAR2(30 BYTE), 
	"SHORT_CODE" VARCHAR2(400 BYTE), 
	"TITLE" VARCHAR2(4000 BYTE), 
	"DEFAULT_SEVERITY" VARCHAR2(400 BYTE), 
	"CLASS" VARCHAR2(400 BYTE), 
	"DEFAULT_REASON_CODE" VARCHAR2(50 BYTE), 
	"TEMPLATE_CLAUSE_TEXT" "XVIEWMGR"."XMLTYPE", 
	"DISPLAY_ORDER" NUMBER(12,0), 
	"DELETE_FLAG" VARCHAR2(10 BYTE), 
	"EDIT_FLAG" VARCHAR2(10 BYTE), 
	"CLEAR_FLAG" VARCHAR2(10 BYTE), 
	"UPDATED_BY_WUA_ID" NUMBER(12,0), 
	"UPDATED_DATETIME" DATE, 
	"STATUS" VARCHAR2(12 BYTE), 
	"STATUS_CONTROL" VARCHAR2(1 BYTE), 
	"START_DATETIME" DATE, 
	"END_DATETIME" DATE
   ) ;
