--------------------------------------------------------
--  DDL for Table XV_WUA_PREFS_KEY_395
--------------------------------------------------------

  CREATE TABLE "XVIEWMGR"."XV_WUA_PREFS_KEY_395" 
   (	"XVIEW_TRANSACTION_ID" VARCHAR2(100 BYTE), 
	"CATEGORY_NAME" VARCHAR2(50 BYTE), 
	 CONSTRAINT "PK_XV_WUA_PREFS_KEY_395" PRIMARY KEY ("XVIEW_TRANSACTION_ID", "CATEGORY_NAME") ENABLE
   ) ORGANIZATION INDEX NOCOMPRESS ;
