--------------------------------------------------------
--  DDL for Table XV_WP_SECURITY_DATA
--------------------------------------------------------

  CREATE TABLE "XVIEWMGR"."XV_WP_SECURITY_DATA" 
   (	"CATEGORY_NAME" VARCHAR2(50 BYTE), 
	"RESOURCE_TYPE" VARCHAR2(30 BYTE), 
	"RESOURCE_ROLE_LIKE" VARCHAR2(30 BYTE), 
	"SYSTEM_PRIV" VARCHAR2(60 BYTE)
   ) ;
  GRANT SELECT ON "XVIEWMGR"."XV_WP_SECURITY_DATA" TO "SECUREMGR" WITH GRANT OPTION;
