--------------------------------------------------------
--  DDL for Table XV_WUA_PREFS_DATA
--------------------------------------------------------

  CREATE TABLE "XVIEWMGR"."XV_WUA_PREFS_DATA" 
   (	"CATEGORY_NAME" VARCHAR2(50 BYTE), 
	"CATEGORY_PROMPT" VARCHAR2(200 BYTE), 
	"CATEGORY_DISPLAY_ORDER" NUMBER, 
	"PREFERENCE_NAME" VARCHAR2(50 BYTE), 
	"PREFERENCE_PROMPT" VARCHAR2(200 BYTE), 
	"PREFERENCE_HINT" VARCHAR2(300 BYTE), 
	"PREFERENCE_DISPLAY_ORDER" NUMBER, 
	"DATA_TYPE" VARCHAR2(50 BYTE), 
	"WIDGET_TYPE" VARCHAR2(50 BYTE), 
	"MAPSET_NAME" VARCHAR2(50 BYTE), 
	"MANDATORY" VARCHAR2(5 BYTE), 
	"DEFAULT_VALUE" VARCHAR2(1000 BYTE)
   ) ;
