--------------------------------------------------------
--  DDL for Table XV_WP_SECURITY_KEY_400
--------------------------------------------------------

  CREATE TABLE "XVIEWMGR"."XV_WP_SECURITY_KEY_400" 
   (	"XVIEW_TRANSACTION_ID" VARCHAR2(100 BYTE), 
	"CATEGORY_NAME" VARCHAR2(50 BYTE), 
	 CONSTRAINT "PK_XV_WP_SECURITY_KEY_400" PRIMARY KEY ("XVIEW_TRANSACTION_ID", "CATEGORY_NAME") ENABLE
   ) ORGANIZATION INDEX NOCOMPRESS ;
