--------------------------------------------------------
--  DDL for Table XVIEW_FOREIGN_KEY_CONSTRAINTS
--------------------------------------------------------

  CREATE TABLE "XVIEWMGR"."XVIEW_FOREIGN_KEY_CONSTRAINTS" 
   (	"XVIEW_OWNER" VARCHAR2(30 BYTE), 
	"XVIEW_NAME" VARCHAR2(30 BYTE), 
	"SEQ" NUMBER(3,0), 
	"STATUS" VARCHAR2(12 BYTE), 
	"CONSTRAINED_TABLE_OWNER" VARCHAR2(30 BYTE), 
	"CONSTRAINED_TABLE_NAME" VARCHAR2(30 BYTE), 
	"CONSTRAINED_TABLE_COLUMN_LIST" VARCHAR2(4000 BYTE), 
	"REFERENCED_TABLE_OWNER" VARCHAR2(30 BYTE), 
	"REFERENCED_TABLE_NAME" VARCHAR2(30 BYTE), 
	"REFERENCED_TABLE_COLUMN_LIST" VARCHAR2(4000 BYTE), 
	"DFR" VARCHAR2(1 BYTE)
   ) ;
