--------------------------------------------------------
--  DDL for View ELC_EXPORTER_VIEW
--------------------------------------------------------

  CREATE OR REPLACE FORCE EDITIONABLE VIEW "WARP_OWNER"."ELC_EXPORTER_VIEW" ("PARTY_ID", "FULL_NAME", "ADDRESS1", "ADDRESS2", "ADDRESS3", "ADDRESS4", "SURNAME", "CONT_ADDRESS1", "CONT_ADDRESS2", "CONT_ADDRESS3", "CONT_ADDRESS4", "TITLE", "INITIALS", "TELEPHONE", "JOB_TITLE", "INACTIVE_FROM_DATE", "MAIL_STOP", "CONT_INDICATOR", "WATCH_LIST", "POSTCODE", "VAT_NO", "REGISTRATION_DATE", "FAX_NO", "EMAIL_ADDRESS") AS 
  SELECT
  E1.PARTY_ID,
  E1.FULL_NAME,
  E1.ADDRESS1,
  E1.ADDRESS2,
  E1.ADDRESS3,
  E1.ADDRESS4,
  E1.SURNAME,
  E1.CONT_ADDRESS1,
  E1.CONT_ADDRESS2,
  E1.CONT_ADDRESS3,
  E1.CONT_ADDRESS4,
  E1.TITLE,
  E1.INITIALS,
  E1.TELEPHONE,
  E1.JOB_TITLE,
  E1.INACTIVE_FROM_DATE,
  E1.MAIL_STOP,
  E1.CONT_INDICATOR,
  E1.WATCH_LIST,
  E1.POSTCODE,
  E1.VAT_NO,
  E1.REGISTRATION_DATE,
  E1.FAX_NO,
  E1.EMAIL_ADDRESS
FROM WARP_OWNER.ELC_PARTY E1
WHERE
  (E1.TYPE ='EXP')
;
