--------------------------------------------------------
--  DDL for View ENTITY_SEARCH
--------------------------------------------------------

  CREATE OR REPLACE FORCE EDITIONABLE VIEW "WARP_OWNER"."ENTITY_SEARCH" ("TYPE", "REFERENCE", "NAME", "ADD1", "ADD2", "ADD3", "ADD4", "ADD5", "POSTCODE", "CONTACT", "SEARCH_DATE", "GOODS", "COMMENTS", "RATING", "END_USER", "COUNTRY") AS 
  SELECT 'O',
 TO_CHAR(ID),
 NAME,
 ADDRESS1,
 ADDRESS2,
 ADDRESS3,
 COUNTY,
 COUNTRY,
 POSTCODE,
 CONTACT_TITLE||' '||CONTACT_SURNAME,
 DATE_OF_REGISTRATION,
 NULL,
 COMMENTS,
 NULL,
 NULL,
 NULL
FROM OGEL_EXPORTER E,
OGEL_REGISTERED_EXPORTER R
WHERE ID = COMPANY_ID
UNION
SELECT 'S',
 'Grp:'||CASE_GROUP_CODE||' Ref:'||TO_CHAR(REFERENCE_NUMBER)||' Yr:'||TO_CHAR(YEAR),
 APPLICANT_COMPANY_NAME                 ,
 APPLICANT_CONTACT_ADDRESS_1            ,
 APPLICANT_CONTACT_ADDRESS_2            ,
 APPLICANT_CONTACT_ADDRESS_3            ,
 APPLICANT_CONTACT_ADDRESS_4            ,
 NULL,
 APPLICANT_POSTCODE                     ,
 APPLICANT_CONTACT_TITLE||' '||APPLICANT_CONTACT_NAME,
 DATE_RECEIVED                          ,
 DESCRIPTION                  ,
 TU_OTHER_COMMENTS,
 NULL,
 NULL,
 COUNTRY_CODE
FROM san_case
UNION
SELECT 'T',
 'Case:'||TO_CHAR(CASE_NO)||' Week:'||TO_CHAR(WEEK_NO)||' Yr:'||TO_CHAR(YEAR),
 EXPORTER_COMPANY_NAME          ,
 EXPORTER_COMPANY_ADDRESS,
 NULL,NULL,NULL,NULL,NULL,NULL,
 ENQUIRY_DATE,
 NULL,
 COMMENTS,
 NULL,NULL,
 COUNTRY_CODE
 FROM tel_enq t, tel_exp e
WHERE e.EXPORTER_RSN = t.EXPORTER_RSN
UNION
SELECT 'R',
'Prefix:'||PREFIX_NAME||' Theme:'||THEME||' File:'||TO_CHAR(FILE_NUMBER)||' Part:'||PART_NUMBER||' Sub:'||SUB_NO||' Yr:'||TO_CHAR(YEAR),
FILE_TITLE,
NULL,NULL,NULL,NULL,NULL,NULL,NULL,
CREATE_DATE,
NULL,
comments,
STATUS,
NULL,NULL
FROM reg_file_list
;
