--------------------------------------------------------
--  DDL for View ENV_MAPSETS
--------------------------------------------------------

  CREATE OR REPLACE FORCE EDITIONABLE VIEW "ENVMGR"."ENV_MAPSETS" ("DOMAIN", "DATA", "DESCRIPTION") AS 
  (
  SELECT
    domain
  , (data).getClobVal() "DATA"
  , description
  FROM envmgr.env_mapsets_xml
) 
;
  GRANT SELECT ON "ENVMGR"."ENV_MAPSETS" TO "SPIREMGR";
  GRANT SELECT ON "ENVMGR"."ENV_MAPSETS" TO "BPMMGR";
  GRANT UPDATE ON "ENVMGR"."ENV_MAPSETS" TO "APPENV";
  GRANT SELECT ON "ENVMGR"."ENV_MAPSETS" TO "APPENV";
  GRANT INSERT ON "ENVMGR"."ENV_MAPSETS" TO "APPENV";
  GRANT DELETE ON "ENVMGR"."ENV_MAPSETS" TO "APPENV";
  GRANT UPDATE ON "ENVMGR"."ENV_MAPSETS" TO "APPBPM";
  GRANT SELECT ON "ENVMGR"."ENV_MAPSETS" TO "APPBPM";
  GRANT INSERT ON "ENVMGR"."ENV_MAPSETS" TO "APPBPM";
  GRANT DELETE ON "ENVMGR"."ENV_MAPSETS" TO "APPBPM";
