--------------------------------------------------------
--  DDL for View OGEL_DATE_REGISTRATION
--------------------------------------------------------

  CREATE OR REPLACE FORCE EDITIONABLE VIEW "WARP_OWNER"."OGEL_DATE_REGISTRATION" ("ID", "NAME", "CONTACT_INITIALS", "CONTACT_SURNAME", "CONTACT_JOB_TITLE", "CONTACT_TITLE", "ADDRESS1", "ADDRESS2", "ADDRESS3", "COUNTY", "POSTCODE", "SHORT_NAME", "DATE_OF_REGISTRATION") AS 
  SELECT
  E.ID,
  E.NAME,
  E.CONTACT_INITIALS,
  E.CONTACT_SURNAME,
  E.CONTACT_JOB_TITLE,
  E.CONTACT_TITLE,
  E.ADDRESS1,
  E.ADDRESS2,
  E.ADDRESS3,
  E.COUNTY,
  E.POSTCODE,
  O.SHORT_NAME,
  R.DATE_OF_REGISTRATION
FROM
  OGEL_OGEL O,
  OGEL_EXPORTER E,
  OGEL_REGISTERED_EXPORTER R
WHERE
  R.COMPANY_ID=E.ID
  AND  O.SHORT_NAME=R.OGEL_SHORTNAME
  ORDER BY e.ID, r.date_of_registration
  --AND  (E.ID  >=  @variable('ID Ref ?'))
;
