--------------------------------------------------------
--  DDL for View OITCL
--------------------------------------------------------

  CREATE OR REPLACE FORCE EDITIONABLE VIEW "WARP_OWNER"."OITCL" ("ID", "CASE_REF", "USER_ID", "APP_TYPE", "TYPE", "YEAR", "COMPANY", "CASE_ENTERED", "STATUS", "SPECIAL_TO_FLAG", "TU_ENTRIES", "TO_TARGET", "TASU_TARGET", "ALL_TARGET", "END_DATE", "PARTY", "OGD_FLAG", "CURRENTLY_WITH_OGD", "RESET_TARGET", "ALL_TARGET_PASS", "TO_TARGET_PASS", "TO_ALLOCATION_MADE", "LEAD_TO", "OVER_UNDER_TARGET_DAYS", "OVER_UNDER_TARGET_HOURS", "OVER_UNDER_TARGET_MINUTES", "TASU_TARGET_PASS") AS 
  select "ID","CASE_REF","USER_ID","APP_TYPE","TYPE","YEAR","COMPANY","CASE_ENTERED","STATUS","SPECIAL_TO_FLAG","TU_ENTRIES","TO_TARGET","TASU_TARGET","ALL_TARGET","END_DATE","PARTY","OGD_FLAG","CURRENTLY_WITH_OGD","RESET_TARGET","ALL_TARGET_PASS","TO_TARGET_PASS","TO_ALLOCATION_MADE","LEAD_TO","OVER_UNDER_TARGET_DAYS","OVER_UNDER_TARGET_HOURS","OVER_UNDER_TARGET_MINUTES","TASU_TARGET_PASS"
from case_work
where app_type = 'Oitcl'
;
