--------------------------------------------------------
--  DDL for View SPIRE_APPLICANTS_OU_MERGE_CURR
--------------------------------------------------------

  CREATE OR REPLACE FORCE EDITIONABLE VIEW "SPIREMGR"."SPIRE_APPLICANTS_OU_MERGE_CURR" ("SA_ID", "SAD_ID", "STATUS", "STATUS_CONTROL", "REG_STATUS", "CREATED_DATETIME", "CREATED_BY_WUA_ID", "CREATED_BY_NAME", "SUBMITTED_DATETIME", "SUBMITTED_BY_WUA_ID", "SUBMITTED_BY_NAME", "APPLICANT_STATUS", "APPLICANT_TYPE", "RES_ID", "FTF_ID", "COMPANY_NAME", "COMPANY_REG_NO", "COMPANY_ADDRESS", "ORIGIN_COUNTRY_CODE", "COMPANY_VAT_NO", "COMPANY_EORI_NO", "DRAFT_PERSON_TITLE", "DRAFT_PERSON_FORENAME", "DRAFT_PERSON_MIDDLE_INITIALS", "DRAFT_PERSON_SURNAME", "OU_ID", "RP_ID", "RESTRICT_APP_VIEW", "RESTRICT_APP_PREPARATION", "RESTRICT_APP_SUBMISSION", "REJECTION_REASON") AS 
  (
  SELECT "SA_ID","SAD_ID","STATUS","STATUS_CONTROL","REG_STATUS","CREATED_DATETIME","CREATED_BY_WUA_ID","CREATED_BY_NAME","SUBMITTED_DATETIME","SUBMITTED_BY_WUA_ID","SUBMITTED_BY_NAME","APPLICANT_STATUS","APPLICANT_TYPE","RES_ID","FTF_ID","COMPANY_NAME","COMPANY_REG_NO","COMPANY_ADDRESS","ORIGIN_COUNTRY_CODE","COMPANY_VAT_NO","COMPANY_EORI_NO","DRAFT_PERSON_TITLE","DRAFT_PERSON_FORENAME","DRAFT_PERSON_MIDDLE_INITIALS","DRAFT_PERSON_SURNAME","OU_ID","RP_ID","RESTRICT_APP_VIEW","RESTRICT_APP_PREPARATION","RESTRICT_APP_SUBMISSION","REJECTION_REASON"
  FROM spiremgr.spire_applicants_ou_merge m
  WHERE (
    m.status_control = 'C' 
    OR ( 
      m.status_control = 'D' AND NOT EXISTS (
        SELECT 1 
        FROM spiremgr.spire_applicant_details a2
        WHERE a2.sa_id = m.sa_id
        AND a2.status_control = 'C'
      )
    )
  )
  AND m.reg_status IN ('REGISTERED','SUBMITTED','ALLOCATED','AUTHORISING','UNREGISTERED')
)

;
  GRANT SELECT ON "SPIREMGR"."SPIRE_APPLICANTS_OU_MERGE_CURR" TO "PVEXMGR";
  GRANT SELECT ON "SPIREMGR"."SPIRE_APPLICANTS_OU_MERGE_CURR" TO "BPMMGR";
  GRANT SELECT ON "SPIREMGR"."SPIRE_APPLICANTS_OU_MERGE_CURR" TO "APPENV";
  GRANT SELECT ON "SPIREMGR"."SPIRE_APPLICANTS_OU_MERGE_CURR" TO "BISAPIMGR";
