--------------------------------------------------------
--  DDL for View WEB_USER_ACCOUNTS
--------------------------------------------------------

  CREATE OR REPLACE FORCE EDITIONABLE VIEW "PORTALMGR"."WEB_USER_ACCOUNTS" ("ID", "WO_ID", "TITLE", "FORENAME", "MIDDLE_INITIALS", "SURNAME", "JOB_TITLE", "TELEPHONE_NO", "MOBILE_NO", "FAX_NO", "PRIMARY_EMAIL_ADDRESS", "ADDITIONAL_EMAIL_ADDRESS", "ADDR_ID", "LOCATION_WITHIN_ADDRESS", "LOGIN_ID", "ENCRYPTED_PASSWORD", "PASSWORD_EXPIRY_DATE", "ACCOUNT_TYPE", "LAST_LOGIN_DATE_TIME", "LAST_LOGOUT_DATE_TIME", "LOGIN_TRY_COUNT", "MAINTAINABLE_BY", "ACCOUNT_CANCELLED_DATE", "ACCOUNT_CANCELLED_BY", "ACCOUNT_SUSPENDED_DATE", "ACCOUNT_SUSPENDED_BY", "LAST_DML_DATE", "LAST_DML_BY", "DTI_STAFF_FK", "ACCOUNT_STATUS", "ACCOUNT_STATUS_BY", "ACCOUNT_STATUS_DATE", "RESOURCE_PERSON_ID", "RESOURCE_PERSON_PRIMARY_FLAG", "EMAIL_AS_LOGIN_ID_FLAG", "PROTECT_FILES", "WORG_ID", "WORG_SHORT_NAME", "WORG_NAME", "WOT_NAME", "PASSWORD_DISPOSITION", "FULL_NAME", "ORGANISATION_NAME") AS 
  SELECT "ID","WO_ID","TITLE","FORENAME","MIDDLE_INITIALS","SURNAME","JOB_TITLE","TELEPHONE_NO","MOBILE_NO","FAX_NO","PRIMARY_EMAIL_ADDRESS","ADDITIONAL_EMAIL_ADDRESS","ADDR_ID","LOCATION_WITHIN_ADDRESS","LOGIN_ID","ENCRYPTED_PASSWORD","PASSWORD_EXPIRY_DATE","ACCOUNT_TYPE","LAST_LOGIN_DATE_TIME","LAST_LOGOUT_DATE_TIME","LOGIN_TRY_COUNT","MAINTAINABLE_BY","ACCOUNT_CANCELLED_DATE","ACCOUNT_CANCELLED_BY","ACCOUNT_SUSPENDED_DATE","ACCOUNT_SUSPENDED_BY","LAST_DML_DATE","LAST_DML_BY","DTI_STAFF_FK","ACCOUNT_STATUS","ACCOUNT_STATUS_BY","ACCOUNT_STATUS_DATE","RESOURCE_PERSON_ID","RESOURCE_PERSON_PRIMARY_FLAG","EMAIL_AS_LOGIN_ID_FLAG","PROTECT_FILES","WORG_ID","WORG_SHORT_NAME","WORG_NAME","WOT_NAME","PASSWORD_DISPOSITION","FULL_NAME","ORGANISATION_NAME"
FROM securemgr.WEB_USER_ACCOUNTS

;
  GRANT SELECT ON "PORTALMGR"."WEB_USER_ACCOUNTS" TO "SECUREMGR";
  GRANT SELECT ON "PORTALMGR"."WEB_USER_ACCOUNTS" TO "SDBMGR";
  GRANT SELECT ON "PORTALMGR"."WEB_USER_ACCOUNTS" TO "SPMIGUSER" WITH GRANT OPTION;
  GRANT SELECT ON "PORTALMGR"."WEB_USER_ACCOUNTS" TO "SPIREMGR";
  GRANT SELECT ON "PORTALMGR"."WEB_USER_ACCOUNTS" TO "BPMMGR";
  GRANT SELECT ON "PORTALMGR"."WEB_USER_ACCOUNTS" TO "FOXMGR";
  GRANT SELECT ON "PORTALMGR"."WEB_USER_ACCOUNTS" TO "ENVMGR" WITH GRANT OPTION;
  GRANT SELECT ON "PORTALMGR"."WEB_USER_ACCOUNTS" TO "DECMGR" WITH GRANT OPTION;
  GRANT SELECT ON "PORTALMGR"."WEB_USER_ACCOUNTS" TO "APPENV";
  GRANT SELECT ON "PORTALMGR"."WEB_USER_ACCOUNTS" TO "APPBPM";
  GRANT SELECT ON "PORTALMGR"."WEB_USER_ACCOUNTS" TO "SURVEYMGR";
