--------------------------------------------------------
--  DDL for View XVIEW_BPD_ASSIGNMENTS
--------------------------------------------------------

  CREATE OR REPLACE FORCE EDITIONABLE VIEW "BPMMGR"."XVIEW_BPD_ASSIGNMENTS" ("BP_ID", "PROCESS_SHORT_NAME", "ASSIGNMENT_TYPE", "ASSIGNMENT", "ASSIGNMENT_TITLE", "DELEGATION", "STAGE_LABEL", "SUBROUTINE_SHORT_NAME", "CONDITION_XML") AS 
  SELECT "BP_ID","PROCESS_SHORT_NAME","ASSIGNMENT_TYPE","ASSIGNMENT","ASSIGNMENT_TITLE","DELEGATION","STAGE_LABEL","SUBROUTINE_SHORT_NAME","CONDITION_XML"
FROM XVIEWMGR.XVIEW_BPD_ASSIGNMENTS
;
  GRANT SELECT ON "BPMMGR"."XVIEW_BPD_ASSIGNMENTS" TO "APPENV";
