--------------------------------------------------------
--  DDL for View XVIEW_BPD_TALLIES
--------------------------------------------------------

  CREATE OR REPLACE FORCE EDITIONABLE VIEW "BPMMGR"."XVIEW_BPD_TALLIES" ("BPD_ID", "PROCESS_SHORT_NAME", "TALLY", "INTERNAL_TALLY", "BPD_TALLY_TYPE", "TALLY_TYPE_DEFINITION", "ROOT_TALLY", "SWITCH", "STAGE_LABEL", "SUBROUTINE_SHORT_NAME", "QUERY") AS 
  SELECT "BPD_ID","PROCESS_SHORT_NAME","TALLY","INTERNAL_TALLY","BPD_TALLY_TYPE","TALLY_TYPE_DEFINITION","ROOT_TALLY","SWITCH","STAGE_LABEL","SUBROUTINE_SHORT_NAME","QUERY"
FROM XVIEWMGR.XVIEW_BPD_TALLIES
;
