--------------------------------------------------------
--  DDL for View XVIEW_BPD_OPERATIONS
--------------------------------------------------------

  CREATE OR REPLACE FORCE EDITIONABLE VIEW "BPMMGR"."XVIEW_BPD_OPERATIONS" ("BPD_ID", "BP_ID", "BPD_FULL_NAME", "EVENT_LABEL", "OPERATION_TYPE", "OPERATION_NAME", "OPERATION_XML") AS 
  SELECT "BPD_ID","BP_ID","BPD_FULL_NAME","EVENT_LABEL","OPERATION_TYPE","OPERATION_NAME","OPERATION_XML"
FROM XVIEWMGR.XVIEW_BPD_OPERATIONS
;
