--------------------------------------------------------
--  DDL for View XVIEW_PAGE_CONTENT_DETAILS
--------------------------------------------------------

  CREATE OR REPLACE FORCE EDITIONABLE VIEW "DECMGR"."XVIEW_PAGE_CONTENT_DETAILS" ("PCD_ID", "PC_ID", "PAGE_CONTENT_TYPE", "TITLE", "PAGE_CONTENT_TEXT", "UPDATED_BY_WUA_ID", "UPDATED_DATETIME", "SELECTED_FLAG", "STATUS", "STATUS_CONTROL") AS 
  SELECT "PCD_ID","PC_ID","PAGE_CONTENT_TYPE","TITLE","PAGE_CONTENT_TEXT","UPDATED_BY_WUA_ID","UPDATED_DATETIME","SELECTED_FLAG","STATUS","STATUS_CONTROL"
FROM XVIEWMGR.XVIEW_PAGE_CONTENT_DETAILS
;
