--------------------------------------------------------
--  DDL for View XVIEW_COUNTRIES
--------------------------------------------------------

  CREATE OR REPLACE FORCE EDITIONABLE VIEW "BPMMGR"."XVIEW_COUNTRIES" ("COUNTRY_DETAIL_ID", "COUNTRY_ID", "COUNTRY_SET_ID", "END_DATETIME", "COUNTRY_NAME", "COUNTRY_STATUS", "COUNTRY_TYPE") AS 
  SELECT "COUNTRY_DETAIL_ID","COUNTRY_ID","COUNTRY_SET_ID","END_DATETIME","COUNTRY_NAME","COUNTRY_STATUS","COUNTRY_TYPE"
FROM XVIEWMGR.XVIEW_COUNTRIES
;
  GRANT SELECT ON "BPMMGR"."XVIEW_COUNTRIES" TO "BISAPIMGR";
  GRANT SELECT ON "BPMMGR"."XVIEW_COUNTRIES" TO "SDBMGR" WITH GRANT OPTION;
  GRANT SELECT ON "BPMMGR"."XVIEW_COUNTRIES" TO "SPMIGUSER";
  GRANT SELECT ON "BPMMGR"."XVIEW_COUNTRIES" TO "SPIREMGR";
  GRANT SELECT ON "BPMMGR"."XVIEW_COUNTRIES" TO "DECMGR";
  GRANT SELECT ON "BPMMGR"."XVIEW_COUNTRIES" TO "APPENV";
