--------------------------------------------------------
--  DDL for View XVIEW_BPD_ACTION_SET_ASSIGNS
--------------------------------------------------------

  CREATE OR REPLACE FORCE EDITIONABLE VIEW "BPMMGR"."XVIEW_BPD_ACTION_SET_ASSIGNS" ("BPD_ID", "ACTION_SET_MNEM", "ASSIGNMENT", "ASSIGNMENT_GROUP", "WORKBASKET", "STAGE_LABEL") AS 
  SELECT "BPD_ID","ACTION_SET_MNEM","ASSIGNMENT","ASSIGNMENT_GROUP","WORKBASKET","STAGE_LABEL"
FROM XVIEWMGR.XVIEW_BPD_ACTION_SET_ASSIGNS
;
