--------------------------------------------------------
--  DDL for View XVIEW_INTENTION_ACTION_AUDIT
--------------------------------------------------------

  CREATE OR REPLACE FORCE EDITIONABLE VIEW "BPMMGR"."XVIEW_INTENTION_ACTION_AUDIT" ("ID_ID", "IN_ID", "ACTION_NAME", "WUA_ID", "WUA_FULL_NAME", "ACTION_DATETIME") AS 
  SELECT "ID_ID","IN_ID","ACTION_NAME","WUA_ID","WUA_FULL_NAME","ACTION_DATETIME"
FROM XVIEWMGR.XVIEW_INTENTION_ACTION_AUDIT
;
  GRANT SELECT ON "BPMMGR"."XVIEW_INTENTION_ACTION_AUDIT" TO "APPENV";
  GRANT SELECT ON "BPMMGR"."XVIEW_INTENTION_ACTION_AUDIT" TO "SPIREMGR";
