--------------------------------------------------------
--  DDL for View XVIEW_RESOURCE_TYPE_PRIVS
--------------------------------------------------------

  CREATE OR REPLACE FORCE EDITIONABLE VIEW "DECMGR"."XVIEW_RESOURCE_TYPE_PRIVS" ("RES_TYPE", "ROLE_NAME", "DEFAULT_SYSTEM_PRIV") AS 
  SELECT "RES_TYPE","ROLE_NAME","DEFAULT_SYSTEM_PRIV"
FROM XVIEWMGR.XVIEW_RESOURCE_TYPE_PRIVS
;
  GRANT SELECT ON "DECMGR"."XVIEW_RESOURCE_TYPE_PRIVS" TO "BISAPIMGR";
  GRANT SELECT ON "DECMGR"."XVIEW_RESOURCE_TYPE_PRIVS" TO "SECUREMGR";
  GRANT SELECT ON "DECMGR"."XVIEW_RESOURCE_TYPE_PRIVS" TO "FOXMGR";
  GRANT SELECT ON "DECMGR"."XVIEW_RESOURCE_TYPE_PRIVS" TO "BPMMGR";
  GRANT SELECT ON "DECMGR"."XVIEW_RESOURCE_TYPE_PRIVS" TO "APPENV";
