--------------------------------------------------------
--  DDL for View XVIEW_REVIEW_BATCH_DETAILS
--------------------------------------------------------

  CREATE OR REPLACE FORCE EDITIONABLE VIEW "BPMMGR"."XVIEW_REVIEW_BATCH_DETAILS" ("RBD_ID", "RB_ID", "START_DATETIME", "END_DATETIME", "STATUS_CONTROL", "CREATED_BY_WUA_ID", "BATCH_START_DATE", "BATCH_END_DATE", "BATCH_STATUS", "BATCH_STATUS_DISPLAY", "ADVICE_TYPE", "REVIEW_TYPE") AS 
  SELECT "RBD_ID","RB_ID","START_DATETIME","END_DATETIME","STATUS_CONTROL","CREATED_BY_WUA_ID","BATCH_START_DATE","BATCH_END_DATE","BATCH_STATUS","BATCH_STATUS_DISPLAY","ADVICE_TYPE","REVIEW_TYPE"
FROM XVIEWMGR.XVIEW_REVIEW_BATCH_DETAILS
;
  GRANT SELECT ON "BPMMGR"."XVIEW_REVIEW_BATCH_DETAILS" TO "APPENV";
