--------------------------------------------------------
--  DDL for View XVIEW_RESOURCE_PEOPLE_TELS
--------------------------------------------------------

  CREATE OR REPLACE FORCE EDITIONABLE VIEW "DECMGR"."XVIEW_RESOURCE_PEOPLE_TELS" ("RPD_ID", "RP_ID", "STATUS_CONTROL", "STATUS", "TELEPHONE_HASH_CODE", "TEL_TYPE", "TEL_COMMENT") AS 
  SELECT "RPD_ID","RP_ID","STATUS_CONTROL","STATUS","TELEPHONE_HASH_CODE","TEL_TYPE","TEL_COMMENT"
FROM XVIEWMGR.XVIEW_RESOURCE_PEOPLE_TELS
;
