--------------------------------------------------------
--  DDL for View XVIEW_BPD_DELEGATIONS
--------------------------------------------------------

  CREATE OR REPLACE FORCE EDITIONABLE VIEW "BPMMGR"."XVIEW_BPD_DELEGATIONS" ("BP_ID", "DELEGATION", "DELEGATION_TYPE", "ALLOW_REASSIGN", "ALLOW_UNASSIGN", "ALLOW_STEAL", "DELEGATION_XML") AS 
  SELECT "BP_ID","DELEGATION","DELEGATION_TYPE","ALLOW_REASSIGN","ALLOW_UNASSIGN","ALLOW_STEAL","DELEGATION_XML"
FROM XVIEWMGR.XVIEW_BPD_DELEGATIONS
;
