--------------------------------------------------------
--  DDL for View XVIEW_ELA_STAKEHOLDERS
--------------------------------------------------------

  CREATE OR REPLACE FORCE EDITIONABLE VIEW "SPIREMGR"."XVIEW_ELA_STAKEHOLDERS" ("ELA_DETAIL_ID", "SH_ID", "ROLE_TYPE", "COMPOSITION", "ROLE_DESCRIPTION", "PD_TITLE", "PD_FORENAME", "PD_MIDDLE_INITIALS", "PD_SURNAME", "PD_JOB_DESCRIPTION", "ORG_ID", "ORG_NAME", "ORG_VAT_NUMBER", "ORG_REGISTERED_NUMBER", "ORG_REGISTERED_ADDRESS_ID", "ORG_REGISTERED_ADDRESS", "ORG_OCD_COUNTRY_OF_ORIGIN", "ORG_OCD_PARENT_REG_NAME", "ORG_OCD_PRNT_REG_COMP_REF", "ORG_OCD_PRNT_REG_COMMENT", "ORG_COMP_DET_ACC_COMMENTS", "ADDRESS", "POSTCODE", "COUNTRY", "NATURE_OF_BUSINESS", "RELATIONSHIP_DESCRIPTION", "MISC_TEXT", "FORMATTED_NAME", "END_USER_FLAG", "CONSIGNEE_FLAG", "XML_DATA", "THIRD_PARTY_FLAG", "OUTCOME_DECISION", "OUTCOME_STATUS", "APPROVAL_COMMENT", "APPROVAL_FLAG", "DC_ID", "IS_ID", "FIRST_NOTIFICATION_DATE", "LAST_NOTIFICATION_DATE", "RECIPIENT_END_USER_TYPE", "REVOKE_SUSPEND_ACTION") AS 
  SELECT "ELA_DETAIL_ID","SH_ID","ROLE_TYPE","COMPOSITION","ROLE_DESCRIPTION","PD_TITLE","PD_FORENAME","PD_MIDDLE_INITIALS","PD_SURNAME","PD_JOB_DESCRIPTION","ORG_ID","ORG_NAME","ORG_VAT_NUMBER","ORG_REGISTERED_NUMBER","ORG_REGISTERED_ADDRESS_ID","ORG_REGISTERED_ADDRESS","ORG_OCD_COUNTRY_OF_ORIGIN","ORG_OCD_PARENT_REG_NAME","ORG_OCD_PRNT_REG_COMP_REF","ORG_OCD_PRNT_REG_COMMENT","ORG_COMP_DET_ACC_COMMENTS","ADDRESS","POSTCODE","COUNTRY","NATURE_OF_BUSINESS","RELATIONSHIP_DESCRIPTION","MISC_TEXT","FORMATTED_NAME","END_USER_FLAG","CONSIGNEE_FLAG","XML_DATA","THIRD_PARTY_FLAG","OUTCOME_DECISION","OUTCOME_STATUS","APPROVAL_COMMENT","APPROVAL_FLAG","DC_ID","IS_ID","FIRST_NOTIFICATION_DATE","LAST_NOTIFICATION_DATE","RECIPIENT_END_USER_TYPE","REVOKE_SUSPEND_ACTION"
FROM XVIEWMGR.XVIEW_ELA_STAKEHOLDERS
;
  GRANT SELECT ON "SPIREMGR"."XVIEW_ELA_STAKEHOLDERS" TO "SDBMGR";
  GRANT SELECT ON "SPIREMGR"."XVIEW_ELA_STAKEHOLDERS" TO "APPENV";
  GRANT SELECT ON "SPIREMGR"."XVIEW_ELA_STAKEHOLDERS" TO "BPMMGR";
