--------------------------------------------------------
--  DDL for View XVIEW_BUSINESS_STAGES
--------------------------------------------------------

  CREATE OR REPLACE FORCE EDITIONABLE VIEW "BPMMGR"."XVIEW_BUSINESS_STAGES" ("BS_ID", "START_DATETIME", "END_DATETIME", "BP_ID", "BA_ID", "BRC_ID", "STAGE_LABEL", "STAGE_STATUS", "ACTION_DESC_STAGE", "PRIMARY_DATA_UREF", "FINAL_SUPER_ROUTINE_STATUS") AS 
  SELECT "BS_ID","START_DATETIME","END_DATETIME","BP_ID","BA_ID","BRC_ID","STAGE_LABEL","STAGE_STATUS","ACTION_DESC_STAGE","PRIMARY_DATA_UREF","FINAL_SUPER_ROUTINE_STATUS"
FROM XVIEWMGR.XVIEW_BUSINESS_STAGES
;
