--------------------------------------------------------
--  DDL for View XVIEW_INTENTION_DETAILS
--------------------------------------------------------

  CREATE OR REPLACE FORCE EDITIONABLE VIEW "BPMMGR"."XVIEW_INTENTION_DETAILS" ("ID_ID", "IN_ID", "STATUS", "START_DATETIME", "END_DATETIME", "CLAUSE_TYPE", "CLASS_TYPE", "SEVERITY", "REASON_CODE", "CLAUSE_ID", "CLAUSE_STATUS", "DISPLAY_ORDER", "DELETE_FLAG", "EDIT_FLAG", "CLEAR_FLAG", "CREATED_BY_WUA_ID", "CREATED_BY_WUA_FULL_NAME", "CREATED_DATETIME", "CLAUSE_TEXT", "RESPONSE_TEXT", "VOIDED_TEXT", "IGNORE_FLAG", "IGNORE_TEXT") AS 
  SELECT "ID_ID","IN_ID","STATUS","START_DATETIME","END_DATETIME","CLAUSE_TYPE","CLASS_TYPE","SEVERITY","REASON_CODE","CLAUSE_ID","CLAUSE_STATUS","DISPLAY_ORDER","DELETE_FLAG","EDIT_FLAG","CLEAR_FLAG","CREATED_BY_WUA_ID","CREATED_BY_WUA_FULL_NAME","CREATED_DATETIME","CLAUSE_TEXT","RESPONSE_TEXT","VOIDED_TEXT","IGNORE_FLAG","IGNORE_TEXT"
FROM XVIEWMGR.XVIEW_INTENTION_DETAILS
;
