--------------------------------------------------------
--  DDL for View XVIEW_DOCUMENT_DATA
--------------------------------------------------------

  CREATE OR REPLACE FORCE EDITIONABLE VIEW "DECMGR"."XVIEW_DOCUMENT_DATA" ("DD_ID", "DI_ID", "STATUS", "DD_IMMUTABLE_ID", "DISPLAY_SEQ", "TITLE", "CONTENT_TYPE", "CONTENT_DESCRIPTION", "SYSTEM_DOCUMENT", "OU_ID", "ORGAN_NAME", "REGISTERED_NUMBER") AS 
  SELECT "DD_ID","DI_ID","STATUS","DD_IMMUTABLE_ID","DISPLAY_SEQ","TITLE","CONTENT_TYPE","CONTENT_DESCRIPTION","SYSTEM_DOCUMENT","OU_ID","ORGAN_NAME","REGISTERED_NUMBER"
FROM XVIEWMGR.XVIEW_DOCUMENT_DATA
;
