--------------------------------------------------------
--  DDL for View XVIEW_COUNTRIES_ATTRS
--------------------------------------------------------

  CREATE OR REPLACE FORCE EDITIONABLE VIEW "BPMMGR"."XVIEW_COUNTRIES_ATTRS" ("COUNTRY_DETAIL_ID", "COUNTRY_ID", "COUNTRY_NAME", "COUNTRY_SET_ID", "ATTR_SET_ID", "NAME", "VALUE") AS 
  SELECT "COUNTRY_DETAIL_ID","COUNTRY_ID","COUNTRY_NAME","COUNTRY_SET_ID","ATTR_SET_ID","NAME","VALUE"
FROM XVIEWMGR.XVIEW_COUNTRIES_ATTRS
;
  GRANT SELECT ON "BPMMGR"."XVIEW_COUNTRIES_ATTRS" TO "APPENV";
