--------------------------------------------------------
--  DDL for View XVIEW_SCAN_PREF_SCAN_TYPES
--------------------------------------------------------

  CREATE OR REPLACE FORCE EDITIONABLE VIEW "DECMGR"."XVIEW_SCAN_PREF_SCAN_TYPES" ("SPT_ID", "SCAN_TYPE", "COVERSHEET_DOCUMENT_TEMPLATE", "SCAN_TYPE_XML", "SCAN_SHEET_DOCUMENT_TEMPLATE", "SCAN_SHEET_MAIL_MERGE_XML", "COVERSHEET_MAIL_MERGE_XML") AS 
  SELECT "SPT_ID","SCAN_TYPE","COVERSHEET_DOCUMENT_TEMPLATE","SCAN_TYPE_XML","SCAN_SHEET_DOCUMENT_TEMPLATE","SCAN_SHEET_MAIL_MERGE_XML","COVERSHEET_MAIL_MERGE_XML"
FROM XVIEWMGR.XVIEW_SCAN_PREF_SCAN_TYPES
;
  GRANT SELECT ON "DECMGR"."XVIEW_SCAN_PREF_SCAN_TYPES" TO "APPENV";
