--------------------------------------------------------
--  DDL for View XVIEW_ADVICE_TYPES
--------------------------------------------------------

  CREATE OR REPLACE FORCE EDITIONABLE VIEW "BPMMGR"."XVIEW_ADVICE_TYPES" ("ADVICE_TYPE", "ADVICE_TITLE", "ADMINISTRATIVE_BODY", "ADMINISTRATIVE_COMMUNITY", "ALLOW_ADVICE_REQUEST_DETAILS") AS 
  SELECT "ADVICE_TYPE","ADVICE_TITLE","ADMINISTRATIVE_BODY","ADMINISTRATIVE_COMMUNITY","ALLOW_ADVICE_REQUEST_DETAILS"
FROM XVIEWMGR.XVIEW_ADVICE_TYPES
;
