--------------------------------------------------------
--  DDL for View XVIEW_BUSINESS_CONTEXTS
--------------------------------------------------------

  CREATE OR REPLACE FORCE EDITIONABLE VIEW "BPMMGR"."XVIEW_BUSINESS_CONTEXTS" ("BC_ID", "PARENT_BC_ID", "CONTEXT_NAME", "PRIMARY_DATA_UREF", "SECONDARY_DATA_UREF", "TERTIARY_DATA_UREF", "ACTIVITY_DATA_UREF", "DOCUMENT_SET_UREF", "NOTIFICATION_ID") AS 
  SELECT "BC_ID","PARENT_BC_ID","CONTEXT_NAME","PRIMARY_DATA_UREF","SECONDARY_DATA_UREF","TERTIARY_DATA_UREF","ACTIVITY_DATA_UREF","DOCUMENT_SET_UREF","NOTIFICATION_ID"
FROM XVIEWMGR.XVIEW_BUSINESS_CONTEXTS
;
  GRANT SELECT ON "BPMMGR"."XVIEW_BUSINESS_CONTEXTS" TO "PVEXMGR";
  GRANT SELECT ON "BPMMGR"."XVIEW_BUSINESS_CONTEXTS" TO "DECMGR";
  GRANT SELECT ON "BPMMGR"."XVIEW_BUSINESS_CONTEXTS" TO "SPIREMGR";
  GRANT SELECT ON "BPMMGR"."XVIEW_BUSINESS_CONTEXTS" TO "APPENV";
  GRANT SELECT ON "BPMMGR"."XVIEW_BUSINESS_CONTEXTS" TO "BISAPIMGR" WITH GRANT OPTION;
