--------------------------------------------------------
--  DDL for View XVIEW_RESOURCE_TYPES
--------------------------------------------------------

  CREATE OR REPLACE FORCE EDITIONABLE VIEW "DECMGR"."XVIEW_RESOURCE_TYPES" ("RES_TYPE", "RES_TYPE_TITLE", "RES_TYPE_DESCRIPTION", "RESOURCE_NAME_EDITABLE", "RESOURCE_NAME_HINT", "SCOPED_WITHIN", "DAYS_BETWEEN_MAINTAIN") AS 
  SELECT "RES_TYPE","RES_TYPE_TITLE","RES_TYPE_DESCRIPTION","RESOURCE_NAME_EDITABLE","RESOURCE_NAME_HINT","SCOPED_WITHIN","DAYS_BETWEEN_MAINTAIN"
FROM XVIEWMGR.XVIEW_RESOURCE_TYPES
;
  GRANT SELECT ON "DECMGR"."XVIEW_RESOURCE_TYPES" TO "SECUREMGR";
  GRANT SELECT ON "DECMGR"."XVIEW_RESOURCE_TYPES" TO "BPMMGR";
  GRANT SELECT ON "DECMGR"."XVIEW_RESOURCE_TYPES" TO "APPENV";
