--------------------------------------------------------
--  DDL for View XVIEW_TRANSACTIONS
--------------------------------------------------------

  CREATE OR REPLACE FORCE EDITIONABLE VIEW "BPMMGR"."XVIEW_TRANSACTIONS" ("T_ID", "PRIMARY_DATA_UREF", "TRANSACTION_REFERENCE", "TRANSACTION_TITLE", "TRANSACTION_TYPE", "TRANSACTION_SUBTYPE", "CURRENT_STATUS", "ACTION_DESC_TRANSACTION", "EVENT_DATE", "TRANSACTION_COMMENTS", "START_DATETIME", "END_DATETIME") AS 
  SELECT "T_ID","PRIMARY_DATA_UREF","TRANSACTION_REFERENCE","TRANSACTION_TITLE","TRANSACTION_TYPE","TRANSACTION_SUBTYPE","CURRENT_STATUS","ACTION_DESC_TRANSACTION","EVENT_DATE","TRANSACTION_COMMENTS","START_DATETIME","END_DATETIME"
FROM XVIEWMGR.XVIEW_TRANSACTIONS
;
  GRANT SELECT ON "BPMMGR"."XVIEW_TRANSACTIONS" TO "SPMIGUSER";
  GRANT SELECT ON "BPMMGR"."XVIEW_TRANSACTIONS" TO "DECMGR";
  GRANT SELECT ON "BPMMGR"."XVIEW_TRANSACTIONS" TO "APPENV" WITH GRANT OPTION;
