--------------------------------------------------------
--  DDL for View XVIEW_WUA_PREF_DETAILS
--------------------------------------------------------

  CREATE OR REPLACE FORCE EDITIONABLE VIEW "SECUREMGR"."XVIEW_WUA_PREF_DETAILS" ("WPD_ID", "WUA_ID", "STATUS_CONTROL", "START_DATE", "END_DATE", "CHANGE_NUMBER", "CATEGORY_NAME", "PREFERENCE_NAME", "PREFERENCE_VALUE") AS 
  SELECT "WPD_ID","WUA_ID","STATUS_CONTROL","START_DATE","END_DATE","CHANGE_NUMBER","CATEGORY_NAME","PREFERENCE_NAME","PREFERENCE_VALUE"
FROM XVIEWMGR.XVIEW_WUA_PREF_DETAILS
;
