--------------------------------------------------------
--  DDL for View XVIEW_REPORT_PART_STYLES
--------------------------------------------------------

  CREATE OR REPLACE FORCE EDITIONABLE VIEW "REPORTMGR"."XVIEW_REPORT_PART_STYLES" ("DOMAIN", "PART_LABEL", "STYLE_NAME", "ALIGNMENT_ATTRIBUTES", "FONT_ATTRIBUTES", "INTERIOR_ATTRIBUTES", "NUMBER_FORMAT_ATTRIBUTES") AS 
  SELECT "DOMAIN","PART_LABEL","STYLE_NAME","ALIGNMENT_ATTRIBUTES","FONT_ATTRIBUTES","INTERIOR_ATTRIBUTES","NUMBER_FORMAT_ATTRIBUTES"
FROM XVIEWMGR.XVIEW_REPORT_PART_STYLES
;
