--------------------------------------------------------
--  DDL for View XVIEW_DEFINITION_STAGES
--------------------------------------------------------

  CREATE OR REPLACE FORCE EDITIONABLE VIEW "BPMMGR"."XVIEW_DEFINITION_STAGES" ("BPD_ID", "BP_ID", "STAGE_LABEL", "STAGE_TYPE", "STAGE_TITLE", "ACTION_DESC_STAGE", "STAGE_XML") AS 
  SELECT "BPD_ID","BP_ID","STAGE_LABEL","STAGE_TYPE","STAGE_TITLE","ACTION_DESC_STAGE","STAGE_XML"
FROM XVIEWMGR.XVIEW_DEFINITION_STAGES
;
  GRANT SELECT ON "BPMMGR"."XVIEW_DEFINITION_STAGES" TO "APPENV";
