--------------------------------------------------------
--  DDL for View XVIEW_ELA_NOTIFICATIONS
--------------------------------------------------------

  CREATE OR REPLACE FORCE EDITIONABLE VIEW "SPIREMGR"."XVIEW_ELA_NOTIFICATIONS" ("ELA_DETAIL_ID", "STAKEHOLDER_ID", "OUTCOME_DECISION", "IS_ID", "DC_ID", "CLEARANCE_LIST", "F680_DURATION", "REASON_FOR_REFUSAL", "DI_ID", "NOTIFICATION_DATE", "ISSUING_WUA_ID", "CLEARED_SECURITY") AS 
  SELECT "ELA_DETAIL_ID","STAKEHOLDER_ID","OUTCOME_DECISION","IS_ID","DC_ID","CLEARANCE_LIST","F680_DURATION","REASON_FOR_REFUSAL","DI_ID","NOTIFICATION_DATE","ISSUING_WUA_ID","CLEARED_SECURITY"
FROM XVIEWMGR.XVIEW_ELA_NOTIFICATIONS
;
