--------------------------------------------------------
--  DDL for View XVIEW_EXHIBITION_ITEMS
--------------------------------------------------------

  CREATE OR REPLACE FORCE EDITIONABLE VIEW "PVEXMGR"."XVIEW_EXHIBITION_ITEMS" ("PEAD_ID", "ITEM_NO", "ITEM_NAME", "ITEM_TYPE", "OTHER_PLEASE_SPECIFY", "IS_ID", "DECISION", "FINAL_DECISION") AS 
  SELECT "PEAD_ID","ITEM_NO","ITEM_NAME","ITEM_TYPE","OTHER_PLEASE_SPECIFY","IS_ID","DECISION","FINAL_DECISION"
FROM XVIEWMGR.XVIEW_EXHIBITION_ITEMS
;
  GRANT SELECT ON "PVEXMGR"."XVIEW_EXHIBITION_ITEMS" TO "APPENV";
  GRANT SELECT ON "PVEXMGR"."XVIEW_EXHIBITION_ITEMS" TO "BPMMGR";
