--------------------------------------------------------
--  DDL for View XVIEW_ACTION_GROUPS
--------------------------------------------------------

  CREATE OR REPLACE FORCE EDITIONABLE VIEW "BPMMGR"."XVIEW_ACTION_GROUPS" ("BPD_ID", "SOURCE_MNEM", "TARGET_MNEM", "DEFAULT_PROMPT", "DESCRIPTION", "ACTION_SOURCE_CODE", "ACTION_ORDER") AS 
  SELECT "BPD_ID","SOURCE_MNEM","TARGET_MNEM","DEFAULT_PROMPT","DESCRIPTION","ACTION_SOURCE_CODE","ACTION_ORDER"
FROM XVIEWMGR.XVIEW_ACTION_GROUPS
;
  GRANT SELECT ON "BPMMGR"."XVIEW_ACTION_GROUPS" TO "APPENV";
