--------------------------------------------------------
--  DDL for View XVIEW_COUNTRY_GROUPS
--------------------------------------------------------

  CREATE OR REPLACE FORCE EDITIONABLE VIEW "BPMMGR"."XVIEW_COUNTRY_GROUPS" ("COUNTRY_GROUP_DETAIL_ID", "COUNTRY_GROUP_ID", "END_DATETIME", "COUNTRY_SET_ID", "GROUP_NAME", "GROUP_STATUS", "GROUP_TYPE", "GROUP_COMMENTS") AS 
  SELECT "COUNTRY_GROUP_DETAIL_ID","COUNTRY_GROUP_ID","END_DATETIME","COUNTRY_SET_ID","GROUP_NAME","GROUP_STATUS","GROUP_TYPE","GROUP_COMMENTS"
FROM XVIEWMGR.XVIEW_COUNTRY_GROUPS
;
  GRANT SELECT ON "BPMMGR"."XVIEW_COUNTRY_GROUPS" TO "BISAPIMGR";
  GRANT SELECT ON "BPMMGR"."XVIEW_COUNTRY_GROUPS" TO "APPENV";
