--------------------------------------------------------
--  DDL for View XVIEW_DENIAL_REGIMES
--------------------------------------------------------

  CREATE OR REPLACE FORCE EDITIONABLE VIEW "SPIREMGR"."XVIEW_DENIAL_REGIMES" ("DD_ID", "D_ID", "REGIME_CODE", "DN_TYPE", "REGIME_REG_REF", "PROCESSED_REGIME_REG_REF", "POC_NUMBER", "ACTIVE_FROM_DATE", "REGIME_DENIAL_STATUS", "RATING_REFS", "REGIME_REFS", "REASON_FOR_REFUSAL", "NOTIFICATION_COMMENTS", "REVOKE_COM_OUTBOUND_REF", "REVOKE_COM_INBOUND_REF", "REVOKE_ISSUED_DATE", "EXPIRED_DATE") AS 
  SELECT "DD_ID","D_ID","REGIME_CODE","DN_TYPE","REGIME_REG_REF","PROCESSED_REGIME_REG_REF","POC_NUMBER","ACTIVE_FROM_DATE","REGIME_DENIAL_STATUS","RATING_REFS","REGIME_REFS","REASON_FOR_REFUSAL","NOTIFICATION_COMMENTS","REVOKE_COM_OUTBOUND_REF","REVOKE_COM_INBOUND_REF","REVOKE_ISSUED_DATE","EXPIRED_DATE"
FROM XVIEWMGR.XVIEW_DENIAL_REGIMES
;
