--------------------------------------------------------
--  DDL for View XVIEW_WUA_PREFERENCES
--------------------------------------------------------

  CREATE OR REPLACE FORCE EDITIONABLE VIEW "SECUREMGR"."XVIEW_WUA_PREFERENCES" ("CATEGORY_NAME", "CATEGORY_PROMPT", "CATEGORY_DISPLAY_ORDER", "PREFERENCE_NAME", "PREFERENCE_PROMPT", "PREFERENCE_HINT", "PREFERENCE_DISPLAY_ORDER", "DATA_TYPE", "WIDGET_TYPE", "MAPSET_NAME", "MANDATORY", "DEFAULT_VALUE") AS 
  SELECT "CATEGORY_NAME","CATEGORY_PROMPT","CATEGORY_DISPLAY_ORDER","PREFERENCE_NAME","PREFERENCE_PROMPT","PREFERENCE_HINT","PREFERENCE_DISPLAY_ORDER","DATA_TYPE","WIDGET_TYPE","MAPSET_NAME","MANDATORY","DEFAULT_VALUE"
FROM XVIEWMGR.XVIEW_WUA_PREFERENCES
;
  GRANT SELECT ON "SECUREMGR"."XVIEW_WUA_PREFERENCES" TO "SPIREMGR";
  GRANT SELECT ON "SECUREMGR"."XVIEW_WUA_PREFERENCES" TO "APPENV";
