--------------------------------------------------------
--  DDL for View XVIEW_BPD_TRANSITION_INVOKES
--------------------------------------------------------

  CREATE OR REPLACE FORCE EDITIONABLE VIEW "BPMMGR"."XVIEW_BPD_TRANSITION_INVOKES" ("BP_ID", "INVOKE_TYPE", "TRANSITION_LABEL", "STAGE_LABEL", "ALIAS_NAME") AS 
  SELECT "BP_ID","INVOKE_TYPE","TRANSITION_LABEL","STAGE_LABEL","ALIAS_NAME"
FROM XVIEWMGR.XVIEW_BPD_TRANSITION_INVOKES
;
