--------------------------------------------------------
--  DDL for View XVIEW_COMPLIANCE_ACTIVITY_DTLS
--------------------------------------------------------

  CREATE OR REPLACE FORCE EDITIONABLE VIEW "SPIREMGR"."XVIEW_COMPLIANCE_ACTIVITY_DTLS" ("CAD_ID", "CA_ID", "START_DATETIME", "END_DATETIME", "STATUS_CONTROL", "STATUS", "FF_ID", "CREATED_DATETIME", "CREATED_BY_WUA_ID", "CREATED_BY_FULL_NAME", "ACTIVATED_DATETIME", "ACTIVATED_BY_WUA_ID", "ACTIVATED_BY_FULL_NAME", "ACTIVITY_TYPE", "WARNING_NUMBER") AS 
  SELECT "CAD_ID","CA_ID","START_DATETIME","END_DATETIME","STATUS_CONTROL","STATUS","FF_ID","CREATED_DATETIME","CREATED_BY_WUA_ID","CREATED_BY_FULL_NAME","ACTIVATED_DATETIME","ACTIVATED_BY_WUA_ID","ACTIVATED_BY_FULL_NAME","ACTIVITY_TYPE","WARNING_NUMBER"
FROM XVIEWMGR.XVIEW_COMPLIANCE_ACTIVITY_DTLS
;
  GRANT SELECT ON "SPIREMGR"."XVIEW_COMPLIANCE_ACTIVITY_DTLS" TO "BPMMGR";
  GRANT SELECT ON "SPIREMGR"."XVIEW_COMPLIANCE_ACTIVITY_DTLS" TO "APPENV";
