--------------------------------------------------------
--  DDL for View XVIEW_FILE_FOLDER_TYPES
--------------------------------------------------------

  CREATE OR REPLACE FORCE EDITIONABLE VIEW "DECMGR"."XVIEW_FILE_FOLDER_TYPES" ("FILE_FOLDER_TYPE", "TITLE", "DESCRIPTION", "VERSION_CONTROL_ENABLED", "DOWNLOAD_FILES_ARE_HIDEABLE", "UPLOAD_PROMPT", "DOWNLOAD_PROMPT", "SHOW_TARGET_STATUS", "INTERNAL_SCAN_ENABLED", "EXTERNAL_SCAN_ENABLED", "SCAN_TYPE", "PRIMARY_PURPOSE", "SECONDARY_PURPOSE", "DEFAULT_EMAIL_TARGET") AS 
  SELECT "FILE_FOLDER_TYPE","TITLE","DESCRIPTION","VERSION_CONTROL_ENABLED","DOWNLOAD_FILES_ARE_HIDEABLE","UPLOAD_PROMPT","DOWNLOAD_PROMPT","SHOW_TARGET_STATUS","INTERNAL_SCAN_ENABLED","EXTERNAL_SCAN_ENABLED","SCAN_TYPE","PRIMARY_PURPOSE","SECONDARY_PURPOSE","DEFAULT_EMAIL_TARGET"
FROM XVIEWMGR.XVIEW_FILE_FOLDER_TYPES
;
