--------------------------------------------------------
--  DDL for View XVIEW_ELA_COUNTRIES
--------------------------------------------------------

  CREATE OR REPLACE FORCE EDITIONABLE VIEW "SPIREMGR"."XVIEW_ELA_COUNTRIES" ("ELA_DETAIL_ID", "COUNTRY_ID", "COUNTRY_NAME", "SOURCE_FLAG", "RECIPIENT_FLAG", "REASON_FOR_CONTRACT_LIST", "ULTIMATE_END_USER_FLAG", "OVERRIDE_OUTCOME") AS 
  SELECT "ELA_DETAIL_ID","COUNTRY_ID","COUNTRY_NAME","SOURCE_FLAG","RECIPIENT_FLAG","REASON_FOR_CONTRACT_LIST","ULTIMATE_END_USER_FLAG","OVERRIDE_OUTCOME"
FROM XVIEWMGR.XVIEW_ELA_COUNTRIES
;
