--------------------------------------------------------
--  DDL for View XVIEW_SCAN_PREF_TEMPLATES
--------------------------------------------------------

  CREATE OR REPLACE FORCE EDITIONABLE VIEW "DECMGR"."XVIEW_SCAN_PREF_TEMPLATES" ("SPT_ID", "NAME", "SYS_MNEM", "DESCRIPTION", "PRINT_SIZE", "AUTO_ALLOCATE_AT", "SCAN_SHEET_ALLOCATION_METHOD", "SERVICE_STATEMENT", "FILENAME_POSTFIX") AS 
  SELECT "SPT_ID","NAME","SYS_MNEM","DESCRIPTION","PRINT_SIZE","AUTO_ALLOCATE_AT","SCAN_SHEET_ALLOCATION_METHOD","SERVICE_STATEMENT","FILENAME_POSTFIX"
FROM XVIEWMGR.XVIEW_SCAN_PREF_TEMPLATES
;
