--------------------------------------------------------
--  DDL for View XVIEW_REPORT_PART_COLS
--------------------------------------------------------

  CREATE OR REPLACE FORCE EDITIONABLE VIEW "REPORTMGR"."XVIEW_REPORT_PART_COLS" ("DOMAIN", "PART_LABEL", "COLUMN_NAME", "COLUMN_TITLE", "COLUMN_WIDTH", "COLUMN_STYLE") AS 
  SELECT "DOMAIN","PART_LABEL","COLUMN_NAME","COLUMN_TITLE","COLUMN_WIDTH","COLUMN_STYLE"
FROM XVIEWMGR.XVIEW_REPORT_PART_COLS
;
