--------------------------------------------------------
--  DDL for View XVIEW_AUTH_REQUESTS
--------------------------------------------------------

  CREATE OR REPLACE FORCE EDITIONABLE VIEW "DECMGR"."XVIEW_AUTH_REQUESTS" ("AR_ID", "OBJECT_UREF", "PRIORITY", "PFA_TITLE", "PFA_TRANSACTION_REF", "PFA_PRIMARY_DATA_UREF", "EVENT_PRIMARY_DATA_UREF", "SIGN", "SIGN_WITHOUT_PLACEHOLDERS", "TRANSFER_TO_MATRIX", "UPDATE_AFTER_FILING", "LOCATION", "REASON", "WUA_ID") AS 
  SELECT "AR_ID","OBJECT_UREF","PRIORITY","PFA_TITLE","PFA_TRANSACTION_REF","PFA_PRIMARY_DATA_UREF","EVENT_PRIMARY_DATA_UREF","SIGN","SIGN_WITHOUT_PLACEHOLDERS","TRANSFER_TO_MATRIX","UPDATE_AFTER_FILING","LOCATION","REASON","WUA_ID"
FROM XVIEWMGR.XVIEW_AUTH_REQUESTS
;
