--------------------------------------------------------
--  DDL for View XVIEW_DOCUMENT_SETS
--------------------------------------------------------

  CREATE OR REPLACE FORCE EDITIONABLE VIEW "DECMGR"."XVIEW_DOCUMENT_SETS" ("DS_ID", "STATUS", "TITLE", "PRIMARY_DATA_UREF", "TRANSACTION_DATA_UREF", "ACTIVITY_DATA_UREF", "DEADLINE_DAYS") AS 
  SELECT "DS_ID","STATUS","TITLE","PRIMARY_DATA_UREF","TRANSACTION_DATA_UREF","ACTIVITY_DATA_UREF","DEADLINE_DAYS"
FROM XVIEWMGR.XVIEW_DOCUMENT_SETS
;
