--------------------------------------------------------
--  DDL for View XVIEW_RESOURCE_MEMBERS_HISTORY
--------------------------------------------------------

  CREATE OR REPLACE FORCE EDITIONABLE VIEW "DECMGR"."XVIEW_RESOURCE_MEMBERS_HISTORY" ("RD_ID", "RES_ID", "RR_ID", "RES_TYPE", "ROLE_NAME", "MEMBER_ID", "STATUS_CONTROL", "STATUS", "START_DATE", "END_DATE", "RESOURCE_PERSON_ID", "ADDRESS_ID", "LOCATION_AT_ADDRESS", "QUALIFYING_COMMENT", "BRANCH_NUMBER", "BRANCH_START_DATE", "AUTHORISATION_DATE", "AUTHORISATION_COMMENT", "WORK_TELEPHONE_NO_LIST", "FAX_NO_LIST", "MOBILE_TEL_NO", "WORK_EMAIL_ADDRESS", "LEGACY_NOTIFICATION_METHOD", "LEGACY_CREATED_BY", "LEGACY_CREATED_DATE", "LEGACY_LAST_UPDATED_BY", "LEGACY_LAST_UPDATED_DATE", "RESOURCE_PERSON_ID_CURRENT", "RR_ID_CURRENT") AS 
  SELECT "RD_ID","RES_ID","RR_ID","RES_TYPE","ROLE_NAME","MEMBER_ID","STATUS_CONTROL","STATUS","START_DATE","END_DATE","RESOURCE_PERSON_ID","ADDRESS_ID","LOCATION_AT_ADDRESS","QUALIFYING_COMMENT","BRANCH_NUMBER","BRANCH_START_DATE","AUTHORISATION_DATE","AUTHORISATION_COMMENT","WORK_TELEPHONE_NO_LIST","FAX_NO_LIST","MOBILE_TEL_NO","WORK_EMAIL_ADDRESS","LEGACY_NOTIFICATION_METHOD","LEGACY_CREATED_BY","LEGACY_CREATED_DATE","LEGACY_LAST_UPDATED_BY","LEGACY_LAST_UPDATED_DATE","RESOURCE_PERSON_ID_CURRENT","RR_ID_CURRENT"
FROM XVIEWMGR.XVIEW_RESOURCE_MEMBERS_HISTORY
;
