--------------------------------------------------------
--  DDL for View XVIEW_PORTAL_SCHEDULE_TYPES
--------------------------------------------------------

  CREATE OR REPLACE FORCE EDITIONABLE VIEW "DECMGR"."XVIEW_PORTAL_SCHEDULE_TYPES" ("DUMMY") AS 
  SELECT "DUMMY" FROM DUAL

;
  GRANT SELECT ON "DECMGR"."XVIEW_PORTAL_SCHEDULE_TYPES" TO "BPMMGR";
  GRANT SELECT ON "DECMGR"."XVIEW_PORTAL_SCHEDULE_TYPES" TO "APPENV";
