--------------------------------------------------------
--  DDL for View XVIEW_SPIRE_APPLICANTS
--------------------------------------------------------

  CREATE OR REPLACE FORCE EDITIONABLE VIEW "SPIREMGR"."XVIEW_SPIRE_APPLICANTS" ("SAD_ID", "SA_ID", "STATUS", "STATUS_CONTROL", "REG_STATUS", "CREATED_DATETIME", "CREATED_BY_WUA_ID", "CREATED_BY_NAME", "SUBMITTED_DATETIME", "SUBMITTED_BY_WUA_ID", "SUBMITTED_BY_NAME", "APPLICANT_STATUS", "APPLICANT_TYPE", "RES_ID", "FTF_ID", "COMPANY_NAME", "COMPANY_REG_NO", "COMPANY_VAT_NO", "COMPANY_EORI_NO", "COMPANY_ADDRESS", "DRAFT_PERSON_TITLE", "DRAFT_PERSON_FORENAME", "DRAFT_PERSON_MIDDLE_INITIALS", "DRAFT_PERSON_SURNAME", "OU_ID", "RP_ID", "RESTRICT_APP_VIEW", "RESTRICT_APP_PREPARATION", "RESTRICT_APP_SUBMISSION", "REJECTION_REASON") AS 
  SELECT "SAD_ID","SA_ID","STATUS","STATUS_CONTROL","REG_STATUS","CREATED_DATETIME","CREATED_BY_WUA_ID","CREATED_BY_NAME","SUBMITTED_DATETIME","SUBMITTED_BY_WUA_ID","SUBMITTED_BY_NAME","APPLICANT_STATUS","APPLICANT_TYPE","RES_ID","FTF_ID","COMPANY_NAME","COMPANY_REG_NO","COMPANY_VAT_NO","COMPANY_EORI_NO","COMPANY_ADDRESS","DRAFT_PERSON_TITLE","DRAFT_PERSON_FORENAME","DRAFT_PERSON_MIDDLE_INITIALS","DRAFT_PERSON_SURNAME","OU_ID","RP_ID","RESTRICT_APP_VIEW","RESTRICT_APP_PREPARATION","RESTRICT_APP_SUBMISSION","REJECTION_REASON"
FROM XVIEWMGR.XVIEW_SPIRE_APPLICANTS
;
  GRANT SELECT ON "SPIREMGR"."XVIEW_SPIRE_APPLICANTS" TO "BISAPIMGR";
  GRANT SELECT ON "SPIREMGR"."XVIEW_SPIRE_APPLICANTS" TO "BPMMGR";
  GRANT SELECT ON "SPIREMGR"."XVIEW_SPIRE_APPLICANTS" TO "APPENV";
