--------------------------------------------------------
--  DDL for View XVIEW_ELA_GOODS_COUNTRIES
--------------------------------------------------------

  CREATE OR REPLACE FORCE EDITIONABLE VIEW "SPIREMGR"."XVIEW_ELA_GOODS_COUNTRIES" ("ELA_DETAIL_ID", "COUNTRY_ID", "GOODS_ITEM_ID", "DC_ID", "SOURCE_FLAG", "DESTINATION_FLAG", "DESTINATION_OVERRIDE_FLAG", "OUTCOME", "LD_ID", "LICENCE_LINE_NUMBER", "PRIOR_AMENDMENT_LD_ID") AS 
  SELECT "ELA_DETAIL_ID","COUNTRY_ID","GOODS_ITEM_ID","DC_ID","SOURCE_FLAG","DESTINATION_FLAG","DESTINATION_OVERRIDE_FLAG","OUTCOME","LD_ID","LICENCE_LINE_NUMBER","PRIOR_AMENDMENT_LD_ID"
FROM XVIEWMGR.XVIEW_ELA_GOODS_COUNTRIES
;
