--------------------------------------------------------
--  DDL for View XVIEW_PV_EX_SUB_ADVICE
--------------------------------------------------------

  CREATE OR REPLACE FORCE EDITIONABLE VIEW "PVEXMGR"."XVIEW_PV_EX_SUB_ADVICE" ("PEAD_ID", "REVIEWER_NAME", "REVIEWER_CONTACT_DETAILS", "REVIEWER_QUESTION", "SENT_DATE", "TARGET_WORKING_DAYS", "RESPONSE_DATE", "REVIEW_RESPONSE", "REVIEW_SAVED", "TARGET_DAYS_REACHED") AS 
  SELECT "PEAD_ID","REVIEWER_NAME","REVIEWER_CONTACT_DETAILS","REVIEWER_QUESTION","SENT_DATE","TARGET_WORKING_DAYS","RESPONSE_DATE","REVIEW_RESPONSE","REVIEW_SAVED","TARGET_DAYS_REACHED"
FROM XVIEWMGR.XVIEW_PV_EX_SUB_ADVICE
;
  GRANT SELECT ON "PVEXMGR"."XVIEW_PV_EX_SUB_ADVICE" TO "APPENV";
  GRANT SELECT ON "PVEXMGR"."XVIEW_PV_EX_SUB_ADVICE" TO "BPMMGR";
