--------------------------------------------------------
--  DDL for View XVIEW_BPD_CONDITION_TRANS
--------------------------------------------------------

  CREATE OR REPLACE FORCE EDITIONABLE VIEW "BPMMGR"."XVIEW_BPD_CONDITION_TRANS" ("BPD_ID", "STAGE_LABEL", "SEQ", "TRANSITION_LABEL", "CONDITION_XML", "ON_CASE_XML") AS 
  SELECT "BPD_ID","STAGE_LABEL","SEQ","TRANSITION_LABEL","CONDITION_XML","ON_CASE_XML"
FROM XVIEWMGR.XVIEW_BPD_CONDITION_TRANS
;
