--------------------------------------------------------
--  DDL for View XVIEW_BPD_ACT_SET_DSPL_TALLIES
--------------------------------------------------------

  CREATE OR REPLACE FORCE EDITIONABLE VIEW "BPMMGR"."XVIEW_BPD_ACT_SET_DSPL_TALLIES" ("BPD_ID", "ACTION_SET_MNEM", "STAGE_LABEL", "TALLY", "STYLE", "DISPLAY_ORDER") AS 
  SELECT "BPD_ID","ACTION_SET_MNEM","STAGE_LABEL","TALLY","STYLE","DISPLAY_ORDER"
FROM XVIEWMGR.XVIEW_BPD_ACT_SET_DSPL_TALLIES
;
