--------------------------------------------------------
--  DDL for View XVIEW_DOCUMENT_PACKS
--------------------------------------------------------

  CREATE OR REPLACE FORCE EDITIONABLE VIEW "DECMGR"."XVIEW_DOCUMENT_PACKS" ("DP_ID", "DS_ID", "OU_ID", "CHECKED", "AUTHORISED", "ISSUED", "DOCUMENT_PACK_TYPE", "DOCUMENT_PACK_TITLE", "PERSON_ID", "RECIPIENT_DATA_UREF") AS 
  SELECT "DP_ID","DS_ID","OU_ID","CHECKED","AUTHORISED","ISSUED","DOCUMENT_PACK_TYPE","DOCUMENT_PACK_TITLE","PERSON_ID","RECIPIENT_DATA_UREF"
FROM XVIEWMGR.XVIEW_DOCUMENT_PACKS
;
