--------------------------------------------------------
--  DDL for View XVIEW_SDB_EXTAPP_GOODS_ITEMS
--------------------------------------------------------

  CREATE OR REPLACE FORCE EDITIONABLE VIEW "SDBMGR"."XVIEW_SDB_EXTAPP_GOODS_ITEMS" ("ID", "GI_ID", "DESCRIPTION", "DTI_CONTROL_ENTRY", "DTI_ARS_DESCRIPTION", "VALUE") AS 
  SELECT "ID","GI_ID","DESCRIPTION","DTI_CONTROL_ENTRY","DTI_ARS_DESCRIPTION","VALUE"
FROM XVIEWMGR.XVIEW_SDB_EXTAPP_GOODS_ITEMS
;
