--------------------------------------------------------
--  DDL for View XVIEW_REPORT_PART_ATTACH
--------------------------------------------------------

  CREATE OR REPLACE FORCE EDITIONABLE VIEW "REPORTMGR"."XVIEW_REPORT_PART_ATTACH" ("REPORT_DOMAIN", "REPORT_PART_NAME", "OUTPUT_TYPE", "OPTIONAL") AS 
  SELECT "REPORT_DOMAIN","REPORT_PART_NAME","OUTPUT_TYPE","OPTIONAL"
FROM XVIEWMGR.XVIEW_REPORT_PART_ATTACH
;
  GRANT SELECT ON "REPORTMGR"."XVIEW_REPORT_PART_ATTACH" TO "APPENV";
