--------------------------------------------------------
--  DDL for View XVIEW_OGL_TYPE_REVISIONS
--------------------------------------------------------

  CREATE OR REPLACE FORCE EDITIONABLE VIEW "SPIREMGR"."XVIEW_OGL_TYPE_REVISIONS" ("OGL_TYPE_CONDITION_DETAIL_ID", "OGL_TYPE_CONDITION_ID", "STATUS_CONTROL", "REVISION_ID", "REVISION_VERSION", "NAME", "START_DATE", "END_DATE", "INTANGIBLE_DECLARATION", "OGL_DESCRIPTION", "LINK_TO_OGL", "OGL_TYPE", "VIRTUAL_OGEL_FLAG", "OGL_ACTIVITY", "INCLUDE_IN_SEARCH", "CONDITION_LIST", "RATING_CONDITION_LIST", "MIGRATED_REVISION", "ENFORCED_DATE", "EXPANDED_CONDITION_LIST") AS 
  SELECT "OGL_TYPE_CONDITION_DETAIL_ID","OGL_TYPE_CONDITION_ID","STATUS_CONTROL","REVISION_ID","REVISION_VERSION","NAME","START_DATE","END_DATE","INTANGIBLE_DECLARATION","OGL_DESCRIPTION","LINK_TO_OGL","OGL_TYPE","VIRTUAL_OGEL_FLAG","OGL_ACTIVITY","INCLUDE_IN_SEARCH","CONDITION_LIST","RATING_CONDITION_LIST","MIGRATED_REVISION","ENFORCED_DATE","EXPANDED_CONDITION_LIST"
FROM XVIEWMGR.XVIEW_OGL_TYPE_REVISIONS
;
  GRANT SELECT ON "SPIREMGR"."XVIEW_OGL_TYPE_REVISIONS" TO "APPENV";
  GRANT SELECT ON "SPIREMGR"."XVIEW_OGL_TYPE_REVISIONS" TO "BISAPIMGR";
