--------------------------------------------------------
--  DDL for View XVIEW_CLAUSE_CLASS_SEVERITY
--------------------------------------------------------

  CREATE OR REPLACE FORCE EDITIONABLE VIEW "BPMMGR"."XVIEW_CLAUSE_CLASS_SEVERITY" ("CLAUSE_TYPE_ID", "CLAUSE_TITLE", "CLASS_TYPE", "CLASS_TITLE", "CLASS_DESCRIPTION", "SEVERITY_CODE", "SEVERITY_TITLE", "SEVERITY_DESCRIPTION", "INTENTION_DEFAULT_STATUS", "REASON_REQUIRED", "DELETABLE", "EDITABLE", "CLEARABLE", "VOIDABLE", "EVENT_REQUEST", "EVENT_RESPOND", "EVENT_REJECT", "EVENT_REQUEST_CONFIRM_TEXT", "EVENT_RESPOND_CONFIRM_TEXT", "EVENT_REJECT_CONFIRM_TEXT", "INTENTION_TYPE", "DISPLAY_COLOUR", "REQUEST_DEFINE_OWN_CONTEXT", "RESPOND_DEFINE_OWN_CONTEXT", "REJECT_DEFINE_OWN_CONTEXT", "VOIDABLE_ANYTIME_BY_CREATOR", "DEFINE_COUNTERSIGN_RECIPIENT", "LINKED_ESCALATE_FLAG", "RFI_IMMEDIATELY_CLOSABLE") AS 
  SELECT "CLAUSE_TYPE_ID","CLAUSE_TITLE","CLASS_TYPE","CLASS_TITLE","CLASS_DESCRIPTION","SEVERITY_CODE","SEVERITY_TITLE","SEVERITY_DESCRIPTION","INTENTION_DEFAULT_STATUS","REASON_REQUIRED","DELETABLE","EDITABLE","CLEARABLE","VOIDABLE","EVENT_REQUEST","EVENT_RESPOND","EVENT_REJECT","EVENT_REQUEST_CONFIRM_TEXT","EVENT_RESPOND_CONFIRM_TEXT","EVENT_REJECT_CONFIRM_TEXT","INTENTION_TYPE","DISPLAY_COLOUR","REQUEST_DEFINE_OWN_CONTEXT","RESPOND_DEFINE_OWN_CONTEXT","REJECT_DEFINE_OWN_CONTEXT","VOIDABLE_ANYTIME_BY_CREATOR","DEFINE_COUNTERSIGN_RECIPIENT","LINKED_ESCALATE_FLAG","RFI_IMMEDIATELY_CLOSABLE"
FROM XVIEWMGR.XVIEW_CLAUSE_CLASS_SEVERITY
;
