--------------------------------------------------------
--  DDL for View XVIEW_TEMPLATE_CLAUSE_DETAILS
--------------------------------------------------------

  CREATE OR REPLACE FORCE EDITIONABLE VIEW "BPMMGR"."XVIEW_TEMPLATE_CLAUSE_DETAILS" ("TCD_ID", "TC_ID", "CLAUSE_TYPE_ID", "SHORT_CODE", "TITLE", "DEFAULT_SEVERITY", "CLASS", "DEFAULT_REASON_CODE", "TEMPLATE_CLAUSE_TEXT", "DISPLAY_ORDER", "DELETE_FLAG", "EDIT_FLAG", "CLEAR_FLAG", "UPDATED_BY_WUA_ID", "UPDATED_DATETIME", "STATUS", "STATUS_CONTROL", "START_DATETIME", "END_DATETIME") AS 
  SELECT "TCD_ID","TC_ID","CLAUSE_TYPE_ID","SHORT_CODE","TITLE","DEFAULT_SEVERITY","CLASS","DEFAULT_REASON_CODE","TEMPLATE_CLAUSE_TEXT","DISPLAY_ORDER","DELETE_FLAG","EDIT_FLAG","CLEAR_FLAG","UPDATED_BY_WUA_ID","UPDATED_DATETIME","STATUS","STATUS_CONTROL","START_DATETIME","END_DATETIME"
FROM XVIEWMGR.XVIEW_TEMPLATE_CLAUSE_DETAILS
;
  GRANT SELECT ON "BPMMGR"."XVIEW_TEMPLATE_CLAUSE_DETAILS" TO "PVEXMGR";
  GRANT SELECT ON "BPMMGR"."XVIEW_TEMPLATE_CLAUSE_DETAILS" TO "SPIREMGR";
  GRANT SELECT ON "BPMMGR"."XVIEW_TEMPLATE_CLAUSE_DETAILS" TO "DECMGR";
  GRANT SELECT ON "BPMMGR"."XVIEW_TEMPLATE_CLAUSE_DETAILS" TO "APPENV";
