--------------------------------------------------------
--  DDL for View XVIEW_FILE_TRANSM_TYPE_PARAMS
--------------------------------------------------------

  CREATE OR REPLACE FORCE EDITIONABLE VIEW "PORTALMGR"."XVIEW_FILE_TRANSM_TYPE_PARAMS" ("ID", "TYPE_MNEM", "START_DATETIME", "END_DATETIME", "PARAMETER_NAME", "EXTERNAL_NAME", "PARAMETER_TYPE", "PAYLOAD_SEQUENCE") AS 
  SELECT "ID","TYPE_MNEM","START_DATETIME","END_DATETIME","PARAMETER_NAME","EXTERNAL_NAME","PARAMETER_TYPE","PAYLOAD_SEQUENCE"
FROM XVIEWMGR.XVIEW_FILE_TRANSM_TYPE_PARAMS
;
