--------------------------------------------------------
--  DDL for View XVIEW_OGL_TYPE_SECONDARY_CE
--------------------------------------------------------

  CREATE OR REPLACE FORCE EDITIONABLE VIEW "SPIREMGR"."XVIEW_OGL_TYPE_SECONDARY_CE" ("OGL_TYPE_CONDITION_DETAIL_ID", "OGL_TYPE_CONDITION_ID", "STATUS_CONTROL", "REVISION_ID", "CONDITION_NO", "SECONDARY_CONTROL_ENTRY") AS 
  SELECT "OGL_TYPE_CONDITION_DETAIL_ID","OGL_TYPE_CONDITION_ID","STATUS_CONTROL","REVISION_ID","CONDITION_NO","SECONDARY_CONTROL_ENTRY"
FROM XVIEWMGR.XVIEW_OGL_TYPE_SECONDARY_CE
;
  GRANT SELECT ON "SPIREMGR"."XVIEW_OGL_TYPE_SECONDARY_CE" TO "APPENV";
