--------------------------------------------------------
--  DDL for View XVIEW_PORTAL_FOLDERS
--------------------------------------------------------

  CREATE OR REPLACE FORCE EDITIONABLE VIEW "DECMGR"."XVIEW_PORTAL_FOLDERS" ("PF_ID", "PRIMARY_FOLDER_REFERENCE", "PF_TITLE", "STARTED", "ENDED", "PRIMARY_DATA_UREF", "FOLDER_TYPE") AS 
  SELECT "PF_ID","PRIMARY_FOLDER_REFERENCE","PF_TITLE","STARTED","ENDED","PRIMARY_DATA_UREF","FOLDER_TYPE"
FROM XVIEWMGR.XVIEW_PORTAL_FOLDERS
;
