--------------------------------------------------------
--  DDL for View XVIEW_RES_TYPE_CHECK_EVENTS
--------------------------------------------------------

  CREATE OR REPLACE FORCE EDITIONABLE VIEW "DECMGR"."XVIEW_RES_TYPE_CHECK_EVENTS" ("RES_TYPE", "DAYS_SINCE_INITIAL_REQUEST", "EVENT_LABEL", "EVENT_XML_METADATA") AS 
  SELECT "RES_TYPE","DAYS_SINCE_INITIAL_REQUEST","EVENT_LABEL","EVENT_XML_METADATA"
FROM XVIEWMGR.XVIEW_RES_TYPE_CHECK_EVENTS
;
