--------------------------------------------------------
--  DDL for View XVIEW_BUSINESS_ACTIVITIES
--------------------------------------------------------

  CREATE OR REPLACE FORCE EDITIONABLE VIEW "BPMMGR"."XVIEW_BUSINESS_ACTIVITIES" ("BA_ID", "ACTIVITY_REF", "TITLE", "STATUS", "START_DATETIME", "END_DATETIME", "BT_ID", "TYPE", "ACTION_DESC_ACTIVITY", "ACTIVITY_NOTES", "SECONDARY_DATA_UREF") AS 
  SELECT "BA_ID","ACTIVITY_REF","TITLE","STATUS","START_DATETIME","END_DATETIME","BT_ID","TYPE","ACTION_DESC_ACTIVITY","ACTIVITY_NOTES","SECONDARY_DATA_UREF"
FROM XVIEWMGR.XVIEW_BUSINESS_ACTIVITIES
;
