--------------------------------------------------------
--  DDL for View XVIEW_ORGANISATION_UNITS
--------------------------------------------------------

  CREATE OR REPLACE FORCE EDITIONABLE VIEW "DECMGR"."XVIEW_ORGANISATION_UNITS" ("OD_ID", "ORGAN_ID", "SHORT_NAME", "NAME", "NATIONALITY", "CREATED_BY_DEPT", "COMMENTS", "CREATED_BY", "CREATED_DATE", "LAST_UPDATED_BY", "LAST_UPDATED_DATE", "REGISTERED_NUMBER", "FOREIGN_REGISTERED_NUMBER", "COUNTRY_OF_ORIGIN", "ORIGIN_COUNTRY_CODE", "START_DATE", "END_DATE", "GENERAL_INFO", "WARNING_INFO") AS 
  SELECT "OD_ID","ORGAN_ID","SHORT_NAME","NAME","NATIONALITY","CREATED_BY_DEPT","COMMENTS","CREATED_BY","CREATED_DATE","LAST_UPDATED_BY","LAST_UPDATED_DATE","REGISTERED_NUMBER","FOREIGN_REGISTERED_NUMBER","COUNTRY_OF_ORIGIN","ORIGIN_COUNTRY_CODE","START_DATE","END_DATE","GENERAL_INFO","WARNING_INFO"
FROM XVIEWMGR.XVIEW_ORGANISATION_UNITS
;
  GRANT SELECT ON "DECMGR"."XVIEW_ORGANISATION_UNITS" TO "BISAPIMGR";
  GRANT SELECT ON "DECMGR"."XVIEW_ORGANISATION_UNITS" TO "SPIREMGR" WITH GRANT OPTION;
  GRANT SELECT ON "DECMGR"."XVIEW_ORGANISATION_UNITS" TO "ENVMGR";
  GRANT SELECT ON "DECMGR"."XVIEW_ORGANISATION_UNITS" TO "BPMMGR";
  GRANT SELECT ON "DECMGR"."XVIEW_ORGANISATION_UNITS" TO "APPENV";
