--------------------------------------------------------
--  DDL for View XVIEW_ENV_MAPSETS_HISTORICAL
--------------------------------------------------------

  CREATE OR REPLACE FORCE EDITIONABLE VIEW "ENVMGR"."XVIEW_ENV_MAPSETS_HISTORICAL" ("MS_DOMAIN", "ID", "MAPSET_ID", "KEY", "DATA", "DISPLAY_ORDER", "DESCRIPTION", "HISTORICAL") AS 
  SELECT "MS_DOMAIN","ID","MAPSET_ID","KEY","DATA","DISPLAY_ORDER","DESCRIPTION","HISTORICAL"
FROM XVIEWMGR.XVIEW_ENV_MAPSETS_HISTORICAL
;
