--------------------------------------------------------
--  DDL for View XVIEW_REPORTS
--------------------------------------------------------

  CREATE OR REPLACE FORCE EDITIONABLE VIEW "REPORTMGR"."XVIEW_REPORTS" ("DOMAIN", "TITLE", "DESCRIPTION", "CATEGORY_MNEM", "GLOBAL_DEFINITION", "RUN_NOW", "RUN_LATER", "RUN_REPEAT", "RUN_REPEAT_INTERVAL_MNEMS", "RUN_REPEAT_INTERVAL_DEFAULT", "DISPLAY_SCHEDULER", "CONFIG_PARAMETER_DOMAIN", "EMAIL_NOTIFICATION_ENABLED", "EMAIL_NOTIFICATION_MESSAGE", "EMAIL_DEFAULT_NOTIFY_AUDIENCE", "EMAIL_NOTIFY_AUDIENCE_QUERY", "REPORT_PART_ATTACH_LIST", "NOTIFICATION_AUDIENCE_EDITABLE", "NOTIFICATION_OPTIONAL", "PUBLISH_ENABLED", "PRIVATE_ENABLED", "PRIVATE_ENFORCED", "DEFAULT_QUEUE", "DEFAULT_RETENTION_DAYS", "RETENTION_PERIOD_EDITABLE", "MAXIMUM_RETENTION_DAYS", "DELETION_WARNING_PERIOD_DAYS", "DELETION_EMAIL_MESSAGE_TEXT", "PARAMETER_XML", "MAPSET_TEMPLATE_XML", "FILE_TRANSMISSION_TYPE_MNEM", "FILE_TRANSMISSION_TIME_OFFSET", "VISIBILITY") AS 
  SELECT "DOMAIN","TITLE","DESCRIPTION","CATEGORY_MNEM","GLOBAL_DEFINITION","RUN_NOW","RUN_LATER","RUN_REPEAT","RUN_REPEAT_INTERVAL_MNEMS","RUN_REPEAT_INTERVAL_DEFAULT","DISPLAY_SCHEDULER","CONFIG_PARAMETER_DOMAIN","EMAIL_NOTIFICATION_ENABLED","EMAIL_NOTIFICATION_MESSAGE","EMAIL_DEFAULT_NOTIFY_AUDIENCE","EMAIL_NOTIFY_AUDIENCE_QUERY","REPORT_PART_ATTACH_LIST","NOTIFICATION_AUDIENCE_EDITABLE","NOTIFICATION_OPTIONAL","PUBLISH_ENABLED","PRIVATE_ENABLED","PRIVATE_ENFORCED","DEFAULT_QUEUE","DEFAULT_RETENTION_DAYS","RETENTION_PERIOD_EDITABLE","MAXIMUM_RETENTION_DAYS","DELETION_WARNING_PERIOD_DAYS","DELETION_EMAIL_MESSAGE_TEXT","PARAMETER_XML","MAPSET_TEMPLATE_XML","FILE_TRANSMISSION_TYPE_MNEM","FILE_TRANSMISSION_TIME_OFFSET","VISIBILITY"
FROM XVIEWMGR.XVIEW_REPORTS
;
  GRANT SELECT ON "REPORTMGR"."XVIEW_REPORTS" TO "BPMMGR";
  GRANT SELECT ON "REPORTMGR"."XVIEW_REPORTS" TO "APPENV";
