--------------------------------------------------------
--  DDL for View XVIEW_DENIAL_ENTITIES
--------------------------------------------------------

  CREATE OR REPLACE FORCE EDITIONABLE VIEW "SPIREMGR"."XVIEW_DENIAL_ENTITIES" ("DD_ID", "D_ID", "ENTITY_ID", "ENTITY_NAME", "ADDRESS", "COUNTRY_ID", "POSTCODE", "PROCESSED_ENTITY_DETAILS", "TEL", "FAX", "END_USER_FLAG", "CONSIGNEE_FLAG", "OTHER_ROLE") AS 
  SELECT "DD_ID","D_ID","ENTITY_ID","ENTITY_NAME","ADDRESS","COUNTRY_ID","POSTCODE","PROCESSED_ENTITY_DETAILS","TEL","FAX","END_USER_FLAG","CONSIGNEE_FLAG","OTHER_ROLE"
FROM XVIEWMGR.XVIEW_DENIAL_ENTITIES
;
  GRANT SELECT ON "SPIREMGR"."XVIEW_DENIAL_ENTITIES" TO "APPENV";
