--------------------------------------------------------
--  DDL for View XVIEW_TALLY_TYPE_ADJUSTMENTS
--------------------------------------------------------

  CREATE OR REPLACE FORCE EDITIONABLE VIEW "BPMMGR"."XVIEW_TALLY_TYPE_ADJUSTMENTS" ("TALLY_TYPE", "ADJUSTMENT", "STATUS", "DAYS", "HOURS", "MINUTES", "SECONDS", "MIN_ADJUSTMENTS", "MAX_ADJUSTMENTS", "EDITABLE", "STORE", "DAY_TYPE") AS 
  SELECT "TALLY_TYPE","ADJUSTMENT","STATUS","DAYS","HOURS","MINUTES","SECONDS","MIN_ADJUSTMENTS","MAX_ADJUSTMENTS","EDITABLE","STORE","DAY_TYPE"
FROM XVIEWMGR.XVIEW_TALLY_TYPE_ADJUSTMENTS
;
