--------------------------------------------------------
--  DDL for View XVIEW_DENIAL_DETAILS
--------------------------------------------------------

  CREATE OR REPLACE FORCE EDITIONABLE VIEW "SPIREMGR"."XVIEW_DENIAL_DETAILS" ("DD_ID", "D_ID", "STATUS_CONTROL", "ERROR_STATUS", "REGULATOR_REF", "OTHER_REF", "ISSUING_COUNTRY_ID", "CREATED_DATETIME", "DENIAL_STATUS", "GOODS_DESCRIPTION", "QUANTITY", "MEASURE", "VALUE", "CURRENCY", "STATED_END_USE", "LEGACY_FLAG", "LEGACY_DENIAL_ID", "FILE_FOLDER_ID") AS 
  SELECT "DD_ID","D_ID","STATUS_CONTROL","ERROR_STATUS","REGULATOR_REF","OTHER_REF","ISSUING_COUNTRY_ID","CREATED_DATETIME","DENIAL_STATUS","GOODS_DESCRIPTION","QUANTITY","MEASURE","VALUE","CURRENCY","STATED_END_USE","LEGACY_FLAG","LEGACY_DENIAL_ID","FILE_FOLDER_ID"
FROM XVIEWMGR.XVIEW_DENIAL_DETAILS
;
  GRANT SELECT ON "SPIREMGR"."XVIEW_DENIAL_DETAILS" TO "APPENV";
