--------------------------------------------------------
--  DDL for View XVIEW_PORTAL_SCHEDULE_EVENTS
--------------------------------------------------------

  CREATE OR REPLACE FORCE EDITIONABLE VIEW "DECMGR"."XVIEW_PORTAL_SCHEDULE_EVENTS" ("DUMMY") AS 
  SELECT "DUMMY" FROM DUAL

;
  GRANT SELECT ON "DECMGR"."XVIEW_PORTAL_SCHEDULE_EVENTS" TO "BPMMGR";
  GRANT SELECT ON "DECMGR"."XVIEW_PORTAL_SCHEDULE_EVENTS" TO "APPENV";
