--------------------------------------------------------
--  DDL for View XVIEW_SPIRE_APPLICATIONS
--------------------------------------------------------

  CREATE OR REPLACE FORCE EDITIONABLE VIEW "SPIREMGR"."XVIEW_SPIRE_APPLICATIONS" ("DUMMY") AS 
  SELECT "DUMMY" FROM DUAL

;
  GRANT SELECT ON "SPIREMGR"."XVIEW_SPIRE_APPLICATIONS" TO "APPENV";
  GRANT SELECT ON "SPIREMGR"."XVIEW_SPIRE_APPLICATIONS" TO "BPMMGR";
