--------------------------------------------------------
--  DDL for View XVIEW_NOVATION_DETAILS
--------------------------------------------------------

  CREATE OR REPLACE FORCE EDITIONABLE VIEW "PVEXMGR"."XVIEW_NOVATION_DETAILS" ("ND_ID", "N_ID", "STATUS_CONTROL", "SAR_ID", "PREVIOUS_COMPANY_NAME", "CURRENT_COMPANY_NAME", "REASON_FOR_CHANGE", "CREATED_BY_WUA_ID", "CREATED_DATETIME", "COMPLETED_BY_WUA_ID", "COMPLETED_DATETIME", "STATUS", "NOVATION_REFERENCE", "LETTER_DECISION") AS 
  SELECT "ND_ID","N_ID","STATUS_CONTROL","SAR_ID","PREVIOUS_COMPANY_NAME","CURRENT_COMPANY_NAME","REASON_FOR_CHANGE","CREATED_BY_WUA_ID","CREATED_DATETIME","COMPLETED_BY_WUA_ID","COMPLETED_DATETIME","STATUS","NOVATION_REFERENCE","LETTER_DECISION"
FROM XVIEWMGR.XVIEW_NOVATION_DETAILS
;
