--------------------------------------------------------
--  DDL for View XVIEW_COMPLIANCE_VISIT_ACTIONS
--------------------------------------------------------

  CREATE OR REPLACE FORCE EDITIONABLE VIEW "SPIREMGR"."XVIEW_COMPLIANCE_VISIT_ACTIONS" ("VISIT_ID", "DESCRIPTION", "STATUS", "TYPE", "EXP_STATUS", "RESPONSE", "RESOLUTION", "CLOSED_DATE", "RESPONSE_DATE", "PUBLISH_DATE") AS 
  SELECT "VISIT_ID","DESCRIPTION","STATUS","TYPE","EXP_STATUS","RESPONSE","RESOLUTION","CLOSED_DATE","RESPONSE_DATE","PUBLISH_DATE"
FROM XVIEWMGR.XVIEW_COMPLIANCE_VISIT_ACTIONS
;
