--------------------------------------------------------
--  DDL for View XVIEW_SURVEY_INSTANCES
--------------------------------------------------------

  CREATE OR REPLACE FORCE EDITIONABLE VIEW "SURVEYMGR"."XVIEW_SURVEY_INSTANCES" ("ST_ID", "SI_ID", "INSTANCE_TYPE", "INSTANCE_TITLE", "CREATED_DATETIME", "STATUS", "RESPONSE_NUMBER", "RESPONSE_DATETIME", "TEMPLATE_NAME", "TEMPLATE_DESCRIPTION") AS 
  SELECT "ST_ID","SI_ID","INSTANCE_TYPE","INSTANCE_TITLE","CREATED_DATETIME","STATUS","RESPONSE_NUMBER","RESPONSE_DATETIME","TEMPLATE_NAME","TEMPLATE_DESCRIPTION"
FROM XVIEWMGR.XVIEW_SURVEY_INSTANCES
;
  GRANT SELECT ON "SURVEYMGR"."XVIEW_SURVEY_INSTANCES" TO "BPMMGR";
  GRANT SELECT ON "SURVEYMGR"."XVIEW_SURVEY_INSTANCES" TO "APPENV";
