--------------------------------------------------------
--  DDL for View XVIEW_ELA_GOODS
--------------------------------------------------------

  CREATE OR REPLACE FORCE EDITIONABLE VIEW "SPIREMGR"."XVIEW_ELA_GOODS" ("ELA_DETAIL_ID", "ITEM_NO", "DESCRIPTION", "PART_NO", "EXPORT_CONTROL_ENTRY", "GOODS_QUANTITY_MEASURE", "GOODS_QUANTITY", "GOODS_VALUE", "MANUFACTURERS_HOMEPAGE", "END_USE_INFORM_EXHAUSTED_FLAG", "FINAL_OUTCOME", "ORIGINAL_FINAL_OUTCOME", "REASON_FOR_REFUSAL", "XML_DATA", "ITEM_NAME", "DTI_COMMENT", "LINE_NO", "TECHNICAL_DESCRIPTION") AS 
  SELECT "ELA_DETAIL_ID","ITEM_NO","DESCRIPTION","PART_NO","EXPORT_CONTROL_ENTRY","GOODS_QUANTITY_MEASURE","GOODS_QUANTITY","GOODS_VALUE","MANUFACTURERS_HOMEPAGE","END_USE_INFORM_EXHAUSTED_FLAG","FINAL_OUTCOME","ORIGINAL_FINAL_OUTCOME","REASON_FOR_REFUSAL","XML_DATA","ITEM_NAME","DTI_COMMENT","LINE_NO","TECHNICAL_DESCRIPTION"
FROM XVIEWMGR.XVIEW_ELA_GOODS
;
  GRANT SELECT ON "SPIREMGR"."XVIEW_ELA_GOODS" TO "BPMMGR";
  GRANT SELECT ON "SPIREMGR"."XVIEW_ELA_GOODS" TO "SDBMGR";
  GRANT SELECT ON "SPIREMGR"."XVIEW_ELA_GOODS" TO "APPENV";
