--------------------------------------------------------
--  DDL for View XVIEW_DOCUMENT_SET_REVIEWS
--------------------------------------------------------

  CREATE OR REPLACE FORCE EDITIONABLE VIEW "DECMGR"."XVIEW_DOCUMENT_SET_REVIEWS" ("DS_ID", "REVIEW_ID", "REVIEWER", "REVIEWER_DISPLAY_NAME", "DEADLINE_DAYS", "INTERRUPT_CASE_TALLY", "REVIEW_REQUIRED", "REVIEW_STATUS", "USE_EXISTING_AUDIENCE", "REVIEW_AUDIENCE_LIST", "MEMBER_SELECT_LIST", "AUDIENCE_ASSIGN_ROLE", "SEND_AGAIN_AUDIENCE", "COPY_FROM_SOURCE_DCP", "FILE_FOLDER_TYPE", "VIEW_CODE", "NOTIFICATION_MESSAGE") AS 
  SELECT "DS_ID","REVIEW_ID","REVIEWER","REVIEWER_DISPLAY_NAME","DEADLINE_DAYS","INTERRUPT_CASE_TALLY","REVIEW_REQUIRED","REVIEW_STATUS","USE_EXISTING_AUDIENCE","REVIEW_AUDIENCE_LIST","MEMBER_SELECT_LIST","AUDIENCE_ASSIGN_ROLE","SEND_AGAIN_AUDIENCE","COPY_FROM_SOURCE_DCP","FILE_FOLDER_TYPE","VIEW_CODE","NOTIFICATION_MESSAGE"
FROM XVIEWMGR.XVIEW_DOCUMENT_SET_REVIEWS
;
