--------------------------------------------------------
--  DDL for View XVIEW_DOCUMENT_PACK_RECIPIENTS
--------------------------------------------------------

  CREATE OR REPLACE FORCE EDITIONABLE VIEW "DECMGR"."XVIEW_DOCUMENT_PACK_RECIPIENTS" ("DP_ID", "AUDIENCE_TYPE", "AUDIENCE_TITLE", "FULL_NAME", "MEMBER_ID", "PERSON_ID", "ADDRESS_ID", "LOCATION_AT_ADDRESS", "NOTIFICATION_DATE", "LETTER_FLAG") AS 
  SELECT "DP_ID","AUDIENCE_TYPE","AUDIENCE_TITLE","FULL_NAME","MEMBER_ID","PERSON_ID","ADDRESS_ID","LOCATION_AT_ADDRESS","NOTIFICATION_DATE","LETTER_FLAG"
FROM XVIEWMGR.XVIEW_DOCUMENT_PACK_RECIPIENTS
;
