--------------------------------------------------------
--  DDL for View XVIEW_BPD_TRANSITIONS
--------------------------------------------------------

  CREATE OR REPLACE FORCE EDITIONABLE VIEW "BPMMGR"."XVIEW_BPD_TRANSITIONS" ("BP_ID", "PROCESS_SHORT_NAME", "TRANSITION_LABEL", "CONTEXT_SET_XML", "IN_TRANSITION_XML", "BEFORE_TRANSITION_XML", "AFTER_TRANSITION_XML") AS 
  SELECT "BP_ID","PROCESS_SHORT_NAME","TRANSITION_LABEL","CONTEXT_SET_XML","IN_TRANSITION_XML","BEFORE_TRANSITION_XML","AFTER_TRANSITION_XML"
FROM XVIEWMGR.XVIEW_BPD_TRANSITIONS
;
