--------------------------------------------------------
--  DDL for View XVIEW_SURVEY_TYPE_QUESTIONS
--------------------------------------------------------

  CREATE OR REPLACE FORCE EDITIONABLE VIEW "SURVEYMGR"."XVIEW_SURVEY_TYPE_QUESTIONS" ("ST_ID", "Q_ID", "Q_NUMBER", "TITLE", "QUESTION_TYPE", "MAPSET_TYPE", "MAPSET_NAME", "PARAGRAPH_DECORATION") AS 
  SELECT "ST_ID","Q_ID","Q_NUMBER","TITLE","QUESTION_TYPE","MAPSET_TYPE","MAPSET_NAME","PARAGRAPH_DECORATION"
FROM XVIEWMGR.XVIEW_SURVEY_TYPE_QUESTIONS
;
