--------------------------------------------------------
--  DDL for View XVIEW_SITE_DETAILS
--------------------------------------------------------

  CREATE OR REPLACE FORCE EDITIONABLE VIEW "SPIREMGR"."XVIEW_SITE_DETAILS" ("SITE_ID", "SITE_DETAIL_ID", "STATUS", "STATUS_CONTROL", "SITE_STATUS", "OCCUPANCY_STATUS", "DIVISION_TITLE", "TURN_NUMBER", "SPIRE_APPLICANT_ID", "SPIRE_APPLICANT_UREF", "STAKEHOLDER_ADDRESS", "STAKEHOLDER_POSTCODE", "COMMENTS", "RES_ID", "RESTRICT_APP_VIEW", "RESTRICT_APP_PREPARATION", "RESTRICT_APP_SUBMISSION") AS 
  SELECT "SITE_ID","SITE_DETAIL_ID","STATUS","STATUS_CONTROL","SITE_STATUS","OCCUPANCY_STATUS","DIVISION_TITLE","TURN_NUMBER","SPIRE_APPLICANT_ID","SPIRE_APPLICANT_UREF","STAKEHOLDER_ADDRESS","STAKEHOLDER_POSTCODE","COMMENTS","RES_ID","RESTRICT_APP_VIEW","RESTRICT_APP_PREPARATION","RESTRICT_APP_SUBMISSION"
FROM XVIEWMGR.XVIEW_SITE_DETAILS
;
  GRANT SELECT ON "SPIREMGR"."XVIEW_SITE_DETAILS" TO "BISAPIMGR";
  GRANT SELECT ON "SPIREMGR"."XVIEW_SITE_DETAILS" TO "BPMMGR";
  GRANT SELECT ON "SPIREMGR"."XVIEW_SITE_DETAILS" TO "APPENV";
