--------------------------------------------------------
--  DDL for View XVIEW_BPD_TRANSITION_MOVES
--------------------------------------------------------

  CREATE OR REPLACE FORCE EDITIONABLE VIEW "BPMMGR"."XVIEW_BPD_TRANSITION_MOVES" ("BP_ID", "PROCESS_SHORT_NAME", "TRANSITION_LABEL", "BEFORE_AFTER", "CNO", "STAGE_LABEL", "INVOKER_THIS", "INVOKER_SIBLING", "INVOKER_SIGNAL", "AFTER_EXISTS", "RETURN_ENVIRONMENT") AS 
  SELECT "BP_ID","PROCESS_SHORT_NAME","TRANSITION_LABEL","BEFORE_AFTER","CNO","STAGE_LABEL","INVOKER_THIS","INVOKER_SIBLING","INVOKER_SIGNAL","AFTER_EXISTS","RETURN_ENVIRONMENT"
FROM XVIEWMGR.XVIEW_BPD_TRANSITION_MOVES
;
