--------------------------------------------------------
--  DDL for View XVIEW_BPD_STAGES
--------------------------------------------------------

  CREATE OR REPLACE FORCE EDITIONABLE VIEW "BPMMGR"."XVIEW_BPD_STAGES" ("BPD_ID", "BP_ID", "PROCESS_SHORT_NAME", "STAGE_LABEL", "STAGE_TYPE", "STAGE_TITLE", "ACTION_DESC_STAGE", "STAGE_XML", "SUBROUTINE_SHORT_NAME", "STAGE_CLASSIFICATION") AS 
  SELECT "BPD_ID","BP_ID","PROCESS_SHORT_NAME","STAGE_LABEL","STAGE_TYPE","STAGE_TITLE","ACTION_DESC_STAGE","STAGE_XML","SUBROUTINE_SHORT_NAME","STAGE_CLASSIFICATION"
FROM XVIEWMGR.XVIEW_BPD_STAGES
;
  GRANT SELECT ON "BPMMGR"."XVIEW_BPD_STAGES" TO "APPENV";
  GRANT SELECT ON "BPMMGR"."XVIEW_BPD_STAGES" TO "SPIREMGR";
