--------------------------------------------------------
--  DDL for View XVIEW_RESOURCE_PEOPLE_HISTORY
--------------------------------------------------------

  CREATE OR REPLACE FORCE EDITIONABLE VIEW "DECMGR"."XVIEW_RESOURCE_PEOPLE_HISTORY" ("RPD_ID", "RP_ID", "STATUS_CONTROL", "STATUS", "FULL_NAME", "INFORMAL_NAME", "TITLE", "SURNAME", "PREFERRED_FORENAME", "FORENAME", "ORG_ID", "WORK_ADDRESS_ID", "TELEPHONE_HASH_CODE", "FAX_HASH_CODE", "JOB_DESCRIPTION", "ORACLE_USER_ID", "UNIX_LOGIN_ID", "CREATED_BY", "CREATED_DATE", "LAST_UPDATED_BY", "LAST_UPDATED_DATE", "SELF_UPDATED_DATE", "PORTAL_EMAIL_ADDRESS", "LOCATION_AT_ADDRESS", "ORGANISATION_DESCRIPTION", "DEPARTMENT_DESCRIPTION", "SHARE_ADDRESS_INFO", "PROCESSED_EMAIL_DOMAIN", "PERSON_TYPE", "SECURITY_QUESTION_FLAG", "DOB_FLAG", "SHARED_ACC_FLAG") AS 
  SELECT "RPD_ID","RP_ID","STATUS_CONTROL","STATUS","FULL_NAME","INFORMAL_NAME","TITLE","SURNAME","PREFERRED_FORENAME","FORENAME","ORG_ID","WORK_ADDRESS_ID","TELEPHONE_HASH_CODE","FAX_HASH_CODE","JOB_DESCRIPTION","ORACLE_USER_ID","UNIX_LOGIN_ID","CREATED_BY","CREATED_DATE","LAST_UPDATED_BY","LAST_UPDATED_DATE","SELF_UPDATED_DATE","PORTAL_EMAIL_ADDRESS","LOCATION_AT_ADDRESS","ORGANISATION_DESCRIPTION","DEPARTMENT_DESCRIPTION","SHARE_ADDRESS_INFO","PROCESSED_EMAIL_DOMAIN","PERSON_TYPE","SECURITY_QUESTION_FLAG","DOB_FLAG","SHARED_ACC_FLAG"
FROM XVIEWMGR.XVIEW_RESOURCE_PEOPLE_HISTORY
;
  GRANT SELECT ON "DECMGR"."XVIEW_RESOURCE_PEOPLE_HISTORY" TO "PVEXMGR";
  GRANT SELECT ON "DECMGR"."XVIEW_RESOURCE_PEOPLE_HISTORY" TO "BISAPIMGR" WITH GRANT OPTION;
  GRANT SELECT ON "DECMGR"."XVIEW_RESOURCE_PEOPLE_HISTORY" TO "FOXMGR";
  GRANT SELECT ON "DECMGR"."XVIEW_RESOURCE_PEOPLE_HISTORY" TO "SPIREMGR" WITH GRANT OPTION;
  GRANT SELECT ON "DECMGR"."XVIEW_RESOURCE_PEOPLE_HISTORY" TO "SECUREMGR" WITH GRANT OPTION;
  GRANT SELECT ON "DECMGR"."XVIEW_RESOURCE_PEOPLE_HISTORY" TO "BPMMGR" WITH GRANT OPTION;
  GRANT SELECT ON "DECMGR"."XVIEW_RESOURCE_PEOPLE_HISTORY" TO "APPENV" WITH GRANT OPTION;
  GRANT SELECT ON "DECMGR"."XVIEW_RESOURCE_PEOPLE_HISTORY" TO "SURVEYMGR";
