--------------------------------------------------------
--  DDL for View XVIEW_OGL_TYPE_CONDITIONS
--------------------------------------------------------

  CREATE OR REPLACE FORCE EDITIONABLE VIEW "SPIREMGR"."XVIEW_OGL_TYPE_CONDITIONS" ("OGL_TYPE_CONDITION_DETAIL_ID", "OGL_TYPE_CONDITION_ID", "REVISION_NAME", "REVISION_ID", "CONDITION_NO", "RATINGS_LIST", "SECONDARY_RATINGS_LIST", "END_USER_TYPE_GOV", "END_USER_TYPE_COM", "END_USER_TYPE_IND", "END_USER_TYPE_OTHER", "STATUS_CONTROL") AS 
  SELECT "OGL_TYPE_CONDITION_DETAIL_ID","OGL_TYPE_CONDITION_ID","REVISION_NAME","REVISION_ID","CONDITION_NO","RATINGS_LIST","SECONDARY_RATINGS_LIST","END_USER_TYPE_GOV","END_USER_TYPE_COM","END_USER_TYPE_IND","END_USER_TYPE_OTHER","STATUS_CONTROL"
FROM XVIEWMGR.XVIEW_OGL_TYPE_CONDITIONS
;
