--------------------------------------------------------
--  DDL for View XVIEW_PORTAL_FOLDER_TYPES
--------------------------------------------------------

  CREATE OR REPLACE FORCE EDITIONABLE VIEW "DECMGR"."XVIEW_PORTAL_FOLDER_TYPES" ("PF_TYPE", "FOLDER_TITLE_EDITABLE", "CONSOLIDATE_FOLDER_TITLE", "CONSOLIDATE_FOLDER_REFERENCE", "SUMMARY_MODE", "MATRIX_LEGAL_FOLDER_REQUIRED", "MATRIX_INFO_FOLDER_REQUIRED", "SYSTEM_DOMAIN") AS 
  SELECT "PF_TYPE","FOLDER_TITLE_EDITABLE","CONSOLIDATE_FOLDER_TITLE","CONSOLIDATE_FOLDER_REFERENCE","SUMMARY_MODE","MATRIX_LEGAL_FOLDER_REQUIRED","MATRIX_INFO_FOLDER_REQUIRED","SYSTEM_DOMAIN"
FROM XVIEWMGR.XVIEW_PORTAL_FOLDER_TYPES
;
