--------------------------------------------------------
--  DDL for View XVIEW_BPD_ACTIONS
--------------------------------------------------------

  CREATE OR REPLACE FORCE EDITIONABLE VIEW "BPMMGR"."XVIEW_BPD_ACTIONS" ("BPD_ID", "ACTION_MNEM", "DEFAULT_PROMPT", "DESCRIPTION", "ACTION_TYPE", "ACTION_SOURCE_CODE", "PANEL_ACTION_SOURCE_CODE", "METADATA_XML", "FOX_SERVICES_RESTRICTION") AS 
  SELECT "BPD_ID","ACTION_MNEM","DEFAULT_PROMPT","DESCRIPTION","ACTION_TYPE","ACTION_SOURCE_CODE","PANEL_ACTION_SOURCE_CODE","METADATA_XML","FOX_SERVICES_RESTRICTION"
FROM XVIEWMGR.XVIEW_BPD_ACTIONS
;
