--------------------------------------------------------
--  DDL for View XVIEW_DOCUMENT_MIME_TYPES
--------------------------------------------------------

  CREATE OR REPLACE FORCE EDITIONABLE VIEW "DECMGR"."XVIEW_DOCUMENT_MIME_TYPES" ("DMT_ID", "MIME_TYPE", "DESCRIPTION", "DEFAULT_EXT_ID", "EXT_ID", "EXT", "MIME_TYPE_LOWER") AS 
  SELECT "DMT_ID","MIME_TYPE","DESCRIPTION","DEFAULT_EXT_ID","EXT_ID","EXT","MIME_TYPE_LOWER"
FROM XVIEWMGR.XVIEW_DOCUMENT_MIME_TYPES
;
