--------------------------------------------------------
--  DDL for View XVIEW_OGL_TYPE_DST_COUNTRY_INC
--------------------------------------------------------

  CREATE OR REPLACE FORCE EDITIONABLE VIEW "SPIREMGR"."XVIEW_OGL_TYPE_DST_COUNTRY_INC" ("OGL_TYPE_CONDITION_ID", "OGL_TYPE_CONDITION_DETAIL_ID", "REVISION_ID", "REVISION_NAME", "CONDITION_NO", "COUNTRY_ID", "COUNTRY_NAME") AS 
  SELECT "OGL_TYPE_CONDITION_ID","OGL_TYPE_CONDITION_DETAIL_ID","REVISION_ID","REVISION_NAME","CONDITION_NO","COUNTRY_ID","COUNTRY_NAME"
FROM XVIEWMGR.XVIEW_OGL_TYPE_DST_COUNTRY_INC
;
