--------------------------------------------------------
--  DDL for View XVIEW_NOTIFICATION_SETS
--------------------------------------------------------

  CREATE OR REPLACE FORCE EDITIONABLE VIEW "DECMGR"."XVIEW_NOTIFICATION_SETS" ("NS_ID", "NOTIFICATION_DATE", "NOTIFICATION_TYPE", "CREATED_WUA_ID", "FOLDER_REF", "TRANSACTION_REF", "SUBJECT", "TOPIC", "CONSULTATION_STATUS", "DOC_REVIEW_TARGET") AS 
  SELECT "NS_ID","NOTIFICATION_DATE","NOTIFICATION_TYPE","CREATED_WUA_ID","FOLDER_REF","TRANSACTION_REF","SUBJECT","TOPIC","CONSULTATION_STATUS","DOC_REVIEW_TARGET"
FROM XVIEWMGR.XVIEW_NOTIFICATION_SETS
;
  GRANT SELECT ON "DECMGR"."XVIEW_NOTIFICATION_SETS" TO "BPMMGR";
  GRANT SELECT ON "DECMGR"."XVIEW_NOTIFICATION_SETS" TO "SPIREMGR";
  GRANT SELECT ON "DECMGR"."XVIEW_NOTIFICATION_SETS" TO "APPENV";
