--------------------------------------------------------
--  DDL for View XVIEW_DOCUMENT_COMPOSITIONS
--------------------------------------------------------

  CREATE OR REPLACE FORCE EDITIONABLE VIEW "DECMGR"."XVIEW_DOCUMENT_COMPOSITIONS" ("DC_ID", "DOCUMENT_TYPE", "DOCUMENT_TITLE", "STATUS", "DOCUMENT_TEMPLATE") AS 
  SELECT "DC_ID","DOCUMENT_TYPE","DOCUMENT_TITLE","STATUS","DOCUMENT_TEMPLATE"
FROM XVIEWMGR.XVIEW_DOCUMENT_COMPOSITIONS
;
  GRANT SELECT ON "DECMGR"."XVIEW_DOCUMENT_COMPOSITIONS" TO "BISAPIMGR";
  GRANT SELECT ON "DECMGR"."XVIEW_DOCUMENT_COMPOSITIONS" TO "PVEXMGR";
  GRANT SELECT ON "DECMGR"."XVIEW_DOCUMENT_COMPOSITIONS" TO "BPMMGR";
  GRANT SELECT ON "DECMGR"."XVIEW_DOCUMENT_COMPOSITIONS" TO "SPIREMGR";
  GRANT SELECT ON "DECMGR"."XVIEW_DOCUMENT_COMPOSITIONS" TO "APPENV";
