--------------------------------------------------------
--  Constraints for Table ACTIVITY_AUDIT_ITEMS
--------------------------------------------------------

  ALTER TABLE "BPMMGR"."ACTIVITY_AUDIT_ITEMS" ADD CONSTRAINT "PK_ACTIVITY_AUDIT_ITEMS" PRIMARY KEY ("AAE_ID", "DISPLAY_SEQ")
  USING INDEX  ENABLE;
  ALTER TABLE "BPMMGR"."ACTIVITY_AUDIT_ITEMS" MODIFY ("DISPLAY_SEQ" NOT NULL ENABLE);
  ALTER TABLE "BPMMGR"."ACTIVITY_AUDIT_ITEMS" MODIFY ("AAE_ID" NOT NULL ENABLE);
