--------------------------------------------------------
--  Constraints for Table ACTIVITY_AUDIT_ENTRIES
--------------------------------------------------------

  ALTER TABLE "BPMMGR"."ACTIVITY_AUDIT_ENTRIES" ADD CONSTRAINT "ACTIVITY_AUDIT_ENTRIES_UK1" UNIQUE ("BA_ID", "DISPLAY_SEQ")
  USING INDEX  ENABLE;
  ALTER TABLE "BPMMGR"."ACTIVITY_AUDIT_ENTRIES" ADD CONSTRAINT "PK_ACTIVITY_AUDIT_ENTRIES" PRIMARY KEY ("ID")
  USING INDEX  ENABLE;
  ALTER TABLE "BPMMGR"."ACTIVITY_AUDIT_ENTRIES" MODIFY ("TITLE" NOT NULL ENABLE);
  ALTER TABLE "BPMMGR"."ACTIVITY_AUDIT_ENTRIES" MODIFY ("DISPLAY_SEQ" NOT NULL ENABLE);
  ALTER TABLE "BPMMGR"."ACTIVITY_AUDIT_ENTRIES" MODIFY ("BA_ID" NOT NULL ENABLE);
  ALTER TABLE "BPMMGR"."ACTIVITY_AUDIT_ENTRIES" MODIFY ("ID" NOT NULL ENABLE);
