--------------------------------------------------------
--  Constraints for Table ADD_SCANNED_DOCUMENT_LOADER
--------------------------------------------------------

  ALTER TABLE "DECMGR"."ADD_SCANNED_DOCUMENT_LOADER" ADD CONSTRAINT "ADD_SCANNED_DOC_LOADER_CK2" CHECK (document_set_id IS NOT NULL OR notification_id IS NOT NULL) ENABLE;
  ALTER TABLE "DECMGR"."ADD_SCANNED_DOCUMENT_LOADER" MODIFY ("STATUS" NOT NULL ENABLE);
  ALTER TABLE "DECMGR"."ADD_SCANNED_DOCUMENT_LOADER" MODIFY ("SCANNED_LETTER" NOT NULL ENABLE);
  ALTER TABLE "DECMGR"."ADD_SCANNED_DOCUMENT_LOADER" ADD CONSTRAINT "ADD_SCANNED_DOC_LOADER_CK1" CHECK (STATUS IN ('NEW', 'LOADED', 'ERROR', 'REPLACE', 'REPLACED')) ENABLE;
