--------------------------------------------------------
--  Constraints for Table ADVISORY_BODIES
--------------------------------------------------------

  ALTER TABLE "BPMMGR"."ADVISORY_BODIES" ADD CONSTRAINT "ADVISORY_BODIES_UK2" UNIQUE ("ID", "SHORT_NAME")
  USING INDEX  ENABLE;
  ALTER TABLE "BPMMGR"."ADVISORY_BODIES" ADD CONSTRAINT "ADVISORY_BODIES_UK1" UNIQUE ("ID", "NAME")
  USING INDEX  ENABLE;
  ALTER TABLE "BPMMGR"."ADVISORY_BODIES" ADD CONSTRAINT "ADVISORY_BODIES_PK" PRIMARY KEY ("ID")
  USING INDEX  ENABLE;
  ALTER TABLE "BPMMGR"."ADVISORY_BODIES" MODIFY ("STATUS" NOT NULL ENABLE);
  ALTER TABLE "BPMMGR"."ADVISORY_BODIES" MODIFY ("NAME" NOT NULL ENABLE);
  ALTER TABLE "BPMMGR"."ADVISORY_BODIES" MODIFY ("ID" NOT NULL ENABLE);
