--------------------------------------------------------
--  Constraints for Table ADVICE_ADVISORY_COMM_CRITERIA
--------------------------------------------------------

  ALTER TABLE "BPMMGR"."ADVICE_ADVISORY_COMM_CRITERIA" ADD CONSTRAINT "PK_AAC_CRITERIA" PRIMARY KEY ("ID")
  USING INDEX  ENABLE;
  ALTER TABLE "BPMMGR"."ADVICE_ADVISORY_COMM_CRITERIA" ADD CONSTRAINT "AAC_CRITERIA_CK1" CHECK ((END_DATETIME IS NULL AND STATUS_CONTROL = 'C') OR (END_DATETIME IS NOT NULL AND STATUS_CONTROL IS NULL)) ENABLE;
  ALTER TABLE "BPMMGR"."ADVICE_ADVISORY_COMM_CRITERIA" MODIFY ("START_DATETIME" NOT NULL ENABLE);
  ALTER TABLE "BPMMGR"."ADVICE_ADVISORY_COMM_CRITERIA" MODIFY ("STATUS" NOT NULL ENABLE);
  ALTER TABLE "BPMMGR"."ADVICE_ADVISORY_COMM_CRITERIA" MODIFY ("CRITERIA_TEXT_STR" NOT NULL ENABLE);
  ALTER TABLE "BPMMGR"."ADVICE_ADVISORY_COMM_CRITERIA" MODIFY ("CRITERIA_CODE" NOT NULL ENABLE);
  ALTER TABLE "BPMMGR"."ADVICE_ADVISORY_COMM_CRITERIA" MODIFY ("AAC_ID" NOT NULL ENABLE);
  ALTER TABLE "BPMMGR"."ADVICE_ADVISORY_COMM_CRITERIA" MODIFY ("ID" NOT NULL ENABLE);
