--------------------------------------------------------
--  Constraints for Table ADVISORY_COMMUNITIES
--------------------------------------------------------

  ALTER TABLE "BPMMGR"."ADVISORY_COMMUNITIES" ADD CONSTRAINT "ADVISORY_COMMUNITIES_UK3" UNIQUE ("ID", "SHORT_NAME")
  USING INDEX  ENABLE;
  ALTER TABLE "BPMMGR"."ADVISORY_COMMUNITIES" ADD CONSTRAINT "ADVISORY_COMMUNITIES_UK2" UNIQUE ("ID", "NAME")
  USING INDEX  ENABLE;
  ALTER TABLE "BPMMGR"."ADVISORY_COMMUNITIES" ADD CONSTRAINT "ADVISORY_COMMUNITIES_UK1" UNIQUE ("ID", "AB_ID")
  USING INDEX  ENABLE;
  ALTER TABLE "BPMMGR"."ADVISORY_COMMUNITIES" ADD CONSTRAINT "ADVISORY_COMMUNITIES_PK" PRIMARY KEY ("ID")
  USING INDEX  ENABLE;
  ALTER TABLE "BPMMGR"."ADVISORY_COMMUNITIES" MODIFY ("STATUS" NOT NULL ENABLE);
  ALTER TABLE "BPMMGR"."ADVISORY_COMMUNITIES" MODIFY ("NAME" NOT NULL ENABLE);
  ALTER TABLE "BPMMGR"."ADVISORY_COMMUNITIES" MODIFY ("AB_ID" NOT NULL ENABLE);
  ALTER TABLE "BPMMGR"."ADVISORY_COMMUNITIES" MODIFY ("ID" NOT NULL ENABLE);
