--------------------------------------------------------
--  Constraints for Table ADVICE_ADVISORY_COMM_MATRIX
--------------------------------------------------------

  ALTER TABLE "BPMMGR"."ADVICE_ADVISORY_COMM_MATRIX" ADD CONSTRAINT "ADVICE_ADV_COMM_MAT_PK" PRIMARY KEY ("ID")
  USING INDEX  ENABLE;
  ALTER TABLE "BPMMGR"."ADVICE_ADVISORY_COMM_MATRIX" MODIFY ("PURPOSE_CODE" NOT NULL ENABLE);
  ALTER TABLE "BPMMGR"."ADVICE_ADVISORY_COMM_MATRIX" MODIFY ("ADVICE_TYPE" NOT NULL ENABLE);
  ALTER TABLE "BPMMGR"."ADVICE_ADVISORY_COMM_MATRIX" MODIFY ("REF_AAC_ID" NOT NULL ENABLE);
  ALTER TABLE "BPMMGR"."ADVICE_ADVISORY_COMM_MATRIX" MODIFY ("AAC_ID" NOT NULL ENABLE);
  ALTER TABLE "BPMMGR"."ADVICE_ADVISORY_COMM_MATRIX" MODIFY ("ID" NOT NULL ENABLE);
