--------------------------------------------------------
--  Constraints for Table ADVICE_ADVISORY_COMM_MATRIX_70
--------------------------------------------------------

  ALTER TABLE "SAVEMGR"."ADVICE_ADVISORY_COMM_MATRIX_70" MODIFY ("PURPOSE_CODE" NOT NULL ENABLE);
  ALTER TABLE "SAVEMGR"."ADVICE_ADVISORY_COMM_MATRIX_70" MODIFY ("ADVICE_TYPE" NOT NULL ENABLE);
  ALTER TABLE "SAVEMGR"."ADVICE_ADVISORY_COMM_MATRIX_70" MODIFY ("REF_AAC_ID" NOT NULL ENABLE);
  ALTER TABLE "SAVEMGR"."ADVICE_ADVISORY_COMM_MATRIX_70" MODIFY ("AAC_ID" NOT NULL ENABLE);
  ALTER TABLE "SAVEMGR"."ADVICE_ADVISORY_COMM_MATRIX_70" MODIFY ("ID" NOT NULL ENABLE);
