--------------------------------------------------------
--  Constraints for Table ADVICE_SELECTION_TYPES
--------------------------------------------------------

  ALTER TABLE "BPMMGR"."ADVICE_SELECTION_TYPES" ADD CONSTRAINT "ADVICE_SELECTION_TYPES_PK1" PRIMARY KEY ("CRITERIA_CODE")
  USING INDEX  ENABLE;
  ALTER TABLE "BPMMGR"."ADVICE_SELECTION_TYPES" MODIFY ("START_DATETIME" NOT NULL ENABLE);
  ALTER TABLE "BPMMGR"."ADVICE_SELECTION_TYPES" MODIFY ("FALSE_MESSAGE_ICON" NOT NULL ENABLE);
  ALTER TABLE "BPMMGR"."ADVICE_SELECTION_TYPES" MODIFY ("TRUE_MESSAGE_ICON" NOT NULL ENABLE);
  ALTER TABLE "BPMMGR"."ADVICE_SELECTION_TYPES" MODIFY ("FALSE_INFO_MESSAGE" NOT NULL ENABLE);
  ALTER TABLE "BPMMGR"."ADVICE_SELECTION_TYPES" MODIFY ("TRUE_INFO_MESSAGE" NOT NULL ENABLE);
  ALTER TABLE "BPMMGR"."ADVICE_SELECTION_TYPES" MODIFY ("DESCRIPTION" NOT NULL ENABLE);
  ALTER TABLE "BPMMGR"."ADVICE_SELECTION_TYPES" MODIFY ("CRITERIA_CODE" NOT NULL ENABLE);
