--------------------------------------------------------
--  Constraints for Table ADVICE_ADVISORY_COMM_MATRIX_48
--------------------------------------------------------

  ALTER TABLE "SAVEMGR"."ADVICE_ADVISORY_COMM_MATRIX_48" MODIFY ("PURPOSE_CODE" NOT NULL ENABLE);
  ALTER TABLE "SAVEMGR"."ADVICE_ADVISORY_COMM_MATRIX_48" MODIFY ("ADVICE_TYPE" NOT NULL ENABLE);
  ALTER TABLE "SAVEMGR"."ADVICE_ADVISORY_COMM_MATRIX_48" MODIFY ("REF_AAC_ID" NOT NULL ENABLE);
  ALTER TABLE "SAVEMGR"."ADVICE_ADVISORY_COMM_MATRIX_48" MODIFY ("AAC_ID" NOT NULL ENABLE);
  ALTER TABLE "SAVEMGR"."ADVICE_ADVISORY_COMM_MATRIX_48" MODIFY ("ID" NOT NULL ENABLE);
