--------------------------------------------------------
--  Constraints for Table ADVICE_ADVISORY_COMM_MATRIX_69
--------------------------------------------------------

  ALTER TABLE "SAVEMGR"."ADVICE_ADVISORY_COMM_MATRIX_69" MODIFY ("PURPOSE_CODE" NOT NULL ENABLE);
  ALTER TABLE "SAVEMGR"."ADVICE_ADVISORY_COMM_MATRIX_69" MODIFY ("ADVICE_TYPE" NOT NULL ENABLE);
  ALTER TABLE "SAVEMGR"."ADVICE_ADVISORY_COMM_MATRIX_69" MODIFY ("REF_AAC_ID" NOT NULL ENABLE);
  ALTER TABLE "SAVEMGR"."ADVICE_ADVISORY_COMM_MATRIX_69" MODIFY ("AAC_ID" NOT NULL ENABLE);
  ALTER TABLE "SAVEMGR"."ADVICE_ADVISORY_COMM_MATRIX_69" MODIFY ("ID" NOT NULL ENABLE);
