--------------------------------------------------------
--  Constraints for Table ADVICE_ADVISORY_BODIES
--------------------------------------------------------

  ALTER TABLE "BPMMGR"."ADVICE_ADVISORY_BODIES" ADD CONSTRAINT "ADVICE_ADVISORY_BODIES_UK1" UNIQUE ("AB_ID", "ADVICE_TYPE")
  USING INDEX  ENABLE;
  ALTER TABLE "BPMMGR"."ADVICE_ADVISORY_BODIES" ADD CONSTRAINT "ADVICE_ADVISORY_BODIES_PK" PRIMARY KEY ("ID")
  USING INDEX  ENABLE;
  ALTER TABLE "BPMMGR"."ADVICE_ADVISORY_BODIES" MODIFY ("ADVICE_TYPE" NOT NULL ENABLE);
  ALTER TABLE "BPMMGR"."ADVICE_ADVISORY_BODIES" MODIFY ("AB_ID" NOT NULL ENABLE);
  ALTER TABLE "BPMMGR"."ADVICE_ADVISORY_BODIES" MODIFY ("ID" NOT NULL ENABLE);
