--------------------------------------------------------
--  Constraints for Table APPLICATIONS_FIV5411
--------------------------------------------------------

  ALTER TABLE "SAVEMGR"."APPLICATIONS_FIV5411" MODIFY ("CASE_CLOSED_DATE" NOT NULL ENABLE);
  ALTER TABLE "SAVEMGR"."APPLICATIONS_FIV5411" MODIFY ("INITIAL_PROCESSING_TIME" NOT NULL ENABLE);
  ALTER TABLE "SAVEMGR"."APPLICATIONS_FIV5411" MODIFY ("CASE_TYPE" NOT NULL ENABLE);
  ALTER TABLE "SAVEMGR"."APPLICATIONS_FIV5411" MODIFY ("ELA_GRP_ID" NOT NULL ENABLE);
