--------------------------------------------------------
--  Constraints for Table APPLICATION_COUNTRIES
--------------------------------------------------------

  ALTER TABLE "SDBPUBMGR"."APPLICATION_COUNTRIES" ADD CONSTRAINT "APPLICATION_COUNTRIES_PK" PRIMARY KEY ("ELA_GRP_ID", "COUNTRY_ID")
  USING INDEX  ENABLE;
  ALTER TABLE "SDBPUBMGR"."APPLICATION_COUNTRIES" MODIFY ("BATCH_ID" NOT NULL ENABLE);
  ALTER TABLE "SDBPUBMGR"."APPLICATION_COUNTRIES" MODIFY ("START_DATE" NOT NULL ENABLE);
  ALTER TABLE "SDBPUBMGR"."APPLICATION_COUNTRIES" MODIFY ("REPORT_DATE" NOT NULL ENABLE);
  ALTER TABLE "SDBPUBMGR"."APPLICATION_COUNTRIES" MODIFY ("COUNTRY_ID" NOT NULL ENABLE);
  ALTER TABLE "SDBPUBMGR"."APPLICATION_COUNTRIES" MODIFY ("ELA_GRP_ID" NOT NULL ENABLE);
