--------------------------------------------------------
--  Constraints for Table AUDIT_RATING
--------------------------------------------------------

  ALTER TABLE "WARP_OWNER"."AUDIT_RATING" MODIFY ("MODEL_NO_TYPE" NOT NULL ENABLE);
  ALTER TABLE "WARP_OWNER"."AUDIT_RATING" MODIFY ("RATING" NOT NULL ENABLE);
  ALTER TABLE "WARP_OWNER"."AUDIT_RATING" MODIFY ("CHANGE_BY" NOT NULL ENABLE);
  ALTER TABLE "WARP_OWNER"."AUDIT_RATING" MODIFY ("CHANGE_DATE" NOT NULL ENABLE);
  ALTER TABLE "WARP_OWNER"."AUDIT_RATING" MODIFY ("DETAIL_ID" NOT NULL ENABLE);
  ALTER TABLE "WARP_OWNER"."AUDIT_RATING" MODIFY ("CASE_ID" NOT NULL ENABLE);
  ALTER TABLE "WARP_OWNER"."AUDIT_RATING" MODIFY ("CHANGE_TYPE" NOT NULL ENABLE);
