--------------------------------------------------------
--  Constraints for Table AUTHORISATION_REQUESTS
--------------------------------------------------------

  ALTER TABLE "DECMGR"."AUTHORISATION_REQUESTS" ADD CONSTRAINT "AUTH_REQ_PK" PRIMARY KEY ("ID")
  USING INDEX  ENABLE;
  ALTER TABLE "DECMGR"."AUTHORISATION_REQUESTS" MODIFY ("STATUS" NOT NULL ENABLE);
  ALTER TABLE "DECMGR"."AUTHORISATION_REQUESTS" ADD CONSTRAINT "AUTH_REQ_CK1" CHECK (status IN ('COMPLETE', 'FAILED', 'FOLDER_ERROR', 'PENDING', 'READY')) ENABLE;
