--------------------------------------------------------
--  Constraints for Table AUTH_REQUEST_MATRIX_STATS
--------------------------------------------------------

  ALTER TABLE "DECMGR"."AUTH_REQUEST_MATRIX_STATS" ADD CONSTRAINT "AR_MATRIX_STATS_PK" PRIMARY KEY ("ID")
  USING INDEX  ENABLE;
  ALTER TABLE "DECMGR"."AUTH_REQUEST_MATRIX_STATS" MODIFY ("CONTENT_TYPE" NOT NULL ENABLE);
  ALTER TABLE "DECMGR"."AUTH_REQUEST_MATRIX_STATS" MODIFY ("CONTENT_SIZE" NOT NULL ENABLE);
  ALTER TABLE "DECMGR"."AUTH_REQUEST_MATRIX_STATS" MODIFY ("MFI_ID" NOT NULL ENABLE);
  ALTER TABLE "DECMGR"."AUTH_REQUEST_MATRIX_STATS" MODIFY ("AR_ID" NOT NULL ENABLE);
