--------------------------------------------------------
--  Constraints for Table AUTO_REVIEW_ADVICE_AAC_MATRIX
--------------------------------------------------------

  ALTER TABLE "SPIREMGR"."AUTO_REVIEW_ADVICE_AAC_MATRIX" MODIFY ("ADVICE_TYPE" NOT NULL ENABLE);
  ALTER TABLE "SPIREMGR"."AUTO_REVIEW_ADVICE_AAC_MATRIX" MODIFY ("AAC_ID" NOT NULL ENABLE);
  ALTER TABLE "SPIREMGR"."AUTO_REVIEW_ADVICE_AAC_MATRIX" MODIFY ("ARR_ID" NOT NULL ENABLE);
  ALTER TABLE "SPIREMGR"."AUTO_REVIEW_ADVICE_AAC_MATRIX" MODIFY ("ID" NOT NULL ENABLE);
