--------------------------------------------------------
--  Constraints for Table AUTO_REVIEW_RULES
--------------------------------------------------------

  ALTER TABLE "SPIREMGR"."AUTO_REVIEW_RULES" ADD CONSTRAINT "AUTO_REVIEW_RULES_PK" PRIMARY KEY ("ID")
  USING INDEX  ENABLE;
  ALTER TABLE "SPIREMGR"."AUTO_REVIEW_RULES" MODIFY ("COUNTRY_LIST_XML" NOT NULL ENABLE);
  ALTER TABLE "SPIREMGR"."AUTO_REVIEW_RULES" MODIFY ("CREATED_BY_WUA_ID" NOT NULL ENABLE);
  ALTER TABLE "SPIREMGR"."AUTO_REVIEW_RULES" MODIFY ("START_DATETIME" NOT NULL ENABLE);
  ALTER TABLE "SPIREMGR"."AUTO_REVIEW_RULES" MODIFY ("AC_ID" NOT NULL ENABLE);
  ALTER TABLE "SPIREMGR"."AUTO_REVIEW_RULES" MODIFY ("ID" NOT NULL ENABLE);
