--------------------------------------------------------
--  Constraints for Table BCK_SUSPECT_LICENCE_DETAILS
--------------------------------------------------------

  ALTER TABLE "HMRCMGR"."BCK_SUSPECT_LICENCE_DETAILS" MODIFY ("LICENCE_TYPE" NOT NULL ENABLE);
  ALTER TABLE "HMRCMGR"."BCK_SUSPECT_LICENCE_DETAILS" MODIFY ("START_DATE" NOT NULL ENABLE);
  ALTER TABLE "HMRCMGR"."BCK_SUSPECT_LICENCE_DETAILS" MODIFY ("ELA_DETAIL_ID" NOT NULL ENABLE);
  ALTER TABLE "HMRCMGR"."BCK_SUSPECT_LICENCE_DETAILS" MODIFY ("ELA_ID" NOT NULL ENABLE);
  ALTER TABLE "HMRCMGR"."BCK_SUSPECT_LICENCE_DETAILS" MODIFY ("L_ID" NOT NULL ENABLE);
  ALTER TABLE "HMRCMGR"."BCK_SUSPECT_LICENCE_DETAILS" MODIFY ("ID" NOT NULL ENABLE);
