--------------------------------------------------------
--  Constraints for Table BPM_ORCHESTRATE
--------------------------------------------------------

  ALTER TABLE "BPMMGR"."BPM_ORCHESTRATE" MODIFY ("STATUS" NOT NULL ENABLE);
  ALTER TABLE "BPMMGR"."BPM_ORCHESTRATE" MODIFY ("MOTION" NOT NULL ENABLE);
  ALTER TABLE "BPMMGR"."BPM_ORCHESTRATE" MODIFY ("BR_ID" NOT NULL ENABLE);
  ALTER TABLE "BPMMGR"."BPM_ORCHESTRATE" MODIFY ("OPERATION_ID" NOT NULL ENABLE);
  ALTER TABLE "BPMMGR"."BPM_ORCHESTRATE" MODIFY ("ID" NOT NULL ENABLE);
