--------------------------------------------------------
--  Constraints for Table BPM_LOGS
--------------------------------------------------------

  ALTER TABLE "BPMMGR"."BPM_LOGS" ADD CONSTRAINT "BPM_LOGS_PK" PRIMARY KEY ("ID")
  USING INDEX  ENABLE;
  ALTER TABLE "BPMMGR"."BPM_LOGS" MODIFY ("XML_DATA" NOT NULL ENABLE);
  ALTER TABLE "BPMMGR"."BPM_LOGS" MODIFY ("LOG_DATETIME" NOT NULL ENABLE);
  ALTER TABLE "BPMMGR"."BPM_LOGS" MODIFY ("LOG_REF" NOT NULL ENABLE);
  ALTER TABLE "BPMMGR"."BPM_LOGS" MODIFY ("LOG_TYPE" NOT NULL ENABLE);
  ALTER TABLE "BPMMGR"."BPM_LOGS" MODIFY ("ID" NOT NULL ENABLE);
