--------------------------------------------------------
--  Constraints for Table BUS_ROUTINE_TALLY_RELATIONS
--------------------------------------------------------

  ALTER TABLE "BPMMGR"."BUS_ROUTINE_TALLY_RELATIONS" ADD CONSTRAINT "BUS_ROUTINE_TALLY_RELS_PK" UNIQUE ("BRT_ID", "TALLY_ID", "SWITCH", "ROOT_TALLY")
  USING INDEX  ENABLE;
  ALTER TABLE "BPMMGR"."BUS_ROUTINE_TALLY_RELATIONS" MODIFY ("SWITCH" NOT NULL ENABLE);
  ALTER TABLE "BPMMGR"."BUS_ROUTINE_TALLY_RELATIONS" MODIFY ("TALLY_ID" NOT NULL ENABLE);
  ALTER TABLE "BPMMGR"."BUS_ROUTINE_TALLY_RELATIONS" MODIFY ("BRT_ID" NOT NULL ENABLE);
