--------------------------------------------------------
--  Constraints for Table BUSINESS_PROCESS_DEFINITION_13
--------------------------------------------------------

  ALTER TABLE "SAVEMGR"."BUSINESS_PROCESS_DEFINITION_13" MODIFY ("START_DATETIME" NOT NULL ENABLE);
  ALTER TABLE "SAVEMGR"."BUSINESS_PROCESS_DEFINITION_13" MODIFY ("BP_ID" NOT NULL ENABLE);
  ALTER TABLE "SAVEMGR"."BUSINESS_PROCESS_DEFINITION_13" MODIFY ("ID" NOT NULL ENABLE);
