--------------------------------------------------------
--  Constraints for Table BUSINESS_UNAVAILABLE
--------------------------------------------------------

  ALTER TABLE "BPMMGR"."BUSINESS_UNAVAILABLE" ADD CONSTRAINT "BUSINESS_UNAVAILABLE_CK1" CHECK (status IN ('ACTIVE','ARCHIVED','CANCELLED')) ENABLE;
  ALTER TABLE "BPMMGR"."BUSINESS_UNAVAILABLE" ADD CONSTRAINT "BUSINESS_UNAVAILABLE_PK" PRIMARY KEY ("ID")
  USING INDEX  ENABLE;
  ALTER TABLE "BPMMGR"."BUSINESS_UNAVAILABLE" MODIFY ("CREATED_DATETIME" NOT NULL ENABLE);
  ALTER TABLE "BPMMGR"."BUSINESS_UNAVAILABLE" MODIFY ("CREATED_BY" NOT NULL ENABLE);
  ALTER TABLE "BPMMGR"."BUSINESS_UNAVAILABLE" MODIFY ("STATUS" NOT NULL ENABLE);
  ALTER TABLE "BPMMGR"."BUSINESS_UNAVAILABLE" MODIFY ("TITLE" NOT NULL ENABLE);
  ALTER TABLE "BPMMGR"."BUSINESS_UNAVAILABLE" MODIFY ("ID" NOT NULL ENABLE);
