--------------------------------------------------------
--  Constraints for Table BUSINESS_ROUTINES
--------------------------------------------------------

  ALTER TABLE "BPMMGR"."BUSINESS_ROUTINES" ADD CONSTRAINT "BUSINESS_ROUTINES_CK2" CHECK (
    
    (
      bs_id IS NULL AND orphans_parent_br_id IS NULL AND root_br_id = id
    )
    OR (
      (bs_id IS NOT NULL OR orphans_parent_br_id IS NOT NULL) AND root_br_id != id
    )
  ) ENABLE;
  ALTER TABLE "BPMMGR"."BUSINESS_ROUTINES" ADD CHECK ("ROOT_BR_ID" IS NOT NULL) DEFERRABLE INITIALLY DEFERRED ENABLE;
  ALTER TABLE "BPMMGR"."BUSINESS_ROUTINES" ADD CONSTRAINT "BUSINESS_ROUTINES_CK1" CHECK (/* Orphan routines cannot have a parent routine stage */ orphans_parent_br_id IS NULL OR (orphans_parent_br_id IS NOT NULL AND bs_id IS NULL)) ENABLE;
  ALTER TABLE "BPMMGR"."BUSINESS_ROUTINES" ADD CONSTRAINT "BUSINESS_ROUTINES_UK1" UNIQUE ("ORPHANS_PARENT_BR_ID")
  USING INDEX  ENABLE;
  ALTER TABLE "BPMMGR"."BUSINESS_ROUTINES" ADD CONSTRAINT "BUSINESS_ROUTINES_PK" PRIMARY KEY ("ID")
  USING INDEX  ENABLE;
  ALTER TABLE "BPMMGR"."BUSINESS_ROUTINES" MODIFY ("BP_ID" NOT NULL ENABLE);
  ALTER TABLE "BPMMGR"."BUSINESS_ROUTINES" MODIFY ("ID" NOT NULL ENABLE);
