--------------------------------------------------------
--  Constraints for Table BUSINESS_STAGE_TRIGGER_LOG
--------------------------------------------------------

  ALTER TABLE "BPMMGR"."BUSINESS_STAGE_TRIGGER_LOG" ADD CONSTRAINT "BUSINESS_STAGE_TRIGGER_LOG_CK1" CHECK (/* Status options */ STATUS IN ('SUCCESS', 'FAILED')) ENABLE;
  ALTER TABLE "BPMMGR"."BUSINESS_STAGE_TRIGGER_LOG" ADD CONSTRAINT "BUSINESS_STAGE_TRIGGER_LOG_PK" PRIMARY KEY ("ID")
  USING INDEX  ENABLE;
  ALTER TABLE "BPMMGR"."BUSINESS_STAGE_TRIGGER_LOG" MODIFY ("STATUS" NOT NULL ENABLE);
  ALTER TABLE "BPMMGR"."BUSINESS_STAGE_TRIGGER_LOG" MODIFY ("PROCESSED_DATETIME" NOT NULL ENABLE);
  ALTER TABLE "BPMMGR"."BUSINESS_STAGE_TRIGGER_LOG" MODIFY ("BST_ID" NOT NULL ENABLE);
  ALTER TABLE "BPMMGR"."BUSINESS_STAGE_TRIGGER_LOG" MODIFY ("ID" NOT NULL ENABLE);
