--------------------------------------------------------
--  Constraints for Table BUSINESS_TRANSACTION_DATA
--------------------------------------------------------

  ALTER TABLE "BPMMGR"."BUSINESS_TRANSACTION_DATA" ADD CONSTRAINT "BUSINESS_TRANSACTION_DATA_PK" PRIMARY KEY ("ID")
  USING INDEX  ENABLE;
  ALTER TABLE "BPMMGR"."BUSINESS_TRANSACTION_DATA" ADD CONSTRAINT "BUSINESS_TRANSACTION_DATA_CK1" CHECK ((END_OPERATION_ID IS NOT NULL AND END_DATETIME IS NOT NULL) OR (END_OPERATION_ID IS NULL AND END_DATETIME IS NULL)) ENABLE;
  ALTER TABLE "BPMMGR"."BUSINESS_TRANSACTION_DATA" MODIFY ("START_DATETIME" NOT NULL ENABLE);
  ALTER TABLE "BPMMGR"."BUSINESS_TRANSACTION_DATA" MODIFY ("START_OPERATION_ID" NOT NULL ENABLE);
  ALTER TABLE "BPMMGR"."BUSINESS_TRANSACTION_DATA" MODIFY ("DATA_DOMAIN" NOT NULL ENABLE);
  ALTER TABLE "BPMMGR"."BUSINESS_TRANSACTION_DATA" MODIFY ("BT_ID" NOT NULL ENABLE);
  ALTER TABLE "BPMMGR"."BUSINESS_TRANSACTION_DATA" MODIFY ("ID" NOT NULL ENABLE);
