--------------------------------------------------------
--  Constraints for Table BUSINESS_ROUTINE_ASSIGNMENTS
--------------------------------------------------------

  ALTER TABLE "BPMMGR"."BUSINESS_ROUTINE_ASSIGNMENTS" ADD CONSTRAINT "BUSINESS_ROUTINE_ASSIGNMT_UK1" UNIQUE ("BRC_ID", "ASSIGNMENT")
  USING INDEX  ENABLE;
  ALTER TABLE "BPMMGR"."BUSINESS_ROUTINE_ASSIGNMENTS" ADD CONSTRAINT "BUSINESS_ROUTINE_ASSIGNMT_PK" PRIMARY KEY ("ID")
  USING INDEX  ENABLE;
  ALTER TABLE "BPMMGR"."BUSINESS_ROUTINE_ASSIGNMENTS" MODIFY ("BAS_ID" NOT NULL ENABLE);
  ALTER TABLE "BPMMGR"."BUSINESS_ROUTINE_ASSIGNMENTS" MODIFY ("ASSIGNMENT" NOT NULL ENABLE);
  ALTER TABLE "BPMMGR"."BUSINESS_ROUTINE_ASSIGNMENTS" MODIFY ("BRC_ID" NOT NULL ENABLE);
  ALTER TABLE "BPMMGR"."BUSINESS_ROUTINE_ASSIGNMENTS" MODIFY ("ID" NOT NULL ENABLE);
