--------------------------------------------------------
--  Constraints for Table BUSINESS_PROCESS_DEFINITIONS_4
--------------------------------------------------------

  ALTER TABLE "SAVEMGR"."BUSINESS_PROCESS_DEFINITIONS_4" MODIFY ("START_DATETIME" NOT NULL ENABLE);
  ALTER TABLE "SAVEMGR"."BUSINESS_PROCESS_DEFINITIONS_4" MODIFY ("BP_ID" NOT NULL ENABLE);
  ALTER TABLE "SAVEMGR"."BUSINESS_PROCESS_DEFINITIONS_4" MODIFY ("ID" NOT NULL ENABLE);
