--------------------------------------------------------
--  Constraints for Table BUSINESS_ACTIVITIES
--------------------------------------------------------

  ALTER TABLE "BPMMGR"."BUSINESS_ACTIVITIES" ADD CONSTRAINT "PK_BUSINESS_ACTIVITIES" PRIMARY KEY ("ID")
  USING INDEX  ENABLE;
  ALTER TABLE "BPMMGR"."BUSINESS_ACTIVITIES" ADD CONSTRAINT "BUSINESS_ACTIVITIES_CK1" CHECK ((END_OPERATION_ID IS NOT NULL AND END_DATETIME IS NOT NULL) OR (END_OPERATION_ID IS NULL AND END_DATETIME IS NULL)) ENABLE;
  ALTER TABLE "BPMMGR"."BUSINESS_ACTIVITIES" MODIFY ("START_DATETIME" NOT NULL ENABLE);
  ALTER TABLE "BPMMGR"."BUSINESS_ACTIVITIES" MODIFY ("START_OPERATION_ID" NOT NULL ENABLE);
