--------------------------------------------------------
--  Constraints for Table BUSINESS_PROCESS_DEFINITIONS_7
--------------------------------------------------------

  ALTER TABLE "SAVEMGR"."BUSINESS_PROCESS_DEFINITIONS_7" MODIFY ("START_DATETIME" NOT NULL ENABLE);
  ALTER TABLE "SAVEMGR"."BUSINESS_PROCESS_DEFINITIONS_7" MODIFY ("BP_ID" NOT NULL ENABLE);
  ALTER TABLE "SAVEMGR"."BUSINESS_PROCESS_DEFINITIONS_7" MODIFY ("ID" NOT NULL ENABLE);
