--------------------------------------------------------
--  Constraints for Table BUSINESS_POOL_ALLOCATIONS
--------------------------------------------------------

  ALTER TABLE "BPMMGR"."BUSINESS_POOL_ALLOCATIONS" ADD CONSTRAINT "BUSINESS_POOL_ALLOCATIONS_UK1" UNIQUE ("POOL_ID", "ALLOCATION_SET", "UREF")
  USING INDEX  ENABLE;
  ALTER TABLE "BPMMGR"."BUSINESS_POOL_ALLOCATIONS" MODIFY ("LATEST_DATETIME" NOT NULL ENABLE);
  ALTER TABLE "BPMMGR"."BUSINESS_POOL_ALLOCATIONS" MODIFY ("EARLIEST_DATETIME" NOT NULL ENABLE);
  ALTER TABLE "BPMMGR"."BUSINESS_POOL_ALLOCATIONS" MODIFY ("ALLOCATION_PASS" NOT NULL ENABLE);
  ALTER TABLE "BPMMGR"."BUSINESS_POOL_ALLOCATIONS" MODIFY ("ALLOCATION_SET" NOT NULL ENABLE);
  ALTER TABLE "BPMMGR"."BUSINESS_POOL_ALLOCATIONS" MODIFY ("UREF" NOT NULL ENABLE);
  ALTER TABLE "BPMMGR"."BUSINESS_POOL_ALLOCATIONS" MODIFY ("POOL_ID" NOT NULL ENABLE);
