--------------------------------------------------------
--  Constraints for Table BUSINESS_STAGES
--------------------------------------------------------

  ALTER TABLE "BPMMGR"."BUSINESS_STAGES" ADD CONSTRAINT "PK_BUSINESS_STAGES" PRIMARY KEY ("ID")
  USING INDEX  ENABLE;
  ALTER TABLE "BPMMGR"."BUSINESS_STAGES" ADD CONSTRAINT "BUSINESS_STAGES_CK1" CHECK ((END_OPERATION_ID IS NOT NULL AND END_DATETIME IS NOT NULL) OR (END_OPERATION_ID IS NULL AND END_DATETIME IS NULL)) ENABLE;
  ALTER TABLE "BPMMGR"."BUSINESS_STAGES" MODIFY ("STAGE_LABEL" NOT NULL ENABLE);
  ALTER TABLE "BPMMGR"."BUSINESS_STAGES" MODIFY ("BP_ID" NOT NULL ENABLE);
  ALTER TABLE "BPMMGR"."BUSINESS_STAGES" MODIFY ("START_DATETIME" NOT NULL ENABLE);
  ALTER TABLE "BPMMGR"."BUSINESS_STAGES" MODIFY ("START_OPERATION_ID" NOT NULL ENABLE);
  ALTER TABLE "BPMMGR"."BUSINESS_STAGES" MODIFY ("ID" NOT NULL ENABLE);
