--------------------------------------------------------
--  Constraints for Table BUSINESS_PROCESS_DEFINITIONS
--------------------------------------------------------

  ALTER TABLE "BPMMGR"."BUSINESS_PROCESS_DEFINITIONS" ADD CONSTRAINT "BUSINESS_PROCESS_DEF_CK1" CHECK (/*check so that bp_id can be phased out later */ id = bp_id) ENABLE;
  ALTER TABLE "BPMMGR"."BUSINESS_PROCESS_DEFINITIONS" ADD CONSTRAINT "BUSINESS_PROCESS_DEFINITIO_UK1" UNIQUE ("BP_ID", "END_DATETIME")
  USING INDEX  ENABLE;
  ALTER TABLE "BPMMGR"."BUSINESS_PROCESS_DEFINITIONS" ADD CONSTRAINT "PK_BUSINESS_PROCESS_DEFINITION" PRIMARY KEY ("ID")
  USING INDEX  ENABLE;
  ALTER TABLE "BPMMGR"."BUSINESS_PROCESS_DEFINITIONS" MODIFY ("START_DATETIME" NOT NULL ENABLE);
  ALTER TABLE "BPMMGR"."BUSINESS_PROCESS_DEFINITIONS" MODIFY ("BP_ID" NOT NULL ENABLE);
  ALTER TABLE "BPMMGR"."BUSINESS_PROCESS_DEFINITIONS" MODIFY ("ID" NOT NULL ENABLE);
