--------------------------------------------------------
--  Constraints for Table BUSINESS_UNAVAILABLE_DETAILS
--------------------------------------------------------

  ALTER TABLE "BPMMGR"."BUSINESS_UNAVAILABLE_DETAILS" ADD CONSTRAINT "BUSINESS_UNAVAILABLE_DET_CK3" CHECK (START_INCLUSIVE_DATEONLY = TRUNC(START_INCLUSIVE_DATEONLY)) ENABLE;
  ALTER TABLE "BPMMGR"."BUSINESS_UNAVAILABLE_DETAILS" ADD CONSTRAINT "BUSINESS_UNAVAILABLE_DET_CK2" CHECK (type IN ('LEAVE','SICK','HOMEWORK','BLOCKED','TRAINING','MEETINGS','CONFERENCE')) ENABLE;
  ALTER TABLE "BPMMGR"."BUSINESS_UNAVAILABLE_DETAILS" ADD CONSTRAINT "BUSINESS_UNAVAILABLE_DET_CK1" CHECK (status IN ('ACTIVE','ARCHIVED','CANCELLED')) ENABLE;
  ALTER TABLE "BPMMGR"."BUSINESS_UNAVAILABLE_DETAILS" ADD CONSTRAINT "BUSINESS_UNAVAILABLE_DET_PK" PRIMARY KEY ("ID")
  USING INDEX  ENABLE;
  ALTER TABLE "BPMMGR"."BUSINESS_UNAVAILABLE_DETAILS" MODIFY ("CREATED_DATETIME" NOT NULL ENABLE);
  ALTER TABLE "BPMMGR"."BUSINESS_UNAVAILABLE_DETAILS" MODIFY ("CREATED_BY" NOT NULL ENABLE);
  ALTER TABLE "BPMMGR"."BUSINESS_UNAVAILABLE_DETAILS" MODIFY ("END_INCLUSIVE_DATEONLY" NOT NULL ENABLE);
  ALTER TABLE "BPMMGR"."BUSINESS_UNAVAILABLE_DETAILS" MODIFY ("START_INCLUSIVE_DATEONLY" NOT NULL ENABLE);
  ALTER TABLE "BPMMGR"."BUSINESS_UNAVAILABLE_DETAILS" MODIFY ("SCOPE_UREF" NOT NULL ENABLE);
  ALTER TABLE "BPMMGR"."BUSINESS_UNAVAILABLE_DETAILS" MODIFY ("STATUS" NOT NULL ENABLE);
  ALTER TABLE "BPMMGR"."BUSINESS_UNAVAILABLE_DETAILS" MODIFY ("TYPE" NOT NULL ENABLE);
  ALTER TABLE "BPMMGR"."BUSINESS_UNAVAILABLE_DETAILS" MODIFY ("ENTRY_ID" NOT NULL ENABLE);
  ALTER TABLE "BPMMGR"."BUSINESS_UNAVAILABLE_DETAILS" MODIFY ("BU_ID" NOT NULL ENABLE);
  ALTER TABLE "BPMMGR"."BUSINESS_UNAVAILABLE_DETAILS" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "BPMMGR"."BUSINESS_UNAVAILABLE_DETAILS" ADD CONSTRAINT "BUSINESS_UNAVAILABLE_DET_CK6" CHECK ((status = 'CANCELLED' AND CANCEL_REASON IS NOT NULL) OR status != 'CANCELLED') ENABLE;
  ALTER TABLE "BPMMGR"."BUSINESS_UNAVAILABLE_DETAILS" ADD CONSTRAINT "BUSINESS_UNAVAILABLE_DET_CK5" CHECK (START_INCLUSIVE_DATEONLY <= END_INCLUSIVE_DATEONLY) ENABLE;
  ALTER TABLE "BPMMGR"."BUSINESS_UNAVAILABLE_DETAILS" ADD CONSTRAINT "BUSINESS_UNAVAILABLE_DET_CK4" CHECK (END_INCLUSIVE_DATEONLY = TRUNC(END_INCLUSIVE_DATEONLY)) ENABLE;
