--------------------------------------------------------
--  Constraints for Table BUSINESS_POOLS
--------------------------------------------------------

  ALTER TABLE "BPMMGR"."BUSINESS_POOLS" ADD CONSTRAINT "BUSINESS_POOLS_UK1" UNIQUE ("BP_ID", "DELEGATION")
  USING INDEX  ENABLE;
  ALTER TABLE "BPMMGR"."BUSINESS_POOLS" ADD CONSTRAINT "BUSINESS_POOLS_PK" PRIMARY KEY ("ID")
  USING INDEX  ENABLE;
  ALTER TABLE "BPMMGR"."BUSINESS_POOLS" MODIFY ("UPDATED_DATETIME" NOT NULL ENABLE);
  ALTER TABLE "BPMMGR"."BUSINESS_POOLS" MODIFY ("ALLOCATION_PASS" NOT NULL ENABLE);
  ALTER TABLE "BPMMGR"."BUSINESS_POOLS" MODIFY ("ALLOCATION_SET" NOT NULL ENABLE);
  ALTER TABLE "BPMMGR"."BUSINESS_POOLS" MODIFY ("DELEGATION" NOT NULL ENABLE);
  ALTER TABLE "BPMMGR"."BUSINESS_POOLS" MODIFY ("BP_ID" NOT NULL ENABLE);
  ALTER TABLE "BPMMGR"."BUSINESS_POOLS" MODIFY ("ID" NOT NULL ENABLE);
