--------------------------------------------------------
--  Constraints for Table BUSINESS_PROCESS_DEFINITIONS_2
--------------------------------------------------------

  ALTER TABLE "SAVEMGR"."BUSINESS_PROCESS_DEFINITIONS_2" MODIFY ("START_DATETIME" NOT NULL ENABLE);
  ALTER TABLE "SAVEMGR"."BUSINESS_PROCESS_DEFINITIONS_2" MODIFY ("BP_ID" NOT NULL ENABLE);
  ALTER TABLE "SAVEMGR"."BUSINESS_PROCESS_DEFINITIONS_2" MODIFY ("ID" NOT NULL ENABLE);
