--------------------------------------------------------
--  Constraints for Table BUSINESS_TRANSACTIONS
--------------------------------------------------------

  ALTER TABLE "BPMMGR"."BUSINESS_TRANSACTIONS" ADD CONSTRAINT "PK_BUSINESS_TRANSACTIONS" PRIMARY KEY ("ID")
  USING INDEX  ENABLE;
  ALTER TABLE "BPMMGR"."BUSINESS_TRANSACTIONS" ADD CONSTRAINT "BUSINESS_TRANSACTIONS_CK1" CHECK ((END_OPERATION_ID IS NOT NULL AND END_DATETIME IS NOT NULL) OR (END_OPERATION_ID IS NULL AND END_DATETIME IS NULL)) ENABLE;
  ALTER TABLE "BPMMGR"."BUSINESS_TRANSACTIONS" MODIFY ("START_DATETIME" NOT NULL ENABLE);
  ALTER TABLE "BPMMGR"."BUSINESS_TRANSACTIONS" MODIFY ("START_OPERATION_ID" NOT NULL ENABLE);
  ALTER TABLE "BPMMGR"."BUSINESS_TRANSACTIONS" MODIFY ("TRANSACTION_TYPE" NOT NULL ENABLE);
  ALTER TABLE "BPMMGR"."BUSINESS_TRANSACTIONS" MODIFY ("ID" NOT NULL ENABLE);
