--------------------------------------------------------
--  Constraints for Table BUSINESS_PROCESS_DEFINITIONS_3
--------------------------------------------------------

  ALTER TABLE "SAVEMGR"."BUSINESS_PROCESS_DEFINITIONS_3" MODIFY ("START_DATETIME" NOT NULL ENABLE);
  ALTER TABLE "SAVEMGR"."BUSINESS_PROCESS_DEFINITIONS_3" MODIFY ("BP_ID" NOT NULL ENABLE);
  ALTER TABLE "SAVEMGR"."BUSINESS_PROCESS_DEFINITIONS_3" MODIFY ("ID" NOT NULL ENABLE);
