--------------------------------------------------------
--  Constraints for Table BUSINESS_PROCESS_DEFINITIONS_1
--------------------------------------------------------

  ALTER TABLE "SAVEMGR"."BUSINESS_PROCESS_DEFINITIONS_1" MODIFY ("START_DATETIME" NOT NULL ENABLE);
  ALTER TABLE "SAVEMGR"."BUSINESS_PROCESS_DEFINITIONS_1" MODIFY ("BP_ID" NOT NULL ENABLE);
  ALTER TABLE "SAVEMGR"."BUSINESS_PROCESS_DEFINITIONS_1" MODIFY ("ID" NOT NULL ENABLE);
