--------------------------------------------------------
--  Constraints for Table BUSINESS_STAGE_TRIGGERS
--------------------------------------------------------

  ALTER TABLE "BPMMGR"."BUSINESS_STAGE_TRIGGERS" ADD CONSTRAINT "BUSINESS_STAGE_TRIGGERS_CK1" CHECK (/* Status options */ STATUS IN ('PENDING', 'EXECUTING', 'COMPLETE', 'CANCELLED', 'STALE', 'FAILED')) ENABLE;
  ALTER TABLE "BPMMGR"."BUSINESS_STAGE_TRIGGERS" ADD CONSTRAINT "BUSINESS_STAGE_TRIGGERS_PK" PRIMARY KEY ("ID")
  USING INDEX  ENABLE;
  ALTER TABLE "BPMMGR"."BUSINESS_STAGE_TRIGGERS" MODIFY ("STATUS" NOT NULL ENABLE);
  ALTER TABLE "BPMMGR"."BUSINESS_STAGE_TRIGGERS" MODIFY ("TRIGGER_DATETIME" NOT NULL ENABLE);
  ALTER TABLE "BPMMGR"."BUSINESS_STAGE_TRIGGERS" MODIFY ("BS_ID" NOT NULL ENABLE);
  ALTER TABLE "BPMMGR"."BUSINESS_STAGE_TRIGGERS" MODIFY ("ID" NOT NULL ENABLE);
