--------------------------------------------------------
--  Constraints for Table CACHED_SEARCHES_MASTER
--------------------------------------------------------

  ALTER TABLE "ENVMGR"."CACHED_SEARCHES_MASTER" ADD CONSTRAINT "CACHED_SEARCHES_MASTER_UK1" UNIQUE ("PRIMARY_SCOPE", "SECONDARY_SCOPE") DEFERRABLE INITIALLY DEFERRED
  USING INDEX  ENABLE;
  ALTER TABLE "ENVMGR"."CACHED_SEARCHES_MASTER" ADD CONSTRAINT "CACHED_SEARCHES_MASTER_PK" PRIMARY KEY ("ID")
  USING INDEX  ENABLE;
  ALTER TABLE "ENVMGR"."CACHED_SEARCHES_MASTER" MODIFY ("DATE_RUN" NOT NULL ENABLE);
  ALTER TABLE "ENVMGR"."CACHED_SEARCHES_MASTER" MODIFY ("PRIMARY_SCOPE" NOT NULL ENABLE);
  ALTER TABLE "ENVMGR"."CACHED_SEARCHES_MASTER" MODIFY ("ID" NOT NULL ENABLE);
