--------------------------------------------------------
--  Constraints for Table CACHED_SEARCHES_DETAIL
--------------------------------------------------------

  ALTER TABLE "ENVMGR"."CACHED_SEARCHES_DETAIL" ADD CONSTRAINT "CACHED_SEARCHES_DETAIL_PK" PRIMARY KEY ("ID")
  USING INDEX  ENABLE;
  ALTER TABLE "ENVMGR"."CACHED_SEARCHES_DETAIL" MODIFY ("XMLDATA" NOT NULL ENABLE);
  ALTER TABLE "ENVMGR"."CACHED_SEARCHES_DETAIL" MODIFY ("ROW_NUMBER" NOT NULL ENABLE);
  ALTER TABLE "ENVMGR"."CACHED_SEARCHES_DETAIL" MODIFY ("PAGE_NUMBER" NOT NULL ENABLE);
  ALTER TABLE "ENVMGR"."CACHED_SEARCHES_DETAIL" MODIFY ("CSM_ID" NOT NULL ENABLE);
  ALTER TABLE "ENVMGR"."CACHED_SEARCHES_DETAIL" MODIFY ("ID" NOT NULL ENABLE);
