--------------------------------------------------------
--  Constraints for Table CASE_WORK
--------------------------------------------------------

  ALTER TABLE "WARP_OWNER"."CASE_WORK" ADD CONSTRAINT "PK_CASE_WORK" PRIMARY KEY ("ID")
  USING INDEX  ENABLE;
  ALTER TABLE "WARP_OWNER"."CASE_WORK" MODIFY ("APP_TYPE" NOT NULL ENABLE);
  ALTER TABLE "WARP_OWNER"."CASE_WORK" MODIFY ("USER_ID" NOT NULL ENABLE);
  ALTER TABLE "WARP_OWNER"."CASE_WORK" MODIFY ("CASE_REF" NOT NULL ENABLE);
  ALTER TABLE "WARP_OWNER"."CASE_WORK" MODIFY ("ID" NOT NULL ENABLE);
