--------------------------------------------------------
--  Constraints for Table CASE_WEEKLY_STATS
--------------------------------------------------------

  ALTER TABLE "WARP_OWNER"."CASE_WEEKLY_STATS" ADD CONSTRAINT "PK_CASE_WEEKLY_STATS" PRIMARY KEY ("YEAR", "WEEK_NO", "APP_TYPE")
  USING INDEX  ENABLE;
  ALTER TABLE "WARP_OWNER"."CASE_WEEKLY_STATS" MODIFY ("END_DATE" NOT NULL ENABLE);
  ALTER TABLE "WARP_OWNER"."CASE_WEEKLY_STATS" MODIFY ("START_DATE" NOT NULL ENABLE);
  ALTER TABLE "WARP_OWNER"."CASE_WEEKLY_STATS" MODIFY ("APP_TYPE" NOT NULL ENABLE);
  ALTER TABLE "WARP_OWNER"."CASE_WEEKLY_STATS" MODIFY ("WEEK_NO" NOT NULL ENABLE);
  ALTER TABLE "WARP_OWNER"."CASE_WEEKLY_STATS" MODIFY ("YEAR" NOT NULL ENABLE);
