--------------------------------------------------------
--  Constraints for Table CASE_TO_ATTENDANCE
--------------------------------------------------------

  ALTER TABLE "WARP_OWNER"."CASE_TO_ATTENDANCE" ADD CONSTRAINT "PK_CASE_TO_ATTENDANCE" PRIMARY KEY ("YEAR", "WEEK_NO", "PERSON")
  USING INDEX  ENABLE;
  ALTER TABLE "WARP_OWNER"."CASE_TO_ATTENDANCE" MODIFY ("TOTAL_DAYS" NOT NULL DISABLE);
  ALTER TABLE "WARP_OWNER"."CASE_TO_ATTENDANCE" MODIFY ("PERSON" NOT NULL DISABLE);
  ALTER TABLE "WARP_OWNER"."CASE_TO_ATTENDANCE" MODIFY ("END_DATE" NOT NULL DISABLE);
  ALTER TABLE "WARP_OWNER"."CASE_TO_ATTENDANCE" MODIFY ("START_DATE" NOT NULL DISABLE);
  ALTER TABLE "WARP_OWNER"."CASE_TO_ATTENDANCE" MODIFY ("WEEK_NO" NOT NULL DISABLE);
  ALTER TABLE "WARP_OWNER"."CASE_TO_ATTENDANCE" MODIFY ("YEAR" NOT NULL DISABLE);
