--------------------------------------------------------
--  Constraints for Table CASE_WORK_TIME
--------------------------------------------------------

  ALTER TABLE "WARP_OWNER"."CASE_WORK_TIME" ADD CONSTRAINT "PK_CASE_WORK_TIME" PRIMARY KEY ("ID")
  USING INDEX  ENABLE;
  ALTER TABLE "WARP_OWNER"."CASE_WORK_TIME" MODIFY ("START_DATE" NOT NULL ENABLE);
  ALTER TABLE "WARP_OWNER"."CASE_WORK_TIME" MODIFY ("STARTED_BY" NOT NULL ENABLE);
  ALTER TABLE "WARP_OWNER"."CASE_WORK_TIME" MODIFY ("CASE_WORK_ID" NOT NULL ENABLE);
  ALTER TABLE "WARP_OWNER"."CASE_WORK_TIME" MODIFY ("ID" NOT NULL ENABLE);
