--------------------------------------------------------
--  Constraints for Table CLASS_PRIVILEGES
--------------------------------------------------------

  ALTER TABLE "BPMMGR"."CLASS_PRIVILEGES" ADD CONSTRAINT "CLASS_PRIVILEGES_CK1" CHECK (class_access IN ('SELECTABLE', 'EDITABLE', 'DELETABLE', 'CLEARABLE', 'VOIDABLE')) ENABLE;
  ALTER TABLE "BPMMGR"."CLASS_PRIVILEGES" MODIFY ("RES_TYPE" NOT NULL ENABLE);
  ALTER TABLE "BPMMGR"."CLASS_PRIVILEGES" MODIFY ("CLASS_ACCESS" NOT NULL ENABLE);
  ALTER TABLE "BPMMGR"."CLASS_PRIVILEGES" MODIFY ("CLASS_TYPE" NOT NULL ENABLE);
