--------------------------------------------------------
--  Constraints for Table COMPLIANCE_ACTIVITY_DETAILS
--------------------------------------------------------

  ALTER TABLE "SPIREMGR"."COMPLIANCE_ACTIVITY_DETAILS" ADD CONSTRAINT "COMPLIANCE_ACTIVITY_DTLS_CK1" CHECK (/* End date and status control */ (end_datetime IS NULL AND status_control='C') OR (end_datetime IS NOT NULL AND status_control IS NULL)) ENABLE;
  ALTER TABLE "SPIREMGR"."COMPLIANCE_ACTIVITY_DETAILS" ADD CONSTRAINT "COMPLIANCE_ACTIVITY_DETAILS_PK" PRIMARY KEY ("ID")
  USING INDEX  ENABLE;
  ALTER TABLE "SPIREMGR"."COMPLIANCE_ACTIVITY_DETAILS" MODIFY ("XML_DATA" NOT NULL ENABLE);
  ALTER TABLE "SPIREMGR"."COMPLIANCE_ACTIVITY_DETAILS" MODIFY ("START_DATETIME" NOT NULL ENABLE);
  ALTER TABLE "SPIREMGR"."COMPLIANCE_ACTIVITY_DETAILS" MODIFY ("CA_ID" NOT NULL ENABLE);
  ALTER TABLE "SPIREMGR"."COMPLIANCE_ACTIVITY_DETAILS" MODIFY ("ID" NOT NULL ENABLE);
