--------------------------------------------------------
--  Constraints for Table COMPLIANCE_PROFILE
--------------------------------------------------------

  ALTER TABLE "SAVEMGR"."COMPLIANCE_PROFILE" MODIFY ("WUA_ID" NOT NULL ENABLE);
  ALTER TABLE "SAVEMGR"."COMPLIANCE_PROFILE" MODIFY ("START_DATETIME" NOT NULL ENABLE);
  ALTER TABLE "SAVEMGR"."COMPLIANCE_PROFILE" MODIFY ("COMPLIANCE_LEVEL" NOT NULL ENABLE);
  ALTER TABLE "SAVEMGR"."COMPLIANCE_PROFILE" MODIFY ("SITE_ID" NOT NULL ENABLE);
  ALTER TABLE "SAVEMGR"."COMPLIANCE_PROFILE" MODIFY ("ID" NOT NULL ENABLE);
