--------------------------------------------------------
--  Constraints for Table CONFIG_PARAMETERS
--------------------------------------------------------

  ALTER TABLE "PORTALMGR"."CONFIG_PARAMETERS" MODIFY ("PARAM_DESCRIPTION" NOT NULL ENABLE);
  ALTER TABLE "PORTALMGR"."CONFIG_PARAMETERS" MODIFY ("PARAM_NAME" NOT NULL ENABLE);
  ALTER TABLE "PORTALMGR"."CONFIG_PARAMETERS" ADD CONSTRAINT "CHK_PRM_VIS" CHECK (param_visibility IN('VIEW', 'EDIT', 'HIDDEN')) ENABLE;
  ALTER TABLE "PORTALMGR"."CONFIG_PARAMETERS" MODIFY ("PARAM_VISIBILITY" NOT NULL ENABLE);
  ALTER TABLE "PORTALMGR"."CONFIG_PARAMETERS" ADD CONSTRAINT "CONFIG_PARAMETERS_CK3" CHECK (DATA_TYPE IS NULL OR DATA_TYPE != 'NULL' OR (DATA_TYPE = 'NULL' AND PARAM_VALUE = 'NULL_VALUE')) ENABLE;
  ALTER TABLE "PORTALMGR"."CONFIG_PARAMETERS" ADD CONSTRAINT "CONFIG_PARAMETERS_CK2" CHECK (DATA_TYPE IS NULL OR DATA_TYPE IN('VARCHAR2', 'DATE', 'NUMBER')) ENABLE;
  ALTER TABLE "PORTALMGR"."CONFIG_PARAMETERS" ADD CONSTRAINT "CONFIG_PARAMETERS_CK1" CHECK (PARAM_TYPE IS NOT NULL AND PARAM_TYPE IN('STANDARD', 'NULL', 'FUNCTION', 'LEGACY', 'DELETED', 'UNKNOWN')) ENABLE;
  ALTER TABLE "PORTALMGR"."CONFIG_PARAMETERS" MODIFY ("CREATED_DATETIME" NOT NULL ENABLE);
  ALTER TABLE "PORTALMGR"."CONFIG_PARAMETERS" MODIFY ("PARAM_ORDER" NOT NULL ENABLE);
  ALTER TABLE "PORTALMGR"."CONFIG_PARAMETERS" MODIFY ("PARAM_TYPE" NOT NULL ENABLE);
  ALTER TABLE "PORTALMGR"."CONFIG_PARAMETERS" MODIFY ("LAST_DML_BY" NOT NULL ENABLE);
  ALTER TABLE "PORTALMGR"."CONFIG_PARAMETERS" MODIFY ("LAST_DML_DATE" NOT NULL ENABLE);
