--------------------------------------------------------
--  Constraints for Table CONFIG_PARAMETERS
--------------------------------------------------------

  ALTER TABLE "SAVEMGR"."CONFIG_PARAMETERS" MODIFY ("LAST_DML_BY" NOT NULL ENABLE);
  ALTER TABLE "SAVEMGR"."CONFIG_PARAMETERS" MODIFY ("LAST_DML_DATE" NOT NULL ENABLE);
  ALTER TABLE "SAVEMGR"."CONFIG_PARAMETERS" MODIFY ("CREATED_DATETIME" NOT NULL ENABLE);
  ALTER TABLE "SAVEMGR"."CONFIG_PARAMETERS" MODIFY ("PARAM_TYPE" NOT NULL ENABLE);
  ALTER TABLE "SAVEMGR"."CONFIG_PARAMETERS" MODIFY ("PARAM_ORDER" NOT NULL ENABLE);
  ALTER TABLE "SAVEMGR"."CONFIG_PARAMETERS" MODIFY ("PARAM_DESCRIPTION" NOT NULL ENABLE);
  ALTER TABLE "SAVEMGR"."CONFIG_PARAMETERS" MODIFY ("PARAM_NAME" NOT NULL ENABLE);
