--------------------------------------------------------
--  Constraints for Table CONFIG_PARAMETERS_3
--------------------------------------------------------

  ALTER TABLE "SAVEMGR"."CONFIG_PARAMETERS_3" MODIFY ("PARAM_VISIBILITY" NOT NULL ENABLE);
  ALTER TABLE "SAVEMGR"."CONFIG_PARAMETERS_3" MODIFY ("LAST_DML_BY" NOT NULL ENABLE);
  ALTER TABLE "SAVEMGR"."CONFIG_PARAMETERS_3" MODIFY ("LAST_DML_DATE" NOT NULL ENABLE);
  ALTER TABLE "SAVEMGR"."CONFIG_PARAMETERS_3" MODIFY ("CREATED_DATETIME" NOT NULL ENABLE);
  ALTER TABLE "SAVEMGR"."CONFIG_PARAMETERS_3" MODIFY ("PARAM_TYPE" NOT NULL ENABLE);
  ALTER TABLE "SAVEMGR"."CONFIG_PARAMETERS_3" MODIFY ("PARAM_ORDER" NOT NULL ENABLE);
  ALTER TABLE "SAVEMGR"."CONFIG_PARAMETERS_3" MODIFY ("PARAM_DESCRIPTION" NOT NULL ENABLE);
  ALTER TABLE "SAVEMGR"."CONFIG_PARAMETERS_3" MODIFY ("PARAM_NAME" NOT NULL ENABLE);
