--------------------------------------------------------
--  Constraints for Table CONFIG_PARAMETERSP3800
--------------------------------------------------------

  ALTER TABLE "SAVEMGR"."CONFIG_PARAMETERSP3800" MODIFY ("LAST_DML_BY" NOT NULL ENABLE);
  ALTER TABLE "SAVEMGR"."CONFIG_PARAMETERSP3800" MODIFY ("LAST_DML_DATE" NOT NULL ENABLE);
  ALTER TABLE "SAVEMGR"."CONFIG_PARAMETERSP3800" MODIFY ("PARAM_VALUE" NOT NULL ENABLE);
  ALTER TABLE "SAVEMGR"."CONFIG_PARAMETERSP3800" MODIFY ("PARAM_DESCRIPTION" NOT NULL ENABLE);
  ALTER TABLE "SAVEMGR"."CONFIG_PARAMETERSP3800" MODIFY ("PARAM_NAME" NOT NULL ENABLE);
