--------------------------------------------------------
--  Constraints for Table COUNTRY_GROUP_DETAILS
--------------------------------------------------------

  ALTER TABLE "BPMMGR"."COUNTRY_GROUP_DETAILS" ADD CONSTRAINT "COUNTRY_GRP_DETAILS_UNIQUE_KEY" UNIQUE ("COUNTRY_GROUP_ID", "COUNTRY_SET_ID", "END_DATETIME")
  USING INDEX  ENABLE;
  ALTER TABLE "BPMMGR"."COUNTRY_GROUP_DETAILS" ADD CONSTRAINT "COUNTRY_GROUP_DETAILS_PK" PRIMARY KEY ("ID")
  USING INDEX  ENABLE;
  ALTER TABLE "BPMMGR"."COUNTRY_GROUP_DETAILS" MODIFY ("XML_DATA" NOT NULL ENABLE);
  ALTER TABLE "BPMMGR"."COUNTRY_GROUP_DETAILS" MODIFY ("START_DATETIME" NOT NULL ENABLE);
  ALTER TABLE "BPMMGR"."COUNTRY_GROUP_DETAILS" MODIFY ("COUNTRY_SET_ID" NOT NULL ENABLE);
  ALTER TABLE "BPMMGR"."COUNTRY_GROUP_DETAILS" MODIFY ("COUNTRY_GROUP_ID" NOT NULL ENABLE);
  ALTER TABLE "BPMMGR"."COUNTRY_GROUP_DETAILS" MODIFY ("ID" NOT NULL ENABLE);
