--------------------------------------------------------
--  Constraints for Table COUNTRY_SETS
--------------------------------------------------------

  ALTER TABLE "BPMMGR"."COUNTRY_SETS" ADD CONSTRAINT "COUNTRY_SETS_U01" UNIQUE ("COUNTRY_SET_NAME")
  USING INDEX  ENABLE;
  ALTER TABLE "BPMMGR"."COUNTRY_SETS" ADD CONSTRAINT "COUNTRY_SETS_PK" PRIMARY KEY ("COUNTRY_SET_ID")
  USING INDEX  ENABLE;
  ALTER TABLE "BPMMGR"."COUNTRY_SETS" MODIFY ("COUNTRY_SET_NAME" NOT NULL ENABLE);
  ALTER TABLE "BPMMGR"."COUNTRY_SETS" MODIFY ("COUNTRY_SET_ID" NOT NULL ENABLE);
