--------------------------------------------------------
--  Constraints for Table COUNTRY_GROUPS
--------------------------------------------------------

  ALTER TABLE "BPMMGR"."COUNTRY_GROUPS" ADD CONSTRAINT "COUNTRY_GROUPS_PK" PRIMARY KEY ("COUNTRY_GROUP_ID", "COUNTRY_SET_ID")
  USING INDEX  ENABLE;
  ALTER TABLE "BPMMGR"."COUNTRY_GROUPS" MODIFY ("COUNTRY_SET_ID" NOT NULL ENABLE);
  ALTER TABLE "BPMMGR"."COUNTRY_GROUPS" MODIFY ("COUNTRY_GROUP_ID" NOT NULL ENABLE);
