--------------------------------------------------------
--  Constraints for Table COUNTRIES
--------------------------------------------------------

  ALTER TABLE "BPMMGR"."COUNTRIES" ADD CONSTRAINT "COUNTRIES_UK1" UNIQUE ("ID")
  USING INDEX  ENABLE;
  ALTER TABLE "BPMMGR"."COUNTRIES" ADD CONSTRAINT "COUNTRIES_PK" PRIMARY KEY ("ID", "COUNTRY_SET_ID")
  USING INDEX  ENABLE;
  ALTER TABLE "BPMMGR"."COUNTRIES" MODIFY ("COUNTRY_SET_ID" NOT NULL ENABLE);
  ALTER TABLE "BPMMGR"."COUNTRIES" MODIFY ("ID" NOT NULL ENABLE);
