--------------------------------------------------------
--  Constraints for Table COUNTRY_DETAILS
--------------------------------------------------------

  ALTER TABLE "BPMMGR"."COUNTRY_DETAILS" ADD CONSTRAINT "COUNTRY_DETAILS_UNIQUE_KEY" UNIQUE ("COUNTRY_ID", "COUNTRY_SET_ID", "END_DATETIME")
  USING INDEX  ENABLE;
  ALTER TABLE "BPMMGR"."COUNTRY_DETAILS" ADD CONSTRAINT "COUNTRY_DETAILS_PK" PRIMARY KEY ("ID")
  USING INDEX  ENABLE;
  ALTER TABLE "BPMMGR"."COUNTRY_DETAILS" MODIFY ("START_DATETIME" NOT NULL ENABLE);
  ALTER TABLE "BPMMGR"."COUNTRY_DETAILS" MODIFY ("COUNTRY_SET_ID" NOT NULL ENABLE);
  ALTER TABLE "BPMMGR"."COUNTRY_DETAILS" MODIFY ("COUNTRY_ID" NOT NULL ENABLE);
  ALTER TABLE "BPMMGR"."COUNTRY_DETAILS" MODIFY ("ID" NOT NULL ENABLE);
