--------------------------------------------------------
--  Constraints for Table COUNTRY_RESTRICTIONS
--------------------------------------------------------

  ALTER TABLE "SPIREMGR"."COUNTRY_RESTRICTIONS" ADD CONSTRAINT "COUNTRY_RESTRICTIONS_CK1" CHECK (RESTRICTION_TYPE IN ('SANCTION')) ENABLE;
  ALTER TABLE "SPIREMGR"."COUNTRY_RESTRICTIONS" ADD CONSTRAINT "COUNTRY_RESTRICTIONS_PK1" PRIMARY KEY ("ID")
  USING INDEX  ENABLE;
  ALTER TABLE "SPIREMGR"."COUNTRY_RESTRICTIONS" MODIFY ("TITLE" NOT NULL ENABLE);
  ALTER TABLE "SPIREMGR"."COUNTRY_RESTRICTIONS" MODIFY ("COUNTRY_SET_ID" NOT NULL ENABLE);
  ALTER TABLE "SPIREMGR"."COUNTRY_RESTRICTIONS" MODIFY ("COUNTRY_ID" NOT NULL ENABLE);
  ALTER TABLE "SPIREMGR"."COUNTRY_RESTRICTIONS" MODIFY ("RESTRICTION_TYPE" NOT NULL ENABLE);
  ALTER TABLE "SPIREMGR"."COUNTRY_RESTRICTIONS" MODIFY ("SHORT_CODE" NOT NULL ENABLE);
  ALTER TABLE "SPIREMGR"."COUNTRY_RESTRICTIONS" MODIFY ("ID" NOT NULL ENABLE);
