--------------------------------------------------------
--  Constraints for Table COUNTRY_GROUP_ENTRIES
--------------------------------------------------------

  ALTER TABLE "SDBPUBMGR"."COUNTRY_GROUP_ENTRIES" ADD CONSTRAINT "COUNTRY_GROUP_ENTRIES_PK" PRIMARY KEY ("CG_ID", "COUNTRY_ID")
  USING INDEX  ENABLE;
  ALTER TABLE "SDBPUBMGR"."COUNTRY_GROUP_ENTRIES" MODIFY ("COUNTRY_ID" NOT NULL ENABLE);
  ALTER TABLE "SDBPUBMGR"."COUNTRY_GROUP_ENTRIES" MODIFY ("CG_ID" NOT NULL ENABLE);
