--------------------------------------------------------
--  Constraints for Table COUNTRY_LOADER_TEMP
--------------------------------------------------------

  ALTER TABLE "BPMMGR"."COUNTRY_LOADER_TEMP" ADD CONSTRAINT "COUNTRY_LOADER_TEMP_CK1" CHECK (/* Valid status values */ STATUS IN ('NEW','LOADED','ERROR')) ENABLE;
  ALTER TABLE "BPMMGR"."COUNTRY_LOADER_TEMP" ADD CONSTRAINT "COUNTRY_LOADER_TEMP_PK" PRIMARY KEY ("COUNTRY_NAME")
  USING INDEX  ENABLE;
  ALTER TABLE "BPMMGR"."COUNTRY_LOADER_TEMP" MODIFY ("UPDATED_DATE" NOT NULL ENABLE);
  ALTER TABLE "BPMMGR"."COUNTRY_LOADER_TEMP" MODIFY ("STATUS" NOT NULL ENABLE);
  ALTER TABLE "BPMMGR"."COUNTRY_LOADER_TEMP" MODIFY ("COUNTRY_NAME" NOT NULL ENABLE);
