--------------------------------------------------------
--  Constraints for Table DATAPATCH_SAR_MOVE2333
--------------------------------------------------------

  ALTER TABLE "SAVEMGR"."DATAPATCH_SAR_MOVE2333" MODIFY ("ELA_ID" NOT NULL ENABLE);
  ALTER TABLE "SAVEMGR"."DATAPATCH_SAR_MOVE2333" MODIFY ("CASE_DETAIL_ID" NOT NULL ENABLE);
  ALTER TABLE "SAVEMGR"."DATAPATCH_SAR_MOVE2333" MODIFY ("APP_DETAIL_ID" NOT NULL ENABLE);
