--------------------------------------------------------
--  Constraints for Table DATAPATCH_SAR_MOVE3649
--------------------------------------------------------

  ALTER TABLE "SAVEMGR"."DATAPATCH_SAR_MOVE3649" MODIFY ("ELA_ID" NOT NULL ENABLE);
  ALTER TABLE "SAVEMGR"."DATAPATCH_SAR_MOVE3649" MODIFY ("CASE_DETAIL_ID" NOT NULL ENABLE);
  ALTER TABLE "SAVEMGR"."DATAPATCH_SAR_MOVE3649" MODIFY ("APP_DETAIL_ID" NOT NULL ENABLE);
