--------------------------------------------------------
--  Constraints for Table DATAPATCH_SAR_MOVE_1403
--------------------------------------------------------

  ALTER TABLE "SAVEMGR"."DATAPATCH_SAR_MOVE_1403" MODIFY ("ELA_ID" NOT NULL ENABLE);
  ALTER TABLE "SAVEMGR"."DATAPATCH_SAR_MOVE_1403" MODIFY ("CASE_DETAIL_ID" NOT NULL ENABLE);
  ALTER TABLE "SAVEMGR"."DATAPATCH_SAR_MOVE_1403" MODIFY ("APP_DETAIL_ID" NOT NULL ENABLE);
