--------------------------------------------------------
--  Constraints for Table DATAPATCH_SAR_MOVE_4869
--------------------------------------------------------

  ALTER TABLE "SAVEMGR"."DATAPATCH_SAR_MOVE_4869" MODIFY ("ELA_ID" NOT NULL ENABLE);
  ALTER TABLE "SAVEMGR"."DATAPATCH_SAR_MOVE_4869" MODIFY ("CASE_DETAIL_ID" NOT NULL ENABLE);
  ALTER TABLE "SAVEMGR"."DATAPATCH_SAR_MOVE_4869" MODIFY ("APP_DETAIL_ID" NOT NULL ENABLE);
