--------------------------------------------------------
--  Constraints for Table DATAPATCH_SAR_MOVE_7178
--------------------------------------------------------

  ALTER TABLE "SAVEMGR"."DATAPATCH_SAR_MOVE_7178" MODIFY ("ELA_ID" NOT NULL ENABLE);
  ALTER TABLE "SAVEMGR"."DATAPATCH_SAR_MOVE_7178" MODIFY ("CASE_DETAIL_ID" NOT NULL ENABLE);
  ALTER TABLE "SAVEMGR"."DATAPATCH_SAR_MOVE_7178" MODIFY ("APP_DETAIL_ID" NOT NULL ENABLE);
