--------------------------------------------------------
--  Constraints for Table DATAPATCH_SAR_MOVE11023
--------------------------------------------------------

  ALTER TABLE "SAVEMGR"."DATAPATCH_SAR_MOVE11023" MODIFY ("ELA_ID" NOT NULL ENABLE);
  ALTER TABLE "SAVEMGR"."DATAPATCH_SAR_MOVE11023" MODIFY ("CASE_DETAIL_ID" NOT NULL ENABLE);
  ALTER TABLE "SAVEMGR"."DATAPATCH_SAR_MOVE11023" MODIFY ("APP_DETAIL_ID" NOT NULL ENABLE);
