--------------------------------------------------------
--  Constraints for Table DATAPATCH_SAR_MOVE_11037
--------------------------------------------------------

  ALTER TABLE "SAVEMGR"."DATAPATCH_SAR_MOVE_11037" MODIFY ("ELA_ID" NOT NULL ENABLE);
  ALTER TABLE "SAVEMGR"."DATAPATCH_SAR_MOVE_11037" MODIFY ("CASE_DETAIL_ID" NOT NULL ENABLE);
  ALTER TABLE "SAVEMGR"."DATAPATCH_SAR_MOVE_11037" MODIFY ("APP_DETAIL_ID" NOT NULL ENABLE);
