--------------------------------------------------------
--  Constraints for Table DATAPATCH000030_AP_BCK2
--------------------------------------------------------

  ALTER TABLE "SAVEMGR"."DATAPATCH000030_AP_BCK2" MODIFY ("STATUS" NOT NULL ENABLE);
  ALTER TABLE "SAVEMGR"."DATAPATCH000030_AP_BCK2" MODIFY ("LAST_UPDATED_DATETIME" NOT NULL ENABLE);
  ALTER TABLE "SAVEMGR"."DATAPATCH000030_AP_BCK2" MODIFY ("LAST_UPDATED_BY_WUA_ID" NOT NULL ENABLE);
  ALTER TABLE "SAVEMGR"."DATAPATCH000030_AP_BCK2" MODIFY ("CREATED_DATETIME" NOT NULL ENABLE);
  ALTER TABLE "SAVEMGR"."DATAPATCH000030_AP_BCK2" MODIFY ("CREATED_BY_WUA_ID" NOT NULL ENABLE);
  ALTER TABLE "SAVEMGR"."DATAPATCH000030_AP_BCK2" MODIFY ("NAME" NOT NULL ENABLE);
  ALTER TABLE "SAVEMGR"."DATAPATCH000030_AP_BCK2" MODIFY ("TYPE" NOT NULL ENABLE);
  ALTER TABLE "SAVEMGR"."DATAPATCH000030_AP_BCK2" MODIFY ("ID" NOT NULL ENABLE);
