--------------------------------------------------------
--  Constraints for Table DATAPATCH_SAR_MOVE_2034
--------------------------------------------------------

  ALTER TABLE "SAVEMGR"."DATAPATCH_SAR_MOVE_2034" MODIFY ("ELA_ID" NOT NULL ENABLE);
  ALTER TABLE "SAVEMGR"."DATAPATCH_SAR_MOVE_2034" MODIFY ("CASE_DETAIL_ID" NOT NULL ENABLE);
  ALTER TABLE "SAVEMGR"."DATAPATCH_SAR_MOVE_2034" MODIFY ("APP_DETAIL_ID" NOT NULL ENABLE);
