--------------------------------------------------------
--  Constraints for Table DATAPATCH_SAR_MOVE_14099
--------------------------------------------------------

  ALTER TABLE "SAVEMGR"."DATAPATCH_SAR_MOVE_14099" MODIFY ("ELA_ID" NOT NULL ENABLE);
  ALTER TABLE "SAVEMGR"."DATAPATCH_SAR_MOVE_14099" MODIFY ("CASE_DETAIL_ID" NOT NULL ENABLE);
  ALTER TABLE "SAVEMGR"."DATAPATCH_SAR_MOVE_14099" MODIFY ("APP_DETAIL_ID" NOT NULL ENABLE);
