--------------------------------------------------------
--  Constraints for Table DATAPATCH_SAR_MOVE_7485
--------------------------------------------------------

  ALTER TABLE "SAVEMGR"."DATAPATCH_SAR_MOVE_7485" MODIFY ("ELA_ID" NOT NULL ENABLE);
  ALTER TABLE "SAVEMGR"."DATAPATCH_SAR_MOVE_7485" MODIFY ("CASE_DETAIL_ID" NOT NULL ENABLE);
  ALTER TABLE "SAVEMGR"."DATAPATCH_SAR_MOVE_7485" MODIFY ("APP_DETAIL_ID" NOT NULL ENABLE);
