--------------------------------------------------------
--  Constraints for Table DATAPATCH_SAR_MOVE_3107
--------------------------------------------------------

  ALTER TABLE "SAVEMGR"."DATAPATCH_SAR_MOVE_3107" MODIFY ("ELA_ID" NOT NULL ENABLE);
  ALTER TABLE "SAVEMGR"."DATAPATCH_SAR_MOVE_3107" MODIFY ("CASE_DETAIL_ID" NOT NULL ENABLE);
  ALTER TABLE "SAVEMGR"."DATAPATCH_SAR_MOVE_3107" MODIFY ("APP_DETAIL_ID" NOT NULL ENABLE);
