--------------------------------------------------------
--  Constraints for Table DATAPATCH_SAR_MOVE_1626
--------------------------------------------------------

  ALTER TABLE "SAVEMGR"."DATAPATCH_SAR_MOVE_1626" MODIFY ("ELA_ID" NOT NULL ENABLE);
  ALTER TABLE "SAVEMGR"."DATAPATCH_SAR_MOVE_1626" MODIFY ("CASE_DETAIL_ID" NOT NULL ENABLE);
  ALTER TABLE "SAVEMGR"."DATAPATCH_SAR_MOVE_1626" MODIFY ("APP_DETAIL_ID" NOT NULL ENABLE);
