--------------------------------------------------------
--  Constraints for Table DATAPATCH_DELETE_DRAFT_RATINGS
--------------------------------------------------------

  ALTER TABLE "SAVEMGR"."DATAPATCH_DELETE_DRAFT_RATINGS" MODIFY ("STATUS" NOT NULL ENABLE);
  ALTER TABLE "SAVEMGR"."DATAPATCH_DELETE_DRAFT_RATINGS" MODIFY ("START_DATE" NOT NULL ENABLE);
  ALTER TABLE "SAVEMGR"."DATAPATCH_DELETE_DRAFT_RATINGS" MODIFY ("ELA_ID" NOT NULL ENABLE);
  ALTER TABLE "SAVEMGR"."DATAPATCH_DELETE_DRAFT_RATINGS" MODIFY ("ELA_DETAIL_ID" NOT NULL ENABLE);
