--------------------------------------------------------
--  Constraints for Table DATAPATCH_SAR_MOVE_4778
--------------------------------------------------------

  ALTER TABLE "SAVEMGR"."DATAPATCH_SAR_MOVE_4778" MODIFY ("ELA_ID" NOT NULL ENABLE);
  ALTER TABLE "SAVEMGR"."DATAPATCH_SAR_MOVE_4778" MODIFY ("CASE_DETAIL_ID" NOT NULL ENABLE);
  ALTER TABLE "SAVEMGR"."DATAPATCH_SAR_MOVE_4778" MODIFY ("APP_DETAIL_ID" NOT NULL ENABLE);
