--------------------------------------------------------
--  Constraints for Table DATAPATCH_SAR_MOVE_4255
--------------------------------------------------------

  ALTER TABLE "SAVEMGR"."DATAPATCH_SAR_MOVE_4255" MODIFY ("ELA_ID" NOT NULL ENABLE);
  ALTER TABLE "SAVEMGR"."DATAPATCH_SAR_MOVE_4255" MODIFY ("CASE_DETAIL_ID" NOT NULL ENABLE);
  ALTER TABLE "SAVEMGR"."DATAPATCH_SAR_MOVE_4255" MODIFY ("APP_DETAIL_ID" NOT NULL ENABLE);
