--------------------------------------------------------
--  Constraints for Table DATAPATCH_SAR_MOVE_5156
--------------------------------------------------------

  ALTER TABLE "SAVEMGR"."DATAPATCH_SAR_MOVE_5156" MODIFY ("ELA_ID" NOT NULL ENABLE);
  ALTER TABLE "SAVEMGR"."DATAPATCH_SAR_MOVE_5156" MODIFY ("CASE_DETAIL_ID" NOT NULL ENABLE);
  ALTER TABLE "SAVEMGR"."DATAPATCH_SAR_MOVE_5156" MODIFY ("APP_DETAIL_ID" NOT NULL ENABLE);
