--------------------------------------------------------
--  Constraints for Table DATAPATCH_DELETE_DRAFT_ELRE_TP
--------------------------------------------------------

  ALTER TABLE "SAVEMGR"."DATAPATCH_DELETE_DRAFT_ELRE_TP" MODIFY ("STATUS" NOT NULL ENABLE);
  ALTER TABLE "SAVEMGR"."DATAPATCH_DELETE_DRAFT_ELRE_TP" MODIFY ("LAST_UPDATED_DATETIME" NOT NULL ENABLE);
  ALTER TABLE "SAVEMGR"."DATAPATCH_DELETE_DRAFT_ELRE_TP" MODIFY ("LAST_UPDATED_BY_WUA_ID" NOT NULL ENABLE);
  ALTER TABLE "SAVEMGR"."DATAPATCH_DELETE_DRAFT_ELRE_TP" MODIFY ("CREATED_DATETIME" NOT NULL ENABLE);
  ALTER TABLE "SAVEMGR"."DATAPATCH_DELETE_DRAFT_ELRE_TP" MODIFY ("CREATED_BY_WUA_ID" NOT NULL ENABLE);
  ALTER TABLE "SAVEMGR"."DATAPATCH_DELETE_DRAFT_ELRE_TP" MODIFY ("NAME" NOT NULL ENABLE);
  ALTER TABLE "SAVEMGR"."DATAPATCH_DELETE_DRAFT_ELRE_TP" MODIFY ("TYPE" NOT NULL ENABLE);
  ALTER TABLE "SAVEMGR"."DATAPATCH_DELETE_DRAFT_ELRE_TP" MODIFY ("ID" NOT NULL ENABLE);
