--------------------------------------------------------
--  Constraints for Table DATAPATCH_SAR_MOVE_6913
--------------------------------------------------------

  ALTER TABLE "SAVEMGR"."DATAPATCH_SAR_MOVE_6913" MODIFY ("ELA_ID" NOT NULL ENABLE);
  ALTER TABLE "SAVEMGR"."DATAPATCH_SAR_MOVE_6913" MODIFY ("CASE_DETAIL_ID" NOT NULL ENABLE);
  ALTER TABLE "SAVEMGR"."DATAPATCH_SAR_MOVE_6913" MODIFY ("APP_DETAIL_ID" NOT NULL ENABLE);
