--------------------------------------------------------
--  Constraints for Table DATAPATCH_SAR_MOVE6432
--------------------------------------------------------

  ALTER TABLE "SAVEMGR"."DATAPATCH_SAR_MOVE6432" MODIFY ("ELA_ID" NOT NULL ENABLE);
  ALTER TABLE "SAVEMGR"."DATAPATCH_SAR_MOVE6432" MODIFY ("CASE_DETAIL_ID" NOT NULL ENABLE);
  ALTER TABLE "SAVEMGR"."DATAPATCH_SAR_MOVE6432" MODIFY ("APP_DETAIL_ID" NOT NULL ENABLE);
