--------------------------------------------------------
--  Constraints for Table DATAPATCH_SAR_MOVE_5680
--------------------------------------------------------

  ALTER TABLE "SAVEMGR"."DATAPATCH_SAR_MOVE_5680" MODIFY ("ELA_ID" NOT NULL ENABLE);
  ALTER TABLE "SAVEMGR"."DATAPATCH_SAR_MOVE_5680" MODIFY ("CASE_DETAIL_ID" NOT NULL ENABLE);
  ALTER TABLE "SAVEMGR"."DATAPATCH_SAR_MOVE_5680" MODIFY ("APP_DETAIL_ID" NOT NULL ENABLE);
