--------------------------------------------------------
--  Constraints for Table DATAPATCH_SAR_MOVE_4748
--------------------------------------------------------

  ALTER TABLE "SAVEMGR"."DATAPATCH_SAR_MOVE_4748" MODIFY ("ELA_ID" NOT NULL ENABLE);
  ALTER TABLE "SAVEMGR"."DATAPATCH_SAR_MOVE_4748" MODIFY ("CASE_DETAIL_ID" NOT NULL ENABLE);
  ALTER TABLE "SAVEMGR"."DATAPATCH_SAR_MOVE_4748" MODIFY ("APP_DETAIL_ID" NOT NULL ENABLE);
