--------------------------------------------------------
--  Constraints for Table DATAPATCH_SAR_MOVE8224
--------------------------------------------------------

  ALTER TABLE "SAVEMGR"."DATAPATCH_SAR_MOVE8224" MODIFY ("ELA_ID" NOT NULL ENABLE);
  ALTER TABLE "SAVEMGR"."DATAPATCH_SAR_MOVE8224" MODIFY ("CASE_DETAIL_ID" NOT NULL ENABLE);
  ALTER TABLE "SAVEMGR"."DATAPATCH_SAR_MOVE8224" MODIFY ("APP_DETAIL_ID" NOT NULL ENABLE);
