--------------------------------------------------------
--  Constraints for Table DATAPATCH_SAR_MOVE_11104
--------------------------------------------------------

  ALTER TABLE "SAVEMGR"."DATAPATCH_SAR_MOVE_11104" MODIFY ("ELA_ID" NOT NULL ENABLE);
  ALTER TABLE "SAVEMGR"."DATAPATCH_SAR_MOVE_11104" MODIFY ("CASE_DETAIL_ID" NOT NULL ENABLE);
  ALTER TABLE "SAVEMGR"."DATAPATCH_SAR_MOVE_11104" MODIFY ("APP_DETAIL_ID" NOT NULL ENABLE);
