--------------------------------------------------------
--  Constraints for Table DATAPATCH_SAR_MOVE_6659
--------------------------------------------------------

  ALTER TABLE "SAVEMGR"."DATAPATCH_SAR_MOVE_6659" MODIFY ("ELA_ID" NOT NULL ENABLE);
  ALTER TABLE "SAVEMGR"."DATAPATCH_SAR_MOVE_6659" MODIFY ("CASE_DETAIL_ID" NOT NULL ENABLE);
  ALTER TABLE "SAVEMGR"."DATAPATCH_SAR_MOVE_6659" MODIFY ("APP_DETAIL_ID" NOT NULL ENABLE);
