--------------------------------------------------------
--  Constraints for Table DATAPATCH_SAR_MOVE13302
--------------------------------------------------------

  ALTER TABLE "SAVEMGR"."DATAPATCH_SAR_MOVE13302" MODIFY ("ELA_ID" NOT NULL ENABLE);
  ALTER TABLE "SAVEMGR"."DATAPATCH_SAR_MOVE13302" MODIFY ("CASE_DETAIL_ID" NOT NULL ENABLE);
  ALTER TABLE "SAVEMGR"."DATAPATCH_SAR_MOVE13302" MODIFY ("APP_DETAIL_ID" NOT NULL ENABLE);
