--------------------------------------------------------
--  Constraints for Table DATAPATCH_SAR_MOVE_10434
--------------------------------------------------------

  ALTER TABLE "SAVEMGR"."DATAPATCH_SAR_MOVE_10434" MODIFY ("ELA_ID" NOT NULL ENABLE);
  ALTER TABLE "SAVEMGR"."DATAPATCH_SAR_MOVE_10434" MODIFY ("CASE_DETAIL_ID" NOT NULL ENABLE);
  ALTER TABLE "SAVEMGR"."DATAPATCH_SAR_MOVE_10434" MODIFY ("APP_DETAIL_ID" NOT NULL ENABLE);
