--------------------------------------------------------
--  Constraints for Table DATAPATCH_SAR_MOVE14611
--------------------------------------------------------

  ALTER TABLE "SAVEMGR"."DATAPATCH_SAR_MOVE14611" MODIFY ("ELA_ID" NOT NULL ENABLE);
  ALTER TABLE "SAVEMGR"."DATAPATCH_SAR_MOVE14611" MODIFY ("CASE_DETAIL_ID" NOT NULL ENABLE);
  ALTER TABLE "SAVEMGR"."DATAPATCH_SAR_MOVE14611" MODIFY ("APP_DETAIL_ID" NOT NULL ENABLE);
