--------------------------------------------------------
--  Constraints for Table DATAPATCH_SAR_MOVE_3193
--------------------------------------------------------

  ALTER TABLE "SAVEMGR"."DATAPATCH_SAR_MOVE_3193" MODIFY ("ELA_ID" NOT NULL ENABLE);
  ALTER TABLE "SAVEMGR"."DATAPATCH_SAR_MOVE_3193" MODIFY ("CASE_DETAIL_ID" NOT NULL ENABLE);
  ALTER TABLE "SAVEMGR"."DATAPATCH_SAR_MOVE_3193" MODIFY ("APP_DETAIL_ID" NOT NULL ENABLE);
