--------------------------------------------------------
--  Constraints for Table DATAPATCH_SAR_MOVE_16962
--------------------------------------------------------

  ALTER TABLE "SAVEMGR"."DATAPATCH_SAR_MOVE_16962" MODIFY ("ELA_ID" NOT NULL ENABLE);
  ALTER TABLE "SAVEMGR"."DATAPATCH_SAR_MOVE_16962" MODIFY ("CASE_DETAIL_ID" NOT NULL ENABLE);
  ALTER TABLE "SAVEMGR"."DATAPATCH_SAR_MOVE_16962" MODIFY ("APP_DETAIL_ID" NOT NULL ENABLE);
