--------------------------------------------------------
--  Constraints for Table DATAPATCH_SAR_MOVE_7271
--------------------------------------------------------

  ALTER TABLE "SAVEMGR"."DATAPATCH_SAR_MOVE_7271" MODIFY ("ELA_ID" NOT NULL ENABLE);
  ALTER TABLE "SAVEMGR"."DATAPATCH_SAR_MOVE_7271" MODIFY ("CASE_DETAIL_ID" NOT NULL ENABLE);
  ALTER TABLE "SAVEMGR"."DATAPATCH_SAR_MOVE_7271" MODIFY ("APP_DETAIL_ID" NOT NULL ENABLE);
