--------------------------------------------------------
--  Constraints for Table DATAPATCH_SAR_MOVE_11580
--------------------------------------------------------

  ALTER TABLE "SAVEMGR"."DATAPATCH_SAR_MOVE_11580" MODIFY ("ELA_ID" NOT NULL ENABLE);
  ALTER TABLE "SAVEMGR"."DATAPATCH_SAR_MOVE_11580" MODIFY ("CASE_DETAIL_ID" NOT NULL ENABLE);
  ALTER TABLE "SAVEMGR"."DATAPATCH_SAR_MOVE_11580" MODIFY ("APP_DETAIL_ID" NOT NULL ENABLE);
