--------------------------------------------------------
--  Constraints for Table DATAPATCH_SAR_MOVE_10624
--------------------------------------------------------

  ALTER TABLE "SAVEMGR"."DATAPATCH_SAR_MOVE_10624" MODIFY ("ELA_ID" NOT NULL ENABLE);
  ALTER TABLE "SAVEMGR"."DATAPATCH_SAR_MOVE_10624" MODIFY ("CASE_DETAIL_ID" NOT NULL ENABLE);
  ALTER TABLE "SAVEMGR"."DATAPATCH_SAR_MOVE_10624" MODIFY ("APP_DETAIL_ID" NOT NULL ENABLE);
