--------------------------------------------------------
--  Constraints for Table DATAPATCH_SAR_MOVE7495
--------------------------------------------------------

  ALTER TABLE "SAVEMGR"."DATAPATCH_SAR_MOVE7495" MODIFY ("ELA_ID" NOT NULL ENABLE);
  ALTER TABLE "SAVEMGR"."DATAPATCH_SAR_MOVE7495" MODIFY ("CASE_DETAIL_ID" NOT NULL ENABLE);
  ALTER TABLE "SAVEMGR"."DATAPATCH_SAR_MOVE7495" MODIFY ("APP_DETAIL_ID" NOT NULL ENABLE);
