--------------------------------------------------------
--  Constraints for Table DATAPATCH_SAR_MOVE11077
--------------------------------------------------------

  ALTER TABLE "SAVEMGR"."DATAPATCH_SAR_MOVE11077" MODIFY ("ELA_ID" NOT NULL ENABLE);
  ALTER TABLE "SAVEMGR"."DATAPATCH_SAR_MOVE11077" MODIFY ("CASE_DETAIL_ID" NOT NULL ENABLE);
  ALTER TABLE "SAVEMGR"."DATAPATCH_SAR_MOVE11077" MODIFY ("APP_DETAIL_ID" NOT NULL ENABLE);
