--------------------------------------------------------
--  Constraints for Table DATAPATCH_MEDIA_OIEL_TEMPLATES
--------------------------------------------------------

  ALTER TABLE "SAVEMGR"."DATAPATCH_MEDIA_OIEL_TEMPLATES" MODIFY ("STATUS" NOT NULL ENABLE);
  ALTER TABLE "SAVEMGR"."DATAPATCH_MEDIA_OIEL_TEMPLATES" MODIFY ("LAST_UPDATED_DATETIME" NOT NULL ENABLE);
  ALTER TABLE "SAVEMGR"."DATAPATCH_MEDIA_OIEL_TEMPLATES" MODIFY ("LAST_UPDATED_BY_WUA_ID" NOT NULL ENABLE);
  ALTER TABLE "SAVEMGR"."DATAPATCH_MEDIA_OIEL_TEMPLATES" MODIFY ("CREATED_DATETIME" NOT NULL ENABLE);
  ALTER TABLE "SAVEMGR"."DATAPATCH_MEDIA_OIEL_TEMPLATES" MODIFY ("CREATED_BY_WUA_ID" NOT NULL ENABLE);
  ALTER TABLE "SAVEMGR"."DATAPATCH_MEDIA_OIEL_TEMPLATES" MODIFY ("NAME" NOT NULL ENABLE);
  ALTER TABLE "SAVEMGR"."DATAPATCH_MEDIA_OIEL_TEMPLATES" MODIFY ("TYPE" NOT NULL ENABLE);
  ALTER TABLE "SAVEMGR"."DATAPATCH_MEDIA_OIEL_TEMPLATES" MODIFY ("ID" NOT NULL ENABLE);
