--------------------------------------------------------
--  Constraints for Table DENIAL_REPORTS
--------------------------------------------------------

  ALTER TABLE "SPIREMGR"."DENIAL_REPORTS" ADD CONSTRAINT "DENIAL_REPORTS_CK1" CHECK (status_control IN ('C', 'D', 'A')) ENABLE;
  ALTER TABLE "SPIREMGR"."DENIAL_REPORTS" ADD CONSTRAINT "DENIAL_REPORTS_PK" PRIMARY KEY ("ID")
  USING INDEX  ENABLE;
  ALTER TABLE "SPIREMGR"."DENIAL_REPORTS" MODIFY ("DATE_RUN" NOT NULL ENABLE);
  ALTER TABLE "SPIREMGR"."DENIAL_REPORTS" MODIFY ("CREATED_BY_WUA_ID" NOT NULL ENABLE);
  ALTER TABLE "SPIREMGR"."DENIAL_REPORTS" MODIFY ("ELA_GRP_UREF" NOT NULL ENABLE);
  ALTER TABLE "SPIREMGR"."DENIAL_REPORTS" MODIFY ("ID" NOT NULL ENABLE);
