--------------------------------------------------------
--  Constraints for Table DENIAL_LEGACY_ENTITIES
--------------------------------------------------------

  ALTER TABLE "SPMIGUSER"."DENIAL_LEGACY_ENTITIES" ADD CONSTRAINT "DENIAL_LEGACY_ENTITIES_UK1" UNIQUE ("LEGACY_DENIAL_CONSIGNEE_ID", "LEGACY_CHOSEN_ADDRESS_ID")
  USING INDEX (CREATE INDEX "SPMIGUSER"."DENIAL_LEGACY_ENTITIES_IDX1" ON "SPMIGUSER"."DENIAL_LEGACY_ENTITIES" ("LEGACY_DENIAL_CONSIGNEE_ID", "LEGACY_CHOSEN_ADDRESS_ID") 
  )  ENABLE;
  ALTER TABLE "SPMIGUSER"."DENIAL_LEGACY_ENTITIES" ADD CONSTRAINT "DENIAL_LEGACY_ENTITIES_CK1" CHECK (main_contact IS NULL AND contact_email IS NULL) ENABLE;
  ALTER TABLE "SPMIGUSER"."DENIAL_LEGACY_ENTITIES" MODIFY ("XML_DATA" NOT NULL ENABLE);
  ALTER TABLE "SPMIGUSER"."DENIAL_LEGACY_ENTITIES" MODIFY ("LEGACY_CHOSEN_ADDRESS_ID" NOT NULL ENABLE);
  ALTER TABLE "SPMIGUSER"."DENIAL_LEGACY_ENTITIES" MODIFY ("LEGACY_DENIAL_CONSIGNEE_ID" NOT NULL ENABLE);
