--------------------------------------------------------
--  Constraints for Table DENIAL_DETAILS
--------------------------------------------------------

  ALTER TABLE "SPIREMGR"."DENIAL_DETAILS" ADD CONSTRAINT "DENIAL_DETAILS_CK1" CHECK (status_control IS NULL OR status_control IN ('C', 'D', 'A')) ENABLE;
  ALTER TABLE "SPIREMGR"."DENIAL_DETAILS" ADD CONSTRAINT "DENIALS_DETAILS_PK" PRIMARY KEY ("ID")
  USING INDEX  ENABLE;
  ALTER TABLE "SPIREMGR"."DENIAL_DETAILS" MODIFY ("CREATED_BY_WUA_ID" NOT NULL ENABLE);
  ALTER TABLE "SPIREMGR"."DENIAL_DETAILS" MODIFY ("CREATED_BY_NAME" NOT NULL ENABLE);
  ALTER TABLE "SPIREMGR"."DENIAL_DETAILS" MODIFY ("CREATED_DATETIME" NOT NULL ENABLE);
