--------------------------------------------------------
--  Constraints for Table DIGITAL_CERTIFICATES
--------------------------------------------------------

  ALTER TABLE "DECMGR"."DIGITAL_CERTIFICATES" ADD CONSTRAINT "DIGITAL_CERTIFICATES_CK1" CHECK (certificate_file_type IN('PKCS7','PKIPATH', 'X509')) ENABLE;
  ALTER TABLE "DECMGR"."DIGITAL_CERTIFICATES" MODIFY ("CERTIFICATE_FILE_TYPE" NOT NULL ENABLE);
  ALTER TABLE "DECMGR"."DIGITAL_CERTIFICATES" ADD CONSTRAINT "DIGITAL_CERTIFICATES_PK" PRIMARY KEY ("ID")
  USING INDEX  ENABLE;
  ALTER TABLE "DECMGR"."DIGITAL_CERTIFICATES" MODIFY ("USAGE_WINDOW_START_DATE" NOT NULL ENABLE);
  ALTER TABLE "DECMGR"."DIGITAL_CERTIFICATES" MODIFY ("EXPIRY_DATE" NOT NULL ENABLE);
  ALTER TABLE "DECMGR"."DIGITAL_CERTIFICATES" MODIFY ("PRIVATE_KEY_FILE" NOT NULL ENABLE);
  ALTER TABLE "DECMGR"."DIGITAL_CERTIFICATES" MODIFY ("CERTIFICATE_FILE" NOT NULL ENABLE);
  ALTER TABLE "DECMGR"."DIGITAL_CERTIFICATES" MODIFY ("CERTIFICATE_NAME" NOT NULL ENABLE);
  ALTER TABLE "DECMGR"."DIGITAL_CERTIFICATES" MODIFY ("ID" NOT NULL ENABLE);
