--------------------------------------------------------
--  Constraints for Table DOCUMENT_INSTANCES
--------------------------------------------------------

  ALTER TABLE "DECMGR"."DOCUMENT_INSTANCES" ADD CONSTRAINT "PK_DOCUMENT_INSTANCES" PRIMARY KEY ("ID")
  USING INDEX  ENABLE;
  ALTER TABLE "DECMGR"."DOCUMENT_INSTANCES" MODIFY ("DP_ID" NOT NULL ENABLE);
  ALTER TABLE "DECMGR"."DOCUMENT_INSTANCES" MODIFY ("DISPLAY_SEQUENCE" NOT NULL ENABLE);
  ALTER TABLE "DECMGR"."DOCUMENT_INSTANCES" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "DECMGR"."DOCUMENT_INSTANCES" ADD CONSTRAINT "DOCUMENT_INSTANCES_CK4" CHECK (copy_of_di_id != id) ENABLE;
  ALTER TABLE "DECMGR"."DOCUMENT_INSTANCES" ADD CONSTRAINT "DOCUMENT_INSTANCES_CK3" CHECK (
    (status = 'COPY' AND copy_of_di_id IS NOT NULL AND metadata_xml IS NULL AND xml_data IS NULL)
    OR
    (status != 'COPY' AND metadata_xml IS NOT NULL)
  ) ENABLE;
  ALTER TABLE "DECMGR"."DOCUMENT_INSTANCES" ADD CONSTRAINT "DOCUMENT_INSTANCES_CK2" CHECK (
    (copy_of_di_id IS NULL)
    OR
    (copy_of_di_id IS NOT NULL AND status IS NOT NULL AND status IN ('COPY', 'COMPLETE'))
  ) ENABLE;
  ALTER TABLE "DECMGR"."DOCUMENT_INSTANCES" ADD CONSTRAINT "DOCUMENT_INSTANCES_CK1" CHECK (/* Valid status values */ status IN ('INCOMPLETE', 'BACKGROUND_INCOMPLETE', 'WARNING', 'COMPLETE', 'FAILED', 'COPY')) ENABLE;
