--------------------------------------------------------
--  Constraints for Table DOCUMENT_COMPOSITION_PACKS
--------------------------------------------------------

  ALTER TABLE "DECMGR"."DOCUMENT_COMPOSITION_PACKS" ADD CONSTRAINT "DOCUMENT_COMP_PACKS_UK" UNIQUE ("ID", "DS_ID")
  USING INDEX (CREATE UNIQUE INDEX "DECMGR"."DOCUMENT_COMP_PACKS_UK_IDX1" ON "DECMGR"."DOCUMENT_COMPOSITION_PACKS" ("ID", "DS_ID") 
  )  ENABLE;
  ALTER TABLE "DECMGR"."DOCUMENT_COMPOSITION_PACKS" ADD CONSTRAINT "DOCUMENT_COMPOSITION_PACKS_PK" PRIMARY KEY ("ID")
  USING INDEX  ENABLE;
  ALTER TABLE "DECMGR"."DOCUMENT_COMPOSITION_PACKS" MODIFY ("DS_ID" NOT NULL ENABLE);
  ALTER TABLE "DECMGR"."DOCUMENT_COMPOSITION_PACKS" MODIFY ("ID" NOT NULL ENABLE);
