--------------------------------------------------------
--  Constraints for Table DOCUMENT_DATA
--------------------------------------------------------

  ALTER TABLE "DECMGR"."DOCUMENT_DATA" ADD CONSTRAINT "DOCUMENT_DATA_UK1" UNIQUE ("DD_IMMUTABLE_ID")
  USING INDEX  ENABLE;
  ALTER TABLE "DECMGR"."DOCUMENT_DATA" ADD CONSTRAINT "PK_DOCUMENT_DATA" PRIMARY KEY ("ID")
  USING INDEX  ENABLE;
  ALTER TABLE "DECMGR"."DOCUMENT_DATA" ADD CONSTRAINT "DOCUMENT_DATA_CK2" CHECK (/* Check all signed columns are set or unset correctly */  DECODE(STATUS, 'SIGNED', 1, 0) +  DECODE(SIGNED_BY, NULL, 0, 1) +  DECODE(SIGNED_DATETIME, NULL, 0, 1) IN (0, 3)) DISABLE;
  ALTER TABLE "DECMGR"."DOCUMENT_DATA" ADD CONSTRAINT "DOCUMENT_DATA_CK1" CHECK (/* Valid status values */ STATUS IN ('INCOMPLETE', 'WARNING', 'COMPLETE', 'SIGNED')) ENABLE;
  ALTER TABLE "DECMGR"."DOCUMENT_DATA" ADD CONSTRAINT "DOCUMENT_DATA_CK3" CHECK (/* Immutable key compminations and status */ DD_IMMUTABLE_ID IS NULL OR (DD_IMMUTABLE_ID = ID AND STATUS IN ('COMPLETE', 'SIGNED'))) ENABLE;
  ALTER TABLE "DECMGR"."DOCUMENT_DATA" MODIFY ("METADATA_XML" NOT NULL ENABLE);
  ALTER TABLE "DECMGR"."DOCUMENT_DATA" MODIFY ("CREATED_DATETIME" NOT NULL ENABLE);
  ALTER TABLE "DECMGR"."DOCUMENT_DATA" MODIFY ("CREATED_BY" NOT NULL ENABLE);
  ALTER TABLE "DECMGR"."DOCUMENT_DATA" MODIFY ("STATUS" NOT NULL ENABLE);
  ALTER TABLE "DECMGR"."DOCUMENT_DATA" MODIFY ("DI_ID" NOT NULL ENABLE);
  ALTER TABLE "DECMGR"."DOCUMENT_DATA" MODIFY ("ID" NOT NULL ENABLE);
