--------------------------------------------------------
--  Constraints for Table DOCUMENT_PACKS
--------------------------------------------------------

  ALTER TABLE "DECMGR"."DOCUMENT_PACKS" ADD CONSTRAINT "PK_DOCUMENT_PACKS" PRIMARY KEY ("ID")
  USING INDEX  ENABLE;
  ALTER TABLE "DECMGR"."DOCUMENT_PACKS" ADD CHECK ("XML_DATA" IS NOT NULL) ENABLE;
  ALTER TABLE "DECMGR"."DOCUMENT_PACKS" MODIFY ("XML_DATA" CONSTRAINT "SYS_C0010563" NOT NULL ENABLE);
  ALTER TABLE "DECMGR"."DOCUMENT_PACKS" MODIFY ("DS_ID" NOT NULL ENABLE);
  ALTER TABLE "DECMGR"."DOCUMENT_PACKS" MODIFY ("ID" NOT NULL ENABLE);
