--------------------------------------------------------
--  Constraints for Table DOCUMENT_SETS
--------------------------------------------------------

  ALTER TABLE "DECMGR"."DOCUMENT_SETS" ADD CONSTRAINT "PK_DOCUMENT_SETS" PRIMARY KEY ("ID")
  USING INDEX  ENABLE;
  ALTER TABLE "DECMGR"."DOCUMENT_SETS" ADD CHECK ("XML_DATA" IS NOT NULL) ENABLE;
  ALTER TABLE "DECMGR"."DOCUMENT_SETS" MODIFY ("XML_DATA" CONSTRAINT "SYS_C0010548" NOT NULL ENABLE);
  ALTER TABLE "DECMGR"."DOCUMENT_SETS" MODIFY ("ID" NOT NULL ENABLE);
