--------------------------------------------------------
--  Constraints for Table DOCUMENT_COMPOSITIONS
--------------------------------------------------------

  ALTER TABLE "DECMGR"."DOCUMENT_COMPOSITIONS" ADD CONSTRAINT "DOCUMENT_COMPOSITIONS_PK" PRIMARY KEY ("ID")
  USING INDEX  ENABLE;
  ALTER TABLE "DECMGR"."DOCUMENT_COMPOSITIONS" MODIFY ("XML_DATA" NOT NULL ENABLE);
  ALTER TABLE "DECMGR"."DOCUMENT_COMPOSITIONS" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "DECMGR"."DOCUMENT_COMPOSITIONS" ADD CONSTRAINT "DOCUMENT_COMPOSITIONS_UK" UNIQUE ("ID", "DS_ID")
  USING INDEX (CREATE UNIQUE INDEX "DECMGR"."DOCUMENT_COMPOSITIONS_UK_IDX1" ON "DECMGR"."DOCUMENT_COMPOSITIONS" ("ID", "DS_ID") 
  )  ENABLE;
