--------------------------------------------------------
--  Constraints for Table DOMAIN_SEVERITY_RECIPIENT
--------------------------------------------------------

  ALTER TABLE "FOXMGR"."DOMAIN_SEVERITY_RECIPIENT" ADD CONSTRAINT "DSR_CK1" CHECK (email IN ('true','false') AND sms IN ('true','false')) ENABLE;
  ALTER TABLE "FOXMGR"."DOMAIN_SEVERITY_RECIPIENT" ADD CONSTRAINT "DSR_UK1" UNIQUE ("DOMAIN", "SEVERITY", "PERSON_ID")
  USING INDEX  ENABLE;
  ALTER TABLE "FOXMGR"."DOMAIN_SEVERITY_RECIPIENT" ADD CONSTRAINT "DSR_PK1" PRIMARY KEY ("ID")
  USING INDEX  ENABLE;
  ALTER TABLE "FOXMGR"."DOMAIN_SEVERITY_RECIPIENT" MODIFY ("SMS" NOT NULL ENABLE);
  ALTER TABLE "FOXMGR"."DOMAIN_SEVERITY_RECIPIENT" MODIFY ("EMAIL" NOT NULL ENABLE);
  ALTER TABLE "FOXMGR"."DOMAIN_SEVERITY_RECIPIENT" MODIFY ("PERSON_ID" NOT NULL ENABLE);
  ALTER TABLE "FOXMGR"."DOMAIN_SEVERITY_RECIPIENT" MODIFY ("SEVERITY" NOT NULL ENABLE);
  ALTER TABLE "FOXMGR"."DOMAIN_SEVERITY_RECIPIENT" MODIFY ("DOMAIN" NOT NULL ENABLE);
