--------------------------------------------------------
--  Constraints for Table EDI_EXTRACT_RESPONSE_LINES
--------------------------------------------------------

  ALTER TABLE "HMRCMGR"."EDI_EXTRACT_RESPONSE_LINES" ADD CONSTRAINT "EDI_EXTRACT_RESPONSE_LINES_CK2" CHECK (
  (status IN ('Accepted','Rejected') AND eld_id IS NOT NULL)
  OR
  (status = 'fileError' AND eld_id IS NULL)
) ENABLE;
  ALTER TABLE "HMRCMGR"."EDI_EXTRACT_RESPONSE_LINES" ADD CONSTRAINT "EDI_EXTRACT_RESPONSE_LINES_CK1" CHECK (status IN ('Accepted', 'Rejected', 'fileError')) ENABLE;
  ALTER TABLE "HMRCMGR"."EDI_EXTRACT_RESPONSE_LINES" ADD CONSTRAINT "EDI_EXTRACT_RESPONSE_LINES_PK" PRIMARY KEY ("TRANSMISSION_ID", "TRANSMISSION_SET", "LINE_NUMBER")
  USING INDEX  ENABLE;
  ALTER TABLE "HMRCMGR"."EDI_EXTRACT_RESPONSE_LINES" MODIFY ("STATUS" NOT NULL ENABLE);
  ALTER TABLE "HMRCMGR"."EDI_EXTRACT_RESPONSE_LINES" ADD CONSTRAINT "EDI_EXTRACT_RESPONSE_LINES_CK4" CHECK (resent_flag IS NULL OR (NVL(request_resend, 'N') = 'Y' AND resent_flag = 'Y')) ENABLE;
  ALTER TABLE "HMRCMGR"."EDI_EXTRACT_RESPONSE_LINES" ADD CONSTRAINT "EDI_EXTRACT_RESPONSE_LINES_CK3" CHECK (request_resend IS NULL OR (NVL(request_resend, 'N') = 'Y' AND status = 'Rejected')) ENABLE;
