--------------------------------------------------------
--  Constraints for Table ELA_TEMPLATE_TYPE
--------------------------------------------------------

  ALTER TABLE "SPIREMGR"."ELA_TEMPLATE_TYPE" ADD CONSTRAINT "ELA_TMPL_TYPE_AUTO_LOAD_CK2" CHECK ((AUTO_LOAD_YN = 'Y' AND MAX_PUBLISHED_TEMPLATES = 1) OR AUTO_LOAD_YN = 'N') ENABLE;
  ALTER TABLE "SPIREMGR"."ELA_TEMPLATE_TYPE" ADD CONSTRAINT "ELA_TEMPL_TYPE_AUTO_LOAD_CK1" CHECK (AUTO_LOAD_YN IN ('Y', 'N')) ENABLE;
  ALTER TABLE "SPIREMGR"."ELA_TEMPLATE_TYPE" ADD CONSTRAINT "ELA_TEMPLATE_TYPE_UK1" UNIQUE ("TYPE", "SUBTYPE")
  USING INDEX  ENABLE;
  ALTER TABLE "SPIREMGR"."ELA_TEMPLATE_TYPE" MODIFY ("TEMPLATE_TITLE" NOT NULL ENABLE);
  ALTER TABLE "SPIREMGR"."ELA_TEMPLATE_TYPE" MODIFY ("AUTO_LOAD_YN" NOT NULL ENABLE);
  ALTER TABLE "SPIREMGR"."ELA_TEMPLATE_TYPE" MODIFY ("MAX_PUBLISHED_TEMPLATES" NOT NULL ENABLE);
  ALTER TABLE "SPIREMGR"."ELA_TEMPLATE_TYPE" MODIFY ("MIN_PUBLISHED_TEMPLATES" NOT NULL ENABLE);
  ALTER TABLE "SPIREMGR"."ELA_TEMPLATE_TYPE" MODIFY ("TYPE" NOT NULL ENABLE);
