--------------------------------------------------------
--  Constraints for Table ELC_CONS_RATING
--------------------------------------------------------

  ALTER TABLE "WARP_OWNER"."ELC_CONS_RATING" ADD CONSTRAINT "ELC_CONS_RATING_PK" PRIMARY KEY ("RATING_ID", "DETAIL_ID")
  USING INDEX  ENABLE;
  ALTER TABLE "WARP_OWNER"."ELC_CONS_RATING" MODIFY ("PERSON_RATING" NOT NULL ENABLE);
  ALTER TABLE "WARP_OWNER"."ELC_CONS_RATING" MODIFY ("LICENCE_REQUIRED" NOT NULL ENABLE);
  ALTER TABLE "WARP_OWNER"."ELC_CONS_RATING" MODIFY ("EMBARGO_STATUS" NOT NULL ENABLE);
  ALTER TABLE "WARP_OWNER"."ELC_CONS_RATING" MODIFY ("RATING_ID" NOT NULL ENABLE);
  ALTER TABLE "WARP_OWNER"."ELC_CONS_RATING" MODIFY ("DETAIL_ID" NOT NULL ENABLE);
