--------------------------------------------------------
--  Constraints for Table ELC_CONS_DETAIL
--------------------------------------------------------

  ALTER TABLE "WARP_OWNER"."ELC_CONS_DETAIL" ADD CONSTRAINT "ELC_CONS_DETAIL_PK" PRIMARY KEY ("DETAIL_ID", "CASE_ID")
  USING INDEX  ENABLE;
  ALTER TABLE "WARP_OWNER"."ELC_CONS_DETAIL" MODIFY ("MODEL_NO_TYPE" NOT NULL ENABLE);
  ALTER TABLE "WARP_OWNER"."ELC_CONS_DETAIL" MODIFY ("CASE_ID" NOT NULL ENABLE);
  ALTER TABLE "WARP_OWNER"."ELC_CONS_DETAIL" MODIFY ("DETAIL_ID" NOT NULL ENABLE);
