--------------------------------------------------------
--  Constraints for Table ELC_COMMENT
--------------------------------------------------------

  ALTER TABLE "WARP_OWNER"."ELC_COMMENT" MODIFY ("DATE_TIME" NOT NULL ENABLE);
  ALTER TABLE "WARP_OWNER"."ELC_COMMENT" MODIFY ("USER_ID" NOT NULL ENABLE);
  ALTER TABLE "WARP_OWNER"."ELC_COMMENT" MODIFY ("TEXT_ID" NOT NULL ENABLE);
  ALTER TABLE "WARP_OWNER"."ELC_COMMENT" MODIFY ("TYPE" NOT NULL ENABLE);
  ALTER TABLE "WARP_OWNER"."ELC_COMMENT" MODIFY ("CASE_CONS_ID" NOT NULL ENABLE);
