--------------------------------------------------------
--  Constraints for Table ELC_CASE
--------------------------------------------------------

  ALTER TABLE "WARP_OWNER"."ELC_CASE" ADD CONSTRAINT "ELC_CASES_PK_ID" PRIMARY KEY ("CASE_ID")
  USING INDEX  ENABLE;
  ALTER TABLE "WARP_OWNER"."ELC_CASE" MODIFY ("REF_NO" NOT NULL ENABLE);
  ALTER TABLE "WARP_OWNER"."ELC_CASE" MODIFY ("TYPE" NOT NULL ENABLE);
  ALTER TABLE "WARP_OWNER"."ELC_CASE" MODIFY ("YEAR" NOT NULL ENABLE);
  ALTER TABLE "WARP_OWNER"."ELC_CASE" MODIFY ("CASE_ID" NOT NULL ENABLE);
