--------------------------------------------------------
--  Constraints for Table ELR_REMINDER_LOG_DETAILS
--------------------------------------------------------

  ALTER TABLE "SPIREMGR"."ELR_REMINDER_LOG_DETAILS" ADD CONSTRAINT "ELR_REMINDER_LOG_DETAILS_PK" PRIMARY KEY ("ID")
  USING INDEX  ENABLE;
  ALTER TABLE "SPIREMGR"."ELR_REMINDER_LOG_DETAILS" MODIFY ("XML_DATA" NOT NULL ENABLE);
  ALTER TABLE "SPIREMGR"."ELR_REMINDER_LOG_DETAILS" MODIFY ("ERL_ID" NOT NULL ENABLE);
