--------------------------------------------------------
--  Constraints for Table ELR_REMINDER_TYPES
--------------------------------------------------------

  ALTER TABLE "SPIREMGR"."ELR_REMINDER_TYPES" ADD CONSTRAINT "ELR_REMINDER_TYPES_PK" PRIMARY KEY ("REMINDER_TYPE")
  USING INDEX  ENABLE;
  ALTER TABLE "SPIREMGR"."ELR_REMINDER_TYPES" MODIFY ("DAYS_OFFSET" NOT NULL ENABLE);
  ALTER TABLE "SPIREMGR"."ELR_REMINDER_TYPES" MODIFY ("BODY" NOT NULL ENABLE);
  ALTER TABLE "SPIREMGR"."ELR_REMINDER_TYPES" MODIFY ("SUBJECT" NOT NULL ENABLE);
  ALTER TABLE "SPIREMGR"."ELR_REMINDER_TYPES" MODIFY ("REMINDER_TYPE" NOT NULL ENABLE);
