--------------------------------------------------------
--  Constraints for Table EMAIL_REMINDER_LOGS
--------------------------------------------------------

  ALTER TABLE "SPIREMGR"."EMAIL_REMINDER_LOGS" ADD CONSTRAINT "EMAIL_REMINDER_LOGS_PK" PRIMARY KEY ("ID")
  USING INDEX  ENABLE;
  ALTER TABLE "SPIREMGR"."EMAIL_REMINDER_LOGS" MODIFY ("CREATED_DATETIME" NOT NULL ENABLE);
  ALTER TABLE "SPIREMGR"."EMAIL_REMINDER_LOGS" MODIFY ("PURPOSE" NOT NULL ENABLE);
  ALTER TABLE "SPIREMGR"."EMAIL_REMINDER_LOGS" MODIFY ("UREF" NOT NULL ENABLE);
  ALTER TABLE "SPIREMGR"."EMAIL_REMINDER_LOGS" MODIFY ("ID" NOT NULL ENABLE);
