--------------------------------------------------------
--  Constraints for Table EMAIL_RECIPIENTS
--------------------------------------------------------

  ALTER TABLE "PORTALMGR"."EMAIL_RECIPIENTS" MODIFY ("LAST_DML_BY" NOT NULL ENABLE);
  ALTER TABLE "PORTALMGR"."EMAIL_RECIPIENTS" MODIFY ("LAST_DML_DATE" NOT NULL ENABLE);
  ALTER TABLE "PORTALMGR"."EMAIL_RECIPIENTS" MODIFY ("FIRST_REQUESTED_BY" NOT NULL ENABLE);
  ALTER TABLE "PORTALMGR"."EMAIL_RECIPIENTS" MODIFY ("FIRST_REQUESTED_DATE" NOT NULL ENABLE);
  ALTER TABLE "PORTALMGR"."EMAIL_RECIPIENTS" MODIFY ("EMAIL_ADDRESSEE" NOT NULL ENABLE);
  ALTER TABLE "PORTALMGR"."EMAIL_RECIPIENTS" MODIFY ("ID" NOT NULL ENABLE);
