--------------------------------------------------------
--  Constraints for Table EMAIL_ROUND_TRIP_ENVIRONMENTS
--------------------------------------------------------

  ALTER TABLE "SERVICEMGR"."EMAIL_ROUND_TRIP_ENVIRONMENTS" ADD CONSTRAINT "ERT_ENVIRONMENTS_PK1" PRIMARY KEY ("ID")
  USING INDEX  ENABLE;
  ALTER TABLE "SERVICEMGR"."EMAIL_ROUND_TRIP_ENVIRONMENTS" ADD CONSTRAINT "ERT_ENVIRONMENTS_CK4" CHECK (system = upper(system)) ENABLE;
  ALTER TABLE "SERVICEMGR"."EMAIL_ROUND_TRIP_ENVIRONMENTS" ADD CONSTRAINT "ERT_ENVIRONMENTS_CK3" CHECK (
    (environment_type IN ('INBOUND_OUTBOUND', 'MASTER') AND email_address IS NOT NULL)
    OR (environment_type = 'OUTBOUND_ONLY' AND email_address IS NULL)
  ) ENABLE;
  ALTER TABLE "SERVICEMGR"."EMAIL_ROUND_TRIP_ENVIRONMENTS" ADD CONSTRAINT "ERT_ENVIRONMENTS_CK2" CHECK (status IN ('CURRENT', 'ARCHIVED')) ENABLE;
  ALTER TABLE "SERVICEMGR"."EMAIL_ROUND_TRIP_ENVIRONMENTS" ADD CONSTRAINT "ERT_ENVIRONMENTS_CK1" CHECK (environment_type IN ('INBOUND_OUTBOUND', 'OUTBOUND_ONLY', 'MASTER')) ENABLE;
  ALTER TABLE "SERVICEMGR"."EMAIL_ROUND_TRIP_ENVIRONMENTS" MODIFY ("STATUS" NOT NULL ENABLE);
  ALTER TABLE "SERVICEMGR"."EMAIL_ROUND_TRIP_ENVIRONMENTS" MODIFY ("DATABASE" NOT NULL ENABLE);
  ALTER TABLE "SERVICEMGR"."EMAIL_ROUND_TRIP_ENVIRONMENTS" MODIFY ("SYSTEM" NOT NULL ENABLE);
  ALTER TABLE "SERVICEMGR"."EMAIL_ROUND_TRIP_ENVIRONMENTS" MODIFY ("ENVIRONMENT" NOT NULL ENABLE);
  ALTER TABLE "SERVICEMGR"."EMAIL_ROUND_TRIP_ENVIRONMENTS" MODIFY ("ENVIRONMENT_TYPE" NOT NULL ENABLE);
