--------------------------------------------------------
--  Constraints for Table EMAIL_ROUND_TRIP_LOGS
--------------------------------------------------------

  ALTER TABLE "SERVICEMGR"."EMAIL_ROUND_TRIP_LOGS" ADD CONSTRAINT "ERT_LOGS_PK1" PRIMARY KEY ("ID")
  USING INDEX  ENABLE;
  ALTER TABLE "SERVICEMGR"."EMAIL_ROUND_TRIP_LOGS" ADD CONSTRAINT "ERT_LOGS_CK4" CHECK (
    (status IN ('AWAITING_RESPONSE', 'OUTBOUND_ONLY_STUB', 'IGNORE', 'ALERTED') AND received_timestamp IS NULL)
    OR (status = 'RECEIVED' AND received_timestamp IS NOT NULL)
  ) ENABLE;
  ALTER TABLE "SERVICEMGR"."EMAIL_ROUND_TRIP_LOGS" ADD CONSTRAINT "ERT_LOGS_CK3" CHECK (
    (environment_type = 'INBOUND_OUTBOUND' AND email_address IS NOT NULL)
    OR (environment_type = 'OUTBOUND_ONLY' AND email_address IS NULL)
  ) ENABLE;
  ALTER TABLE "SERVICEMGR"."EMAIL_ROUND_TRIP_LOGS" ADD CONSTRAINT "ERT_LOGS_CK2" CHECK (status IN ('AWAITING_RESPONSE', 'OUTBOUND_ONLY_STUB', 'RECEIVED', 'IGNORE', 'ALERTED')) ENABLE;
  ALTER TABLE "SERVICEMGR"."EMAIL_ROUND_TRIP_LOGS" ADD CONSTRAINT "ERT_LOGS_CK1" CHECK (environment_type IN ('INBOUND_OUTBOUND', 'OUTBOUND_ONLY')) ENABLE;
  ALTER TABLE "SERVICEMGR"."EMAIL_ROUND_TRIP_LOGS" MODIFY ("CREATED_TIMESTAMP" NOT NULL ENABLE);
  ALTER TABLE "SERVICEMGR"."EMAIL_ROUND_TRIP_LOGS" MODIFY ("STATUS" NOT NULL ENABLE);
  ALTER TABLE "SERVICEMGR"."EMAIL_ROUND_TRIP_LOGS" MODIFY ("ERT_LOG_CODE" NOT NULL ENABLE);
  ALTER TABLE "SERVICEMGR"."EMAIL_ROUND_TRIP_LOGS" MODIFY ("ENVIRONMENT_TYPE" NOT NULL ENABLE);
  ALTER TABLE "SERVICEMGR"."EMAIL_ROUND_TRIP_LOGS" MODIFY ("ERTE_ID" NOT NULL ENABLE);
