--------------------------------------------------------
--  Constraints for Table EMAIL_DOMAINS
--------------------------------------------------------

  ALTER TABLE "SECUREMGR"."EMAIL_DOMAINS" ADD UNIQUE ("DOMAIN_NAME")
  USING INDEX  ENABLE;
  ALTER TABLE "SECUREMGR"."EMAIL_DOMAINS" ADD PRIMARY KEY ("DOMAIN_ID")
  USING INDEX  ENABLE;
  ALTER TABLE "SECUREMGR"."EMAIL_DOMAINS" ADD CONSTRAINT "EMAIL_DOMAINS_CK4" CHECK (allow_duplicate_logins IN ('ALLOW','FORBID')) ENABLE;
  ALTER TABLE "SECUREMGR"."EMAIL_DOMAINS" ADD CONSTRAINT "EMAIL_DOMAINS_CK3" CHECK (allow_self_registration IN ('ALLOW','QA-REQUIRED','FORBID')) ENABLE;
  ALTER TABLE "SECUREMGR"."EMAIL_DOMAINS" ADD CONSTRAINT "EMAIL_DOMAINS_CK2" CHECK (auto_approve IN ('Y','N')) ENABLE;
  ALTER TABLE "SECUREMGR"."EMAIL_DOMAINS" ADD CONSTRAINT "EMAIL_DOMAINS_CK1" CHECK (auto_offer_for_wua_roles IN ('Y','N')) ENABLE;
  ALTER TABLE "SECUREMGR"."EMAIL_DOMAINS" MODIFY ("LAST_DML_DATE" NOT NULL ENABLE);
  ALTER TABLE "SECUREMGR"."EMAIL_DOMAINS" MODIFY ("LAST_DML_BY" NOT NULL ENABLE);
  ALTER TABLE "SECUREMGR"."EMAIL_DOMAINS" MODIFY ("PERSON_TYPE" NOT NULL ENABLE);
  ALTER TABLE "SECUREMGR"."EMAIL_DOMAINS" MODIFY ("DOMAIN_NAME" NOT NULL ENABLE);
