--------------------------------------------------------
--  Constraints for Table ERROR_CODES
--------------------------------------------------------

  ALTER TABLE "PORTALMGR"."ERROR_CODES" ADD CONSTRAINT "ERC_PK" PRIMARY KEY ("ERROR_NUMBER")
  USING INDEX  ENABLE;
  ALTER TABLE "PORTALMGR"."ERROR_CODES" MODIFY ("LAST_DML_BY" NOT NULL ENABLE);
  ALTER TABLE "PORTALMGR"."ERROR_CODES" MODIFY ("LAST_DML_DATE" NOT NULL ENABLE);
  ALTER TABLE "PORTALMGR"."ERROR_CODES" MODIFY ("DESCRIPTION" NOT NULL ENABLE);
  ALTER TABLE "PORTALMGR"."ERROR_CODES" MODIFY ("ERROR_TYPE" NOT NULL ENABLE);
  ALTER TABLE "PORTALMGR"."ERROR_CODES" MODIFY ("ERROR_NUMBER" NOT NULL ENABLE);
