--------------------------------------------------------
--  Constraints for Table EVENTS
--------------------------------------------------------

  ALTER TABLE "BPMMGR"."EVENTS" ADD CONSTRAINT "EVENTS_PK" PRIMARY KEY ("ID")
  USING INDEX  ENABLE;
  ALTER TABLE "BPMMGR"."EVENTS" MODIFY ("RAISING_MODULE_CODE" NOT NULL ENABLE);
  ALTER TABLE "BPMMGR"."EVENTS" MODIFY ("RAISING_WUA_ID" NOT NULL ENABLE);
  ALTER TABLE "BPMMGR"."EVENTS" MODIFY ("EVENT_LABEL" NOT NULL ENABLE);
  ALTER TABLE "BPMMGR"."EVENTS" MODIFY ("EVENT_DATETIME" NOT NULL ENABLE);
  ALTER TABLE "BPMMGR"."EVENTS" MODIFY ("ID" NOT NULL ENABLE);
