--------------------------------------------------------
--  Constraints for Table EXPORT_LICENCE_COUNTRIES_1
--------------------------------------------------------

  ALTER TABLE "SAVEMGR"."EXPORT_LICENCE_COUNTRIES_1" MODIFY ("TYPE" NOT NULL ENABLE);
  ALTER TABLE "SAVEMGR"."EXPORT_LICENCE_COUNTRIES_1" MODIFY ("ELCG_ID" NOT NULL ENABLE);
  ALTER TABLE "SAVEMGR"."EXPORT_LICENCE_COUNTRIES_1" MODIFY ("COUNTRY_ID" NOT NULL ENABLE);
  ALTER TABLE "SAVEMGR"."EXPORT_LICENCE_COUNTRIES_1" MODIFY ("LD_ID" NOT NULL ENABLE);
