--------------------------------------------------------
--  Constraints for Table EXPORT_LICENCE_LINES_2
--------------------------------------------------------

  ALTER TABLE "SAVEMGR"."EXPORT_LICENCE_LINES_2" MODIFY ("ELCG_ID" NOT NULL ENABLE);
  ALTER TABLE "SAVEMGR"."EXPORT_LICENCE_LINES_2" MODIFY ("DESCRIPTION" NOT NULL ENABLE);
  ALTER TABLE "SAVEMGR"."EXPORT_LICENCE_LINES_2" MODIFY ("LINE_NO" NOT NULL ENABLE);
  ALTER TABLE "SAVEMGR"."EXPORT_LICENCE_LINES_2" MODIFY ("GOODS_ITEM_ID" NOT NULL ENABLE);
  ALTER TABLE "SAVEMGR"."EXPORT_LICENCE_LINES_2" MODIFY ("LD_ID" NOT NULL ENABLE);
  ALTER TABLE "SAVEMGR"."EXPORT_LICENCE_LINES_2" MODIFY ("ID" NOT NULL ENABLE);
