--------------------------------------------------------
--  Constraints for Table EXPORT_LICENCES
--------------------------------------------------------

  ALTER TABLE "SPIREMGR"."EXPORT_LICENCES" ADD CONSTRAINT "EXPORT_LICENCES_CK2" CHECK (LICENCE_STATUS IN ('EXTANT', 'REVOKED', 'SURRENDERED', 'LEGACY_SDB',  'DRAFT', 'DEREGISTERED')) ENABLE;
  ALTER TABLE "SPIREMGR"."EXPORT_LICENCES" MODIFY ("LICENCE_STATUS" NOT NULL ENABLE);
  ALTER TABLE "SPIREMGR"."EXPORT_LICENCES" MODIFY ("ELA_GRP_ID" NOT NULL ENABLE);
  ALTER TABLE "SPIREMGR"."EXPORT_LICENCES" ADD CONSTRAINT "EXPORT_LICENCES_UK3" UNIQUE ("ELA_GRP_ID", "ID")
  USING INDEX  ENABLE;
  ALTER TABLE "SPIREMGR"."EXPORT_LICENCES" ADD CONSTRAINT "EXPORT_LICENCES_PK" PRIMARY KEY ("ID")
  USING INDEX  ENABLE;
  ALTER TABLE "SPIREMGR"."EXPORT_LICENCES" MODIFY ("LICENCE_REF" NOT NULL ENABLE);
  ALTER TABLE "SPIREMGR"."EXPORT_LICENCES" MODIFY ("ID" NOT NULL ENABLE);
