--------------------------------------------------------
--  Constraints for Table EXPORT_LICENCE_DETAILS_4
--------------------------------------------------------

  ALTER TABLE "SAVEMGR"."EXPORT_LICENCE_DETAILS_4" MODIFY ("LICENCE_TYPE" NOT NULL ENABLE);
  ALTER TABLE "SAVEMGR"."EXPORT_LICENCE_DETAILS_4" MODIFY ("START_DATE" NOT NULL ENABLE);
  ALTER TABLE "SAVEMGR"."EXPORT_LICENCE_DETAILS_4" MODIFY ("ELA_DETAIL_ID" NOT NULL ENABLE);
  ALTER TABLE "SAVEMGR"."EXPORT_LICENCE_DETAILS_4" MODIFY ("ELA_ID" NOT NULL ENABLE);
  ALTER TABLE "SAVEMGR"."EXPORT_LICENCE_DETAILS_4" MODIFY ("L_ID" NOT NULL ENABLE);
  ALTER TABLE "SAVEMGR"."EXPORT_LICENCE_DETAILS_4" MODIFY ("ID" NOT NULL ENABLE);
