--------------------------------------------------------
--  Constraints for Table EXPORT_LICENCE_LINES_1
--------------------------------------------------------

  ALTER TABLE "SAVEMGR"."EXPORT_LICENCE_LINES_1" MODIFY ("ELCG_ID" NOT NULL ENABLE);
  ALTER TABLE "SAVEMGR"."EXPORT_LICENCE_LINES_1" MODIFY ("DESCRIPTION" NOT NULL ENABLE);
  ALTER TABLE "SAVEMGR"."EXPORT_LICENCE_LINES_1" MODIFY ("LINE_NO" NOT NULL ENABLE);
  ALTER TABLE "SAVEMGR"."EXPORT_LICENCE_LINES_1" MODIFY ("GOODS_ITEM_ID" NOT NULL ENABLE);
  ALTER TABLE "SAVEMGR"."EXPORT_LICENCE_LINES_1" MODIFY ("LD_ID" NOT NULL ENABLE);
  ALTER TABLE "SAVEMGR"."EXPORT_LICENCE_LINES_1" MODIFY ("ID" NOT NULL ENABLE);
