--------------------------------------------------------
--  Constraints for Table EXPORT_LICENCE_RETURNS_UPLOADS
--------------------------------------------------------

  ALTER TABLE "SPIREMGR"."EXPORT_LICENCE_RETURNS_UPLOADS" ADD CONSTRAINT "EL_RETURNS_UPLOADS_PK" PRIMARY KEY ("FILE_ID")
  USING INDEX  ENABLE;
  ALTER TABLE "SPIREMGR"."EXPORT_LICENCE_RETURNS_UPLOADS" MODIFY ("FILE_CONTENT" NOT NULL ENABLE);
  ALTER TABLE "SPIREMGR"."EXPORT_LICENCE_RETURNS_UPLOADS" MODIFY ("FILE_ID" NOT NULL ENABLE);
