--------------------------------------------------------
--  Constraints for Table EXPORT_LICENCE_LINES_3
--------------------------------------------------------

  ALTER TABLE "SAVEMGR"."EXPORT_LICENCE_LINES_3" MODIFY ("ELCG_ID" NOT NULL ENABLE);
  ALTER TABLE "SAVEMGR"."EXPORT_LICENCE_LINES_3" MODIFY ("DESCRIPTION" NOT NULL ENABLE);
  ALTER TABLE "SAVEMGR"."EXPORT_LICENCE_LINES_3" MODIFY ("LINE_NO" NOT NULL ENABLE);
  ALTER TABLE "SAVEMGR"."EXPORT_LICENCE_LINES_3" MODIFY ("GOODS_ITEM_ID" NOT NULL ENABLE);
  ALTER TABLE "SAVEMGR"."EXPORT_LICENCE_LINES_3" MODIFY ("LD_ID" NOT NULL ENABLE);
  ALTER TABLE "SAVEMGR"."EXPORT_LICENCE_LINES_3" MODIFY ("ID" NOT NULL ENABLE);
