--------------------------------------------------------
--  Constraints for Table EXPORT_LICENCE_COUNTRIES_2
--------------------------------------------------------

  ALTER TABLE "SAVEMGR"."EXPORT_LICENCE_COUNTRIES_2" MODIFY ("TYPE" NOT NULL ENABLE);
  ALTER TABLE "SAVEMGR"."EXPORT_LICENCE_COUNTRIES_2" MODIFY ("ELCG_ID" NOT NULL ENABLE);
  ALTER TABLE "SAVEMGR"."EXPORT_LICENCE_COUNTRIES_2" MODIFY ("COUNTRY_ID" NOT NULL ENABLE);
  ALTER TABLE "SAVEMGR"."EXPORT_LICENCE_COUNTRIES_2" MODIFY ("LD_ID" NOT NULL ENABLE);
