--------------------------------------------------------
--  Constraints for Table EXPORT_LICENCE_COUNTRY_GROUPS
--------------------------------------------------------

  ALTER TABLE "SPIREMGR"."EXPORT_LICENCE_COUNTRY_GROUPS" MODIFY ("TYPE" NOT NULL ENABLE);
  ALTER TABLE "SPIREMGR"."EXPORT_LICENCE_COUNTRY_GROUPS" ADD CONSTRAINT "EXPORT_LICENCE_COUNTRY_GPS_CK1" CHECK (type IN ('INCLUDE','EXCLUDE')) ENABLE;
  ALTER TABLE "SPIREMGR"."EXPORT_LICENCE_COUNTRY_GROUPS" ADD CONSTRAINT "EXPORT_LICENCE_COUNTRY_GPS_PK" PRIMARY KEY ("ID")
  USING INDEX  ENABLE;
