--------------------------------------------------------
--  Constraints for Table EXPORT_LICENCE_LINES
--------------------------------------------------------

  ALTER TABLE "SAVEMGR"."EXPORT_LICENCE_LINES" MODIFY ("DESCRIPTION" NOT NULL ENABLE);
  ALTER TABLE "SAVEMGR"."EXPORT_LICENCE_LINES" MODIFY ("LINE_NO" NOT NULL ENABLE);
  ALTER TABLE "SAVEMGR"."EXPORT_LICENCE_LINES" MODIFY ("GOODS_ITEM_ID" NOT NULL ENABLE);
  ALTER TABLE "SAVEMGR"."EXPORT_LICENCE_LINES" MODIFY ("COUNTRY_ID" NOT NULL ENABLE);
  ALTER TABLE "SAVEMGR"."EXPORT_LICENCE_LINES" MODIFY ("LD_ID" NOT NULL ENABLE);
  ALTER TABLE "SAVEMGR"."EXPORT_LICENCE_LINES" MODIFY ("ID" NOT NULL ENABLE);
