--------------------------------------------------------
--  Constraints for Table EXPORT_LICENCE_COUNTRIES
--------------------------------------------------------

  ALTER TABLE "SPIREMGR"."EXPORT_LICENCE_COUNTRIES" MODIFY ("TYPE" NOT NULL ENABLE);
  ALTER TABLE "SPIREMGR"."EXPORT_LICENCE_COUNTRIES" MODIFY ("ELCG_ID" NOT NULL ENABLE);
  ALTER TABLE "SPIREMGR"."EXPORT_LICENCE_COUNTRIES" ADD CONSTRAINT "EXPORT_LICENCE_COUNTRIES_CK1" CHECK (TYPE IN ('END_USER','CONSIGNEE','OPEN')) ENABLE;
  ALTER TABLE "SPIREMGR"."EXPORT_LICENCE_COUNTRIES" MODIFY ("COUNTRY_ID" NOT NULL ENABLE);
  ALTER TABLE "SPIREMGR"."EXPORT_LICENCE_COUNTRIES" MODIFY ("LD_ID" NOT NULL ENABLE);
