--------------------------------------------------------
--  Constraints for Table EXPORT_LICENCE_DETAILS_1
--------------------------------------------------------

  ALTER TABLE "SAVEMGR"."EXPORT_LICENCE_DETAILS_1" MODIFY ("LICENCE_TYPE" NOT NULL ENABLE);
  ALTER TABLE "SAVEMGR"."EXPORT_LICENCE_DETAILS_1" MODIFY ("START_DATE" NOT NULL ENABLE);
  ALTER TABLE "SAVEMGR"."EXPORT_LICENCE_DETAILS_1" MODIFY ("ELA_DETAIL_ID" NOT NULL ENABLE);
  ALTER TABLE "SAVEMGR"."EXPORT_LICENCE_DETAILS_1" MODIFY ("ELA_ID" NOT NULL ENABLE);
  ALTER TABLE "SAVEMGR"."EXPORT_LICENCE_DETAILS_1" MODIFY ("L_ID" NOT NULL ENABLE);
  ALTER TABLE "SAVEMGR"."EXPORT_LICENCE_DETAILS_1" MODIFY ("ID" NOT NULL ENABLE);
