--------------------------------------------------------
--  Constraints for Table EXPORT_LICENCE_DETAILS
--------------------------------------------------------

  ALTER TABLE "SPIREMGR"."EXPORT_LICENCE_DETAILS" ADD CONSTRAINT "EXPORT_LICENCE_DETAILS_CK5" CHECK (
  (LEGACY_FLAG IS NULL AND N_ID IS NOT NULL) OR LEGACY_FLAG IS NOT NULL OR LITE_APP IS NOT NULL
) ENABLE;
  ALTER TABLE "SPIREMGR"."EXPORT_LICENCE_DETAILS" ADD CONSTRAINT "EXPORT_LICENCE_DETAILS_CK1" CHECK (
  (LEGACY_FLAG IS NULL AND DI_ID IS NOT NULL) OR LEGACY_FLAG IS NOT NULL OR LITE_APP IS NOT NULL
) ENABLE;
  ALTER TABLE "SPIREMGR"."EXPORT_LICENCE_DETAILS" ADD CONSTRAINT "EXPORT_LICENCE_DETAILS_CK3" CHECK (LICENCE_REF IS NOT NULL) ENABLE;
  ALTER TABLE "SPIREMGR"."EXPORT_LICENCE_DETAILS" ADD CONSTRAINT "EXPORT_LICENCE_DETAILS_CK2" CHECK (EXPIRY_DATE IS NOT NULL OR OGL_ID IS NOT NULL) ENABLE;
  ALTER TABLE "SPIREMGR"."EXPORT_LICENCE_DETAILS" MODIFY ("LICENCE_TYPE" NOT NULL ENABLE);
  ALTER TABLE "SPIREMGR"."EXPORT_LICENCE_DETAILS" ADD CONSTRAINT "EXPORT_LICENCE_DETAILS_PK" PRIMARY KEY ("ID")
  USING INDEX  ENABLE;
  ALTER TABLE "SPIREMGR"."EXPORT_LICENCE_DETAILS" MODIFY ("START_DATE" NOT NULL ENABLE);
  ALTER TABLE "SPIREMGR"."EXPORT_LICENCE_DETAILS" ADD CONSTRAINT "EXPORT_LICENCE_DETAILS_CK4" CHECK (LEGACY_FLAG IS NULL OR LEGACY_FLAG = 'Y') ENABLE;
  ALTER TABLE "SPIREMGR"."EXPORT_LICENCE_DETAILS" MODIFY ("ELA_DETAIL_ID" NOT NULL ENABLE);
  ALTER TABLE "SPIREMGR"."EXPORT_LICENCE_DETAILS" MODIFY ("ELA_ID" NOT NULL ENABLE);
  ALTER TABLE "SPIREMGR"."EXPORT_LICENCE_DETAILS" MODIFY ("L_ID" NOT NULL ENABLE);
  ALTER TABLE "SPIREMGR"."EXPORT_LICENCE_DETAILS" MODIFY ("ID" NOT NULL ENABLE);
