--------------------------------------------------------
--  Constraints for Table EXPORT_LICENCE_APP_DETAILS
--------------------------------------------------------

  ALTER TABLE "SAVEMGR"."EXPORT_LICENCE_APP_DETAILS" MODIFY ("STATUS" NOT NULL ENABLE);
  ALTER TABLE "SAVEMGR"."EXPORT_LICENCE_APP_DETAILS" MODIFY ("START_DATE" NOT NULL ENABLE);
  ALTER TABLE "SAVEMGR"."EXPORT_LICENCE_APP_DETAILS" MODIFY ("ELA_ID" NOT NULL ENABLE);
  ALTER TABLE "SAVEMGR"."EXPORT_LICENCE_APP_DETAILS" MODIFY ("ID" NOT NULL ENABLE);
