--------------------------------------------------------
--  Constraints for Table EXPORT_LICENCE_USAGES
--------------------------------------------------------

  ALTER TABLE "SPIREMGR"."EXPORT_LICENCE_USAGES" ADD CONSTRAINT "EXPORT_LICENCE_USAGES_CK9" CHECK (chief_pseudo_exhaust_flag IN ('true', 'false')) ENABLE;
  ALTER TABLE "SPIREMGR"."EXPORT_LICENCE_USAGES" ADD CONSTRAINT "EXPORT_LICENCE_USAGES_CK8" CHECK (originator != 'CHIEF' OR (originator = 'CHIEF' AND mc_id IS NOT NULL)) ENABLE;
  ALTER TABLE "SPIREMGR"."EXPORT_LICENCE_USAGES" ADD CONSTRAINT "EXPORT_LICENCE_USAGES_CK7" CHECK ((warning_msg IS NOT NULL AND originator = 'CHIEF') OR warning_msg IS NULL) ENABLE;
  ALTER TABLE "SPIREMGR"."EXPORT_LICENCE_USAGES" ADD CONSTRAINT "EXPORT_LICENCE_USAGES_CK6" CHECK ((warning_flag IS NOT NULL AND originator = 'CHIEF') OR warning_flag IS NULL) ENABLE;
  ALTER TABLE "SPIREMGR"."EXPORT_LICENCE_USAGES" ADD CONSTRAINT "EXPORT_LICENCE_USAGES_CK4" CHECK (originator != 'CHIEF' OR (originator = 'CHIEF' AND declaration_ucr IS NOT NULL)) ENABLE;
  ALTER TABLE "SPIREMGR"."EXPORT_LICENCE_USAGES" ADD CONSTRAINT "EXPORT_LICENCE_USAGES_CK3" CHECK (STATUS IN ('ACTIVE', 'CANCELLED')) ENABLE;
  ALTER TABLE "SPIREMGR"."EXPORT_LICENCE_USAGES" ADD CONSTRAINT "EXPORT_LICENCE_USAGES_CK2" CHECK (TYPE IN ('CREDIT', 'DEBIT')) ENABLE;
  ALTER TABLE "SPIREMGR"."EXPORT_LICENCE_USAGES" ADD CONSTRAINT "EXPORT_LICENCE_USAGES_CK1" CHECK (ORIGINATOR IN ('EXPORTER', 'REGULATOR', 'CHIEF')) ENABLE;
  ALTER TABLE "SPIREMGR"."EXPORT_LICENCE_USAGES" ADD CONSTRAINT "EXPORT_LICENCE_USAGES_PK" PRIMARY KEY ("ID")
  USING INDEX  ENABLE;
  ALTER TABLE "SPIREMGR"."EXPORT_LICENCE_USAGES" MODIFY ("CHIEF_PSEUDO_EXHAUST_FLAG" NOT NULL ENABLE);
  ALTER TABLE "SPIREMGR"."EXPORT_LICENCE_USAGES" MODIFY ("UPDATED_DATETIME" NOT NULL ENABLE);
  ALTER TABLE "SPIREMGR"."EXPORT_LICENCE_USAGES" MODIFY ("UPDATED_BY_WUA_ID" NOT NULL ENABLE);
  ALTER TABLE "SPIREMGR"."EXPORT_LICENCE_USAGES" MODIFY ("UPDATED_BY_WUA_FULL_NAME" NOT NULL ENABLE);
  ALTER TABLE "SPIREMGR"."EXPORT_LICENCE_USAGES" MODIFY ("CREATED_DATETIME" NOT NULL ENABLE);
  ALTER TABLE "SPIREMGR"."EXPORT_LICENCE_USAGES" MODIFY ("CREATED_BY_WUA_ID" NOT NULL ENABLE);
  ALTER TABLE "SPIREMGR"."EXPORT_LICENCE_USAGES" MODIFY ("CREATED_BY_WUA_FULL_NAME" NOT NULL ENABLE);
  ALTER TABLE "SPIREMGR"."EXPORT_LICENCE_USAGES" MODIFY ("STATUS" NOT NULL ENABLE);
  ALTER TABLE "SPIREMGR"."EXPORT_LICENCE_USAGES" MODIFY ("TYPE" NOT NULL ENABLE);
  ALTER TABLE "SPIREMGR"."EXPORT_LICENCE_USAGES" MODIFY ("ORIGINATOR" NOT NULL ENABLE);
  ALTER TABLE "SPIREMGR"."EXPORT_LICENCE_USAGES" MODIFY ("QUANTITY" NOT NULL ENABLE);
  ALTER TABLE "SPIREMGR"."EXPORT_LICENCE_USAGES" MODIFY ("LD_ID" NOT NULL ENABLE);
  ALTER TABLE "SPIREMGR"."EXPORT_LICENCE_USAGES" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "SPIREMGR"."EXPORT_LICENCE_USAGES" ADD CONSTRAINT "EXPORT_LICENCE_USAGES_CK5" CHECK (warning_flag IS NULL OR warning_flag IN ('WARNING', 'ILLEGAL', 'WARNING_ILLEGAL')) ENABLE;
