--------------------------------------------------------
--  Constraints for Table EXPORT_LICENCE_APP_TYPES
--------------------------------------------------------

  ALTER TABLE "SPIREMGR"."EXPORT_LICENCE_APP_TYPES" ADD CONSTRAINT "EXPORT_LICENCE_APP_TYPES_UK" UNIQUE ("APPLICATION_TYPE", "APPLICATION_SUB_TYPE")
  USING INDEX  ENABLE;
  ALTER TABLE "SPIREMGR"."EXPORT_LICENCE_APP_TYPES" MODIFY ("APPLICATION_TYPE" NOT NULL ENABLE);
