--------------------------------------------------------
--  Constraints for Table EXPORT_LICENCE_LINES
--------------------------------------------------------

  ALTER TABLE "SPIREMGR"."EXPORT_LICENCE_LINES" ADD CONSTRAINT "EXPORT_LICENCE_LINES_CK2" CHECK (LEGACY_FLAG IS NULL OR LEGACY_FLAG = 'Y') ENABLE;
  ALTER TABLE "SPIREMGR"."EXPORT_LICENCE_LINES" MODIFY ("ELCG_ID" NOT NULL ENABLE);
  ALTER TABLE "SPIREMGR"."EXPORT_LICENCE_LINES" ADD CONSTRAINT "EXPORT_LICENCE_DT_COUNTRIES_PK" PRIMARY KEY ("ID")
  USING INDEX  ENABLE;
  ALTER TABLE "SPIREMGR"."EXPORT_LICENCE_LINES" MODIFY ("DESCRIPTION" NOT NULL ENABLE);
  ALTER TABLE "SPIREMGR"."EXPORT_LICENCE_LINES" MODIFY ("LINE_NO" NOT NULL ENABLE);
  ALTER TABLE "SPIREMGR"."EXPORT_LICENCE_LINES" MODIFY ("GOODS_ITEM_ID" NOT NULL ENABLE);
  ALTER TABLE "SPIREMGR"."EXPORT_LICENCE_LINES" ADD CONSTRAINT "EXPORT_LICENCE_LINES_CK1" CHECK ((LEGACY_FLAG IS NULL AND GOODS_ITEM_ID IS NOT NULL) OR LEGACY_FLAG IS NOT NULL) ENABLE;
  ALTER TABLE "SPIREMGR"."EXPORT_LICENCE_LINES" MODIFY ("LD_ID" NOT NULL ENABLE);
  ALTER TABLE "SPIREMGR"."EXPORT_LICENCE_LINES" MODIFY ("ID" NOT NULL ENABLE);
