--------------------------------------------------------
--  Constraints for Table EXPORT_LICENCE_APP_DETAILS
--------------------------------------------------------

  ALTER TABLE "SPIREMGR"."EXPORT_LICENCE_APP_DETAILS" ADD CONSTRAINT "EXPORT_LICENCE_APP_DETAILS_PK1" PRIMARY KEY ("ID")
  USING INDEX  ENABLE;
  ALTER TABLE "SPIREMGR"."EXPORT_LICENCE_APP_DETAILS" ADD CONSTRAINT "EXPORT_LICENCE_APP_DETAILS_CK4" CHECK (
 /* Check that at access_external_date is populated if access external is populated */  
 ( ACCESS_EXTERNAL IS NULL OR (ACCESS_EXTERNAL IS NOT NULL AND ACCESS_EXTERNAL_DATE IS NOT NULL) )
 ) ENABLE;
  ALTER TABLE "SPIREMGR"."EXPORT_LICENCE_APP_DETAILS" ADD CONSTRAINT "EXPORT_LICENCE_APP_DETAILS_CK3" CHECK (
 /* Check that at least 1 control is populated */  
 ( ACCESS_EXTERNAL IS NOT NULL OR ACCESS_INTERNAL IS NOT NULL )
 ) ENABLE;
  ALTER TABLE "SPIREMGR"."EXPORT_LICENCE_APP_DETAILS" ADD CONSTRAINT "EXPORT_LICENCE_APP_DETAILS_CK5" CHECK (
 /* Check access_external value */  
 ( ACCESS_EXTERNAL IN ('C','A') OR ACCESS_EXTERNAL IS NULL )
 ) ENABLE;
  ALTER TABLE "SPIREMGR"."EXPORT_LICENCE_APP_DETAILS" ADD CONSTRAINT "EXPORT_LICENCE_APP_DETAILS_CK6" CHECK (
 /* Check access_internal value */  
 ( ACCESS_INTERNAL IN ('C','A') OR ACCESS_INTERNAL IS NULL )
 ) ENABLE;
  ALTER TABLE "SPIREMGR"."EXPORT_LICENCE_APP_DETAILS" MODIFY ("STATUS" NOT NULL ENABLE);
  ALTER TABLE "SPIREMGR"."EXPORT_LICENCE_APP_DETAILS" MODIFY ("START_DATE" NOT NULL ENABLE);
  ALTER TABLE "SPIREMGR"."EXPORT_LICENCE_APP_DETAILS" MODIFY ("ELA_ID" NOT NULL ENABLE);
  ALTER TABLE "SPIREMGR"."EXPORT_LICENCE_APP_DETAILS" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "SPIREMGR"."EXPORT_LICENCE_APP_DETAILS" ADD CONSTRAINT "EXPORT_LICENCE_APP_DETAILS_CK1" CHECK (status IN ('DRAFT', 'DELETED', 'SUBMITTED','CURRENT','FINAL', 'REOPENED','RETURNED','WITHDRAWN','DRAFT-REVISE')) ENABLE;
  ALTER TABLE "SPIREMGR"."EXPORT_LICENCE_APP_DETAILS" MODIFY ("XML_DATA" NOT NULL ENABLE);
  ALTER TABLE "SPIREMGR"."EXPORT_LICENCE_APP_DETAILS" ADD CONSTRAINT "EXPORT_LICENCE_APP_DETAILS_UK1" UNIQUE ("ELA_ID", "ID")
  USING INDEX  ENABLE;
