--------------------------------------------------------
--  Constraints for Table EXPORT_LIC_STATUS_EVENT_DTLS
--------------------------------------------------------

  ALTER TABLE "SPIREMGR"."EXPORT_LIC_STATUS_EVENT_DTLS" ADD CONSTRAINT "EXP_LIC_STATUS_EVENT_DTLS_CK1" CHECK (/* End date and status control */ (end_datetime IS NULL AND status_control='C') OR (end_datetime IS NOT NULL AND status_control IS NULL)) ENABLE;
  ALTER TABLE "SPIREMGR"."EXPORT_LIC_STATUS_EVENT_DTLS" ADD CONSTRAINT "EXP_LIC_STATUS_EVENT_DTLS_PK" PRIMARY KEY ("ID")
  USING INDEX  ENABLE;
  ALTER TABLE "SPIREMGR"."EXPORT_LIC_STATUS_EVENT_DTLS" MODIFY ("EVENT_STARTED_BY_WUA_ID" NOT NULL ENABLE);
  ALTER TABLE "SPIREMGR"."EXPORT_LIC_STATUS_EVENT_DTLS" MODIFY ("EVENT_STARTED_DATE" NOT NULL ENABLE);
  ALTER TABLE "SPIREMGR"."EXPORT_LIC_STATUS_EVENT_DTLS" MODIFY ("START_DATETIME" NOT NULL ENABLE);
  ALTER TABLE "SPIREMGR"."EXPORT_LIC_STATUS_EVENT_DTLS" MODIFY ("CA_ID" NOT NULL ENABLE);
  ALTER TABLE "SPIREMGR"."EXPORT_LIC_STATUS_EVENT_DTLS" MODIFY ("ELSE_ID" NOT NULL ENABLE);
  ALTER TABLE "SPIREMGR"."EXPORT_LIC_STATUS_EVENT_DTLS" MODIFY ("ID" NOT NULL ENABLE);
