--------------------------------------------------------
--  Constraints for Table EXPORT_LICENCE_APPS
--------------------------------------------------------

  ALTER TABLE "SPIREMGR"."EXPORT_LICENCE_APPS" ADD CONSTRAINT "EXPORT_LICENCE_APPS_PK" PRIMARY KEY ("ID")
  USING INDEX  ENABLE;
  ALTER TABLE "SPIREMGR"."EXPORT_LICENCE_APPS" ADD CONSTRAINT "EXPORT_LICENCE_APPS_CK2" CHECK (suspended_flag IN (0,1)) ENABLE;
  ALTER TABLE "SPIREMGR"."EXPORT_LICENCE_APPS" ADD CONSTRAINT "EXPORT_LICENCE_APPS_CK1" CHECK (ela_grp_id IS NOT NULL) DEFERRABLE INITIALLY DEFERRED ENABLE;
