--------------------------------------------------------
--  Constraints for Table EXPORT_LICENCE_DETAILS_2
--------------------------------------------------------

  ALTER TABLE "SAVEMGR"."EXPORT_LICENCE_DETAILS_2" MODIFY ("LICENCE_TYPE" NOT NULL ENABLE);
  ALTER TABLE "SAVEMGR"."EXPORT_LICENCE_DETAILS_2" MODIFY ("START_DATE" NOT NULL ENABLE);
  ALTER TABLE "SAVEMGR"."EXPORT_LICENCE_DETAILS_2" MODIFY ("ELA_DETAIL_ID" NOT NULL ENABLE);
  ALTER TABLE "SAVEMGR"."EXPORT_LICENCE_DETAILS_2" MODIFY ("ELA_ID" NOT NULL ENABLE);
  ALTER TABLE "SAVEMGR"."EXPORT_LICENCE_DETAILS_2" MODIFY ("L_ID" NOT NULL ENABLE);
  ALTER TABLE "SAVEMGR"."EXPORT_LICENCE_DETAILS_2" MODIFY ("ID" NOT NULL ENABLE);
