--------------------------------------------------------
--  Constraints for Table FDS_LOG
--------------------------------------------------------

  ALTER TABLE "DECMGR"."FDS_LOG" ADD CONSTRAINT "FDS_LOG_PK" PRIMARY KEY ("ID")
  USING INDEX  ENABLE;
  ALTER TABLE "DECMGR"."FDS_LOG" MODIFY ("LOG_DATE" NOT NULL ENABLE);
  ALTER TABLE "DECMGR"."FDS_LOG" MODIFY ("MESSAGE" NOT NULL ENABLE);
  ALTER TABLE "DECMGR"."FDS_LOG" MODIFY ("SEVERITY_NAME" NOT NULL ENABLE);
  ALTER TABLE "DECMGR"."FDS_LOG" MODIFY ("SEVERITY" NOT NULL ENABLE);
  ALTER TABLE "DECMGR"."FDS_LOG" MODIFY ("CONTEXT" NOT NULL ENABLE);
  ALTER TABLE "DECMGR"."FDS_LOG" MODIFY ("APPLICATION" NOT NULL ENABLE);
