--------------------------------------------------------
--  Constraints for Table FILE_FOLDER_USAGES
--------------------------------------------------------

  ALTER TABLE "DECMGR"."FILE_FOLDER_USAGES" ADD CONSTRAINT "FILE_FOLDER_USAGES_UK1" UNIQUE ("FF_ID", "UREF", "PURPOSE", "START_DATETIME")
  USING INDEX (CREATE UNIQUE INDEX "DECMGR"."FILE_FOLDER_USAGES_PK" ON "DECMGR"."FILE_FOLDER_USAGES" ("UREF", "FF_ID", "PURPOSE", "START_DATETIME") 
  )  ENABLE;
  ALTER TABLE "DECMGR"."FILE_FOLDER_USAGES" ADD CONSTRAINT "FILE_FOLDER_USAGES_PK" PRIMARY KEY ("UREF", "FF_ID", "PURPOSE", "START_DATETIME")
  USING INDEX  ENABLE;
  ALTER TABLE "DECMGR"."FILE_FOLDER_USAGES" MODIFY ("START_DATETIME" NOT NULL ENABLE);
  ALTER TABLE "DECMGR"."FILE_FOLDER_USAGES" MODIFY ("UREF" NOT NULL ENABLE);
  ALTER TABLE "DECMGR"."FILE_FOLDER_USAGES" MODIFY ("FF_ID" NOT NULL ENABLE);
