--------------------------------------------------------
--  Constraints for Table FILE_TRANSMISSION_ATTACHMENTS
--------------------------------------------------------

  ALTER TABLE "PORTALMGR"."FILE_TRANSMISSION_ATTACHMENTS" ADD CONSTRAINT "FILE_TRANSMISSION_ATTACH_CK1" CHECK (status IN('PENDING','IN_PROGRESS','COMPLETED','FAILED')) ENABLE;
  ALTER TABLE "PORTALMGR"."FILE_TRANSMISSION_ATTACHMENTS" ADD CONSTRAINT "FILE_TRANSMISSION_ATTACH_UK1" UNIQUE ("FT_ID", "PL_ID")
  USING INDEX  ENABLE;
  ALTER TABLE "PORTALMGR"."FILE_TRANSMISSION_ATTACHMENTS" MODIFY ("PAYLOAD_SEQUENCE" NOT NULL ENABLE);
  ALTER TABLE "PORTALMGR"."FILE_TRANSMISSION_ATTACHMENTS" MODIFY ("STATUS" NOT NULL ENABLE);
  ALTER TABLE "PORTALMGR"."FILE_TRANSMISSION_ATTACHMENTS" MODIFY ("PL_ID" NOT NULL ENABLE);
  ALTER TABLE "PORTALMGR"."FILE_TRANSMISSION_ATTACHMENTS" MODIFY ("FT_ID" NOT NULL ENABLE);
