--------------------------------------------------------
--  Constraints for Table FILE_TRANSMISSION_TYPE_DETAILS
--------------------------------------------------------

  ALTER TABLE "PORTALMGR"."FILE_TRANSMISSION_TYPE_DETAILS" ADD CONSTRAINT "FILE_TRANSMISSION_TYPE_DET_PK" PRIMARY KEY ("ID")
  USING INDEX  ENABLE;
  ALTER TABLE "PORTALMGR"."FILE_TRANSMISSION_TYPE_DETAILS" MODIFY ("CONFIG_XML" NOT NULL ENABLE);
  ALTER TABLE "PORTALMGR"."FILE_TRANSMISSION_TYPE_DETAILS" MODIFY ("START_DATETIME" NOT NULL ENABLE);
  ALTER TABLE "PORTALMGR"."FILE_TRANSMISSION_TYPE_DETAILS" MODIFY ("TYPE_MNEM" NOT NULL ENABLE);
