--------------------------------------------------------
--  Constraints for Table FILE_FOLDERS
--------------------------------------------------------

  ALTER TABLE "DECMGR"."FILE_FOLDERS" ADD CHECK (STATUS IN ('NEW_COMPLETE', 'NEW_INCOMPLETE', 'COMPLETE', 'INCOMPLETE', 'CANCELLED')) ENABLE;
  ALTER TABLE "DECMGR"."FILE_FOLDERS" ADD CONSTRAINT "FILE_FOLDERS_PK" PRIMARY KEY ("ID")
  USING INDEX  ENABLE;
  ALTER TABLE "DECMGR"."FILE_FOLDERS" MODIFY ("OPEN_START_DATETIME" NOT NULL ENABLE);
  ALTER TABLE "DECMGR"."FILE_FOLDERS" MODIFY ("TITLE" NOT NULL ENABLE);
  ALTER TABLE "DECMGR"."FILE_FOLDERS" MODIFY ("STATUS" NOT NULL ENABLE);
  ALTER TABLE "DECMGR"."FILE_FOLDERS" MODIFY ("FILE_FOLDER_TYPE" NOT NULL ENABLE);
  ALTER TABLE "DECMGR"."FILE_FOLDERS" MODIFY ("ID" NOT NULL ENABLE);
