--------------------------------------------------------
--  Constraints for Table FILE_VERSIONS
--------------------------------------------------------

  ALTER TABLE "DECMGR"."FILE_VERSIONS" ADD CONSTRAINT "FILE_VERSIONS_UK3" UNIQUE ("FOX_FILE_ID")
  USING INDEX  ENABLE;
  ALTER TABLE "DECMGR"."FILE_VERSIONS" MODIFY ("FOX_FILE_ID" NOT NULL ENABLE);
  ALTER TABLE "DECMGR"."FILE_VERSIONS" ADD CHECK (STATUS_CONTROL IN ('C', 'A', 'D')) ENABLE;
  ALTER TABLE "DECMGR"."FILE_VERSIONS" ADD CHECK (STATUS IN ('UPLOAD_INPROGRESS'
                , 'UPLOAD_FAILURE'
                , 'VIRUS_CHECKING'
                , 'VIRUS_FAILURE'
                , 'SIGN_CHECKING'
                , 'SIGN_FAILURE'
                , 'RECEIVED')) ENABLE;
  ALTER TABLE "DECMGR"."FILE_VERSIONS" ADD CHECK (STATUS IS NOT NULL) ENABLE;
  ALTER TABLE "DECMGR"."FILE_VERSIONS" ADD CHECK (STATUS IS NOT NULL) ENABLE;
  ALTER TABLE "DECMGR"."FILE_VERSIONS" ADD CHECK (STATUS_CONTROL IS NOT NULL) ENABLE;
  ALTER TABLE "DECMGR"."FILE_VERSIONS" ADD CONSTRAINT "FILE_VERSIONS_PK" PRIMARY KEY ("ID")
  USING INDEX  ENABLE;
  ALTER TABLE "DECMGR"."FILE_VERSIONS" MODIFY ("CREATE_START_DATETIME" NOT NULL ENABLE);
  ALTER TABLE "DECMGR"."FILE_VERSIONS" MODIFY ("CREATE_BY_WUA_ID" NOT NULL ENABLE);
  ALTER TABLE "DECMGR"."FILE_VERSIONS" MODIFY ("VERSION" NOT NULL ENABLE);
  ALTER TABLE "DECMGR"."FILE_VERSIONS" MODIFY ("STATUS" NOT NULL ENABLE);
  ALTER TABLE "DECMGR"."FILE_VERSIONS" MODIFY ("FFT_ID" NOT NULL ENABLE);
  ALTER TABLE "DECMGR"."FILE_VERSIONS" MODIFY ("ID" NOT NULL ENABLE);
