--------------------------------------------------------
--  Constraints for Table FILE_FOLDER_TARGETS
--------------------------------------------------------

  ALTER TABLE "DECMGR"."FILE_FOLDER_TARGETS" ADD CONSTRAINT "FILE_FOLDER_TARGETS_CK1" CHECK (STATUS IS NOT NULL) ENABLE;
  ALTER TABLE "DECMGR"."FILE_FOLDER_TARGETS" ADD CONSTRAINT "FILE_FOLDER_TARGETS_PK" PRIMARY KEY ("ID")
  USING INDEX  ENABLE;
  ALTER TABLE "DECMGR"."FILE_FOLDER_TARGETS" MODIFY ("TARGET_TITLE" NOT NULL ENABLE);
  ALTER TABLE "DECMGR"."FILE_FOLDER_TARGETS" MODIFY ("TARGET_MNEM" NOT NULL ENABLE);
  ALTER TABLE "DECMGR"."FILE_FOLDER_TARGETS" MODIFY ("FF_ID" NOT NULL ENABLE);
  ALTER TABLE "DECMGR"."FILE_FOLDER_TARGETS" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "DECMGR"."FILE_FOLDER_TARGETS" ADD CONSTRAINT "FILE_FOLDER_TARGETS_CK2" CHECK (STATUS IN ('EMPTY', 'RECEIVED', 'DELETED', 'AWAITING_SCAN')) ENABLE;
