--------------------------------------------------------
--  Constraints for Table FILE_TRANSMISSIONS
--------------------------------------------------------

  ALTER TABLE "PORTALMGR"."FILE_TRANSMISSIONS" ADD CONSTRAINT "FILE_TRANSMISSIONS_CK4" CHECK ((status IN('PENDING','SUSPENDED','CANCELLED') AND transmission_type_config_id IS NULL) OR (status NOT IN('PENDING','SUSPENDED') AND transmission_type_config_id IS NOT NULL)) ENABLE;
  ALTER TABLE "PORTALMGR"."FILE_TRANSMISSIONS" ADD CONSTRAINT "FILE_TRANSMISSIONS_CK3" CHECK (finished_datetime >= created_datetime) ENABLE;
  ALTER TABLE "PORTALMGR"."FILE_TRANSMISSIONS" ADD CONSTRAINT "FILE_TRANSMISSIONS_CK2" CHECK ((finished_datetime IS NULL AND status NOT IN('COMPLETED','FAILED','CANCELLED')) OR (finished_datetime IS NOT NULL AND status IN('COMPLETED','FAILED','CANCELLED'))) ENABLE;
  ALTER TABLE "PORTALMGR"."FILE_TRANSMISSIONS" ADD CONSTRAINT "FILE_TRANSMISSIONS_CK1" CHECK (status IN('PENDING', 'SUSPENDED', 'IN_PROGRESS', 'AWAITING_RESPONSE', 'COMPLETED', 'FAILED', 'CANCELLED')) ENABLE;
  ALTER TABLE "PORTALMGR"."FILE_TRANSMISSIONS" ADD CONSTRAINT "FILE_TRANSMISSIONS_PK" PRIMARY KEY ("ID")
  USING INDEX  ENABLE;
  ALTER TABLE "PORTALMGR"."FILE_TRANSMISSIONS" MODIFY ("CREATED_DATETIME" NOT NULL ENABLE);
  ALTER TABLE "PORTALMGR"."FILE_TRANSMISSIONS" MODIFY ("TRANSMISSION_TYPE_MNEM" NOT NULL ENABLE);
  ALTER TABLE "PORTALMGR"."FILE_TRANSMISSIONS" MODIFY ("STATUS" NOT NULL ENABLE);
