--------------------------------------------------------
--  Constraints for Table FOOTNOTES
--------------------------------------------------------

  ALTER TABLE "SDBPUBMGR"."FOOTNOTES" ADD CONSTRAINT "FOOTNOTES_CK1" CHECK (status IN ('CURRENT', 'DELETED', 'ARCHIVED')) ENABLE;
  ALTER TABLE "SDBPUBMGR"."FOOTNOTES" ADD CONSTRAINT "FOOTNOTES_PK" PRIMARY KEY ("ID")
  USING INDEX  ENABLE;
  ALTER TABLE "SDBPUBMGR"."FOOTNOTES" MODIFY ("STATUS" NOT NULL ENABLE);
  ALTER TABLE "SDBPUBMGR"."FOOTNOTES" MODIFY ("ID" NOT NULL ENABLE);
