--------------------------------------------------------
--  Constraints for Table FOOTNOTES
--------------------------------------------------------

  ALTER TABLE "SDBMGR"."FOOTNOTES" ADD CONSTRAINT "FOOTNOTES_CK2" CHECK (REPLACE(TRANSLATE(text,'ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz1234567890 !"£$%^&*()-_=+[{]};:''@#~,<.>/?\|'||CHR(10)||CHR(13),'A'),'A',NULL) IS NULL) ENABLE;
  ALTER TABLE "SDBMGR"."FOOTNOTES" ADD CONSTRAINT "FOOTNOTES_CK1" CHECK (status IN ('CURRENT', 'DELETED', 'ARCHIVED')) ENABLE;
  ALTER TABLE "SDBMGR"."FOOTNOTES" ADD CONSTRAINT "FOOTNOTES_PK" PRIMARY KEY ("ID")
  USING INDEX  ENABLE;
  ALTER TABLE "SDBMGR"."FOOTNOTES" MODIFY ("STATUS" NOT NULL ENABLE);
  ALTER TABLE "SDBMGR"."FOOTNOTES" MODIFY ("ID" NOT NULL ENABLE);
