--------------------------------------------------------
--  Constraints for Table FOOTNOTE_ENTRIES
--------------------------------------------------------

  ALTER TABLE "SDBPUBMGR"."FOOTNOTE_ENTRIES" ADD CONSTRAINT "FOOTNOTE_ENTRIES_CK4" CHECK (
    (fn_id IS NOT NULL AND mfd_id IS NULL AND mf_free_text IS NULL AND mf_grp_id IS NULL)
    OR
    (fn_id IS NULL AND mfd_id IS NOT NULL AND mf_free_text IS NULL AND mf_grp_id IS NOT NULL)
    OR
    (fn_id IS NULL AND mfd_id IS NULL AND mf_free_text IS NOT NULL AND mf_grp_id IS NOT NULL)
  ) ENABLE;
  ALTER TABLE "SDBPUBMGR"."FOOTNOTE_ENTRIES" MODIFY ("STATUS_CONTROL" NOT NULL ENABLE);
  ALTER TABLE "SDBPUBMGR"."FOOTNOTE_ENTRIES" ADD CONSTRAINT "FOOTNOTE_ENTRIES_CK3" CHECK (version_no >= 0) ENABLE;
  ALTER TABLE "SDBPUBMGR"."FOOTNOTE_ENTRIES" ADD CONSTRAINT "FOOTNOTE_ENTRIES_CK1" CHECK (   (goods_item_id IS NULL     AND country_id IS NULL     AND fnr_id IS NULL    )  -- Whole application
       OR (goods_item_id IS NOT NULL AND country_id IS NULL     AND fnr_id IS NULL    )  -- Application / goods line
       OR (goods_item_id IS NULL     AND country_id IS NOT NULL AND fnr_id IS NULL    )  -- Application / country
       OR (goods_item_id IS NULL     AND country_id IS NOT NULL AND fnr_id IS NOT NULL)  -- Country
      ) ENABLE;
  ALTER TABLE "SDBPUBMGR"."FOOTNOTE_ENTRIES" ADD CONSTRAINT "FOOTNOTE_ENTRIES_PK" PRIMARY KEY ("FNE_ID", "VERSION_NO")
  USING INDEX  ENABLE;
  ALTER TABLE "SDBPUBMGR"."FOOTNOTE_ENTRIES" MODIFY ("BATCH_ID" NOT NULL ENABLE);
  ALTER TABLE "SDBPUBMGR"."FOOTNOTE_ENTRIES" MODIFY ("VERSION_NO" NOT NULL ENABLE);
  ALTER TABLE "SDBPUBMGR"."FOOTNOTE_ENTRIES" MODIFY ("START_DATE" NOT NULL ENABLE);
  ALTER TABLE "SDBPUBMGR"."FOOTNOTE_ENTRIES" MODIFY ("ELA_GRP_ID" NOT NULL ENABLE);
  ALTER TABLE "SDBPUBMGR"."FOOTNOTE_ENTRIES" MODIFY ("FNE_ID" NOT NULL ENABLE);
