--------------------------------------------------------
--  Constraints for Table FOP_CONFIGURATIONS
--------------------------------------------------------

  ALTER TABLE "FOX5MGR"."FOP_CONFIGURATIONS" ADD CONSTRAINT "FOP_CONFIGURATIONS_PK1" PRIMARY KEY ("DOMAIN")
  USING INDEX  ENABLE;
  ALTER TABLE "FOX5MGR"."FOP_CONFIGURATIONS" MODIFY ("XML_DATA" NOT NULL ENABLE);
  ALTER TABLE "FOX5MGR"."FOP_CONFIGURATIONS" MODIFY ("DOMAIN" NOT NULL ENABLE);
