--------------------------------------------------------
--  Constraints for Table FOX_THREADS
--------------------------------------------------------

  ALTER TABLE "FOX5MGR"."FOX_THREADS" ADD CONSTRAINT "FOX_THREADS_CK1" CHECK ((locked_by IS NULL AND locked_since_datetime IS NULL) OR (locked_by IS NOT NULL AND locked_since_datetime IS NOT NULL)) ENABLE;
  ALTER TABLE "FOX5MGR"."FOX_THREADS" ADD CONSTRAINT "FOX_THREADS_PK" PRIMARY KEY ("THREAD_ID")
  USING INDEX  ENABLE;
  ALTER TABLE "FOX5MGR"."FOX_THREADS" MODIFY ("LAST_UPDATED_DATETIME" NOT NULL ENABLE);
  ALTER TABLE "FOX5MGR"."FOX_THREADS" MODIFY ("CREATED_DATETIME" NOT NULL ENABLE);
  ALTER TABLE "FOX5MGR"."FOX_THREADS" MODIFY ("THREAD_PROPERTY_MAP" NOT NULL ENABLE);
  ALTER TABLE "FOX5MGR"."FOX_THREADS" MODIFY ("USER_THREAD_SESSION_ID" NOT NULL ENABLE);
  ALTER TABLE "FOX5MGR"."FOX_THREADS" MODIFY ("APP_MNEM" NOT NULL ENABLE);
