--------------------------------------------------------
--  Constraints for Table FOX_REQUESTS
--------------------------------------------------------

  ALTER TABLE "FOXMGR"."FOX_REQUESTS" ADD CONSTRAINT "FOX_REQUESTS_PK" PRIMARY KEY ("ID")
  USING INDEX  ENABLE;
  ALTER TABLE "FOXMGR"."FOX_REQUESTS" MODIFY ("START_DATETIME" NOT NULL ENABLE);
  ALTER TABLE "FOXMGR"."FOX_REQUESTS" MODIFY ("ORIGINID" NOT NULL ENABLE);
  ALTER TABLE "FOXMGR"."FOX_REQUESTS" MODIFY ("METHOD" NOT NULL ENABLE);
  ALTER TABLE "FOXMGR"."FOX_REQUESTS" MODIFY ("URI" NOT NULL ENABLE);
  ALTER TABLE "FOXMGR"."FOX_REQUESTS" MODIFY ("APP_NAME" NOT NULL ENABLE);
  ALTER TABLE "FOXMGR"."FOX_REQUESTS" MODIFY ("CONTEXT" NOT NULL ENABLE);
  ALTER TABLE "FOXMGR"."FOX_REQUESTS" MODIFY ("HOSTNAME" NOT NULL ENABLE);
  ALTER TABLE "FOXMGR"."FOX_REQUESTS" MODIFY ("ID" NOT NULL ENABLE);
