--------------------------------------------------------
--  Constraints for Table FOX_THREAD_SYS
--------------------------------------------------------

  ALTER TABLE "FOXMGR"."FOX_THREAD_SYS" ADD CONSTRAINT "PK_FOX_THREAD_DEMO" PRIMARY KEY ("NAME")
  USING INDEX  ENABLE;
  ALTER TABLE "FOXMGR"."FOX_THREAD_SYS" MODIFY ("CREATED_DATE" NOT NULL ENABLE);
  ALTER TABLE "FOXMGR"."FOX_THREAD_SYS" MODIFY ("CREATED_BY" NOT NULL ENABLE);
  ALTER TABLE "FOXMGR"."FOX_THREAD_SYS" MODIFY ("TYPE" NOT NULL ENABLE);
  ALTER TABLE "FOXMGR"."FOX_THREAD_SYS" MODIFY ("NAME" NOT NULL ENABLE);
