--------------------------------------------------------
--  Constraints for Table FOX_RESOURCE_MASTER
--------------------------------------------------------

  ALTER TABLE "FOXMGR"."FOX_RESOURCE_MASTER" ADD CONSTRAINT "FOX_RESOURCE_MASTER_CK1" CHECK (engine_mirror = 'Y' OR engine_mirror IS NULL) ENABLE;
  ALTER TABLE "FOXMGR"."FOX_RESOURCE_MASTER" ADD CONSTRAINT "PK_FOX_RESOURCE_MASTER" PRIMARY KEY ("NAME")
  USING INDEX  ENABLE;
  ALTER TABLE "FOXMGR"."FOX_RESOURCE_MASTER" MODIFY ("TYPE" NOT NULL ENABLE);
  ALTER TABLE "FOXMGR"."FOX_RESOURCE_MASTER" MODIFY ("NAME" NOT NULL ENABLE);
