--------------------------------------------------------
--  Constraints for Table FOX_THREAD_LOG_AA_16_05_09
--------------------------------------------------------

  ALTER TABLE "FOXMGR"."FOX_THREAD_LOG_AA_16_05_09" MODIFY ("CREATED_DATE" NOT NULL ENABLE);
  ALTER TABLE "FOXMGR"."FOX_THREAD_LOG_AA_16_05_09" MODIFY ("CREATED_BY" NOT NULL ENABLE);
  ALTER TABLE "FOXMGR"."FOX_THREAD_LOG_AA_16_05_09" MODIFY ("TYPE" NOT NULL ENABLE);
  ALTER TABLE "FOXMGR"."FOX_THREAD_LOG_AA_16_05_09" MODIFY ("NAME" NOT NULL ENABLE);
