--------------------------------------------------------
--  Constraints for Table FOX_ENGINE_PLUGINS
--------------------------------------------------------

  ALTER TABLE "FOX5MGR"."FOX_ENGINE_PLUGINS" ADD CONSTRAINT "FOX_PLUGIN_PK" PRIMARY KEY ("PLUGIN_NAME", "ENGINE_LOCATOR", "ENVIRONMENT_KEY")
  USING INDEX  ENABLE;
  ALTER TABLE "FOX5MGR"."FOX_ENGINE_PLUGINS" MODIFY ("WS_ALLOWED" NOT NULL ENABLE);
  ALTER TABLE "FOX5MGR"."FOX_ENGINE_PLUGINS" MODIFY ("LOAD_ALLOWED" NOT NULL ENABLE);
