--------------------------------------------------------
--  Constraints for Table FOX_ENGINES
--------------------------------------------------------

  ALTER TABLE "FOX5MGR"."FOX_ENGINES" ADD CONSTRAINT "FOX_ENGINES_CK1" CHECK (status IN('FAILED_START', 'RUNNING', 'STOPPED','NOT_RESPONDING')) ENABLE;
  ALTER TABLE "FOX5MGR"."FOX_ENGINES" ADD CONSTRAINT "FOX_ENGINES_PK" PRIMARY KEY ("ENGINE_LOCATOR", "ENVIRONMENT_KEY")
  USING INDEX  ENABLE;
  ALTER TABLE "FOX5MGR"."FOX_ENGINES" MODIFY ("SECURITY_TOKEN" NOT NULL ENABLE);
  ALTER TABLE "FOX5MGR"."FOX_ENGINES" MODIFY ("STATUS" NOT NULL ENABLE);
