--------------------------------------------------------
--  Constraints for Table FOX_PLSQL_CONTROL
--------------------------------------------------------

  ALTER TABLE "FOXMGR"."FOX_PLSQL_CONTROL" MODIFY ("CREATED_DATETIME" NOT NULL ENABLE);
  ALTER TABLE "FOXMGR"."FOX_PLSQL_CONTROL" MODIFY ("STATUS" NOT NULL ENABLE);
  ALTER TABLE "FOXMGR"."FOX_PLSQL_CONTROL" MODIFY ("APP_MNEM" NOT NULL ENABLE);
  ALTER TABLE "FOXMGR"."FOX_PLSQL_CONTROL" MODIFY ("URL" NOT NULL ENABLE);
  ALTER TABLE "FOXMGR"."FOX_PLSQL_CONTROL" MODIFY ("NODE_NAME" NOT NULL ENABLE);
  ALTER TABLE "FOXMGR"."FOX_PLSQL_CONTROL" MODIFY ("DATABASE_SID" NOT NULL ENABLE);
