--------------------------------------------------------
--  Constraints for Table FOX_COMPONENTS_SPIRE
--------------------------------------------------------

  ALTER TABLE "ENVMGR"."FOX_COMPONENTS_SPIRE" ADD CONSTRAINT "FOX_COMPONENTS_SPIRE_CK1" CHECK (engine_mirror = 'Y' OR engine_mirror IS NULL) ENABLE;
  ALTER TABLE "ENVMGR"."FOX_COMPONENTS_SPIRE" ADD CONSTRAINT "FOX_COMPONENTS_SPIRE_PK" PRIMARY KEY ("NAME")
  USING INDEX  ENABLE;
  ALTER TABLE "ENVMGR"."FOX_COMPONENTS_SPIRE" MODIFY ("TYPE" NOT NULL ENABLE);
  ALTER TABLE "ENVMGR"."FOX_COMPONENTS_SPIRE" MODIFY ("NAME" NOT NULL ENABLE);
