--------------------------------------------------------
--  Constraints for Table FOX_UPLOAD_LOG
--------------------------------------------------------

  ALTER TABLE "FOX5MGR"."FOX_UPLOAD_LOG" ADD CONSTRAINT "FOX_UPLOAD_LOG_PK" PRIMARY KEY ("FILE_ID")
  USING INDEX  ENABLE;
  ALTER TABLE "FOX5MGR"."FOX_UPLOAD_LOG" MODIFY ("STATE" NOT NULL ENABLE);
  ALTER TABLE "FOX5MGR"."FOX_UPLOAD_LOG" MODIFY ("MODULE" NOT NULL ENABLE);
  ALTER TABLE "FOX5MGR"."FOX_UPLOAD_LOG" MODIFY ("APP_HOST" NOT NULL ENABLE);
  ALTER TABLE "FOX5MGR"."FOX_UPLOAD_LOG" MODIFY ("APP_MNEM" NOT NULL ENABLE);
  ALTER TABLE "FOX5MGR"."FOX_UPLOAD_LOG" MODIFY ("FILE_ID" NOT NULL ENABLE);
