--------------------------------------------------------
--  Constraints for Table FOX_COMPONENTS_FOX5
--------------------------------------------------------

  ALTER TABLE "ENVMGR"."FOX_COMPONENTS_FOX5" ADD CONSTRAINT "FOX_COMPONENTS_FOX5_CK1" CHECK (engine_mirror = 'Y' OR engine_mirror IS NULL) ENABLE;
  ALTER TABLE "ENVMGR"."FOX_COMPONENTS_FOX5" ADD CONSTRAINT "FOX_COMPONENTS_FOX5_PK" PRIMARY KEY ("NAME")
  USING INDEX  ENABLE;
  ALTER TABLE "ENVMGR"."FOX_COMPONENTS_FOX5" MODIFY ("TYPE" NOT NULL ENABLE);
  ALTER TABLE "ENVMGR"."FOX_COMPONENTS_FOX5" MODIFY ("NAME" NOT NULL ENABLE);
