--------------------------------------------------------
--  Constraints for Table FOX_THREAD_LOG_ERRORS
--------------------------------------------------------

  ALTER TABLE "FOXMGR"."FOX_THREAD_LOG_ERRORS" MODIFY ("CREATED_DATE" NOT NULL ENABLE);
  ALTER TABLE "FOXMGR"."FOX_THREAD_LOG_ERRORS" MODIFY ("CREATED_BY" NOT NULL ENABLE);
  ALTER TABLE "FOXMGR"."FOX_THREAD_LOG_ERRORS" MODIFY ("TYPE" NOT NULL ENABLE);
  ALTER TABLE "FOXMGR"."FOX_THREAD_LOG_ERRORS" MODIFY ("NAME" NOT NULL ENABLE);
