--------------------------------------------------------
--  Constraints for Table FOX_THREAD
--------------------------------------------------------

  ALTER TABLE "ENVMGR"."FOX_THREAD" ADD CONSTRAINT "FOX_THREAD_PK" PRIMARY KEY ("NAME")
  USING INDEX  ENABLE;
  ALTER TABLE "ENVMGR"."FOX_THREAD" MODIFY ("CREATED_DATE" NOT NULL ENABLE);
  ALTER TABLE "ENVMGR"."FOX_THREAD" MODIFY ("CREATED_BY" NOT NULL ENABLE);
  ALTER TABLE "ENVMGR"."FOX_THREAD" MODIFY ("TYPE" NOT NULL ENABLE);
  ALTER TABLE "ENVMGR"."FOX_THREAD" MODIFY ("NAME" NOT NULL ENABLE);
