--------------------------------------------------------
--  Constraints for Table FOX_SERVICES
--------------------------------------------------------

  ALTER TABLE "BPMMGR"."FOX_SERVICES" ADD CONSTRAINT "FOX_SERVICE_MASTER_UK1" UNIQUE ("FOX_SERVICE")
  USING INDEX  ENABLE;
  ALTER TABLE "BPMMGR"."FOX_SERVICES" ADD CONSTRAINT "FOX_SERVICE_MASTER_PK" PRIMARY KEY ("ID")
  USING INDEX  ENABLE;
  ALTER TABLE "BPMMGR"."FOX_SERVICES" MODIFY ("FOX_SERVICE" NOT NULL ENABLE);
  ALTER TABLE "BPMMGR"."FOX_SERVICES" MODIFY ("ID" NOT NULL ENABLE);
