--------------------------------------------------------
--  Constraints for Table FOX_STATE_CALLS
--------------------------------------------------------

  ALTER TABLE "FOX5MGR"."FOX_STATE_CALLS" ADD CONSTRAINT "FOX_STATE_CALLS_PK" PRIMARY KEY ("CALL_ID")
  USING INDEX  ENABLE;
  ALTER TABLE "FOX5MGR"."FOX_STATE_CALLS" MODIFY ("LAST_UPDATED_DATETIME" NOT NULL ENABLE);
  ALTER TABLE "FOX5MGR"."FOX_STATE_CALLS" MODIFY ("CREATED_DATETIME" NOT NULL ENABLE);
  ALTER TABLE "FOX5MGR"."FOX_STATE_CALLS" MODIFY ("SCROLL_POSITION" NOT NULL ENABLE);
  ALTER TABLE "FOX5MGR"."FOX_STATE_CALLS" MODIFY ("STATE_NAME" NOT NULL ENABLE);
  ALTER TABLE "FOX5MGR"."FOX_STATE_CALLS" MODIFY ("MODULE_CALL_ID" NOT NULL ENABLE);
  ALTER TABLE "FOX5MGR"."FOX_STATE_CALLS" MODIFY ("STACK_POSITION" NOT NULL ENABLE);
