--------------------------------------------------------
--  Constraints for Table GOODS_CHECKER_REVISIONS
--------------------------------------------------------

  ALTER TABLE "SPIREMGR"."GOODS_CHECKER_REVISIONS" ADD CONSTRAINT "GCR_STATUS_CHECK_CONSTRAINT" CHECK (
    status IN ('PENDING', 'DELETED', 'ARCHIVED', 'CURRENT')
  ) ENABLE;
  ALTER TABLE "SPIREMGR"."GOODS_CHECKER_REVISIONS" ADD CONSTRAINT "GOODS_CHECKER_REVISIONS_PK" PRIMARY KEY ("ID")
  USING INDEX  ENABLE;
  ALTER TABLE "SPIREMGR"."GOODS_CHECKER_REVISIONS" MODIFY ("CREATED_BY_WUA_ID" NOT NULL ENABLE);
  ALTER TABLE "SPIREMGR"."GOODS_CHECKER_REVISIONS" MODIFY ("STATUS" NOT NULL ENABLE);
  ALTER TABLE "SPIREMGR"."GOODS_CHECKER_REVISIONS" MODIFY ("DESCRIPTION" NOT NULL ENABLE);
