--------------------------------------------------------
--  Constraints for Table GOODS_INCIDENTS
--------------------------------------------------------

  ALTER TABLE "SDBPUBMGR"."GOODS_INCIDENTS" ADD CONSTRAINT "GOODS_INCIDENTS_CK1" CHECK (type IN ('REFUSAL', 'ISSUE', 'REVOKE',  'SURRENDER')) ENABLE NOVALIDATE;
  ALTER TABLE "SDBPUBMGR"."GOODS_INCIDENTS" MODIFY ("STATUS_CONTROL" NOT NULL ENABLE);
  ALTER TABLE "SDBPUBMGR"."GOODS_INCIDENTS" ADD CONSTRAINT "GOODS_INCIDENTS_CK2" CHECK (version_no >= 0) ENABLE;
  ALTER TABLE "SDBPUBMGR"."GOODS_INCIDENTS" ADD CONSTRAINT "GOODS_INCIDENTS_PK" PRIMARY KEY ("ID")
  USING INDEX  ENABLE;
  ALTER TABLE "SDBPUBMGR"."GOODS_INCIDENTS" MODIFY ("BATCH_ID" NOT NULL ENABLE);
  ALTER TABLE "SDBPUBMGR"."GOODS_INCIDENTS" MODIFY ("VERSION_NO" NOT NULL ENABLE);
  ALTER TABLE "SDBPUBMGR"."GOODS_INCIDENTS" MODIFY ("START_DATE" NOT NULL ENABLE);
  ALTER TABLE "SDBPUBMGR"."GOODS_INCIDENTS" MODIFY ("ELA_GRP_ID" NOT NULL ENABLE);
  ALTER TABLE "SDBPUBMGR"."GOODS_INCIDENTS" MODIFY ("REPORT_DATE" NOT NULL ENABLE);
  ALTER TABLE "SDBPUBMGR"."GOODS_INCIDENTS" MODIFY ("DEST_COUNTRY_ID" NOT NULL ENABLE);
  ALTER TABLE "SDBPUBMGR"."GOODS_INCIDENTS" MODIFY ("GOODS_ITEM_ID" NOT NULL ENABLE);
  ALTER TABLE "SDBPUBMGR"."GOODS_INCIDENTS" MODIFY ("TYPE" NOT NULL ENABLE);
  ALTER TABLE "SDBPUBMGR"."GOODS_INCIDENTS" MODIFY ("INC_ID" NOT NULL ENABLE);
  ALTER TABLE "SDBPUBMGR"."GOODS_INCIDENTS" MODIFY ("ID" NOT NULL ENABLE);
