--------------------------------------------------------
--  Constraints for Table GOODS_INCIDENTS_FIV5411
--------------------------------------------------------

  ALTER TABLE "SAVEMGR"."GOODS_INCIDENTS_FIV5411" MODIFY ("STATUS_CONTROL" NOT NULL ENABLE);
  ALTER TABLE "SAVEMGR"."GOODS_INCIDENTS_FIV5411" MODIFY ("VERSION_NO" NOT NULL ENABLE);
  ALTER TABLE "SAVEMGR"."GOODS_INCIDENTS_FIV5411" MODIFY ("START_DATE" NOT NULL ENABLE);
  ALTER TABLE "SAVEMGR"."GOODS_INCIDENTS_FIV5411" MODIFY ("ELA_GRP_ID" NOT NULL ENABLE);
  ALTER TABLE "SAVEMGR"."GOODS_INCIDENTS_FIV5411" MODIFY ("REPORT_DATE" NOT NULL ENABLE);
  ALTER TABLE "SAVEMGR"."GOODS_INCIDENTS_FIV5411" MODIFY ("DEST_COUNTRY_ID" NOT NULL ENABLE);
  ALTER TABLE "SAVEMGR"."GOODS_INCIDENTS_FIV5411" MODIFY ("GOODS_ITEM_ID" NOT NULL ENABLE);
  ALTER TABLE "SAVEMGR"."GOODS_INCIDENTS_FIV5411" MODIFY ("TYPE" NOT NULL ENABLE);
  ALTER TABLE "SAVEMGR"."GOODS_INCIDENTS_FIV5411" MODIFY ("INC_ID" NOT NULL ENABLE);
  ALTER TABLE "SAVEMGR"."GOODS_INCIDENTS_FIV5411" MODIFY ("ID" NOT NULL ENABLE);
