--------------------------------------------------------
--  Constraints for Table GRADING_BREAKDOWN_UPLOADS
--------------------------------------------------------

  ALTER TABLE "PVEXMGR"."GRADING_BREAKDOWN_UPLOADS" ADD CONSTRAINT "GRADING_BREAKDOWN_CK1" CHECK (status_control = 'C' OR status_control IS NULL) ENABLE;
  ALTER TABLE "PVEXMGR"."GRADING_BREAKDOWN_UPLOADS" ADD CONSTRAINT "GRADING_BREAKDOWN_PK" PRIMARY KEY ("FILE_ID", "PEA_ID", "VERSION_NO")
  USING INDEX  ENABLE;
  ALTER TABLE "PVEXMGR"."GRADING_BREAKDOWN_UPLOADS" MODIFY ("FILE_CONTENT" NOT NULL ENABLE);
  ALTER TABLE "PVEXMGR"."GRADING_BREAKDOWN_UPLOADS" MODIFY ("FILE_ID" NOT NULL ENABLE);
  ALTER TABLE "PVEXMGR"."GRADING_BREAKDOWN_UPLOADS" MODIFY ("VERSION_NO" NOT NULL ENABLE);
