--------------------------------------------------------
--  Constraints for Table HMRC_LICENCE_LINE_DETAILS
--------------------------------------------------------

  ALTER TABLE "HMRCMGR"."HMRC_LICENCE_LINE_DETAILS" ADD CONSTRAINT "HMRC_LICENCE_LINE_DETAILS_PK" PRIMARY KEY ("TRANSACTION_REF", "LICENCE_REF", "LINE_NO")
  USING INDEX  ENABLE;
  ALTER TABLE "HMRCMGR"."HMRC_LICENCE_LINE_DETAILS" MODIFY ("LINE_NO" NOT NULL ENABLE);
  ALTER TABLE "HMRCMGR"."HMRC_LICENCE_LINE_DETAILS" MODIFY ("LICENCE_REF" NOT NULL ENABLE);
  ALTER TABLE "HMRCMGR"."HMRC_LICENCE_LINE_DETAILS" MODIFY ("TRANSACTION_REF" NOT NULL ENABLE);
