--------------------------------------------------------
--  Constraints for Table HMRC_LICENCE_LINE_USAGES
--------------------------------------------------------

  ALTER TABLE "HMRCMGR"."HMRC_LICENCE_LINE_USAGES" ADD CONSTRAINT "HMRC_LICENCE_LINE_USAGES_PK" PRIMARY KEY ("TRANSACTION_REF", "LICENCE_REF", "LINE_NO", "RECORD_NO")
  USING INDEX  ENABLE;
  ALTER TABLE "HMRCMGR"."HMRC_LICENCE_LINE_USAGES" ADD CONSTRAINT "HLLU_USAGE_TYPE_CHK" CHECK (usage_type in ('A','C','L','M','O')) ENABLE;
  ALTER TABLE "HMRCMGR"."HMRC_LICENCE_LINE_USAGES" MODIFY ("CONTROL_DATE" NOT NULL ENABLE);
  ALTER TABLE "HMRCMGR"."HMRC_LICENCE_LINE_USAGES" MODIFY ("DECLARATION_UCR" NOT NULL ENABLE);
  ALTER TABLE "HMRCMGR"."HMRC_LICENCE_LINE_USAGES" MODIFY ("RECORD_NO" NOT NULL ENABLE);
  ALTER TABLE "HMRCMGR"."HMRC_LICENCE_LINE_USAGES" MODIFY ("USAGE_TYPE" NOT NULL ENABLE);
  ALTER TABLE "HMRCMGR"."HMRC_LICENCE_LINE_USAGES" MODIFY ("LINE_NO" NOT NULL ENABLE);
  ALTER TABLE "HMRCMGR"."HMRC_LICENCE_LINE_USAGES" MODIFY ("LICENCE_REF" NOT NULL ENABLE);
  ALTER TABLE "HMRCMGR"."HMRC_LICENCE_LINE_USAGES" MODIFY ("TRANSACTION_REF" NOT NULL ENABLE);
