--------------------------------------------------------
--  Constraints for Table HMRC_LICENCE_USAGES
--------------------------------------------------------

  ALTER TABLE "HMRCMGR"."HMRC_LICENCE_USAGES" ADD CONSTRAINT "HMRC_LICENCE_USAGES_PK" PRIMARY KEY ("TRANSACTION_REF", "LICENCE_REF")
  USING INDEX  ENABLE;
  ALTER TABLE "HMRCMGR"."HMRC_LICENCE_USAGES" ADD CONSTRAINT "HLU_LICENCE_STATUS_CHECK" CHECK (licence_status in ('C','E','O','S','D')) ENABLE;
  ALTER TABLE "HMRCMGR"."HMRC_LICENCE_USAGES" MODIFY ("LICENCE_STATUS" NOT NULL ENABLE);
  ALTER TABLE "HMRCMGR"."HMRC_LICENCE_USAGES" MODIFY ("LICENCE_REF" NOT NULL ENABLE);
  ALTER TABLE "HMRCMGR"."HMRC_LICENCE_USAGES" MODIFY ("TRANSACTION_REF" NOT NULL ENABLE);
