--------------------------------------------------------
--  Constraints for Table HMRC_USAGE_TRANSMISSIONS
--------------------------------------------------------

  ALTER TABLE "HMRCMGR"."HMRC_USAGE_TRANSMISSIONS" ADD CONSTRAINT "HMRC_USAGE_TRANSMISSIONS_UK1" UNIQUE ("REPOSITORY_NAME", "MESSAGE_NAME")
  USING INDEX  ENABLE;
  ALTER TABLE "HMRCMGR"."HMRC_USAGE_TRANSMISSIONS" ADD CONSTRAINT "HMRC_USAGE_TRANSMISSIONS_PK" PRIMARY KEY ("TRANSMISSION_ID")
  USING INDEX  ENABLE;
  ALTER TABLE "HMRCMGR"."HMRC_USAGE_TRANSMISSIONS" MODIFY ("REPOSITORY_NAME" NOT NULL ENABLE);
  ALTER TABLE "HMRCMGR"."HMRC_USAGE_TRANSMISSIONS" MODIFY ("MESSAGE_NAME" NOT NULL ENABLE);
