--------------------------------------------------------
--  Constraints for Table HMRC_LICENCES_QUEUE_AUD
--------------------------------------------------------

  ALTER TABLE "HMRCMGR"."HMRC_LICENCES_QUEUE_AUD" MODIFY ("LICENCE_TYPE" NOT NULL ENABLE);
  ALTER TABLE "HMRCMGR"."HMRC_LICENCES_QUEUE_AUD" MODIFY ("CREATION_DATE" NOT NULL ENABLE);
  ALTER TABLE "HMRCMGR"."HMRC_LICENCES_QUEUE_AUD" MODIFY ("ACTION" NOT NULL ENABLE);
  ALTER TABLE "HMRCMGR"."HMRC_LICENCES_QUEUE_AUD" MODIFY ("ELD_ID" NOT NULL ENABLE);
