--------------------------------------------------------
--  Constraints for Table HMRC_LICENCES_QUEUE
--------------------------------------------------------

  ALTER TABLE "HMRCMGR"."HMRC_LICENCES_QUEUE" ADD CONSTRAINT "HMRC_LICENCES_QUEUE_PK" PRIMARY KEY ("ID")
  USING INDEX  ENABLE;
  ALTER TABLE "HMRCMGR"."HMRC_LICENCES_QUEUE" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "HMRCMGR"."HMRC_LICENCES_QUEUE" ADD CONSTRAINT "VALID_ACTION" CHECK (action in ('insert','cancel','replace','reopen','reissue')) ENABLE;
  ALTER TABLE "HMRCMGR"."HMRC_LICENCES_QUEUE" ADD CONSTRAINT "HLQ_LICENCE_TYPE" CHECK (licence_type in ('OGE', 'OIE', 'SIE')) ENABLE;
  ALTER TABLE "HMRCMGR"."HMRC_LICENCES_QUEUE" MODIFY ("LICENCE_TYPE" NOT NULL ENABLE);
  ALTER TABLE "HMRCMGR"."HMRC_LICENCES_QUEUE" MODIFY ("CREATION_DATE" NOT NULL ENABLE);
  ALTER TABLE "HMRCMGR"."HMRC_LICENCES_QUEUE" MODIFY ("ACTION" NOT NULL ENABLE);
  ALTER TABLE "HMRCMGR"."HMRC_LICENCES_QUEUE" MODIFY ("ELD_ID" NOT NULL ENABLE);
