--------------------------------------------------------
--  Constraints for Table INCIDENTS
--------------------------------------------------------

  ALTER TABLE "SDBMGR"."INCIDENTS" ADD CONSTRAINT "INCIDENTS_CK15" CHECK ((type = 'SUSPENSION' AND else_id IS NOT NULL) OR (type != 'SUSPENSION' AND else_id IS NULL)) ENABLE;
  ALTER TABLE "SDBMGR"."INCIDENTS" ADD CONSTRAINT "INCIDENTS_CK2" CHECK (type IN ('REFUSAL', 'ISSUE', 'REDUCTION', 'REVOKE', 'DEREGISTRATION', 'SUSPENSION', 'SURRENDER')) ENABLE NOVALIDATE;
  ALTER TABLE "SDBMGR"."INCIDENTS" ADD CONSTRAINT "INCIDENTS_CK4" CHECK ((case_type = 'SIEL' AND case_sub_type IN ('PERMANENT', 'TEMPORARY', 'TRANSHIPMENT'))
       OR (case_type = 'OIEL' AND case_sub_type IN ('DEALER', 'MEDIA', 'MIL_DUAL', 'UKCONTSHELF','CRYPTO'))
       OR (case_type IN ('SITCL', 'OITCL', 'OGEL', 'GPL', 'TA_SIEL', 'TA_OIEL') AND case_sub_type IS NULL)) ENABLE;
  ALTER TABLE "SDBMGR"."INCIDENTS" ADD CONSTRAINT "INCIDENTS_CK14" CHECK (   (type != 'REFUSAL' AND licence_id IS NOT NULL)
       OR (type = 'REFUSAL' AND licence_id IS NULL)
      ) ENABLE;
  ALTER TABLE "SDBMGR"."INCIDENTS" ADD CONSTRAINT "INCIDENTS_CK13" CHECK (temporary_licence_flag IN (0, 1)) ENABLE;
  ALTER TABLE "SDBMGR"."INCIDENTS" ADD CONSTRAINT "INCIDENTS_CK12" CHECK (   (case_type != 'OGEL' AND ogl_id IS NULL)
       OR (case_type = 'OGEL' AND ogl_id IS NOT NULL)
      ) ENABLE;
  ALTER TABLE "SDBMGR"."INCIDENTS" ADD CONSTRAINT "INCIDENTS_CK11" CHECK (status_control IN ('A', 'P', 'C')) ENABLE;
  ALTER TABLE "SDBMGR"."INCIDENTS" ADD CONSTRAINT "INCIDENTS_CK10" CHECK (version_no >= 0) ENABLE;
  ALTER TABLE "SDBMGR"."INCIDENTS" ADD CONSTRAINT "INCIDENTS_CK9" CHECK (torture_flag IS NULL OR torture_flag IN (0, 1)) ENABLE;
  ALTER TABLE "SDBMGR"."INCIDENTS" ADD CONSTRAINT "INCIDENTS_CK8" CHECK (other_flag IS NULL OR other_flag IN (0, 1)) ENABLE;
  ALTER TABLE "SDBMGR"."INCIDENTS" ADD CONSTRAINT "INCIDENTS_CK7" CHECK (mil_flag IS NULL OR mil_flag IN (0, 1)) ENABLE;
  ALTER TABLE "SDBMGR"."INCIDENTS" ADD CONSTRAINT "INCIDENTS_CK6" CHECK (incorporation_flag IN (0, 1)) ENABLE;
  ALTER TABLE "SDBMGR"."INCIDENTS" ADD CONSTRAINT "INCIDENTS_CK5" CHECK (licence_conversion_flag IN (0, 1)) ENABLE;
  ALTER TABLE "SDBMGR"."INCIDENTS" ADD CONSTRAINT "INCIDENTS_CK3" CHECK (case_type IN ('SIEL', 'OIEL', 'SITCL', 'OITCL', 'OGEL', 'GPL', 'TA_SIEL', 'TA_OIEL')) ENABLE;
  ALTER TABLE "SDBMGR"."INCIDENTS" ADD CONSTRAINT "INCIDENTS_CK1" CHECK (status IN ('READY', 'FOR_ATTENTION')) ENABLE;
  ALTER TABLE "SDBMGR"."INCIDENTS" ADD CONSTRAINT "INCIDENTS_PK" PRIMARY KEY ("INC_ID", "VERSION_NO")
  USING INDEX  ENABLE;
  ALTER TABLE "SDBMGR"."INCIDENTS" MODIFY ("STATUS_CONTROL" NOT NULL ENABLE);
  ALTER TABLE "SDBMGR"."INCIDENTS" MODIFY ("VERSION_NO" NOT NULL ENABLE);
  ALTER TABLE "SDBMGR"."INCIDENTS" MODIFY ("START_DATE" NOT NULL ENABLE);
  ALTER TABLE "SDBMGR"."INCIDENTS" MODIFY ("INCORPORATION_FLAG" NOT NULL ENABLE);
  ALTER TABLE "SDBMGR"."INCIDENTS" MODIFY ("LICENCE_CONVERSION_FLAG" NOT NULL ENABLE);
  ALTER TABLE "SDBMGR"."INCIDENTS" MODIFY ("TEMPORARY_LICENCE_FLAG" NOT NULL ENABLE);
  ALTER TABLE "SDBMGR"."INCIDENTS" MODIFY ("REPORT_DATE" NOT NULL ENABLE);
  ALTER TABLE "SDBMGR"."INCIDENTS" MODIFY ("ELA_GRP_ID" NOT NULL ENABLE);
  ALTER TABLE "SDBMGR"."INCIDENTS" MODIFY ("CASE_TYPE" NOT NULL ENABLE);
  ALTER TABLE "SDBMGR"."INCIDENTS" MODIFY ("TYPE" NOT NULL ENABLE);
  ALTER TABLE "SDBMGR"."INCIDENTS" MODIFY ("STATUS" NOT NULL ENABLE);
  ALTER TABLE "SDBMGR"."INCIDENTS" MODIFY ("INC_ID" NOT NULL ENABLE);
