--------------------------------------------------------
--  Constraints for Table INCIDENTS_FIV5411
--------------------------------------------------------

  ALTER TABLE "SAVEMGR"."INCIDENTS_FIV5411" MODIFY ("STATUS_CONTROL" NOT NULL ENABLE);
  ALTER TABLE "SAVEMGR"."INCIDENTS_FIV5411" MODIFY ("VERSION_NO" NOT NULL ENABLE);
  ALTER TABLE "SAVEMGR"."INCIDENTS_FIV5411" MODIFY ("START_DATE" NOT NULL ENABLE);
  ALTER TABLE "SAVEMGR"."INCIDENTS_FIV5411" MODIFY ("INCORPORATION_FLAG" NOT NULL ENABLE);
  ALTER TABLE "SAVEMGR"."INCIDENTS_FIV5411" MODIFY ("LICENCE_CONVERSION_FLAG" NOT NULL ENABLE);
  ALTER TABLE "SAVEMGR"."INCIDENTS_FIV5411" MODIFY ("TEMPORARY_LICENCE_FLAG" NOT NULL ENABLE);
  ALTER TABLE "SAVEMGR"."INCIDENTS_FIV5411" MODIFY ("REPORT_DATE" NOT NULL ENABLE);
  ALTER TABLE "SAVEMGR"."INCIDENTS_FIV5411" MODIFY ("ELA_GRP_ID" NOT NULL ENABLE);
  ALTER TABLE "SAVEMGR"."INCIDENTS_FIV5411" MODIFY ("CASE_TYPE" NOT NULL ENABLE);
  ALTER TABLE "SAVEMGR"."INCIDENTS_FIV5411" MODIFY ("TYPE" NOT NULL ENABLE);
  ALTER TABLE "SAVEMGR"."INCIDENTS_FIV5411" MODIFY ("STATUS" NOT NULL ENABLE);
  ALTER TABLE "SAVEMGR"."INCIDENTS_FIV5411" MODIFY ("INC_ID" NOT NULL ENABLE);
