--------------------------------------------------------
--  Constraints for Table INCIDENTS
--------------------------------------------------------

  ALTER TABLE "SAVEMGR"."INCIDENTS" MODIFY ("STATUS_CONTROL" NOT NULL ENABLE);
  ALTER TABLE "SAVEMGR"."INCIDENTS" MODIFY ("VERSION_NO" NOT NULL ENABLE);
  ALTER TABLE "SAVEMGR"."INCIDENTS" MODIFY ("START_DATE" NOT NULL ENABLE);
  ALTER TABLE "SAVEMGR"."INCIDENTS" MODIFY ("INCORPORATION_FLAG" NOT NULL ENABLE);
  ALTER TABLE "SAVEMGR"."INCIDENTS" MODIFY ("LICENCE_CONVERSION_FLAG" NOT NULL ENABLE);
  ALTER TABLE "SAVEMGR"."INCIDENTS" MODIFY ("TEMPORARY_LICENCE_FLAG" NOT NULL ENABLE);
  ALTER TABLE "SAVEMGR"."INCIDENTS" MODIFY ("REPORT_DATE" NOT NULL ENABLE);
  ALTER TABLE "SAVEMGR"."INCIDENTS" MODIFY ("ELA_GRP_ID" NOT NULL ENABLE);
  ALTER TABLE "SAVEMGR"."INCIDENTS" MODIFY ("CASE_TYPE" NOT NULL ENABLE);
  ALTER TABLE "SAVEMGR"."INCIDENTS" MODIFY ("TYPE" NOT NULL ENABLE);
  ALTER TABLE "SAVEMGR"."INCIDENTS" MODIFY ("STATUS" NOT NULL ENABLE);
  ALTER TABLE "SAVEMGR"."INCIDENTS" MODIFY ("INC_ID" NOT NULL ENABLE);
