--------------------------------------------------------
--  Constraints for Table INTENTION_SET_INTENTIONS
--------------------------------------------------------

  ALTER TABLE "BPMMGR"."INTENTION_SET_INTENTIONS" MODIFY ("PURPOSE" NOT NULL ENABLE);
  ALTER TABLE "BPMMGR"."INTENTION_SET_INTENTIONS" MODIFY ("START_DATETIME" NOT NULL ENABLE);
  ALTER TABLE "BPMMGR"."INTENTION_SET_INTENTIONS" MODIFY ("IN_ID" NOT NULL ENABLE);
  ALTER TABLE "BPMMGR"."INTENTION_SET_INTENTIONS" MODIFY ("IS_ID" NOT NULL ENABLE);
