--------------------------------------------------------
--  Constraints for Table KF_ELA_DETAILS_FIV_3902
--------------------------------------------------------

  ALTER TABLE "XVIEWMGR"."KF_ELA_DETAILS_FIV_3902" MODIFY ("START_DATE" NOT NULL ENABLE);
  ALTER TABLE "XVIEWMGR"."KF_ELA_DETAILS_FIV_3902" MODIFY ("STATUS" NOT NULL ENABLE);
  ALTER TABLE "XVIEWMGR"."KF_ELA_DETAILS_FIV_3902" MODIFY ("ELA_DETAIL_ID" NOT NULL ENABLE);
  ALTER TABLE "XVIEWMGR"."KF_ELA_DETAILS_FIV_3902" MODIFY ("LOGIN_ID" NOT NULL ENABLE);
