--------------------------------------------------------
--  Constraints for Table KF_FOOTNOTE_ENTRIES
--------------------------------------------------------

  ALTER TABLE "SDBMGR"."KF_FOOTNOTE_ENTRIES" MODIFY ("STATUS_CONTROL" NOT NULL ENABLE);
  ALTER TABLE "SDBMGR"."KF_FOOTNOTE_ENTRIES" MODIFY ("BATCH_ID" NOT NULL ENABLE);
  ALTER TABLE "SDBMGR"."KF_FOOTNOTE_ENTRIES" MODIFY ("VERSION_NO" NOT NULL ENABLE);
  ALTER TABLE "SDBMGR"."KF_FOOTNOTE_ENTRIES" MODIFY ("START_DATE" NOT NULL ENABLE);
  ALTER TABLE "SDBMGR"."KF_FOOTNOTE_ENTRIES" MODIFY ("ELA_GRP_ID" NOT NULL ENABLE);
  ALTER TABLE "SDBMGR"."KF_FOOTNOTE_ENTRIES" MODIFY ("FNE_ID" NOT NULL ENABLE);
