--------------------------------------------------------
--  Constraints for Table KF_TEMP
--------------------------------------------------------

  ALTER TABLE "XVIEWMGR"."KF_TEMP" MODIFY ("DEST_COUNTRY_ID" NOT NULL ENABLE);
  ALTER TABLE "XVIEWMGR"."KF_TEMP" MODIFY ("GOODS_ITEM_ID" NOT NULL ENABLE);
  ALTER TABLE "XVIEWMGR"."KF_TEMP" MODIFY ("GI_ID" NOT NULL ENABLE);
  ALTER TABLE "XVIEWMGR"."KF_TEMP" MODIFY ("LICENCE_CONVERSION_FLAG" NOT NULL ENABLE);
  ALTER TABLE "XVIEWMGR"."KF_TEMP" MODIFY ("TYPE" NOT NULL ENABLE);
  ALTER TABLE "XVIEWMGR"."KF_TEMP" MODIFY ("INCORPORATION_FLAG" NOT NULL ENABLE);
  ALTER TABLE "XVIEWMGR"."KF_TEMP" MODIFY ("CASE_TYPE" NOT NULL ENABLE);
  ALTER TABLE "XVIEWMGR"."KF_TEMP" MODIFY ("ELA_GRP_ID" NOT NULL ENABLE);
  ALTER TABLE "XVIEWMGR"."KF_TEMP" MODIFY ("INC_ID" NOT NULL ENABLE);
