--------------------------------------------------------
--  Constraints for Table LICENCE_EXPIRY_EMAIL_TYPES
--------------------------------------------------------

  ALTER TABLE "SPIREMGR"."LICENCE_EXPIRY_EMAIL_TYPES" ADD CONSTRAINT "LICENCE_EXPIRY_EMAIL_TYPES_PK1" PRIMARY KEY ("EXPIRY_TYPE")
  USING INDEX  ENABLE;
  ALTER TABLE "SPIREMGR"."LICENCE_EXPIRY_EMAIL_TYPES" MODIFY ("BODY" NOT NULL ENABLE);
  ALTER TABLE "SPIREMGR"."LICENCE_EXPIRY_EMAIL_TYPES" MODIFY ("SUBJECT" NOT NULL ENABLE);
  ALTER TABLE "SPIREMGR"."LICENCE_EXPIRY_EMAIL_TYPES" MODIFY ("COMMENCEMENT_DATE" NOT NULL ENABLE);
  ALTER TABLE "SPIREMGR"."LICENCE_EXPIRY_EMAIL_TYPES" MODIFY ("MONTHS_BEFORE_EXPIRY" NOT NULL ENABLE);
