--------------------------------------------------------
--  Constraints for Table LICENCE_EXPIRY_EMAIL_LOGS
--------------------------------------------------------

  ALTER TABLE "SPIREMGR"."LICENCE_EXPIRY_EMAIL_LOGS" ADD CONSTRAINT "LICENCE_EXPIRY_EMAIL_LOGS_PK1" PRIMARY KEY ("LICENCE_ID", "SENT_TO_WUA_ID")
  USING INDEX  ENABLE;
  ALTER TABLE "SPIREMGR"."LICENCE_EXPIRY_EMAIL_LOGS" MODIFY ("SENT_DATE" NOT NULL ENABLE);
  ALTER TABLE "SPIREMGR"."LICENCE_EXPIRY_EMAIL_LOGS" MODIFY ("EXPIRY_TYPE" NOT NULL ENABLE);
