--------------------------------------------------------
--  Constraints for Table MAIL_CONTROL
--------------------------------------------------------

  ALTER TABLE "HMRCMGR"."MAIL_CONTROL" ADD CONSTRAINT "MAIL_CONTROL_CK4" CHECK (type = 'N/A' OR (type IN ('REPLY', 'USAGE') AND transmission_id IS NOT NULL)) ENABLE;
  ALTER TABLE "HMRCMGR"."MAIL_CONTROL" ADD CONSTRAINT "MAIL_CONTROL_CK3" CHECK (status != 'AWAITING_USAGE_JOB' OR (status = 'AWAITING_USAGE_JOB' AND type = 'USAGE')) ENABLE;
  ALTER TABLE "HMRCMGR"."MAIL_CONTROL" ADD CONSTRAINT "MAIL_CONTROL_CK2" CHECK (type IN ('N/A', 'REPLY', 'USAGE')) ENABLE;
  ALTER TABLE "HMRCMGR"."MAIL_CONTROL" ADD CONSTRAINT "MAIL_CONTROL_CK1" CHECK (status IN ('AWAITING_USAGE_JOB', 'COMPLETE', 'UNKNOWN_TYPE', 'USAGE_ERROR', 'PENDING', 'SKIPPED_TRANSMISSION')) ENABLE;
  ALTER TABLE "HMRCMGR"."MAIL_CONTROL" ADD CONSTRAINT "MAIL_CONTROL_PK1" PRIMARY KEY ("ID")
  USING INDEX  ENABLE;
  ALTER TABLE "HMRCMGR"."MAIL_CONTROL" ADD CHECK ("LAST_DML_DATETIME" IS NOT NULL) DEFERRABLE INITIALLY DEFERRED ENABLE;
  ALTER TABLE "HMRCMGR"."MAIL_CONTROL" MODIFY ("CREATED_DATETIME" NOT NULL ENABLE);
  ALTER TABLE "HMRCMGR"."MAIL_CONTROL" MODIFY ("STATUS" NOT NULL ENABLE);
  ALTER TABLE "HMRCMGR"."MAIL_CONTROL" MODIFY ("REPOSITORY_NAME" NOT NULL ENABLE);
  ALTER TABLE "HMRCMGR"."MAIL_CONTROL" MODIFY ("MESSAGE_NAME" NOT NULL ENABLE);
