--------------------------------------------------------
--  Constraints for Table MAIL_CONTROL
--------------------------------------------------------

  ALTER TABLE "SAVEMGR"."MAIL_CONTROL" MODIFY ("CREATED_DATETIME" NOT NULL ENABLE);
  ALTER TABLE "SAVEMGR"."MAIL_CONTROL" MODIFY ("STATUS" NOT NULL ENABLE);
  ALTER TABLE "SAVEMGR"."MAIL_CONTROL" MODIFY ("REPOSITORY_NAME" NOT NULL ENABLE);
  ALTER TABLE "SAVEMGR"."MAIL_CONTROL" MODIFY ("MESSAGE_NAME" NOT NULL ENABLE);
