--------------------------------------------------------
--  Constraints for Table MANUAL_TRANSMISSION_CONTROL
--------------------------------------------------------

  ALTER TABLE "HMRCMGR"."MANUAL_TRANSMISSION_CONTROL" ADD CONSTRAINT "MANUAL_TRANSMISSION_CRL_CK2" CHECK (resent_flag IS NULL OR resent_flag = 'Y') ENABLE;
  ALTER TABLE "HMRCMGR"."MANUAL_TRANSMISSION_CONTROL" ADD CONSTRAINT "MANUAL_TRANSMISSION_CRL_CK1" CHECK (response_pending IN ('Y','N')) ENABLE;
  ALTER TABLE "HMRCMGR"."MANUAL_TRANSMISSION_CONTROL" ADD CONSTRAINT "MANUAL_TRANSMISSION_CONTROL_PK" PRIMARY KEY ("TRANSMISSION_ID", "TRANSMISSION_SET")
  USING INDEX  ENABLE;
