--------------------------------------------------------
--  Constraints for Table MAPSETS
--------------------------------------------------------

  ALTER TABLE "ENVMGR"."MAPSETS" ADD CONSTRAINT "MAPSETS_CK3" CHECK (deletable_flag IN ('true', 'false')) ENABLE;
  ALTER TABLE "ENVMGR"."MAPSETS" ADD CONSTRAINT "MAPSETS_CK2" CHECK (editable_flag IN ('true', 'false')) ENABLE;
  ALTER TABLE "ENVMGR"."MAPSETS" ADD CONSTRAINT "MAPSETS_CK1" CHECK ("MODIFIED_FLAG" IN ('true','false')) ENABLE;
  ALTER TABLE "ENVMGR"."MAPSETS" ADD CONSTRAINT "MAPSETS_PK" PRIMARY KEY ("ID")
  USING INDEX  ENABLE;
  ALTER TABLE "ENVMGR"."MAPSETS" MODIFY ("DELETABLE_FLAG" NOT NULL ENABLE);
  ALTER TABLE "ENVMGR"."MAPSETS" MODIFY ("EDITABLE_FLAG" NOT NULL ENABLE);
  ALTER TABLE "ENVMGR"."MAPSETS" MODIFY ("MODIFIED_FLAG" NOT NULL ENABLE);
  ALTER TABLE "ENVMGR"."MAPSETS" MODIFY ("DOMAIN" NOT NULL ENABLE);
  ALTER TABLE "ENVMGR"."MAPSETS" MODIFY ("ID" NOT NULL ENABLE);
