--------------------------------------------------------
--  Constraints for Table MAPSETS_5
--------------------------------------------------------

  ALTER TABLE "SAVEMGR"."MAPSETS_5" MODIFY ("DELETABLE_FLAG" NOT NULL ENABLE);
  ALTER TABLE "SAVEMGR"."MAPSETS_5" MODIFY ("EDITABLE_FLAG" NOT NULL ENABLE);
  ALTER TABLE "SAVEMGR"."MAPSETS_5" MODIFY ("MODIFIED_FLAG" NOT NULL ENABLE);
  ALTER TABLE "SAVEMGR"."MAPSETS_5" MODIFY ("DOMAIN" NOT NULL ENABLE);
  ALTER TABLE "SAVEMGR"."MAPSETS_5" MODIFY ("ID" NOT NULL ENABLE);
