--------------------------------------------------------
--  Constraints for Table MAPSETS_HISTORY
--------------------------------------------------------

  ALTER TABLE "ENVMGR"."MAPSETS_HISTORY" ADD CONSTRAINT "MAPSETS_HISTORY_CK1" CHECK (status_control = 'C' OR status_control IS NULL) ENABLE;
  ALTER TABLE "ENVMGR"."MAPSETS_HISTORY" ADD CONSTRAINT "MAPSETS_HISTORY_PK" PRIMARY KEY ("ID")
  USING INDEX  ENABLE;
  ALTER TABLE "ENVMGR"."MAPSETS_HISTORY" MODIFY ("DATA" NOT NULL ENABLE);
  ALTER TABLE "ENVMGR"."MAPSETS_HISTORY" MODIFY ("START_DATE" NOT NULL ENABLE);
  ALTER TABLE "ENVMGR"."MAPSETS_HISTORY" MODIFY ("MAPSET_ID" NOT NULL ENABLE);
  ALTER TABLE "ENVMGR"."MAPSETS_HISTORY" MODIFY ("ID" NOT NULL ENABLE);
