--------------------------------------------------------
--  Constraints for Table MAPSETS_1
--------------------------------------------------------

  ALTER TABLE "SAVEMGR"."MAPSETS_1" MODIFY ("DELETABLE_FLAG" NOT NULL ENABLE);
  ALTER TABLE "SAVEMGR"."MAPSETS_1" MODIFY ("EDITABLE_FLAG" NOT NULL ENABLE);
  ALTER TABLE "SAVEMGR"."MAPSETS_1" MODIFY ("MODIFIED_FLAG" NOT NULL ENABLE);
  ALTER TABLE "SAVEMGR"."MAPSETS_1" MODIFY ("DOMAIN" NOT NULL ENABLE);
  ALTER TABLE "SAVEMGR"."MAPSETS_1" MODIFY ("ID" NOT NULL ENABLE);
