--------------------------------------------------------
--  Constraints for Table MAPSETS_22
--------------------------------------------------------

  ALTER TABLE "SAVEMGR"."MAPSETS_22" MODIFY ("DELETABLE_FLAG" NOT NULL ENABLE);
  ALTER TABLE "SAVEMGR"."MAPSETS_22" MODIFY ("EDITABLE_FLAG" NOT NULL ENABLE);
  ALTER TABLE "SAVEMGR"."MAPSETS_22" MODIFY ("MODIFIED_FLAG" NOT NULL ENABLE);
  ALTER TABLE "SAVEMGR"."MAPSETS_22" MODIFY ("DOMAIN" NOT NULL ENABLE);
  ALTER TABLE "SAVEMGR"."MAPSETS_22" MODIFY ("ID" NOT NULL ENABLE);
