--------------------------------------------------------
--  Constraints for Table MAPSETS_12
--------------------------------------------------------

  ALTER TABLE "SAVEMGR"."MAPSETS_12" MODIFY ("DELETABLE_FLAG" NOT NULL ENABLE);
  ALTER TABLE "SAVEMGR"."MAPSETS_12" MODIFY ("EDITABLE_FLAG" NOT NULL ENABLE);
  ALTER TABLE "SAVEMGR"."MAPSETS_12" MODIFY ("MODIFIED_FLAG" NOT NULL ENABLE);
  ALTER TABLE "SAVEMGR"."MAPSETS_12" MODIFY ("DOMAIN" NOT NULL ENABLE);
  ALTER TABLE "SAVEMGR"."MAPSETS_12" MODIFY ("ID" NOT NULL ENABLE);
