--------------------------------------------------------
--  Constraints for Table MAPSETS_13
--------------------------------------------------------

  ALTER TABLE "SAVEMGR"."MAPSETS_13" MODIFY ("DELETABLE_FLAG" NOT NULL ENABLE);
  ALTER TABLE "SAVEMGR"."MAPSETS_13" MODIFY ("EDITABLE_FLAG" NOT NULL ENABLE);
  ALTER TABLE "SAVEMGR"."MAPSETS_13" MODIFY ("MODIFIED_FLAG" NOT NULL ENABLE);
  ALTER TABLE "SAVEMGR"."MAPSETS_13" MODIFY ("DOMAIN" NOT NULL ENABLE);
  ALTER TABLE "SAVEMGR"."MAPSETS_13" MODIFY ("ID" NOT NULL ENABLE);
