--------------------------------------------------------
--  Constraints for Table MATRIX_SERVICE_LOG
--------------------------------------------------------

  ALTER TABLE "DECMGR"."MATRIX_SERVICE_LOG" ADD CONSTRAINT "MATRIX_SERVICE_LOG_PK" PRIMARY KEY ("ID")
  USING INDEX  ENABLE;
  ALTER TABLE "DECMGR"."MATRIX_SERVICE_LOG" MODIFY ("REQUEST_XML" NOT NULL ENABLE);
  ALTER TABLE "DECMGR"."MATRIX_SERVICE_LOG" MODIFY ("REQUEST_DATETIME" NOT NULL ENABLE);
  ALTER TABLE "DECMGR"."MATRIX_SERVICE_LOG" MODIFY ("MODULE" NOT NULL ENABLE);
  ALTER TABLE "DECMGR"."MATRIX_SERVICE_LOG" MODIFY ("ID" NOT NULL ENABLE);
