--------------------------------------------------------
--  Constraints for Table MATRIX_FOLDER_TYPES
--------------------------------------------------------

  ALTER TABLE "DECMGR"."MATRIX_FOLDER_TYPES" ADD CONSTRAINT "MATRIX_FOLDER_TYPES_PK" PRIMARY KEY ("ID")
  USING INDEX  ENABLE;
  ALTER TABLE "DECMGR"."MATRIX_FOLDER_TYPES" ADD CHECK ("XML_DATA" IS NOT NULL) ENABLE;
  ALTER TABLE "DECMGR"."MATRIX_FOLDER_TYPES" MODIFY ("XML_DATA" CONSTRAINT "SYS_C0010550" NOT NULL ENABLE);
