--------------------------------------------------------
--  Constraints for Table MATRIX_SERVICE_CONTROL
--------------------------------------------------------

  ALTER TABLE "DECMGR"."MATRIX_SERVICE_CONTROL" ADD CONSTRAINT "MATRIX_SERVICE_CONTROL_CK5" CHECK (create_unresolved_folder_enbld IN ('true', 'false')) ENABLE;
  ALTER TABLE "DECMGR"."MATRIX_SERVICE_CONTROL" ADD CONSTRAINT "MATRIX_SERVICE_CONTROL_CK4" CHECK (create_folder_enabled IN ('true', 'false')) ENABLE;
  ALTER TABLE "DECMGR"."MATRIX_SERVICE_CONTROL" ADD CONSTRAINT "MATRIX_SERVICE_CONTROL_CK3" CHECK (filing_enabled IN ('true', 'false')) ENABLE;
  ALTER TABLE "DECMGR"."MATRIX_SERVICE_CONTROL" ADD CONSTRAINT "MATRIX_SERVICE_CONTROL_CK2" CHECK (regexp_like(search_window_start, '^[0-2][0-9]:[0-5][0-9]$') AND regexp_like(search_window_end, '^[0-2][0-9]:[0-5][0-9]$')) ENABLE;
  ALTER TABLE "DECMGR"."MATRIX_SERVICE_CONTROL" MODIFY ("CREATE_UNRESOLVED_FOLDER_ENBLD" NOT NULL ENABLE);
  ALTER TABLE "DECMGR"."MATRIX_SERVICE_CONTROL" MODIFY ("SEARCH_ENABLED" NOT NULL ENABLE);
  ALTER TABLE "DECMGR"."MATRIX_SERVICE_CONTROL" MODIFY ("SEARCH_WINDOW_END" NOT NULL ENABLE);
  ALTER TABLE "DECMGR"."MATRIX_SERVICE_CONTROL" MODIFY ("SEARCH_WINDOW_START" NOT NULL ENABLE);
  ALTER TABLE "DECMGR"."MATRIX_SERVICE_CONTROL" ADD CONSTRAINT "MATRIX_SERVICE_CONTROL_UK1" UNIQUE ("DATABASE_SID", "NODE_NAME", "UREF_TYPE", "TRIM_URL")
  USING INDEX  ENABLE;
  ALTER TABLE "DECMGR"."MATRIX_SERVICE_CONTROL" MODIFY ("TRIM_VERSION" NOT NULL ENABLE);
  ALTER TABLE "DECMGR"."MATRIX_SERVICE_CONTROL" ADD CONSTRAINT "MATRIX_SERVICE_CONTROL_CK1" CHECK (regexp_like(filing_window_start, '^[0-2][0-9]:[0-5][0-9]$') AND regexp_like(filing_window_end, '^[0-2][0-9]:[0-5][0-9]$')) ENABLE;
  ALTER TABLE "DECMGR"."MATRIX_SERVICE_CONTROL" MODIFY ("FILING_WINDOW_END" NOT NULL ENABLE);
  ALTER TABLE "DECMGR"."MATRIX_SERVICE_CONTROL" MODIFY ("FILING_WINDOW_START" NOT NULL ENABLE);
  ALTER TABLE "DECMGR"."MATRIX_SERVICE_CONTROL" MODIFY ("CREATE_FOLDER_ENABLED" NOT NULL ENABLE);
  ALTER TABLE "DECMGR"."MATRIX_SERVICE_CONTROL" MODIFY ("FILING_ENABLED" NOT NULL ENABLE);
  ALTER TABLE "DECMGR"."MATRIX_SERVICE_CONTROL" MODIFY ("TRIM_LICENCE" NOT NULL ENABLE);
  ALTER TABLE "DECMGR"."MATRIX_SERVICE_CONTROL" MODIFY ("TRIM_DATABASE_ID" NOT NULL ENABLE);
  ALTER TABLE "DECMGR"."MATRIX_SERVICE_CONTROL" MODIFY ("TRIM_PASSWORD" NOT NULL ENABLE);
  ALTER TABLE "DECMGR"."MATRIX_SERVICE_CONTROL" MODIFY ("TRIM_USERNAME" NOT NULL ENABLE);
  ALTER TABLE "DECMGR"."MATRIX_SERVICE_CONTROL" MODIFY ("TRIM_DOMAIN" NOT NULL ENABLE);
  ALTER TABLE "DECMGR"."MATRIX_SERVICE_CONTROL" MODIFY ("TRIM_URL" NOT NULL ENABLE);
  ALTER TABLE "DECMGR"."MATRIX_SERVICE_CONTROL" MODIFY ("MATRIX_SERVICE_NAME" NOT NULL ENABLE);
  ALTER TABLE "DECMGR"."MATRIX_SERVICE_CONTROL" MODIFY ("NODE_NAME" NOT NULL ENABLE);
  ALTER TABLE "DECMGR"."MATRIX_SERVICE_CONTROL" MODIFY ("DATABASE_SID" NOT NULL ENABLE);
