--------------------------------------------------------
--  Constraints for Table MATRIX_SERVICE_REC_TYPES
--------------------------------------------------------

  ALTER TABLE "DECMGR"."MATRIX_SERVICE_REC_TYPES" ADD CONSTRAINT "MATRIX_SERVICE_REC_TYPES_CK1" CHECK (behaviour_filter IS NULL OR behaviour_filter IN ('Document', 'Folder')) ENABLE;
  ALTER TABLE "DECMGR"."MATRIX_SERVICE_REC_TYPES" ADD CONSTRAINT "MATRIX_SERVICE_REC_TYPES_PK" PRIMARY KEY ("URI")
  USING INDEX  ENABLE;
  ALTER TABLE "DECMGR"."MATRIX_SERVICE_REC_TYPES" MODIFY ("CREATED_DATETIME" NOT NULL ENABLE);
  ALTER TABLE "DECMGR"."MATRIX_SERVICE_REC_TYPES" MODIFY ("CREATED_BY" NOT NULL ENABLE);
  ALTER TABLE "DECMGR"."MATRIX_SERVICE_REC_TYPES" MODIFY ("TYPE_INTERNAL" NOT NULL ENABLE);
  ALTER TABLE "DECMGR"."MATRIX_SERVICE_REC_TYPES" MODIFY ("TYPE_DISPLAY" NOT NULL ENABLE);
  ALTER TABLE "DECMGR"."MATRIX_SERVICE_REC_TYPES" MODIFY ("TYPE_RAW" NOT NULL ENABLE);
  ALTER TABLE "DECMGR"."MATRIX_SERVICE_REC_TYPES" MODIFY ("URI" NOT NULL ENABLE);
