--------------------------------------------------------
--  Constraints for Table MATRIX_FOLDERS
--------------------------------------------------------

  ALTER TABLE "DECMGR"."MATRIX_FOLDERS" ADD CONSTRAINT "MATRIX_FOLDERS_PK" PRIMARY KEY ("ID")
  USING INDEX  ENABLE;
  ALTER TABLE "DECMGR"."MATRIX_FOLDERS" ADD CHECK ("XML_DATA" IS NOT NULL) ENABLE;
  ALTER TABLE "DECMGR"."MATRIX_FOLDERS" MODIFY ("XML_DATA" CONSTRAINT "SYS_C0010549" NOT NULL ENABLE);
  ALTER TABLE "DECMGR"."MATRIX_FOLDERS" MODIFY ("MFT_ID" NOT NULL ENABLE);
