--------------------------------------------------------
--  Constraints for Table MATRIX_FOLDER_ITEMS
--------------------------------------------------------

  ALTER TABLE "DECMGR"."MATRIX_FOLDER_ITEMS" ADD CONSTRAINT "MATRIX_FOLDER_ITEMS_PK" PRIMARY KEY ("ID")
  USING INDEX  ENABLE;
  ALTER TABLE "DECMGR"."MATRIX_FOLDER_ITEMS" MODIFY ("MATRIX_RECORD_NUMBER" NOT NULL ENABLE);
  ALTER TABLE "DECMGR"."MATRIX_FOLDER_ITEMS" MODIFY ("PFI_ID" NOT NULL ENABLE);
  ALTER TABLE "DECMGR"."MATRIX_FOLDER_ITEMS" MODIFY ("MF_ID" NOT NULL ENABLE);
