--------------------------------------------------------
--  Constraints for Table MEDIA_FOOTNOTE_COUNTRIES
--------------------------------------------------------

  ALTER TABLE "SDBPUBMGR"."MEDIA_FOOTNOTE_COUNTRIES" ADD CONSTRAINT "MEDIA_FOOTNOTE_COUNTRIES_CK1" CHECK (
    (status_control = 'C' AND end_datetime IS NULL)
    OR
    (status_control IS NULL AND end_datetime IS NOT NULL)
  ) ENABLE;
  ALTER TABLE "SDBPUBMGR"."MEDIA_FOOTNOTE_COUNTRIES" ADD CONSTRAINT "MEDIA_FOOTNOTE_COUNTRIES_PK" PRIMARY KEY ("ID")
  USING INDEX  ENABLE;
  ALTER TABLE "SDBPUBMGR"."MEDIA_FOOTNOTE_COUNTRIES" MODIFY ("START_DATETIME" NOT NULL ENABLE);
  ALTER TABLE "SDBPUBMGR"."MEDIA_FOOTNOTE_COUNTRIES" MODIFY ("COUNTRY_NAME" NOT NULL ENABLE);
  ALTER TABLE "SDBPUBMGR"."MEDIA_FOOTNOTE_COUNTRIES" MODIFY ("COUNTRY_ID" NOT NULL ENABLE);
  ALTER TABLE "SDBPUBMGR"."MEDIA_FOOTNOTE_COUNTRIES" MODIFY ("MF_GRP_ID" NOT NULL ENABLE);
  ALTER TABLE "SDBPUBMGR"."MEDIA_FOOTNOTE_COUNTRIES" MODIFY ("ELA_GRP_ID" NOT NULL ENABLE);
  ALTER TABLE "SDBPUBMGR"."MEDIA_FOOTNOTE_COUNTRIES" MODIFY ("ID" NOT NULL ENABLE);
