--------------------------------------------------------
--  Constraints for Table MF_EU_BATCH_EVENTS_ERROR
--------------------------------------------------------

  ALTER TABLE "SAVEMGR"."MF_EU_BATCH_EVENTS_ERROR" MODIFY ("RAISING_MODULE_CODE" NOT NULL ENABLE);
  ALTER TABLE "SAVEMGR"."MF_EU_BATCH_EVENTS_ERROR" MODIFY ("RAISING_WUA_ID" NOT NULL ENABLE);
  ALTER TABLE "SAVEMGR"."MF_EU_BATCH_EVENTS_ERROR" MODIFY ("EVENT_LABEL" NOT NULL ENABLE);
  ALTER TABLE "SAVEMGR"."MF_EU_BATCH_EVENTS_ERROR" MODIFY ("EVENT_DATETIME" NOT NULL ENABLE);
  ALTER TABLE "SAVEMGR"."MF_EU_BATCH_EVENTS_ERROR" MODIFY ("ID" NOT NULL ENABLE);
