--------------------------------------------------------
--  Constraints for Table NOTE_UREFS
--------------------------------------------------------

  ALTER TABLE "DECMGR"."NOTE_UREFS" ADD CONSTRAINT "NOTE_UREFS_ID_PK" PRIMARY KEY ("ID")
  USING INDEX  ENABLE;
  ALTER TABLE "DECMGR"."NOTE_UREFS" ADD CONSTRAINT "NOTE_UREFS_CK1" CHECK (( REMINDER_DATETIME IS NOT NULL   AND REMINDER_AUDIENCE IS NOT NULL  AND REMINDER_STATUS IS NOT NULL  AND REMINDER_PROMPT IS NOT NULL )  OR  ( REMINDER_DATETIME IS NULL   AND REMINDER_AUDIENCE IS NULL  AND REMINDER_STATUS IS NULL  AND REMINDER_PROMPT IS NULL )) ENABLE;
  ALTER TABLE "DECMGR"."NOTE_UREFS" MODIFY ("WUA_ID" NOT NULL ENABLE);
  ALTER TABLE "DECMGR"."NOTE_UREFS" MODIFY ("ASSOCIATION_TYPE" NOT NULL ENABLE);
  ALTER TABLE "DECMGR"."NOTE_UREFS" MODIFY ("ASSOCIATION_DATETIME" NOT NULL ENABLE);
  ALTER TABLE "DECMGR"."NOTE_UREFS" MODIFY ("N_ID" NOT NULL ENABLE);
  ALTER TABLE "DECMGR"."NOTE_UREFS" MODIFY ("UREF" NOT NULL ENABLE);
  ALTER TABLE "DECMGR"."NOTE_UREFS" MODIFY ("ID" NOT NULL ENABLE);
