--------------------------------------------------------
--  Constraints for Table NOVATION_DETAILS
--------------------------------------------------------

  ALTER TABLE "PVEXMGR"."NOVATION_DETAILS" MODIFY ("STATUS" NOT NULL ENABLE);
  ALTER TABLE "PVEXMGR"."NOVATION_DETAILS" ADD CONSTRAINT "NOVATION_DETAILS_CK1" CHECK (
    (status_control = 'C' AND end_datetime IS NULL)
    OR
    (status_control IS NULL AND end_datetime IS NOT NULL)
  ) ENABLE;
  ALTER TABLE "PVEXMGR"."NOVATION_DETAILS" ADD CONSTRAINT "NOVATION_DETAILS_PK" PRIMARY KEY ("ID")
  USING INDEX  ENABLE;
  ALTER TABLE "PVEXMGR"."NOVATION_DETAILS" MODIFY ("XML_DATA" NOT NULL ENABLE);
  ALTER TABLE "PVEXMGR"."NOVATION_DETAILS" MODIFY ("CREATED_DATETIME" NOT NULL ENABLE);
  ALTER TABLE "PVEXMGR"."NOVATION_DETAILS" MODIFY ("N_ID" NOT NULL ENABLE);
  ALTER TABLE "PVEXMGR"."NOVATION_DETAILS" MODIFY ("ID" NOT NULL ENABLE);
