--------------------------------------------------------
--  Constraints for Table OGEL_REGISTERED_EXPORTER
--------------------------------------------------------

  ALTER TABLE "WARP_OWNER"."OGEL_REGISTERED_EXPORTER" ADD CONSTRAINT "PK_OGEL_REG_EXPORTER" PRIMARY KEY ("COMPANY_ID", "OGEL_SHORTNAME")
  USING INDEX  ENABLE;
  ALTER TABLE "WARP_OWNER"."OGEL_REGISTERED_EXPORTER" MODIFY ("DATE_OF_REGISTRATION" NOT NULL ENABLE);
  ALTER TABLE "WARP_OWNER"."OGEL_REGISTERED_EXPORTER" MODIFY ("OGEL_SHORTNAME" NOT NULL ENABLE);
  ALTER TABLE "WARP_OWNER"."OGEL_REGISTERED_EXPORTER" MODIFY ("COMPANY_ID" NOT NULL ENABLE);
