--------------------------------------------------------
--  Constraints for Table OGL_TYPE_CONDITIONS
--------------------------------------------------------

  ALTER TABLE "SPIREMGR"."OGL_TYPE_CONDITIONS" ADD CONSTRAINT "OGL_TYPE_CONDITIONS_UK1" UNIQUE ("OGL_TYPE_ID")
  USING INDEX  ENABLE;
  ALTER TABLE "SPIREMGR"."OGL_TYPE_CONDITIONS" ADD CONSTRAINT "OGL_TYPE_CONDITIONS_PK" PRIMARY KEY ("ID")
  USING INDEX  ENABLE;
  ALTER TABLE "SPIREMGR"."OGL_TYPE_CONDITIONS" MODIFY ("OGL_TYPE_ID" NOT NULL ENABLE);
  ALTER TABLE "SPIREMGR"."OGL_TYPE_CONDITIONS" MODIFY ("ID" NOT NULL ENABLE);
