--------------------------------------------------------
--  Constraints for Table OIELS_TBL_APPLICATION_STORE
--------------------------------------------------------

  ALTER TABLE "OIELS_OWNER"."OIELS_TBL_APPLICATION_STORE" MODIFY ("DTI_REFERENCE_ID_REF" NOT NULL ENABLE);
  ALTER TABLE "OIELS_OWNER"."OIELS_TBL_APPLICATION_STORE" MODIFY ("FORM_LENGTH" NOT NULL ENABLE);
  ALTER TABLE "OIELS_OWNER"."OIELS_TBL_APPLICATION_STORE" MODIFY ("APPLICATION_STORE_ID" NOT NULL ENABLE);
