--------------------------------------------------------
--  Constraints for Table OIELS_TBL_SYSTEMUSERS
--------------------------------------------------------

  ALTER TABLE "OIELS_OWNER"."OIELS_TBL_SYSTEMUSERS" MODIFY ("USERROLE_ID_REF" NOT NULL ENABLE);
  ALTER TABLE "OIELS_OWNER"."OIELS_TBL_SYSTEMUSERS" MODIFY ("USER_NAME" NOT NULL ENABLE);
  ALTER TABLE "OIELS_OWNER"."OIELS_TBL_SYSTEMUSERS" MODIFY ("LOGIN_NAME" NOT NULL ENABLE);
  ALTER TABLE "OIELS_OWNER"."OIELS_TBL_SYSTEMUSERS" MODIFY ("SYSTEMUSER_ID" NOT NULL ENABLE);
