--------------------------------------------------------
--  Constraints for Table OIELS_TBL_APP_MATRIX
--------------------------------------------------------

  ALTER TABLE "OIELS_OWNER"."OIELS_TBL_APP_MATRIX" MODIFY ("APP_DESTINATION_ID_REF" NOT NULL ENABLE);
  ALTER TABLE "OIELS_OWNER"."OIELS_TBL_APP_MATRIX" MODIFY ("APP_GOODSITEM_ID_REF" NOT NULL ENABLE);
  ALTER TABLE "OIELS_OWNER"."OIELS_TBL_APP_MATRIX" MODIFY ("DTI_REFERENCE_ID_REF" NOT NULL ENABLE);
  ALTER TABLE "OIELS_OWNER"."OIELS_TBL_APP_MATRIX" MODIFY ("APP_MATRIX_ID" NOT NULL ENABLE);
