--------------------------------------------------------
--  Constraints for Table OIELS_TBL_APPLICATION_CASES
--------------------------------------------------------

  ALTER TABLE "OIELS_OWNER"."OIELS_TBL_APPLICATION_CASES" MODIFY ("AUDITTRAIL_ID_REF" NOT NULL ENABLE);
  ALTER TABLE "OIELS_OWNER"."OIELS_TBL_APPLICATION_CASES" MODIFY ("CASE_REFERENCE_ID" NOT NULL ENABLE);
  ALTER TABLE "OIELS_OWNER"."OIELS_TBL_APPLICATION_CASES" MODIFY ("DTI_REFERENCE_ID_REF" NOT NULL ENABLE);
