--------------------------------------------------------
--  Constraints for Table OIELS_TBL_ADVICERECIEVED
--------------------------------------------------------

  ALTER TABLE "OIELS_OWNER"."OIELS_TBL_ADVICERECIEVED" MODIFY ("ADVICESOUGHT_ID_REF" NOT NULL ENABLE);
  ALTER TABLE "OIELS_OWNER"."OIELS_TBL_ADVICERECIEVED" MODIFY ("ADVISORLIST_ID_REF" NOT NULL ENABLE);
  ALTER TABLE "OIELS_OWNER"."OIELS_TBL_ADVICERECIEVED" MODIFY ("DTI_REFERENCE_ID_REF" NOT NULL ENABLE);
  ALTER TABLE "OIELS_OWNER"."OIELS_TBL_ADVICERECIEVED" MODIFY ("ADVICERECIEVED_ID" NOT NULL ENABLE);
