--------------------------------------------------------
--  Constraints for Table OIELS_TBL_GOODS_RATING
--------------------------------------------------------

  ALTER TABLE "OIELS_OWNER"."OIELS_TBL_GOODS_RATING" MODIFY ("GOODSITEM_ID_REF" NOT NULL ENABLE);
  ALTER TABLE "OIELS_OWNER"."OIELS_TBL_GOODS_RATING" MODIFY ("GOODSRATINGLIST_ID_REF" NOT NULL ENABLE);
  ALTER TABLE "OIELS_OWNER"."OIELS_TBL_GOODS_RATING" MODIFY ("GOODS_RATING_ID" NOT NULL ENABLE);
