--------------------------------------------------------
--  Constraints for Table OIELS_TBL_CIRCULATIONMATRIX
--------------------------------------------------------

  ALTER TABLE "OIELS_OWNER"."OIELS_TBL_CIRCULATIONMATRIX" MODIFY ("ADVISORLIST_ID_REF" NOT NULL ENABLE);
  ALTER TABLE "OIELS_OWNER"."OIELS_TBL_CIRCULATIONMATRIX" MODIFY ("GOODSTYPELIST_ID_REF" NOT NULL ENABLE);
  ALTER TABLE "OIELS_OWNER"."OIELS_TBL_CIRCULATIONMATRIX" MODIFY ("CIRCULATIONMATRIX_ID" NOT NULL ENABLE);
