--------------------------------------------------------
--  Constraints for Table OIELS_TBL_MATRIX
--------------------------------------------------------

  ALTER TABLE "OIELS_OWNER"."OIELS_TBL_MATRIX" MODIFY ("DESTINATION_ID_REF" NOT NULL ENABLE);
  ALTER TABLE "OIELS_OWNER"."OIELS_TBL_MATRIX" MODIFY ("GOODSITEM_ID_REF" NOT NULL ENABLE);
  ALTER TABLE "OIELS_OWNER"."OIELS_TBL_MATRIX" MODIFY ("DTI_REFERENCE_ID_REF" NOT NULL ENABLE);
  ALTER TABLE "OIELS_OWNER"."OIELS_TBL_MATRIX" MODIFY ("MATRIX_ID" NOT NULL ENABLE);
