--------------------------------------------------------
--  Constraints for Table OIELS_TBL_ARS_REPORTS
--------------------------------------------------------

  ALTER TABLE "OIELS_OWNER"."OIELS_TBL_ARS_REPORTS" MODIFY ("GOODSRATINGLIST_ID_REF" NOT NULL ENABLE);
  ALTER TABLE "OIELS_OWNER"."OIELS_TBL_ARS_REPORTS" MODIFY ("REPORT_ID" NOT NULL ENABLE);
  ALTER TABLE "OIELS_OWNER"."OIELS_TBL_ARS_REPORTS" MODIFY ("GOODSITEM_ID_REF" NOT NULL ENABLE);
