--------------------------------------------------------
--  Constraints for Table OIELS_TBL_LICENCEPROVISO
--------------------------------------------------------

  ALTER TABLE "OIELS_OWNER"."OIELS_TBL_LICENCEPROVISO" MODIFY ("DESTINATION_ID_REF" NOT NULL ENABLE);
  ALTER TABLE "OIELS_OWNER"."OIELS_TBL_LICENCEPROVISO" MODIFY ("DTI_REFERENCE_ID_REF" NOT NULL ENABLE);
  ALTER TABLE "OIELS_OWNER"."OIELS_TBL_LICENCEPROVISO" MODIFY ("PROVISO_ID" NOT NULL ENABLE);
