--------------------------------------------------------
--  Constraints for Table OIELS_TBL_COMPANY_AUXINFO
--------------------------------------------------------

  ALTER TABLE "OIELS_OWNER"."OIELS_TBL_COMPANY_AUXINFO" MODIFY ("DTI_REFERENCE_ID_REF" NOT NULL ENABLE);
  ALTER TABLE "OIELS_OWNER"."OIELS_TBL_COMPANY_AUXINFO" MODIFY ("MAINCOMPANYINFO_ID_REF" NOT NULL ENABLE);
  ALTER TABLE "OIELS_OWNER"."OIELS_TBL_COMPANY_AUXINFO" MODIFY ("AUXCOMPANYINFO_ID" NOT NULL ENABLE);
