--------------------------------------------------------
--  Constraints for Table OIELS_TBL_GOODSTYPE
--------------------------------------------------------

  ALTER TABLE "OIELS_OWNER"."OIELS_TBL_GOODSTYPE" MODIFY ("GOODSTYPELIST_ID_REF" NOT NULL ENABLE);
  ALTER TABLE "OIELS_OWNER"."OIELS_TBL_GOODSTYPE" MODIFY ("DTI_REFERENCE_ID_REF" NOT NULL ENABLE);
  ALTER TABLE "OIELS_OWNER"."OIELS_TBL_GOODSTYPE" MODIFY ("GOODSTYPE_ID" NOT NULL ENABLE);
