--------------------------------------------------------
--  Constraints for Table OIELS_TBL_LICENCE_REMINDER
--------------------------------------------------------

  ALTER TABLE "OIELS_OWNER"."OIELS_TBL_LICENCE_REMINDER" MODIFY ("LICENCE_REMINDER_MONTHS_DUE" NOT NULL ENABLE);
  ALTER TABLE "OIELS_OWNER"."OIELS_TBL_LICENCE_REMINDER" MODIFY ("LICENCE_EXPIRY_DATE" NOT NULL ENABLE);
  ALTER TABLE "OIELS_OWNER"."OIELS_TBL_LICENCE_REMINDER" MODIFY ("LICENCE_ID_REF" NOT NULL ENABLE);
  ALTER TABLE "OIELS_OWNER"."OIELS_TBL_LICENCE_REMINDER" MODIFY ("LICENCE_REMINDER_ID" NOT NULL ENABLE);
