--------------------------------------------------------
--  Constraints for Table OIELS_TBL_ADVICESOUGHT
--------------------------------------------------------

  ALTER TABLE "OIELS_OWNER"."OIELS_TBL_ADVICESOUGHT" MODIFY ("ADVISORLIST_ID_REF" NOT NULL ENABLE);
  ALTER TABLE "OIELS_OWNER"."OIELS_TBL_ADVICESOUGHT" MODIFY ("DTI_REFERENCE_ID_REF" NOT NULL ENABLE);
  ALTER TABLE "OIELS_OWNER"."OIELS_TBL_ADVICESOUGHT" MODIFY ("ADVICESOUGHT_ID" NOT NULL ENABLE);
