--------------------------------------------------------
--  Constraints for Table OIELS_TBL_ADDITIONALQUESTION
--------------------------------------------------------

  ALTER TABLE "OIELS_OWNER"."OIELS_TBL_ADDITIONALQUESTION" MODIFY ("ADDITIONALQUESTIONB_ID_REF" NOT NULL ENABLE);
  ALTER TABLE "OIELS_OWNER"."OIELS_TBL_ADDITIONALQUESTION" MODIFY ("DTI_REFERENCE_ID_REF" NOT NULL ENABLE);
  ALTER TABLE "OIELS_OWNER"."OIELS_TBL_ADDITIONALQUESTION" MODIFY ("ADDITIONALQUESTION_ID" NOT NULL ENABLE);
