--------------------------------------------------------
--  Constraints for Table ORGANISATION_GROUP_TYPES
--------------------------------------------------------

  ALTER TABLE "DECMGR"."ORGANISATION_GROUP_TYPES" ADD CONSTRAINT "ORG_GRP_TY_PK" PRIMARY KEY ("ORG_GRP_TYPE")
  USING INDEX  ENABLE;
  ALTER TABLE "DECMGR"."ORGANISATION_GROUP_TYPES" MODIFY ("DESCRIPTION" NOT NULL ENABLE);
  ALTER TABLE "DECMGR"."ORGANISATION_GROUP_TYPES" MODIFY ("ORG_GRP_TYPE" NOT NULL ENABLE);
