--------------------------------------------------------
--  Constraints for Table PAGE_CONTENT_TYPES
--------------------------------------------------------

  ALTER TABLE "DECMGR"."PAGE_CONTENT_TYPES" ADD CONSTRAINT "PAGE_CONTENT_TYPES_PK" PRIMARY KEY ("PAGE_CONTENT_TYPE")
  USING INDEX  ENABLE;
  ALTER TABLE "DECMGR"."PAGE_CONTENT_TYPES" MODIFY ("TITLE" NOT NULL ENABLE);
  ALTER TABLE "DECMGR"."PAGE_CONTENT_TYPES" MODIFY ("PAGE_CONTENT_TYPE" NOT NULL ENABLE);
