--------------------------------------------------------
--  Constraints for Table PAGINATION_CACHE
--------------------------------------------------------

  ALTER TABLE "FOXMGR"."PAGINATION_CACHE" ADD CONSTRAINT "PAGINATION_CACHE_PK" PRIMARY KEY ("DBI_NAME", "QRY_NAME", "INVOKE_NAME", "MATCH_FOXID", "ROW_NUM")
  USING INDEX  ENABLE;
  ALTER TABLE "FOXMGR"."PAGINATION_CACHE" MODIFY ("DATA" NOT NULL ENABLE);
  ALTER TABLE "FOXMGR"."PAGINATION_CACHE" MODIFY ("CREATED_DATETIME" NOT NULL ENABLE);
  ALTER TABLE "FOXMGR"."PAGINATION_CACHE" MODIFY ("ROW_NUM" NOT NULL ENABLE);
  ALTER TABLE "FOXMGR"."PAGINATION_CACHE" MODIFY ("THREAD_ID" NOT NULL ENABLE);
  ALTER TABLE "FOXMGR"."PAGINATION_CACHE" MODIFY ("SESSION_ID" NOT NULL ENABLE);
  ALTER TABLE "FOXMGR"."PAGINATION_CACHE" MODIFY ("MATCH_FOXID" NOT NULL ENABLE);
  ALTER TABLE "FOXMGR"."PAGINATION_CACHE" MODIFY ("INVOKE_NAME" NOT NULL ENABLE);
  ALTER TABLE "FOXMGR"."PAGINATION_CACHE" MODIFY ("QRY_NAME" NOT NULL ENABLE);
  ALTER TABLE "FOXMGR"."PAGINATION_CACHE" MODIFY ("DBI_NAME" NOT NULL ENABLE);
