--------------------------------------------------------
--  Constraints for Table PATCH_RUNS
--------------------------------------------------------

  ALTER TABLE "PROMOTEMGR"."PATCH_RUNS" ADD CONSTRAINT "PATCH_RUNS_CK2" CHECK (status IN('STARTED', 'COMPLETE', 'FAILED')) ENABLE;
  ALTER TABLE "PROMOTEMGR"."PATCH_RUNS" ADD CONSTRAINT "PATCH_RUNS_CK1" CHECK (ignore_flag IS NULL OR ignore_flag = 'Y') ENABLE;
  ALTER TABLE "PROMOTEMGR"."PATCH_RUNS" ADD CONSTRAINT "PATCH_RUNS_PK" PRIMARY KEY ("ID")
  USING INDEX  ENABLE;
  ALTER TABLE "PROMOTEMGR"."PATCH_RUNS" MODIFY ("FILE_HASH" NOT NULL ENABLE);
  ALTER TABLE "PROMOTEMGR"."PATCH_RUNS" MODIFY ("STATUS" NOT NULL ENABLE);
  ALTER TABLE "PROMOTEMGR"."PATCH_RUNS" MODIFY ("START_TIMESTAMP" NOT NULL ENABLE);
  ALTER TABLE "PROMOTEMGR"."PATCH_RUNS" MODIFY ("PROMOTION_LOAD_SEQUENCE" NOT NULL ENABLE);
  ALTER TABLE "PROMOTEMGR"."PATCH_RUNS" MODIFY ("PROMOTION_LABEL" NOT NULL ENABLE);
  ALTER TABLE "PROMOTEMGR"."PATCH_RUNS" MODIFY ("PROMOTION_RUN_ID" NOT NULL ENABLE);
  ALTER TABLE "PROMOTEMGR"."PATCH_RUNS" MODIFY ("PATCH_DESCRIPTION" NOT NULL ENABLE);
  ALTER TABLE "PROMOTEMGR"."PATCH_RUNS" MODIFY ("PATCH_NUMBER" NOT NULL ENABLE);
  ALTER TABLE "PROMOTEMGR"."PATCH_RUNS" MODIFY ("PATCH_LABEL" NOT NULL ENABLE);
