--------------------------------------------------------
--  Constraints for Table PATCH_RUN_STATEMENTS
--------------------------------------------------------

  ALTER TABLE "PROMOTEMGR"."PATCH_RUN_STATEMENTS" ADD CONSTRAINT "PATCH_RUN_STATEMENTS_CK2" CHECK (status IN('STARTED', 'COMPLETE', 'FAILED')) ENABLE;
  ALTER TABLE "PROMOTEMGR"."PATCH_RUN_STATEMENTS" ADD CONSTRAINT "PATCH_RUN_STATEMENTS_CK1" CHECK (ignore_flag IS NULL OR ignore_flag = 'Y') ENABLE;
  ALTER TABLE "PROMOTEMGR"."PATCH_RUN_STATEMENTS" MODIFY ("STATEMENT_SQL" NOT NULL ENABLE);
  ALTER TABLE "PROMOTEMGR"."PATCH_RUN_STATEMENTS" MODIFY ("STATUS" NOT NULL ENABLE);
  ALTER TABLE "PROMOTEMGR"."PATCH_RUN_STATEMENTS" MODIFY ("START_TIMESTAMP" NOT NULL ENABLE);
  ALTER TABLE "PROMOTEMGR"."PATCH_RUN_STATEMENTS" MODIFY ("SCRIPT_SEQUENCE" NOT NULL ENABLE);
  ALTER TABLE "PROMOTEMGR"."PATCH_RUN_STATEMENTS" MODIFY ("PATCH_RUN_ID" NOT NULL ENABLE);
  ALTER TABLE "PROMOTEMGR"."PATCH_RUN_STATEMENTS" MODIFY ("PATCH_NUMBER" NOT NULL ENABLE);
  ALTER TABLE "PROMOTEMGR"."PATCH_RUN_STATEMENTS" MODIFY ("PATCH_LABEL" NOT NULL ENABLE);
  ALTER TABLE "PROMOTEMGR"."PATCH_RUN_STATEMENTS" MODIFY ("STATEMENT_HASH" NOT NULL ENABLE);
