--------------------------------------------------------
--  Constraints for Table PORTAL_SCHEDULE_EVENTS
--------------------------------------------------------

  ALTER TABLE "DECMGR"."PORTAL_SCHEDULE_EVENTS" ADD CONSTRAINT "PORTAL_SCHEDULE_EVENTS_PK" PRIMARY KEY ("ID")
  USING INDEX  ENABLE;
  ALTER TABLE "DECMGR"."PORTAL_SCHEDULE_EVENTS" ADD CHECK (STATUS IN ('CREATED', 'OPENED', 'ISSUED', 'CANCELLED', 'FILING', 'FILING_ERROR', 'ACCEPTED')) ENABLE;
  ALTER TABLE "DECMGR"."PORTAL_SCHEDULE_EVENTS" MODIFY ("STATUS" NOT NULL ENABLE);
  ALTER TABLE "DECMGR"."PORTAL_SCHEDULE_EVENTS" MODIFY ("START_DATE" NOT NULL ENABLE);
  ALTER TABLE "DECMGR"."PORTAL_SCHEDULE_EVENTS" MODIFY ("EVENT_MNEM" NOT NULL ENABLE);
  ALTER TABLE "DECMGR"."PORTAL_SCHEDULE_EVENTS" MODIFY ("SCHEDULE_SUBJECT_ID" NOT NULL ENABLE);
