--------------------------------------------------------
--  Constraints for Table PORTAL_SCHEDULE_SUBJECTS
--------------------------------------------------------

  ALTER TABLE "DECMGR"."PORTAL_SCHEDULE_SUBJECTS" ADD CONSTRAINT "PORTAL_SCHEDULE_SUBJECTS_PK" PRIMARY KEY ("ID")
  USING INDEX  ENABLE;
  ALTER TABLE "DECMGR"."PORTAL_SCHEDULE_SUBJECTS" MODIFY ("SCOPE_UREF" NOT NULL ENABLE);
  ALTER TABLE "DECMGR"."PORTAL_SCHEDULE_SUBJECTS" MODIFY ("PORTAL_SCHEDULE_INSTANCE" NOT NULL ENABLE);
