--------------------------------------------------------
--  Constraints for Table PORTAL_FOLDER_ABSTRACTS
--------------------------------------------------------

  ALTER TABLE "DECMGR"."PORTAL_FOLDER_ABSTRACTS" ADD CONSTRAINT "PK_PORTAL_FOLDER_ABSTRACTS" PRIMARY KEY ("ID")
  USING INDEX  ENABLE;
  ALTER TABLE "DECMGR"."PORTAL_FOLDER_ABSTRACTS" ADD CHECK ("XML_DATA" IS NOT NULL) ENABLE;
  ALTER TABLE "DECMGR"."PORTAL_FOLDER_ABSTRACTS" MODIFY ("XML_DATA" NOT NULL ENABLE);
  ALTER TABLE "DECMGR"."PORTAL_FOLDER_ABSTRACTS" MODIFY ("PF_ID" NOT NULL ENABLE);
  ALTER TABLE "DECMGR"."PORTAL_FOLDER_ABSTRACTS" MODIFY ("ID" NOT NULL ENABLE);
