--------------------------------------------------------
--  Constraints for Table PORTAL_SCHEDULE_INSTANCES
--------------------------------------------------------

  ALTER TABLE "DECMGR"."PORTAL_SCHEDULE_INSTANCES" ADD CONSTRAINT "PORTAL_SCHEDULE_INSTANCES_UK1" UNIQUE ("ORIGIN_DATE", "SCHEDULE_GROUP_ID")
  USING INDEX  ENABLE;
  ALTER TABLE "DECMGR"."PORTAL_SCHEDULE_INSTANCES" ADD CONSTRAINT "PORTAL_SCHEDULE_INSTANCES_PK" PRIMARY KEY ("ID")
  USING INDEX  ENABLE;
  ALTER TABLE "DECMGR"."PORTAL_SCHEDULE_INSTANCES" MODIFY ("SCHEDULE_GROUP_ID" NOT NULL ENABLE);
  ALTER TABLE "DECMGR"."PORTAL_SCHEDULE_INSTANCES" MODIFY ("ORIGIN_DATE" NOT NULL ENABLE);
