--------------------------------------------------------
--  Constraints for Table PORTAL_SCHEDULE_GROUPS
--------------------------------------------------------

  ALTER TABLE "DECMGR"."PORTAL_SCHEDULE_GROUPS" ADD CONSTRAINT "PORTAL_SCHEDULE_GROUPS_PK" PRIMARY KEY ("ID")
  USING INDEX  ENABLE;
  ALTER TABLE "DECMGR"."PORTAL_SCHEDULE_GROUPS" MODIFY ("TITLE" NOT NULL ENABLE);
  ALTER TABLE "DECMGR"."PORTAL_SCHEDULE_GROUPS" MODIFY ("PORTAL_SCHEDULE_TYPE" NOT NULL ENABLE);
