--------------------------------------------------------
--  Constraints for Table PORTAL_SCHEDULE_SUBJECT_NOTES
--------------------------------------------------------

  ALTER TABLE "DECMGR"."PORTAL_SCHEDULE_SUBJECT_NOTES" ADD CONSTRAINT "PORTAL_SCHED_SUBJ_NOTES_UK" UNIQUE ("SUBJECT_UREF")
  USING INDEX  ENABLE;
  ALTER TABLE "DECMGR"."PORTAL_SCHEDULE_SUBJECT_NOTES" MODIFY ("METADATA_XML" NOT NULL ENABLE);
  ALTER TABLE "DECMGR"."PORTAL_SCHEDULE_SUBJECT_NOTES" MODIFY ("SUBJECT_UREF" NOT NULL ENABLE);
