--------------------------------------------------------
--  Constraints for Table POSTPATCHCORE000330_BK1
--------------------------------------------------------

  ALTER TABLE "SAVEMGR"."POSTPATCHCORE000330_BK1" MODIFY ("START_DATETIME" NOT NULL ENABLE);
  ALTER TABLE "SAVEMGR"."POSTPATCHCORE000330_BK1" MODIFY ("STATUS" NOT NULL ENABLE);
  ALTER TABLE "SAVEMGR"."POSTPATCHCORE000330_BK1" MODIFY ("TC_ID" NOT NULL ENABLE);
  ALTER TABLE "SAVEMGR"."POSTPATCHCORE000330_BK1" MODIFY ("ID" NOT NULL ENABLE);
