--------------------------------------------------------
--  Constraints for Table PRAGMA_RESPONSE_SESSIONS
--------------------------------------------------------

  ALTER TABLE "SECUREMGR"."PRAGMA_RESPONSE_SESSIONS" ADD CONSTRAINT "PRAGMA_RESPONSE_SESSIONS_PK" PRIMARY KEY ("ID")
  USING INDEX  ENABLE;
  ALTER TABLE "SECUREMGR"."PRAGMA_RESPONSE_SESSIONS" MODIFY ("SESSION_DOM" NOT NULL ENABLE);
  ALTER TABLE "SECUREMGR"."PRAGMA_RESPONSE_SESSIONS" MODIFY ("ID" NOT NULL ENABLE);
