--------------------------------------------------------
--  Constraints for Table PROMOTION_LABELS
--------------------------------------------------------

  ALTER TABLE "PROMOTEMGR"."PROMOTION_LABELS" ADD CONSTRAINT "PROMOTION_LABELS_PK" PRIMARY KEY ("LABEL")
  USING INDEX  ENABLE;
  ALTER TABLE "PROMOTEMGR"."PROMOTION_LABELS" MODIFY ("LAST_PROMOTED_DATETIME" NOT NULL ENABLE);
  ALTER TABLE "PROMOTEMGR"."PROMOTION_LABELS" MODIFY ("CREATED_DATETIME" NOT NULL ENABLE);
