--------------------------------------------------------
--  Constraints for Table PROMOTION_RUNS
--------------------------------------------------------

  ALTER TABLE "PROMOTEMGR"."PROMOTION_RUNS" ADD CONSTRAINT "PROMOTION_RUNS_CK2" CHECK (status IN('STARTED', 'COMPLETE', 'FAILED')) ENABLE;
  ALTER TABLE "PROMOTEMGR"."PROMOTION_RUNS" ADD CONSTRAINT "PROMOTION_RUNS_CK1" CHECK (ignore_flag IS NULL OR ignore_flag = 'Y') ENABLE;
  ALTER TABLE "PROMOTEMGR"."PROMOTION_RUNS" ADD CONSTRAINT "PROMOTION_RUNS_PK" PRIMARY KEY ("ID")
  USING INDEX  ENABLE;
  ALTER TABLE "PROMOTEMGR"."PROMOTION_RUNS" MODIFY ("START_DATETIME" NOT NULL ENABLE);
  ALTER TABLE "PROMOTEMGR"."PROMOTION_RUNS" MODIFY ("SCRIPTRUNNER_VERSION" NOT NULL ENABLE);
  ALTER TABLE "PROMOTEMGR"."PROMOTION_RUNS" MODIFY ("PROMOTION_LABEL" NOT NULL ENABLE);
