--------------------------------------------------------
--  Constraints for Table PV_EX_APP_DETAILS
--------------------------------------------------------

  ALTER TABLE "PVEXMGR"."PV_EX_APP_DETAILS" ADD CONSTRAINT "PEA_DETAILS_CK3" CHECK (status IN ('DRAFT','DELETED','SUBMITTED','CURRENT', 'FINAL')) ENABLE;
  ALTER TABLE "PVEXMGR"."PV_EX_APP_DETAILS" ADD CONSTRAINT "PEA_DETAILS_CK1" CHECK (
    (status_control IN ('C','D','A') AND end_datetime IS NULL)
  OR 
    (status_control IS NULL AND end_datetime IS NOT NULL)
  ) ENABLE;
  ALTER TABLE "PVEXMGR"."PV_EX_APP_DETAILS" ADD CONSTRAINT "PEA_DETAILS_PK" PRIMARY KEY ("ID")
  USING INDEX  ENABLE;
  ALTER TABLE "PVEXMGR"."PV_EX_APP_DETAILS" MODIFY ("XML_DATA" NOT NULL ENABLE);
  ALTER TABLE "PVEXMGR"."PV_EX_APP_DETAILS" MODIFY ("VERSION_NO" NOT NULL ENABLE);
  ALTER TABLE "PVEXMGR"."PV_EX_APP_DETAILS" MODIFY ("STATUS" NOT NULL ENABLE);
  ALTER TABLE "PVEXMGR"."PV_EX_APP_DETAILS" MODIFY ("START_DATETIME" NOT NULL ENABLE);
  ALTER TABLE "PVEXMGR"."PV_EX_APP_DETAILS" MODIFY ("PEA_ID" NOT NULL ENABLE);
  ALTER TABLE "PVEXMGR"."PV_EX_APP_DETAILS" MODIFY ("ID" NOT NULL ENABLE);
