--------------------------------------------------------
--  Constraints for Table PV_EX_APPLICATIONS
--------------------------------------------------------

  ALTER TABLE "PVEXMGR"."PV_EX_APPLICATIONS" ADD CONSTRAINT "PEA_CK1" CHECK (case_status IN ('DRAFT','DELETED','CASE_PROCESSING','AWAITING_POST','COMPLETE')) ENABLE;
  ALTER TABLE "PVEXMGR"."PV_EX_APPLICATIONS" ADD CONSTRAINT "PEA_PK" PRIMARY KEY ("ID")
  USING INDEX  ENABLE;
  ALTER TABLE "PVEXMGR"."PV_EX_APPLICATIONS" MODIFY ("CASE_STATUS" NOT NULL ENABLE);
  ALTER TABLE "PVEXMGR"."PV_EX_APPLICATIONS" MODIFY ("APPLICATION_TYPE" NOT NULL ENABLE);
  ALTER TABLE "PVEXMGR"."PV_EX_APPLICATIONS" MODIFY ("SDD_ID" NOT NULL ENABLE);
  ALTER TABLE "PVEXMGR"."PV_EX_APPLICATIONS" MODIFY ("ID" NOT NULL ENABLE);
