--------------------------------------------------------
--  Constraints for Table REASONS_FOR_REFUSAL
--------------------------------------------------------

  ALTER TABLE "SDBPUBMGR"."REASONS_FOR_REFUSAL" ADD CONSTRAINT "REASONS_FOR_REFUSAL_PK" PRIMARY KEY ("GI_ID", "REASON_FOR_REFUSAL")
  USING INDEX  ENABLE;
  ALTER TABLE "SDBPUBMGR"."REASONS_FOR_REFUSAL" MODIFY ("REASON_FOR_REFUSAL" NOT NULL ENABLE);
  ALTER TABLE "SDBPUBMGR"."REASONS_FOR_REFUSAL" MODIFY ("GI_ID" NOT NULL ENABLE);
