--------------------------------------------------------
--  Constraints for Table REF_COUNTRY_MAPPING_SOURCE
--------------------------------------------------------

  ALTER TABLE "SDBMGR"."REF_COUNTRY_MAPPING_SOURCE" ADD CONSTRAINT "REF_COUNTRY_MAPPING_SOURCE_PK" PRIMARY KEY ("COUNTRY_ID")
  USING INDEX  ENABLE;
  ALTER TABLE "SDBMGR"."REF_COUNTRY_MAPPING_SOURCE" MODIFY ("SDB_COUNTRY_NAME" NOT NULL ENABLE);
  ALTER TABLE "SDBMGR"."REF_COUNTRY_MAPPING_SOURCE" MODIFY ("COUNTRY_ID" NOT NULL ENABLE);
