--------------------------------------------------------
--  Constraints for Table REF_DO_NOT_REPORT_VALUES
--------------------------------------------------------

  ALTER TABLE "SDBMGR"."REF_DO_NOT_REPORT_VALUES" ADD CONSTRAINT "REF_DO_NOT_REPORT_VALUES_PK" PRIMARY KEY ("DNR_TYPE", "DNR_VALUE")
  USING INDEX  ENABLE;
  ALTER TABLE "SDBMGR"."REF_DO_NOT_REPORT_VALUES" MODIFY ("DNR_VALUE" NOT NULL ENABLE);
  ALTER TABLE "SDBMGR"."REF_DO_NOT_REPORT_VALUES" MODIFY ("DNR_TYPE" NOT NULL ENABLE);
