--------------------------------------------------------
--  Constraints for Table REF_COUNTRY_MAPPINGS
--------------------------------------------------------

  ALTER TABLE "SDBPUBMGR"."REF_COUNTRY_MAPPINGS" ADD CONSTRAINT "REF_COUNTRY_MAPPINGS_PK" PRIMARY KEY ("COUNTRY_ID")
  USING INDEX  ENABLE;
  ALTER TABLE "SDBPUBMGR"."REF_COUNTRY_MAPPINGS" MODIFY ("COUNTRY_NAME" NOT NULL ENABLE);
  ALTER TABLE "SDBPUBMGR"."REF_COUNTRY_MAPPINGS" MODIFY ("COUNTRY_ID" NOT NULL ENABLE);
