--------------------------------------------------------
--  Constraints for Table REPORT_RUNS
--------------------------------------------------------

  ALTER TABLE "REPORTMGR"."REPORT_RUNS" ADD CONSTRAINT "REPORT_RUNS_PK" PRIMARY KEY ("ID")
  USING INDEX  ENABLE;
  ALTER TABLE "REPORTMGR"."REPORT_RUNS" MODIFY ("STATUS" NOT NULL ENABLE);
  ALTER TABLE "REPORTMGR"."REPORT_RUNS" ADD CONSTRAINT "REPORT_RUNS_CHK3" CHECK (retention_housekeeping_done IS NULL OR retention_days IS NOT NULL) ENABLE;
  ALTER TABLE "REPORTMGR"."REPORT_RUNS" ADD CONSTRAINT "REPORT_RUNS_CHK2" CHECK (status in ('PENDING','FAILED','COMPLETE','PROCESSING')) ENABLE;
  ALTER TABLE "REPORTMGR"."REPORT_RUNS" MODIFY ("REPORT_SERVICE_QUEUE" NOT NULL ENABLE);
