--------------------------------------------------------
--  Constraints for Table REPORT_PARAMETER_SETS
--------------------------------------------------------

  ALTER TABLE "REPORTMGR"."REPORT_PARAMETER_SETS" ADD CONSTRAINT "REPORT_PARAMETER_SETS_PK" PRIMARY KEY ("ID")
  USING INDEX  ENABLE;
  ALTER TABLE "REPORTMGR"."REPORT_PARAMETER_SETS" MODIFY ("XML_DATA" NOT NULL ENABLE);
  ALTER TABLE "REPORTMGR"."REPORT_PARAMETER_SETS" MODIFY ("CREATED_DATETIME" NOT NULL ENABLE);
  ALTER TABLE "REPORTMGR"."REPORT_PARAMETER_SETS" MODIFY ("TITLE" NOT NULL ENABLE);
  ALTER TABLE "REPORTMGR"."REPORT_PARAMETER_SETS" MODIFY ("WUA_ID" NOT NULL ENABLE);
  ALTER TABLE "REPORTMGR"."REPORT_PARAMETER_SETS" MODIFY ("DOMAIN" NOT NULL ENABLE);
