--------------------------------------------------------
--  Constraints for Table REPORT_PARTS_OUTPUTS
--------------------------------------------------------

  ALTER TABLE "REPORTMGR"."REPORT_PARTS_OUTPUTS" MODIFY ("RP_ID" NOT NULL ENABLE);
  ALTER TABLE "REPORTMGR"."REPORT_PARTS_OUTPUTS" ADD CONSTRAINT "REPORT_PARTS_OUTPUTS_CHK2" CHECK (   (output_type = 'PDF' AND di_id IS NOT NULL)
                                                OR (output_type != 'PDF' AND di_id IS NULL)
                                               ) ENABLE;
  ALTER TABLE "REPORTMGR"."REPORT_PARTS_OUTPUTS" ADD CONSTRAINT "REPORT_PARTS_OUTPUTS_CHK1" CHECK (output_type IN ('SYLK', 'CSV', 'XML_XLS', 'PDF', 'JASPER_PDF', 'JASPER_HTML', 'JASPER_XLS')) ENABLE;
  ALTER TABLE "REPORTMGR"."REPORT_PARTS_OUTPUTS" ADD CONSTRAINT "REPORT_PARTS_OUTPUTS_PK" PRIMARY KEY ("ID")
  USING INDEX  ENABLE;
  ALTER TABLE "REPORTMGR"."REPORT_PARTS_OUTPUTS" MODIFY ("OUTPUT_TYPE" NOT NULL ENABLE);
  ALTER TABLE "REPORTMGR"."REPORT_PARTS_OUTPUTS" MODIFY ("ID" NOT NULL ENABLE);
