--------------------------------------------------------
--  Constraints for Table REQUESTED_BATCH_REPORTS
--------------------------------------------------------

  ALTER TABLE "SDBMGR"."REQUESTED_BATCH_REPORTS" ADD CONSTRAINT "REQUESTED_BATCH_REPORTS_PK" PRIMARY KEY ("RR_ID", "BATCH_ID")
  USING INDEX  ENABLE;
  ALTER TABLE "SDBMGR"."REQUESTED_BATCH_REPORTS" MODIFY ("BATCH_ID" NOT NULL ENABLE);
  ALTER TABLE "SDBMGR"."REQUESTED_BATCH_REPORTS" MODIFY ("RR_ID" NOT NULL ENABLE);
