--------------------------------------------------------
--  Constraints for Table RESOURCE_PEOPLE_BATCH_LOAD
--------------------------------------------------------

  ALTER TABLE "DECMGR"."RESOURCE_PEOPLE_BATCH_LOAD" MODIFY ("PERSON_TYPE" NOT NULL ENABLE);
  ALTER TABLE "DECMGR"."RESOURCE_PEOPLE_BATCH_LOAD" MODIFY ("STATUS" NOT NULL ENABLE);
  ALTER TABLE "DECMGR"."RESOURCE_PEOPLE_BATCH_LOAD" MODIFY ("EMAIL_ADDRESS" NOT NULL ENABLE);
  ALTER TABLE "DECMGR"."RESOURCE_PEOPLE_BATCH_LOAD" MODIFY ("TEL_NO" NOT NULL ENABLE);
  ALTER TABLE "DECMGR"."RESOURCE_PEOPLE_BATCH_LOAD" MODIFY ("PERSON_NAME" NOT NULL ENABLE);
  ALTER TABLE "DECMGR"."RESOURCE_PEOPLE_BATCH_LOAD" MODIFY ("ORG_NAME" NOT NULL ENABLE);
