--------------------------------------------------------
--  Constraints for Table RESOURCE_USAGES
--------------------------------------------------------

  ALTER TABLE "DECMGR"."RESOURCE_USAGES" ADD CONSTRAINT "RESOURCE_USAGES_UK1" UNIQUE ("RES_ID", "UREF", "START_DATETIME")
  USING INDEX (CREATE UNIQUE INDEX "DECMGR"."RESOURCE_USAGES_PK" ON "DECMGR"."RESOURCE_USAGES" ("UREF", "RES_ID", "START_DATETIME") 
  )  ENABLE;
  ALTER TABLE "DECMGR"."RESOURCE_USAGES" ADD CONSTRAINT "RESOURCE_USAGES_PK" PRIMARY KEY ("UREF", "RES_ID", "START_DATETIME")
  USING INDEX  ENABLE;
  ALTER TABLE "DECMGR"."RESOURCE_USAGES" MODIFY ("PURPOSE" NOT NULL ENABLE);
  ALTER TABLE "DECMGR"."RESOURCE_USAGES" MODIFY ("START_DATETIME" NOT NULL ENABLE);
  ALTER TABLE "DECMGR"."RESOURCE_USAGES" MODIFY ("UREF" NOT NULL ENABLE);
  ALTER TABLE "DECMGR"."RESOURCE_USAGES" MODIFY ("RES_ID" NOT NULL ENABLE);
