--------------------------------------------------------
--  Constraints for Table RESOURCE_PEOPLE_AUTHENTICATION
--------------------------------------------------------

  ALTER TABLE "DECMGR"."RESOURCE_PEOPLE_AUTHENTICATION" ADD CONSTRAINT "RESOURCE_PEOPLE_AUTH_PK" PRIMARY KEY ("ID")
  USING INDEX  ENABLE;
  ALTER TABLE "DECMGR"."RESOURCE_PEOPLE_AUTHENTICATION" MODIFY ("RP_ID" NOT NULL ENABLE);
  ALTER TABLE "DECMGR"."RESOURCE_PEOPLE_AUTHENTICATION" MODIFY ("LOGIN_ID" NOT NULL ENABLE);
  ALTER TABLE "DECMGR"."RESOURCE_PEOPLE_AUTHENTICATION" MODIFY ("USER_ID" NOT NULL ENABLE);
  ALTER TABLE "DECMGR"."RESOURCE_PEOPLE_AUTHENTICATION" MODIFY ("DOMAIN" NOT NULL ENABLE);
  ALTER TABLE "DECMGR"."RESOURCE_PEOPLE_AUTHENTICATION" MODIFY ("AUTH_SCHEME" NOT NULL ENABLE);
  ALTER TABLE "DECMGR"."RESOURCE_PEOPLE_AUTHENTICATION" MODIFY ("START_DATETIME" NOT NULL ENABLE);
  ALTER TABLE "DECMGR"."RESOURCE_PEOPLE_AUTHENTICATION" MODIFY ("ID" NOT NULL ENABLE);
