--------------------------------------------------------
--  Constraints for Table RESOURCE_PEOPLE_DETAILS
--------------------------------------------------------

  ALTER TABLE "DECMGR"."RESOURCE_PEOPLE_DETAILS" ADD CONSTRAINT "PK_RESOURCE_PEOPLE_DETAILS" PRIMARY KEY ("ID")
  USING INDEX  ENABLE;
  ALTER TABLE "DECMGR"."RESOURCE_PEOPLE_DETAILS" ADD CONSTRAINT "RESOURCE_PEOPLE_DETAILS_CK6" CHECK (/* Valid wua_status values */ WUA_STATUS IN ('NOTREQUIRED','REQUIRED','VALID')) ENABLE;
  ALTER TABLE "DECMGR"."RESOURCE_PEOPLE_DETAILS" ADD CONSTRAINT "RESOURCE_PEOPLE_DETAILS_CK5" CHECK (/* Start Date and Draft permutations */ 
   (NVL(status_control,'.')='D' AND start_date = NVL(end_date,start_date-1)) 
OR (NVL(status_control,'.')='C')
OR (status_control IS NULL AND start_date < NVL(end_date,start_date-1)) 
) ENABLE;
  ALTER TABLE "DECMGR"."RESOURCE_PEOPLE_DETAILS" ADD CONSTRAINT "RESOURCE_PEOPLE_DETAILS_CK4" CHECK (/* End date populated permutations - Note deleted person record must be status_control=C for legacy licensing system */ 
     (end_date IS NULL AND NVL(status_control,'.')='C' AND status!='DELETED') 
  OR (end_date IS NOT NULL AND NVL(status_control,'.')='C' AND status='DELETED') 
  OR (end_date IS NOT NULL AND NVL(status_control,'.')='D') 
  OR (end_date IS NOT NULL AND status_control IS NULL)
 ) ENABLE;
  ALTER TABLE "DECMGR"."RESOURCE_PEOPLE_DETAILS" ADD CONSTRAINT "RESOURCE_PEOPLE_DETAILS_CK2" CHECK (/* Valid status_control values */ STATUS_CONTROL IS NULL OR STATUS_CONTROL IN ('C','D')) ENABLE;
  ALTER TABLE "DECMGR"."RESOURCE_PEOPLE_DETAILS" MODIFY ("WUA_STATUS" NOT NULL ENABLE);
  ALTER TABLE "DECMGR"."RESOURCE_PEOPLE_DETAILS" MODIFY ("STATUS" NOT NULL ENABLE);
  ALTER TABLE "DECMGR"."RESOURCE_PEOPLE_DETAILS" MODIFY ("START_DATE" NOT NULL ENABLE);
  ALTER TABLE "DECMGR"."RESOURCE_PEOPLE_DETAILS" MODIFY ("RP_ID" NOT NULL ENABLE);
  ALTER TABLE "DECMGR"."RESOURCE_PEOPLE_DETAILS" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "DECMGR"."RESOURCE_PEOPLE_DETAILS" ADD CONSTRAINT "RESOURCE_PEOPLE_DETAILS_CK3" CHECK (/* Valid status to status_control mappings - Note deleted person record must be status_control=C for legacy licensing system */ 
  STATUS||'='||STATUS_CONTROL IN ('CURRENT=C','DRAFT=D','DRAFT=C','LEGACY=C','LEGACY=','LEGACY-WUA=C','LEGACY-WUA=','ARCHIVED=','DELETED=C','DELETE-DRAFT=')) ENABLE;
  ALTER TABLE "DECMGR"."RESOURCE_PEOPLE_DETAILS" ADD CONSTRAINT "RESOURCE_PEOPLE_DETAILS_CK1" CHECK (/* Valid status values */ 
  STATUS IN ('CURRENT','ARCHIVED','DRAFT','LEGACY','LEGACY-WUA','DELETED','DELETE-DRAFT')) ENABLE;
