--------------------------------------------------------
--  Constraints for Table RESOURCE_TELE_AREA_CODES
--------------------------------------------------------

  ALTER TABLE "DECMGR"."RESOURCE_TELE_AREA_CODES" ADD CONSTRAINT "RESOURCE_TELE_AREA_CODES_PK" PRIMARY KEY ("STD_REGEXP", "COUNTRY_CODE")
  USING INDEX  ENABLE;
  ALTER TABLE "DECMGR"."RESOURCE_TELE_AREA_CODES" MODIFY ("CREATED_DATETIME" NOT NULL ENABLE);
  ALTER TABLE "DECMGR"."RESOURCE_TELE_AREA_CODES" MODIFY ("CREATED_BY" NOT NULL ENABLE);
  ALTER TABLE "DECMGR"."RESOURCE_TELE_AREA_CODES" MODIFY ("STD_LENGTH" NOT NULL ENABLE);
  ALTER TABLE "DECMGR"."RESOURCE_TELE_AREA_CODES" MODIFY ("STATUS" NOT NULL ENABLE);
  ALTER TABLE "DECMGR"."RESOURCE_TELE_AREA_CODES" MODIFY ("STD_REGEXP" NOT NULL ENABLE);
  ALTER TABLE "DECMGR"."RESOURCE_TELE_AREA_CODES" MODIFY ("COUNTRY_CODE" NOT NULL ENABLE);
