--------------------------------------------------------
--  Constraints for Table RESOURCES
--------------------------------------------------------

  ALTER TABLE "DECMGR"."RESOURCES" ADD CONSTRAINT "RESOURCES_UK" UNIQUE ("ID", "RES_TYPE")
  USING INDEX  ENABLE;
  ALTER TABLE "DECMGR"."RESOURCES" ADD CONSTRAINT "RESOURCES_PK" PRIMARY KEY ("ID")
  USING INDEX  ENABLE;
  ALTER TABLE "DECMGR"."RESOURCES" MODIFY ("RES_TYPE" NOT NULL ENABLE);
  ALTER TABLE "DECMGR"."RESOURCES" MODIFY ("ID" NOT NULL ENABLE);
