--------------------------------------------------------
--  Constraints for Table RESOURCE_PEOPLE_DETAILS
--------------------------------------------------------

  ALTER TABLE "SAVEMGR"."RESOURCE_PEOPLE_DETAILS" MODIFY ("WUA_STATUS" NOT NULL ENABLE);
  ALTER TABLE "SAVEMGR"."RESOURCE_PEOPLE_DETAILS" MODIFY ("STATUS" NOT NULL ENABLE);
  ALTER TABLE "SAVEMGR"."RESOURCE_PEOPLE_DETAILS" MODIFY ("START_DATE" NOT NULL ENABLE);
  ALTER TABLE "SAVEMGR"."RESOURCE_PEOPLE_DETAILS" MODIFY ("RP_ID" NOT NULL ENABLE);
  ALTER TABLE "SAVEMGR"."RESOURCE_PEOPLE_DETAILS" MODIFY ("ID" NOT NULL ENABLE);
