--------------------------------------------------------
--  Constraints for Table RESOURCE_TELE_COUNTRY_CODES
--------------------------------------------------------

  ALTER TABLE "DECMGR"."RESOURCE_TELE_COUNTRY_CODES" ADD CONSTRAINT "RESOURCE_TELE_COUNTRY_CODE_PK" PRIMARY KEY ("COUNTRY_CODE")
  USING INDEX  ENABLE;
  ALTER TABLE "DECMGR"."RESOURCE_TELE_COUNTRY_CODES" ADD CONSTRAINT "RESOURCE_TELE_COUNTRY_CK4" CHECK (USE_NDD_IN_DIAL IN ('Y','N')) ENABLE;
  ALTER TABLE "DECMGR"."RESOURCE_TELE_COUNTRY_CODES" ADD CONSTRAINT "RESOURCE_TELE_COUNTRY_CK3" CHECK (SHOW_NDD_IN_CANONICAL IN ('Y','N')) ENABLE;
  ALTER TABLE "DECMGR"."RESOURCE_TELE_COUNTRY_CODES" ADD CONSTRAINT "RESOURCE_TELE_COUNTRY_CK2" CHECK (AUTO_STRIP_NDD_FROM_STD IN ('Y','N')) ENABLE;
  ALTER TABLE "DECMGR"."RESOURCE_TELE_COUNTRY_CODES" ADD CONSTRAINT "RESOURCE_TELE_COUNTRY_CK1" CHECK (STATUS IN ('VALID','DRAFT')) ENABLE;
  ALTER TABLE "DECMGR"."RESOURCE_TELE_COUNTRY_CODES" MODIFY ("USE_NDD_IN_DIAL" NOT NULL ENABLE);
  ALTER TABLE "DECMGR"."RESOURCE_TELE_COUNTRY_CODES" MODIFY ("SHOW_NDD_IN_CANONICAL" NOT NULL ENABLE);
  ALTER TABLE "DECMGR"."RESOURCE_TELE_COUNTRY_CODES" MODIFY ("AUTO_STRIP_NDD_FROM_STD" NOT NULL ENABLE);
  ALTER TABLE "DECMGR"."RESOURCE_TELE_COUNTRY_CODES" MODIFY ("CREATED_DATETIME" NOT NULL ENABLE);
  ALTER TABLE "DECMGR"."RESOURCE_TELE_COUNTRY_CODES" MODIFY ("CREATED_BY" NOT NULL ENABLE);
  ALTER TABLE "DECMGR"."RESOURCE_TELE_COUNTRY_CODES" MODIFY ("STATUS" NOT NULL ENABLE);
  ALTER TABLE "DECMGR"."RESOURCE_TELE_COUNTRY_CODES" MODIFY ("COUNTRY_CODE" NOT NULL ENABLE);
