--------------------------------------------------------
--  Constraints for Table RESOURCE_ROLES
--------------------------------------------------------

  ALTER TABLE "DECMGR"."RESOURCE_ROLES" ADD CONSTRAINT "RESOURCE_ROLES_UK1" UNIQUE ("RES_ID", "ROLE_NAME")
  USING INDEX  ENABLE;
  ALTER TABLE "DECMGR"."RESOURCE_ROLES" ADD CONSTRAINT "RESOURCE_ROLES_PK" PRIMARY KEY ("ID")
  USING INDEX  ENABLE;
  ALTER TABLE "DECMGR"."RESOURCE_ROLES" MODIFY ("ROLE_NAME" NOT NULL ENABLE);
  ALTER TABLE "DECMGR"."RESOURCE_ROLES" MODIFY ("RES_ID" NOT NULL ENABLE);
  ALTER TABLE "DECMGR"."RESOURCE_ROLES" MODIFY ("ID" NOT NULL ENABLE);
