--------------------------------------------------------
--  Constraints for Table RETURNS
--------------------------------------------------------

  ALTER TABLE "SDBPUBMGR"."RETURNS" ADD CONSTRAINT "RETURNS_CK5" CHECK ((licence_type = 'OGEL' AND ogl_id IS NOT NULL) OR (licence_type != 'OGL' AND ogl_id IS NULL)) ENABLE;
  ALTER TABLE "SDBPUBMGR"."RETURNS" ADD CONSTRAINT "RETURNS_CK4" CHECK (licence_type IN ('OGEL','OIEL','OITCL')) ENABLE;
  ALTER TABLE "SDBPUBMGR"."RETURNS" ADD CONSTRAINT "RETURNS_CK3" CHECK (status_control IN ('A','P','C')) ENABLE;
  ALTER TABLE "SDBPUBMGR"."RETURNS" ADD CONSTRAINT "RETURNS_CK2" CHECK (status IN ('WITHDRAWN', 'ACTIVE')) ENABLE;
  ALTER TABLE "SDBPUBMGR"."RETURNS" ADD CONSTRAINT "RETURNS_CK1" CHECK (elr_version > 0) ENABLE;
  ALTER TABLE "SDBPUBMGR"."RETURNS" ADD CONSTRAINT "RETURNS_PK" PRIMARY KEY ("ELR_ID", "ELR_VERSION")
  USING INDEX  ENABLE;
  ALTER TABLE "SDBPUBMGR"."RETURNS" MODIFY ("EL_ID" NOT NULL ENABLE);
  ALTER TABLE "SDBPUBMGR"."RETURNS" MODIFY ("LICENCE_TYPE" NOT NULL ENABLE);
  ALTER TABLE "SDBPUBMGR"."RETURNS" MODIFY ("BATCH_ID" NOT NULL ENABLE);
  ALTER TABLE "SDBPUBMGR"."RETURNS" MODIFY ("STATUS_CONTROL" NOT NULL ENABLE);
  ALTER TABLE "SDBPUBMGR"."RETURNS" MODIFY ("CREATED_DATETIME" NOT NULL ENABLE);
  ALTER TABLE "SDBPUBMGR"."RETURNS" MODIFY ("STATUS" NOT NULL ENABLE);
  ALTER TABLE "SDBPUBMGR"."RETURNS" MODIFY ("ELR_VERSION" NOT NULL ENABLE);
  ALTER TABLE "SDBPUBMGR"."RETURNS" MODIFY ("ELR_ID" NOT NULL ENABLE);
