--------------------------------------------------------
--  Constraints for Table REVIEW_REMOTE_DWNLOAD_CONTENTS
--------------------------------------------------------

  ALTER TABLE "BPMMGR"."REVIEW_REMOTE_DWNLOAD_CONTENTS" ADD CONSTRAINT "REVIEW_REMOTE_DWN_CONTENTS_CK1" CHECK (status IN ('PENDING', 'PARTIAL', 'COMPLETED')) ENABLE;
  ALTER TABLE "BPMMGR"."REVIEW_REMOTE_DWNLOAD_CONTENTS" ADD CONSTRAINT "REVIEW_REMOTE_DWN_CONTENTS_PK" PRIMARY KEY ("ID")
  USING INDEX  ENABLE;
  ALTER TABLE "BPMMGR"."REVIEW_REMOTE_DWNLOAD_CONTENTS" MODIFY ("CREATED_BY_WUA_ID" NOT NULL ENABLE);
  ALTER TABLE "BPMMGR"."REVIEW_REMOTE_DWNLOAD_CONTENTS" MODIFY ("START_DATETIME" NOT NULL ENABLE);
  ALTER TABLE "BPMMGR"."REVIEW_REMOTE_DWNLOAD_CONTENTS" MODIFY ("STATUS" NOT NULL ENABLE);
  ALTER TABLE "BPMMGR"."REVIEW_REMOTE_DWNLOAD_CONTENTS" MODIFY ("RA_ID" NOT NULL ENABLE);
  ALTER TABLE "BPMMGR"."REVIEW_REMOTE_DWNLOAD_CONTENTS" MODIFY ("RRD_ID" NOT NULL ENABLE);
  ALTER TABLE "BPMMGR"."REVIEW_REMOTE_DWNLOAD_CONTENTS" MODIFY ("ID" NOT NULL ENABLE);
