--------------------------------------------------------
--  Constraints for Table REVIEW_REQ_BATCH_ACKNOWLEDGE
--------------------------------------------------------

  ALTER TABLE "BPMMGR"."REVIEW_REQ_BATCH_ACKNOWLEDGE" ADD CONSTRAINT "RR_BATCH_ACKNOWLEDGE_PK" PRIMARY KEY ("ID")
  USING INDEX  ENABLE;
  ALTER TABLE "BPMMGR"."REVIEW_REQ_BATCH_ACKNOWLEDGE" MODIFY ("START_DATETIME" NOT NULL ENABLE);
  ALTER TABLE "BPMMGR"."REVIEW_REQ_BATCH_ACKNOWLEDGE" MODIFY ("REVIEW_ITEM_TYPE_CODE" NOT NULL ENABLE);
  ALTER TABLE "BPMMGR"."REVIEW_REQ_BATCH_ACKNOWLEDGE" MODIFY ("ROLE_NAME" NOT NULL ENABLE);
  ALTER TABLE "BPMMGR"."REVIEW_REQ_BATCH_ACKNOWLEDGE" MODIFY ("PERSON_ID" NOT NULL ENABLE);
  ALTER TABLE "BPMMGR"."REVIEW_REQ_BATCH_ACKNOWLEDGE" MODIFY ("RREQ_ID" NOT NULL ENABLE);
  ALTER TABLE "BPMMGR"."REVIEW_REQ_BATCH_ACKNOWLEDGE" MODIFY ("ID" NOT NULL ENABLE);
