--------------------------------------------------------
--  Constraints for Table REVIEW_ADVISOR_SLOT_DETAILS
--------------------------------------------------------

  ALTER TABLE "BPMMGR"."REVIEW_ADVISOR_SLOT_DETAILS" ADD CONSTRAINT "REVIEW_ADVISOR_SLOT_DTLS_CK1" CHECK (/* End date and status control */ (end_datetime IS NULL AND status_control='C') OR (end_datetime IS NOT NULL AND status_control IS NULL)) ENABLE;
  ALTER TABLE "BPMMGR"."REVIEW_ADVISOR_SLOT_DETAILS" ADD CONSTRAINT "REVIEW_ADVISOR_SLOT_DTLS_PK" PRIMARY KEY ("ID")
  USING INDEX  ENABLE;
  ALTER TABLE "BPMMGR"."REVIEW_ADVISOR_SLOT_DETAILS" MODIFY ("STATUS" NOT NULL ENABLE);
  ALTER TABLE "BPMMGR"."REVIEW_ADVISOR_SLOT_DETAILS" MODIFY ("NAME" NOT NULL ENABLE);
  ALTER TABLE "BPMMGR"."REVIEW_ADVISOR_SLOT_DETAILS" MODIFY ("RAS_ID" NOT NULL ENABLE);
  ALTER TABLE "BPMMGR"."REVIEW_ADVISOR_SLOT_DETAILS" MODIFY ("ID" NOT NULL ENABLE);
