--------------------------------------------------------
--  Constraints for Table REVIEW_ADVISOR_SLOTS_OLD
--------------------------------------------------------

  ALTER TABLE "BPMMGR"."REVIEW_ADVISOR_SLOTS_OLD" MODIFY ("STATUS" NOT NULL ENABLE);
  ALTER TABLE "BPMMGR"."REVIEW_ADVISOR_SLOTS_OLD" MODIFY ("NAME" NOT NULL ENABLE);
  ALTER TABLE "BPMMGR"."REVIEW_ADVISOR_SLOTS_OLD" MODIFY ("RA_ID" NOT NULL ENABLE);
  ALTER TABLE "BPMMGR"."REVIEW_ADVISOR_SLOTS_OLD" MODIFY ("ID" NOT NULL ENABLE);
