--------------------------------------------------------
--  Constraints for Table REVIEW_ADVISOR_SLOT_DETAILS
--------------------------------------------------------

  ALTER TABLE "SAVEMGR"."REVIEW_ADVISOR_SLOT_DETAILS" MODIFY ("STATUS" NOT NULL ENABLE);
  ALTER TABLE "SAVEMGR"."REVIEW_ADVISOR_SLOT_DETAILS" MODIFY ("NAME" NOT NULL ENABLE);
  ALTER TABLE "SAVEMGR"."REVIEW_ADVISOR_SLOT_DETAILS" MODIFY ("RAS_ID" NOT NULL ENABLE);
  ALTER TABLE "SAVEMGR"."REVIEW_ADVISOR_SLOT_DETAILS" MODIFY ("ID" NOT NULL ENABLE);
