--------------------------------------------------------
--  Constraints for Table REVIEW_REMOTE_UPLOAD_SLOTS
--------------------------------------------------------

  ALTER TABLE "BPMMGR"."REVIEW_REMOTE_UPLOAD_SLOTS" ADD CONSTRAINT "REVIEW_REMOTE_UPLOAD_SLOTS_PK" PRIMARY KEY ("ID")
  USING INDEX  ENABLE;
  ALTER TABLE "BPMMGR"."REVIEW_REMOTE_UPLOAD_SLOTS" MODIFY ("STATUS" NOT NULL ENABLE);
  ALTER TABLE "BPMMGR"."REVIEW_REMOTE_UPLOAD_SLOTS" MODIFY ("RAS_ID" NOT NULL ENABLE);
  ALTER TABLE "BPMMGR"."REVIEW_REMOTE_UPLOAD_SLOTS" MODIFY ("RRUC_ID" NOT NULL ENABLE);
  ALTER TABLE "BPMMGR"."REVIEW_REMOTE_UPLOAD_SLOTS" MODIFY ("ID" NOT NULL ENABLE);
