--------------------------------------------------------
--  Constraints for Table REVIEW_REQ_BATCH_ADVICE
--------------------------------------------------------

  ALTER TABLE "BPMMGR"."REVIEW_REQ_BATCH_ADVICE" ADD CONSTRAINT "REVIEW_REQ_BATCH_ADVICE_PK" PRIMARY KEY ("ID")
  USING INDEX  ENABLE;
  ALTER TABLE "BPMMGR"."REVIEW_REQ_BATCH_ADVICE" MODIFY ("REQUEST_DATE" NOT NULL ENABLE);
  ALTER TABLE "BPMMGR"."REVIEW_REQ_BATCH_ADVICE" MODIFY ("STATUS" NOT NULL ENABLE);
  ALTER TABLE "BPMMGR"."REVIEW_REQ_BATCH_ADVICE" MODIFY ("ROLE_NAME" NOT NULL ENABLE);
  ALTER TABLE "BPMMGR"."REVIEW_REQ_BATCH_ADVICE" MODIFY ("RREQ_ID" NOT NULL ENABLE);
  ALTER TABLE "BPMMGR"."REVIEW_REQ_BATCH_ADVICE" MODIFY ("ID" NOT NULL ENABLE);
