--------------------------------------------------------
--  Constraints for Table REVIEW_REMOTE_UPLOAD_CONTENTS
--------------------------------------------------------

  ALTER TABLE "BPMMGR"."REVIEW_REMOTE_UPLOAD_CONTENTS" ADD CONSTRAINT "REVIEW_REMOTE_UPL_CONTENTS_CK1" CHECK ((rrdc_id IS NOT NULL AND status = 'COMPLETED') OR status != 'COMPLETED') ENABLE;
  ALTER TABLE "BPMMGR"."REVIEW_REMOTE_UPLOAD_CONTENTS" ADD CONSTRAINT "REVIEW_REMOTE_UPLD_CONTENTS_PK" PRIMARY KEY ("ID")
  USING INDEX  ENABLE;
  ALTER TABLE "BPMMGR"."REVIEW_REMOTE_UPLOAD_CONTENTS" MODIFY ("CREATED_BY_WUA_ID" NOT NULL ENABLE);
  ALTER TABLE "BPMMGR"."REVIEW_REMOTE_UPLOAD_CONTENTS" MODIFY ("START_DATETIME" NOT NULL ENABLE);
  ALTER TABLE "BPMMGR"."REVIEW_REMOTE_UPLOAD_CONTENTS" MODIFY ("STATUS" NOT NULL ENABLE);
  ALTER TABLE "BPMMGR"."REVIEW_REMOTE_UPLOAD_CONTENTS" MODIFY ("RRU_ID" NOT NULL ENABLE);
  ALTER TABLE "BPMMGR"."REVIEW_REMOTE_UPLOAD_CONTENTS" MODIFY ("ID" NOT NULL ENABLE);
