--------------------------------------------------------
--  Constraints for Table REVIEW_RUN_DETAILS
--------------------------------------------------------

  ALTER TABLE "BPMMGR"."REVIEW_RUN_DETAILS" ADD CONSTRAINT "REVIEW_RUN_DETAILS_CK1" CHECK (/* End date and status control */ (END_DATETIME IS NULL AND STATUS_CONTROL='C') OR (END_DATETIME IS NOT NULL AND STATUS_CONTROL IS NULL)) ENABLE;
  ALTER TABLE "BPMMGR"."REVIEW_RUN_DETAILS" ADD CONSTRAINT "REVIEW_RUN_DETAILS_PK" PRIMARY KEY ("ID")
  USING INDEX  ENABLE;
  ALTER TABLE "BPMMGR"."REVIEW_RUN_DETAILS" MODIFY ("CREATED_BY_WUA_ID" NOT NULL ENABLE);
  ALTER TABLE "BPMMGR"."REVIEW_RUN_DETAILS" MODIFY ("START_DATETIME" NOT NULL ENABLE);
  ALTER TABLE "BPMMGR"."REVIEW_RUN_DETAILS" MODIFY ("RRUN_ID" NOT NULL ENABLE);
  ALTER TABLE "BPMMGR"."REVIEW_RUN_DETAILS" MODIFY ("ID" NOT NULL ENABLE);
