--------------------------------------------------------
--  Constraints for Table REVIEW_REQUESTS
--------------------------------------------------------

  ALTER TABLE "BPMMGR"."REVIEW_REQUESTS" ADD CONSTRAINT "REVIEW_REQUESTS_PK" PRIMARY KEY ("ID")
  USING INDEX  ENABLE;
  ALTER TABLE "BPMMGR"."REVIEW_REQUESTS" MODIFY ("AAC_ID" NOT NULL ENABLE);
  ALTER TABLE "BPMMGR"."REVIEW_REQUESTS" MODIFY ("RRUN_ID" NOT NULL ENABLE);
  ALTER TABLE "BPMMGR"."REVIEW_REQUESTS" MODIFY ("ID" NOT NULL ENABLE);
