--------------------------------------------------------
--  Constraints for Table REVIEW_REMOTE_SCHEMAS
--------------------------------------------------------

  ALTER TABLE "BPMMGR"."REVIEW_REMOTE_SCHEMAS" ADD CONSTRAINT "REVIEW_REMOTE_SCHEMAS_PK" PRIMARY KEY ("NAME")
  USING INDEX  ENABLE;
  ALTER TABLE "BPMMGR"."REVIEW_REMOTE_SCHEMAS" MODIFY ("XML_DATA" NOT NULL ENABLE);
  ALTER TABLE "BPMMGR"."REVIEW_REMOTE_SCHEMAS" MODIFY ("NAME" NOT NULL ENABLE);
