--------------------------------------------------------
--  Constraints for Table REVIEW_ADVISORS
--------------------------------------------------------

  ALTER TABLE "BPMMGR"."REVIEW_ADVISORS" ADD CONSTRAINT "REVIEW_ADVISORS_PK" PRIMARY KEY ("ID")
  USING INDEX  ENABLE;
  ALTER TABLE "BPMMGR"."REVIEW_ADVISORS" MODIFY ("BAS_ID" NOT NULL ENABLE);
  ALTER TABLE "BPMMGR"."REVIEW_ADVISORS" MODIFY ("RREQ_ID" NOT NULL ENABLE);
  ALTER TABLE "BPMMGR"."REVIEW_ADVISORS" MODIFY ("ID" NOT NULL ENABLE);
