--------------------------------------------------------
--  Constraints for Table REVIEW_REMOTE_UPLOADS
--------------------------------------------------------

  ALTER TABLE "BPMMGR"."REVIEW_REMOTE_UPLOADS" ADD CONSTRAINT "REVIEW_REMOTE_UPLOADS_PK" PRIMARY KEY ("ID")
  USING INDEX  ENABLE;
  ALTER TABLE "BPMMGR"."REVIEW_REMOTE_UPLOADS" MODIFY ("XML_IN" NOT NULL ENABLE);
  ALTER TABLE "BPMMGR"."REVIEW_REMOTE_UPLOADS" MODIFY ("REVIEW_TYPE" NOT NULL ENABLE);
  ALTER TABLE "BPMMGR"."REVIEW_REMOTE_UPLOADS" MODIFY ("ADVICE_TYPE" NOT NULL ENABLE);
  ALTER TABLE "BPMMGR"."REVIEW_REMOTE_UPLOADS" MODIFY ("FOX_FILE_ID" NOT NULL ENABLE);
  ALTER TABLE "BPMMGR"."REVIEW_REMOTE_UPLOADS" MODIFY ("CREATED_BY_WUA_ID" NOT NULL ENABLE);
  ALTER TABLE "BPMMGR"."REVIEW_REMOTE_UPLOADS" MODIFY ("START_DATETIME" NOT NULL ENABLE);
  ALTER TABLE "BPMMGR"."REVIEW_REMOTE_UPLOADS" MODIFY ("ID" NOT NULL ENABLE);
