--------------------------------------------------------
--  Constraints for Table REVIEW_ADVISOR_SLOTS
--------------------------------------------------------

  ALTER TABLE "SAVEMGR"."REVIEW_ADVISOR_SLOTS" MODIFY ("STATUS" NOT NULL ENABLE);
  ALTER TABLE "SAVEMGR"."REVIEW_ADVISOR_SLOTS" MODIFY ("NAME" NOT NULL ENABLE);
  ALTER TABLE "SAVEMGR"."REVIEW_ADVISOR_SLOTS" MODIFY ("RA_ID" NOT NULL ENABLE);
  ALTER TABLE "SAVEMGR"."REVIEW_ADVISOR_SLOTS" MODIFY ("ID" NOT NULL ENABLE);
