--------------------------------------------------------
--  Constraints for Table REVIEW_ADVISOR_ITEMS
--------------------------------------------------------

  ALTER TABLE "BPMMGR"."REVIEW_ADVISOR_ITEMS" ADD CONSTRAINT "REVIEW_ADVISOR_ITEMS_CK2" CHECK (acknowledged_flag IN ('true', 'false')) ENABLE;
  ALTER TABLE "BPMMGR"."REVIEW_ADVISOR_ITEMS" ADD CONSTRAINT "REVIEW_ADVISOR_ITEMS_CK1" CHECK (status IN ('ACTIVE', 'ARCHIVED')) ENABLE;
  ALTER TABLE "BPMMGR"."REVIEW_ADVISOR_ITEMS" ADD CONSTRAINT "REVIEW_ADVISOR_ITEMS_PK" PRIMARY KEY ("RA_ID", "RII_ID")
  USING INDEX  ENABLE;
  ALTER TABLE "BPMMGR"."REVIEW_ADVISOR_ITEMS" MODIFY ("ACKNOWLEDGED_FLAG" NOT NULL ENABLE);
  ALTER TABLE "BPMMGR"."REVIEW_ADVISOR_ITEMS" MODIFY ("STATUS" NOT NULL ENABLE);
  ALTER TABLE "BPMMGR"."REVIEW_ADVISOR_ITEMS" MODIFY ("CREATED_BY_WUA" NOT NULL ENABLE);
  ALTER TABLE "BPMMGR"."REVIEW_ADVISOR_ITEMS" MODIFY ("CREATED_DATETIME" NOT NULL ENABLE);
