--------------------------------------------------------
--  Constraints for Table RSS_FEEDS
--------------------------------------------------------

  ALTER TABLE "DECMGR"."RSS_FEEDS" ADD CONSTRAINT "RSS_FEEDS_UK_URI" UNIQUE ("URI")
  USING INDEX  ENABLE;
  ALTER TABLE "DECMGR"."RSS_FEEDS" ADD CONSTRAINT "RSS_FEEDS_UK_NAME" UNIQUE ("NAME")
  USING INDEX  ENABLE;
  ALTER TABLE "DECMGR"."RSS_FEEDS" ADD CONSTRAINT "RSS_FEEDS_PK" PRIMARY KEY ("ID")
  USING INDEX  ENABLE;
  ALTER TABLE "DECMGR"."RSS_FEEDS" MODIFY ("POLL_INTERVAL_MINS" NOT NULL ENABLE);
  ALTER TABLE "DECMGR"."RSS_FEEDS" MODIFY ("URI" NOT NULL ENABLE);
  ALTER TABLE "DECMGR"."RSS_FEEDS" MODIFY ("NAME" NOT NULL ENABLE);
  ALTER TABLE "DECMGR"."RSS_FEEDS" MODIFY ("ID" NOT NULL ENABLE);
