--------------------------------------------------------
--  Constraints for Table RSS_FEED_CACHE
--------------------------------------------------------

  ALTER TABLE "DECMGR"."RSS_FEED_CACHE" ADD CONSTRAINT "PK_RSS_FEED_CACHE_ID" PRIMARY KEY ("ID")
  USING INDEX (CREATE INDEX "DECMGR"."RSS_FEED_CACHE_IDX1" ON "DECMGR"."RSS_FEED_CACHE" ("ID") 
  )  ENABLE;
  ALTER TABLE "DECMGR"."RSS_FEED_CACHE" MODIFY ("CACHE_DATETIME" NOT NULL ENABLE);
  ALTER TABLE "DECMGR"."RSS_FEED_CACHE" MODIFY ("RF_ID" NOT NULL ENABLE);
  ALTER TABLE "DECMGR"."RSS_FEED_CACHE" MODIFY ("ID" NOT NULL ENABLE);
