--------------------------------------------------------
--  Constraints for Table SCAN_EXCHANGE_CONTEXTS
--------------------------------------------------------

  ALTER TABLE "DECMGR"."SCAN_EXCHANGE_CONTEXTS" ADD CONSTRAINT "SCAN_EXCHANGE_CONTEXTS_CK2" CHECK (received_event IS NOT NULL) ENABLE;
  ALTER TABLE "DECMGR"."SCAN_EXCHANGE_CONTEXTS" ADD CONSTRAINT "SCAN_EXCHANGE_CONTEXTS_CK1" CHECK (STATUS IN ('NEW', 'ARCHIVE', 'INUSE')) ENABLE;
  ALTER TABLE "DECMGR"."SCAN_EXCHANGE_CONTEXTS" ADD CONSTRAINT "SCAN_EXCHANGE_CONTEXTS_PK" PRIMARY KEY ("ID")
  USING INDEX  ENABLE;
  ALTER TABLE "DECMGR"."SCAN_EXCHANGE_CONTEXTS" MODIFY ("STATUS" NOT NULL ENABLE);
  ALTER TABLE "DECMGR"."SCAN_EXCHANGE_CONTEXTS" MODIFY ("CREATED_DATETIME" NOT NULL ENABLE);
  ALTER TABLE "DECMGR"."SCAN_EXCHANGE_CONTEXTS" MODIFY ("CONTEXT_UREF" NOT NULL ENABLE);
  ALTER TABLE "DECMGR"."SCAN_EXCHANGE_CONTEXTS" MODIFY ("ID" NOT NULL ENABLE);
