--------------------------------------------------------
--  Constraints for Table SCAN_TYPES
--------------------------------------------------------

  ALTER TABLE "DECMGR"."SCAN_TYPES" ADD CONSTRAINT "SCAN_TYPES_UK1" UNIQUE ("DESCRIPTION")
  USING INDEX  ENABLE;
  ALTER TABLE "DECMGR"."SCAN_TYPES" ADD CONSTRAINT "SCAN_TYPES_PK1" PRIMARY KEY ("SCAN_TYPE")
  USING INDEX  ENABLE;
  ALTER TABLE "DECMGR"."SCAN_TYPES" MODIFY ("DESCRIPTION" NOT NULL ENABLE);
  ALTER TABLE "DECMGR"."SCAN_TYPES" MODIFY ("SCAN_TYPE" NOT NULL ENABLE);
