--------------------------------------------------------
--  Constraints for Table SCAN_SHEETS
--------------------------------------------------------

  ALTER TABLE "DECMGR"."SCAN_SHEETS" ADD CONSTRAINT "SCAN_SHEETS_CK1" CHECK (STATUS IN ('NEW', 'DELETED', 'SCAN_PENDING', 'ALLOCATED')) ENABLE;
  ALTER TABLE "DECMGR"."SCAN_SHEETS" ADD CONSTRAINT "SCAN_SHEETS_UK1" UNIQUE ("BARCODE_VALUE")
  USING INDEX  ENABLE;
  ALTER TABLE "DECMGR"."SCAN_SHEETS" ADD CONSTRAINT "SCAN_SHEETS_PK" PRIMARY KEY ("ID")
  USING INDEX  ENABLE;
  ALTER TABLE "DECMGR"."SCAN_SHEETS" MODIFY ("STATUS" NOT NULL ENABLE);
  ALTER TABLE "DECMGR"."SCAN_SHEETS" MODIFY ("P_NUMBER" NOT NULL ENABLE);
  ALTER TABLE "DECMGR"."SCAN_SHEETS" MODIFY ("BARCODE_VALUE" NOT NULL ENABLE);
  ALTER TABLE "DECMGR"."SCAN_SHEETS" MODIFY ("ID" NOT NULL ENABLE);
