--------------------------------------------------------
--  Constraints for Table SCAN_TARGETS
--------------------------------------------------------

  ALTER TABLE "DECMGR"."SCAN_TARGETS" ADD CONSTRAINT "SCAN_TARGETS_CK1" CHECK (STATUS IN ('NEW', 'SCAN_PENDING', 'SCAN_COMPLETE', 'DELETED')) ENABLE;
  ALTER TABLE "DECMGR"."SCAN_TARGETS" ADD CONSTRAINT "SCAN_TARGETS_PK" PRIMARY KEY ("ID")
  USING INDEX  ENABLE;
  ALTER TABLE "DECMGR"."SCAN_TARGETS" MODIFY ("STATUS" NOT NULL ENABLE);
  ALTER TABLE "DECMGR"."SCAN_TARGETS" MODIFY ("TARGET_UREF" NOT NULL ENABLE);
  ALTER TABLE "DECMGR"."SCAN_TARGETS" MODIFY ("SCAN_TYPE" NOT NULL ENABLE);
  ALTER TABLE "DECMGR"."SCAN_TARGETS" MODIFY ("ID" NOT NULL ENABLE);
