--------------------------------------------------------
--  Constraints for Table SCAN_PRINT_BATCH
--------------------------------------------------------

  ALTER TABLE "DECMGR"."SCAN_PRINT_BATCH" ADD CONSTRAINT "SCAN_PRINT_BATCH_CK1" CHECK (STATUS IN ('NEW', 'DELETED', 'ARCHIVE')) ENABLE;
  ALTER TABLE "DECMGR"."SCAN_PRINT_BATCH" ADD CONSTRAINT "SCAN_PRINT_BATCH_PK" PRIMARY KEY ("ID")
  USING INDEX  ENABLE;
  ALTER TABLE "DECMGR"."SCAN_PRINT_BATCH" MODIFY ("STATUS" NOT NULL ENABLE);
  ALTER TABLE "DECMGR"."SCAN_PRINT_BATCH" MODIFY ("CREATED_DATETIME" NOT NULL ENABLE);
  ALTER TABLE "DECMGR"."SCAN_PRINT_BATCH" MODIFY ("DI_ID" NOT NULL ENABLE);
  ALTER TABLE "DECMGR"."SCAN_PRINT_BATCH" MODIFY ("SP_ID" NOT NULL ENABLE);
  ALTER TABLE "DECMGR"."SCAN_PRINT_BATCH" MODIFY ("ID" NOT NULL ENABLE);
