--------------------------------------------------------
--  Constraints for Table SCHEMA_DEFINITION_DETAILS
--------------------------------------------------------

  ALTER TABLE "PVEXMGR"."SCHEMA_DEFINITION_DETAILS" ADD CONSTRAINT "SD_DETAILS_CK2" CHECK (
    (status_control = 'C' AND end_datetime IS NULL)
    OR
    (status_control IS NULL AND end_datetime IS NOT NULL)
  ) ENABLE;
  ALTER TABLE "PVEXMGR"."SCHEMA_DEFINITION_DETAILS" ADD CONSTRAINT "SD_DETAILS_CK1" CHECK (status_control = 'C' OR status_control IS NULL) ENABLE;
  ALTER TABLE "PVEXMGR"."SCHEMA_DEFINITION_DETAILS" ADD CONSTRAINT "SDD_PK" PRIMARY KEY ("ID")
  USING INDEX  ENABLE;
  ALTER TABLE "PVEXMGR"."SCHEMA_DEFINITION_DETAILS" MODIFY ("XML_DATA" NOT NULL ENABLE);
  ALTER TABLE "PVEXMGR"."SCHEMA_DEFINITION_DETAILS" MODIFY ("START_DATETIME" NOT NULL ENABLE);
  ALTER TABLE "PVEXMGR"."SCHEMA_DEFINITION_DETAILS" MODIFY ("SD_ID" NOT NULL ENABLE);
  ALTER TABLE "PVEXMGR"."SCHEMA_DEFINITION_DETAILS" MODIFY ("ID" NOT NULL ENABLE);
