--------------------------------------------------------
--  Constraints for Table SEARCH_PARAM_LOGS
--------------------------------------------------------

  ALTER TABLE "FOXMGR"."SEARCH_PARAM_LOGS" MODIFY ("PARAMS_XML" NOT NULL ENABLE);
  ALTER TABLE "FOXMGR"."SEARCH_PARAM_LOGS" MODIFY ("RUN_DATETIME" NOT NULL ENABLE);
  ALTER TABLE "FOXMGR"."SEARCH_PARAM_LOGS" MODIFY ("QRY_NAME" NOT NULL ENABLE);
  ALTER TABLE "FOXMGR"."SEARCH_PARAM_LOGS" MODIFY ("MODULE_NAME" NOT NULL ENABLE);
  ALTER TABLE "FOXMGR"."SEARCH_PARAM_LOGS" MODIFY ("LOGIN_ID" NOT NULL ENABLE);
  ALTER TABLE "FOXMGR"."SEARCH_PARAM_LOGS" MODIFY ("WUA_ID" NOT NULL ENABLE);
