--------------------------------------------------------
--  Constraints for Table SECURITY_TRACE_STEP
--------------------------------------------------------

  ALTER TABLE "BPMMGR"."SECURITY_TRACE_STEP" ADD CONSTRAINT "PK_SECURITY_TRACE_STEP" PRIMARY KEY ("TRACE_ID", "START_TIMESTAMP")
  USING INDEX  ENABLE;
  ALTER TABLE "BPMMGR"."SECURITY_TRACE_STEP" MODIFY ("ROW_COUNT" NOT NULL ENABLE);
  ALTER TABLE "BPMMGR"."SECURITY_TRACE_STEP" MODIFY ("STEP_NAME" NOT NULL ENABLE);
  ALTER TABLE "BPMMGR"."SECURITY_TRACE_STEP" MODIFY ("END_TIMESTAMP" NOT NULL ENABLE);
  ALTER TABLE "BPMMGR"."SECURITY_TRACE_STEP" MODIFY ("START_TIMESTAMP" NOT NULL ENABLE);
  ALTER TABLE "BPMMGR"."SECURITY_TRACE_STEP" MODIFY ("TRACE_ID" NOT NULL ENABLE);
