--------------------------------------------------------
--  Constraints for Table SECURITY_OBJECT_RULES
--------------------------------------------------------

  ALTER TABLE "SAVEMGR"."SECURITY_OBJECT_RULES" MODIFY ("STATUS" NOT NULL ENABLE);
  ALTER TABLE "SAVEMGR"."SECURITY_OBJECT_RULES" MODIFY ("OBJECT_UREF_SELECT" NOT NULL ENABLE);
  ALTER TABLE "SAVEMGR"."SECURITY_OBJECT_RULES" MODIFY ("OBJECT_PRIVILEGE_LIST" NOT NULL ENABLE);
  ALTER TABLE "SAVEMGR"."SECURITY_OBJECT_RULES" MODIFY ("OBJECT_UREF_TYPE" NOT NULL ENABLE);
  ALTER TABLE "SAVEMGR"."SECURITY_OBJECT_RULES" MODIFY ("GRANTEE_UREF_TYPE" NOT NULL ENABLE);
  ALTER TABLE "SAVEMGR"."SECURITY_OBJECT_RULES" MODIFY ("DESCRIPTION" NOT NULL ENABLE);
  ALTER TABLE "SAVEMGR"."SECURITY_OBJECT_RULES" MODIFY ("ID" NOT NULL ENABLE);
