--------------------------------------------------------
--  Constraints for Table SECURITY_OBJECT_RULES
--------------------------------------------------------

  ALTER TABLE "BPMMGR"."SECURITY_OBJECT_RULES" ADD CONSTRAINT "SECURITY_OBJECT_RULES_PK" PRIMARY KEY ("ID")
  USING INDEX  ENABLE;
  ALTER TABLE "BPMMGR"."SECURITY_OBJECT_RULES" ADD CONSTRAINT "SECURITY_OBJECT_RULES_CK2" CHECK (STATUS IN ('ENABLE', 'DISABLE')) ENABLE;
  ALTER TABLE "BPMMGR"."SECURITY_OBJECT_RULES" ADD CONSTRAINT "SECURITY_OBJECT_RULES_CK1" CHECK (INSTR(object_privilege_list, ' ') = 0) ENABLE;
  ALTER TABLE "BPMMGR"."SECURITY_OBJECT_RULES" MODIFY ("STATUS" NOT NULL ENABLE);
  ALTER TABLE "BPMMGR"."SECURITY_OBJECT_RULES" MODIFY ("OBJECT_UREF_SELECT" NOT NULL ENABLE);
  ALTER TABLE "BPMMGR"."SECURITY_OBJECT_RULES" MODIFY ("OBJECT_PRIVILEGE_LIST" NOT NULL ENABLE);
  ALTER TABLE "BPMMGR"."SECURITY_OBJECT_RULES" MODIFY ("OBJECT_UREF_TYPE" NOT NULL ENABLE);
  ALTER TABLE "BPMMGR"."SECURITY_OBJECT_RULES" MODIFY ("GRANTEE_UREF_TYPE" NOT NULL ENABLE);
  ALTER TABLE "BPMMGR"."SECURITY_OBJECT_RULES" MODIFY ("DESCRIPTION" NOT NULL ENABLE);
  ALTER TABLE "BPMMGR"."SECURITY_OBJECT_RULES" MODIFY ("ID" NOT NULL ENABLE);
