--------------------------------------------------------
--  Constraints for Table SECURITY_OBJECT_RULES_8
--------------------------------------------------------

  ALTER TABLE "SAVEMGR"."SECURITY_OBJECT_RULES_8" MODIFY ("STATUS" NOT NULL ENABLE);
  ALTER TABLE "SAVEMGR"."SECURITY_OBJECT_RULES_8" MODIFY ("OBJECT_UREF_SELECT" NOT NULL ENABLE);
  ALTER TABLE "SAVEMGR"."SECURITY_OBJECT_RULES_8" MODIFY ("OBJECT_PRIVILEGE_LIST" NOT NULL ENABLE);
  ALTER TABLE "SAVEMGR"."SECURITY_OBJECT_RULES_8" MODIFY ("OBJECT_UREF_TYPE" NOT NULL ENABLE);
  ALTER TABLE "SAVEMGR"."SECURITY_OBJECT_RULES_8" MODIFY ("GRANTEE_UREF_TYPE" NOT NULL ENABLE);
  ALTER TABLE "SAVEMGR"."SECURITY_OBJECT_RULES_8" MODIFY ("DESCRIPTION" NOT NULL ENABLE);
  ALTER TABLE "SAVEMGR"."SECURITY_OBJECT_RULES_8" MODIFY ("ID" NOT NULL ENABLE);
