--------------------------------------------------------
--  Constraints for Table SECURITY_OBJECT_RULES_17
--------------------------------------------------------

  ALTER TABLE "SAVEMGR"."SECURITY_OBJECT_RULES_17" MODIFY ("STATUS" NOT NULL ENABLE);
  ALTER TABLE "SAVEMGR"."SECURITY_OBJECT_RULES_17" MODIFY ("OBJECT_UREF_SELECT" NOT NULL ENABLE);
  ALTER TABLE "SAVEMGR"."SECURITY_OBJECT_RULES_17" MODIFY ("OBJECT_PRIVILEGE_LIST" NOT NULL ENABLE);
  ALTER TABLE "SAVEMGR"."SECURITY_OBJECT_RULES_17" MODIFY ("OBJECT_UREF_TYPE" NOT NULL ENABLE);
  ALTER TABLE "SAVEMGR"."SECURITY_OBJECT_RULES_17" MODIFY ("GRANTEE_UREF_TYPE" NOT NULL ENABLE);
  ALTER TABLE "SAVEMGR"."SECURITY_OBJECT_RULES_17" MODIFY ("DESCRIPTION" NOT NULL ENABLE);
  ALTER TABLE "SAVEMGR"."SECURITY_OBJECT_RULES_17" MODIFY ("ID" NOT NULL ENABLE);
