--------------------------------------------------------
--  Constraints for Table SECURITY_SYSTEM_RULES
--------------------------------------------------------

  ALTER TABLE "SAVEMGR"."SECURITY_SYSTEM_RULES" MODIFY ("STATUS" NOT NULL ENABLE);
  ALTER TABLE "SAVEMGR"."SECURITY_SYSTEM_RULES" MODIFY ("SYSTEM_UREF_SELECT" NOT NULL ENABLE);
  ALTER TABLE "SAVEMGR"."SECURITY_SYSTEM_RULES" MODIFY ("SYSTEM_PRIVILEGE_LIST" NOT NULL ENABLE);
  ALTER TABLE "SAVEMGR"."SECURITY_SYSTEM_RULES" MODIFY ("GRANTEE_UREF_TYPE" NOT NULL ENABLE);
  ALTER TABLE "SAVEMGR"."SECURITY_SYSTEM_RULES" MODIFY ("DESCRIPTION" NOT NULL ENABLE);
  ALTER TABLE "SAVEMGR"."SECURITY_SYSTEM_RULES" MODIFY ("ID" NOT NULL ENABLE);
