--------------------------------------------------------
--  Constraints for Table SERVICE_DATA_OUTBOX
--------------------------------------------------------

  ALTER TABLE "SERVICEMGR"."SERVICE_DATA_OUTBOX" ADD PRIMARY KEY ("ID")
  USING INDEX  ENABLE;
  ALTER TABLE "SERVICEMGR"."SERVICE_DATA_OUTBOX" MODIFY ("STATUS" NOT NULL ENABLE);
  ALTER TABLE "SERVICEMGR"."SERVICE_DATA_OUTBOX" MODIFY ("START_DATETIME" NOT NULL ENABLE);
  ALTER TABLE "SERVICEMGR"."SERVICE_DATA_OUTBOX" MODIFY ("DATA_MNEM" NOT NULL ENABLE);
  ALTER TABLE "SERVICEMGR"."SERVICE_DATA_OUTBOX" MODIFY ("DEF_MNEM" NOT NULL ENABLE);
  ALTER TABLE "SERVICEMGR"."SERVICE_DATA_OUTBOX" MODIFY ("SDC_ID" NOT NULL ENABLE);
