--------------------------------------------------------
--  Constraints for Table SMS_TRANSMISSION_REQUEST_LOGS
--------------------------------------------------------

  ALTER TABLE "PORTALMGR"."SMS_TRANSMISSION_REQUEST_LOGS" ADD CONSTRAINT "SMS_TR_LOG_CK1" CHECK (status IN ('INTERNAL_ERROR', 'EXTERNAL_ERROR', 'SUCCESS')) ENABLE;
  ALTER TABLE "PORTALMGR"."SMS_TRANSMISSION_REQUEST_LOGS" ADD CONSTRAINT "SMS_TR_LOG_PK" PRIMARY KEY ("ID")
  USING INDEX  ENABLE;
  ALTER TABLE "PORTALMGR"."SMS_TRANSMISSION_REQUEST_LOGS" MODIFY ("XML_DATA" NOT NULL ENABLE);
  ALTER TABLE "PORTALMGR"."SMS_TRANSMISSION_REQUEST_LOGS" MODIFY ("SENT_DATE_TIME" NOT NULL ENABLE);
  ALTER TABLE "PORTALMGR"."SMS_TRANSMISSION_REQUEST_LOGS" MODIFY ("STATUS" NOT NULL ENABLE);
  ALTER TABLE "PORTALMGR"."SMS_TRANSMISSION_REQUEST_LOGS" MODIFY ("ID" NOT NULL ENABLE);
