--------------------------------------------------------
--  Constraints for Table SPIRE_APPLICANT_DETAILS
--------------------------------------------------------

  ALTER TABLE "SPIREMGR"."SPIRE_APPLICANT_DETAILS" ADD CONSTRAINT "SPIRE_APPLICANT_DETAILS_CK3" CHECK (/* Valid status to control mappings */ STATUS||'='||STATUS_CONTROL IN ('DRAFT=D','CURRENT=C','ARCHIVED=','DELETED=C')) ENABLE;
  ALTER TABLE "SPIREMGR"."SPIRE_APPLICANT_DETAILS" ADD CONSTRAINT "SPIRE_APPLICANT_DETAILS_CK2" CHECK (/* Valid status_control values */ STATUS_CONTROL IS NULL OR STATUS_CONTROL IN ('C','D')) ENABLE;
  ALTER TABLE "SPIREMGR"."SPIRE_APPLICANT_DETAILS" ADD CONSTRAINT "SPIRE_APPLICANT_DETAILS_CK1" CHECK (/* Valid status values */ STATUS IN ('DRAFT','CURRENT','ARCHIVED','DELETED')) ENABLE;
  ALTER TABLE "SPIREMGR"."SPIRE_APPLICANT_DETAILS" ADD PRIMARY KEY ("ID")
  USING INDEX  ENABLE;
  ALTER TABLE "SPIREMGR"."SPIRE_APPLICANT_DETAILS" MODIFY ("STATUS" NOT NULL ENABLE);
  ALTER TABLE "SPIREMGR"."SPIRE_APPLICANT_DETAILS" MODIFY ("START_DATE" NOT NULL ENABLE);
  ALTER TABLE "SPIREMGR"."SPIRE_APPLICANT_DETAILS" ADD CONSTRAINT "SPIRE_APPLICANT_DETAILS_CK4" CHECK (
  (end_date is not null AND status = 'ARCHIVED') 
  OR (end_date is not null AND start_date = end_date AND status IN ('DRAFT'))
  OR (end_date is null AND status IN ('CURRENT','DELETED'))
) ENABLE;
