--------------------------------------------------------
--  Constraints for Table SPIRE_ENHANCEMENT_DETAILS
--------------------------------------------------------

  ALTER TABLE "SAVEMGR"."SPIRE_ENHANCEMENT_DETAILS" MODIFY ("START_DATETIME" NOT NULL ENABLE);
  ALTER TABLE "SAVEMGR"."SPIRE_ENHANCEMENT_DETAILS" MODIFY ("DESCRIPTION" NOT NULL ENABLE);
  ALTER TABLE "SAVEMGR"."SPIRE_ENHANCEMENT_DETAILS" MODIFY ("SE_ID" NOT NULL ENABLE);
