--------------------------------------------------------
--  Constraints for Table SPIRE_FEEDBACK
--------------------------------------------------------

  ALTER TABLE "SPIREMGR"."SPIRE_FEEDBACK" ADD CONSTRAINT "SPIRE_FEEDBACK_PK1" PRIMARY KEY ("ID")
  USING INDEX  ENABLE;
  ALTER TABLE "SPIREMGR"."SPIRE_FEEDBACK" MODIFY ("FEEDBACK_XML" NOT NULL ENABLE);
  ALTER TABLE "SPIREMGR"."SPIRE_FEEDBACK" MODIFY ("SUBMITTED_DATETIME" NOT NULL ENABLE);
  ALTER TABLE "SPIREMGR"."SPIRE_FEEDBACK" MODIFY ("ID" NOT NULL ENABLE);
