--------------------------------------------------------
--  Constraints for Table SPIRE_ENHANCEMENT_DETAILS
--------------------------------------------------------

  ALTER TABLE "SPIREMGR"."SPIRE_ENHANCEMENT_DETAILS" ADD CONSTRAINT "SPIRE_ENHANCEMENT_DETAILS_CK1" CHECK ((status_control ='C' AND end_datetime IS NULL) OR (status_control IS NULL AND end_datetime IS NOT NULL)) ENABLE;
  ALTER TABLE "SPIREMGR"."SPIRE_ENHANCEMENT_DETAILS" ADD CONSTRAINT "SPIRE_ENHANCEMENT_DETAILS_PK" PRIMARY KEY ("ID")
  USING INDEX  ENABLE;
  ALTER TABLE "SPIREMGR"."SPIRE_ENHANCEMENT_DETAILS" MODIFY ("START_DATETIME" NOT NULL ENABLE);
  ALTER TABLE "SPIREMGR"."SPIRE_ENHANCEMENT_DETAILS" MODIFY ("DESCRIPTION" NOT NULL ENABLE);
  ALTER TABLE "SPIREMGR"."SPIRE_ENHANCEMENT_DETAILS" MODIFY ("SE_ID" NOT NULL ENABLE);
