--------------------------------------------------------
--  Constraints for Table SPREADSHEET_DEFINITIONS
--------------------------------------------------------

  ALTER TABLE "REPORTMGR"."SPREADSHEET_DEFINITIONS" ADD CONSTRAINT "SPREADSHEET_DEFINITIONS_PK" PRIMARY KEY ("DOMAIN")
  USING INDEX  ENABLE;
  ALTER TABLE "REPORTMGR"."SPREADSHEET_DEFINITIONS" MODIFY ("XML_DATA" NOT NULL ENABLE);
  ALTER TABLE "REPORTMGR"."SPREADSHEET_DEFINITIONS" MODIFY ("DOMAIN" NOT NULL ENABLE);
