--------------------------------------------------------
--  Constraints for Table STRUC_CODE_CONTROL_BCK_23_NOV
--------------------------------------------------------

  ALTER TABLE "SPIREMGR"."STRUC_CODE_CONTROL_BCK_23_NOV" MODIFY ("STATUS" NOT NULL ENABLE);
  ALTER TABLE "SPIREMGR"."STRUC_CODE_CONTROL_BCK_23_NOV" MODIFY ("CONTROL_TYPE" NOT NULL ENABLE);
  ALTER TABLE "SPIREMGR"."STRUC_CODE_CONTROL_BCK_23_NOV" MODIFY ("REFERENCED_SC_ID" NOT NULL ENABLE);
  ALTER TABLE "SPIREMGR"."STRUC_CODE_CONTROL_BCK_23_NOV" MODIFY ("SC_ID" NOT NULL ENABLE);
  ALTER TABLE "SPIREMGR"."STRUC_CODE_CONTROL_BCK_23_NOV" MODIFY ("SCR_ID" NOT NULL ENABLE);
  ALTER TABLE "SPIREMGR"."STRUC_CODE_CONTROL_BCK_23_NOV" MODIFY ("ID" NOT NULL ENABLE);
