--------------------------------------------------------
--  Constraints for Table STRUCTURED_CODE_CONTROLS
--------------------------------------------------------

  ALTER TABLE "SAVEMGR"."STRUCTURED_CODE_CONTROLS" MODIFY ("STATUS" NOT NULL ENABLE);
  ALTER TABLE "SAVEMGR"."STRUCTURED_CODE_CONTROLS" MODIFY ("CONTROL_TYPE" NOT NULL ENABLE);
  ALTER TABLE "SAVEMGR"."STRUCTURED_CODE_CONTROLS" MODIFY ("REFERENCED_SC_ID" NOT NULL ENABLE);
  ALTER TABLE "SAVEMGR"."STRUCTURED_CODE_CONTROLS" MODIFY ("SC_ID" NOT NULL ENABLE);
  ALTER TABLE "SAVEMGR"."STRUCTURED_CODE_CONTROLS" MODIFY ("SCR_ID" NOT NULL ENABLE);
  ALTER TABLE "SAVEMGR"."STRUCTURED_CODE_CONTROLS" MODIFY ("ID" NOT NULL ENABLE);
