--------------------------------------------------------
--  Constraints for Table STRUCTURED_CODES
--------------------------------------------------------

  ALTER TABLE "SPIREMGR"."STRUCTURED_CODES" ADD CONSTRAINT "STRUCTURED_CODES_UK3" UNIQUE ("CODE_VALUE", "SC_TYPE")
  USING INDEX  ENABLE;
  ALTER TABLE "SPIREMGR"."STRUCTURED_CODES" ADD CONSTRAINT "STRUCTURED_CODES_UK2" UNIQUE ("ID", "SC_TYPE")
  USING INDEX  ENABLE;
  ALTER TABLE "SPIREMGR"."STRUCTURED_CODES" ADD CONSTRAINT "STRUCTURED_CODES_UK1" UNIQUE ("CODE_VALUE", "SC_TYPE", "ID")
  USING INDEX  ENABLE;
  ALTER TABLE "SPIREMGR"."STRUCTURED_CODES" ADD CONSTRAINT "STRUCTURED_CODES_PK1" PRIMARY KEY ("ID")
  USING INDEX  ENABLE;
  ALTER TABLE "SPIREMGR"."STRUCTURED_CODES" MODIFY ("CODE_VALUE" NOT NULL ENABLE);
  ALTER TABLE "SPIREMGR"."STRUCTURED_CODES" MODIFY ("SC_TYPE" NOT NULL ENABLE);
  ALTER TABLE "SPIREMGR"."STRUCTURED_CODES" MODIFY ("ID" NOT NULL ENABLE);
