--------------------------------------------------------
--  Constraints for Table STRUCTURED_CODE_DETAILS
--------------------------------------------------------

  ALTER TABLE "SPIREMGR"."STRUCTURED_CODE_DETAILS" ADD CONSTRAINT "STRUCTURED_CODE_DETAILS_CK1" CHECK (CODE_STATUS IN ('ACTIVE', 'DELETED', 'PARENT', 'DELETED_PARENT')) ENABLE;
  ALTER TABLE "SPIREMGR"."STRUCTURED_CODE_DETAILS" ADD CONSTRAINT "STRUCTURED_CODE_DETAILS_UK2" UNIQUE ("ID", "SC_ID", "SCR_ID", "SC_TYPE", "SCR_STATUS")
  USING INDEX  ENABLE;
  ALTER TABLE "SPIREMGR"."STRUCTURED_CODE_DETAILS" ADD CONSTRAINT "STRUCTURED_CODE_DETAILS_PK1" PRIMARY KEY ("ID")
  USING INDEX  ENABLE;
  ALTER TABLE "SPIREMGR"."STRUCTURED_CODE_DETAILS" MODIFY ("XML_DATA" NOT NULL ENABLE);
  ALTER TABLE "SPIREMGR"."STRUCTURED_CODE_DETAILS" MODIFY ("START_DATETIME" NOT NULL ENABLE);
  ALTER TABLE "SPIREMGR"."STRUCTURED_CODE_DETAILS" MODIFY ("CODE_LEVEL" NOT NULL ENABLE);
  ALTER TABLE "SPIREMGR"."STRUCTURED_CODE_DETAILS" MODIFY ("CODE_STATUS" NOT NULL ENABLE);
  ALTER TABLE "SPIREMGR"."STRUCTURED_CODE_DETAILS" MODIFY ("CODE_VALUE" NOT NULL ENABLE);
  ALTER TABLE "SPIREMGR"."STRUCTURED_CODE_DETAILS" MODIFY ("SCR_STATUS" NOT NULL ENABLE);
  ALTER TABLE "SPIREMGR"."STRUCTURED_CODE_DETAILS" MODIFY ("SCR_ID" NOT NULL ENABLE);
  ALTER TABLE "SPIREMGR"."STRUCTURED_CODE_DETAILS" MODIFY ("SC_TYPE" NOT NULL ENABLE);
  ALTER TABLE "SPIREMGR"."STRUCTURED_CODE_DETAILS" MODIFY ("SC_ID" NOT NULL ENABLE);
  ALTER TABLE "SPIREMGR"."STRUCTURED_CODE_DETAILS" MODIFY ("ID" NOT NULL ENABLE);
