--------------------------------------------------------
--  Constraints for Table STRUCTURED_CODE_CONTROLS
--------------------------------------------------------

  ALTER TABLE "SPIREMGR"."STRUCTURED_CODE_CONTROLS" ADD CONSTRAINT "STRUCTURED_CODE_CONTROLS_CK1" CHECK (STATUS IN ('CURRENT', 'DELETED')) ENABLE;
  ALTER TABLE "SPIREMGR"."STRUCTURED_CODE_CONTROLS" ADD CONSTRAINT "STRUCTURED_CODE_CONTROLS_PK1" PRIMARY KEY ("ID")
  USING INDEX  ENABLE;
  ALTER TABLE "SPIREMGR"."STRUCTURED_CODE_CONTROLS" MODIFY ("STATUS" NOT NULL ENABLE);
  ALTER TABLE "SPIREMGR"."STRUCTURED_CODE_CONTROLS" MODIFY ("CONTROL_TYPE" NOT NULL ENABLE);
  ALTER TABLE "SPIREMGR"."STRUCTURED_CODE_CONTROLS" MODIFY ("REFERENCED_SC_ID" NOT NULL ENABLE);
  ALTER TABLE "SPIREMGR"."STRUCTURED_CODE_CONTROLS" MODIFY ("SC_ID" NOT NULL ENABLE);
  ALTER TABLE "SPIREMGR"."STRUCTURED_CODE_CONTROLS" MODIFY ("SCR_ID" NOT NULL ENABLE);
  ALTER TABLE "SPIREMGR"."STRUCTURED_CODE_CONTROLS" MODIFY ("ID" NOT NULL ENABLE);
