--------------------------------------------------------
--  Constraints for Table STRUCT_CODE_CONT_11_DEC_07
--------------------------------------------------------

  ALTER TABLE "SAVEMGR"."STRUCT_CODE_CONT_11_DEC_07" MODIFY ("STATUS" NOT NULL ENABLE);
  ALTER TABLE "SAVEMGR"."STRUCT_CODE_CONT_11_DEC_07" MODIFY ("CONTROL_TYPE" NOT NULL ENABLE);
  ALTER TABLE "SAVEMGR"."STRUCT_CODE_CONT_11_DEC_07" MODIFY ("REFERENCED_SC_ID" NOT NULL ENABLE);
  ALTER TABLE "SAVEMGR"."STRUCT_CODE_CONT_11_DEC_07" MODIFY ("SC_ID" NOT NULL ENABLE);
  ALTER TABLE "SAVEMGR"."STRUCT_CODE_CONT_11_DEC_07" MODIFY ("SCR_ID" NOT NULL ENABLE);
  ALTER TABLE "SAVEMGR"."STRUCT_CODE_CONT_11_DEC_07" MODIFY ("ID" NOT NULL ENABLE);
