--------------------------------------------------------
--  Constraints for Table STRUCT_CODE_BATCH_LOAD
--------------------------------------------------------

  ALTER TABLE "SPIREMGR"."STRUCT_CODE_BATCH_LOAD" ADD CONSTRAINT "STRUCT_CODE_BATCH_LOAD_CK1" CHECK (STATUS IN ('NEW', 'PROCESSING', 'IGNORE', 'LOADED', 'FAILED')) ENABLE;
  ALTER TABLE "SPIREMGR"."STRUCT_CODE_BATCH_LOAD" MODIFY ("CONTROL_ENTRY" NOT NULL ENABLE);
  ALTER TABLE "SPIREMGR"."STRUCT_CODE_BATCH_LOAD" MODIFY ("STATUS" NOT NULL ENABLE);
  ALTER TABLE "SPIREMGR"."STRUCT_CODE_BATCH_LOAD" MODIFY ("LOAD_ID" NOT NULL ENABLE);
