--------------------------------------------------------
--  Constraints for Table SUB_ADVICE_UPLOADS
--------------------------------------------------------

  ALTER TABLE "PVEXMGR"."SUB_ADVICE_UPLOADS" ADD CONSTRAINT "SUB_ADVICE_UPLOADS_CK1" CHECK (status_control = 'C' OR status_control IS NULL) ENABLE;
  ALTER TABLE "PVEXMGR"."SUB_ADVICE_UPLOADS" ADD CONSTRAINT "SUB_ADVICE_UPLOADS_PK" PRIMARY KEY ("FILE_ID")
  USING INDEX  ENABLE;
  ALTER TABLE "PVEXMGR"."SUB_ADVICE_UPLOADS" MODIFY ("FILE_CONTENT" NOT NULL ENABLE);
  ALTER TABLE "PVEXMGR"."SUB_ADVICE_UPLOADS" MODIFY ("FILE_ID" NOT NULL ENABLE);
