--------------------------------------------------------
--  Constraints for Table SURVEY_TYPE_DETAILS
--------------------------------------------------------

  ALTER TABLE "SURVEYMGR"."SURVEY_TYPE_DETAILS" ADD CONSTRAINT "SURVEY_TYPE_DETAILS_CK1" CHECK (
	status IN ('DRAFT', 'CURRENT') AND status_control = 'C'
	OR
	status = 'DRAFT' AND status_control = 'D'
	OR
	status = 'CURRENT' AND status_control = 'A'
	) ENABLE;
  ALTER TABLE "SURVEYMGR"."SURVEY_TYPE_DETAILS" ADD CONSTRAINT "SURVEY_TYPE_DETAILS_PK" PRIMARY KEY ("ID")
  USING INDEX  ENABLE;
  ALTER TABLE "SURVEYMGR"."SURVEY_TYPE_DETAILS" MODIFY ("XML_DATA" NOT NULL ENABLE);
  ALTER TABLE "SURVEYMGR"."SURVEY_TYPE_DETAILS" MODIFY ("STATUS_CONTROL" NOT NULL ENABLE);
  ALTER TABLE "SURVEYMGR"."SURVEY_TYPE_DETAILS" MODIFY ("STATUS" NOT NULL ENABLE);
  ALTER TABLE "SURVEYMGR"."SURVEY_TYPE_DETAILS" MODIFY ("START_DATE" NOT NULL ENABLE);
  ALTER TABLE "SURVEYMGR"."SURVEY_TYPE_DETAILS" MODIFY ("ST_ID" NOT NULL ENABLE);
  ALTER TABLE "SURVEYMGR"."SURVEY_TYPE_DETAILS" MODIFY ("ID" NOT NULL ENABLE);
