--------------------------------------------------------
--  Constraints for Table SURVEY_TYPES
--------------------------------------------------------

  ALTER TABLE "SURVEYMGR"."SURVEY_TYPES" ADD CONSTRAINT "SURVEY_TYPES_CK1" CHECK (
	status IN ('OPEN', 'EXPIRED')
) ENABLE;
  ALTER TABLE "SURVEYMGR"."SURVEY_TYPES" ADD CONSTRAINT "SURVEY_TYPES_PK" PRIMARY KEY ("ID")
  USING INDEX  ENABLE;
  ALTER TABLE "SURVEYMGR"."SURVEY_TYPES" MODIFY ("STATUS" NOT NULL ENABLE);
  ALTER TABLE "SURVEYMGR"."SURVEY_TYPES" MODIFY ("ID" NOT NULL ENABLE);
