--------------------------------------------------------
--  Constraints for Table SURVEY_INSTANCES
--------------------------------------------------------

  ALTER TABLE "SURVEYMGR"."SURVEY_INSTANCES" ADD CONSTRAINT "SURVEY_INSTANCES_CK2" CHECK (
	instance_type IN ('TEMPLATE', 'REQUEST')
	) ENABLE;
  ALTER TABLE "SURVEYMGR"."SURVEY_INSTANCES" ADD CONSTRAINT "SURVEY_INSTANCES_CK1" CHECK (
	instance_type = 'TEMPLATE'
	OR
	(wua_id IS NOT NULL AND non_wua_email_address IS NULL)
	OR
	(wua_id IS NULL AND non_wua_email_address IS NOT NULL)
	) ENABLE;
  ALTER TABLE "SURVEYMGR"."SURVEY_INSTANCES" ADD CONSTRAINT "SURVEY_INSTANCES_PK" PRIMARY KEY ("ID")
  USING INDEX  ENABLE;
  ALTER TABLE "SURVEYMGR"."SURVEY_INSTANCES" MODIFY ("XML_DATA" NOT NULL ENABLE);
  ALTER TABLE "SURVEYMGR"."SURVEY_INSTANCES" MODIFY ("CREATED_DATETIME" NOT NULL ENABLE);
  ALTER TABLE "SURVEYMGR"."SURVEY_INSTANCES" MODIFY ("INSTANCE_TYPE" NOT NULL ENABLE);
  ALTER TABLE "SURVEYMGR"."SURVEY_INSTANCES" MODIFY ("ST_ID" NOT NULL ENABLE);
  ALTER TABLE "SURVEYMGR"."SURVEY_INSTANCES" MODIFY ("ID" NOT NULL ENABLE);
