--------------------------------------------------------
--  Constraints for Table TALLY_WEEK_PLAN_DETAILS
--------------------------------------------------------

  ALTER TABLE "BPMMGR"."TALLY_WEEK_PLAN_DETAILS" ADD CONSTRAINT "TALLY_WEEK_PLAN_DETAILS_UK1" UNIQUE ("TWP_ID", "START_DATE")
  USING INDEX  ENABLE;
  ALTER TABLE "BPMMGR"."TALLY_WEEK_PLAN_DETAILS" ADD CONSTRAINT "TALLY_WEEK_PLAN_DETAILS_PK" PRIMARY KEY ("ID")
  USING INDEX  ENABLE;
  ALTER TABLE "BPMMGR"."TALLY_WEEK_PLAN_DETAILS" ADD CONSTRAINT "TALLY_WEEK_PLAN_DETAILS_CK1" CHECK (start_date = trunc(start_date)) ENABLE;
  ALTER TABLE "BPMMGR"."TALLY_WEEK_PLAN_DETAILS" MODIFY ("CREATED_BY_WUA_ID" NOT NULL ENABLE);
  ALTER TABLE "BPMMGR"."TALLY_WEEK_PLAN_DETAILS" MODIFY ("START_DATE" NOT NULL ENABLE);
  ALTER TABLE "BPMMGR"."TALLY_WEEK_PLAN_DETAILS" MODIFY ("TWP_ID" NOT NULL ENABLE);
  ALTER TABLE "BPMMGR"."TALLY_WEEK_PLAN_DETAILS" MODIFY ("ID" NOT NULL ENABLE);
