--------------------------------------------------------
--  Constraints for Table TALLY_ADJUSTMENTS
--------------------------------------------------------

  ALTER TABLE "BPMMGR"."TALLY_ADJUSTMENTS" ADD CONSTRAINT "TALLY_ADJUSTMENTS_PK" PRIMARY KEY ("ID")
  USING INDEX  ENABLE;
  ALTER TABLE "BPMMGR"."TALLY_ADJUSTMENTS" MODIFY ("STORE" NOT NULL ENABLE);
  ALTER TABLE "BPMMGR"."TALLY_ADJUSTMENTS" MODIFY ("ADJUSTMENT" NOT NULL ENABLE);
  ALTER TABLE "BPMMGR"."TALLY_ADJUSTMENTS" MODIFY ("TALLY_ID" NOT NULL ENABLE);
  ALTER TABLE "BPMMGR"."TALLY_ADJUSTMENTS" MODIFY ("ID" NOT NULL ENABLE);
