--------------------------------------------------------
--  Constraints for Table TALLY_NORMALS
--------------------------------------------------------

  ALTER TABLE "SAVEMGR"."TALLY_NORMALS" MODIFY ("SWITCH" NOT NULL ENABLE);
  ALTER TABLE "SAVEMGR"."TALLY_NORMALS" MODIFY ("END_DT" NOT NULL ENABLE);
  ALTER TABLE "SAVEMGR"."TALLY_NORMALS" MODIFY ("START_DT" NOT NULL ENABLE);
  ALTER TABLE "SAVEMGR"."TALLY_NORMALS" MODIFY ("TALLY_ID" NOT NULL ENABLE);
  ALTER TABLE "SAVEMGR"."TALLY_NORMALS" MODIFY ("TI_ID" NOT NULL ENABLE);
  ALTER TABLE "SAVEMGR"."TALLY_NORMALS" MODIFY ("ID" NOT NULL ENABLE);
