--------------------------------------------------------
--  Constraints for Table TALLY_CALENDAR_EVENTS
--------------------------------------------------------

  ALTER TABLE "BPMMGR"."TALLY_CALENDAR_EVENTS" ADD CONSTRAINT "TALLY_CALENDAR_EVENTS_UK1" UNIQUE ("TC_ID", "FROM_DT")
  USING INDEX  ENABLE;
  ALTER TABLE "BPMMGR"."TALLY_CALENDAR_EVENTS" ADD CONSTRAINT "TALLY_CALENDAR_EVENTS_PK" PRIMARY KEY ("ID")
  USING INDEX (CREATE UNIQUE INDEX "BPMMGR"."TALLY_CALENDAR_PK" ON "BPMMGR"."TALLY_CALENDAR_EVENTS" ("ID") 
  )  ENABLE;
  ALTER TABLE "BPMMGR"."TALLY_CALENDAR_EVENTS" ADD CONSTRAINT "TALLY_CALENDAR_EVENTS_CK1" CHECK (SWITCH IN ('INT','RUN')) ENABLE;
  ALTER TABLE "BPMMGR"."TALLY_CALENDAR_EVENTS" MODIFY ("SWITCH" NOT NULL ENABLE);
  ALTER TABLE "BPMMGR"."TALLY_CALENDAR_EVENTS" MODIFY ("FROM_DT" NOT NULL ENABLE);
  ALTER TABLE "BPMMGR"."TALLY_CALENDAR_EVENTS" MODIFY ("TC_ID" NOT NULL ENABLE);
  ALTER TABLE "BPMMGR"."TALLY_CALENDAR_EVENTS" MODIFY ("ID" NOT NULL ENABLE);
