--------------------------------------------------------
--  Constraints for Table TALLY_WEEK_PLAN_DETAILS
--------------------------------------------------------

  ALTER TABLE "SAVEMGR"."TALLY_WEEK_PLAN_DETAILS" MODIFY ("CREATED_BY_WUA_ID" NOT NULL ENABLE);
  ALTER TABLE "SAVEMGR"."TALLY_WEEK_PLAN_DETAILS" MODIFY ("START_DATETIME" NOT NULL ENABLE);
  ALTER TABLE "SAVEMGR"."TALLY_WEEK_PLAN_DETAILS" MODIFY ("TWP_ID" NOT NULL ENABLE);
  ALTER TABLE "SAVEMGR"."TALLY_WEEK_PLAN_DETAILS" MODIFY ("ID" NOT NULL ENABLE);
