--------------------------------------------------------
--  Constraints for Table TALLY_ADJUSTMENTS
--------------------------------------------------------

  ALTER TABLE "SAVEMGR"."TALLY_ADJUSTMENTS" MODIFY ("STORE" NOT NULL ENABLE);
  ALTER TABLE "SAVEMGR"."TALLY_ADJUSTMENTS" MODIFY ("ADJUSTMENT" NOT NULL ENABLE);
  ALTER TABLE "SAVEMGR"."TALLY_ADJUSTMENTS" MODIFY ("TALLY_ID" NOT NULL ENABLE);
  ALTER TABLE "SAVEMGR"."TALLY_ADJUSTMENTS" MODIFY ("ID" NOT NULL ENABLE);
