--------------------------------------------------------
--  Constraints for Table TALLY_ADJUSTMENT_DETAILS
--------------------------------------------------------

  ALTER TABLE "BPMMGR"."TALLY_ADJUSTMENT_DETAILS" ADD CONSTRAINT "TALLY_ADJUSTMENT_DETAILS_PK" PRIMARY KEY ("ID")
  USING INDEX (CREATE UNIQUE INDEX "BPMMGR"."TALLY_ADJUSTMENTS_DETAILS_PK" ON "BPMMGR"."TALLY_ADJUSTMENT_DETAILS" ("ID") 
  )  ENABLE;
  ALTER TABLE "BPMMGR"."TALLY_ADJUSTMENT_DETAILS" ADD CONSTRAINT "TALLY_ADJUSTMENT_DETAILS_CK1" CHECK (/* End date and status control */ (END_DATETIME IS NULL AND STATUS_CONTROL='C') OR (END_DATETIME IS NOT NULL AND STATUS_CONTROL IS NULL)) ENABLE;
  ALTER TABLE "BPMMGR"."TALLY_ADJUSTMENT_DETAILS" MODIFY ("CREATED_BY_WUA_ID" NOT NULL ENABLE);
  ALTER TABLE "BPMMGR"."TALLY_ADJUSTMENT_DETAILS" MODIFY ("START_DATETIME" NOT NULL ENABLE);
  ALTER TABLE "BPMMGR"."TALLY_ADJUSTMENT_DETAILS" MODIFY ("TA_ID" NOT NULL ENABLE);
  ALTER TABLE "BPMMGR"."TALLY_ADJUSTMENT_DETAILS" MODIFY ("ID" NOT NULL ENABLE);
