--------------------------------------------------------
--  Constraints for Table TALLY_ADJUSTMENT_DETAILS
--------------------------------------------------------

  ALTER TABLE "SAVEMGR"."TALLY_ADJUSTMENT_DETAILS" MODIFY ("CREATED_BY_WUA_ID" NOT NULL ENABLE);
  ALTER TABLE "SAVEMGR"."TALLY_ADJUSTMENT_DETAILS" MODIFY ("START_DATETIME" NOT NULL ENABLE);
  ALTER TABLE "SAVEMGR"."TALLY_ADJUSTMENT_DETAILS" MODIFY ("TA_ID" NOT NULL ENABLE);
  ALTER TABLE "SAVEMGR"."TALLY_ADJUSTMENT_DETAILS" MODIFY ("ID" NOT NULL ENABLE);
