--------------------------------------------------------
--  Constraints for Table TALLY_INTERPRETATIONS
--------------------------------------------------------

  ALTER TABLE "BPMMGR"."TALLY_INTERPRETATIONS" ADD CONSTRAINT "TALLY_INTERPRETATIONS_UK1" UNIQUE ("TALLY_ID", "SUBJECT_UREF_NN")
  USING INDEX  ENABLE;
  ALTER TABLE "BPMMGR"."TALLY_INTERPRETATIONS" MODIFY ("SUBJECT_UREF_NN" NOT NULL ENABLE);
  ALTER TABLE "BPMMGR"."TALLY_INTERPRETATIONS" ADD CONSTRAINT "TALLY_INTERPRETATIONS_PK" PRIMARY KEY ("ID")
  USING INDEX  ENABLE;
  ALTER TABLE "BPMMGR"."TALLY_INTERPRETATIONS" MODIFY ("TALLY_ID" NOT NULL ENABLE);
  ALTER TABLE "BPMMGR"."TALLY_INTERPRETATIONS" MODIFY ("ID" NOT NULL ENABLE);
