--------------------------------------------------------
--  Constraints for Table TAU_SFE_COUNTRY_GROUPS
--------------------------------------------------------

  ALTER TABLE "SPIREMGR"."TAU_SFE_COUNTRY_GROUPS" MODIFY ("CREATED_BY_WUA_ID" NOT NULL ENABLE);
  ALTER TABLE "SPIREMGR"."TAU_SFE_COUNTRY_GROUPS" MODIFY ("START_DATETIME" NOT NULL ENABLE);
  ALTER TABLE "SPIREMGR"."TAU_SFE_COUNTRY_GROUPS" MODIFY ("SHORT_NAME" NOT NULL ENABLE);
  ALTER TABLE "SPIREMGR"."TAU_SFE_COUNTRY_GROUPS" MODIFY ("SFE_COUNTRY_GROUP" NOT NULL ENABLE);
