--------------------------------------------------------
--  Constraints for Table TAU_ARS_WITH_GOODS_QUANTITIES
--------------------------------------------------------

  ALTER TABLE "SPIREMGR"."TAU_ARS_WITH_GOODS_QUANTITIES" MODIFY ("CREATED_BY_WUA_ID" NOT NULL ENABLE);
  ALTER TABLE "SPIREMGR"."TAU_ARS_WITH_GOODS_QUANTITIES" MODIFY ("START_DATETIME" NOT NULL ENABLE);
  ALTER TABLE "SPIREMGR"."TAU_ARS_WITH_GOODS_QUANTITIES" MODIFY ("ARS" NOT NULL ENABLE);
