--------------------------------------------------------
--  Constraints for Table TAU_CHECKED_CONTROL_ENTRIES
--------------------------------------------------------

  ALTER TABLE "SPIREMGR"."TAU_CHECKED_CONTROL_ENTRIES" MODIFY ("CREATED_BY_WUA_ID" NOT NULL ENABLE);
  ALTER TABLE "SPIREMGR"."TAU_CHECKED_CONTROL_ENTRIES" MODIFY ("START_DATETIME" NOT NULL ENABLE);
  ALTER TABLE "SPIREMGR"."TAU_CHECKED_CONTROL_ENTRIES" MODIFY ("CONTROL_ENTRY" NOT NULL ENABLE);
