--------------------------------------------------------
--  Constraints for Table TEMPLATE_CLAUSE_DETAILS_4
--------------------------------------------------------

  ALTER TABLE "SAVEMGR"."TEMPLATE_CLAUSE_DETAILS_4" MODIFY ("START_DATETIME" NOT NULL ENABLE);
  ALTER TABLE "SAVEMGR"."TEMPLATE_CLAUSE_DETAILS_4" MODIFY ("STATUS" NOT NULL ENABLE);
  ALTER TABLE "SAVEMGR"."TEMPLATE_CLAUSE_DETAILS_4" MODIFY ("TC_ID" NOT NULL ENABLE);
  ALTER TABLE "SAVEMGR"."TEMPLATE_CLAUSE_DETAILS_4" MODIFY ("ID" NOT NULL ENABLE);
