--------------------------------------------------------
--  Constraints for Table TEMPLATE_CLAUSE_DETAILS
--------------------------------------------------------

  ALTER TABLE "SAVEMGR"."TEMPLATE_CLAUSE_DETAILS" MODIFY ("START_DATETIME" NOT NULL ENABLE);
  ALTER TABLE "SAVEMGR"."TEMPLATE_CLAUSE_DETAILS" MODIFY ("STATUS" NOT NULL ENABLE);
  ALTER TABLE "SAVEMGR"."TEMPLATE_CLAUSE_DETAILS" MODIFY ("TC_ID" NOT NULL ENABLE);
  ALTER TABLE "SAVEMGR"."TEMPLATE_CLAUSE_DETAILS" MODIFY ("ID" NOT NULL ENABLE);
