--------------------------------------------------------
--  Constraints for Table TEMPLATE_CLAUSE_ATTR_LOADER
--------------------------------------------------------

  ALTER TABLE "BPMMGR"."TEMPLATE_CLAUSE_ATTR_LOADER" ADD CONSTRAINT "TEMPLATE_CLAUSE_ATTR_LDER_CK1" CHECK (lower(ENTER_COMMAND_HERE) IN ('c')) ENABLE;
  ALTER TABLE "BPMMGR"."TEMPLATE_CLAUSE_ATTR_LOADER" MODIFY ("CLAUSE_TYPE_ID" NOT NULL ENABLE);
  ALTER TABLE "BPMMGR"."TEMPLATE_CLAUSE_ATTR_LOADER" MODIFY ("SHORT_CODE" NOT NULL ENABLE);
