--------------------------------------------------------
--  Constraints for Table TEMPLATE_CLAUSE_DETAILS
--------------------------------------------------------

  ALTER TABLE "BPMMGR"."TEMPLATE_CLAUSE_DETAILS" ADD CONSTRAINT "TEMPLATE_CLAUSE_DETAILS_CK3" CHECK (/* Valid status to control mappings */ STATUS||'='||STATUS_CONTROL IN ('CURRENT=C','ARCHIVED=','DELETED=C')) ENABLE;
  ALTER TABLE "BPMMGR"."TEMPLATE_CLAUSE_DETAILS" ADD CONSTRAINT "TEMPLATE_CLAUSE_DETAILS_CK2" CHECK (/* Valid status values */ STATUS IN ('CURRENT','ARCHIVED','DELETED')) ENABLE;
  ALTER TABLE "BPMMGR"."TEMPLATE_CLAUSE_DETAILS" ADD CONSTRAINT "TEMPLATE_CLAUSE_DETAILS_CK1" CHECK (/* Valid status_control values */ STATUS_CONTROL IS NULL OR STATUS_CONTROL = 'C') ENABLE;
  ALTER TABLE "BPMMGR"."TEMPLATE_CLAUSE_DETAILS" ADD CONSTRAINT "TEMPLATE_CLAUSE_DETAILS_PK" PRIMARY KEY ("ID")
  USING INDEX  ENABLE;
  ALTER TABLE "BPMMGR"."TEMPLATE_CLAUSE_DETAILS" MODIFY ("XML_DATA" NOT NULL ENABLE);
  ALTER TABLE "BPMMGR"."TEMPLATE_CLAUSE_DETAILS" MODIFY ("START_DATETIME" NOT NULL ENABLE);
  ALTER TABLE "BPMMGR"."TEMPLATE_CLAUSE_DETAILS" MODIFY ("STATUS" NOT NULL ENABLE);
  ALTER TABLE "BPMMGR"."TEMPLATE_CLAUSE_DETAILS" MODIFY ("TC_ID" NOT NULL ENABLE);
  ALTER TABLE "BPMMGR"."TEMPLATE_CLAUSE_DETAILS" MODIFY ("ID" NOT NULL ENABLE);
