--------------------------------------------------------
--  Constraints for Table TEMPLATE_CLAUSE_DETAILS_3
--------------------------------------------------------

  ALTER TABLE "SAVEMGR"."TEMPLATE_CLAUSE_DETAILS_3" MODIFY ("START_DATETIME" NOT NULL ENABLE);
  ALTER TABLE "SAVEMGR"."TEMPLATE_CLAUSE_DETAILS_3" MODIFY ("STATUS" NOT NULL ENABLE);
  ALTER TABLE "SAVEMGR"."TEMPLATE_CLAUSE_DETAILS_3" MODIFY ("TC_ID" NOT NULL ENABLE);
  ALTER TABLE "SAVEMGR"."TEMPLATE_CLAUSE_DETAILS_3" MODIFY ("ID" NOT NULL ENABLE);
