--------------------------------------------------------
--  Constraints for Table TEMPLATE_CLAUSE_DETAILS_1
--------------------------------------------------------

  ALTER TABLE "SAVEMGR"."TEMPLATE_CLAUSE_DETAILS_1" MODIFY ("START_DATETIME" NOT NULL ENABLE);
  ALTER TABLE "SAVEMGR"."TEMPLATE_CLAUSE_DETAILS_1" MODIFY ("STATUS" NOT NULL ENABLE);
  ALTER TABLE "SAVEMGR"."TEMPLATE_CLAUSE_DETAILS_1" MODIFY ("TC_ID" NOT NULL ENABLE);
  ALTER TABLE "SAVEMGR"."TEMPLATE_CLAUSE_DETAILS_1" MODIFY ("ID" NOT NULL ENABLE);
