--------------------------------------------------------
--  Constraints for Table TEMPLATE_CLAUSE_DETAILS_2
--------------------------------------------------------

  ALTER TABLE "SAVEMGR"."TEMPLATE_CLAUSE_DETAILS_2" MODIFY ("START_DATETIME" NOT NULL ENABLE);
  ALTER TABLE "SAVEMGR"."TEMPLATE_CLAUSE_DETAILS_2" MODIFY ("STATUS" NOT NULL ENABLE);
  ALTER TABLE "SAVEMGR"."TEMPLATE_CLAUSE_DETAILS_2" MODIFY ("TC_ID" NOT NULL ENABLE);
  ALTER TABLE "SAVEMGR"."TEMPLATE_CLAUSE_DETAILS_2" MODIFY ("ID" NOT NULL ENABLE);
