--------------------------------------------------------
--  Constraints for Table TEMPLATE_CLAUSE_SETS
--------------------------------------------------------

  ALTER TABLE "BPMMGR"."TEMPLATE_CLAUSE_SETS" ADD CONSTRAINT "TEMPLATE_CLAUSE_SETS_PK" PRIMARY KEY ("ID")
  USING INDEX  ENABLE;
  ALTER TABLE "BPMMGR"."TEMPLATE_CLAUSE_SETS" MODIFY ("TITLE" NOT NULL ENABLE);
  ALTER TABLE "BPMMGR"."TEMPLATE_CLAUSE_SETS" MODIFY ("CLAUSE_TYPE_ID" NOT NULL ENABLE);
  ALTER TABLE "BPMMGR"."TEMPLATE_CLAUSE_SETS" MODIFY ("ID" NOT NULL ENABLE);
