--------------------------------------------------------
--  Constraints for Table TFA_LOGIN_AUDIT
--------------------------------------------------------

  ALTER TABLE "SECUREMGR"."TFA_LOGIN_AUDIT" ADD CONSTRAINT "TFA_LOGIN_AUDIT_CK1" CHECK (login_status IN ('CODE_REQUESTED','SUCCESS','FAILURE','CANCELLED')) ENABLE;
  ALTER TABLE "SECUREMGR"."TFA_LOGIN_AUDIT" ADD CONSTRAINT "TFA_LOGIN_AUDIT_PK" PRIMARY KEY ("ID")
  USING INDEX  ENABLE;
  ALTER TABLE "SECUREMGR"."TFA_LOGIN_AUDIT" MODIFY ("LOGIN_STATUS" NOT NULL ENABLE);
  ALTER TABLE "SECUREMGR"."TFA_LOGIN_AUDIT" MODIFY ("REQUEST_DATETIME" NOT NULL ENABLE);
  ALTER TABLE "SECUREMGR"."TFA_LOGIN_AUDIT" MODIFY ("TRD_DETAIL_ID" NOT NULL ENABLE);
  ALTER TABLE "SECUREMGR"."TFA_LOGIN_AUDIT" MODIFY ("ID" NOT NULL ENABLE);
