--------------------------------------------------------
--  Constraints for Table TFA_DEVICE_TYPES
--------------------------------------------------------

  ALTER TABLE "SECUREMGR"."TFA_DEVICE_TYPES" ADD CONSTRAINT "TFA_DEVICE_TYPE_UNIQUE" UNIQUE ("DEVICE_TYPE")
  USING INDEX  ENABLE;
  ALTER TABLE "SECUREMGR"."TFA_DEVICE_TYPES" MODIFY ("DEVICE_PRIORITY" NOT NULL ENABLE);
  ALTER TABLE "SECUREMGR"."TFA_DEVICE_TYPES" MODIFY ("DEVICE_TYPE" NOT NULL ENABLE);
