--------------------------------------------------------
--  Constraints for Table TFA_REGISTERED_DEVICE_DETAILS
--------------------------------------------------------

  ALTER TABLE "SECUREMGR"."TFA_REGISTERED_DEVICE_DETAILS" ADD CONSTRAINT "TFA_REG_DEVICE_DETAILS_CK1" CHECK (
    (device_type = 'SMARTPHONE' AND shared_secret IS NOT NULL AND mobile_number IS NULL)
    OR
    (device_type = 'MOBILE_PHONE' AND mobile_number IS NOT NULL AND shared_secret IS NULL)
  ) ENABLE;
  ALTER TABLE "SECUREMGR"."TFA_REGISTERED_DEVICE_DETAILS" ADD CONSTRAINT "TFA_REG_DEVICE_DETAILS_PK" PRIMARY KEY ("ID")
  USING INDEX  ENABLE;
  ALTER TABLE "SECUREMGR"."TFA_REGISTERED_DEVICE_DETAILS" MODIFY ("DEVICE_TYPE" NOT NULL ENABLE);
  ALTER TABLE "SECUREMGR"."TFA_REGISTERED_DEVICE_DETAILS" MODIFY ("START_DATETIME" NOT NULL ENABLE);
  ALTER TABLE "SECUREMGR"."TFA_REGISTERED_DEVICE_DETAILS" MODIFY ("STATUS" NOT NULL ENABLE);
  ALTER TABLE "SECUREMGR"."TFA_REGISTERED_DEVICE_DETAILS" MODIFY ("WUA_ID" NOT NULL ENABLE);
  ALTER TABLE "SECUREMGR"."TFA_REGISTERED_DEVICE_DETAILS" MODIFY ("TRD_ID" NOT NULL ENABLE);
  ALTER TABLE "SECUREMGR"."TFA_REGISTERED_DEVICE_DETAILS" MODIFY ("ID" NOT NULL ENABLE);
