--------------------------------------------------------
--  Constraints for Table THIRD_PARTIES_DB
--------------------------------------------------------

  ALTER TABLE "SAVEMGR"."THIRD_PARTIES_DB" MODIFY ("STATUS_CONTROL" NOT NULL ENABLE);
  ALTER TABLE "SAVEMGR"."THIRD_PARTIES_DB" MODIFY ("VERSION_NO" NOT NULL ENABLE);
  ALTER TABLE "SAVEMGR"."THIRD_PARTIES_DB" MODIFY ("START_DATE" NOT NULL ENABLE);
  ALTER TABLE "SAVEMGR"."THIRD_PARTIES_DB" MODIFY ("COUNTRY_ID" NOT NULL ENABLE);
  ALTER TABLE "SAVEMGR"."THIRD_PARTIES_DB" MODIFY ("ELA_GRP_ID" NOT NULL ENABLE);
  ALTER TABLE "SAVEMGR"."THIRD_PARTIES_DB" MODIFY ("TP_ID" NOT NULL ENABLE);
