--------------------------------------------------------
--  Constraints for Table TOKEN_REQUESTS
--------------------------------------------------------

  ALTER TABLE "SECUREMGR"."TOKEN_REQUESTS" ADD CONSTRAINT "TOKEN_REQUESTS_CK1" CHECK (used IN ('Y','N')) ENABLE;
  ALTER TABLE "SECUREMGR"."TOKEN_REQUESTS" ADD CONSTRAINT "TOKEN_REQUESTS_PK" PRIMARY KEY ("ID")
  USING INDEX  ENABLE;
  ALTER TABLE "SECUREMGR"."TOKEN_REQUESTS" MODIFY ("USED" NOT NULL ENABLE);
  ALTER TABLE "SECUREMGR"."TOKEN_REQUESTS" MODIFY ("TOKEN" NOT NULL ENABLE);
