--------------------------------------------------------
--  Constraints for Table TRANSMISSION_CONTENT
--------------------------------------------------------

  ALTER TABLE "PORTALMGR"."TRANSMISSION_CONTENT" ADD CONSTRAINT "TRANSMISSION_CONTENT_PK" PRIMARY KEY ("MAIL_ID", "ATT_SEQ")
  USING INDEX  ENABLE;
  ALTER TABLE "PORTALMGR"."TRANSMISSION_CONTENT" MODIFY ("MIMETYPE" NOT NULL ENABLE);
  ALTER TABLE "PORTALMGR"."TRANSMISSION_CONTENT" MODIFY ("ATT_SEQ" NOT NULL ENABLE);
  ALTER TABLE "PORTALMGR"."TRANSMISSION_CONTENT" MODIFY ("MAIL_ID" NOT NULL ENABLE);
