--------------------------------------------------------
--  Constraints for Table TRANSMISSION_SET
--------------------------------------------------------

  ALTER TABLE "PORTALMGR"."TRANSMISSION_SET" ADD CONSTRAINT "TRANSMISSION_SET_CK1" CHECK (show_copy_recipients IS NULL OR show_copy_recipients IN ('true','false')) ENABLE;
  ALTER TABLE "PORTALMGR"."TRANSMISSION_SET" ADD CONSTRAINT "PK_MAIL_ID" PRIMARY KEY ("MAIL_ID")
  USING INDEX  ENABLE;
  ALTER TABLE "PORTALMGR"."TRANSMISSION_SET" MODIFY ("STATUS" NOT NULL ENABLE);
  ALTER TABLE "PORTALMGR"."TRANSMISSION_SET" MODIFY ("ATT_CHECKSUM" NOT NULL ENABLE);
  ALTER TABLE "PORTALMGR"."TRANSMISSION_SET" MODIFY ("REQUESTED_BY" NOT NULL ENABLE);
  ALTER TABLE "PORTALMGR"."TRANSMISSION_SET" MODIFY ("REQUESTED_DATE" NOT NULL ENABLE);
  ALTER TABLE "PORTALMGR"."TRANSMISSION_SET" MODIFY ("MAIL_ID" NOT NULL ENABLE);
