--------------------------------------------------------
--  Constraints for Table TRANSMISSION_REQUESTS
--------------------------------------------------------

  ALTER TABLE "PORTALMGR"."TRANSMISSION_REQUESTS" ADD CONSTRAINT "PK_TRANSMISSION_REQUESTS" PRIMARY KEY ("ID")
  USING INDEX  ENABLE;
  ALTER TABLE "PORTALMGR"."TRANSMISSION_REQUESTS" MODIFY ("FIRST_REQUESTED_BY" NOT NULL ENABLE);
  ALTER TABLE "PORTALMGR"."TRANSMISSION_REQUESTS" MODIFY ("FIRST_REQUESTED_DATE" NOT NULL ENABLE);
  ALTER TABLE "PORTALMGR"."TRANSMISSION_REQUESTS" MODIFY ("NO_SEND" NOT NULL ENABLE);
  ALTER TABLE "PORTALMGR"."TRANSMISSION_REQUESTS" MODIFY ("TO_TYPE" NOT NULL ENABLE);
  ALTER TABLE "PORTALMGR"."TRANSMISSION_REQUESTS" MODIFY ("FORMAT" NOT NULL ENABLE);
  ALTER TABLE "PORTALMGR"."TRANSMISSION_REQUESTS" MODIFY ("STATUS" NOT NULL ENABLE);
  ALTER TABLE "PORTALMGR"."TRANSMISSION_REQUESTS" MODIFY ("MAIL_ID" NOT NULL ENABLE);
  ALTER TABLE "PORTALMGR"."TRANSMISSION_REQUESTS" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "PORTALMGR"."TRANSMISSION_REQUESTS" ADD CONSTRAINT "TRANSMISSION_REQUESTS_CK1" CHECK ( transmission_route IS NULL OR transmission_route IN ('GSE')) ENABLE;
