--------------------------------------------------------
--  Constraints for Table TRANSMISSION_REQUEST_LOGS
--------------------------------------------------------

  ALTER TABLE "PORTALMGR"."TRANSMISSION_REQUEST_LOGS" MODIFY ("START_DATETIME" NOT NULL ENABLE);
  ALTER TABLE "PORTALMGR"."TRANSMISSION_REQUEST_LOGS" MODIFY ("STATUS" NOT NULL ENABLE);
  ALTER TABLE "PORTALMGR"."TRANSMISSION_REQUEST_LOGS" MODIFY ("TR_ID" NOT NULL ENABLE);
  ALTER TABLE "PORTALMGR"."TRANSMISSION_REQUEST_LOGS" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "PORTALMGR"."TRANSMISSION_REQUEST_LOGS" ADD CONSTRAINT "TRANSMISSION_REQUEST_LOGS_PK" PRIMARY KEY ("ID")
  USING INDEX  ENABLE;
