--------------------------------------------------------
--  Constraints for Table UREF_PRIVILEGES
--------------------------------------------------------

  ALTER TABLE "BPMMGR"."UREF_PRIVILEGES" ADD CONSTRAINT "UREF_PRIVS_UREF_CK1" CHECK (uref like '%'||uref_type) ENABLE;
  ALTER TABLE "BPMMGR"."UREF_PRIVILEGES" MODIFY ("RES_TYPE" NOT NULL ENABLE);
  ALTER TABLE "BPMMGR"."UREF_PRIVILEGES" MODIFY ("PRIVILEGE" NOT NULL ENABLE);
  ALTER TABLE "BPMMGR"."UREF_PRIVILEGES" MODIFY ("DOMAIN" NOT NULL ENABLE);
  ALTER TABLE "BPMMGR"."UREF_PRIVILEGES" MODIFY ("UREF_TYPE" NOT NULL ENABLE);
  ALTER TABLE "BPMMGR"."UREF_PRIVILEGES" MODIFY ("UREF" NOT NULL ENABLE);
