--------------------------------------------------------
--  Constraints for Table UREFS
--------------------------------------------------------

  ALTER TABLE "BPMMGR"."UREFS" ADD CONSTRAINT "UREFS_MAND_ARC_CK2" CHECK (
  DECODE(GENERIC_DESCRIPTION, NULL, 0, 1) 
+ DECODE(ADVICE_ADVISORY_BODIES, NULL, 0, 1) 
+ DECODE(ADVICE_ADVISORY_COMMUNITY_ID, NULL, 0, 1) 
+ DECODE(ADVISORY_BODY_ID, NULL, 0, 1) 
+ DECODE(ADVISORY_COMMUNITY_ID, NULL, 0, 1) 
+ DECODE(APP_ERROR_ID, NULL, 0, 1) 
+ DECODE(BUSINESS_ACTIVITY_ID, NULL, 0, 1) 
+ DECODE(BUSINESS_STAGES_ID, NULL, 0, 1) 
+ DECODE(BUSINESS_UNAVAIL_ID, NULL, 0, 1) 
+ DECODE(CA_ID, NULL, 0, 1) 
+ DECODE(CLAUSE_TYPE_ID, NULL, 0, 1) 
+ DECODE(COUNTRY_ID, NULL, 0, 1) 
+ DECODE(COUNTRY_SET_ID, NULL, 0, 1) 
+ DECODE(DENIAL_ID, NULL, 0, 1) 
+ DECODE(DOCUMENT_SETS_ID, NULL, 0, 1) 
+ DECODE(ELA_GROUP_ID, NULL, 0, 1) 
+ DECODE(ELA_ID, NULL, 0, 1) 
+ DECODE(ELA_TEMPLATES_ID, NULL, 0, 1) 
+ DECODE(ELD_ID, NULL, 0, 1) 
+ DECODE(EXPORT_LICENCE_ID, NULL, 0, 1) 
+ DECODE(FILE_FOLDER_ID, NULL, 0, 1) 
+ DECODE(FILE_FOLDER_TARGET_ID, NULL, 0, 1) 
+ DECODE(FOX_SERVICE_ID, NULL, 0, 1) 
+ DECODE(INTENTION_ID, NULL, 0, 1) 
+ DECODE(MAPSETS_ID, NULL, 0, 1) 
+ DECODE(MISC_DOMAIN_ID, NULL, 0, 1) 
+ DECODE(NOTES_ID, NULL, 0, 1) 
+ DECODE(NOTE_UREFS_ID, NULL, 0, 1) 
+ DECODE(NOTIFICATIONS_ID, NULL, 0, 1) 
+ DECODE(NOTIFICATION_SET_ID, NULL, 0, 1) 
+ DECODE(N_ID, NULL, 0, 1) 
+ DECODE(ORGANISATION_UNITS_ID, NULL, 0, 1) 
+ DECODE(PEA_ID, NULL, 0, 1) 
+ DECODE(PORTAL_FOLDERS_ID, NULL, 0, 1) 
+ DECODE(PORTAL_FOLDER_TYPE, NULL, 0, 1) 
+ DECODE(PORTAL_PRIVILEGES_ID, NULL, 0, 1) 
+ DECODE(PORTAL_SCHEDULE_EVENT_ID, NULL, 0, 1) 
+ DECODE(PORTAL_SCHEDULE_INSTANCE_ID, NULL, 0, 1) 
+ DECODE(PORTAL_SCHEDULE_TYPE_MNEM, NULL, 0, 1) 
+ DECODE(REPORT_CAT_MNEM, NULL, 0, 1) 
+ DECODE(REPORT_DEF_ID, NULL, 0, 1) 
+ DECODE(RESOURCES_ID, NULL, 0, 1) 
+ DECODE(RESOURCE_PEOPLE_ID, NULL, 0, 1) 
+ DECODE(RESOURCE_ROLES_ID, NULL, 0, 1) 
+ DECODE(REVIEW_ADVISOR_ID, NULL, 0, 1) 
+ DECODE(REVIEW_BATCH_ID, NULL, 0, 1) 
+ DECODE(RPT_RUN_ID, NULL, 0, 1) 
+ DECODE(SCAN_PREFERENCE_TEMPLATES_ID, NULL, 0, 1) 
+ DECODE(SITE_ID, NULL, 0, 1) 
+ DECODE(SPIRE_APP_ID, NULL, 0, 1) 
+ DECODE(SPIRE_AP_DTL_ID, NULL, 0, 1) 
+ DECODE(SPIRE_AP_REC_ID, NULL, 0, 1) 
+ DECODE(SURVEY_INSTANCES_ID, NULL, 0, 1) 
+ DECODE(SURVEY_TYPES_ID, NULL, 0, 1) 
+ DECODE(SYSTEM_DOMAIN_ID, NULL, 0, 1) 
+ DECODE(TEMPLATE_CLAUSE_ID, NULL, 0, 1) 
+ DECODE(TEMPLATE_CLAUSE_SETS_ID, NULL, 0, 1) 
+ DECODE(VISIT_ID, NULL, 0, 1) 
+ DECODE(WEB_ORGANISATION_ID, NULL, 0, 1) 
+ DECODE(WEB_USER_ACCOUNT_ID, NULL, 0, 1) 
+ DECODE(COUNTRY_GROUP_ID, NULL, 0, 0.5) 
+ DECODE(COUNTRY_GROUP_SET_ID, NULL, 0, 0.5) 
= 1
 OR uref_type IN ('SH') /* This list of uref_types are excluded since the columns referenced in the uref type record don't exist in the urefs table */
) ENABLE;
  ALTER TABLE "BPMMGR"."UREFS" ADD CONSTRAINT "UREFS_NOVATIONS_UK" UNIQUE ("N_ID")
  USING INDEX  ENABLE;
  ALTER TABLE "BPMMGR"."UREFS" ADD CONSTRAINT "UREFS_EXP_LICENCE_DETAILS_UK" UNIQUE ("ELD_ID")
  USING INDEX  ENABLE;
  ALTER TABLE "BPMMGR"."UREFS" ADD CONSTRAINT "UREFS_APPLICATION_ERRORS_UK" UNIQUE ("APP_ERROR_ID")
  USING INDEX  ENABLE;
  ALTER TABLE "BPMMGR"."UREFS" ADD CONSTRAINT "UREFS_COMPOSIT_OF_REF_CK1" CHECK (
DECODE(UREF_TYPE, 'GEN', UREF_TYPE, UREF) =
 ADVICE_ADVISORY_BODIES
 ||ADVICE_ADVISORY_COMMUNITY_ID
 ||ADVISORY_BODY_ID
 ||ADVISORY_COMMUNITY_ID
 ||APP_ERROR_ID
 ||BUSINESS_ACTIVITY_ID
 ||BUSINESS_STAGES_ID
 ||BUSINESS_UNAVAIL_ID
 ||CA_ID
 ||CLAUSE_TYPE_ID
 ||COUNTRY_ID
 ||COUNTRY_SET_ID
 ||DENIAL_ID
 ||DOCUMENT_SETS_ID
 ||ELA_GROUP_ID
 ||ELA_ID
 ||ELA_TEMPLATES_ID
 ||ELD_ID
 ||EXPORT_LICENCE_ID
 ||FILE_FOLDER_ID
 ||FILE_FOLDER_TARGET_ID
 ||FOX_SERVICE_ID
 ||INTENTION_ID
 ||MAPSETS_ID
 ||MISC_DOMAIN_ID
 ||NOTES_ID
 ||NOTE_UREFS_ID
 ||NOTIFICATIONS_ID
 ||NOTIFICATION_SET_ID
 ||N_ID
 ||ORGANISATION_UNITS_ID
 ||PEA_ID
 ||PORTAL_FOLDERS_ID
 ||PORTAL_FOLDER_TYPE
 ||PORTAL_PRIVILEGES_ID
 ||PORTAL_SCHEDULE_EVENT_ID
 ||PORTAL_SCHEDULE_INSTANCE_ID
 ||PORTAL_SCHEDULE_TYPE_MNEM
 ||REPORT_CAT_MNEM
 ||REPORT_DEF_ID
 ||RESOURCES_ID
 ||RESOURCE_PEOPLE_ID
 ||RESOURCE_ROLES_ID
 ||REVIEW_ADVISOR_ID
 ||REVIEW_BATCH_ID
 ||RPT_RUN_ID
 ||SCAN_PREFERENCE_TEMPLATES_ID
 ||SITE_ID
 ||SPIRE_APP_ID
 ||SPIRE_AP_DTL_ID
 ||SPIRE_AP_REC_ID
 ||SURVEY_INSTANCES_ID
 ||SURVEY_TYPES_ID
 ||SYSTEM_DOMAIN_ID
 ||TEMPLATE_CLAUSE_ID
 ||TEMPLATE_CLAUSE_SETS_ID
 ||VISIT_ID
 ||WEB_ORGANISATION_ID
 ||WEB_USER_ACCOUNT_ID
 || CASE WHEN COUNTRY_GROUP_ID IS NOT NULL THEN COUNTRY_GROUP_ID||'++'||COUNTRY_GROUP_SET_ID END
 ||UREF_TYPE 
 OR uref_type IN ('SH') /* This list of uref_types are excluded since the columns referenced in the uref type record don't exist in the urefs table */
) ENABLE;
  ALTER TABLE "BPMMGR"."UREFS" ADD CONSTRAINT "UREFS_COMPLIANCE_ACTS_UK" UNIQUE ("CA_ID")
  USING INDEX  ENABLE;
  ALTER TABLE "BPMMGR"."UREFS" ADD CONSTRAINT "UREFS_SURVEY_INSTANCES_UK" UNIQUE ("SURVEY_INSTANCES_ID")
  USING INDEX  ENABLE;
  ALTER TABLE "BPMMGR"."UREFS" ADD CONSTRAINT "UREFS_FOX_SERVICES_UK" UNIQUE ("FOX_SERVICE_ID")
  USING INDEX  ENABLE;
  ALTER TABLE "BPMMGR"."UREFS" ADD CONSTRAINT "UREFS_MAPSETS_UK" UNIQUE ("MAPSETS_ID")
  USING INDEX  ENABLE;
  ALTER TABLE "BPMMGR"."UREFS" ADD CONSTRAINT "UREFS_PORTAL_FOLDER_TYPES_UK" UNIQUE ("PORTAL_FOLDER_TYPE")
  USING INDEX  ENABLE;
  ALTER TABLE "BPMMGR"."UREFS" ADD CONSTRAINT "PK_UREFS" PRIMARY KEY ("UREF")
  USING INDEX  ENABLE;
  ALTER TABLE "BPMMGR"."UREFS" MODIFY ("UREF_TYPE" NOT NULL ENABLE);
  ALTER TABLE "BPMMGR"."UREFS" MODIFY ("UREF" NOT NULL ENABLE);
  ALTER TABLE "BPMMGR"."UREFS" ADD CONSTRAINT "UREFS_WEB_USER_ACCOUNTS_UK" UNIQUE ("WEB_USER_ACCOUNT_ID")
  USING INDEX  ENABLE;
  ALTER TABLE "BPMMGR"."UREFS" ADD CONSTRAINT "UREFS_SPIRE_APP_DETAIL_UK" UNIQUE ("SPIRE_AP_DTL_ID")
  USING INDEX  ENABLE;
  ALTER TABLE "BPMMGR"."UREFS" ADD CONSTRAINT "UREFS_RESOURCES_UK" UNIQUE ("RESOURCES_ID")
  USING INDEX  ENABLE;
  ALTER TABLE "BPMMGR"."UREFS" ADD CONSTRAINT "UREFS_WEB_ROLES_UK" UNIQUE ("PORTAL_PRIVILEGES_ID")
  USING INDEX  ENABLE;
  ALTER TABLE "BPMMGR"."UREFS" ADD CONSTRAINT "UREFS_ORG_UNITS_UK" UNIQUE ("ORGANISATION_UNITS_ID")
  USING INDEX  ENABLE;
  ALTER TABLE "BPMMGR"."UREFS" ADD CONSTRAINT "UREFS_NOTE_UREFS_UK" UNIQUE ("NOTE_UREFS_ID")
  USING INDEX  ENABLE;
  ALTER TABLE "BPMMGR"."UREFS" ADD CONSTRAINT "UREFS_NOTES_UK" UNIQUE ("NOTES_ID")
  USING INDEX  ENABLE;
  ALTER TABLE "BPMMGR"."UREFS" ADD CONSTRAINT "UREFS_NOTIFICATION_SETS_UK" UNIQUE ("NOTIFICATION_SET_ID")
  USING INDEX  ENABLE;
  ALTER TABLE "BPMMGR"."UREFS" ADD CONSTRAINT "UREFS_NOTIFICATIONS_UK" UNIQUE ("NOTIFICATIONS_ID")
  USING INDEX  ENABLE;
  ALTER TABLE "BPMMGR"."UREFS" ADD CONSTRAINT "UREFS_FILE_FOLDERS_UK" UNIQUE ("FILE_FOLDER_ID")
  USING INDEX  ENABLE;
  ALTER TABLE "BPMMGR"."UREFS" ADD CONSTRAINT "UREFS_FILE_FOLDER_TARGETS_UK" UNIQUE ("FILE_FOLDER_TARGET_ID")
  USING INDEX  ENABLE;
  ALTER TABLE "BPMMGR"."UREFS" ADD CONSTRAINT "UREFS_ELA_TEMPLATES_UK" UNIQUE ("ELA_TEMPLATES_ID")
  USING INDEX  ENABLE;
  ALTER TABLE "BPMMGR"."UREFS" ADD CONSTRAINT "UREFS_EXPORT_LICENCE_APPS_UK" UNIQUE ("ELA_ID")
  USING INDEX  ENABLE;
  ALTER TABLE "BPMMGR"."UREFS" ADD CONSTRAINT "UREFS_DOCUMENT_SETS_UK" UNIQUE ("DOCUMENT_SETS_ID")
  USING INDEX  ENABLE;
  ALTER TABLE "BPMMGR"."UREFS" ADD CONSTRAINT "UREFS_COUNTRIES_UK" UNIQUE ("COUNTRY_ID")
  USING INDEX  ENABLE;
  ALTER TABLE "BPMMGR"."UREFS" ADD CONSTRAINT "UREFS_BUSINESS_STAGES_UK" UNIQUE ("BUSINESS_STAGES_ID")
  USING INDEX  ENABLE;
  ALTER TABLE "BPMMGR"."UREFS" ADD CONSTRAINT "UREFS_BUS_ACTIVITIES_UK" UNIQUE ("BUSINESS_ACTIVITY_ID")
  USING INDEX  ENABLE;
  ALTER TABLE "BPMMGR"."UREFS" ADD CONSTRAINT "UREFS_PV_EX_APPLICATIONS_UK" UNIQUE ("PEA_ID")
  USING INDEX  ENABLE;
  ALTER TABLE "BPMMGR"."UREFS" ADD CONSTRAINT "UREFS_REPORT_CATEGORIES_UK" UNIQUE ("REPORT_CAT_MNEM")
  USING INDEX  ENABLE;
  ALTER TABLE "BPMMGR"."UREFS" ADD CONSTRAINT "UREFS_BUSINESS_UNAVAIL_UK" UNIQUE ("BUSINESS_UNAVAIL_ID")
  USING INDEX  ENABLE;
  ALTER TABLE "BPMMGR"."UREFS" ADD CONSTRAINT "UREFS_MISC_DOMAINS_UK" UNIQUE ("MISC_DOMAIN_ID")
  USING INDEX  ENABLE;
  ALTER TABLE "BPMMGR"."UREFS" ADD CONSTRAINT "UREFS_SURVEY_TYPES_UK" UNIQUE ("SURVEY_TYPES_ID")
  USING INDEX  ENABLE;
  ALTER TABLE "BPMMGR"."UREFS" ADD CONSTRAINT "UREFS_EXPORT_LICENCES_UK" UNIQUE ("EXPORT_LICENCE_ID")
  USING INDEX  ENABLE;
  ALTER TABLE "BPMMGR"."UREFS" ADD CONSTRAINT "UREFS_DENIALS_UK" UNIQUE ("DENIAL_ID")
  USING INDEX  ENABLE;
  ALTER TABLE "BPMMGR"."UREFS" ADD CONSTRAINT "UREFS_REPORT_DEFINITIONS_UK" UNIQUE ("REPORT_DEF_ID")
  USING INDEX  ENABLE;
  ALTER TABLE "BPMMGR"."UREFS" ADD CONSTRAINT "UREFS_REPORT_RUNS_UK" UNIQUE ("RPT_RUN_ID")
  USING INDEX  ENABLE;
  ALTER TABLE "BPMMGR"."UREFS" ADD CONSTRAINT "UREFS_CLAUSE_TYPES_UK" UNIQUE ("CLAUSE_TYPE_ID")
  USING INDEX  ENABLE;
  ALTER TABLE "BPMMGR"."UREFS" ADD CONSTRAINT "UREFS_COUNTRY_SETS_UK" UNIQUE ("COUNTRY_SET_ID")
  USING INDEX  ENABLE;
  ALTER TABLE "BPMMGR"."UREFS" ADD CONSTRAINT "UREFS_COUNTRY_GROUPS_UK" UNIQUE ("COUNTRY_GROUP_ID", "COUNTRY_GROUP_SET_ID")
  USING INDEX  ENABLE;
  ALTER TABLE "BPMMGR"."UREFS" ADD CONSTRAINT "UREFS_ELA_GROUPS_UK" UNIQUE ("ELA_GROUP_ID")
  USING INDEX  ENABLE;
  ALTER TABLE "BPMMGR"."UREFS" ADD CONSTRAINT "UREFS_PS_TYPES_UK" UNIQUE ("PORTAL_SCHEDULE_TYPE_MNEM")
  USING INDEX  ENABLE;
  ALTER TABLE "BPMMGR"."UREFS" ADD CONSTRAINT "UREFS_SPIRE_APPLICATIONS_UK" UNIQUE ("SPIRE_APP_ID")
  USING INDEX  ENABLE;
  ALTER TABLE "BPMMGR"."UREFS" ADD CONSTRAINT "UREFS_SPIRE_APPLICANTS_UK" UNIQUE ("SPIRE_AP_REC_ID")
  USING INDEX  ENABLE;
  ALTER TABLE "BPMMGR"."UREFS" ADD CONSTRAINT "UREFS_ADVISORY_BODY_UK" UNIQUE ("ADVISORY_BODY_ID")
  USING INDEX  ENABLE;
  ALTER TABLE "BPMMGR"."UREFS" ADD CONSTRAINT "UREFS_REVIEW_BATCH_UK" UNIQUE ("REVIEW_BATCH_ID")
  USING INDEX  ENABLE;
  ALTER TABLE "BPMMGR"."UREFS" ADD CONSTRAINT "UREFS_PORTAL_FOLDERS_UK" UNIQUE ("PORTAL_FOLDERS_ID")
  USING INDEX  ENABLE;
  ALTER TABLE "BPMMGR"."UREFS" ADD CONSTRAINT "UREFS_TEMPLATE_CLAUSES_UK" UNIQUE ("TEMPLATE_CLAUSE_ID")
  USING INDEX  ENABLE;
  ALTER TABLE "BPMMGR"."UREFS" ADD CONSTRAINT "UREFS_SCAN_PREF_TEMPS_UK" UNIQUE ("SCAN_PREFERENCE_TEMPLATES_ID")
  USING INDEX  ENABLE;
  ALTER TABLE "BPMMGR"."UREFS" ADD CONSTRAINT "UREFS_SITES_UK" UNIQUE ("SITE_ID")
  USING INDEX  ENABLE;
  ALTER TABLE "BPMMGR"."UREFS" ADD CONSTRAINT "UREFS_PS_EVENTS_UK" UNIQUE ("PORTAL_SCHEDULE_EVENT_ID")
  USING INDEX  ENABLE;
  ALTER TABLE "BPMMGR"."UREFS" ADD CONSTRAINT "UREFS_RES_ROLES_UK" UNIQUE ("RESOURCE_ROLES_ID")
  USING INDEX  ENABLE;
  ALTER TABLE "BPMMGR"."UREFS" ADD CONSTRAINT "UREFS_REVIEW_ADVISOR_UK" UNIQUE ("REVIEW_ADVISOR_ID")
  USING INDEX  ENABLE;
  ALTER TABLE "BPMMGR"."UREFS" ADD CONSTRAINT "UREFS_RESOURCE_PEOPLE_UK" UNIQUE ("RESOURCE_PEOPLE_ID")
  USING INDEX  ENABLE;
  ALTER TABLE "BPMMGR"."UREFS" ADD CONSTRAINT "UREFS_ADVICE_ADVISORY_BODI_UK" UNIQUE ("ADVICE_ADVISORY_BODIES")
  USING INDEX  ENABLE;
  ALTER TABLE "BPMMGR"."UREFS" ADD CONSTRAINT "UREFS_TEMPLATE_CLAUSE_SETS_UK" UNIQUE ("TEMPLATE_CLAUSE_SETS_ID")
  USING INDEX  ENABLE;
  ALTER TABLE "BPMMGR"."UREFS" ADD CONSTRAINT "UREFS_PS_INSTANCES_UK" UNIQUE ("PORTAL_SCHEDULE_INSTANCE_ID")
  USING INDEX  ENABLE;
  ALTER TABLE "BPMMGR"."UREFS" ADD CONSTRAINT "UREFS_ADVISORY_COMMUNITY_UK" UNIQUE ("ADVISORY_COMMUNITY_ID")
  USING INDEX  ENABLE;
  ALTER TABLE "BPMMGR"."UREFS" ADD CONSTRAINT "UREFS_ADVICE_ADVISORY_COMM_UK" UNIQUE ("ADVICE_ADVISORY_COMMUNITY_ID")
  USING INDEX  ENABLE;
  ALTER TABLE "BPMMGR"."UREFS" ADD CONSTRAINT "UREFS_SYSTEM_DOMAINS_UK" UNIQUE ("SYSTEM_DOMAIN_ID")
  USING INDEX  ENABLE;
  ALTER TABLE "BPMMGR"."UREFS" ADD CONSTRAINT "UREFS_COMPLIANCE_VISITS_UK" UNIQUE ("VISIT_ID")
  USING INDEX  ENABLE;
  ALTER TABLE "BPMMGR"."UREFS" ADD CONSTRAINT "UREFS_INTENTION_UK" UNIQUE ("INTENTION_ID")
  USING INDEX  ENABLE;
  ALTER TABLE "BPMMGR"."UREFS" ADD CONSTRAINT "UREFS_WEB_ORGANISATIONS_UK" UNIQUE ("WEB_ORGANISATION_ID")
  USING INDEX  ENABLE;
