--------------------------------------------------------
--  Constraints for Table UREF_TYPES
--------------------------------------------------------

  ALTER TABLE "BPMMGR"."UREF_TYPES" MODIFY ("EXPANDED_TYPE" NOT NULL ENABLE);
  ALTER TABLE "BPMMGR"."UREF_TYPES" MODIFY ("DESCRIPTION" NOT NULL ENABLE);
  ALTER TABLE "BPMMGR"."UREF_TYPES" MODIFY ("UREF_FK1_COLUMN_NAME" NOT NULL ENABLE);
  ALTER TABLE "BPMMGR"."UREF_TYPES" MODIFY ("OBJECT_PK_1_COLUMN_NAME" NOT NULL ENABLE);
  ALTER TABLE "BPMMGR"."UREF_TYPES" MODIFY ("OBJECT_NAME" NOT NULL ENABLE);
  ALTER TABLE "BPMMGR"."UREF_TYPES" MODIFY ("OBJECT_OWNER" NOT NULL ENABLE);
  ALTER TABLE "BPMMGR"."UREF_TYPES" MODIFY ("UREF_TYPE" NOT NULL ENABLE);
  ALTER TABLE "BPMMGR"."UREF_TYPES" ADD CONSTRAINT "PK_UREF_TYPES" PRIMARY KEY ("UREF_TYPE")
  USING INDEX  ENABLE;
  ALTER TABLE "BPMMGR"."UREF_TYPES" ADD CONSTRAINT "UREF_TYPES_CK1" CHECK (strategy IN ('STANDARD', 'JIT')) ENABLE;
  ALTER TABLE "BPMMGR"."UREF_TYPES" MODIFY ("STRATEGY" NOT NULL ENABLE);
