--------------------------------------------------------
--  Constraints for Table USAGE_CONTROL
--------------------------------------------------------

  ALTER TABLE "HMRCMGR"."USAGE_CONTROL" MODIFY ("LICENCE_REF" NOT NULL ENABLE);
  ALTER TABLE "HMRCMGR"."USAGE_CONTROL" MODIFY ("TRANSMISSION_ID" NOT NULL ENABLE);
  ALTER TABLE "HMRCMGR"."USAGE_CONTROL" ADD CONSTRAINT "USAGE_CONTROL_CK2" CHECK (system_msg IS NULL OR (system_msg IS NOT NULL AND status IN ('ERROR', 'WARNING'))) ENABLE;
  ALTER TABLE "HMRCMGR"."USAGE_CONTROL" ADD CONSTRAINT "USAGE_CONTROL_CK1" CHECK (status IN ('ERROR', 'COMPLETE', 'WARNING')) ENABLE;
  ALTER TABLE "HMRCMGR"."USAGE_CONTROL" ADD CONSTRAINT "USAGE_CONTROL_UK1" UNIQUE ("TRANSMISSION_ID", "LICENCE_REF")
  USING INDEX  ENABLE;
  ALTER TABLE "HMRCMGR"."USAGE_CONTROL" ADD CONSTRAINT "USAGE_CONTROL_PK1" PRIMARY KEY ("ID")
  USING INDEX  ENABLE;
  ALTER TABLE "HMRCMGR"."USAGE_CONTROL" MODIFY ("CREATED_DATETIME" NOT NULL ENABLE);
  ALTER TABLE "HMRCMGR"."USAGE_CONTROL" MODIFY ("ELD_ID" NOT NULL ENABLE);
