--------------------------------------------------------
--  Constraints for Table USER_DOM_CACHE
--------------------------------------------------------

  ALTER TABLE "SECUREMGR"."USER_DOM_CACHE" ADD CONSTRAINT "USER_DOM_CACHE_CK1" CHECK (dirty_flag IS NULL OR dirty_flag = 'Y') ENABLE;
  ALTER TABLE "SECUREMGR"."USER_DOM_CACHE" ADD CONSTRAINT "USER_DOM_CACHE_PK" PRIMARY KEY ("WUS_ID")
  USING INDEX  ENABLE;
  ALTER TABLE "SECUREMGR"."USER_DOM_CACHE" MODIFY ("CACHED_DOM" NOT NULL ENABLE);
  ALTER TABLE "SECUREMGR"."USER_DOM_CACHE" MODIFY ("LAST_GENERATED_DATETIME" NOT NULL ENABLE);
  ALTER TABLE "SECUREMGR"."USER_DOM_CACHE" MODIFY ("CHANGE_NUMBER" NOT NULL ENABLE);
  ALTER TABLE "SECUREMGR"."USER_DOM_CACHE" MODIFY ("WUA_ID" NOT NULL ENABLE);
  ALTER TABLE "SECUREMGR"."USER_DOM_CACHE" MODIFY ("WUS_ID" NOT NULL ENABLE);
