--------------------------------------------------------
--  Constraints for Table WEB_USER_ROLES
--------------------------------------------------------

  ALTER TABLE "SAVEMGR"."WEB_USER_ROLES" MODIFY ("GRANT_OPTION" NOT NULL ENABLE);
  ALTER TABLE "SAVEMGR"."WEB_USER_ROLES" MODIFY ("GRANTED" NOT NULL ENABLE);
  ALTER TABLE "SAVEMGR"."WEB_USER_ROLES" MODIFY ("LAST_DML_BY" NOT NULL ENABLE);
  ALTER TABLE "SAVEMGR"."WEB_USER_ROLES" MODIFY ("LAST_DML_DATE" NOT NULL ENABLE);
  ALTER TABLE "SAVEMGR"."WEB_USER_ROLES" MODIFY ("EFFECTIVE_FROM_DATE" NOT NULL ENABLE);
  ALTER TABLE "SAVEMGR"."WEB_USER_ROLES" MODIFY ("ROLE_ID" NOT NULL ENABLE);
  ALTER TABLE "SAVEMGR"."WEB_USER_ROLES" MODIFY ("WUA_ID" NOT NULL ENABLE);
