--------------------------------------------------------
--  Constraints for Table WEB_ROLES
--------------------------------------------------------

  ALTER TABLE "PORTALMGR"."WEB_ROLES" ADD CONSTRAINT "WRL_UK" UNIQUE ("NAME")
  USING INDEX  ENABLE;
  ALTER TABLE "PORTALMGR"."WEB_ROLES" ADD CONSTRAINT "WRL_PK" PRIMARY KEY ("ID")
  USING INDEX  ENABLE;
  ALTER TABLE "PORTALMGR"."WEB_ROLES" MODIFY ("LAST_DML_BY" NOT NULL ENABLE);
  ALTER TABLE "PORTALMGR"."WEB_ROLES" MODIFY ("LAST_DML_DATE" NOT NULL ENABLE);
  ALTER TABLE "PORTALMGR"."WEB_ROLES" MODIFY ("DESCRIPTION" NOT NULL ENABLE);
  ALTER TABLE "PORTALMGR"."WEB_ROLES" MODIFY ("NAME" NOT NULL ENABLE);
  ALTER TABLE "PORTALMGR"."WEB_ROLES" MODIFY ("APP_ID" NOT NULL ENABLE);
  ALTER TABLE "PORTALMGR"."WEB_ROLES" MODIFY ("ID" NOT NULL ENABLE);
