--------------------------------------------------------
--  Constraints for Table WEB_ORGANISATIONS
--------------------------------------------------------

  ALTER TABLE "PORTALMGR"."WEB_ORGANISATIONS" ADD CONSTRAINT "WO_PK" PRIMARY KEY ("ID")
  USING INDEX  ENABLE;
  ALTER TABLE "PORTALMGR"."WEB_ORGANISATIONS" MODIFY ("ORG_GRP_TYPE" NOT NULL ENABLE);
  ALTER TABLE "PORTALMGR"."WEB_ORGANISATIONS" MODIFY ("LAST_DML_BY" NOT NULL ENABLE);
  ALTER TABLE "PORTALMGR"."WEB_ORGANISATIONS" MODIFY ("LAST_DML_DATE" NOT NULL ENABLE);
  ALTER TABLE "PORTALMGR"."WEB_ORGANISATIONS" MODIFY ("NAME" NOT NULL ENABLE);
  ALTER TABLE "PORTALMGR"."WEB_ORGANISATIONS" MODIFY ("SHORT_NAME" NOT NULL ENABLE);
  ALTER TABLE "PORTALMGR"."WEB_ORGANISATIONS" MODIFY ("WOT_ID" NOT NULL ENABLE);
  ALTER TABLE "PORTALMGR"."WEB_ORGANISATIONS" MODIFY ("ID" NOT NULL ENABLE);
