--------------------------------------------------------
--  Constraints for Table WEB_USER_ACCOUNT_HISTORIES
--------------------------------------------------------

  ALTER TABLE "SECUREMGR"."WEB_USER_ACCOUNT_HISTORIES" MODIFY ("ENCRYPT_SCHEME" NOT NULL ENABLE);
  ALTER TABLE "SECUREMGR"."WEB_USER_ACCOUNT_HISTORIES" ADD CONSTRAINT "WUA_HISTORIES_CK5" CHECK (/* Valid account status values */ ACCOUNT_STATUS IN ('ACTIVE', 'BLOCKED', 'CANCELLED', 'NEW', 'SUSPENDED', 'INREVIEW')) ENABLE;
  ALTER TABLE "SECUREMGR"."WEB_USER_ACCOUNT_HISTORIES" ADD CONSTRAINT "WUAH_PK" PRIMARY KEY ("WUAH_ID")
  USING INDEX  ENABLE;
  ALTER TABLE "SECUREMGR"."WEB_USER_ACCOUNT_HISTORIES" ADD CONSTRAINT "WUA_HISTORIES_CK9" CHECK (/* Value Restriction */ EMAIL_AS_LOGIN_ID_FLAG IN ('Y', 'N')) ENABLE;
  ALTER TABLE "SECUREMGR"."WEB_USER_ACCOUNT_HISTORIES" ADD CONSTRAINT "WUA_HISTORIES_CK8" CHECK (/* Values Restriction */ ACCOUNT_APPROVED IN ('Y', 'N')) ENABLE;
  ALTER TABLE "SECUREMGR"."WEB_USER_ACCOUNT_HISTORIES" ADD CONSTRAINT "WUA_HISTORIES_CK7" CHECK (password_disposition IN ('ACTIVATED' , 'FULL', 'NEW', 'OFFER' , 'TEMPORARY', 'SSO_BOOTSTRAP')) ENABLE;
  ALTER TABLE "SECUREMGR"."WEB_USER_ACCOUNT_HISTORIES" ADD CONSTRAINT "WUA_HISTORIES_CK6" CHECK (NOT (EMAIL_AS_LOGIN_ID_FLAG = 'Y' AND RESOURCE_PERSON_ID IS NULL)) ENABLE;
  ALTER TABLE "SECUREMGR"."WEB_USER_ACCOUNT_HISTORIES" ADD CONSTRAINT "WUA_HISTORIES_CK4" CHECK (/* Status_control and end_date */ (END_DATE IS NULL AND NVL(STATUS_CONTROL,'.') = 'C') OR (END_DATE IS NOT NULL AND NVL(STATUS_CONTROL,'.') != 'C')) ENABLE;
  ALTER TABLE "SECUREMGR"."WEB_USER_ACCOUNT_HISTORIES" ADD CONSTRAINT "WUA_HISTORIES_CK3" CHECK (/* Valid status to control mappings */ STATUS||'='||STATUS_CONTROL IN ('CURRENT=C','ARCHIVED=')) ENABLE;
  ALTER TABLE "SECUREMGR"."WEB_USER_ACCOUNT_HISTORIES" ADD CONSTRAINT "WUA_HISTORIES_CK2" CHECK (/* Valid status_control values */ STATUS_CONTROL IS NULL OR STATUS_CONTROL IN ('C')) ENABLE;
  ALTER TABLE "SECUREMGR"."WEB_USER_ACCOUNT_HISTORIES" ADD CONSTRAINT "WUA_HISTORIES_CK10" CHECK (/* Value Restriction */ RESOURCE_PERSON_PRIMARY_FLAG IN ('Y', 'N')) ENABLE;
  ALTER TABLE "SECUREMGR"."WEB_USER_ACCOUNT_HISTORIES" ADD CONSTRAINT "WUA_HISTORIES_CK1" CHECK (/* Valid status values */ STATUS IN ('CURRENT','ARCHIVED')) ENABLE;
  ALTER TABLE "SECUREMGR"."WEB_USER_ACCOUNT_HISTORIES" MODIFY ("ACCOUNT_APPROVED" NOT NULL ENABLE);
  ALTER TABLE "SECUREMGR"."WEB_USER_ACCOUNT_HISTORIES" MODIFY ("START_DATE" NOT NULL ENABLE);
  ALTER TABLE "SECUREMGR"."WEB_USER_ACCOUNT_HISTORIES" MODIFY ("EMAIL_AS_LOGIN_ID_FLAG" NOT NULL ENABLE);
  ALTER TABLE "SECUREMGR"."WEB_USER_ACCOUNT_HISTORIES" MODIFY ("RESOURCE_PERSON_PRIMARY_FLAG" NOT NULL ENABLE);
  ALTER TABLE "SECUREMGR"."WEB_USER_ACCOUNT_HISTORIES" MODIFY ("PASSWORD_DISPOSITION" NOT NULL ENABLE);
  ALTER TABLE "SECUREMGR"."WEB_USER_ACCOUNT_HISTORIES" MODIFY ("ACCOUNT_TYPE" NOT NULL ENABLE);
  ALTER TABLE "SECUREMGR"."WEB_USER_ACCOUNT_HISTORIES" MODIFY ("LOGIN_TRY_COUNT" NOT NULL ENABLE);
  ALTER TABLE "SECUREMGR"."WEB_USER_ACCOUNT_HISTORIES" MODIFY ("LOGIN_ID" NOT NULL ENABLE);
  ALTER TABLE "SECUREMGR"."WEB_USER_ACCOUNT_HISTORIES" MODIFY ("STATUS" NOT NULL ENABLE);
  ALTER TABLE "SECUREMGR"."WEB_USER_ACCOUNT_HISTORIES" MODIFY ("WUA_ID" NOT NULL ENABLE);
  ALTER TABLE "SECUREMGR"."WEB_USER_ACCOUNT_HISTORIES" MODIFY ("WUAH_ID" NOT NULL ENABLE);
