--------------------------------------------------------
--  Constraints for Table WEB_USER_SESSIONS
--------------------------------------------------------

  ALTER TABLE "SECUREMGR"."WEB_USER_SESSIONS" MODIFY ("LAST_ACCESS_DATE" NOT NULL ENABLE);
  ALTER TABLE "SECUREMGR"."WEB_USER_SESSIONS" MODIFY ("LOGIN_DATE" NOT NULL ENABLE);
  ALTER TABLE "SECUREMGR"."WEB_USER_SESSIONS" MODIFY ("WUA_ID" NOT NULL ENABLE);
  ALTER TABLE "SECUREMGR"."WEB_USER_SESSIONS" MODIFY ("WUS_ID" NOT NULL ENABLE);
  ALTER TABLE "SECUREMGR"."WEB_USER_SESSIONS" ADD CONSTRAINT "WEB_USER_SESSIONS_PK" PRIMARY KEY ("WUS_ID")
  USING INDEX  ENABLE;
