--------------------------------------------------------
--  Constraints for Table WEB_USER_LOGIN_CHECKS
--------------------------------------------------------

  ALTER TABLE "SECUREMGR"."WEB_USER_LOGIN_CHECKS" ADD CONSTRAINT "WEB_USER_LOGIN_CHECKS_PK" PRIMARY KEY ("ID")
  USING INDEX  ENABLE;
  ALTER TABLE "SECUREMGR"."WEB_USER_LOGIN_CHECKS" MODIFY ("LOGIN_TRY_COUNT" NOT NULL ENABLE);
  ALTER TABLE "SECUREMGR"."WEB_USER_LOGIN_CHECKS" MODIFY ("EXPIRY_DATETIME" NOT NULL ENABLE);
  ALTER TABLE "SECUREMGR"."WEB_USER_LOGIN_CHECKS" MODIFY ("RESUME_LOGIN_DATETIME" NOT NULL ENABLE);
  ALTER TABLE "SECUREMGR"."WEB_USER_LOGIN_CHECKS" MODIFY ("HASH_CODE" NOT NULL ENABLE);
  ALTER TABLE "SECUREMGR"."WEB_USER_LOGIN_CHECKS" MODIFY ("WUA_ID" NOT NULL ENABLE);
  ALTER TABLE "SECUREMGR"."WEB_USER_LOGIN_CHECKS" MODIFY ("ID" NOT NULL ENABLE);
