--------------------------------------------------------
--  Constraints for Table WEB_ORG_TYPES
--------------------------------------------------------

  ALTER TABLE "PORTALMGR"."WEB_ORG_TYPES" ADD CONSTRAINT "WOT_PK" PRIMARY KEY ("ID")
  USING INDEX  ENABLE;
  ALTER TABLE "PORTALMGR"."WEB_ORG_TYPES" MODIFY ("LAST_DML_BY" NOT NULL ENABLE);
  ALTER TABLE "PORTALMGR"."WEB_ORG_TYPES" MODIFY ("LAST_DML_DATE" NOT NULL ENABLE);
  ALTER TABLE "PORTALMGR"."WEB_ORG_TYPES" MODIFY ("TYPE_DESCRIPTION" NOT NULL ENABLE);
  ALTER TABLE "PORTALMGR"."WEB_ORG_TYPES" MODIFY ("TYPE_NAME" NOT NULL ENABLE);
  ALTER TABLE "PORTALMGR"."WEB_ORG_TYPES" MODIFY ("ID" NOT NULL ENABLE);
