--------------------------------------------------------
--  Constraints for Table WORKBASKET_ACTIONS
--------------------------------------------------------

  ALTER TABLE "SAVEMGR"."WORKBASKET_ACTIONS" MODIFY ("START_DATETIME" NOT NULL ENABLE);
  ALTER TABLE "SAVEMGR"."WORKBASKET_ACTIONS" MODIFY ("START_OPERATION_ID" NOT NULL ENABLE);
  ALTER TABLE "SAVEMGR"."WORKBASKET_ACTIONS" MODIFY ("ID" NOT NULL ENABLE);
