--------------------------------------------------------
--  Constraints for Table WORKING_TABLE
--------------------------------------------------------

  ALTER TABLE "PORTALMGR"."WORKING_TABLE" ADD CONSTRAINT "WORKING_TABLE_PKEY" PRIMARY KEY ("SESSION_ID", "SEQUENCE_NO")
  USING INDEX  ENABLE;
  ALTER TABLE "PORTALMGR"."WORKING_TABLE" MODIFY ("LAST_DML_BY" NOT NULL ENABLE);
  ALTER TABLE "PORTALMGR"."WORKING_TABLE" MODIFY ("LAST_DML_DATE" NOT NULL ENABLE);
  ALTER TABLE "PORTALMGR"."WORKING_TABLE" MODIFY ("DATA_IN_USE" NOT NULL ENABLE);
  ALTER TABLE "PORTALMGR"."WORKING_TABLE" MODIFY ("DATA_TYPE" NOT NULL ENABLE);
  ALTER TABLE "PORTALMGR"."WORKING_TABLE" MODIFY ("STATUS" NOT NULL ENABLE);
  ALTER TABLE "PORTALMGR"."WORKING_TABLE" MODIFY ("SEQUENCE_NO" NOT NULL ENABLE);
  ALTER TABLE "PORTALMGR"."WORKING_TABLE" MODIFY ("SESSION_ID" NOT NULL ENABLE);
