--------------------------------------------------------
--  Constraints for Table WORKBASKETS
--------------------------------------------------------

  ALTER TABLE "BPMMGR"."WORKBASKETS" ADD CONSTRAINT "WORKBASKETS_UK1" UNIQUE ("SCOPE_UREF", "WB_TYPE")
  USING INDEX  ENABLE;
  ALTER TABLE "BPMMGR"."WORKBASKETS" ADD CONSTRAINT "PK_WORKBASKETS" PRIMARY KEY ("ID")
  USING INDEX  ENABLE;
  ALTER TABLE "BPMMGR"."WORKBASKETS" MODIFY ("WB_TYPE" NOT NULL ENABLE);
  ALTER TABLE "BPMMGR"."WORKBASKETS" MODIFY ("SCOPE_UREF" NOT NULL ENABLE);
  ALTER TABLE "BPMMGR"."WORKBASKETS" MODIFY ("ID" NOT NULL ENABLE);
