--------------------------------------------------------
--  Constraints for Table WORKBASKET_UREF_PREFERENCES
--------------------------------------------------------

  ALTER TABLE "BPMMGR"."WORKBASKET_UREF_PREFERENCES" ADD CONSTRAINT "WORKBASKET_UREF_PREFERENCES_PK" PRIMARY KEY ("ID")
  USING INDEX  ENABLE;
  ALTER TABLE "BPMMGR"."WORKBASKET_UREF_PREFERENCES" MODIFY ("CREATED_DATETIME" NOT NULL ENABLE);
  ALTER TABLE "BPMMGR"."WORKBASKET_UREF_PREFERENCES" MODIFY ("UREF" NOT NULL ENABLE);
  ALTER TABLE "BPMMGR"."WORKBASKET_UREF_PREFERENCES" MODIFY ("WUA_ID" NOT NULL ENABLE);
  ALTER TABLE "BPMMGR"."WORKBASKET_UREF_PREFERENCES" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "BPMMGR"."WORKBASKET_UREF_PREFERENCES" ADD CONSTRAINT "WORKBASKET_UREF_PREFS_CK1" CHECK (
  public_comment IS NULL AND public_comment_update_datetime IS NULL 
  OR public_comment IS NOT NULL AND public_comment_update_datetime IS NOT NULL
) ENABLE;
