--------------------------------------------------------
--  Constraints for Table WORKBASKET_ACTIONS_ARCHIVE
--------------------------------------------------------

  ALTER TABLE "BPMMGR"."WORKBASKET_ACTIONS_ARCHIVE" MODIFY ("START_DATETIME" NOT NULL ENABLE);
  ALTER TABLE "BPMMGR"."WORKBASKET_ACTIONS_ARCHIVE" MODIFY ("START_OPERATION_ID" NOT NULL ENABLE);
  ALTER TABLE "BPMMGR"."WORKBASKET_ACTIONS_ARCHIVE" MODIFY ("ID" NOT NULL ENABLE);
