--------------------------------------------------------
--  Constraints for Table WORKBASKET_ACTIONS
--------------------------------------------------------

  ALTER TABLE "BPMMGR"."WORKBASKET_ACTIONS" ADD CONSTRAINT "PK_WORKBASKET_ACTIONS" PRIMARY KEY ("ID")
  USING INDEX  ENABLE;
  ALTER TABLE "BPMMGR"."WORKBASKET_ACTIONS" ADD CONSTRAINT "WORKBASKET_ACTIONS_CK1" CHECK ((END_OPERATION_ID IS NOT NULL AND END_DATETIME IS NOT NULL) OR (END_OPERATION_ID IS NULL AND END_DATETIME IS NULL)) ENABLE;
  ALTER TABLE "BPMMGR"."WORKBASKET_ACTIONS" MODIFY ("START_DATETIME" NOT NULL ENABLE);
  ALTER TABLE "BPMMGR"."WORKBASKET_ACTIONS" MODIFY ("START_OPERATION_ID" NOT NULL ENABLE);
  ALTER TABLE "BPMMGR"."WORKBASKET_ACTIONS" MODIFY ("ID" NOT NULL ENABLE);
