--------------------------------------------------------
--  Constraints for Table WORKBASKET_ACTION_PREFERENCES
--------------------------------------------------------

  ALTER TABLE "SAVEMGR"."WORKBASKET_ACTION_PREFERENCES" MODIFY ("WB_TYPE" NOT NULL ENABLE);
  ALTER TABLE "SAVEMGR"."WORKBASKET_ACTION_PREFERENCES" MODIFY ("ACTION_MNEM" NOT NULL ENABLE);
  ALTER TABLE "SAVEMGR"."WORKBASKET_ACTION_PREFERENCES" MODIFY ("WUA_ID" NOT NULL ENABLE);
  ALTER TABLE "SAVEMGR"."WORKBASKET_ACTION_PREFERENCES" MODIFY ("WBA_ID" NOT NULL ENABLE);
  ALTER TABLE "SAVEMGR"."WORKBASKET_ACTION_PREFERENCES" MODIFY ("ID" NOT NULL ENABLE);
