--------------------------------------------------------
--  Constraints for Table WORKBASKET_ENTRIES
--------------------------------------------------------

  ALTER TABLE "BPMMGR"."WORKBASKET_ENTRIES" ADD CONSTRAINT "PK_WORKBASKET_ENTRIES" PRIMARY KEY ("WBA_ID", "WB_ID")
  USING INDEX  ENABLE;
  ALTER TABLE "BPMMGR"."WORKBASKET_ENTRIES" MODIFY ("WB_ID" NOT NULL ENABLE);
  ALTER TABLE "BPMMGR"."WORKBASKET_ENTRIES" MODIFY ("WBA_ID" NOT NULL ENABLE);
  ALTER TABLE "BPMMGR"."WORKBASKET_ENTRIES" ADD CONSTRAINT "WORKBASKET_ENTRIES_UK1" UNIQUE ("WB_ID", "WBA_ID")
  USING INDEX  ENABLE;
