--------------------------------------------------------
--  Constraints for Table WUA_PREFERENCE_CATEGORIES
--------------------------------------------------------

  ALTER TABLE "SECUREMGR"."WUA_PREFERENCE_CATEGORIES" ADD CONSTRAINT "WUA_PREF_CAT_PK" PRIMARY KEY ("CATEGORY_NAME")
  USING INDEX  ENABLE;
  ALTER TABLE "SECUREMGR"."WUA_PREFERENCE_CATEGORIES" MODIFY ("XML_DATA" NOT NULL ENABLE);
  ALTER TABLE "SECUREMGR"."WUA_PREFERENCE_CATEGORIES" MODIFY ("CATEGORY_NAME" NOT NULL ENABLE);
