--------------------------------------------------------
--  Constraints for Table XSEQ_FREES
--------------------------------------------------------

  ALTER TABLE "SECUREMGR"."XSEQ_FREES" ADD CONSTRAINT "XSEQS_FREES_PK" PRIMARY KEY ("XSEQ_ID", "XSEQ_VALUE")
  USING INDEX  ENABLE;
  ALTER TABLE "SECUREMGR"."XSEQ_FREES" MODIFY ("CREATED_DATETIME" NOT NULL ENABLE);
  ALTER TABLE "SECUREMGR"."XSEQ_FREES" MODIFY ("XSEQ_TYPE" NOT NULL ENABLE);
  ALTER TABLE "SECUREMGR"."XSEQ_FREES" MODIFY ("XSEQ_VALUE" NOT NULL ENABLE);
  ALTER TABLE "SECUREMGR"."XSEQ_FREES" MODIFY ("XSEQ_ID" NOT NULL ENABLE);
