--------------------------------------------------------
--  Constraints for Table XSEQS
--------------------------------------------------------

  ALTER TABLE "SECUREMGR"."XSEQS" ADD CONSTRAINT "XSEQS_UK1" UNIQUE ("XSEQ_NAME")
  USING INDEX  ENABLE;
  ALTER TABLE "SECUREMGR"."XSEQS" ADD CONSTRAINT "XSEQS_PK" PRIMARY KEY ("XSEQ_ID")
  USING INDEX  ENABLE;
  ALTER TABLE "SECUREMGR"."XSEQS" MODIFY ("FILL_COUNT" NOT NULL ENABLE);
  ALTER TABLE "SECUREMGR"."XSEQS" MODIFY ("RELEASE_COUNT" NOT NULL ENABLE);
  ALTER TABLE "SECUREMGR"."XSEQS" MODIFY ("ALLOCATE_COUNT" NOT NULL ENABLE);
  ALTER TABLE "SECUREMGR"."XSEQS" MODIFY ("CREATED_DATETIME" NOT NULL ENABLE);
  ALTER TABLE "SECUREMGR"."XSEQS" MODIFY ("FILL_SIZE" NOT NULL ENABLE);
  ALTER TABLE "SECUREMGR"."XSEQS" MODIFY ("MIN_VALUE" NOT NULL ENABLE);
  ALTER TABLE "SECUREMGR"."XSEQS" MODIFY ("XSEQ_NAME" NOT NULL ENABLE);
  ALTER TABLE "SECUREMGR"."XSEQS" MODIFY ("XSEQ_ID" NOT NULL ENABLE);
