--------------------------------------------------------
--  Constraints for Table XV_ACTION_GRPS_DATA
--------------------------------------------------------

  ALTER TABLE "XVIEWMGR"."XV_ACTION_GRPS_DATA" MODIFY ("DEFAULT_PROMPT" CONSTRAINT "XV_ACTION_GRPS_NN_CK4" NOT NULL ENABLE);
  ALTER TABLE "XVIEWMGR"."XV_ACTION_GRPS_DATA" MODIFY ("TARGET_MNEM" CONSTRAINT "XV_ACTION_GRPS_NN_CK3" NOT NULL ENABLE);
  ALTER TABLE "XVIEWMGR"."XV_ACTION_GRPS_DATA" MODIFY ("SOURCE_MNEM" CONSTRAINT "XV_ACTION_GRPS_NN_CK2" NOT NULL ENABLE);
  ALTER TABLE "XVIEWMGR"."XV_ACTION_GRPS_DATA" MODIFY ("BPD_ID" CONSTRAINT "XV_ACTION_GRPS_NN_CK1" NOT NULL ENABLE);
  ALTER TABLE "XVIEWMGR"."XV_ACTION_GRPS_DATA" ADD CONSTRAINT "XV_ACTION_GRPS_PK" PRIMARY KEY ("SOURCE_MNEM", "TARGET_MNEM") DEFERRABLE INITIALLY DEFERRED
  USING INDEX  ENABLE;
