--------------------------------------------------------
--  Constraints for Table XV_AB_REQUEST_TMPL_DATA
--------------------------------------------------------

  ALTER TABLE "XVIEWMGR"."XV_AB_REQUEST_TMPL_DATA" MODIFY ("AB_ID" CONSTRAINT "XV_AB_REQUEST_TMPL_NN_CK1" NOT NULL ENABLE);
  ALTER TABLE "XVIEWMGR"."XV_AB_REQUEST_TMPL_DATA" ADD CONSTRAINT "XV_AB_REQUEST_TMPL_PK" PRIMARY KEY ("ART_ID") DEFERRABLE INITIALLY DEFERRED
  USING INDEX  ENABLE;
