--------------------------------------------------------
--  Constraints for Table XV_ASSIGNEES_DATA
--------------------------------------------------------

  ALTER TABLE "XVIEWMGR"."XV_ASSIGNEES_DATA" MODIFY ("ASSIGNEE_UREF" CONSTRAINT "XV_ASSIGNEES_NN_CK3" NOT NULL ENABLE);
  ALTER TABLE "XVIEWMGR"."XV_ASSIGNEES_DATA" MODIFY ("BAS_ID" CONSTRAINT "XV_ASSIGNEES_NN_CK2" NOT NULL ENABLE);
  ALTER TABLE "XVIEWMGR"."XV_ASSIGNEES_DATA" MODIFY ("BAD_ID" CONSTRAINT "XV_ASSIGNEES_NN_CK1" NOT NULL ENABLE);
  ALTER TABLE "XVIEWMGR"."XV_ASSIGNEES_DATA" ADD CONSTRAINT "XV_ASSIGNEES_PK" PRIMARY KEY ("BAD_ID", "ASSIGNEE_UREF")
  USING INDEX  ENABLE;
