--------------------------------------------------------
--  Constraints for Table XV_BUSINESS_ACT_DATA
--------------------------------------------------------

  ALTER TABLE "XVIEWMGR"."XV_BUSINESS_ACT_DATA" MODIFY ("START_DATETIME" CONSTRAINT "XV_BUSINESS_ACT_NN_CK5" NOT NULL ENABLE);
  ALTER TABLE "XVIEWMGR"."XV_BUSINESS_ACT_DATA" MODIFY ("STATUS" CONSTRAINT "XV_BUSINESS_ACT_NN_CK4" NOT NULL ENABLE);
  ALTER TABLE "XVIEWMGR"."XV_BUSINESS_ACT_DATA" MODIFY ("TITLE" CONSTRAINT "XV_BUSINESS_ACT_NN_CK3" NOT NULL ENABLE);
  ALTER TABLE "XVIEWMGR"."XV_BUSINESS_ACT_DATA" MODIFY ("ACTIVITY_REF" CONSTRAINT "XV_BUSINESS_ACT_NN_CK2" NOT NULL ENABLE);
  ALTER TABLE "XVIEWMGR"."XV_BUSINESS_ACT_DATA" MODIFY ("BA_ID" CONSTRAINT "XV_BUSINESS_ACT_NN_CK1" NOT NULL ENABLE);
  ALTER TABLE "XVIEWMGR"."XV_BUSINESS_ACT_DATA" ADD CONSTRAINT "XV_BUSINESS_ACT_PK" PRIMARY KEY ("BA_ID")
  USING INDEX  ENABLE;
