--------------------------------------------------------
--  Constraints for Table XV_BUSINESS_STAGES_DATA
--------------------------------------------------------

  ALTER TABLE "XVIEWMGR"."XV_BUSINESS_STAGES_DATA" MODIFY ("STAGE_LABEL" CONSTRAINT "XV_BUSINESS_STAGES_NN_CK7" NOT NULL ENABLE);
  ALTER TABLE "XVIEWMGR"."XV_BUSINESS_STAGES_DATA" MODIFY ("BP_ID" CONSTRAINT "XV_BUSINESS_STAGES_NN_CK4" NOT NULL ENABLE);
  ALTER TABLE "XVIEWMGR"."XV_BUSINESS_STAGES_DATA" MODIFY ("START_DATETIME" CONSTRAINT "XV_BUSINESS_STAGES_NN_CK2" NOT NULL ENABLE);
  ALTER TABLE "XVIEWMGR"."XV_BUSINESS_STAGES_DATA" MODIFY ("BS_ID" CONSTRAINT "XV_BUSINESS_STAGES_NN_CK1" NOT NULL ENABLE);
