--------------------------------------------------------
--  Constraints for Table XV_CNTRY_GRP_ATTR_DATA
--------------------------------------------------------

  ALTER TABLE "XVIEWMGR"."XV_CNTRY_GRP_ATTR_DATA" MODIFY ("COUNTRY_GROUP_ID" CONSTRAINT "XV_CNTRY_GRP_ATTR_NN_CK3" NOT NULL ENABLE);
  ALTER TABLE "XVIEWMGR"."XV_CNTRY_GRP_ATTR_DATA" MODIFY ("COUNTRY_SET_ID" CONSTRAINT "XV_CNTRY_GRP_ATTR_NN_CK2" NOT NULL ENABLE);
  ALTER TABLE "XVIEWMGR"."XV_CNTRY_GRP_ATTR_DATA" MODIFY ("CGD_ID" CONSTRAINT "XV_CNTRY_GRP_ATTR_NN_CK1" NOT NULL ENABLE);
