--------------------------------------------------------
--  Constraints for Table XV_CTRY_GRP_DTLS_DATA
--------------------------------------------------------

  ALTER TABLE "XVIEWMGR"."XV_CTRY_GRP_DTLS_DATA" MODIFY ("COUNTRY_SET_ID" CONSTRAINT "XV_CTRY_GRP_DTLS_NN_CK4" NOT NULL ENABLE);
  ALTER TABLE "XVIEWMGR"."XV_CTRY_GRP_DTLS_DATA" MODIFY ("COUNTRY_GROUP_ID" CONSTRAINT "XV_CTRY_GRP_DTLS_NN_CK2" NOT NULL ENABLE);
  ALTER TABLE "XVIEWMGR"."XV_CTRY_GRP_DTLS_DATA" MODIFY ("COUNTRY_GROUP_DETAIL_ID" CONSTRAINT "XV_CTRY_GRP_DTLS_NN_CK1" NOT NULL ENABLE);
