--------------------------------------------------------
--  Constraints for Table XV_COMPL_ACT_DTLS_DATA
--------------------------------------------------------

  ALTER TABLE "XVIEWMGR"."XV_COMPL_ACT_DTLS_DATA" MODIFY ("START_DATETIME" CONSTRAINT "XV_COMPL_ACT_DTLS_NN_CK3" NOT NULL ENABLE);
  ALTER TABLE "XVIEWMGR"."XV_COMPL_ACT_DTLS_DATA" MODIFY ("CA_ID" CONSTRAINT "XV_COMPL_ACT_DTLS_NN_CK2" NOT NULL ENABLE);
  ALTER TABLE "XVIEWMGR"."XV_COMPL_ACT_DTLS_DATA" MODIFY ("CAD_ID" CONSTRAINT "XV_COMPL_ACT_DTLS_NN_CK1" NOT NULL ENABLE);
