--------------------------------------------------------
--  Constraints for Table XV_COUNTRY_DETAILS_DATA
--------------------------------------------------------

  ALTER TABLE "XVIEWMGR"."XV_COUNTRY_DETAILS_DATA" MODIFY ("COUNTRY_SET_ID" CONSTRAINT "XV_COUNTRY_DETAILS_NN_CK3" NOT NULL ENABLE);
  ALTER TABLE "XVIEWMGR"."XV_COUNTRY_DETAILS_DATA" MODIFY ("COUNTRY_ID" CONSTRAINT "XV_COUNTRY_DETAILS_NN_CK2" NOT NULL ENABLE);
  ALTER TABLE "XVIEWMGR"."XV_COUNTRY_DETAILS_DATA" MODIFY ("COUNTRY_DETAIL_ID" CONSTRAINT "XV_COUNTRY_DETAILS_NN_CK1" NOT NULL ENABLE);
