--------------------------------------------------------
--  Constraints for Table XV_DOC_TEMPLA_ATTR_DATA
--------------------------------------------------------

  ALTER TABLE "XVIEWMGR"."XV_DOC_TEMPLA_ATTR_DATA" MODIFY ("VALUE" CONSTRAINT "XV_DOC_TEMPLA_ATTR_NN_CK4" NOT NULL ENABLE);
  ALTER TABLE "XVIEWMGR"."XV_DOC_TEMPLA_ATTR_DATA" MODIFY ("NAME" CONSTRAINT "XV_DOC_TEMPLA_ATTR_NN_CK3" NOT NULL ENABLE);
  ALTER TABLE "XVIEWMGR"."XV_DOC_TEMPLA_ATTR_DATA" MODIFY ("ATTR_SET_ID" CONSTRAINT "XV_DOC_TEMPLA_ATTR_NN_CK2" NOT NULL ENABLE);
  ALTER TABLE "XVIEWMGR"."XV_DOC_TEMPLA_ATTR_DATA" MODIFY ("TEMPLATE_NAME" CONSTRAINT "XV_DOC_TEMPLA_ATTR_NN_CK1" NOT NULL ENABLE);
  ALTER TABLE "XVIEWMGR"."XV_DOC_TEMPLA_ATTR_DATA" ADD CONSTRAINT "XV_DOC_TEMPLA_ATTR_UK1001" UNIQUE ("TEMPLATE_NAME", "ATTR_SET_ID", "NAME", "VALUE")
  USING INDEX  ENABLE;
