--------------------------------------------------------
--  Constraints for Table XV_DOC_MIME_TYPES_DATA
--------------------------------------------------------

  ALTER TABLE "XVIEWMGR"."XV_DOC_MIME_TYPES_DATA" MODIFY ("MIME_TYPE_LOWER" CONSTRAINT "XV_DOC_MIME_TYPES_NN_CK7" NOT NULL ENABLE);
  ALTER TABLE "XVIEWMGR"."XV_DOC_MIME_TYPES_DATA" MODIFY ("EXT_ID" CONSTRAINT "XV_DOC_MIME_TYPES_NN_CK5" NOT NULL ENABLE);
  ALTER TABLE "XVIEWMGR"."XV_DOC_MIME_TYPES_DATA" MODIFY ("DEFAULT_EXT_ID" CONSTRAINT "XV_DOC_MIME_TYPES_NN_CK4" NOT NULL ENABLE);
  ALTER TABLE "XVIEWMGR"."XV_DOC_MIME_TYPES_DATA" MODIFY ("MIME_TYPE" CONSTRAINT "XV_DOC_MIME_TYPES_NN_CK2" NOT NULL ENABLE);
  ALTER TABLE "XVIEWMGR"."XV_DOC_MIME_TYPES_DATA" MODIFY ("DMT_ID" CONSTRAINT "XV_DOC_MIME_TYPES_NN_CK1" NOT NULL ENABLE);
  ALTER TABLE "XVIEWMGR"."XV_DOC_MIME_TYPES_DATA" ADD CONSTRAINT "XV_DOC_MIME_TYPES_UK1001" UNIQUE ("MIME_TYPE_LOWER", "EXT_ID")
  USING INDEX  ENABLE;
