--------------------------------------------------------
--  Constraints for Table XV_DOC_INTS_DATA
--------------------------------------------------------

  ALTER TABLE "XVIEWMGR"."XV_DOC_INTS_DATA" MODIFY ("DISPLAY_SEQUENCE" CONSTRAINT "XV_DOC_INTS_NN_CK3" NOT NULL ENABLE);
  ALTER TABLE "XVIEWMGR"."XV_DOC_INTS_DATA" MODIFY ("DP_ID" CONSTRAINT "XV_DOC_INTS_NN_CK2" NOT NULL ENABLE);
  ALTER TABLE "XVIEWMGR"."XV_DOC_INTS_DATA" MODIFY ("DI_ID" CONSTRAINT "XV_DOC_INTS_NN_CK1" NOT NULL ENABLE);
