--------------------------------------------------------
--  Constraints for Table XV_DOC_DATA_DATA
--------------------------------------------------------

  ALTER TABLE "XVIEWMGR"."XV_DOC_DATA_DATA" MODIFY ("STATUS" CONSTRAINT "XV_DOC_DATA_NN_CK3" NOT NULL ENABLE);
  ALTER TABLE "XVIEWMGR"."XV_DOC_DATA_DATA" MODIFY ("DI_ID" CONSTRAINT "XV_DOC_DATA_NN_CK2" NOT NULL ENABLE);
  ALTER TABLE "XVIEWMGR"."XV_DOC_DATA_DATA" MODIFY ("DD_ID" CONSTRAINT "XV_DOC_DATA_NN_CK1" NOT NULL ENABLE);
  ALTER TABLE "XVIEWMGR"."XV_DOC_DATA_DATA" ADD CONSTRAINT "XV_DOC_DATA_PK" PRIMARY KEY ("DD_ID") DEFERRABLE INITIALLY DEFERRED
  USING INDEX  ENABLE;
