--------------------------------------------------------
--  Constraints for Table XV_DOC_PACKS_DATA
--------------------------------------------------------

  ALTER TABLE "XVIEWMGR"."XV_DOC_PACKS_DATA" MODIFY ("DS_ID" CONSTRAINT "XV_DOC_PACKS_NN_CK2" NOT NULL ENABLE);
  ALTER TABLE "XVIEWMGR"."XV_DOC_PACKS_DATA" MODIFY ("DP_ID" CONSTRAINT "XV_DOC_PACKS_NN_CK1" NOT NULL ENABLE);
  ALTER TABLE "XVIEWMGR"."XV_DOC_PACKS_DATA" ADD CONSTRAINT "XV_DOC_PACKS_PK" PRIMARY KEY ("DP_ID") DEFERRABLE INITIALLY DEFERRED
  USING INDEX  ENABLE;
