--------------------------------------------------------
--  Constraints for Table XV_ELA_TMPLS_DATA
--------------------------------------------------------

  ALTER TABLE "XVIEWMGR"."XV_ELA_TMPLS_DATA" MODIFY ("STATUS" CONSTRAINT "XV_ELA_TMPLS_NN_CK5" NOT NULL ENABLE);
  ALTER TABLE "XVIEWMGR"."XV_ELA_TMPLS_DATA" MODIFY ("ELA_TMPL_ID" CONSTRAINT "XV_ELA_TMPLS_NN_CK1" NOT NULL ENABLE);
  ALTER TABLE "XVIEWMGR"."XV_ELA_TMPLS_DATA" ADD CONSTRAINT "XV_ELA_TMPLS_PK" PRIMARY KEY ("ELA_TMPL_ID")
  USING INDEX  ENABLE;
