--------------------------------------------------------
--  Constraints for Table XV_ELA_DETAILS_DATA_1
--------------------------------------------------------

  ALTER TABLE "SAVEMGR"."XV_ELA_DETAILS_DATA_1" MODIFY ("STATUS" NOT NULL ENABLE);
  ALTER TABLE "SAVEMGR"."XV_ELA_DETAILS_DATA_1" MODIFY ("START_DATE" NOT NULL ENABLE);
  ALTER TABLE "SAVEMGR"."XV_ELA_DETAILS_DATA_1" MODIFY ("ELA_ID" NOT NULL ENABLE);
  ALTER TABLE "SAVEMGR"."XV_ELA_DETAILS_DATA_1" MODIFY ("ELA_DETAIL_ID" NOT NULL ENABLE);
