--------------------------------------------------------
--  Constraints for Table XV_ENV_MAPSETS_DATA
--------------------------------------------------------

  ALTER TABLE "XVIEWMGR"."XV_ENV_MAPSETS_DATA" MODIFY ("MAPSET_ID" CONSTRAINT "XV_ENV_MAPSETS_NN_CK3" NOT NULL ENABLE);
  ALTER TABLE "XVIEWMGR"."XV_ENV_MAPSETS_DATA" MODIFY ("ID" CONSTRAINT "XV_ENV_MAPSETS_NN_CK2" NOT NULL ENABLE);
  ALTER TABLE "XVIEWMGR"."XV_ENV_MAPSETS_DATA" MODIFY ("MS_DOMAIN" CONSTRAINT "XV_ENV_MAPSETS_NN_CK1" NOT NULL ENABLE);
