--------------------------------------------------------
--  Constraints for Table XV_ELA_DETAILS_DATA
--------------------------------------------------------

  ALTER TABLE "XVIEWMGR"."XV_ELA_DETAILS_DATA" MODIFY ("STATUS" CONSTRAINT "XV_ELA_DETAILS_NN_CK5" NOT NULL ENABLE);
  ALTER TABLE "XVIEWMGR"."XV_ELA_DETAILS_DATA" MODIFY ("START_DATE" CONSTRAINT "XV_ELA_DETAILS_NN_CK3" NOT NULL ENABLE);
  ALTER TABLE "XVIEWMGR"."XV_ELA_DETAILS_DATA" MODIFY ("ELA_ID" CONSTRAINT "XV_ELA_DETAILS_NN_CK2" NOT NULL ENABLE);
  ALTER TABLE "XVIEWMGR"."XV_ELA_DETAILS_DATA" MODIFY ("ELA_DETAIL_ID" CONSTRAINT "XV_ELA_DETAILS_NN_CK1" NOT NULL ENABLE);
  ALTER TABLE "XVIEWMGR"."XV_ELA_DETAILS_DATA" ADD CONSTRAINT "XV_ELA_DETAILS_PK" PRIMARY KEY ("ELA_DETAIL_ID")
  USING INDEX  ENABLE;
