--------------------------------------------------------
--  Constraints for Table XV_ELA_DETAILS_DATA
--------------------------------------------------------

  ALTER TABLE "SAVEMGR"."XV_ELA_DETAILS_DATA" MODIFY ("STATUS" NOT NULL ENABLE);
  ALTER TABLE "SAVEMGR"."XV_ELA_DETAILS_DATA" MODIFY ("START_DATE" NOT NULL ENABLE);
  ALTER TABLE "SAVEMGR"."XV_ELA_DETAILS_DATA" MODIFY ("ELA_ID" NOT NULL ENABLE);
  ALTER TABLE "SAVEMGR"."XV_ELA_DETAILS_DATA" MODIFY ("ELA_DETAIL_ID" NOT NULL ENABLE);
