--------------------------------------------------------
--  Constraints for Table XV_FILE_TGT_DEFS_DATA
--------------------------------------------------------

  ALTER TABLE "XVIEWMGR"."XV_FILE_TGT_DEFS_DATA" MODIFY ("MIN_TARGETS" CONSTRAINT "XV_FILE_TGT_DEFS_NN_CK5" NOT NULL ENABLE);
  ALTER TABLE "XVIEWMGR"."XV_FILE_TGT_DEFS_DATA" MODIFY ("TARGET_MNEM" CONSTRAINT "XV_FILE_TGT_DEFS_NN_CK2" NOT NULL ENABLE);
  ALTER TABLE "XVIEWMGR"."XV_FILE_TGT_DEFS_DATA" MODIFY ("FILE_FOLDER_TYPE" CONSTRAINT "XV_FILE_TGT_DEFS_NN_CK1" NOT NULL ENABLE);
