--------------------------------------------------------
--  Constraints for Table XV_GC_GCED_DATA
--------------------------------------------------------

  ALTER TABLE "XVIEWMGR"."XV_GC_GCED_DATA" MODIFY ("START_DATETIME" CONSTRAINT "XV_GC_GCED_NN_CK5" NOT NULL ENABLE);
  ALTER TABLE "XVIEWMGR"."XV_GC_GCED_DATA" MODIFY ("STATUS" CONSTRAINT "XV_GC_GCED_NN_CK4" NOT NULL ENABLE);
  ALTER TABLE "XVIEWMGR"."XV_GC_GCED_DATA" MODIFY ("GCR_ID" CONSTRAINT "XV_GC_GCED_NN_CK3" NOT NULL ENABLE);
  ALTER TABLE "XVIEWMGR"."XV_GC_GCED_DATA" MODIFY ("GCE_ID" CONSTRAINT "XV_GC_GCED_NN_CK2" NOT NULL ENABLE);
  ALTER TABLE "XVIEWMGR"."XV_GC_GCED_DATA" MODIFY ("GCED_ID" CONSTRAINT "XV_GC_GCED_NN_CK1" NOT NULL ENABLE);
