--------------------------------------------------------
--  Constraints for Table XV_INTENTION_DTLS_DATA
--------------------------------------------------------

  ALTER TABLE "XVIEWMGR"."XV_INTENTION_DTLS_DATA" MODIFY ("CLAUSE_ID" CONSTRAINT "XV_INTENTION_DTLS_NN_CK10" NOT NULL ENABLE);
  ALTER TABLE "XVIEWMGR"."XV_INTENTION_DTLS_DATA" MODIFY ("START_DATETIME" CONSTRAINT "XV_INTENTION_DTLS_NN_CK4" NOT NULL ENABLE);
  ALTER TABLE "XVIEWMGR"."XV_INTENTION_DTLS_DATA" MODIFY ("IN_ID" CONSTRAINT "XV_INTENTION_DTLS_NN_CK2" NOT NULL ENABLE);
  ALTER TABLE "XVIEWMGR"."XV_INTENTION_DTLS_DATA" MODIFY ("ID_ID" CONSTRAINT "XV_INTENTION_DTLS_NN_CK1" NOT NULL ENABLE);
  ALTER TABLE "XVIEWMGR"."XV_INTENTION_DTLS_DATA" ADD CONSTRAINT "XV_INTENTION_DTLS_PK" PRIMARY KEY ("ID_ID") DEFERRABLE INITIALLY DEFERRED
  USING INDEX  ENABLE;
