--------------------------------------------------------
--  Constraints for Table XV_INTENTION_ACTS_DATA
--------------------------------------------------------

  ALTER TABLE "XVIEWMGR"."XV_INTENTION_ACTS_DATA" MODIFY ("ID_ID" CONSTRAINT "XV_INTENTION_ACTS_NN_CK1" NOT NULL ENABLE);
  ALTER TABLE "XVIEWMGR"."XV_INTENTION_ACTS_DATA" MODIFY ("IN_ID" CONSTRAINT "XV_INTENTION_ACTS_NN_CK2" NOT NULL ENABLE);
  ALTER TABLE "XVIEWMGR"."XV_INTENTION_ACTS_DATA" ADD CONSTRAINT "XV_INTENTION_ACTS_UK1001" UNIQUE ("IN_ID", "ACTION_NAME")
  USING INDEX  ENABLE;
