--------------------------------------------------------
--  Constraints for Table XV_MATRIX_FOLDERS_DATA
--------------------------------------------------------

  ALTER TABLE "XVIEWMGR"."XV_MATRIX_FOLDERS_DATA" MODIFY ("PAPER_FILE" CONSTRAINT "XV_MATRIX_FOLDERS_NN_CK14" NOT NULL ENABLE);
  ALTER TABLE "XVIEWMGR"."XV_MATRIX_FOLDERS_DATA" MODIFY ("RECORD_TYPE" CONSTRAINT "XV_MATRIX_FOLDERS_NN_CK7" NOT NULL ENABLE);
  ALTER TABLE "XVIEWMGR"."XV_MATRIX_FOLDERS_DATA" MODIFY ("RECORD_TITLE" CONSTRAINT "XV_MATRIX_FOLDERS_NN_CK5" NOT NULL ENABLE);
  ALTER TABLE "XVIEWMGR"."XV_MATRIX_FOLDERS_DATA" MODIFY ("RECORD_NUMBER" CONSTRAINT "XV_MATRIX_FOLDERS_NN_CK4" NOT NULL ENABLE);
  ALTER TABLE "XVIEWMGR"."XV_MATRIX_FOLDERS_DATA" MODIFY ("MF_ID" CONSTRAINT "XV_MATRIX_FOLDERS_NN_CK1" NOT NULL ENABLE);
  ALTER TABLE "XVIEWMGR"."XV_MATRIX_FOLDERS_DATA" ADD CONSTRAINT "XV_MATRIX_FOLDERS_UK1001" UNIQUE ("RECORD_NUMBER") DEFERRABLE INITIALLY DEFERRED
  USING INDEX  ENABLE;
  ALTER TABLE "XVIEWMGR"."XV_MATRIX_FOLDERS_DATA" ADD CONSTRAINT "XV_MATRIX_FOLDERS_PK" PRIMARY KEY ("MF_ID") DEFERRABLE INITIALLY DEFERRED
  USING INDEX  ENABLE;
