--------------------------------------------------------
--  Constraints for Table XV_NOTES_DATA
--------------------------------------------------------

  ALTER TABLE "XVIEWMGR"."XV_NOTES_DATA" MODIFY ("CREATED_DATETIME" CONSTRAINT "XV_NOTES_NN_CK7" NOT NULL ENABLE);
  ALTER TABLE "XVIEWMGR"."XV_NOTES_DATA" MODIFY ("CREATED_BY_FULL_NAME" CONSTRAINT "XV_NOTES_NN_CK6" NOT NULL ENABLE);
  ALTER TABLE "XVIEWMGR"."XV_NOTES_DATA" MODIFY ("CREATED_BY_ID" CONSTRAINT "XV_NOTES_NN_CK5" NOT NULL ENABLE);
  ALTER TABLE "XVIEWMGR"."XV_NOTES_DATA" MODIFY ("SUBJECT" CONSTRAINT "XV_NOTES_NN_CK2" NOT NULL ENABLE);
  ALTER TABLE "XVIEWMGR"."XV_NOTES_DATA" MODIFY ("N_ID" CONSTRAINT "XV_NOTES_NN_CK1" NOT NULL ENABLE);
