--------------------------------------------------------
--  Constraints for Table XV_NOTIFICATION_DATA
--------------------------------------------------------

  ALTER TABLE "XVIEWMGR"."XV_NOTIFICATION_DATA" MODIFY ("DP_ID" CONSTRAINT "XV_NOTIFICATION_NN_CK3" NOT NULL ENABLE);
  ALTER TABLE "XVIEWMGR"."XV_NOTIFICATION_DATA" MODIFY ("NS_ID" CONSTRAINT "XV_NOTIFICATION_NN_CK2" NOT NULL ENABLE);
  ALTER TABLE "XVIEWMGR"."XV_NOTIFICATION_DATA" MODIFY ("N_ID" CONSTRAINT "XV_NOTIFICATION_NN_CK1" NOT NULL ENABLE);
