--------------------------------------------------------
--  Constraints for Table XV_ORG_NAMES_DATA
--------------------------------------------------------

  ALTER TABLE "XVIEWMGR"."XV_ORG_NAMES_DATA" MODIFY ("NAME" CONSTRAINT "XV_ORG_NAMES_NN_CK5" NOT NULL ENABLE);
  ALTER TABLE "XVIEWMGR"."XV_ORG_NAMES_DATA" MODIFY ("START_DATE" CONSTRAINT "XV_ORG_NAMES_NN_CK3" NOT NULL ENABLE);
  ALTER TABLE "XVIEWMGR"."XV_ORG_NAMES_DATA" MODIFY ("ORGAN_ID" CONSTRAINT "XV_ORG_NAMES_NN_CK2" NOT NULL ENABLE);
  ALTER TABLE "XVIEWMGR"."XV_ORG_NAMES_DATA" MODIFY ("ID" CONSTRAINT "XV_ORG_NAMES_NN_CK1" NOT NULL ENABLE);
  ALTER TABLE "XVIEWMGR"."XV_ORG_NAMES_DATA" ADD CONSTRAINT "XV_ORG_NAMES_UK1001" UNIQUE ("ORGAN_ID", "START_DATE") DEFERRABLE INITIALLY DEFERRED
  USING INDEX  ENABLE;
  ALTER TABLE "XVIEWMGR"."XV_ORG_NAMES_DATA" ADD CONSTRAINT "XV_ORG_NAMES_PK" PRIMARY KEY ("ID") DEFERRABLE INITIALLY DEFERRED
  USING INDEX  ENABLE;
