--------------------------------------------------------
--  Constraints for Table XV_ORG_SIC_CODES_DATA
--------------------------------------------------------

  ALTER TABLE "XVIEWMGR"."XV_ORG_SIC_CODES_DATA" MODIFY ("SIC_CODE" CONSTRAINT "XV_ORG_SIC_CODES_NN_CK3" NOT NULL ENABLE);
  ALTER TABLE "XVIEWMGR"."XV_ORG_SIC_CODES_DATA" MODIFY ("ORGAN_ID" CONSTRAINT "XV_ORG_SIC_CODES_NN_CK2" NOT NULL ENABLE);
  ALTER TABLE "XVIEWMGR"."XV_ORG_SIC_CODES_DATA" MODIFY ("OD_ID" CONSTRAINT "XV_ORG_SIC_CODES_NN_CK1" NOT NULL ENABLE);
