--------------------------------------------------------
--  Constraints for Table XV_PAGE_CNTNT_DTLS_DATA
--------------------------------------------------------

  ALTER TABLE "XVIEWMGR"."XV_PAGE_CNTNT_DTLS_DATA" MODIFY ("PAGE_CONTENT_TYPE" CONSTRAINT "XV_PAGE_CNTNT_DTLS_NN_CK3" NOT NULL ENABLE);
  ALTER TABLE "XVIEWMGR"."XV_PAGE_CNTNT_DTLS_DATA" MODIFY ("PC_ID" CONSTRAINT "XV_PAGE_CNTNT_DTLS_NN_CK2" NOT NULL ENABLE);
  ALTER TABLE "XVIEWMGR"."XV_PAGE_CNTNT_DTLS_DATA" MODIFY ("PCD_ID" CONSTRAINT "XV_PAGE_CNTNT_DTLS_NN_CK1" NOT NULL ENABLE);
  ALTER TABLE "XVIEWMGR"."XV_PAGE_CNTNT_DTLS_DATA" ADD CONSTRAINT "XV_PAGE_CNTNT_DTLS_PK" PRIMARY KEY ("PCD_ID")
  USING INDEX  ENABLE;
