--------------------------------------------------------
--  Constraints for Table XV_PORTAL_FOLDERS_DATA
--------------------------------------------------------

  ALTER TABLE "XVIEWMGR"."XV_PORTAL_FOLDERS_DATA" MODIFY ("FOLDER_TYPE" CONSTRAINT "XV_PORTAL_FOLDERS_NN_CK7" NOT NULL ENABLE);
  ALTER TABLE "XVIEWMGR"."XV_PORTAL_FOLDERS_DATA" MODIFY ("PRIMARY_DATA_UREF" CONSTRAINT "XV_PORTAL_FOLDERS_NN_CK6" NOT NULL ENABLE);
  ALTER TABLE "XVIEWMGR"."XV_PORTAL_FOLDERS_DATA" MODIFY ("PF_TITLE" CONSTRAINT "XV_PORTAL_FOLDERS_NN_CK3" NOT NULL ENABLE);
  ALTER TABLE "XVIEWMGR"."XV_PORTAL_FOLDERS_DATA" MODIFY ("PRIMARY_FOLDER_REFERENCE" CONSTRAINT "XV_PORTAL_FOLDERS_NN_CK2" NOT NULL ENABLE);
  ALTER TABLE "XVIEWMGR"."XV_PORTAL_FOLDERS_DATA" MODIFY ("PF_ID" CONSTRAINT "XV_PORTAL_FOLDERS_NN_CK1" NOT NULL ENABLE);
  ALTER TABLE "XVIEWMGR"."XV_PORTAL_FOLDERS_DATA" MODIFY ("STARTED" CONSTRAINT "XV_PORTAL_FOLDERS_NN_CK4" NOT NULL ENABLE);
  ALTER TABLE "XVIEWMGR"."XV_PORTAL_FOLDERS_DATA" ADD CONSTRAINT "XV_PORTAL_FOLDERS_UK1002" UNIQUE ("PF_TITLE")
  USING INDEX  ENABLE;
  ALTER TABLE "XVIEWMGR"."XV_PORTAL_FOLDERS_DATA" ADD CONSTRAINT "XV_PORTAL_FOLDERS_UK1001" UNIQUE ("PRIMARY_FOLDER_REFERENCE")
  USING INDEX  ENABLE;
  ALTER TABLE "XVIEWMGR"."XV_PORTAL_FOLDERS_DATA" ADD CONSTRAINT "XV_PORTAL_FOLDERS_PK" PRIMARY KEY ("PF_ID")
  USING INDEX  ENABLE;
