--------------------------------------------------------
--  Constraints for Table XV_PF_REFS_DATA
--------------------------------------------------------

  ALTER TABLE "XVIEWMGR"."XV_PF_REFS_DATA" MODIFY ("PF_REFERENCE" CONSTRAINT "XV_PF_REFS_NN_CK2" NOT NULL ENABLE);
  ALTER TABLE "XVIEWMGR"."XV_PF_REFS_DATA" MODIFY ("PF_ID" CONSTRAINT "XV_PF_REFS_NN_CK1" NOT NULL ENABLE);
  ALTER TABLE "XVIEWMGR"."XV_PF_REFS_DATA" ADD CONSTRAINT "XV_PF_REFS_PK" PRIMARY KEY ("PF_ID", "PF_REFERENCE")
  USING INDEX  ENABLE;
