--------------------------------------------------------
--  Constraints for Table XV_PVEX_NOVA_DETS_DATA
--------------------------------------------------------

  ALTER TABLE "XVIEWMGR"."XV_PVEX_NOVA_DETS_DATA" MODIFY ("STATUS" CONSTRAINT "XV_PVEX_NOVA_DETS_NN_CK12" NOT NULL ENABLE);
  ALTER TABLE "XVIEWMGR"."XV_PVEX_NOVA_DETS_DATA" MODIFY ("N_ID" CONSTRAINT "XV_PVEX_NOVA_DETS_NN_CK2" NOT NULL ENABLE);
  ALTER TABLE "XVIEWMGR"."XV_PVEX_NOVA_DETS_DATA" MODIFY ("ND_ID" CONSTRAINT "XV_PVEX_NOVA_DETS_NN_CK1" NOT NULL ENABLE);
