--------------------------------------------------------
--  Constraints for Table XV_PVEX_APP_DETS_DATA
--------------------------------------------------------

  ALTER TABLE "XVIEWMGR"."XV_PVEX_APP_DETS_DATA" MODIFY ("STATUS" CONSTRAINT "XV_PVEX_APP_DETS_NN_CK6" NOT NULL ENABLE);
  ALTER TABLE "XVIEWMGR"."XV_PVEX_APP_DETS_DATA" MODIFY ("PEA_ID" CONSTRAINT "XV_PVEX_APP_DETS_NN_CK2" NOT NULL ENABLE);
  ALTER TABLE "XVIEWMGR"."XV_PVEX_APP_DETS_DATA" MODIFY ("PEAD_ID" CONSTRAINT "XV_PVEX_APP_DETS_NN_CK1" NOT NULL ENABLE);
