--------------------------------------------------------
--  Constraints for Table XV_PORTAL_FDR_ABST_DATA
--------------------------------------------------------

  ALTER TABLE "XVIEWMGR"."XV_PORTAL_FDR_ABST_DATA" MODIFY ("WUA_ID" CONSTRAINT "XV_PORTAL_FDR_ABST_NN_CK5" NOT NULL ENABLE);
  ALTER TABLE "XVIEWMGR"."XV_PORTAL_FDR_ABST_DATA" MODIFY ("PF_ID" CONSTRAINT "XV_PORTAL_FDR_ABST_NN_CK2" NOT NULL ENABLE);
  ALTER TABLE "XVIEWMGR"."XV_PORTAL_FDR_ABST_DATA" MODIFY ("PFA_ID" CONSTRAINT "XV_PORTAL_FDR_ABST_NN_CK1" NOT NULL ENABLE);
