--------------------------------------------------------
--  Constraints for Table XV_REPORT_PRT_STY_DATA
--------------------------------------------------------

  ALTER TABLE "XVIEWMGR"."XV_REPORT_PRT_STY_DATA" MODIFY ("STYLE_NAME" CONSTRAINT "XV_REPORT_PRT_STY_NN_CK3" NOT NULL ENABLE);
  ALTER TABLE "XVIEWMGR"."XV_REPORT_PRT_STY_DATA" MODIFY ("PART_LABEL" CONSTRAINT "XV_REPORT_PRT_STY_NN_CK2" NOT NULL ENABLE);
  ALTER TABLE "XVIEWMGR"."XV_REPORT_PRT_STY_DATA" MODIFY ("DOMAIN" CONSTRAINT "XV_REPORT_PRT_STY_NN_CK1" NOT NULL ENABLE);
  ALTER TABLE "XVIEWMGR"."XV_REPORT_PRT_STY_DATA" ADD CONSTRAINT "XV_REPORT_PRT_STY_UK1001" UNIQUE ("DOMAIN", "PART_LABEL", "STYLE_NAME") DEFERRABLE INITIALLY DEFERRED
  USING INDEX  ENABLE;
