--------------------------------------------------------
--  Constraints for Table XV_REPORT_PRTS_DATA
--------------------------------------------------------

  ALTER TABLE "XVIEWMGR"."XV_REPORT_PRTS_DATA" MODIFY ("FETCH_MODE" CONSTRAINT "XV_REPORT_PRTS_NN_CK18" NOT NULL ENABLE);
  ALTER TABLE "XVIEWMGR"."XV_REPORT_PRTS_DATA" MODIFY ("WORKBOOK" CONSTRAINT "XV_REPORT_PRTS_NN_CK13" NOT NULL ENABLE);
  ALTER TABLE "XVIEWMGR"."XV_REPORT_PRTS_DATA" MODIFY ("PART_LABEL" CONSTRAINT "XV_REPORT_PRTS_NN_CK3" NOT NULL ENABLE);
  ALTER TABLE "XVIEWMGR"."XV_REPORT_PRTS_DATA" MODIFY ("DOMAIN" CONSTRAINT "XV_REPORT_PRTS_NN_CK2" NOT NULL ENABLE);
  ALTER TABLE "XVIEWMGR"."XV_REPORT_PRTS_DATA" MODIFY ("PART_ID" CONSTRAINT "XV_REPORT_PRTS_NN_CK1" NOT NULL ENABLE);
  ALTER TABLE "XVIEWMGR"."XV_REPORT_PRTS_DATA" ADD CONSTRAINT "XV_REPORT_PRTS_PK" PRIMARY KEY ("DOMAIN", "PART_LABEL") DEFERRABLE INITIALLY DEFERRED
  USING INDEX  ENABLE;
