--------------------------------------------------------
--  Constraints for Table XV_REPORT_PRT_COL_DATA
--------------------------------------------------------

  ALTER TABLE "XVIEWMGR"."XV_REPORT_PRT_COL_DATA" MODIFY ("COLUMN_NAME" CONSTRAINT "XV_REPORT_PRT_COL_NN_CK3" NOT NULL ENABLE);
  ALTER TABLE "XVIEWMGR"."XV_REPORT_PRT_COL_DATA" MODIFY ("PART_LABEL" CONSTRAINT "XV_REPORT_PRT_COL_NN_CK2" NOT NULL ENABLE);
  ALTER TABLE "XVIEWMGR"."XV_REPORT_PRT_COL_DATA" MODIFY ("DOMAIN" CONSTRAINT "XV_REPORT_PRT_COL_NN_CK1" NOT NULL ENABLE);
  ALTER TABLE "XVIEWMGR"."XV_REPORT_PRT_COL_DATA" ADD CONSTRAINT "XV_REPORT_PRT_COL_UK1001" UNIQUE ("DOMAIN", "PART_LABEL", "COLUMN_NAME") DEFERRABLE INITIALLY DEFERRED
  USING INDEX  ENABLE;
