--------------------------------------------------------
--  Constraints for Table XV_REVIEW_BAT_DETS_DATA
--------------------------------------------------------

  ALTER TABLE "SAVEMGR"."XV_REVIEW_BAT_DETS_DATA" MODIFY ("CREATED_BY_WUA_ID" NOT NULL ENABLE);
  ALTER TABLE "SAVEMGR"."XV_REVIEW_BAT_DETS_DATA" MODIFY ("START_DATETIME" NOT NULL ENABLE);
  ALTER TABLE "SAVEMGR"."XV_REVIEW_BAT_DETS_DATA" MODIFY ("RB_ID" NOT NULL ENABLE);
  ALTER TABLE "SAVEMGR"."XV_REVIEW_BAT_DETS_DATA" MODIFY ("RBD_ID" NOT NULL ENABLE);
