--------------------------------------------------------
--  Constraints for Table XV_RESOURCE_TYPES_DATA
--------------------------------------------------------

  ALTER TABLE "XVIEWMGR"."XV_RESOURCE_TYPES_DATA" MODIFY ("RES_TYPE" CONSTRAINT "XV_RESOURCE_TYPES_NN_CK1" NOT NULL ENABLE);
  ALTER TABLE "XVIEWMGR"."XV_RESOURCE_TYPES_DATA" ADD CONSTRAINT "XV_RESOURCE_TYPES_UK1001" UNIQUE ("RES_TYPE_TITLE") DEFERRABLE INITIALLY DEFERRED
  USING INDEX  ENABLE;
  ALTER TABLE "XVIEWMGR"."XV_RESOURCE_TYPES_DATA" ADD CONSTRAINT "XV_RESOURCE_TYPES_PK" PRIMARY KEY ("RES_TYPE") DEFERRABLE INITIALLY DEFERRED
  USING INDEX  ENABLE;
