--------------------------------------------------------
--  Constraints for Table XV_RES_PEOPLE_DATA
--------------------------------------------------------

  ALTER TABLE "XVIEWMGR"."XV_RES_PEOPLE_DATA" MODIFY ("SURNAME" CONSTRAINT "XV_RES_PEOPLE_NN_CK8" NOT NULL ENABLE);
  ALTER TABLE "XVIEWMGR"."XV_RES_PEOPLE_DATA" MODIFY ("FULL_NAME" CONSTRAINT "XV_RES_PEOPLE_NN_CK5" NOT NULL ENABLE);
  ALTER TABLE "XVIEWMGR"."XV_RES_PEOPLE_DATA" MODIFY ("STATUS" CONSTRAINT "XV_RES_PEOPLE_NN_CK4" NOT NULL ENABLE);
  ALTER TABLE "XVIEWMGR"."XV_RES_PEOPLE_DATA" MODIFY ("RP_ID" CONSTRAINT "XV_RES_PEOPLE_NN_CK2" NOT NULL ENABLE);
  ALTER TABLE "XVIEWMGR"."XV_RES_PEOPLE_DATA" MODIFY ("RPD_ID" CONSTRAINT "XV_RES_PEOPLE_NN_CK1" NOT NULL ENABLE);
