--------------------------------------------------------
--  Constraints for Table XV_RES_TYPE_ROLES_DATA
--------------------------------------------------------

  ALTER TABLE "XVIEWMGR"."XV_RES_TYPE_ROLES_DATA" MODIFY ("NOTIFICATION_METHOD_REQUIRED" CONSTRAINT "XV_RES_TYPE_ROLES_NN_CK17" NOT NULL ENABLE);
  ALTER TABLE "XVIEWMGR"."XV_RES_TYPE_ROLES_DATA" MODIFY ("AUTHORISATION_REQUIRED" CONSTRAINT "XV_RES_TYPE_ROLES_NN_CK16" NOT NULL ENABLE);
  ALTER TABLE "XVIEWMGR"."XV_RES_TYPE_ROLES_DATA" MODIFY ("BRANCH_REQUIRED" CONSTRAINT "XV_RES_TYPE_ROLES_NN_CK15" NOT NULL ENABLE);
  ALTER TABLE "XVIEWMGR"."XV_RES_TYPE_ROLES_DATA" MODIFY ("QUALIFYING_COMMENT_REQUIRED" CONSTRAINT "XV_RES_TYPE_ROLES_NN_CK14" NOT NULL ENABLE);
  ALTER TABLE "XVIEWMGR"."XV_RES_TYPE_ROLES_DATA" MODIFY ("EMAIL_REQUIRED" CONSTRAINT "XV_RES_TYPE_ROLES_NN_CK13" NOT NULL ENABLE);
  ALTER TABLE "XVIEWMGR"."XV_RES_TYPE_ROLES_DATA" MODIFY ("TELEPHONE_REQUIRED" CONSTRAINT "XV_RES_TYPE_ROLES_NN_CK12" NOT NULL ENABLE);
  ALTER TABLE "XVIEWMGR"."XV_RES_TYPE_ROLES_DATA" MODIFY ("ADDRESS_REQUIRED" CONSTRAINT "XV_RES_TYPE_ROLES_NN_CK11" NOT NULL ENABLE);
  ALTER TABLE "XVIEWMGR"."XV_RES_TYPE_ROLES_DATA" MODIFY ("PERSON_REQUIRES_ACTIVE_WUA" CONSTRAINT "XV_RES_TYPE_ROLES_NN_CK10" NOT NULL ENABLE);
  ALTER TABLE "XVIEWMGR"."XV_RES_TYPE_ROLES_DATA" MODIFY ("PERSON_REQUIRED" CONSTRAINT "XV_RES_TYPE_ROLES_NN_CK9" NOT NULL ENABLE);
  ALTER TABLE "XVIEWMGR"."XV_RES_TYPE_ROLES_DATA" MODIFY ("DISPLAY_SEQ" CONSTRAINT "XV_RES_TYPE_ROLES_NN_CK8" NOT NULL ENABLE);
  ALTER TABLE "XVIEWMGR"."XV_RES_TYPE_ROLES_DATA" MODIFY ("MAX_MEMS" CONSTRAINT "XV_RES_TYPE_ROLES_NN_CK7" NOT NULL ENABLE);
  ALTER TABLE "XVIEWMGR"."XV_RES_TYPE_ROLES_DATA" MODIFY ("MIN_MEMS" CONSTRAINT "XV_RES_TYPE_ROLES_NN_CK6" NOT NULL ENABLE);
  ALTER TABLE "XVIEWMGR"."XV_RES_TYPE_ROLES_DATA" MODIFY ("ROLE_DESCRIPTION" CONSTRAINT "XV_RES_TYPE_ROLES_NN_CK5" NOT NULL ENABLE);
  ALTER TABLE "XVIEWMGR"."XV_RES_TYPE_ROLES_DATA" MODIFY ("ROLE_TITLE" CONSTRAINT "XV_RES_TYPE_ROLES_NN_CK4" NOT NULL ENABLE);
  ALTER TABLE "XVIEWMGR"."XV_RES_TYPE_ROLES_DATA" MODIFY ("ROLE_NAME" CONSTRAINT "XV_RES_TYPE_ROLES_NN_CK2" NOT NULL ENABLE);
  ALTER TABLE "XVIEWMGR"."XV_RES_TYPE_ROLES_DATA" MODIFY ("RES_TYPE" CONSTRAINT "XV_RES_TYPE_ROLES_NN_CK1" NOT NULL ENABLE);
  ALTER TABLE "XVIEWMGR"."XV_RES_TYPE_ROLES_DATA" ADD CONSTRAINT "XV_RES_TYPE_ROLES_UK1001" UNIQUE ("RES_TYPE", "DISPLAY_SEQ")
  USING INDEX  ENABLE;
  ALTER TABLE "XVIEWMGR"."XV_RES_TYPE_ROLES_DATA" ADD CONSTRAINT "XV_RES_TYPE_ROLES_PK" PRIMARY KEY ("RES_TYPE", "ROLE_NAME")
  USING INDEX  ENABLE;
