--------------------------------------------------------
--  Constraints for Table XV_RES_TYPE_PRIVS_DATA
--------------------------------------------------------

  ALTER TABLE "XVIEWMGR"."XV_RES_TYPE_PRIVS_DATA" MODIFY ("DEFAULT_SYSTEM_PRIV" CONSTRAINT "XV_RES_TYPE_PRIVS_NN_CK3" NOT NULL ENABLE);
  ALTER TABLE "XVIEWMGR"."XV_RES_TYPE_PRIVS_DATA" MODIFY ("ROLE_NAME" CONSTRAINT "XV_RES_TYPE_PRIVS_NN_CK2" NOT NULL ENABLE);
  ALTER TABLE "XVIEWMGR"."XV_RES_TYPE_PRIVS_DATA" MODIFY ("RES_TYPE" CONSTRAINT "XV_RES_TYPE_PRIVS_NN_CK1" NOT NULL ENABLE);
  ALTER TABLE "XVIEWMGR"."XV_RES_TYPE_PRIVS_DATA" ADD CONSTRAINT "XV_RES_TYPE_PRIVS_PK" PRIMARY KEY ("RES_TYPE", "ROLE_NAME", "DEFAULT_SYSTEM_PRIV") DEFERRABLE INITIALLY DEFERRED
  USING INDEX  ENABLE;
