--------------------------------------------------------
--  Constraints for Table XV_REVIEW_TYPES_DATA
--------------------------------------------------------

  ALTER TABLE "XVIEWMGR"."XV_REVIEW_TYPES_DATA" MODIFY ("ALLOW_SLOT_DOCUMENT_UPLOAD" CONSTRAINT "XV_REVIEW_TYPES_NN_CK33" NOT NULL ENABLE);
  ALTER TABLE "XVIEWMGR"."XV_REVIEW_TYPES_DATA" MODIFY ("ENABLE_PRIVATE_COMMENTS" CONSTRAINT "XV_REVIEW_TYPES_NN_CK32" NOT NULL ENABLE);
  ALTER TABLE "XVIEWMGR"."XV_REVIEW_TYPES_DATA" MODIFY ("REVIEW_TYPE" CONSTRAINT "XV_REVIEW_TYPES_NN_CK3" NOT NULL ENABLE);
  ALTER TABLE "XVIEWMGR"."XV_REVIEW_TYPES_DATA" MODIFY ("ADVICE_TYPE" CONSTRAINT "XV_REVIEW_TYPES_NN_CK1" NOT NULL ENABLE);
  ALTER TABLE "XVIEWMGR"."XV_REVIEW_TYPES_DATA" ADD CONSTRAINT "XV_REVIEW_TYPES_PK" PRIMARY KEY ("ADVICE_TYPE", "REVIEW_TYPE") DEFERRABLE INITIALLY DEFERRED
  USING INDEX  ENABLE;
