--------------------------------------------------------
--  Constraints for Table XV_RES_MEMBER_HIST_DATA
--------------------------------------------------------

  ALTER TABLE "XVIEWMGR"."XV_RES_MEMBER_HIST_DATA" MODIFY ("START_DATE" CONSTRAINT "XV_RES_MEMBER_HIST_NN_CK9" NOT NULL ENABLE);
  ALTER TABLE "XVIEWMGR"."XV_RES_MEMBER_HIST_DATA" MODIFY ("STATUS" CONSTRAINT "XV_RES_MEMBER_HIST_NN_CK8" NOT NULL ENABLE);
  ALTER TABLE "XVIEWMGR"."XV_RES_MEMBER_HIST_DATA" MODIFY ("MEMBER_ID" CONSTRAINT "XV_RES_MEMBER_HIST_NN_CK6" NOT NULL ENABLE);
  ALTER TABLE "XVIEWMGR"."XV_RES_MEMBER_HIST_DATA" MODIFY ("ROLE_NAME" CONSTRAINT "XV_RES_MEMBER_HIST_NN_CK5" NOT NULL ENABLE);
  ALTER TABLE "XVIEWMGR"."XV_RES_MEMBER_HIST_DATA" MODIFY ("RES_TYPE" CONSTRAINT "XV_RES_MEMBER_HIST_NN_CK4" NOT NULL ENABLE);
  ALTER TABLE "XVIEWMGR"."XV_RES_MEMBER_HIST_DATA" MODIFY ("RR_ID" CONSTRAINT "XV_RES_MEMBER_HIST_NN_CK3" NOT NULL ENABLE);
  ALTER TABLE "XVIEWMGR"."XV_RES_MEMBER_HIST_DATA" MODIFY ("RES_ID" CONSTRAINT "XV_RES_MEMBER_HIST_NN_CK2" NOT NULL ENABLE);
  ALTER TABLE "XVIEWMGR"."XV_RES_MEMBER_HIST_DATA" MODIFY ("RD_ID" CONSTRAINT "XV_RES_MEMBER_HIST_NN_CK1" NOT NULL ENABLE);
  ALTER TABLE "XVIEWMGR"."XV_RES_MEMBER_HIST_DATA" ADD CONSTRAINT "XV_RES_MEMBER_HIST_UK1001" UNIQUE ("MEMBER_ID", "RES_ID", "END_DATE") DEFERRABLE INITIALLY DEFERRED
  USING INDEX  ENABLE;
