--------------------------------------------------------
--  Constraints for Table XV_REVIEW_ADV_DETS_DATA
--------------------------------------------------------

  ALTER TABLE "SAVEMGR"."XV_REVIEW_ADV_DETS_DATA" MODIFY ("CREATED_BY_WUA_ID" NOT NULL ENABLE);
  ALTER TABLE "SAVEMGR"."XV_REVIEW_ADV_DETS_DATA" MODIFY ("START_DATETIME" NOT NULL ENABLE);
  ALTER TABLE "SAVEMGR"."XV_REVIEW_ADV_DETS_DATA" MODIFY ("RA_ID" NOT NULL ENABLE);
  ALTER TABLE "SAVEMGR"."XV_REVIEW_ADV_DETS_DATA" MODIFY ("RAD_ID" NOT NULL ENABLE);
