--------------------------------------------------------
--  Constraints for Table XV_RES_PEOPLE_TELS_DATA
--------------------------------------------------------

  ALTER TABLE "XVIEWMGR"."XV_RES_PEOPLE_TELS_DATA" MODIFY ("STATUS" CONSTRAINT "XV_RES_PEOPLE_TELS_NN_CK4" NOT NULL ENABLE);
  ALTER TABLE "XVIEWMGR"."XV_RES_PEOPLE_TELS_DATA" MODIFY ("RP_ID" CONSTRAINT "XV_RES_PEOPLE_TELS_NN_CK2" NOT NULL ENABLE);
  ALTER TABLE "XVIEWMGR"."XV_RES_PEOPLE_TELS_DATA" MODIFY ("RPD_ID" CONSTRAINT "XV_RES_PEOPLE_TELS_NN_CK1" NOT NULL ENABLE);
