--------------------------------------------------------
--  Constraints for Table XV_RES_ADVICE_TYPS_DATA
--------------------------------------------------------

  ALTER TABLE "XVIEWMGR"."XV_RES_ADVICE_TYPS_DATA" MODIFY ("REVIEW_TYPE_TITLE" CONSTRAINT "XV_RES_ADVICE_TYPS_NN_CK3" NOT NULL ENABLE);
  ALTER TABLE "XVIEWMGR"."XV_RES_ADVICE_TYPS_DATA" MODIFY ("REVIEW_TYPE" CONSTRAINT "XV_RES_ADVICE_TYPS_NN_CK2" NOT NULL ENABLE);
  ALTER TABLE "XVIEWMGR"."XV_RES_ADVICE_TYPS_DATA" MODIFY ("ADVICE_TYPE" CONSTRAINT "XV_RES_ADVICE_TYPS_NN_CK1" NOT NULL ENABLE);
  ALTER TABLE "XVIEWMGR"."XV_RES_ADVICE_TYPS_DATA" ADD CONSTRAINT "XV_RES_ADVICE_TYPS_PK" PRIMARY KEY ("ADVICE_TYPE", "REVIEW_TYPE", "RESPONSE_DATA") DEFERRABLE INITIALLY DEFERRED
  USING INDEX  ENABLE;
  ALTER TABLE "XVIEWMGR"."XV_RES_ADVICE_TYPS_DATA" MODIFY ("RESPONSE_LONG_KEY" CONSTRAINT "XV_RES_ADVICE_TYPS_NN_CK5" NOT NULL ENABLE);
  ALTER TABLE "XVIEWMGR"."XV_RES_ADVICE_TYPS_DATA" MODIFY ("RESPONSE_DATA" CONSTRAINT "XV_RES_ADVICE_TYPS_NN_CK4" NOT NULL ENABLE);
