--------------------------------------------------------
--  Constraints for Table XV_REVIEW_BAT_DETS_DATA
--------------------------------------------------------

  ALTER TABLE "XVIEWMGR"."XV_REVIEW_BAT_DETS_DATA" MODIFY ("CREATED_BY_WUA_ID" CONSTRAINT "XV_REVIEW_BAT_DETS_NN_CK6" NOT NULL ENABLE);
  ALTER TABLE "XVIEWMGR"."XV_REVIEW_BAT_DETS_DATA" MODIFY ("START_DATETIME" CONSTRAINT "XV_REVIEW_BAT_DETS_NN_CK3" NOT NULL ENABLE);
  ALTER TABLE "XVIEWMGR"."XV_REVIEW_BAT_DETS_DATA" MODIFY ("RB_ID" CONSTRAINT "XV_REVIEW_BAT_DETS_NN_CK2" NOT NULL ENABLE);
  ALTER TABLE "XVIEWMGR"."XV_REVIEW_BAT_DETS_DATA" MODIFY ("RBD_ID" CONSTRAINT "XV_REVIEW_BAT_DETS_NN_CK1" NOT NULL ENABLE);
  ALTER TABLE "XVIEWMGR"."XV_REVIEW_BAT_DETS_DATA" ADD CONSTRAINT "XV_REVIEW_BAT_DETS_PK" PRIMARY KEY ("RBD_ID") DEFERRABLE INITIALLY DEFERRED
  USING INDEX  ENABLE;
