--------------------------------------------------------
--  Constraints for Table XV_SDB_EXTAPP_DATA
--------------------------------------------------------

  ALTER TABLE "XVIEWMGR"."XV_SDB_EXTAPP_DATA" MODIFY ("ID" CONSTRAINT "XV_SDB_EXTAPP_NN_CK1" NOT NULL ENABLE);
  ALTER TABLE "XVIEWMGR"."XV_SDB_EXTAPP_DATA" ADD CONSTRAINT "XV_SDB_EXTAPP_UK1001" UNIQUE ("APPLICATION_REF") DEFERRABLE INITIALLY DEFERRED
  USING INDEX  ENABLE;
  ALTER TABLE "XVIEWMGR"."XV_SDB_EXTAPP_DATA" ADD CONSTRAINT "XV_SDB_EXTAPP_PK" PRIMARY KEY ("ID") DEFERRABLE INITIALLY DEFERRED
  USING INDEX  ENABLE;
