--------------------------------------------------------
--  Constraints for Table XV_SDB_EXTAPP_R_DATA
--------------------------------------------------------

  ALTER TABLE "XVIEWMGR"."XV_SDB_EXTAPP_R_DATA" MODIFY ("GI_ID" CONSTRAINT "XV_SDB_EXTAPP_R_NN_CK3" NOT NULL ENABLE);
  ALTER TABLE "XVIEWMGR"."XV_SDB_EXTAPP_R_DATA" MODIFY ("INC_ID" CONSTRAINT "XV_SDB_EXTAPP_R_NN_CK2" NOT NULL ENABLE);
  ALTER TABLE "XVIEWMGR"."XV_SDB_EXTAPP_R_DATA" MODIFY ("ID" CONSTRAINT "XV_SDB_EXTAPP_R_NN_CK1" NOT NULL ENABLE);
