--------------------------------------------------------
--  Constraints for Table XV_SDB_EXTAPP_GL_DATA
--------------------------------------------------------

  ALTER TABLE "XVIEWMGR"."XV_SDB_EXTAPP_GL_DATA" MODIFY ("GI_ID" CONSTRAINT "XV_SDB_EXTAPP_GL_NN_CK3" NOT NULL ENABLE);
  ALTER TABLE "XVIEWMGR"."XV_SDB_EXTAPP_GL_DATA" MODIFY ("INC_ID" CONSTRAINT "XV_SDB_EXTAPP_GL_NN_CK2" NOT NULL ENABLE);
  ALTER TABLE "XVIEWMGR"."XV_SDB_EXTAPP_GL_DATA" MODIFY ("ID" CONSTRAINT "XV_SDB_EXTAPP_GL_NN_CK1" NOT NULL ENABLE);
  ALTER TABLE "XVIEWMGR"."XV_SDB_EXTAPP_GL_DATA" ADD CONSTRAINT "XV_SDB_EXTAPP_GL_PK" PRIMARY KEY ("ID", "INC_ID", "GI_ID") DEFERRABLE INITIALLY DEFERRED
  USING INDEX  ENABLE;
