--------------------------------------------------------
--  Constraints for Table XV_TPL_CLAUSE_DTLS_DATA
--------------------------------------------------------

  ALTER TABLE "XVIEWMGR"."XV_TPL_CLAUSE_DTLS_DATA" MODIFY ("CLAUSE_TYPE_ID" CONSTRAINT "XV_TPL_CLAUSE_DTLS_NN_CK3" NOT NULL ENABLE);
  ALTER TABLE "XVIEWMGR"."XV_TPL_CLAUSE_DTLS_DATA" MODIFY ("TC_ID" CONSTRAINT "XV_TPL_CLAUSE_DTLS_NN_CK2" NOT NULL ENABLE);
  ALTER TABLE "XVIEWMGR"."XV_TPL_CLAUSE_DTLS_DATA" MODIFY ("TCD_ID" CONSTRAINT "XV_TPL_CLAUSE_DTLS_NN_CK1" NOT NULL ENABLE);
