--------------------------------------------------------
--  Constraints for Table XV_TS_ET_MNEMS_DATA
--------------------------------------------------------

  ALTER TABLE "XVIEWMGR"."XV_TS_ET_MNEMS_DATA" MODIFY ("EMAIL_TYPE_MNEM" CONSTRAINT "XV_TS_ET_MNEMS_NN_CK2" NOT NULL ENABLE);
  ALTER TABLE "XVIEWMGR"."XV_TS_ET_MNEMS_DATA" MODIFY ("MAIL_ID" CONSTRAINT "XV_TS_ET_MNEMS_NN_CK1" NOT NULL ENABLE);
  ALTER TABLE "XVIEWMGR"."XV_TS_ET_MNEMS_DATA" ADD CONSTRAINT "XV_TS_ET_MNEMS_PK" PRIMARY KEY ("MAIL_ID", "EMAIL_TYPE_MNEM") DEFERRABLE INITIALLY DEFERRED
  USING INDEX  ENABLE;
