--------------------------------------------------------
--  Constraints for Table XV_TALLY_TYPE_ADJS_DATA
--------------------------------------------------------

  ALTER TABLE "XVIEWMGR"."XV_TALLY_TYPE_ADJS_DATA" MODIFY ("ADJUSTMENT" CONSTRAINT "XV_TALLY_TYPE_ADJS_NN_CK2" NOT NULL ENABLE);
  ALTER TABLE "XVIEWMGR"."XV_TALLY_TYPE_ADJS_DATA" MODIFY ("TALLY_TYPE" CONSTRAINT "XV_TALLY_TYPE_ADJS_NN_CK1" NOT NULL ENABLE);
  ALTER TABLE "XVIEWMGR"."XV_TALLY_TYPE_ADJS_DATA" ADD CONSTRAINT "XV_TALLY_TYPE_ADJS_UK1001" UNIQUE ("TALLY_TYPE", "ADJUSTMENT")
  USING INDEX  ENABLE;
