--------------------------------------------------------
--  Constraints for Table XV_TWEEK_PLAN_DETS_DATA
--------------------------------------------------------

  ALTER TABLE "XVIEWMGR"."XV_TWEEK_PLAN_DETS_DATA" MODIFY ("SWITCH" CONSTRAINT "XV_TWEEK_PLAN_DETS_NN_CK7" NOT NULL ENABLE);
  ALTER TABLE "XVIEWMGR"."XV_TWEEK_PLAN_DETS_DATA" MODIFY ("END_TIME" CONSTRAINT "XV_TWEEK_PLAN_DETS_NN_CK6" NOT NULL ENABLE);
  ALTER TABLE "XVIEWMGR"."XV_TWEEK_PLAN_DETS_DATA" MODIFY ("START_TIME" CONSTRAINT "XV_TWEEK_PLAN_DETS_NN_CK5" NOT NULL ENABLE);
  ALTER TABLE "XVIEWMGR"."XV_TWEEK_PLAN_DETS_DATA" MODIFY ("DAY" CONSTRAINT "XV_TWEEK_PLAN_DETS_NN_CK4" NOT NULL ENABLE);
  ALTER TABLE "XVIEWMGR"."XV_TWEEK_PLAN_DETS_DATA" MODIFY ("START_DATE" CONSTRAINT "XV_TWEEK_PLAN_DETS_NN_CK3" NOT NULL ENABLE);
  ALTER TABLE "XVIEWMGR"."XV_TWEEK_PLAN_DETS_DATA" MODIFY ("TWP_ID" CONSTRAINT "XV_TWEEK_PLAN_DETS_NN_CK2" NOT NULL ENABLE);
  ALTER TABLE "XVIEWMGR"."XV_TWEEK_PLAN_DETS_DATA" MODIFY ("TWP_DETAIL_ID" CONSTRAINT "XV_TWEEK_PLAN_DETS_NN_CK1" NOT NULL ENABLE);
  ALTER TABLE "XVIEWMGR"."XV_TWEEK_PLAN_DETS_DATA" ADD CONSTRAINT "XV_TWEEK_PLAN_DETS_UK1001" UNIQUE ("TWP_ID", "START_DATE", "DAY", "START_TIME")
  USING INDEX  ENABLE;
  ALTER TABLE "XVIEWMGR"."XV_TWEEK_PLAN_DETS_DATA" ADD CONSTRAINT "XV_TWEEK_PLAN_DETS_PK" PRIMARY KEY ("TWP_DETAIL_ID", "DAY", "START_TIME")
  USING INDEX  ENABLE;
