--------------------------------------------------------
--  Constraints for Table XV_TALLY_TYPE_WP_DATA
--------------------------------------------------------

  ALTER TABLE "XVIEWMGR"."XV_TALLY_TYPE_WP_DATA" MODIFY ("WEEK_PLAN" CONSTRAINT "XV_TALLY_TYPE_WP_NN_CK2" NOT NULL ENABLE);
  ALTER TABLE "XVIEWMGR"."XV_TALLY_TYPE_WP_DATA" MODIFY ("TALLY_TYPE" CONSTRAINT "XV_TALLY_TYPE_WP_NN_CK1" NOT NULL ENABLE);
  ALTER TABLE "XVIEWMGR"."XV_TALLY_TYPE_WP_DATA" ADD CONSTRAINT "XV_TALLY_TYPE_WP_PK" PRIMARY KEY ("TALLY_TYPE")
  USING INDEX  ENABLE;
