--------------------------------------------------------
--  Constraints for Table XV_WP_SECURITY_DATA
--------------------------------------------------------

  ALTER TABLE "XVIEWMGR"."XV_WP_SECURITY_DATA" MODIFY ("CATEGORY_NAME" CONSTRAINT "XV_WP_SECURITY_NN_CK1" NOT NULL ENABLE);
  ALTER TABLE "XVIEWMGR"."XV_WP_SECURITY_DATA" ADD CONSTRAINT "XV_WP_SECURITY_UK1001" UNIQUE ("CATEGORY_NAME", "RESOURCE_TYPE", "RESOURCE_ROLE_LIKE", "SYSTEM_PRIV")
  USING INDEX  ENABLE;
