--------------------------------------------------------
--  Constraints for Table XV_WP_DETAILS_DATA
--------------------------------------------------------

  ALTER TABLE "XVIEWMGR"."XV_WP_DETAILS_DATA" MODIFY ("PREFERENCE_NAME" CONSTRAINT "XV_WP_DETAILS_NN_CK8" NOT NULL ENABLE);
  ALTER TABLE "XVIEWMGR"."XV_WP_DETAILS_DATA" MODIFY ("CATEGORY_NAME" CONSTRAINT "XV_WP_DETAILS_NN_CK7" NOT NULL ENABLE);
  ALTER TABLE "XVIEWMGR"."XV_WP_DETAILS_DATA" MODIFY ("CHANGE_NUMBER" CONSTRAINT "XV_WP_DETAILS_NN_CK6" NOT NULL ENABLE);
  ALTER TABLE "XVIEWMGR"."XV_WP_DETAILS_DATA" MODIFY ("START_DATE" CONSTRAINT "XV_WP_DETAILS_NN_CK4" NOT NULL ENABLE);
  ALTER TABLE "XVIEWMGR"."XV_WP_DETAILS_DATA" MODIFY ("WUA_ID" CONSTRAINT "XV_WP_DETAILS_NN_CK2" NOT NULL ENABLE);
  ALTER TABLE "XVIEWMGR"."XV_WP_DETAILS_DATA" MODIFY ("WPD_ID" CONSTRAINT "XV_WP_DETAILS_NN_CK1" NOT NULL ENABLE);
  ALTER TABLE "XVIEWMGR"."XV_WP_DETAILS_DATA" ADD CONSTRAINT "XV_WP_DETAILS_PK" PRIMARY KEY ("WPD_ID", "CATEGORY_NAME", "PREFERENCE_NAME") DEFERRABLE INITIALLY DEFERRED
  USING INDEX  ENABLE;
