--------------------------------------------------------
--  Constraints for Table XVIEW_DEFINITIONS
--------------------------------------------------------

  ALTER TABLE "XVIEWMGR"."XVIEW_DEFINITIONS" ADD CONSTRAINT "XVIEW_DEFINITIONS_UK2" UNIQUE ("INTERNAL_TABLE_NAME")
  USING INDEX  ENABLE;
  ALTER TABLE "XVIEWMGR"."XVIEW_DEFINITIONS" ADD CONSTRAINT "XVIEW_DEFINITIONS_UK1" UNIQUE ("XVIEW_NAME", "XVIEW_OWNER")
  USING INDEX  ENABLE;
  ALTER TABLE "XVIEWMGR"."XVIEW_DEFINITIONS" ADD CONSTRAINT "PK_XVIEW_DEFINITIONS" PRIMARY KEY ("XVIEW_ID")
  USING INDEX  ENABLE;
  ALTER TABLE "XVIEWMGR"."XVIEW_DEFINITIONS" MODIFY ("XVIEW_ID" NOT NULL ENABLE);
  ALTER TABLE "XVIEWMGR"."XVIEW_DEFINITIONS" MODIFY ("XVIEW_STATEMENT" NOT NULL ENABLE);
  ALTER TABLE "XVIEWMGR"."XVIEW_DEFINITIONS" MODIFY ("XVIEW_KEY_COLUMN_1" NOT NULL ENABLE);
  ALTER TABLE "XVIEWMGR"."XVIEW_DEFINITIONS" MODIFY ("BASETABLE_STATEMENT" NOT NULL ENABLE);
  ALTER TABLE "XVIEWMGR"."XVIEW_DEFINITIONS" MODIFY ("BASETABLE_KEY_COLUMN_1" NOT NULL ENABLE);
  ALTER TABLE "XVIEWMGR"."XVIEW_DEFINITIONS" MODIFY ("BASETABLE_NAME" NOT NULL ENABLE);
  ALTER TABLE "XVIEWMGR"."XVIEW_DEFINITIONS" MODIFY ("BASETABLE_OWNER" NOT NULL ENABLE);
  ALTER TABLE "XVIEWMGR"."XVIEW_DEFINITIONS" MODIFY ("DATA_TABLESPACE" NOT NULL ENABLE);
  ALTER TABLE "XVIEWMGR"."XVIEW_DEFINITIONS" MODIFY ("INTERNAL_TABLE_NAME" NOT NULL ENABLE);
  ALTER TABLE "XVIEWMGR"."XVIEW_DEFINITIONS" MODIFY ("LAST_STATUS" NOT NULL ENABLE);
  ALTER TABLE "XVIEWMGR"."XVIEW_DEFINITIONS" MODIFY ("PROCESS_HOW" NOT NULL ENABLE);
  ALTER TABLE "XVIEWMGR"."XVIEW_DEFINITIONS" MODIFY ("PROCESS_KEYS" NOT NULL ENABLE);
  ALTER TABLE "XVIEWMGR"."XVIEW_DEFINITIONS" MODIFY ("PROCESS_WHEN" NOT NULL ENABLE);
  ALTER TABLE "XVIEWMGR"."XVIEW_DEFINITIONS" MODIFY ("XVIEW_NAME" NOT NULL ENABLE);
  ALTER TABLE "XVIEWMGR"."XVIEW_DEFINITIONS" MODIFY ("XVIEW_OWNER" NOT NULL ENABLE);
  ALTER TABLE "XVIEWMGR"."XVIEW_DEFINITIONS" ADD CONSTRAINT "XVIEW_DEF_PROCESS_HOW_CK3" CHECK (
    PROCESS_HOW IN ('FULLREPLACE','MERGE DIFFS', 'REPLACE')
    ) ENABLE;
  ALTER TABLE "XVIEWMGR"."XVIEW_DEFINITIONS" ADD CONSTRAINT "XVIEW_DEF_PROCESS_KEYS_CK2" CHECK (
    PROCESS_KEYS IN ('IN KEY TABLE','IN MEMORY')
    ) ENABLE;
  ALTER TABLE "XVIEWMGR"."XVIEW_DEFINITIONS" ADD CONSTRAINT "XVIEW_DEF_PROCESS_WHEN_CK1" CHECK (
    PROCESS_WHEN IN ('AFTER BATCH','AFTER TRANSACTION', 'IN TRANSACTION')
    ) ENABLE;
