--------------------------------------------------------
--  Constraints for Table XVIEW_FOREIGN_KEY_CONSTRAINTS
--------------------------------------------------------

  ALTER TABLE "XVIEWMGR"."XVIEW_FOREIGN_KEY_CONSTRAINTS" ADD CONSTRAINT "XVIEW_FOREIGN_KEY_CONS_PK" PRIMARY KEY ("SEQ", "XVIEW_NAME", "XVIEW_OWNER")
  USING INDEX  ENABLE;
  ALTER TABLE "XVIEWMGR"."XVIEW_FOREIGN_KEY_CONSTRAINTS" ADD CONSTRAINT "XVIEW_FOREIGN_KEY_CONS_CK3" CHECK (DFR IS NULL OR DFR='Y') ENABLE;
  ALTER TABLE "XVIEWMGR"."XVIEW_FOREIGN_KEY_CONSTRAINTS" ADD CONSTRAINT "XVIEW_FOREIGN_KEY_CONS_CK2" CHECK (STATUS IN ('ENABLED','DISABLED', 'VOIDED')) ENABLE;
  ALTER TABLE "XVIEWMGR"."XVIEW_FOREIGN_KEY_CONSTRAINTS" ADD CONSTRAINT "XVIEW_FOREIGN_KEY_CONS_CK1" CHECK (
CONSTRAINED_TABLE_OWNER||'.'||CONSTRAINED_TABLE_NAME = XVIEW_OWNER||'.'||XVIEW_NAME OR 
(CONSTRAINED_TABLE_OWNER||'.'||CONSTRAINED_TABLE_NAME != XVIEW_OWNER||'.'||XVIEW_NAME AND REFERENCED_TABLE_OWNER||'.'||REFERENCED_TABLE_NAME = XVIEW_OWNER||'.'||XVIEW_NAME)
 ) ENABLE;
  ALTER TABLE "XVIEWMGR"."XVIEW_FOREIGN_KEY_CONSTRAINTS" MODIFY ("REFERENCED_TABLE_COLUMN_LIST" NOT NULL ENABLE);
  ALTER TABLE "XVIEWMGR"."XVIEW_FOREIGN_KEY_CONSTRAINTS" MODIFY ("REFERENCED_TABLE_NAME" NOT NULL ENABLE);
  ALTER TABLE "XVIEWMGR"."XVIEW_FOREIGN_KEY_CONSTRAINTS" MODIFY ("REFERENCED_TABLE_OWNER" NOT NULL ENABLE);
  ALTER TABLE "XVIEWMGR"."XVIEW_FOREIGN_KEY_CONSTRAINTS" MODIFY ("CONSTRAINED_TABLE_COLUMN_LIST" NOT NULL ENABLE);
  ALTER TABLE "XVIEWMGR"."XVIEW_FOREIGN_KEY_CONSTRAINTS" MODIFY ("CONSTRAINED_TABLE_NAME" NOT NULL ENABLE);
  ALTER TABLE "XVIEWMGR"."XVIEW_FOREIGN_KEY_CONSTRAINTS" MODIFY ("CONSTRAINED_TABLE_OWNER" NOT NULL ENABLE);
  ALTER TABLE "XVIEWMGR"."XVIEW_FOREIGN_KEY_CONSTRAINTS" MODIFY ("STATUS" NOT NULL ENABLE);
  ALTER TABLE "XVIEWMGR"."XVIEW_FOREIGN_KEY_CONSTRAINTS" MODIFY ("SEQ" NOT NULL ENABLE);
  ALTER TABLE "XVIEWMGR"."XVIEW_FOREIGN_KEY_CONSTRAINTS" MODIFY ("XVIEW_NAME" NOT NULL ENABLE);
  ALTER TABLE "XVIEWMGR"."XVIEW_FOREIGN_KEY_CONSTRAINTS" MODIFY ("XVIEW_OWNER" NOT NULL ENABLE);
