--------------------------------------------------------
--  Constraints for Table XVIEW_CHECK_CONSTRAINTS
--------------------------------------------------------

  ALTER TABLE "XVIEWMGR"."XVIEW_CHECK_CONSTRAINTS" ADD CONSTRAINT "XVIEW_CHECK_KEY_CONS_PK" PRIMARY KEY ("SEQ", "XVIEW_NAME", "XVIEW_OWNER")
  USING INDEX  ENABLE;
  ALTER TABLE "XVIEWMGR"."XVIEW_CHECK_CONSTRAINTS" ADD CONSTRAINT "XVIEW_CHECK_KEY_CONS_CK2" CHECK (DFR IS NULL OR DFR='Y') ENABLE;
  ALTER TABLE "XVIEWMGR"."XVIEW_CHECK_CONSTRAINTS" ADD CONSTRAINT "XVIEW_CHECK_KEY_CONS_CK1" CHECK (STATUS IN ('ENABLED','DISABLED', 'VOIDED')) ENABLE;
  ALTER TABLE "XVIEWMGR"."XVIEW_CHECK_CONSTRAINTS" MODIFY ("SEARCH_CONDITION" NOT NULL ENABLE);
  ALTER TABLE "XVIEWMGR"."XVIEW_CHECK_CONSTRAINTS" MODIFY ("STATUS" NOT NULL ENABLE);
  ALTER TABLE "XVIEWMGR"."XVIEW_CHECK_CONSTRAINTS" MODIFY ("SEQ" NOT NULL ENABLE);
  ALTER TABLE "XVIEWMGR"."XVIEW_CHECK_CONSTRAINTS" MODIFY ("XVIEW_NAME" NOT NULL ENABLE);
  ALTER TABLE "XVIEWMGR"."XVIEW_CHECK_CONSTRAINTS" MODIFY ("XVIEW_OWNER" NOT NULL ENABLE);
