--------------------------------------------------------
--  Constraints for Table XVIEW_DEFINITIONS_3
--------------------------------------------------------

  ALTER TABLE "SAVEMGR"."XVIEW_DEFINITIONS_3" MODIFY ("XVIEW_ID" NOT NULL ENABLE);
  ALTER TABLE "SAVEMGR"."XVIEW_DEFINITIONS_3" MODIFY ("XVIEW_STATEMENT" NOT NULL ENABLE);
  ALTER TABLE "SAVEMGR"."XVIEW_DEFINITIONS_3" MODIFY ("XVIEW_KEY_COLUMN_1" NOT NULL ENABLE);
  ALTER TABLE "SAVEMGR"."XVIEW_DEFINITIONS_3" MODIFY ("BASETABLE_STATEMENT" NOT NULL ENABLE);
  ALTER TABLE "SAVEMGR"."XVIEW_DEFINITIONS_3" MODIFY ("BASETABLE_KEY_COLUMN_1" NOT NULL ENABLE);
  ALTER TABLE "SAVEMGR"."XVIEW_DEFINITIONS_3" MODIFY ("BASETABLE_NAME" NOT NULL ENABLE);
  ALTER TABLE "SAVEMGR"."XVIEW_DEFINITIONS_3" MODIFY ("BASETABLE_OWNER" NOT NULL ENABLE);
  ALTER TABLE "SAVEMGR"."XVIEW_DEFINITIONS_3" MODIFY ("DATA_TABLESPACE" NOT NULL ENABLE);
  ALTER TABLE "SAVEMGR"."XVIEW_DEFINITIONS_3" MODIFY ("INTERNAL_TABLE_NAME" NOT NULL ENABLE);
  ALTER TABLE "SAVEMGR"."XVIEW_DEFINITIONS_3" MODIFY ("LAST_STATUS" NOT NULL ENABLE);
  ALTER TABLE "SAVEMGR"."XVIEW_DEFINITIONS_3" MODIFY ("PROCESS_HOW" NOT NULL ENABLE);
  ALTER TABLE "SAVEMGR"."XVIEW_DEFINITIONS_3" MODIFY ("PROCESS_KEYS" NOT NULL ENABLE);
  ALTER TABLE "SAVEMGR"."XVIEW_DEFINITIONS_3" MODIFY ("PROCESS_WHEN" NOT NULL ENABLE);
  ALTER TABLE "SAVEMGR"."XVIEW_DEFINITIONS_3" MODIFY ("XVIEW_NAME" NOT NULL ENABLE);
  ALTER TABLE "SAVEMGR"."XVIEW_DEFINITIONS_3" MODIFY ("XVIEW_OWNER" NOT NULL ENABLE);
