--------------------------------------------------------
--  Constraints for Table XVIEW_DEFINITION_COLS
--------------------------------------------------------

  ALTER TABLE "XVIEWMGR"."XVIEW_DEFINITION_COLS" ADD CONSTRAINT "PK_XVIEW_DEFINITION_COLS" PRIMARY KEY ("COLUMN_NAME", "XVIEW_NAME")
  USING INDEX  ENABLE;
  ALTER TABLE "XVIEWMGR"."XVIEW_DEFINITION_COLS" MODIFY ("COLUMN_NAME" NOT NULL ENABLE);
  ALTER TABLE "XVIEWMGR"."XVIEW_DEFINITION_COLS" MODIFY ("XVIEW_NAME" NOT NULL ENABLE);
