--------------------------------------------------------
--  Constraints for Table XVIEW_DEFINITIONS_1
--------------------------------------------------------

  ALTER TABLE "SAVEMGR"."XVIEW_DEFINITIONS_1" MODIFY ("XVIEW_ID" NOT NULL ENABLE);
  ALTER TABLE "SAVEMGR"."XVIEW_DEFINITIONS_1" MODIFY ("XVIEW_STATEMENT" NOT NULL ENABLE);
  ALTER TABLE "SAVEMGR"."XVIEW_DEFINITIONS_1" MODIFY ("XVIEW_KEY_COLUMN_1" NOT NULL ENABLE);
  ALTER TABLE "SAVEMGR"."XVIEW_DEFINITIONS_1" MODIFY ("BASETABLE_STATEMENT" NOT NULL ENABLE);
  ALTER TABLE "SAVEMGR"."XVIEW_DEFINITIONS_1" MODIFY ("BASETABLE_KEY_COLUMN_1" NOT NULL ENABLE);
  ALTER TABLE "SAVEMGR"."XVIEW_DEFINITIONS_1" MODIFY ("BASETABLE_NAME" NOT NULL ENABLE);
  ALTER TABLE "SAVEMGR"."XVIEW_DEFINITIONS_1" MODIFY ("BASETABLE_OWNER" NOT NULL ENABLE);
  ALTER TABLE "SAVEMGR"."XVIEW_DEFINITIONS_1" MODIFY ("DATA_TABLESPACE" NOT NULL ENABLE);
  ALTER TABLE "SAVEMGR"."XVIEW_DEFINITIONS_1" MODIFY ("INTERNAL_TABLE_NAME" NOT NULL ENABLE);
  ALTER TABLE "SAVEMGR"."XVIEW_DEFINITIONS_1" MODIFY ("LAST_STATUS" NOT NULL ENABLE);
  ALTER TABLE "SAVEMGR"."XVIEW_DEFINITIONS_1" MODIFY ("PROCESS_HOW" NOT NULL ENABLE);
  ALTER TABLE "SAVEMGR"."XVIEW_DEFINITIONS_1" MODIFY ("PROCESS_KEYS" NOT NULL ENABLE);
  ALTER TABLE "SAVEMGR"."XVIEW_DEFINITIONS_1" MODIFY ("PROCESS_WHEN" NOT NULL ENABLE);
  ALTER TABLE "SAVEMGR"."XVIEW_DEFINITIONS_1" MODIFY ("XVIEW_NAME" NOT NULL ENABLE);
  ALTER TABLE "SAVEMGR"."XVIEW_DEFINITIONS_1" MODIFY ("XVIEW_OWNER" NOT NULL ENABLE);
