--------------------------------------------------------
--  Constraints for Table ZZ_WB_ACTIONS_DATA_BCK
--------------------------------------------------------

  ALTER TABLE "XVIEWMGR"."ZZ_WB_ACTIONS_DATA_BCK" ADD CONSTRAINT "XV_WB_ACTIONS_BCK_PK" PRIMARY KEY ("WBA_ID")
  USING INDEX  ENABLE;
  ALTER TABLE "XVIEWMGR"."ZZ_WB_ACTIONS_DATA_BCK" MODIFY ("TERMINATED_FLAG" NOT NULL ENABLE);
  ALTER TABLE "XVIEWMGR"."ZZ_WB_ACTIONS_DATA_BCK" MODIFY ("START_DATETIME" NOT NULL ENABLE);
  ALTER TABLE "XVIEWMGR"."ZZ_WB_ACTIONS_DATA_BCK" MODIFY ("ACTION_MNEM" NOT NULL ENABLE);
  ALTER TABLE "XVIEWMGR"."ZZ_WB_ACTIONS_DATA_BCK" MODIFY ("WBA_ID" NOT NULL ENABLE);
