--------------------------------------------------------
--  DDL for Type ACTIONS538_T
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TYPE "XVIEWMGR"."ACTIONS538_T" AS OBJECT ("SYS_XDBPD$" "XDB"."XDB$RAW_LIST_T","foxid" VARCHAR2(4000 CHAR),"REMOVE_FLAG" "REMOVE_FLAG539_T","ARS_FLAG" "ARS_FLAG540_T","COPY_RATING_FLAG" "COPY_RATING_FLAG541_T","COPY_REGIME_FLAG" "COPY_REGIME_FLAG542_T","COPY_ARS_FLAG" "COPY_ARS_FLAG543_T","PASTE_FLAG" "PASTE_FLAG544_T")FINAL INSTANTIABLE 

/
