--------------------------------------------------------
--  DDL for Type ACTION_LIST580_T
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TYPE "XVIEWMGR"."ACTION_LIST580_T" AS OBJECT ("SYS_XDBPD$" "XDB"."XDB$RAW_LIST_T","foxid" VARCHAR2(4000 CHAR),"REMOVE_FLAG" "REMOVE_FLAG581_T","TOO_FEW_SOURCES" "TOO_FEW_SOURCES582_T","TOO_MANY_SOURCES" "TOO_MANY_SOURCES583_T","TOO_FEW_CONSIGNEES" "TOO_FEW_CONSIGNEES584_T","TOO_MANY_CONSIGNEES" "TOO_MANY_CONSIGNEES585_T","TOO_FEW_END_USERS" "TOO_FEW_END_USERS586_T","TOO_MANY_END_USERS" "TOO_MANY_END_USERS587_T")FINAL INSTANTIABLE 

/
