--------------------------------------------------------
--  DDL for Type ADVICE763_T
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TYPE "XVIEWMGR"."ADVICE763_T" AS OBJECT ("SYS_XDBPD$" "XDB"."XDB$RAW_LIST_T","foxid" VARCHAR2(4000 CHAR),"ADVICE_SOUGHT_FROM" "ADVICE_SOUGHT_FROM764_T","DATE_ADVICE_SOUGHT" "DATE_ADVICE_SOUGHT765_T","COMMENTS" "COMMENTS766_T","DATE_ADVICE_RECIEVED" "DATE_ADVICE_RECIEVED767_T","ADVICE_GIVEN" "ADVICE_GIVEN768_T","OGD_PROVISOS" "OGD_PROVISOS769_T")FINAL INSTANTIABLE 

/
