--------------------------------------------------------
--  DDL for Type AMENDMENT_DETAILS831_T
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TYPE "XVIEWMGR"."AMENDMENT_DETAILS831_T" AS OBJECT ("SYS_XDBPD$" "XDB"."XDB$RAW_LIST_T","foxid" VARCHAR2(4000 CHAR),"AMENDMENT_SCALE" "AMENDMENT_SCALE832_T","SEND_TO_PRECIRC" "SEND_TO_PRECIRC833_T","CASE_OFFICER" "CASE_OFFICER834_T","PRECIRC_AMENDMENT_NOTE" "PRECIRC_AMENDMENT_NOTE835_T","SEND_TO_TAU" "SEND_TO_TAU836_T","TECHNICAL_OFFICER" "TECHNICAL_OFFICER837_T","TECHNICAL_AMENDMENT_NOTE" "TECHNICAL_AMENDMENT_NOT838_T","REQUIRES_APPROVAL" "REQUIRES_APPROVAL839_T","AMENDMENT_TYPE" "AMENDMENT_TYPE840_T","REMOVE_SAR_FLAG" "REMOVE_SAR_FLAG841_T","RESEND_TO_PRECIRC" "RESEND_TO_PRECIRC842_T","PRECIRC_REAMEND_NOTE" "PRECIRC_REAMEND_NOTE843_T","RESEND_TO_TAU" "RESEND_TO_TAU844_T","TECHNICAL_REAMEND_NOTE" "TECHNICAL_REAMEND_NOTE845_T")FINAL INSTANTIABLE 

/
