--------------------------------------------------------
--  DDL for Type APPLICATION_JUSTIFICATI570_T
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TYPE "XVIEWMGR"."APPLICATION_JUSTIFICATI570_T" AS OBJECT ("SYS_XDBPD$" "XDB"."XDB$RAW_LIST_T","foxid" VARCHAR2(4000 CHAR),"REASON_FOR_CONTRACT_LIST" "REASON_FOR_CONTRACT_LIS571_T","OTHER_REASON_FOR_CONTRACT" "OTHER_REASON_FOR_CONTRA574_T","PREVIOUS_APP_FLAG" "PREVIOUS_APP_FLAG575_T","NUMBER_OF_PREVIOUS_EXPORTS" "NUMBER_OF_PREVIOUS_EXPO576_T")FINAL INSTANTIABLE 

/
