--------------------------------------------------------
--  DDL for Type APPLICATION_METADATA413_T
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TYPE "XVIEWMGR"."APPLICATION_METADATA413_T" AS OBJECT ("SYS_XDBPD$" "XDB"."XDB$RAW_LIST_T","foxid" VARCHAR2(4000 CHAR),"CREATED_DATETIME" DATE,"CREATED_BY_WUA_ID" "CREATED_BY_WUA_ID414_T","CREATED_BY_NAME" "CREATED_BY_NAME415_T","UPDATED_DATETIME" DATE,"UPDATED_BY_WUA_ID" "UPDATED_BY_WUA_ID416_T","UPDATED_BY_NAME" "UPDATED_BY_NAME417_T","SUBMITTED_DATETIME" DATE,"DUE_DATE" "DUE_DATE418_T","RESUBMITTED_DATETIME" "RESUBMITTED_DATETIME419_T","STATUS" "STATUS420_T","AMENDMENT_FLAG" "AMENDMENT_FLAG421_T","CASE_CLOSED_DATETIME" DATE,"CASE_CLOSED_BY_NAME" "CASE_CLOSED_BY_NAME422_T","CASE_CLOSED_BY_WUA_ID" "CASE_CLOSED_BY_WUA_ID423_T","CASE_CLOSED_REASON" "CASE_CLOSED_REASON424_T","SNAPSHOT_REASON" "SNAPSHOT_REASON425_T","REOPEN_CASE_PERMITTED" "REOPEN_CASE_PERMITTED426_T")FINAL INSTANTIABLE 

/
