--------------------------------------------------------
--  DDL for Type APPLICATION_DETAILS427_T
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TYPE "XVIEWMGR"."APPLICATION_DETAILS427_T" AS OBJECT ("SYS_XDBPD$" "XDB"."XDB$RAW_LIST_T","foxid" VARCHAR2(4000 CHAR),"APPLICATION_TURN_NO" "APPLICATION_TURN_NO428_T","DTI_REF" "DTI_REF429_T","FILE_FOLDER" "FILE_FOLDER430_T","CASE_FILE_FOLDER" "CASE_FILE_FOLDER431_T","APPLICANT_REF" "APPLICANT_REF432_T","LEGACY_APP_REF" "LEGACY_APP_REF433_T","APPLICATION_TYPE" "APPLICATION_TYPE434_T","APPLICATION_SUB_TYPE" "APPLICATION_SUB_TYPE435_T","PREVIOUS_APPLICATION_LIST" "PREVIOUS_APPLICATION_LI436_T","LICENSEE_HAS_PARENT_COMPANY" "LICENSEE_HAS_PARENT_COM442_T","SRC_NOT_KNOWN_REASON" "SRC_NOT_KNOWN_REASON443_T","RCP_NOT_KNOWN_REASON" "RCP_NOT_KNOWN_REASON444_T","HELD_VERSION_NO" "HELD_VERSION_NO445_T","OGL_TYPE_LIST" "OGL_TYPE_LIST446_T","SAR_ID" "SAR_ID451_T","SITE_ID" "SITE_ID452_T","TECHNICAL_CONTACT_SAME_AS454" "TECHNICAL_CONTACT_SAME_453_T","TARGET_DATE" "TARGET_DATE455_T","TARGET_NUMBER_OF_DAYS" "TARGET_NUMBER_OF_DAYS456_T","AMENDMENT_FILE_FOLDER" "AMENDMENT_FILE_FOLDER457_T")FINAL INSTANTIABLE 

/
