--------------------------------------------------------
--  DDL for Type CASE_DETAILS726_T
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TYPE "XVIEWMGR"."CASE_DETAILS726_T" AS OBJECT ("SYS_XDBPD$" "XDB"."XDB$RAW_LIST_T","foxid" VARCHAR2(4000 CHAR),"SUMMARY" "SUMMARY727_T","GOODS_RATING" "GOODS_RATING735_T","GOODS_CLASSIFICATION" "GOODS_CLASSIFICATION742_T","LEGACY_DATA" "LEGACY_DATA752_T","OGL_ELIGIBILITY" "OGL_ELIGIBILITY785_T","ENFORCEMENT_UNIT" "ENFORCEMENT_UNIT792_T","DENIALS" "DENIALS803_T","RATING_CHECKS" "RATING_CHECKS811_T","COUNTRY_RESTRICTION_LIST" "COUNTRY_RESTRICTION_LIS813_T","PRE_CIRCULATION_CHECKS" "PRE_CIRCULATION_CHECKS814_T","POST_CIRCULATION_CHECKS" "POST_CIRCULATION_CHECKS823_T")FINAL INSTANTIABLE 

/
