--------------------------------------------------------
--  DDL for Type COUNTRY_ERROR_LIST610_T
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TYPE "XVIEWMGR"."COUNTRY_ERROR_LIST610_T" AS OBJECT ("SYS_XDBPD$" "XDB"."XDB$RAW_LIST_T","foxid" VARCHAR2(4000 CHAR),"TOO_FEW_SOURCE_COUNTRIES" "TOO_FEW_SOURCE_COUNTRIE611_T","TOO_MANY_SOURCE_COUNTRIES" "TOO_MANY_SOURCE_COUNTRI612_T","TOO_FEW_RECIPIENT_COUNTRIES" "TOO_FEW_RECIPIENT_COUNT613_T","TOO_MANY_RECIPIENT_COUNTRIES" "TOO_MANY_RECIPIENT_COUN614_T")FINAL INSTANTIABLE 

/
