--------------------------------------------------------
--  DDL for Type COUNTRY563_T
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TYPE "XVIEWMGR"."COUNTRY563_T" AS OBJECT ("SYS_XDBPD$" "XDB"."XDB$RAW_LIST_T","foxid" VARCHAR2(4000 CHAR),"COUNTRY_CODE" "COUNTRY_CODE564_T","COUNTRY_ID" "COUNTRY_ID565_T","COUNTRY_NAME" "COUNTRY_NAME566_T","TOO_FEW_SRC_GOODS_FLAG" "TOO_FEW_SRC_GOODS_FLAG567_T","TOO_FEW_RCPT_GOODS_FLAG" "TOO_FEW_RCPT_GOODS_FLAG568_T","SRC_STAKEHOLDER_REQUIRED_FLAG" "SRC_STAKEHOLDER_REQUIRE569_T","APPLICATION_JUSTIFICATION" "APPLICATION_JUSTIFICATI570_T","OTHER_REASON_FOR_CONTRACT" "OTHER_REASON_FOR_CONTRA577_T","PREVIOUS_APP_FLAG" "PREVIOUS_APP_FLAG578_T","NUMBER_OF_PREVIOUS_EXPORTS" "NUMBER_OF_PREVIOUS_EXPO579_T","ACTION_LIST" "ACTION_LIST580_T","SELECT_ALL_GOODS_FLAG" "SELECT_ALL_GOODS_FLAG588_T","STAKEHOLDER_ROLE_LIST" "STAKEHOLDER_ROLE_LIST589_T","GOODS_ITEM_LIST" "GOODS_ITEM_LIST592_T","COUNTRY_WITHDRAW_FLAG" "COUNTRY_WITHDRAW_FLAG606_T","FINAL_OUTCOME" "FINAL_OUTCOME607_T","OUTCOME_ACTIONS" "OUTCOME_ACTIONS608_T")FINAL INSTANTIABLE 

/
