--------------------------------------------------------
--  DDL for Type DENIALS803_T
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TYPE "XVIEWMGR"."DENIALS803_T" AS OBJECT ("SYS_XDBPD$" "XDB"."XDB$RAW_LIST_T","foxid" VARCHAR2(4000 CHAR),"POSSIBLE_MATCH_FLAG" "POSSIBLE_MATCH_FLAG804_T","MATCH_CHECKED_FLAG" "MATCH_CHECKED_FLAG805_T","DENIALS_MATCH_LIST" "DENIALS_MATCH_LIST806_T","SEARCH_LOG_LIST" "SEARCH_LOG_LIST809_T","NEW_DN_SEARCH_USED" "NEW_DN_SEARCH_USED810_T")FINAL INSTANTIABLE 

/
