--------------------------------------------------------
--  DDL for Type EU_CONCERN794_T
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TYPE "XVIEWMGR"."EU_CONCERN794_T" AS OBJECT ("SYS_XDBPD$" "XDB"."XDB$RAW_LIST_T","foxid" VARCHAR2(4000 CHAR),"CONCERN_TYPE" "CONCERN_TYPE795_T","STAKEHOLDER_ROLE_TYPE" "STAKEHOLDER_ROLE_TYPE796_T","CHECKED_DATETIME" "CHECKED_DATETIME797_T","DEALT_WITH_FLAG" "DEALT_WITH_FLAG798_T","CONCERNS" "CONCERNS799_T","REFERRAL" "REFERRAL800_T","ACTIONS" "ACTIONS801_T")FINAL INSTANTIABLE 

/
