--------------------------------------------------------
--  DDL for Type EXPORT_GOODS486_T
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TYPE "XVIEWMGR"."EXPORT_GOODS486_T" AS OBJECT ("SYS_XDBPD$" "XDB"."XDB$RAW_LIST_T","foxid" VARCHAR2(4000 CHAR),"GOODS_ITEM_LIST" "GOODS_ITEM_LIST487_T","GENERAL_GOODS_DESCRIPTION" "GENERAL_GOODS_DESCRIPTI549_T","TOTAL_GOODS_VALUE_CONFIRM" "TOTAL_GOODS_VALUE_CONFI550_T","GOODS_USAGE" "GOODS_USAGE551_T")FINAL INSTANTIABLE 

/
