--------------------------------------------------------
--  DDL for Type F680_QUESTIONS_SECTION464_T
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TYPE "XVIEWMGR"."F680_QUESTIONS_SECTION464_T" AS OBJECT ("SYS_XDBPD$" "XDB"."XDB$RAW_LIST_T","foxid" VARCHAR2(4000 CHAR),"APP_REASON" "APP_REASON465_T","APP_REASON_TEXT" "APP_REASON_TEXT472_T","URGENT_CLEARANCE" "URGENT_CLEARANCE473_T","CLEARANCES" "CLEARANCES478_T","LOCAL_INFO" "LOCAL_INFO482_T","OTHER_INFORMATION" "OTHER_INFORMATION484_T")FINAL INSTANTIABLE 

/
