--------------------------------------------------------
--  DDL for Type FIREARMS_EXPORT655_T
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TYPE "XVIEWMGR"."FIREARMS_EXPORT655_T" AS OBJECT ("SYS_XDBPD$" "XDB"."XDB$RAW_LIST_T","foxid" VARCHAR2(4000 CHAR),"REGISTERED_DEALER" "REGISTERED_DEALER656_T","RFD_CERTIFICATE_NUMBER" "RFD_CERTIFICATE_NUMBER657_T","RFD_CERTIFICATE_EXPIRY_DATE" "RFD_CERTIFICATE_EXPIRY_658_T","FIREARM_EXPORT_EU" "FIREARM_EXPORT_EU659_T","FIREARM_CHECKS" "FIREARM_CHECKS660_T","FIREARM_PROHIBITED" "FIREARM_PROHIBITED661_T","CATEGORY_PROHIBITED_LIST" "CATEGORY_PROHIBITED_LIS662_T","SECTION_5_CERTIFICATE_NO" "SECTION_5_CERTIFICATE_N665_T","SECTION_5_CERTIFICATE_EXP667" "SECTION_5_CERTIFICATE_E666_T")FINAL INSTANTIABLE 

/
