--------------------------------------------------------
--  DDL for Type GOODS_ITEM593_T
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TYPE "XVIEWMGR"."GOODS_ITEM593_T" AS OBJECT ("SYS_XDBPD$" "XDB"."XDB$RAW_LIST_T","foxid" VARCHAR2(4000 CHAR),"ITEM_NO" "ITEM_NO594_T","SOURCE_SELECTED_FLAG" "SOURCE_SELECTED_FLAG595_T","RECIPIENT_SELECTED_FLAG" "RECIPIENT_SELECTED_FLAG596_T","LINE_NO" "LINE_NO597_T","RECIPIENT_OVERRIDE_FLAG" "RECIPIENT_OVERRIDE_FLAG598_T","OUTCOME" "OUTCOME599_T","DC_ID" "DC_ID600_T","DC_TITLE" "DC_TITLE601_T","DC_SELECTOR" "DC_SELECTOR602_T","LICENCE_LINE_NUMBER" "LICENCE_LINE_NUMBER603_T","LD_ID" "LD_ID604_T")FINAL INSTANTIABLE 

/
