--------------------------------------------------------
--  DDL for Type GOODS_RATING735_T
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TYPE "XVIEWMGR"."GOODS_RATING735_T" AS OBJECT ("SYS_XDBPD$" "XDB"."XDB$RAW_LIST_T","foxid" VARCHAR2(4000 CHAR),"TAU_COMMENT" "TAU_COMMENT736_T","ADVICE_POSSIBLE" "ADVICE_POSSIBLE737_T","NLR_TYPE" "NLR_TYPE738_T","ENDORSED_LIST_FLAG" "ENDORSED_LIST_FLAG739_T","SUPERSEDE_TYPE" "SUPERSEDE_TYPE740_T","SUPERSEDE_RESPONSE_DATE" "SUPERSEDE_RESPONSE_DATE741_T")FINAL INSTANTIABLE 

/
