--------------------------------------------------------
--  DDL for Type GOODS_CLASSIFICATION742_T
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TYPE "XVIEWMGR"."GOODS_CLASSIFICATION742_T" AS OBJECT ("SYS_XDBPD$" "XDB"."XDB$RAW_LIST_T","foxid" VARCHAR2(4000 CHAR),"REGIME_ORIGIN_LIST" "REGIME_ORIGIN_LIST743_T","LEGISLATION_ORIGIN_LIST" "LEGISLATION_ORIGIN_LIST746_T","GOODS_RELATED_LIST" "GOODS_RELATED_LIST749_T")FINAL INSTANTIABLE 

/
