--------------------------------------------------------
--  DDL for Type INTENDED_END_USE651_T
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TYPE "XVIEWMGR"."INTENDED_END_USE651_T" AS OBJECT ("SYS_XDBPD$" "XDB"."XDB$RAW_LIST_T","foxid" VARCHAR2(4000 CHAR),"END_USE_DETAILS" "END_USE_DETAILS652_T","OVERSEAS_PRODUCTION" "OVERSEAS_PRODUCTION653_T","OVERSEAS_DETAILS" "OVERSEAS_DETAILS654_T")FINAL INSTANTIABLE 

/
