--------------------------------------------------------
--  DDL for Type LEGACY_DATA752_T
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TYPE "XVIEWMGR"."LEGACY_DATA752_T" AS OBJECT ("SYS_XDBPD$" "XDB"."XDB$RAW_LIST_T","foxid" VARCHAR2(4000 CHAR),"DATE_OF_COMPLIANCE" "DATE_OF_COMPLIANCE753_T","LEGACY_ADVICE" "LEGACY_ADVICE754_T","LEGACY_ARS_SUMMARY" "LEGACY_ARS_SUMMARY772_T","LEGACY_LICENCE_NUMBER" "LEGACY_LICENCE_NUMBER773_T","LEGACY_LICENCE_EXPIRY_DATE" "LEGACY_LICENCE_EXPIRY_D774_T","LEGACY_LICENCE_COMMENT" "LEGACY_LICENCE_COMMENT775_T","LEGACY_SPECIAL_CONDITIONS" "LEGACY_SPECIAL_CONDITIO776_T","LEGACY_SIGNATORY_DETAILS" "LEGACY_SIGNATORY_DETAIL777_T","LEGACY_CASE_ALLOCATION" "LEGACY_CASE_ALLOCATION783_T")FINAL INSTANTIABLE 

/
