--------------------------------------------------------
--  DDL for Type LEGACY_CASE_ALLOCATION783_T
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TYPE "XVIEWMGR"."LEGACY_CASE_ALLOCATION783_T" AS OBJECT ("SYS_XDBPD$" "XDB"."XDB$RAW_LIST_T","foxid" VARCHAR2(4000 CHAR),"CASE_OFFICER_NAME" "CASE_OFFICER_NAME784_T","CASE_OFFICER_PHONE" VARCHAR2(4000 CHAR))FINAL INSTANTIABLE 

/
