--------------------------------------------------------
--  DDL for Type LEGACY_SIGNATORY_DETAIL777_T
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TYPE "XVIEWMGR"."LEGACY_SIGNATORY_DETAIL777_T" AS OBJECT ("SYS_XDBPD$" "XDB"."XDB$RAW_LIST_T","foxid" VARCHAR2(4000 CHAR),"ECO_REF_NUMBER" "ECO_REF_NUMBER778_T","REGISTRATION_NUM" "REGISTRATION_NUM779_T","DATE_OF_SIGNATURE" "DATE_OF_SIGNATURE780_T","ENCLOSURES_YN" "ENCLOSURES_YN781_T","ENCLOSURES_SPECIFIED" "ENCLOSURES_SPECIFIED782_T")FINAL INSTANTIABLE 

/
