--------------------------------------------------------
--  DDL for Type MOD_SPONSOR673_T
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TYPE "XVIEWMGR"."MOD_SPONSOR673_T" AS OBJECT ("SYS_XDBPD$" "XDB"."XDB$RAW_LIST_T","foxid" VARCHAR2(4000 CHAR),"SPONSOR_NAME" "SPONSOR_NAME674_T","SPONSOR_ADDRESS" "SPONSOR_ADDRESS675_T","SPONSOR_TELEPHONE" "SPONSOR_TELEPHONE676_T","SPONSOR_EMAIL" "SPONSOR_EMAIL677_T")FINAL INSTANTIABLE 

/
