--------------------------------------------------------
--  DDL for Type NATURE_OF_ITEMS642_T
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TYPE "XVIEWMGR"."NATURE_OF_ITEMS642_T" AS OBJECT ("SYS_XDBPD$" "XDB"."XDB$RAW_LIST_T","foxid" VARCHAR2(4000 CHAR),"INFORMED_OF_INTENDED_CHEM644" "INFORMED_OF_INTENDED_CH643_T","DTI_REF" "DTI_REF645_T","SUSPECTED_CHEM_BIO_NUC_USE" "SUSPECTED_CHEM_BIO_NUC_646_T","SUSPECTED_DETAILS" "SUSPECTED_DETAILS647_T")FINAL INSTANTIABLE 

/
