--------------------------------------------------------
--  DDL for Type NOTES_TO_APPLICANT847_T
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TYPE "XVIEWMGR"."NOTES_TO_APPLICANT847_T" AS OBJECT ("SYS_XDBPD$" "XDB"."XDB$RAW_LIST_T","foxid" VARCHAR2(4000 CHAR),"NOTE_TYPE" "NOTE_TYPE848_T","NOTE_TEXT" "NOTE_TEXT849_T","CREATED_BY_WUA" "CREATED_BY_WUA850_T","CREATED_BY" "CREATED_BY851_T","CREATED_DATE" "CREATED_DATE852_T","STATUS" "STATUS853_T")FINAL INSTANTIABLE 

/
