--------------------------------------------------------
--  DDL for Type NOTIFICATION_DETAIL395_T
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TYPE "XVIEWMGR"."NOTIFICATION_DETAIL395_T" AS OBJECT ("SYS_XDBPD$" "XDB"."XDB$RAW_LIST_T","foxid" VARCHAR2(4000 CHAR),"OUTCOME_DECISION" "OUTCOME_DECISION396_T","DC_ID" "DC_ID397_T","IS_ID" "IS_ID398_T","CLEARANCE_LIST" "CLEARANCE_LIST399_T","F680_DURATION" "F680_DURATION405_T","CLEARED_SECURITY_CLASSIFI407" "CLEARED_SECURITY_CLASSI406_T","DI_ID" "DI_ID408_T","NOTIFICATION_DATE" "NOTIFICATION_DATE409_T","ISSUING_WUA_ID" "ISSUING_WUA_ID410_T")FINAL INSTANTIABLE 

/
