--------------------------------------------------------
--  DDL for Type ORGANISATION_UNIT334_T
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TYPE "XVIEWMGR"."ORGANISATION_UNIT334_T" AS OBJECT ("SYS_XDBPD$" "XDB"."XDB$RAW_LIST_T","foxid" VARCHAR2(4000 CHAR),"ID" "ID335_T","REGISTERED_NUMBER" "REGISTERED_NUMBER336_T","NAME" "NAME337_T","VAT_NUMBER" "VAT_NUMBER338_T","EORI_NUMBER" "EORI_NUMBER339_T","TURN_NUMBER" "TURN_NUMBER340_T","REGISTERED_ADDRESS_ID" "REGISTERED_ADDRESS_ID341_T","REGISTERED_ADDRESS" "REGISTERED_ADDRESS342_T","REGISTERED_LOCATION_AT_ADDRESS" "REGISTERED_LOCATION_AT_343_T","BRANCH_NUMBER" "BRANCH_NUMBER344_T","BRANCH_ADDRESS_ID" "BRANCH_ADDRESS_ID345_T","BRANCH_LOCATION_AT_ADDRESS" "BRANCH_LOCATION_AT_ADDR346_T","BRANCH_ADDRESS" "BRANCH_ADDRESS347_T","GENERAL_INFO" VARCHAR2(4000 CHAR),"WARNING_INFO" VARCHAR2(4000 CHAR),"OVERSEA_COMPANY_DETAILS" "OVERSEA_COMPANY_DETAILS348_T","COMPANY_DETAILS_ACCURACY_354" "COMPANY_DETAILS_ACCURAC353_T")FINAL INSTANTIABLE 

/
