--------------------------------------------------------
--  DDL for Type OVERSEA_COMPANY_DETAILS348_T
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TYPE "XVIEWMGR"."OVERSEA_COMPANY_DETAILS348_T" AS OBJECT ("SYS_XDBPD$" "XDB"."XDB$RAW_LIST_T","foxid" VARCHAR2(4000 CHAR),"COUNTRY_OF_ORIGIN" "COUNTRY_OF_ORIGIN349_T","PARENT_REGISTRY_NAME" "PARENT_REGISTRY_NAME350_T","PARENT_REGISTRY_COMPANY_REF" "PARENT_REGISTRY_COMPANY351_T","PARENT_REGISTRY_COMMENT" "PARENT_REGISTRY_COMMENT352_T")FINAL INSTANTIABLE 

/
