--------------------------------------------------------
--  DDL for Type PERSON_DETAILS328_T
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TYPE "XVIEWMGR"."PERSON_DETAILS328_T" AS OBJECT ("SYS_XDBPD$" "XDB"."XDB$RAW_LIST_T","foxid" VARCHAR2(4000 CHAR),"JOB_DESCRIPTION" "JOB_DESCRIPTION329_T","TITLE" "TITLE330_T","FORENAME" "FORENAME331_T","MIDDLE_INITIALS" "MIDDLE_INITIALS332_T","SURNAME" "SURNAME333_T")FINAL INSTANTIABLE 

/
