--------------------------------------------------------
--  DDL for Type POST_CIRCULATION_CHECKS823_T
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TYPE "XVIEWMGR"."POST_CIRCULATION_CHECKS823_T" AS OBJECT ("SYS_XDBPD$" "XDB"."XDB$RAW_LIST_T","foxid" VARCHAR2(4000 CHAR),"REFUSALS_MATCH_FLAG" "REFUSALS_MATCH_FLAG824_T","UNSCR_MATCH_FLAG" "UNSCR_MATCH_FLAG825_T","WL_MATCH_FLAG" "WL_MATCH_FLAG826_T","OGD_SUBMIT_TO_MINISTERS" "OGD_SUBMIT_TO_MINISTERS827_T","BERR_SUBMIT_TO_MINISTERS" "BERR_SUBMIT_TO_MINISTER828_T")FINAL INSTANTIABLE 

/
