--------------------------------------------------------
--  DDL for Type PRE_CIRCULATION_CHECKS814_T
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TYPE "XVIEWMGR"."PRE_CIRCULATION_CHECKS814_T" AS OBJECT ("SYS_XDBPD$" "XDB"."XDB$RAW_LIST_T","foxid" VARCHAR2(4000 CHAR),"END_USE_DOCS_FLAG" "END_USE_DOCS_FLAG815_T","RFD_CERTIFCATE_OK_FLAG" "RFD_CERTIFCATE_OK_FLAG816_T","FIREARMS_CERTIFCATE_OK_FLAG" "FIREARMS_CERTIFCATE_OK_817_T","REFUSALS_MATCH_FLAG" "REFUSALS_MATCH_FLAG818_T","UNSCR_MATCH_FLAG" "UNSCR_MATCH_FLAG819_T","INCORPORATION_FLAG" "INCORPORATION_FLAG820_T","PRIOR_IMPORT_CONSENT_REQUIRED" "PRIOR_IMPORT_CONSENT_RE821_T","EC_CONSULTATION_REQUIRED" "EC_CONSULTATION_REQUIRE822_T")FINAL INSTANTIABLE 

/
