--------------------------------------------------------
--  DDL for Type PROPOSED_SECURITY_CLASS692_T
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TYPE "XVIEWMGR"."PROPOSED_SECURITY_CLASS692_T" AS OBJECT ("SYS_XDBPD$" "XDB"."XDB$RAW_LIST_T","foxid" VARCHAR2(4000 CHAR),"PROPOSED_SECURITY_CLASSIF694" "PROPOSED_SECURITY_CLASS693_T","OTHER_TEXT" "OTHER_TEXT695_T")FINAL INSTANTIABLE 

/
