--------------------------------------------------------
--  DDL for Type QUESTIONS_SECTION627_T
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TYPE "XVIEWMGR"."QUESTIONS_SECTION627_T" AS OBJECT ("SYS_XDBPD$" "XDB"."XDB$RAW_LIST_T","foxid" VARCHAR2(4000 CHAR),"TEMPORARY_EXPORTS" "TEMPORARY_EXPORTS628_T","PROMOTION_APPROVALS" "PROMOTION_APPROVALS635_T","NATURE_OF_ITEMS" "NATURE_OF_ITEMS642_T","MILITARY_END_USE_DETAILS" "MILITARY_END_USE_DETAIL648_T","INTENDED_END_USE" "INTENDED_END_USE651_T","FIREARMS_EXPORT" "FIREARMS_EXPORT655_T","PREVIOUS_LICENCE_INFO" "PREVIOUS_LICENCE_INFO668_T","MOD_SPONSOR_INFO" "MOD_SPONSOR_INFO670_T","ARMED_FORCES_INFO" "ARMED_FORCES_INFO678_T","SECURITY_GRADING_INFO" "SECURITY_GRADING_INFO681_T","PROPOSED_SECURITY_CLASSIF696" "PROPOSED_SECURITY_CLASS692_T","FOREIGN_INFO" "FOREIGN_INFO697_T","PROSPECT_VALUE_INFO" "PROSPECT_VALUE_INFO700_T","OTHER_INFORMATION" "OTHER_INFORMATION703_T","APPLICATION_JUSTIFICATION" "APPLICATION_JUSTIFICATI705_T","BUSINESS_CASE_STATEMENT" "BUSINESS_CASE_STATEMENT707_T")FINAL INSTANTIABLE 

/
