--------------------------------------------------------
--  DDL for Type RECIPIENT_COUNTRY_GROUP728_T
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TYPE "XVIEWMGR"."RECIPIENT_COUNTRY_GROUP728_T" AS OBJECT ("SYS_XDBPD$" "XDB"."XDB$RAW_LIST_T","foxid" VARCHAR2(4000 CHAR),"RECIPIENT_COUNTRY_GROUP" "RECIPIENT_COUNTRY_GR732_COLL")FINAL INSTANTIABLE 

/
