--------------------------------------------------------
--  DDL for Type ROUTING_SECTION615_T
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TYPE "XVIEWMGR"."ROUTING_SECTION615_T" AS OBJECT ("SYS_XDBPD$" "XDB"."XDB$RAW_LIST_T","foxid" VARCHAR2(4000 CHAR),"AIRWAY_OR_BILL_LADING_FLAG" "AIRWAY_OR_BILL_LADING_F616_T","ROUTE_HOP_LIST" "ROUTE_HOP_LIST617_T","SIMPLE_ROUTE_DESCRIPTION" "SIMPLE_ROUTE_DESCRIPTIO626_T")FINAL INSTANTIABLE 

/
