--------------------------------------------------------
--  DDL for Type SECURITY_GRADED_DETAILS683_T
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TYPE "XVIEWMGR"."SECURITY_GRADED_DETAILS683_T" AS OBJECT ("SYS_XDBPD$" "XDB"."XDB$RAW_LIST_T","foxid" VARCHAR2(4000 CHAR),"SECURITY_CLASSIFICATION" "SECURITY_CLASSIFICATION684_T","OTHER_TEXT" "OTHER_TEXT685_T","SECURITY_GRADING_AUTHORITY" "SECURITY_GRADING_AUTHOR686_T")FINAL INSTANTIABLE 

/
