--------------------------------------------------------
--  DDL for Type SECURITY_GRADING_INFO681_T
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TYPE "XVIEWMGR"."SECURITY_GRADING_INFO681_T" AS OBJECT ("SYS_XDBPD$" "XDB"."XDB$RAW_LIST_T","foxid" VARCHAR2(4000 CHAR),"SECURITY_GRADED" "SECURITY_GRADED682_T","SECURITY_GRADED_DETAILS" "SECURITY_GRADED_DETAILS683_T","SECURITY_GRADING_ACTION" "SECURITY_GRADING_ACTION691_T")FINAL INSTANTIABLE 

/
