--------------------------------------------------------
--  DDL for Type SECURITY_GRADING_AUTHOR686_T
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TYPE "XVIEWMGR"."SECURITY_GRADING_AUTHOR686_T" AS OBJECT ("SYS_XDBPD$" "XDB"."XDB$RAW_LIST_T","foxid" VARCHAR2(4000 CHAR),"AUTHORITY_NAME" "AUTHORITY_NAME687_T","AUTHORITY_REFERENCE" "AUTHORITY_REFERENCE688_T","AUTHORITY_DATE" "AUTHORITY_DATE689_T","AUTHORITY_REMARKS" "AUTHORITY_REMARKS690_T")FINAL INSTANTIABLE 

/
