--------------------------------------------------------
--  DDL for Type SPIRE_APPLICATION412_T
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TYPE "XVIEWMGR"."SPIRE_APPLICATION412_T" AS OBJECT ("SYS_XDBPD$" "XDB"."XDB$RAW_LIST_T","fox-change-number" VARCHAR2(4000 CHAR),"foxid" VARCHAR2(4000 CHAR),"APPLICATION_METADATA" "APPLICATION_METADATA413_T","APPLICATION_DETAILS" "APPLICATION_DETAILS427_T","HMRC_DETAILS" "HMRC_DETAILS458_T","STAKEHOLDER_ROLE_LIST" "STAKEHOLDER_ROLE_LIST461_T","F680_QUESTIONS_SECTION" "F680_QUESTIONS_SECTION464_T","EXPORT_GOODS" "EXPORT_GOODS486_T","DECLARATION_SECTION" "DECLARATION_SECTION559_T","COUNTRY_LIST" "COUNTRY_LIST562_T","COUNTRY_ERROR_LIST" "COUNTRY_ERROR_LIST610_T","ROUTING_SECTION" "ROUTING_SECTION615_T","QUESTIONS_SECTION" "QUESTIONS_SECTION627_T","VIEW_ONLY_SECTIONS" "VIEW_ONLY_SECTIONS710_T","DOCUMENTS_SECTION" "DOCUMENTS_SECTION715_T","APPLICATION_FLAGS" "APPLICATION_FLAGS723_T","CASE_DETAILS" "CASE_DETAILS726_T","GOODS_RATING" "GOODS_RATING829_T","AMENDMENT_DETAILS" "AMENDMENT_DETAILS831_T","NOTES_TO_APPLICANT_LIST" "NOTES_TO_APPLICANT_LIST846_T")FINAL INSTANTIABLE 

/
