--------------------------------------------------------
--  DDL for Type STAKEHOLDER324_T
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TYPE "XVIEWMGR"."STAKEHOLDER324_T" AS OBJECT ("SYS_XDBPD$" "XDB"."XDB$RAW_LIST_T","foxid" VARCHAR2(4000 CHAR),"STAKEHOLDER_ID" "STAKEHOLDER_ID325_T","STAKEHOLDER_COMPOSITION" "STAKEHOLDER_COMPOSITION326_T","IMMUTABLE_FLAG" "IMMUTABLE_FLAG327_T","PERSON_DETAILS" "PERSON_DETAILS328_T","ORGANISATION_UNIT" "ORGANISATION_UNIT334_T","LICENSEE_SITE" "LICENSEE_SITE355_T","STAKEHOLDER_ADDRESS" "STAKEHOLDER_ADDRESS356_T","STAKEHOLDER_COUNTRY" "STAKEHOLDER_COUNTRY357_T","WEBSITE_LIST" "WEBSITE_LIST358_T","STAKEHOLDER_NATURE_OF_BUSINESS" "STAKEHOLDER_NATURE_OF_B363_T","DISTRIBUTION_EMAIL_LIST" "DISTRIBUTION_EMAIL_LIST364_T","TELEPHONE_NO_LIST" "TELEPHONE_NO_LIST372_T","ROLE_DESCRIPTION" "ROLE_DESCRIPTION380_T","RELATIONSHIP_DESCRIPTION" "RELATIONSHIP_DESCRIPTIO381_T","RECIPIENT_TYPE_LIST" "RECIPIENT_TYPE_LIST382_T","UK_ENTITY" "UK_ENTITY385_T","LIST_X" "LIST_X386_T","MISC_TEXT" "MISC_TEXT387_T","BIN" "BIN388_T","OUTCOME_DECISION" "OUTCOME_DECISION390_T","OUTCOME_STATUS" "OUTCOME_STATUS391_T","DC_ID" "DC_ID392_T","IS_ID" "IS_ID393_T","NOTIFICATION_DETAIL_LIST" "NOTIFICATION_DETAIL_LIS394_T")FINAL INSTANTIABLE 

/
