--------------------------------------------------------
--  DDL for Type SUMMARY727_T
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TYPE "XVIEWMGR"."SUMMARY727_T" AS OBJECT ("SYS_XDBPD$" "XDB"."XDB$RAW_LIST_T","foxid" VARCHAR2(4000 CHAR),"RECIPIENT_COUNTRY_GROUP_LIST" "RECIPIENT_COUNTRY_GROUP728_T","QUERY_RUN" "QUERY_RUN733_T","DOCUMENT_COMPOSITION" "DOCUMENT_COMPOSITION734_T")FINAL INSTANTIABLE 

/
