--------------------------------------------------------
--  DDL for Type TEMPORARY_EXPORTS628_T
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TYPE "XVIEWMGR"."TEMPORARY_EXPORTS628_T" AS OBJECT ("SYS_XDBPD$" "XDB"."XDB$RAW_LIST_T","foxid" VARCHAR2(4000 CHAR),"EXCLUSIVE_TEMPORARY_EXPORT" "EXCLUSIVE_TEMPORARY_EXP629_T","PRECISE_PURPOSE" "PRECISE_PURPOSE630_T","EXPORTERS_CONTROL" "EXPORTERS_CONTROL631_T","WHO_IS_INCHARGE" "WHO_IS_INCHARGE632_T","DATE_OF_RETURN" "DATE_OF_RETURN633_T","HOW_RETURNED" "HOW_RETURNED634_T")FINAL INSTANTIABLE 

/
