--------------------------------------------------------
--  DDL for Type TYPE_STAKEHOLDER_ROLE321_T
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TYPE "XVIEWMGR"."TYPE_STAKEHOLDER_ROLE321_T" AS OBJECT ("SYS_XDBPD$" "XDB"."XDB$RAW_LIST_T","STAKEHOLDER_ROLE_TYPE" "STAKEHOLDER_ROLE_TYPE322_T","STAKEHOLDER_LIST" "STAKEHOLDER_LIST323_T")NOT FINAL INSTANTIABLE 

/
