--------------------------------------------------------
--  DDL for Type TYPE_WORKBASKET_OBJ
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TYPE "ENVMGR"."TYPE_WORKBASKET_OBJ" AS
object
  (ID NUMBER(12),
   FOLDER_ID VARCHAR2(50),
   MATRIX_REF VARCHAR2(50),
   ENTRY_TYPE VARCHAR2(12),
   ENTRY_ID NUMBER(12),
   ENTRY_VARIATION_NO NUMBER(8),
   ENTRY_VERSION_NO NUMBER(8),
   SUBJECT VARCHAR2(4000),
   TOPIC VARCHAR2(4000),
   ORGANISATION_NAME VARCHAR2(100),
   ORGANISATION_SHORT_NAME VARCHAR2(12),
   ORGANISATION_ID NUMBER(12),
   ENTRY_STATUS_DESCRIPTION VARCHAR2(4000),
   COMPLETION_DATE DATE,
   COMPLETION_DATE_TYPE VARCHAR2(5),
   ACTION_LIST varchar2(4000))

/
