--------------------------------------------------------
--  DDL for Type URGENT_JUSTIFICATION475_T
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TYPE "XVIEWMGR"."URGENT_JUSTIFICATION475_T" AS OBJECT ("SYS_XDBPD$" "XDB"."XDB$RAW_LIST_T","foxid" VARCHAR2(4000 CHAR),"CLEARANCE_DATE_REQUESTED" "CLEARANCE_DATE_REQUESTE476_T","URGENT_CLEARANCE_JUSTIFICATION" "URGENT_CLEARANCE_JUSTIF477_T")FINAL INSTANTIABLE 

/
