--------------------------------------------------------
--  DDL for Type URGENT_CLEARANCE473_T
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TYPE "XVIEWMGR"."URGENT_CLEARANCE473_T" AS OBJECT ("SYS_XDBPD$" "XDB"."XDB$RAW_LIST_T","foxid" VARCHAR2(4000 CHAR),"URGENT_CLEARANCE_REQUEST" "URGENT_CLEARANCE_REQUES474_T","URGENT_JUSTIFICATION" "URGENT_JUSTIFICATION475_T")FINAL INSTANTIABLE 

/
