--------------------------------------------------------
--  DDL for Type VIEW_ONLY_SECTIONS710_T
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TYPE "XVIEWMGR"."VIEW_ONLY_SECTIONS710_T" AS OBJECT ("SYS_XDBPD$" "XDB"."XDB$RAW_LIST_T","foxid" VARCHAR2(4000 CHAR),"GOODS_LIST" "GOODS_LIST711_T","GOODS_USAGE" "GOODS_USAGE712_T","SOURCE_AND_RECIPIENT" "SOURCE_AND_RECIPIENT713_T","ITEM_LOCATION_AND_DESTINATION" "ITEM_LOCATION_AND_DESTI714_T")FINAL INSTANTIABLE 

/
