--------------------------------------------------------
--  DDL for Type XV_ADVICE_TYPES_TYPE
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TYPE "XVIEWMGR"."XV_ADVICE_TYPES_TYPE" IS OBJECT (
  ADVICE_TYPE VARCHAR2(30)
, ADVICE_TITLE VARCHAR2(255)
, ADMINISTRATIVE_BODY VARCHAR2(200)
, ADMINISTRATIVE_COMMUNITY VARCHAR2(200)
, ALLOW_ADVICE_REQUEST_DETAILS VARCHAR2(200)
)

/
