--------------------------------------------------------
--  DDL for Type XV_AUTH_REQ_TYPE
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TYPE "XVIEWMGR"."XV_AUTH_REQ_TYPE" IS OBJECT (
  AR_ID NUMBER
, OBJECT_UREF VARCHAR2(50)
, PRIORITY VARCHAR2(6)
, PFA_TITLE VARCHAR2(4000)
, PFA_TRANSACTION_REF VARCHAR2(4000)
, PFA_PRIMARY_DATA_UREF VARCHAR2(50)
, EVENT_PRIMARY_DATA_UREF VARCHAR2(50)
, SIGN VARCHAR2(5)
, SIGN_WITHOUT_PLACEHOLDERS VARCHAR2(5)
, TRANSFER_TO_MATRIX VARCHAR2(5)
, UPDATE_AFTER_FILING VARCHAR2(5)
, LOCATION VARCHAR2(4000)
, REASON VARCHAR2(4000)
, WUA_ID NUMBER(12, 0)
)

/
