--------------------------------------------------------
--  DDL for Type XV_BPD_ACTIONS_TYPE
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TYPE "XVIEWMGR"."XV_BPD_ACTIONS_TYPE" IS OBJECT (
  BPD_ID NUMBER(12, 0)
, ACTION_MNEM VARCHAR2(200)
, DEFAULT_PROMPT VARCHAR2(60)
, DESCRIPTION VARCHAR2(200)
, ACTION_TYPE CHAR(3)
, ACTION_SOURCE_CODE CLOB
, PANEL_ACTION_SOURCE_CODE CLOB
, METADATA_XML SYS.XMLTYPE
, FOX_SERVICES_RESTRICTION VARCHAR2(500)
)

/
