--------------------------------------------------------
--  DDL for Type XV_BPD_DELEG_TYPE
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TYPE "XVIEWMGR"."XV_BPD_DELEG_TYPE" IS OBJECT (
  BP_ID NUMBER(12, 0)
, DELEGATION VARCHAR2(4000)
, DELEGATION_TYPE VARCHAR2(4000)
, ALLOW_REASSIGN VARCHAR2(4000)
, ALLOW_UNASSIGN VARCHAR2(4000)
, ALLOW_STEAL VARCHAR2(4000)
, DELEGATION_XML SYS.XMLTYPE
)

/
