--------------------------------------------------------
--  DDL for Type XV_BPD_STAACTSET_TYPE
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TYPE "XVIEWMGR"."XV_BPD_STAACTSET_TYPE" IS OBJECT (
  BP_ID NUMBER(12, 0)
, PROCESS_SHORT_NAME VARCHAR2(200)
, STAGE_LABEL VARCHAR2(200)
, ACTION_SET_MNEM VARCHAR2(200)
, ACTION_DATA SYS.XMLTYPE
, CONDITION_XML SYS.XMLTYPE
, ACTION_OVERLAY_XML SYS.XMLTYPE
, ACTION_SET_MNEM_COMPOSITE VARCHAR2(200)
)

/
