--------------------------------------------------------
--  DDL for Type XV_BPD_TRANSITION_TYPE
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TYPE "XVIEWMGR"."XV_BPD_TRANSITION_TYPE" IS OBJECT (
  BP_ID NUMBER(12, 0)
, PROCESS_SHORT_NAME VARCHAR2(4000)
, TRANSITION_LABEL VARCHAR2(4000)
, CONTEXT_SET_XML SYS.XMLTYPE
, IN_TRANSITION_XML SYS.XMLTYPE
, BEFORE_TRANSITION_XML SYS.XMLTYPE
, AFTER_TRANSITION_XML SYS.XMLTYPE
)

/
