--------------------------------------------------------
--  DDL for Type XV_BPD_TALLIES_TYPE
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TYPE "XVIEWMGR"."XV_BPD_TALLIES_TYPE" IS OBJECT (
  BPD_ID NUMBER(12, 0)
, PROCESS_SHORT_NAME VARCHAR2(30)
, TALLY VARCHAR2(30)
, INTERNAL_TALLY VARCHAR2(30)
, BPD_TALLY_TYPE VARCHAR2(20)
, TALLY_TYPE_DEFINITION VARCHAR2(4000)
, ROOT_TALLY VARCHAR2(30)
, SWITCH VARCHAR2(30)
, STAGE_LABEL VARCHAR2(200)
, SUBROUTINE_SHORT_NAME VARCHAR2(200)
, QUERY CLOB
)

/
