--------------------------------------------------------
--  DDL for Type XV_BUSINESS_CTX_TYPE
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TYPE "XVIEWMGR"."XV_BUSINESS_CTX_TYPE" IS OBJECT (
  BC_ID NUMBER(12, 0)
, PARENT_BC_ID NUMBER(12, 0)
, CONTEXT_NAME VARCHAR2(200)
, PRIMARY_DATA_UREF VARCHAR2(200)
, SECONDARY_DATA_UREF VARCHAR2(200)
, TERTIARY_DATA_UREF VARCHAR2(200)
, ACTIVITY_DATA_UREF VARCHAR2(200)
, DOCUMENT_SET_UREF VARCHAR2(200)
, NOTIFICATION_ID NUMBER(12, 0)
)

/
