--------------------------------------------------------
--  DDL for Type XV_BPD_ASSIGNMENTS_TYPE
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TYPE "XVIEWMGR"."XV_BPD_ASSIGNMENTS_TYPE" IS OBJECT (
  BP_ID NUMBER(12, 0)
, PROCESS_SHORT_NAME VARCHAR2(200)
, ASSIGNMENT_TYPE VARCHAR2(30)
, ASSIGNMENT VARCHAR2(200)
, ASSIGNMENT_TITLE VARCHAR2(200)
, DELEGATION VARCHAR2(200)
, STAGE_LABEL VARCHAR2(200)
, SUBROUTINE_SHORT_NAME VARCHAR2(200)
, CONDITION_XML SYS.XMLTYPE
)

/
