--------------------------------------------------------
--  DDL for Type XV_BUSINESS_STAGES_TYPE
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TYPE "XVIEWMGR"."XV_BUSINESS_STAGES_TYPE" IS OBJECT (
  BS_ID NUMBER(12, 0)
, START_DATETIME DATE
, END_DATETIME DATE
, BP_ID NUMBER(12, 0)
, BA_ID NUMBER(12, 0)
, BRC_ID NUMBER(12, 0)
, STAGE_LABEL VARCHAR2(30)
, STAGE_STATUS VARCHAR2(200)
, ACTION_DESC_STAGE VARCHAR2(4000)
, PRIMARY_DATA_UREF VARCHAR2(200)
, FINAL_SUPER_ROUTINE_STATUS VARCHAR2(4000)
)

/
