--------------------------------------------------------
--  DDL for Type XV_BPD_TRANMOVES_TYPE
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TYPE "XVIEWMGR"."XV_BPD_TRANMOVES_TYPE" IS OBJECT (
  BP_ID NUMBER(12, 0)
, PROCESS_SHORT_NAME VARCHAR2(200)
, TRANSITION_LABEL VARCHAR2(200)
, BEFORE_AFTER CHAR(1)
, CNO NUMBER(12, 0)
, STAGE_LABEL VARCHAR2(200)
, INVOKER_THIS VARCHAR2(50)
, INVOKER_SIBLING VARCHAR2(50)
, INVOKER_SIGNAL VARCHAR2(50)
, AFTER_EXISTS VARCHAR2(50)
, RETURN_ENVIRONMENT VARCHAR2(4000)
)

/
