--------------------------------------------------------
--  DDL for Type XV_BPD_OPERATIONS_TYPE
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TYPE "XVIEWMGR"."XV_BPD_OPERATIONS_TYPE" IS OBJECT (
  BPD_ID NUMBER(12, 0)
, BP_ID NUMBER(12, 0)
, BPD_FULL_NAME VARCHAR2(4000)
, EVENT_LABEL VARCHAR2(4000)
, OPERATION_TYPE VARCHAR2(7)
, OPERATION_NAME VARCHAR2(4000)
, OPERATION_XML SYS.XMLTYPE
)

/
