--------------------------------------------------------
--  DDL for Type XV_BUSINESS_ACT_TYPE
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TYPE "XVIEWMGR"."XV_BUSINESS_ACT_TYPE" IS OBJECT (
  BA_ID NUMBER(12, 0)
, ACTIVITY_REF VARCHAR2(30)
, TITLE VARCHAR2(50)
, STATUS VARCHAR2(30)
, START_DATETIME DATE
, END_DATETIME DATE
, BT_ID NUMBER(12, 0)
, TYPE VARCHAR2(30)
, ACTION_DESC_ACTIVITY VARCHAR2(30)
, ACTIVITY_NOTES VARCHAR2(4000)
, SECONDARY_DATA_UREF VARCHAR2(20)
)

/
