--------------------------------------------------------
--  DDL for Type XV_BPD_STAGES_TYPE
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TYPE "XVIEWMGR"."XV_BPD_STAGES_TYPE" IS OBJECT (
  BPD_ID NUMBER(12, 0)
, BP_ID NUMBER(12, 0)
, PROCESS_SHORT_NAME VARCHAR2(200)
, STAGE_LABEL VARCHAR2(200)
, STAGE_TYPE VARCHAR2(60)
, STAGE_TITLE VARCHAR2(200)
, ACTION_DESC_STAGE VARCHAR2(4000)
, STAGE_XML SYS.XMLTYPE
, SUBROUTINE_SHORT_NAME VARCHAR2(200)
, STAGE_CLASSIFICATION VARCHAR2(4000)
)

/
