--------------------------------------------------------
--  DDL for Type XV_COUNTRY_DETAILS_TYPE
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TYPE "XVIEWMGR"."XV_COUNTRY_DETAILS_TYPE" IS OBJECT (
  COUNTRY_DETAIL_ID NUMBER
, COUNTRY_ID NUMBER(12, 0)
, COUNTRY_SET_ID VARCHAR2(15)
, END_DATETIME DATE
, COUNTRY_NAME VARCHAR2(4000)
, COUNTRY_STATUS VARCHAR2(4000)
, COUNTRY_TYPE VARCHAR2(4000)
)

/
