--------------------------------------------------------
--  DDL for Type XV_CLAUSE_TYPES_TYPE
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TYPE "XVIEWMGR"."XV_CLAUSE_TYPES_TYPE" IS OBJECT (
  CLAUSE_TYPE_ID VARCHAR2(30)
, CLAUSE_TITLE VARCHAR2(200)
, CLASS_TYPE VARCHAR2(30)
, CLASS_TITLE VARCHAR2(200)
, CLASS_DESCRIPTION VARCHAR2(500)
, SEVERITY_CODE VARCHAR2(30)
, SEVERITY_TITLE VARCHAR2(200)
, SEVERITY_DESCRIPTION VARCHAR2(500)
, INTENTION_DEFAULT_STATUS VARCHAR2(30)
, REASON_REQUIRED VARCHAR2(30)
, DELETABLE VARCHAR2(30)
, EDITABLE VARCHAR2(30)
, CLEARABLE VARCHAR2(30)
, VOIDABLE VARCHAR2(5)
, EVENT_REQUEST VARCHAR2(100)
, EVENT_RESPOND VARCHAR2(100)
, EVENT_REJECT VARCHAR2(100)
, EVENT_REQUEST_CONFIRM_TEXT VARCHAR2(400)
, EVENT_RESPOND_CONFIRM_TEXT VARCHAR2(400)
, EVENT_REJECT_CONFIRM_TEXT VARCHAR2(400)
, INTENTION_TYPE VARCHAR2(15)
, DISPLAY_COLOUR VARCHAR2(100)
, REQUEST_DEFINE_OWN_CONTEXT VARCHAR2(5)
, RESPOND_DEFINE_OWN_CONTEXT VARCHAR2(5)
, REJECT_DEFINE_OWN_CONTEXT VARCHAR2(5)
, VOIDABLE_ANYTIME_BY_CREATOR VARCHAR2(5)
, DEFINE_COUNTERSIGN_RECIPIENT VARCHAR2(5)
, LINKED_ESCALATE_FLAG VARCHAR2(30)
, RFI_IMMEDIATELY_CLOSABLE VARCHAR2(5)
)

/
