--------------------------------------------------------
--  DDL for Type XV_CMP_VST_ACT_TYPE
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TYPE "XVIEWMGR"."XV_CMP_VST_ACT_TYPE" IS OBJECT (
  VISIT_ID NUMBER
, DESCRIPTION VARCHAR2(4000)
, STATUS VARCHAR2(4000)
, TYPE VARCHAR2(4000)
, EXP_STATUS VARCHAR2(4000)
, RESPONSE VARCHAR2(4000)
, RESOLUTION VARCHAR2(4000)
, CLOSED_DATE DATE
, RESPONSE_DATE DATE
, PUBLISH_DATE DATE
)

/
