--------------------------------------------------------
--  DDL for Type XV_COMPL_ACT_DTLS_TYPE
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TYPE "XVIEWMGR"."XV_COMPL_ACT_DTLS_TYPE" IS OBJECT (
  CAD_ID NUMBER(12, 0)
, CA_ID NUMBER
, START_DATETIME DATE
, END_DATETIME DATE
, STATUS_CONTROL VARCHAR2(1)
, STATUS VARCHAR2(50)
, FF_ID NUMBER
, CREATED_DATETIME DATE
, CREATED_BY_WUA_ID NUMBER
, CREATED_BY_FULL_NAME VARCHAR2(400)
, ACTIVATED_DATETIME DATE
, ACTIVATED_BY_WUA_ID NUMBER
, ACTIVATED_BY_FULL_NAME VARCHAR2(400)
, ACTIVITY_TYPE VARCHAR2(50)
, WARNING_NUMBER NUMBER
)

/
