--------------------------------------------------------
--  DDL for Type XV_CTRY_GRP_DTLS_TYPE
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TYPE "XVIEWMGR"."XV_CTRY_GRP_DTLS_TYPE" IS OBJECT (
  COUNTRY_GROUP_DETAIL_ID NUMBER(12, 0)
, COUNTRY_GROUP_ID VARCHAR2(15)
, END_DATETIME DATE
, COUNTRY_SET_ID VARCHAR2(15)
, GROUP_NAME VARCHAR2(4000)
, GROUP_STATUS VARCHAR2(4000)
, GROUP_TYPE VARCHAR2(4000)
, GROUP_COMMENTS VARCHAR2(4000)
)

/
