--------------------------------------------------------
--  DDL for Type XV_CMP_VISITS_TYPE
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TYPE "XVIEWMGR"."XV_CMP_VISITS_TYPE" IS OBJECT (
  VISIT_ID NUMBER
, STATUS VARCHAR2(4000)
, ACTIONS_STATUS VARCHAR2(4000)
, COMPLIANCE_ASSESSMENT VARCHAR2(4000)
, PROPOSED_VISIT_DATE DATE
, ACTUAL_VISIT_DATE DATE
, NEXT_VISIT_DATE DATE
, CREATED_DATETIME DATE
, CREATED_BY_WUA_ID NUMBER
, CREATED_BY_NAME VARCHAR2(4000)
, UPDATED_DATETIME DATE
, UPDATED_BY_WUA_ID NUMBER
, UPDATED_BY_NAME VARCHAR2(4000)
, APPROVED_DATETIME DATE
, APPROVED_BY_WUA_ID NUMBER
, APPROVED_BY_NAME VARCHAR2(4000)
, COMPLETED_DATETIME DATE
, COMPLETED_BY_WUA_ID NUMBER
, COMPLETED_BY_NAME VARCHAR2(4000)
, CLOSED_DATETIME DATE
, CLOSED_BY_WUA_ID NUMBER
, CLOSED_BY_NAME VARCHAR2(4000)
, DELETED_DATETIME DATE
, DELETED_BY_WUA_ID NUMBER
, DELETED_BY_NAME VARCHAR2(4000)
, CANCELLED_DATETIME DATE
, CANCELLED_BY_WUA_ID NUMBER
, CANCELLED_BY_NAME VARCHAR2(4000)
, CANCELLED_REASON VARCHAR2(4000)
, RES_ID VARCHAR2(4000)
, FTF_ID_REG VARCHAR2(4000)
, FTF_ID_EXP VARCHAR2(4000)
, SAR_ID VARCHAR2(4000)
, PREPARATION_NOTES VARCHAR2(4000)
, MSG_TO_ADMIN VARCHAR2(4000)
, MSG_FOR_NEXT_VISIT VARCHAR2(4000)
, HMRC_NOTIFIED_FLAG VARCHAR2(5)
)

/
