--------------------------------------------------------
--  DDL for Type XV_DN_ENTITIES_TYPE
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TYPE "XVIEWMGR"."XV_DN_ENTITIES_TYPE" IS OBJECT (
  DD_ID NUMBER
, D_ID NUMBER
, ENTITY_ID NUMBER
, ENTITY_NAME VARCHAR2(350)
, ADDRESS VARCHAR2(1000)
, COUNTRY_ID NUMBER
, POSTCODE VARCHAR2(20)
, PROCESSED_ENTITY_DETAILS VARCHAR2(1400)
, TEL VARCHAR2(30)
, FAX VARCHAR2(30)
, END_USER_FLAG VARCHAR2(10)
, CONSIGNEE_FLAG VARCHAR2(10)
, OTHER_ROLE VARCHAR2(200)
)

/
