--------------------------------------------------------
--  DDL for Type XV_DN_REGIMES_TYPE
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TYPE "XVIEWMGR"."XV_DN_REGIMES_TYPE" IS OBJECT (
  DD_ID NUMBER
, D_ID NUMBER
, REGIME_CODE VARCHAR2(20)
, DN_TYPE VARCHAR2(5)
, REGIME_REG_REF VARCHAR2(100)
, PROCESSED_REGIME_REG_REF VARCHAR2(100)
, POC_NUMBER VARCHAR2(100)
, ACTIVE_FROM_DATE DATE
, REGIME_DENIAL_STATUS VARCHAR2(10)
, RATING_REFS VARCHAR2(100)
, REGIME_REFS VARCHAR2(1000)
, REASON_FOR_REFUSAL VARCHAR2(4000)
, NOTIFICATION_COMMENTS VARCHAR2(4000)
, REVOKE_COM_OUTBOUND_REF VARCHAR2(200)
, REVOKE_COM_INBOUND_REF VARCHAR2(200)
, REVOKE_ISSUED_DATE DATE
, EXPIRED_DATE DATE
)

/
