--------------------------------------------------------
--  DDL for Type XV_DOC_INTS_TYPE
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TYPE "XVIEWMGR"."XV_DOC_INTS_TYPE" IS OBJECT (
  DI_ID NUMBER(12, 0)
, DP_ID NUMBER(12, 0)
, DISPLAY_SEQUENCE NUMBER(4, 0)
, TITLE VARCHAR2(250)
, OU_ID NUMBER
, ORGAN_NAME VARCHAR2(4000)
, REGISTERED_NUMBER VARCHAR2(4000)
, DOCUMENT_TYPE VARCHAR2(4000)
, SUPPRESS_MATRIX_TITLE VARCHAR2(10)
)

/
