--------------------------------------------------------
--  DDL for Type XV_DOC_PACK_RECIP_TYPE
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TYPE "XVIEWMGR"."XV_DOC_PACK_RECIP_TYPE" IS OBJECT (
  DP_ID NUMBER(12, 0)
, AUDIENCE_TYPE VARCHAR2(30)
, AUDIENCE_TITLE VARCHAR2(200)
, FULL_NAME VARCHAR2(200)
, MEMBER_ID NUMBER(12, 0)
, PERSON_ID NUMBER(12, 0)
, ADDRESS_ID NUMBER(12, 0)
, LOCATION_AT_ADDRESS VARCHAR2(200)
, NOTIFICATION_DATE DATE
, LETTER_FLAG VARCHAR2(10)
)

/
