--------------------------------------------------------
--  DDL for Type XV_DOC_DATA_TYPE
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TYPE "XVIEWMGR"."XV_DOC_DATA_TYPE" IS OBJECT (
  DD_ID NUMBER(12, 0)
, DI_ID NUMBER(12, 0)
, STATUS VARCHAR2(12)
, DD_IMMUTABLE_ID NUMBER(12, 0)
, DISPLAY_SEQ NUMBER(12, 0)
, TITLE VARCHAR2(4000)
, CONTENT_TYPE VARCHAR2(4000)
, CONTENT_DESCRIPTION VARCHAR2(4000)
, SYSTEM_DOCUMENT VARCHAR2(4000)
, OU_ID NUMBER(12, 0)
, ORGAN_NAME VARCHAR2(4000)
, REGISTERED_NUMBER VARCHAR2(4000)
)

/
