--------------------------------------------------------
--  DDL for Type XV_DOC_PACKS_TYPE
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TYPE "XVIEWMGR"."XV_DOC_PACKS_TYPE" IS OBJECT (
  DP_ID NUMBER(12, 0)
, DS_ID NUMBER(12, 0)
, OU_ID NUMBER
, CHECKED VARCHAR2(6)
, AUTHORISED VARCHAR2(6)
, ISSUED VARCHAR2(6)
, DOCUMENT_PACK_TYPE VARCHAR2(4000)
, DOCUMENT_PACK_TITLE VARCHAR2(4000)
, PERSON_ID NUMBER
, RECIPIENT_DATA_UREF VARCHAR2(50)
)

/
