--------------------------------------------------------
--  DDL for Type XV_ELA_NOTIFS_TYPE
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TYPE "XVIEWMGR"."XV_ELA_NOTIFS_TYPE" IS OBJECT (
  ELA_DETAIL_ID NUMBER
, STAKEHOLDER_ID NUMBER(12, 0)
, OUTCOME_DECISION VARCHAR2(500)
, IS_ID NUMBER(12, 0)
, DC_ID NUMBER(12, 0)
, CLEARANCE_LIST SYS.XMLTYPE
, F680_DURATION NUMBER(12, 0)
, REASON_FOR_REFUSAL VARCHAR2(50)
, DI_ID NUMBER(12, 0)
, NOTIFICATION_DATE DATE
, ISSUING_WUA_ID NUMBER(12, 0)
, CLEARED_SECURITY VARCHAR2(50)
)

/
