--------------------------------------------------------
--  DDL for Type XV_ELA_STKHLDS_TYPE
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TYPE "XVIEWMGR"."XV_ELA_STKHLDS_TYPE" IS OBJECT (
  ELA_DETAIL_ID NUMBER(12, 0)
, SH_ID NUMBER(12, 0)
, ROLE_TYPE VARCHAR2(50)
, COMPOSITION VARCHAR2(100)
, ROLE_DESCRIPTION VARCHAR2(500)
, PD_TITLE VARCHAR2(100)
, PD_FORENAME VARCHAR2(500)
, PD_MIDDLE_INITIALS VARCHAR2(500)
, PD_SURNAME VARCHAR2(500)
, PD_JOB_DESCRIPTION VARCHAR2(500)
, ORG_ID NUMBER(12, 0)
, ORG_NAME VARCHAR2(1000)
, ORG_VAT_NUMBER VARCHAR2(100)
, ORG_REGISTERED_NUMBER VARCHAR2(100)
, ORG_REGISTERED_ADDRESS_ID NUMBER(12, 0)
, ORG_REGISTERED_ADDRESS VARCHAR2(500)
, ORG_OCD_COUNTRY_OF_ORIGIN VARCHAR2(500)
, ORG_OCD_PARENT_REG_NAME VARCHAR2(500)
, ORG_OCD_PRNT_REG_COMP_REF VARCHAR2(500)
, ORG_OCD_PRNT_REG_COMMENT VARCHAR2(500)
, ORG_COMP_DET_ACC_COMMENTS VARCHAR2(500)
, ADDRESS VARCHAR2(700)
, POSTCODE VARCHAR2(200)
, COUNTRY NUMBER(12, 0)
, NATURE_OF_BUSINESS VARCHAR2(500)
, RELATIONSHIP_DESCRIPTION VARCHAR2(500)
, MISC_TEXT VARCHAR2(4000)
, FORMATTED_NAME VARCHAR2(500)
, END_USER_FLAG VARCHAR2(5)
, CONSIGNEE_FLAG VARCHAR2(5)
, XML_DATA SYS.XMLTYPE
, THIRD_PARTY_FLAG VARCHAR2(5)
, OUTCOME_DECISION VARCHAR2(20)
, OUTCOME_STATUS VARCHAR2(50)
, APPROVAL_COMMENT VARCHAR2(4000)
, APPROVAL_FLAG VARCHAR2(20)
, DC_ID NUMBER(12, 0)
, IS_ID NUMBER(12, 0)
, FIRST_NOTIFICATION_DATE DATE
, LAST_NOTIFICATION_DATE DATE
, RECIPIENT_END_USER_TYPE VARCHAR2(100)
, REVOKE_SUSPEND_ACTION VARCHAR2(15)
)

/
