--------------------------------------------------------
--  DDL for Type XV_ELA_DETAILS_TYPE
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TYPE "XVIEWMGR"."XV_ELA_DETAILS_TYPE" IS OBJECT (
  ELA_DETAIL_ID NUMBER
, ELA_ID NUMBER
, START_DATE DATE
, END_DATE DATE
, STATUS VARCHAR2(12)
, STATUS_FORMATTED VARCHAR2(100)
, EXCLUSIVE_TEMPORARY_EXPORTS VARCHAR2(5)
, CASE_CLOSED_REASON VARCHAR2(100)
, CASE_CLOSED_DATETIME DATE
, CASE_CLOSED_BY_NAME VARCHAR2(200)
, CASE_CLOSED_BY_WUA_ID NUMBER(12, 0)
, AMENDMENT_FLAG VARCHAR2(5)
, APPEAL_FLAG VARCHAR2(5)
, MAJOR_AMENDMENT_FLAG VARCHAR2(5)
, PRECIRC_CORRECTION_FLAG VARCHAR2(5)
, TAU_CORRECTION_FLAG VARCHAR2(5)
, APPLICATION_TURN_NO VARCHAR2(100)
, LEGACY_APP_REF VARCHAR2(100)
, DTI_REF VARCHAR2(100)
, APPLICANT_REF VARCHAR2(200)
, APPLICATION_TYPE VARCHAR2(100)
, APPLICATION_SUB_TYPE VARCHAR2(100)
, APPLICATION_TYPE_FORMATTED VARCHAR2(100)
, CREATED_DATETIME DATE
, CREATED_BY_NAME VARCHAR2(200)
, CREATED_BY_WUA_ID NUMBER(12, 0)
, UPDATED_DATETIME DATE
, UPDATED_BY_NAME VARCHAR2(200)
, UPDATED_BY_WUA_ID NUMBER(12, 0)
, SNAPSHOT_REASON VARCHAR2(200)
, SUBMITTED_DATETIME DATE
, FILE_FOLDER NUMBER(12, 0)
, CASE_FILE_FOLDER NUMBER(12, 0)
, ACCESS_EXTERNAL VARCHAR2(1)
, ACCESS_INTERNAL VARCHAR2(1)
, SAR_ID NUMBER
, SITE_ID NUMBER
, INCORPORATION_FLAG VARCHAR2(5)
, TARGET_DATE DATE
, CLEARANCE_LIST VARCHAR2(4000)
, PROPOSED_SECURITY_CLASS VARCHAR2(250)
, PROP_SEC_CLASS_OTHER_TEXT VARCHAR2(4000)
, GOODS_RATING_TAU_COMMENT VARCHAR2(4100)
, EU_CONSULTATION_FLAG VARCHAR2(5)
, EU_CONSULTATION_START_DATE DATE
, EU_CONSULTATION_END_DATE DATE
, DSO_REPORT_FLAG VARCHAR2(5)
, SECURITY_CLASS VARCHAR2(250)
, SECURITY_CLASS_OTHER_TEXT VARCHAR2(4000)
, FUNDING_SOURCE VARCHAR2(20)
, F680_APP_REASON_OGEL_FLAG VARCHAR2(5)
, PREVIOUS_APPLICATION_LIST VARCHAR2(4000)
, EUAS_OUTCOME VARCHAR2(4000)
, VALUE_OF_PROSPECT NUMBER
, RENEWAL_FLAG VARCHAR2(5)
, GOODS_AMENDMENT_TYPE VARCHAR2(20)
, GOODS_AMENDMENT_AUTH_WUA_ID NUMBER
)

/
