--------------------------------------------------------
--  DDL for Type XV_ELA_GDS_CNTRY_TYPE
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TYPE "XVIEWMGR"."XV_ELA_GDS_CNTRY_TYPE" IS OBJECT (
  ELA_DETAIL_ID NUMBER(12, 0)
, COUNTRY_ID NUMBER(12, 0)
, GOODS_ITEM_ID NUMBER(12, 0)
, DC_ID NUMBER(12, 0)
, SOURCE_FLAG VARCHAR2(5)
, DESTINATION_FLAG VARCHAR2(5)
, DESTINATION_OVERRIDE_FLAG VARCHAR2(5)
, OUTCOME VARCHAR2(4000)
, LD_ID NUMBER(12, 0)
, LICENCE_LINE_NUMBER NUMBER(12, 0)
, PRIOR_AMENDMENT_LD_ID NUMBER
)

/
