--------------------------------------------------------
--  DDL for Type XV_ELA_CNTRYS_TYPE
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TYPE "XVIEWMGR"."XV_ELA_CNTRYS_TYPE" IS OBJECT (
  ELA_DETAIL_ID NUMBER
, COUNTRY_ID NUMBER
, COUNTRY_NAME VARCHAR2(4000)
, SOURCE_FLAG VARCHAR2(5)
, RECIPIENT_FLAG VARCHAR2(5)
, REASON_FOR_CONTRACT_LIST SYS.XMLTYPE
, ULTIMATE_END_USER_FLAG VARCHAR2(5)
, OVERRIDE_OUTCOME VARCHAR2(6)
)

/
