--------------------------------------------------------
--  DDL for Type XV_FILE_TR_TYP_PRM_TYPE
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TYPE "XVIEWMGR"."XV_FILE_TR_TYP_PRM_TYPE" IS OBJECT (
  ID NUMBER
, TYPE_MNEM VARCHAR2(50)
, START_DATETIME DATE
, END_DATETIME DATE
, PARAMETER_NAME VARCHAR2(4000)
, EXTERNAL_NAME VARCHAR2(4000)
, PARAMETER_TYPE VARCHAR2(10)
, PAYLOAD_SEQUENCE NUMBER
)

/
