--------------------------------------------------------
--  DDL for Type XV_FILE_TGT_DEFS_TYPE
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TYPE "XVIEWMGR"."XV_FILE_TGT_DEFS_TYPE" IS OBJECT (
  FILE_FOLDER_TYPE VARCHAR2(30)
, TARGET_MNEM VARCHAR2(4000)
, TARGET_TITLE VARCHAR2(4000)
, DOWNLOAD_ONLY VARCHAR2(5)
, MIN_TARGETS NUMBER
, MAX_TARGETS NUMBER
, MIN_EMPTY_TARGETS NUMBER
, INIT_NUMBER_OF_TARGETS NUMBER
, DISPLAY_ORDER NUMBER
, LARGE_FILE_FLAG VARCHAR2(5)
, ENABLE_SHOW_HISTORY VARCHAR2(4000)
, ENABLE_DELETE VARCHAR2(4000)
)

/
