--------------------------------------------------------
--  DDL for Type XV_FOLDER_TYPES_TYPE
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TYPE "XVIEWMGR"."XV_FOLDER_TYPES_TYPE" IS OBJECT (
  FILE_FOLDER_TYPE VARCHAR2(30)
, TITLE VARCHAR2(4000)
, DESCRIPTION VARCHAR2(4000)
, VERSION_CONTROL_ENABLED VARCHAR2(100)
, DOWNLOAD_FILES_ARE_HIDEABLE VARCHAR2(5)
, UPLOAD_PROMPT VARCHAR2(4000)
, DOWNLOAD_PROMPT VARCHAR2(4000)
, SHOW_TARGET_STATUS VARCHAR2(4000)
, INTERNAL_SCAN_ENABLED VARCHAR2(5)
, EXTERNAL_SCAN_ENABLED VARCHAR2(5)
, SCAN_TYPE VARCHAR2(100)
, PRIMARY_PURPOSE VARCHAR2(100)
, SECONDARY_PURPOSE VARCHAR2(100)
, DEFAULT_EMAIL_TARGET VARCHAR2(4000)
)

/
