--------------------------------------------------------
--  DDL for Type XV_FILE_TRANS_TYPS_TYPE
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TYPE "XVIEWMGR"."XV_FILE_TRANS_TYPS_TYPE" IS OBJECT (
  ID NUMBER
, TYPE_MNEM VARCHAR2(50)
, START_DATETIME DATE
, END_DATETIME DATE
, TYPE_NAME VARCHAR2(4000)
, TYPE_DESCRIPTION VARCHAR2(4000)
, TRANSMISSION_METHOD VARCHAR2(20)
, TRANSMISSION_DIRECTION VARCHAR2(10)
, FAILURE_ALERT_EMAIL_ADDRESS VARCHAR2(4000)
, ASYNC_RESPONSE_REQUIRED_FLAG VARCHAR2(5)
, AUTHENTICATION_USERNAME VARCHAR2(4000)
, AUTHENTICATION_PASSWORD VARCHAR2(4000)
, PRE_TRANSMIT_PROCESSING_TYPE VARCHAR2(4000)
, POST_TRANSMIT_PLSQL CLOB
, FTP_SERVER VARCHAR2(4000)
, FTP_PORT NUMBER
, FTP_DIRECTORY VARCHAR2(4000)
, FTP_SEND_MD5_HASH_FLAG VARCHAR2(5)
, HTTP_URL VARCHAR2(4000)
, SOAP_TYPE VARCHAR2(8)
, SOAP_RPC_PROCEDURE_NAME VARCHAR2(4000)
, SOAP_BODY_NAMESPACE_NAME VARCHAR2(200)
, SOAP_ENVELOPE_TEMPLATE SYS.XMLTYPE
)

/
