--------------------------------------------------------
--  DDL for Type XV_GC_GCED_TYPE
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TYPE "XVIEWMGR"."XV_GC_GCED_TYPE" IS OBJECT (
  GCED_ID NUMBER
, GCE_ID NUMBER
, GCR_ID NUMBER
, STATUS VARCHAR2(10)
, START_DATETIME DATE
, END_DATETIME DATE
, STATUS_CONTROL VARCHAR2(1)
, LAST_MODIFIED_IN_REVISION NUMBER
, DESCRIPTION VARCHAR2(4000)
, CATEGORY VARCHAR2(4000)
, PARENT_GCE_ID NUMBER
, DEFINITION SYS.XMLTYPE
, BEFORE_CHILD_ITEM_TEXT SYS.XMLTYPE
, AFTER_CHILD_ITEM_TEXT SYS.XMLTYPE
, DISPLAY_ORDER NUMBER
)

/
