--------------------------------------------------------
--  DDL for Type XV_INTENTION_DTLS_TYPE
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TYPE "XVIEWMGR"."XV_INTENTION_DTLS_TYPE" IS OBJECT (
  ID_ID NUMBER(12, 0)
, IN_ID NUMBER(12, 0)
, STATUS VARCHAR2(50)
, START_DATETIME DATE
, END_DATETIME DATE
, CLAUSE_TYPE VARCHAR2(50)
, CLASS_TYPE VARCHAR2(400)
, SEVERITY VARCHAR2(400)
, REASON_CODE VARCHAR2(50)
, CLAUSE_ID NUMBER(12, 0)
, CLAUSE_STATUS VARCHAR2(50)
, DISPLAY_ORDER NUMBER(12, 0)
, DELETE_FLAG VARCHAR2(10)
, EDIT_FLAG VARCHAR2(10)
, CLEAR_FLAG VARCHAR2(10)
, CREATED_BY_WUA_ID VARCHAR2(4000)
, CREATED_BY_WUA_FULL_NAME VARCHAR2(400)
, CREATED_DATETIME DATE
, CLAUSE_TEXT SYS.XMLTYPE
, RESPONSE_TEXT SYS.XMLTYPE
, VOIDED_TEXT SYS.XMLTYPE
, IGNORE_FLAG VARCHAR2(10)
, IGNORE_TEXT VARCHAR2(200)
)

/
