--------------------------------------------------------
--  DDL for Type XV_NOTIF_SET_TYPE
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TYPE "XVIEWMGR"."XV_NOTIF_SET_TYPE" IS OBJECT (
  NS_ID NUMBER(12, 0)
, NOTIFICATION_DATE DATE
, NOTIFICATION_TYPE VARCHAR2(255)
, CREATED_WUA_ID NUMBER(12, 0)
, FOLDER_REF VARCHAR2(255)
, TRANSACTION_REF VARCHAR2(255)
, SUBJECT VARCHAR2(255)
, TOPIC VARCHAR2(255)
, CONSULTATION_STATUS VARCHAR2(10)
, DOC_REVIEW_TARGET VARCHAR2(200)
)

/
