--------------------------------------------------------
--  DDL for Type XV_NOTES_TYPE
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TYPE "XVIEWMGR"."XV_NOTES_TYPE" IS OBJECT (
  N_ID NUMBER(12, 0)
, SUBJECT VARCHAR2(80)
, NOTE_TYPE VARCHAR2(30)
, NOTE_STATUS VARCHAR2(4000)
, CREATED_BY_ID NUMBER(12, 0)
, CREATED_BY_FULL_NAME VARCHAR2(255)
, CREATED_DATETIME DATE
, UPDATED_BY_ID NUMBER(12, 0)
, UPDATED_BY_FULL_NAME VARCHAR2(255)
, UPDATED_STATUS VARCHAR2(30)
, UPDATED_DATETIME DATE
)

/
