--------------------------------------------------------
--  DDL for Type XV_OGL_TYPE_REV_TYPE
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TYPE "XVIEWMGR"."XV_OGL_TYPE_REV_TYPE" IS OBJECT (
  OGL_TYPE_CONDITION_DETAIL_ID NUMBER
, OGL_TYPE_CONDITION_ID NUMBER
, STATUS_CONTROL VARCHAR2(1)
, REVISION_ID NUMBER
, REVISION_VERSION NUMBER
, NAME VARCHAR2(4000)
, START_DATE DATE
, END_DATE DATE
, INTANGIBLE_DECLARATION VARCHAR2(5)
, OGL_DESCRIPTION SYS.XMLTYPE
, LINK_TO_OGL VARCHAR2(1000)
, OGL_TYPE VARCHAR2(4000)
, VIRTUAL_OGEL_FLAG VARCHAR2(10)
, OGL_ACTIVITY VARCHAR2(50)
, INCLUDE_IN_SEARCH VARCHAR2(1)
, CONDITION_LIST SYS.XMLTYPE
, RATING_CONDITION_LIST SYS.XMLTYPE
, MIGRATED_REVISION VARCHAR2(5)
, ENFORCED_DATE DATE
, EXPANDED_CONDITION_LIST SYS.XMLTYPE
)

/
