--------------------------------------------------------
--  DDL for Type XV_ORG_UNITS_TYPE
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TYPE "XVIEWMGR"."XV_ORG_UNITS_TYPE" IS OBJECT (
  OD_ID NUMBER(12, 0)
, ORGAN_ID NUMBER(8, 0)
, SHORT_NAME VARCHAR2(12)
, NAME VARCHAR2(200)
, NATIONALITY VARCHAR2(4)
, CREATED_BY_DEPT VARCHAR2(6)
, COMMENTS VARCHAR2(80)
, CREATED_BY VARCHAR2(30)
, CREATED_DATE DATE
, LAST_UPDATED_BY VARCHAR2(30)
, LAST_UPDATED_DATE DATE
, REGISTERED_NUMBER VARCHAR2(9)
, FOREIGN_REGISTERED_NUMBER VARCHAR2(100)
, COUNTRY_OF_ORIGIN VARCHAR2(4000)
, ORIGIN_COUNTRY_CODE VARCHAR2(4000)
, START_DATE DATE
, END_DATE DATE
, GENERAL_INFO VARCHAR2(4000)
, WARNING_INFO VARCHAR2(34)
)

/
