--------------------------------------------------------
--  DDL for Type XV_OGL_TYPE_COND_TYPE
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TYPE "XVIEWMGR"."XV_OGL_TYPE_COND_TYPE" IS OBJECT (
  OGL_TYPE_CONDITION_DETAIL_ID NUMBER
, OGL_TYPE_CONDITION_ID NUMBER
, REVISION_NAME VARCHAR2(4000)
, REVISION_ID NUMBER
, CONDITION_NO NUMBER
, RATINGS_LIST SYS.XMLTYPE
, SECONDARY_RATINGS_LIST SYS.XMLTYPE
, END_USER_TYPE_GOV VARCHAR2(5)
, END_USER_TYPE_COM VARCHAR2(5)
, END_USER_TYPE_IND VARCHAR2(5)
, END_USER_TYPE_OTHER VARCHAR2(5)
, STATUS_CONTROL VARCHAR2(1)
)

/
