--------------------------------------------------------
--  DDL for Type XV_OGL_TYPE_SEC_CE_TYPE
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TYPE "XVIEWMGR"."XV_OGL_TYPE_SEC_CE_TYPE" IS OBJECT (
  OGL_TYPE_CONDITION_DETAIL_ID NUMBER
, OGL_TYPE_CONDITION_ID NUMBER
, STATUS_CONTROL VARCHAR2(1)
, REVISION_ID NUMBER
, CONDITION_NO NUMBER
, SECONDARY_CONTROL_ENTRY VARCHAR2(4000)
)

/
