--------------------------------------------------------
--  DDL for Type XV_OGL_SRC_CNT_INC_TYPE
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TYPE "XVIEWMGR"."XV_OGL_SRC_CNT_INC_TYPE" IS OBJECT (
  OGL_TYPE_CONDITION_ID NUMBER
, OGL_TYPE_CONDITION_DETAIL_ID NUMBER
, REVISION_ID NUMBER
, REVISION_NAME VARCHAR2(4000)
, CONDITION_NO NUMBER
, COUNTRY_ID VARCHAR2(4000)
, COUNTRY_NAME VARCHAR2(4000)
)

/
