--------------------------------------------------------
--  DDL for Type XV_PVEX_NOVA_DETS_TYPE
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TYPE "XVIEWMGR"."XV_PVEX_NOVA_DETS_TYPE" IS OBJECT (
  ND_ID NUMBER
, N_ID NUMBER
, STATUS_CONTROL VARCHAR2(1)
, SAR_ID NUMBER
, PREVIOUS_COMPANY_NAME VARCHAR2(4000)
, CURRENT_COMPANY_NAME VARCHAR2(4000)
, REASON_FOR_CHANGE VARCHAR2(4000)
, CREATED_BY_WUA_ID NUMBER
, CREATED_DATETIME DATE
, COMPLETED_BY_WUA_ID NUMBER
, COMPLETED_DATETIME DATE
, STATUS VARCHAR2(100)
, NOVATION_REFERENCE VARCHAR2(4000)
, LETTER_DECISION VARCHAR2(20)
)

/
