--------------------------------------------------------
--  DDL for Type XV_PVEX_SUB_ADV_TYPE
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TYPE "XVIEWMGR"."XV_PVEX_SUB_ADV_TYPE" IS OBJECT (
  PEAD_ID NUMBER
, REVIEWER_NAME VARCHAR2(100)
, REVIEWER_CONTACT_DETAILS VARCHAR2(254)
, REVIEWER_QUESTION VARCHAR2(254)
, SENT_DATE DATE
, TARGET_WORKING_DAYS NUMBER
, RESPONSE_DATE DATE
, REVIEW_RESPONSE VARCHAR2(4000)
, REVIEW_SAVED VARCHAR2(5)
, TARGET_DAYS_REACHED VARCHAR2(5)
)

/
