--------------------------------------------------------
--  DDL for Type XV_PF_TYPES_TYPE
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TYPE "XVIEWMGR"."XV_PF_TYPES_TYPE" IS OBJECT (
  PF_TYPE VARCHAR2(30)
, FOLDER_TITLE_EDITABLE VARCHAR2(10)
, CONSOLIDATE_FOLDER_TITLE VARCHAR2(10)
, CONSOLIDATE_FOLDER_REFERENCE VARCHAR2(10)
, SUMMARY_MODE VARCHAR2(10)
, MATRIX_LEGAL_FOLDER_REQUIRED VARCHAR2(10)
, MATRIX_INFO_FOLDER_REQUIRED VARCHAR2(10)
, SYSTEM_DOMAIN VARCHAR2(100)
)

/
