--------------------------------------------------------
--  DDL for Type XV_REPORT_DEFS_TYPE
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TYPE "XVIEWMGR"."XV_REPORT_DEFS_TYPE" IS OBJECT (
  DOMAIN VARCHAR2(80)
, TITLE VARCHAR2(4000)
, DESCRIPTION VARCHAR2(4000)
, CATEGORY_MNEM VARCHAR2(4000)
, GLOBAL_DEFINITION VARCHAR2(5)
, RUN_NOW VARCHAR2(4000)
, RUN_LATER VARCHAR2(4000)
, RUN_REPEAT VARCHAR2(4000)
, RUN_REPEAT_INTERVAL_MNEMS VARCHAR2(4000)
, RUN_REPEAT_INTERVAL_DEFAULT VARCHAR2(4000)
, DISPLAY_SCHEDULER VARCHAR2(10)
, CONFIG_PARAMETER_DOMAIN VARCHAR2(50)
, EMAIL_NOTIFICATION_ENABLED VARCHAR2(10)
, EMAIL_NOTIFICATION_MESSAGE VARCHAR2(4000)
, EMAIL_DEFAULT_NOTIFY_AUDIENCE VARCHAR2(4000)
, EMAIL_NOTIFY_AUDIENCE_QUERY VARCHAR2(4000)
, REPORT_PART_ATTACH_LIST SYS.XMLTYPE
, NOTIFICATION_AUDIENCE_EDITABLE VARCHAR2(4000)
, NOTIFICATION_OPTIONAL VARCHAR2(4000)
, PUBLISH_ENABLED VARCHAR2(10)
, PRIVATE_ENABLED VARCHAR2(10)
, PRIVATE_ENFORCED VARCHAR2(10)
, DEFAULT_QUEUE VARCHAR2(30)
, DEFAULT_RETENTION_DAYS NUMBER
, RETENTION_PERIOD_EDITABLE VARCHAR2(10)
, MAXIMUM_RETENTION_DAYS NUMBER
, DELETION_WARNING_PERIOD_DAYS NUMBER
, DELETION_EMAIL_MESSAGE_TEXT VARCHAR2(4000)
, PARAMETER_XML SYS.XMLTYPE
, MAPSET_TEMPLATE_XML SYS.XMLTYPE
, FILE_TRANSMISSION_TYPE_MNEM VARCHAR2(50)
, FILE_TRANSMISSION_TIME_OFFSET VARCHAR2(4000)
, VISIBILITY VARCHAR2(100)
)

/
