--------------------------------------------------------
--  DDL for Type XV_REVIEW_ADV_DETS_TYPE
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TYPE "XVIEWMGR"."XV_REVIEW_ADV_DETS_TYPE" IS OBJECT (
  RAD_ID NUMBER(12, 0)
, RA_ID NUMBER(12, 0)
, START_DATETIME DATE
, END_DATETIME DATE
, STATUS_CONTROL VARCHAR2(1)
, CREATED_BY_WUA_ID NUMBER(12, 0)
, LEVEL_SEQ NUMBER
, STATUS VARCHAR2(50)
, AAC_ID NUMBER
, PERSON_ID NUMBER
, PARENT_RA_ID NUMBER
, REVIEW_DELIVERED_DATE DATE
, REVIEW_COMPLETED_DATE DATE
, REVIEW_CLOSED_DATE DATE
, SUB_ADVISOR_FORMAT VARCHAR2(4000)
, INTENTION_SET_ID NUMBER(12, 0)
, REVIEW_DEADLINE_DATE DATE
)

/
