--------------------------------------------------------
--  DDL for Type XV_REVIEW_BAT_DETS_TYPE
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TYPE "XVIEWMGR"."XV_REVIEW_BAT_DETS_TYPE" IS OBJECT (
  RBD_ID NUMBER(12, 0)
, RB_ID NUMBER(12, 0)
, START_DATETIME DATE
, END_DATETIME DATE
, STATUS_CONTROL VARCHAR2(1)
, CREATED_BY_WUA_ID NUMBER(12, 0)
, BATCH_START_DATE DATE
, BATCH_END_DATE DATE
, BATCH_STATUS VARCHAR2(50)
, BATCH_STATUS_DISPLAY VARCHAR2(50)
, ADVICE_TYPE VARCHAR2(30)
, REVIEW_TYPE VARCHAR2(30)
)

/
