--------------------------------------------------------
--  DDL for Type XV_REPORT_PRT_STY_TYPE
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TYPE "XVIEWMGR"."XV_REPORT_PRT_STY_TYPE" IS OBJECT (
  DOMAIN VARCHAR2(40)
, PART_LABEL VARCHAR2(2000)
, STYLE_NAME VARCHAR2(2000)
, ALIGNMENT_ATTRIBUTES VARCHAR2(4000)
, FONT_ATTRIBUTES VARCHAR2(4000)
, INTERIOR_ATTRIBUTES VARCHAR2(4000)
, NUMBER_FORMAT_ATTRIBUTES VARCHAR2(4000)
)

/
