--------------------------------------------------------
--  DDL for Type XV_RES_PEOPLE_TYPE
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TYPE "XVIEWMGR"."XV_RES_PEOPLE_TYPE" IS OBJECT (
  RPD_ID NUMBER(12, 0)
, RP_ID NUMBER(12, 0)
, STATUS_CONTROL VARCHAR2(1)
, STATUS VARCHAR2(12)
, FULL_NAME VARCHAR2(4000)
, INFORMAL_NAME VARCHAR2(4000)
, TITLE VARCHAR2(4000)
, SURNAME VARCHAR2(4000)
, PREFERRED_FORENAME VARCHAR2(4000)
, FORENAME VARCHAR2(4000)
, ORG_ID NUMBER
, WORK_ADDRESS_ID NUMBER
, TELEPHONE_HASH_CODE VARCHAR2(60)
, FAX_HASH_CODE VARCHAR2(60)
, JOB_DESCRIPTION VARCHAR2(4000)
, ORACLE_USER_ID VARCHAR2(4000)
, UNIX_LOGIN_ID VARCHAR2(4000)
, CREATED_BY VARCHAR2(4000)
, CREATED_DATE DATE
, LAST_UPDATED_BY VARCHAR2(4000)
, LAST_UPDATED_DATE DATE
, SELF_UPDATED_DATE DATE
, PORTAL_EMAIL_ADDRESS VARCHAR2(4000)
, LOCATION_AT_ADDRESS VARCHAR2(4000)
, ORGANISATION_DESCRIPTION VARCHAR2(4000)
, DEPARTMENT_DESCRIPTION VARCHAR2(4000)
, SHARE_ADDRESS_INFO VARCHAR2(4000)
, PROCESSED_EMAIL_DOMAIN VARCHAR2(4000)
, PERSON_TYPE VARCHAR2(4000)
, SECURITY_QUESTION_FLAG CHAR(1)
, DOB_FLAG VARCHAR2(1)
, SHARED_ACC_FLAG CHAR(1)
)

/
