--------------------------------------------------------
--  DDL for Type XV_REPORT_PRTS_TYPE
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TYPE "XVIEWMGR"."XV_REPORT_PRTS_TYPE" IS OBJECT (
  PART_ID NUMBER
, DOMAIN VARCHAR2(80)
, PART_LABEL VARCHAR2(4000)
, PART_TITLE VARCHAR2(4000)
, SEQ VARCHAR2(4000)
, CATEGORY VARCHAR2(4000)
, VISIBILITY VARCHAR2(4000)
, REQUEST_STATUS VARCHAR2(4000)
, SPREADSHEET_GEN_THRESHOLD VARCHAR2(4000)
, WORKSHEET_TITLE VARCHAR2(31)
, SQL_STATEMENT CLOB
, DOCUMENT_TEMPLATE VARCHAR2(4000)
, WORKBOOK VARCHAR2(5)
, GLOBAL_DOMAIN VARCHAR2(80)
, GLOBAL_NAME VARCHAR2(4000)
, SUB_ROOT_DOC_ELEMENT VARCHAR2(4000)
, RECORD_TARGET_PATH VARCHAR2(4000)
, FETCH_MODE VARCHAR2(20)
, FILE_TRANSMISSION_FLAG VARCHAR2(5)
, FILE_TRANSM_OUTPUT_TYPE VARCHAR2(10)
, FILE_TRANSM_FILE_NAME VARCHAR2(255)
, FILE_TRANSM_FILE_NAME_SQL VARCHAR2(4000)
, FILE_TRANSM_HASH_FILE_NAME VARCHAR2(255)
, FILE_TRANSM_HASH_FILE_NAME_SQL VARCHAR2(4000)
, JASPER_DEFINITION VARCHAR2(4000)
, JASPER_OUTPUTS SYS.XMLTYPE
, WORKSHEET_OPTIONS_RAW CLOB
, AUTOFILTER_FLAG VARCHAR2(5)
, ALL_BORDERS_FLAG VARCHAR2(5)
)

/
