--------------------------------------------------------
--  DDL for Type XV_RES_MEMBER_HIST_TYPE
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TYPE "XVIEWMGR"."XV_RES_MEMBER_HIST_TYPE" IS OBJECT (
  RD_ID NUMBER(12, 0)
, RES_ID NUMBER(12, 0)
, RR_ID NUMBER(12, 0)
, RES_TYPE VARCHAR2(30)
, ROLE_NAME VARCHAR2(100)
, MEMBER_ID NUMBER
, STATUS_CONTROL VARCHAR2(1)
, STATUS VARCHAR2(12)
, START_DATE DATE
, END_DATE DATE
, RESOURCE_PERSON_ID NUMBER
, ADDRESS_ID NUMBER
, LOCATION_AT_ADDRESS VARCHAR2(4000)
, QUALIFYING_COMMENT VARCHAR2(4000)
, BRANCH_NUMBER VARCHAR2(4000)
, BRANCH_START_DATE DATE
, AUTHORISATION_DATE DATE
, AUTHORISATION_COMMENT VARCHAR2(4000)
, WORK_TELEPHONE_NO_LIST VARCHAR2(4000)
, FAX_NO_LIST VARCHAR2(4000)
, MOBILE_TEL_NO VARCHAR2(4000)
, WORK_EMAIL_ADDRESS VARCHAR2(4000)
, LEGACY_NOTIFICATION_METHOD VARCHAR2(4000)
, LEGACY_CREATED_BY VARCHAR2(4000)
, LEGACY_CREATED_DATE DATE
, LEGACY_LAST_UPDATED_BY VARCHAR2(4000)
, LEGACY_LAST_UPDATED_DATE DATE
)

/
