--------------------------------------------------------
--  DDL for Type XV_REV_INV_ITEMS_TYPE
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TYPE "XVIEWMGR"."XV_REV_INV_ITEMS_TYPE" IS OBJECT (
  RII_ID NUMBER(28, 0)
, RI_ID NUMBER(12, 0)
, RID_ID NUMBER(12, 0)
, PRIMARY_DATA_UREF VARCHAR2(50)
, SECONDARY_DATA_UREF VARCHAR2(50)
, TERTIARY_DATA_UREF VARCHAR2(50)
, ACKNOWLEDGE_REQUIRED VARCHAR2(20)
, ACKNOWLEDGE_DISPLAYED VARCHAR2(20)
, ACKNOWLEDGE_EDIT VARCHAR2(20)
, DISPLAY_SEQ NUMBER(12, 0)
)

/
