--------------------------------------------------------
--  DDL for Type XV_RES_TYPE_ROLES_TYPE
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TYPE "XVIEWMGR"."XV_RES_TYPE_ROLES_TYPE" IS OBJECT (
  RES_TYPE VARCHAR2(30)
, ROLE_NAME VARCHAR2(200)
, ROLE_XML SYS.XMLTYPE
, ROLE_TITLE VARCHAR2(200)
, ROLE_DESCRIPTION VARCHAR2(4000)
, MIN_MEMS NUMBER(8, 0)
, MAX_MEMS NUMBER(8, 0)
, DISPLAY_SEQ NUMBER(8, 0)
, PERSON_REQUIRED VARCHAR2(8)
, PERSON_REQUIRES_ACTIVE_WUA VARCHAR2(8)
, ADDRESS_REQUIRED VARCHAR2(8)
, TELEPHONE_REQUIRED VARCHAR2(8)
, EMAIL_REQUIRED VARCHAR2(8)
, QUALIFYING_COMMENT_REQUIRED VARCHAR2(8)
, BRANCH_REQUIRED VARCHAR2(8)
, AUTHORISATION_REQUIRED VARCHAR2(8)
, NOTIFICATION_METHOD_REQUIRED VARCHAR2(8)
, ALLOW_SHARED_ACCOUNTS VARCHAR2(5)
)

/
