--------------------------------------------------------
--  DDL for Type XV_SDB_EXTAPP_TYPE
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TYPE "XVIEWMGR"."XV_SDB_EXTAPP_TYPE" IS OBJECT (
  ID NUMBER
, APPLICATION_REF VARCHAR2(4000)
, CASE_TYPE VARCHAR2(4000)
, CASE_SUB_TYPE VARCHAR2(4000)
, CASE_CLOSED_DATE DATE
, INITIAL_PROCESSING_TIME NUMBER
, INCORPORATION_FLAG NUMBER
, TEMP_OIEL_FLAG NUMBER
)

/
