--------------------------------------------------------
--  DDL for Type XV_SPIRE_APPLNTS_TYPE
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TYPE "XVIEWMGR"."XV_SPIRE_APPLNTS_TYPE" IS OBJECT (
  SAD_ID NUMBER
, SA_ID NUMBER
, STATUS VARCHAR2(12)
, STATUS_CONTROL VARCHAR2(1)
, REG_STATUS VARCHAR2(4000)
, CREATED_DATETIME DATE
, CREATED_BY_WUA_ID NUMBER
, CREATED_BY_NAME VARCHAR2(4000)
, SUBMITTED_DATETIME DATE
, SUBMITTED_BY_WUA_ID NUMBER
, SUBMITTED_BY_NAME VARCHAR2(4000)
, APPLICANT_STATUS VARCHAR2(4000)
, APPLICANT_TYPE VARCHAR2(4000)
, RES_ID NUMBER
, FTF_ID NUMBER
, COMPANY_NAME VARCHAR2(4000)
, COMPANY_REG_NO VARCHAR2(4000)
, COMPANY_VAT_NO VARCHAR2(4000)
, COMPANY_EORI_NO VARCHAR2(4000)
, COMPANY_ADDRESS VARCHAR2(4000)
, DRAFT_PERSON_TITLE VARCHAR2(20)
, DRAFT_PERSON_FORENAME VARCHAR2(4000)
, DRAFT_PERSON_MIDDLE_INITIALS VARCHAR2(4000)
, DRAFT_PERSON_SURNAME VARCHAR2(4000)
, OU_ID NUMBER
, RP_ID NUMBER
, RESTRICT_APP_VIEW VARCHAR2(10)
, RESTRICT_APP_PREPARATION VARCHAR2(10)
, RESTRICT_APP_SUBMISSION VARCHAR2(10)
, REJECTION_REASON VARCHAR2(4000)
)

/
