--------------------------------------------------------
--  DDL for Type XV_SCAN_PREF_TEMPS_TYPE
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TYPE "XVIEWMGR"."XV_SCAN_PREF_TEMPS_TYPE" IS OBJECT (
  SPT_ID NUMBER(12, 0)
, NAME VARCHAR2(100)
, SYS_MNEM VARCHAR2(100)
, DESCRIPTION VARCHAR2(1000)
, PRINT_SIZE NUMBER(3, 0)
, AUTO_ALLOCATE_AT NUMBER(3, 0)
, SCAN_SHEET_ALLOCATION_METHOD VARCHAR2(30)
, SERVICE_STATEMENT VARCHAR2(4000)
, FILENAME_POSTFIX VARCHAR2(4000)
)

/
