--------------------------------------------------------
--  DDL for Type XV_SC_PREF_SC_TYPE_TYPE
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TYPE "XVIEWMGR"."XV_SC_PREF_SC_TYPE_TYPE" IS OBJECT (
  SPT_ID NUMBER(12, 0)
, SCAN_TYPE VARCHAR2(30)
, COVERSHEET_DOCUMENT_TEMPLATE VARCHAR2(4000)
, SCAN_TYPE_XML SYS.XMLTYPE
, SCAN_SHEET_DOCUMENT_TEMPLATE VARCHAR2(60)
, SCAN_SHEET_MAIL_MERGE_XML SYS.XMLTYPE
, COVERSHEET_MAIL_MERGE_XML SYS.XMLTYPE
)

/
