--------------------------------------------------------
--  DDL for Type XV_SITES_TYPE
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TYPE "XVIEWMGR"."XV_SITES_TYPE" IS OBJECT (
  SITE_ID NUMBER
, SITE_DETAIL_ID NUMBER
, STATUS VARCHAR2(12)
, STATUS_CONTROL VARCHAR2(1)
, SITE_STATUS VARCHAR2(20)
, OCCUPANCY_STATUS VARCHAR2(4000)
, DIVISION_TITLE VARCHAR2(4000)
, TURN_NUMBER VARCHAR2(4000)
, SPIRE_APPLICANT_ID NUMBER
, SPIRE_APPLICANT_UREF VARCHAR2(4000)
, STAKEHOLDER_ADDRESS VARCHAR2(4000)
, STAKEHOLDER_POSTCODE VARCHAR2(4000)
, COMMENTS VARCHAR2(4000)
, RES_ID NUMBER
, RESTRICT_APP_VIEW VARCHAR2(4000)
, RESTRICT_APP_PREPARATION VARCHAR2(4000)
, RESTRICT_APP_SUBMISSION VARCHAR2(4000)
)

/
