--------------------------------------------------------
--  DDL for Type XV_SURVEY_TYPES_TYPE
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TYPE "XVIEWMGR"."XV_SURVEY_TYPES_TYPE" IS OBJECT (
  ST_ID NUMBER(12, 0)
, SURVEY_TYPE VARCHAR2(100)
, START_DATE DATE
, END_DATE DATE
, DESCRIPTION VARCHAR2(4000)
, ALLOW_REPEAT_SURVEY VARCHAR2(5)
, DISPLAY_QUESTION_BARS VARCHAR2(5)
, EMAIL_TEXT VARCHAR2(4000)
, ADMIN_NAME VARCHAR2(200)
, ADMIN_EMAIL VARCHAR2(200)
)

/
