--------------------------------------------------------
--  DDL for Type XV_SV_INSTANCES_TYPE
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TYPE "XVIEWMGR"."XV_SV_INSTANCES_TYPE" IS OBJECT (
  ST_ID NUMBER(12, 0)
, SI_ID NUMBER(12, 0)
, INSTANCE_TYPE VARCHAR2(8)
, INSTANCE_TITLE VARCHAR2(50)
, CREATED_DATETIME DATE
, STATUS CHAR(10)
, RESPONSE_NUMBER VARCHAR2(100)
, RESPONSE_DATETIME DATE
, TEMPLATE_NAME VARCHAR2(4000)
, TEMPLATE_DESCRIPTION VARCHAR2(4000)
)

/
