--------------------------------------------------------
--  DDL for Type XV_TRANSACTIONS_TYPE
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TYPE "XVIEWMGR"."XV_TRANSACTIONS_TYPE" IS OBJECT (
  T_ID NUMBER(12, 0)
, PRIMARY_DATA_UREF VARCHAR2(20)
, TRANSACTION_REFERENCE VARCHAR2(20)
, TRANSACTION_TITLE VARCHAR2(50)
, TRANSACTION_TYPE VARCHAR2(50)
, TRANSACTION_SUBTYPE VARCHAR2(50)
, CURRENT_STATUS VARCHAR2(20)
, ACTION_DESC_TRANSACTION VARCHAR2(50)
, EVENT_DATE DATE
, TRANSACTION_COMMENTS VARCHAR2(4000)
, START_DATETIME DATE
, END_DATETIME DATE
)

/
