--------------------------------------------------------
--  DDL for Type XV_TPL_CLAUSE_DTLS_TYPE
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TYPE "XVIEWMGR"."XV_TPL_CLAUSE_DTLS_TYPE" IS OBJECT (
  TCD_ID NUMBER(12, 0)
, TC_ID NUMBER(12, 0)
, CLAUSE_TYPE_ID VARCHAR2(30)
, SHORT_CODE VARCHAR2(400)
, TITLE VARCHAR2(4000)
, DEFAULT_SEVERITY VARCHAR2(400)
, CLASS VARCHAR2(400)
, DEFAULT_REASON_CODE VARCHAR2(50)
, TEMPLATE_CLAUSE_TEXT SYS.XMLTYPE
, DISPLAY_ORDER NUMBER(12, 0)
, DELETE_FLAG VARCHAR2(10)
, EDIT_FLAG VARCHAR2(10)
, CLEAR_FLAG VARCHAR2(10)
, UPDATED_BY_WUA_ID NUMBER(12, 0)
, UPDATED_DATETIME DATE
, STATUS VARCHAR2(12)
, STATUS_CONTROL VARCHAR2(1)
, START_DATETIME DATE
, END_DATETIME DATE
)

/
