--------------------------------------------------------
--  DDL for Type XV_TALLY_TYPE_STYL_TYPE
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TYPE "XVIEWMGR"."XV_TALLY_TYPE_STYL_TYPE" IS OBJECT (
  TALLY_TYPE VARCHAR2(30)
, STYLE_NAME VARCHAR2(50)
, STYLE_UNIT VARCHAR2(50)
, STYLE_PROMPT VARCHAR2(200)
, TARGET_DISPLAY_ADJUSTMENT NUMBER(12, 0)
, STYLE_TYPE VARCHAR2(50)
, INTERRUPT_OVERLAY_IMAGE VARCHAR2(200)
, SEGMENT_IDX NUMBER(12, 0)
, IMAGE_NAME VARCHAR2(200)
, SEG_INT_OVERLAY_IMAGE VARCHAR2(200)
, SEGMENT_LWR_LIMIT NUMBER(12, 2)
, SEGMENT_UPR_LIMIT NUMBER(12, 2)
)

/
