--------------------------------------------------------
--  DDL for Type XV_WUA_PREFS_TYPE
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TYPE "XVIEWMGR"."XV_WUA_PREFS_TYPE" IS OBJECT (
  CATEGORY_NAME VARCHAR2(50)
, CATEGORY_PROMPT VARCHAR2(200)
, CATEGORY_DISPLAY_ORDER NUMBER
, PREFERENCE_NAME VARCHAR2(50)
, PREFERENCE_PROMPT VARCHAR2(200)
, PREFERENCE_HINT VARCHAR2(300)
, PREFERENCE_DISPLAY_ORDER NUMBER
, DATA_TYPE VARCHAR2(50)
, WIDGET_TYPE VARCHAR2(50)
, MAPSET_NAME VARCHAR2(50)
, MANDATORY VARCHAR2(5)
, DEFAULT_VALUE VARCHAR2(1000)
)

/
