--------------------------------------------------------
--  Ref Constraints for Table ADVICE_ADVISORY_BODIES
--------------------------------------------------------

  ALTER TABLE "BPMMGR"."ADVICE_ADVISORY_BODIES" ADD CONSTRAINT "ADVICE_ADVISORY_BODIES_FK1" FOREIGN KEY ("ADVICE_TYPE")
	  REFERENCES "BPMMGR"."ADVICE_TYPES" ("ADVICE_TYPE") ENABLE;
  ALTER TABLE "BPMMGR"."ADVICE_ADVISORY_BODIES" ADD CONSTRAINT "ADVICE_ADVISORY_BODIES_FK2" FOREIGN KEY ("AB_ID")
	  REFERENCES "BPMMGR"."ADVISORY_BODIES" ("ID") ENABLE;
  ALTER TABLE "BPMMGR"."ADVICE_ADVISORY_BODIES" ADD CONSTRAINT "ADVICE_ADVISORY_BODI_UREFS_FK" FOREIGN KEY ("ID")
	  REFERENCES "BPMMGR"."UREFS" ("ADVICE_ADVISORY_BODIES") DEFERRABLE INITIALLY DEFERRED ENABLE;
