--------------------------------------------------------
--  Ref Constraints for Table ADVICE_ADVISORY_COMMUNITIES
--------------------------------------------------------

  ALTER TABLE "BPMMGR"."ADVICE_ADVISORY_COMMUNITIES" ADD CONSTRAINT "ADVICE_ADVISORY_COMM_FK1" FOREIGN KEY ("AAB_ID")
	  REFERENCES "BPMMGR"."ADVICE_ADVISORY_BODIES" ("ID") ENABLE;
  ALTER TABLE "BPMMGR"."ADVICE_ADVISORY_COMMUNITIES" ADD CONSTRAINT "ADVICE_ADVISORY_COMM_FK2" FOREIGN KEY ("AC_ID", "AB_ID")
	  REFERENCES "BPMMGR"."ADVISORY_COMMUNITIES" ("ID", "AB_ID") ENABLE;
  ALTER TABLE "BPMMGR"."ADVICE_ADVISORY_COMMUNITIES" ADD CONSTRAINT "ADVICE_ADVISORY_COMM_FK3" FOREIGN KEY ("AB_ID", "ADVICE_TYPE")
	  REFERENCES "BPMMGR"."ADVICE_ADVISORY_BODIES" ("AB_ID", "ADVICE_TYPE") ENABLE;
  ALTER TABLE "BPMMGR"."ADVICE_ADVISORY_COMMUNITIES" ADD CONSTRAINT "ADVICE_ADVISORY_COMM_UREFS_FK" FOREIGN KEY ("ID")
	  REFERENCES "BPMMGR"."UREFS" ("ADVICE_ADVISORY_COMMUNITY_ID") DEFERRABLE INITIALLY DEFERRED ENABLE;
