--------------------------------------------------------
--  Ref Constraints for Table ADVICE_ADVISORY_COMM_MATRIX
--------------------------------------------------------

  ALTER TABLE "BPMMGR"."ADVICE_ADVISORY_COMM_MATRIX" ADD CONSTRAINT "ADVICE_ADV_COMM_MAT_FK1" FOREIGN KEY ("AAC_ID", "ADVICE_TYPE")
	  REFERENCES "BPMMGR"."ADVICE_ADVISORY_COMMUNITIES" ("ID", "ADVICE_TYPE") ENABLE;
  ALTER TABLE "BPMMGR"."ADVICE_ADVISORY_COMM_MATRIX" ADD CONSTRAINT "ADVICE_ADV_COMM_MAT_FK2" FOREIGN KEY ("REF_AAC_ID", "ADVICE_TYPE")
	  REFERENCES "BPMMGR"."ADVICE_ADVISORY_COMMUNITIES" ("ID", "ADVICE_TYPE") ENABLE;
