--------------------------------------------------------
--  Ref Constraints for Table ADVISORY_COMMUNITIES
--------------------------------------------------------

  ALTER TABLE "BPMMGR"."ADVISORY_COMMUNITIES" ADD CONSTRAINT "ADVISORY_COMMUNITIES_FK1" FOREIGN KEY ("AB_ID")
	  REFERENCES "BPMMGR"."ADVISORY_BODIES" ("ID") ENABLE;
  ALTER TABLE "BPMMGR"."ADVISORY_COMMUNITIES" ADD CONSTRAINT "ADVISORY_COMMUNITY_UREFS_FK" FOREIGN KEY ("ID")
	  REFERENCES "BPMMGR"."UREFS" ("ADVISORY_COMMUNITY_ID") DEFERRABLE INITIALLY DEFERRED ENABLE;
