--------------------------------------------------------
--  Ref Constraints for Table APP_ERRORS
--------------------------------------------------------

  ALTER TABLE "FOXMGR"."APP_ERRORS" ADD CONSTRAINT "APPLICATION_ERRORS_UREFS_FK" FOREIGN KEY ("ID")
	  REFERENCES "BPMMGR"."UREFS" ("APP_ERROR_ID") DEFERRABLE INITIALLY DEFERRED ENABLE;
  ALTER TABLE "FOXMGR"."APP_ERRORS" ADD CONSTRAINT "APP_ERRORS_FK1" FOREIGN KEY ("SYSTEM_DOMAIN_ID")
	  REFERENCES "FOXMGR"."SYSTEM_DOMAINS" ("ID") ENABLE;
  ALTER TABLE "FOXMGR"."APP_ERRORS" ADD CONSTRAINT "APP_ERRORS_FK2" FOREIGN KEY ("SEVERITY")
	  REFERENCES "FOXMGR"."APP_ERROR_SEVERITY" ("NAME") ENABLE;
