--------------------------------------------------------
--  Ref Constraints for Table APPLICATIONS
--------------------------------------------------------

  ALTER TABLE "SDBMGR"."APPLICATIONS" ADD CONSTRAINT "APPLICATIONS_FK1" FOREIGN KEY ("ELA_GRP_ID")
	  REFERENCES "SPIREMGR"."ELA_GROUPS" ("ID") ENABLE;
  ALTER TABLE "SDBMGR"."APPLICATIONS" ADD CONSTRAINT "APPLICATIONS_FK2" FOREIGN KEY ("BATCH_ID")
	  REFERENCES "SDBMGR"."BATCHES" ("ID") ENABLE;
  ALTER TABLE "SDBMGR"."APPLICATIONS" ADD CONSTRAINT "APPLICATIONS_FK3" FOREIGN KEY ("EXTERNAL_APPLICATION_ID")
	  REFERENCES "SDBMGR"."EXTERNAL_APPLICATIONS" ("ID") ENABLE;
  ALTER TABLE "SDBMGR"."APPLICATIONS" ADD CONSTRAINT "APPLICATIONS_FK4" FOREIGN KEY ("ALLOW_RELEASE_OF_BATCH_ID")
	  REFERENCES "SDBMGR"."BATCHES" ("ID") ENABLE;
