--------------------------------------------------------
--  Ref Constraints for Table APPLICATION_COUNTRIES
--------------------------------------------------------

  ALTER TABLE "SDBMGR"."APPLICATION_COUNTRIES" ADD CONSTRAINT "APPLICATION_COUNTRIES_FK1" FOREIGN KEY ("ELA_GRP_ID")
	  REFERENCES "SDBMGR"."APPLICATIONS" ("ELA_GRP_ID") ENABLE;
  ALTER TABLE "SDBMGR"."APPLICATION_COUNTRIES" ADD CONSTRAINT "APPLICATION_COUNTRIES_FK2" FOREIGN KEY ("BATCH_ID")
	  REFERENCES "SDBMGR"."BATCHES" ("ID") ENABLE;
  ALTER TABLE "SDBMGR"."APPLICATION_COUNTRIES" ADD CONSTRAINT "APPLICATION_COUNTRIES_FK3" FOREIGN KEY ("COUNTRY_ID")
	  REFERENCES "BPMMGR"."COUNTRIES" ("ID") ENABLE;
