--------------------------------------------------------
--  Ref Constraints for Table AUTO_REVIEW_ADVICE_AAC_MATRIX
--------------------------------------------------------

  ALTER TABLE "SPIREMGR"."AUTO_REVIEW_ADVICE_AAC_MATRIX" ADD CONSTRAINT "AUTO_REV_ADV_AAC_MAT_FK1" FOREIGN KEY ("AAC_ID")
	  REFERENCES "BPMMGR"."ADVICE_ADVISORY_COMMUNITIES" ("ID") ENABLE;
  ALTER TABLE "SPIREMGR"."AUTO_REVIEW_ADVICE_AAC_MATRIX" ADD CONSTRAINT "AUTO_REV_ADV_AAC_MAT_FK2" FOREIGN KEY ("ADVICE_TYPE")
	  REFERENCES "BPMMGR"."ADVICE_TYPES" ("ADVICE_TYPE") ENABLE;
  ALTER TABLE "SPIREMGR"."AUTO_REVIEW_ADVICE_AAC_MATRIX" ADD CONSTRAINT "AUTO_REV_ADV_AAC_MAT_FK3" FOREIGN KEY ("ARR_ID")
	  REFERENCES "SPIREMGR"."AUTO_REVIEW_RULES" ("ID") ENABLE;
