--------------------------------------------------------
--  Ref Constraints for Table BUS_ROUTINE_TALLY_RELATIONS
--------------------------------------------------------

  ALTER TABLE "BPMMGR"."BUS_ROUTINE_TALLY_RELATIONS" ADD CONSTRAINT "BUS_ROUTINE_TALLY_RELS_FK1" FOREIGN KEY ("BRT_ID")
	  REFERENCES "BPMMGR"."BUSINESS_ROUTINE_TALLIES" ("ID") ENABLE;
  ALTER TABLE "BPMMGR"."BUS_ROUTINE_TALLY_RELATIONS" ADD CONSTRAINT "BUS_ROUTINE_TALLY_RELS_FK2" FOREIGN KEY ("TALLY_ID")
	  REFERENCES "BPMMGR"."TALLIES" ("ID") ENABLE;
