--------------------------------------------------------
--  Ref Constraints for Table BUSINESS_TRANSACTION_DATA
--------------------------------------------------------

  ALTER TABLE "BPMMGR"."BUSINESS_TRANSACTION_DATA" ADD CONSTRAINT "BUSINESS_TRANSACTION_DATA_FK" FOREIGN KEY ("BT_ID")
	  REFERENCES "BPMMGR"."BUSINESS_TRANSACTIONS" ("ID") ENABLE;
  ALTER TABLE "BPMMGR"."BUSINESS_TRANSACTION_DATA" ADD CONSTRAINT "BUSINESS_TRANSACTION_DATA_FK2" FOREIGN KEY ("START_OPERATION_ID")
	  REFERENCES "BPMMGR"."CHANGE_OPERATIONS" ("ID") ENABLE;
  ALTER TABLE "BPMMGR"."BUSINESS_TRANSACTION_DATA" ADD CONSTRAINT "BUSINESS_TRANSACTION_DATA_FK3" FOREIGN KEY ("END_OPERATION_ID")
	  REFERENCES "BPMMGR"."CHANGE_OPERATIONS" ("ID") ENABLE;
