--------------------------------------------------------
--  Ref Constraints for Table BUSINESS_TRANSACTIONS
--------------------------------------------------------

  ALTER TABLE "BPMMGR"."BUSINESS_TRANSACTIONS" ADD CONSTRAINT "BUSINESS_TRANSACTIONS_FK1" FOREIGN KEY ("TRANSACTION_TYPE")
	  REFERENCES "BPMMGR"."BUSINESS_TRANSACTION_TYPES" ("TRANSACTION_TYPE") ENABLE;
  ALTER TABLE "BPMMGR"."BUSINESS_TRANSACTIONS" ADD CONSTRAINT "BUSINESS_TRANSACTIONS_FK2" FOREIGN KEY ("START_OPERATION_ID")
	  REFERENCES "BPMMGR"."CHANGE_OPERATIONS" ("ID") ENABLE;
  ALTER TABLE "BPMMGR"."BUSINESS_TRANSACTIONS" ADD CONSTRAINT "BUSINESS_TRANSACTIONS_FK3" FOREIGN KEY ("END_OPERATION_ID")
	  REFERENCES "BPMMGR"."CHANGE_OPERATIONS" ("ID") ENABLE;
