--------------------------------------------------------
--  Ref Constraints for Table BUSINESS_ROUTINE_ASSIGNMENTS
--------------------------------------------------------

  ALTER TABLE "BPMMGR"."BUSINESS_ROUTINE_ASSIGNMENTS" ADD CONSTRAINT "BUSINESS_ROUTINE_ASSIGNMT_FK1" FOREIGN KEY ("BRC_ID")
	  REFERENCES "BPMMGR"."BUSINESS_ROUTINE_CONTEXTS" ("ID") ENABLE;
  ALTER TABLE "BPMMGR"."BUSINESS_ROUTINE_ASSIGNMENTS" ADD CONSTRAINT "BUSINESS_ROUTINE_ASSIGNMT_FK2" FOREIGN KEY ("BAS_ID")
	  REFERENCES "BPMMGR"."BUSINESS_ASSIGNMENTS" ("ID") ENABLE;
