--------------------------------------------------------
--  Ref Constraints for Table BUSINESS_STAGES
--------------------------------------------------------

  ALTER TABLE "BPMMGR"."BUSINESS_STAGES" ADD CONSTRAINT "BUSINESS_STAGES_FK1" FOREIGN KEY ("BP_ID")
	  REFERENCES "BPMMGR"."BUSINESS_PROCESSES" ("ID") ENABLE;
  ALTER TABLE "BPMMGR"."BUSINESS_STAGES" ADD CONSTRAINT "BUSINESS_STAGES_FK2" FOREIGN KEY ("START_OPERATION_ID")
	  REFERENCES "BPMMGR"."CHANGE_OPERATIONS" ("ID") ENABLE;
  ALTER TABLE "BPMMGR"."BUSINESS_STAGES" ADD CONSTRAINT "BUSINESS_STAGES_FK3" FOREIGN KEY ("END_OPERATION_ID")
	  REFERENCES "BPMMGR"."CHANGE_OPERATIONS" ("ID") ENABLE;
  ALTER TABLE "BPMMGR"."BUSINESS_STAGES" ADD CONSTRAINT "BUSINESS_STAGES_FK4" FOREIGN KEY ("BA_ID")
	  REFERENCES "BPMMGR"."BUSINESS_ACTIVITIES" ("ID") ENABLE;
  ALTER TABLE "BPMMGR"."BUSINESS_STAGES" ADD CONSTRAINT "BUSINESS_STAGES_FK5" FOREIGN KEY ("BRC_ID")
	  REFERENCES "BPMMGR"."BUSINESS_ROUTINE_CONTEXTS" ("ID") DEFERRABLE INITIALLY DEFERRED ENABLE;
  ALTER TABLE "BPMMGR"."BUSINESS_STAGES" ADD CONSTRAINT "BUSINESS_STAGES_UREFS_FK" FOREIGN KEY ("ID")
	  REFERENCES "BPMMGR"."UREFS" ("BUSINESS_STAGES_ID") DEFERRABLE INITIALLY DEFERRED ENABLE;
