--------------------------------------------------------
--  Ref Constraints for Table BUSINESS_UNAVAILABLE_USAGE
--------------------------------------------------------

  ALTER TABLE "BPMMGR"."BUSINESS_UNAVAILABLE_USAGE" ADD CONSTRAINT "BUSINESS_UNAVAILABLE_USE_FK1" FOREIGN KEY ("BU_ID")
	  REFERENCES "BPMMGR"."BUSINESS_UNAVAILABLE" ("ID") ENABLE;
  ALTER TABLE "BPMMGR"."BUSINESS_UNAVAILABLE_USAGE" ADD CONSTRAINT "BUSINESS_UNAVAILABLE_USE_FK2" FOREIGN KEY ("RES_ID")
	  REFERENCES "DECMGR"."RESOURCES" ("ID") ENABLE;
