--------------------------------------------------------
--  Ref Constraints for Table BUSINESS_UNAVAILABLE_DETAILS
--------------------------------------------------------

  ALTER TABLE "BPMMGR"."BUSINESS_UNAVAILABLE_DETAILS" ADD CONSTRAINT "BUSINESS_UNAVAILABLE_DET_FK1" FOREIGN KEY ("BU_ID")
	  REFERENCES "BPMMGR"."BUSINESS_UNAVAILABLE" ("ID") ENABLE;
  ALTER TABLE "BPMMGR"."BUSINESS_UNAVAILABLE_DETAILS" ADD CONSTRAINT "BUSINESS_UNAVAILABLE_DET_FK2" FOREIGN KEY ("SCOPE_UREF")
	  REFERENCES "BPMMGR"."UREFS" ("UREF") ENABLE;
