--------------------------------------------------------
--  Ref Constraints for Table BUSINESS_ROUTINES
--------------------------------------------------------

  ALTER TABLE "BPMMGR"."BUSINESS_ROUTINES" ADD CONSTRAINT "BUSINESS_ROUTINES_FK1" FOREIGN KEY ("BP_ID")
	  REFERENCES "BPMMGR"."BUSINESS_PROCESS_DEFINITIONS" ("ID") ENABLE;
  ALTER TABLE "BPMMGR"."BUSINESS_ROUTINES" ADD CONSTRAINT "BUSINESS_ROUTINES_FK2" FOREIGN KEY ("BS_ID")
	  REFERENCES "BPMMGR"."BUSINESS_STAGES" ("ID") ENABLE;
  ALTER TABLE "BPMMGR"."BUSINESS_ROUTINES" ADD CONSTRAINT "BUSINESS_ROUTINES_FK3" FOREIGN KEY ("ORPHANS_PARENT_BR_ID")
	  REFERENCES "BPMMGR"."BUSINESS_ROUTINES" ("ID") ENABLE;
  ALTER TABLE "BPMMGR"."BUSINESS_ROUTINES" ADD CONSTRAINT "BUSINESS_ROUTINES_FK4" FOREIGN KEY ("ROOT_BR_ID")
	  REFERENCES "BPMMGR"."BUSINESS_ROUTINES" ("ID") ENABLE;
