--------------------------------------------------------
--  Ref Constraints for Table BUSINESS_ACTIVITIES
--------------------------------------------------------

  ALTER TABLE "BPMMGR"."BUSINESS_ACTIVITIES" ADD CONSTRAINT "BUSINESS_ACTIVITIES_FK1" FOREIGN KEY ("BT_ID")
	  REFERENCES "BPMMGR"."BUSINESS_TRANSACTIONS" ("ID") ENABLE;
  ALTER TABLE "BPMMGR"."BUSINESS_ACTIVITIES" ADD CONSTRAINT "BUSINESS_ACTIVITIES_FK2" FOREIGN KEY ("START_OPERATION_ID")
	  REFERENCES "BPMMGR"."CHANGE_OPERATIONS" ("ID") ENABLE;
  ALTER TABLE "BPMMGR"."BUSINESS_ACTIVITIES" ADD CONSTRAINT "BUSINESS_ACTIVITIES_FK3" FOREIGN KEY ("END_OPERATION_ID")
	  REFERENCES "BPMMGR"."CHANGE_OPERATIONS" ("ID") ENABLE;
  ALTER TABLE "BPMMGR"."BUSINESS_ACTIVITIES" ADD CONSTRAINT "BUS_ACTIVITIES_UREFS_FK" FOREIGN KEY ("ID")
	  REFERENCES "BPMMGR"."UREFS" ("BUSINESS_ACTIVITY_ID") DEFERRABLE INITIALLY DEFERRED ENABLE;
