--------------------------------------------------------
--  Ref Constraints for Table BUSINESS_ASSIGNMENT_DETAILS
--------------------------------------------------------

  ALTER TABLE "BPMMGR"."BUSINESS_ASSIGNMENT_DETAILS" ADD CONSTRAINT "BUSINESS_ASSIGNMENT_DETAIL_FK1" FOREIGN KEY ("BAS_ID")
	  REFERENCES "BPMMGR"."BUSINESS_ASSIGNMENTS" ("ID") ENABLE;
  ALTER TABLE "BPMMGR"."BUSINESS_ASSIGNMENT_DETAILS" ADD CONSTRAINT "BUSINESS_ASS_DETAILS_FK1" FOREIGN KEY ("UPDATE_WUA_ID")
	  REFERENCES "SECUREMGR"."WEB_USER_ACCOUNT_MASTER" ("WUA_ID") ENABLE;
