--------------------------------------------------------
--  Ref Constraints for Table BUSINESS_ROUTINE_CONTEXTS
--------------------------------------------------------

  ALTER TABLE "BPMMGR"."BUSINESS_ROUTINE_CONTEXTS" ADD CONSTRAINT "BUSINESS_ROUTINE_CTX_FK1" FOREIGN KEY ("BC_ID")
	  REFERENCES "BPMMGR"."BUSINESS_CONTEXTS" ("ID") ENABLE;
  ALTER TABLE "BPMMGR"."BUSINESS_ROUTINE_CONTEXTS" ADD CONSTRAINT "BUSINESS_ROUTINE_CTX_FK2" FOREIGN KEY ("BR_ID")
	  REFERENCES "BPMMGR"."BUSINESS_ROUTINES" ("ID") ENABLE;
