--------------------------------------------------------
--  Ref Constraints for Table CASE_PROCESS_QUEUE
--------------------------------------------------------

  ALTER TABLE "SDBMGR"."CASE_PROCESS_QUEUE" ADD CONSTRAINT "CASE_PROCESS_QUEUE_FK1" FOREIGN KEY ("BATCH_ID")
	  REFERENCES "SDBMGR"."BATCHES" ("ID") ENABLE;
  ALTER TABLE "SDBMGR"."CASE_PROCESS_QUEUE" ADD CONSTRAINT "CASE_PROCESS_QUEUE_FK2" FOREIGN KEY ("ELA_DETAIL_ID")
	  REFERENCES "SPIREMGR"."EXPORT_LICENCE_APP_DETAILS" ("ID") ENABLE;
