--------------------------------------------------------
--  Ref Constraints for Table CLASS_PRIVILEGES
--------------------------------------------------------

  ALTER TABLE "BPMMGR"."CLASS_PRIVILEGES" ADD CONSTRAINT "CLASS_PRIVILEGES_FK1" FOREIGN KEY ("CLASS_TYPE")
	  REFERENCES "BPMMGR"."CLAUSE_CLASSES" ("CLASS_TYPE") DEFERRABLE INITIALLY DEFERRED ENABLE;
  ALTER TABLE "BPMMGR"."CLASS_PRIVILEGES" ADD CONSTRAINT "CLASS_PRIVILEGES_FK2" FOREIGN KEY ("RES_ID")
	  REFERENCES "DECMGR"."RESOURCES" ("ID") ENABLE;
