--------------------------------------------------------
--  Ref Constraints for Table COMPLIANCE_ACTIVITIES
--------------------------------------------------------

  ALTER TABLE "SPIREMGR"."COMPLIANCE_ACTIVITIES" ADD CONSTRAINT "COMPLIANCE_ACTIVITIES_FK1" FOREIGN KEY ("VISIT_ID")
	  REFERENCES "SPIREMGR"."COMPLIANCE_VISITS" ("ID") ENABLE;
  ALTER TABLE "SPIREMGR"."COMPLIANCE_ACTIVITIES" ADD CONSTRAINT "COMPLIANCE_ACTS_UREFS_FK" FOREIGN KEY ("ID")
	  REFERENCES "BPMMGR"."UREFS" ("CA_ID") DEFERRABLE INITIALLY DEFERRED ENABLE;
