--------------------------------------------------------
--  Ref Constraints for Table COMPLIANCE_PROFILE
--------------------------------------------------------

  ALTER TABLE "SPIREMGR"."COMPLIANCE_PROFILE" ADD CONSTRAINT "COMPLIANCE_PROFILE_FK1" FOREIGN KEY ("SITE_ID")
	  REFERENCES "SPIREMGR"."SITES" ("ID") ENABLE;
  ALTER TABLE "SPIREMGR"."COMPLIANCE_PROFILE" ADD CONSTRAINT "COMPLIANCE_PROFILE_FK2" FOREIGN KEY ("SET_BY_WUA_ID")
	  REFERENCES "SECUREMGR"."WEB_USER_ACCOUNT_MASTER" ("WUA_ID") ENABLE;
  ALTER TABLE "SPIREMGR"."COMPLIANCE_PROFILE" ADD CONSTRAINT "COMPLIANCE_PROFILE_FK3" FOREIGN KEY ("APPROVED_BY_WUA_ID")
	  REFERENCES "SECUREMGR"."WEB_USER_ACCOUNT_MASTER" ("WUA_ID") ENABLE;
