--------------------------------------------------------
--  Ref Constraints for Table CONTROL_ENTRIES
--------------------------------------------------------

  ALTER TABLE "SDBMGR"."CONTROL_ENTRIES" ADD CONSTRAINT "CONTROL_ENTRIES_FK1" FOREIGN KEY ("GI_ID")
	  REFERENCES "SDBMGR"."GOODS_INCIDENTS" ("ID") ENABLE;
  ALTER TABLE "SDBMGR"."CONTROL_ENTRIES" ADD CONSTRAINT "CONTROL_ENTRIES_FK2" FOREIGN KEY ("RATING")
	  REFERENCES "SDBMGR"."REF_REPORT_RATINGS" ("RATING") ENABLE;
