--------------------------------------------------------
--  Ref Constraints for Table COUNTRIES
--------------------------------------------------------

  ALTER TABLE "BPMMGR"."COUNTRIES" ADD CONSTRAINT "COUNTRIES_FK" FOREIGN KEY ("COUNTRY_SET_ID")
	  REFERENCES "BPMMGR"."COUNTRY_SETS" ("COUNTRY_SET_ID") ENABLE;
  ALTER TABLE "BPMMGR"."COUNTRIES" ADD CONSTRAINT "COUNTRIES_UREFS_FK" FOREIGN KEY ("ID")
	  REFERENCES "BPMMGR"."UREFS" ("COUNTRY_ID") DEFERRABLE INITIALLY DEFERRED ENABLE;
