--------------------------------------------------------
--  Ref Constraints for Table DOCUMENT_INSTANCES
--------------------------------------------------------

  ALTER TABLE "DECMGR"."DOCUMENT_INSTANCES" ADD CONSTRAINT "DOCUMENT_INSTANCES_FK1" FOREIGN KEY ("DP_ID")
	  REFERENCES "DECMGR"."DOCUMENT_PACKS" ("ID") ENABLE;
  ALTER TABLE "DECMGR"."DOCUMENT_INSTANCES" ADD CONSTRAINT "DOCUMENT_INSTANCES_FK2" FOREIGN KEY ("DC_ID")
	  REFERENCES "DECMGR"."DOCUMENT_COMPOSITIONS" ("ID") ENABLE;
  ALTER TABLE "DECMGR"."DOCUMENT_INSTANCES" ADD CONSTRAINT "DOCUMENT_INSTANCES_FK3" FOREIGN KEY ("COPY_OF_DI_ID")
	  REFERENCES "DECMGR"."DOCUMENT_INSTANCES" ("ID") ENABLE;
