--------------------------------------------------------
--  Ref Constraints for Table DOCUMENT_DOC_PACK_CONTENTS
--------------------------------------------------------

  ALTER TABLE "DECMGR"."DOCUMENT_DOC_PACK_CONTENTS" ADD CONSTRAINT "DOCUMENT_DOC_PACK_CONTENTS_FK1" FOREIGN KEY ("DCP_ID", "DS_ID")
	  REFERENCES "DECMGR"."DOCUMENT_COMPOSITION_PACKS" ("ID", "DS_ID") ENABLE;
  ALTER TABLE "DECMGR"."DOCUMENT_DOC_PACK_CONTENTS" ADD CONSTRAINT "DOCUMENT_DOC_PACK_CONTENTS_FK2" FOREIGN KEY ("DC_ID", "DS_ID")
	  REFERENCES "DECMGR"."DOCUMENT_COMPOSITIONS" ("ID", "DS_ID") ENABLE;
