--------------------------------------------------------
--  Ref Constraints for Table DOMAIN_SEVERITY_RECIPIENT
--------------------------------------------------------

  ALTER TABLE "FOXMGR"."DOMAIN_SEVERITY_RECIPIENT" ADD CONSTRAINT "DSR_FK1" FOREIGN KEY ("DOMAIN")
	  REFERENCES "FOXMGR"."SYSTEM_DOMAINS" ("ID") ENABLE;
  ALTER TABLE "FOXMGR"."DOMAIN_SEVERITY_RECIPIENT" ADD CONSTRAINT "DSR_FK2" FOREIGN KEY ("SEVERITY")
	  REFERENCES "FOXMGR"."APP_ERROR_SEVERITY" ("NAME") ENABLE;
  ALTER TABLE "FOXMGR"."DOMAIN_SEVERITY_RECIPIENT" ADD CONSTRAINT "DSR_FK3" FOREIGN KEY ("PERSON_ID")
	  REFERENCES "DECMGR"."RESOURCE_PEOPLE" ("ID") ENABLE;
