--------------------------------------------------------
--  Ref Constraints for Table ELA_TEMPLATES
--------------------------------------------------------

  ALTER TABLE "SPIREMGR"."ELA_TEMPLATES" ADD CONSTRAINT "ELA_TEMPLATES_FK1" FOREIGN KEY ("TYPE", "SUBTYPE")
	  REFERENCES "SPIREMGR"."ELA_TEMPLATE_TYPE" ("TYPE", "SUBTYPE") ENABLE;
  ALTER TABLE "SPIREMGR"."ELA_TEMPLATES" ADD CONSTRAINT "ELA_TEMPLATES_UREFS_FK" FOREIGN KEY ("ID")
	  REFERENCES "BPMMGR"."UREFS" ("ELA_TEMPLATES_ID") DEFERRABLE INITIALLY DEFERRED ENABLE;
