--------------------------------------------------------
--  Ref Constraints for Table EXPORT_LIC_STATUS_EVENT_DTLS
--------------------------------------------------------

  ALTER TABLE "SPIREMGR"."EXPORT_LIC_STATUS_EVENT_DTLS" ADD CONSTRAINT "EXP_LIC_STATUS_EVENT_DTLS_FK1" FOREIGN KEY ("ELSE_ID")
	  REFERENCES "SPIREMGR"."EXPORT_LICENCE_STATUS_EVENTS" ("ID") ENABLE;
  ALTER TABLE "SPIREMGR"."EXPORT_LIC_STATUS_EVENT_DTLS" ADD CONSTRAINT "EXP_LIC_STATUS_EVENT_DTLS_FK2" FOREIGN KEY ("CA_ID")
	  REFERENCES "SPIREMGR"."COMPLIANCE_ACTIVITIES" ("ID") ENABLE;
  ALTER TABLE "SPIREMGR"."EXPORT_LIC_STATUS_EVENT_DTLS" ADD CONSTRAINT "EXP_LIC_STATUS_EVENT_DTLS_FK3" FOREIGN KEY ("EVENT_STARTED_BY_WUA_ID")
	  REFERENCES "SECUREMGR"."WEB_USER_ACCOUNT_MASTER" ("WUA_ID") ENABLE;
  ALTER TABLE "SPIREMGR"."EXPORT_LIC_STATUS_EVENT_DTLS" ADD CONSTRAINT "EXP_LIC_STATUS_EVENT_DTLS_FK4" FOREIGN KEY ("EVENT_ENDED_BY_WUA_ID")
	  REFERENCES "SECUREMGR"."WEB_USER_ACCOUNT_MASTER" ("WUA_ID") ENABLE;
