--------------------------------------------------------
--  Ref Constraints for Table EXPORT_LICENCE_LINES
--------------------------------------------------------

  ALTER TABLE "SPIREMGR"."EXPORT_LICENCE_LINES" ADD CONSTRAINT "EXPORT_LICENCE_LINES_FK1" FOREIGN KEY ("LD_ID")
	  REFERENCES "SPIREMGR"."EXPORT_LICENCE_DETAILS" ("ID") ENABLE;
  ALTER TABLE "SPIREMGR"."EXPORT_LICENCE_LINES" ADD CONSTRAINT "EXPORT_LICENCE_LINES_FK2" FOREIGN KEY ("ELCG_ID")
	  REFERENCES "SPIREMGR"."EXPORT_LICENCE_COUNTRY_GROUPS" ("ID") ENABLE;
