--------------------------------------------------------
--  Ref Constraints for Table EXPORT_LICENCE_APPS
--------------------------------------------------------

  ALTER TABLE "SPIREMGR"."EXPORT_LICENCE_APPS" ADD CONSTRAINT "EXPORT_LICENCE_APPS_FK1" FOREIGN KEY ("PF_ID")
	  REFERENCES "DECMGR"."PORTAL_FOLDERS" ("ID") ENABLE;
  ALTER TABLE "SPIREMGR"."EXPORT_LICENCE_APPS" ADD CONSTRAINT "EXPORT_LICENCE_APPS_FK2" FOREIGN KEY ("PREVIOUS_ELA_ID")
	  REFERENCES "SPIREMGR"."EXPORT_LICENCE_APPS" ("ID") ENABLE;
  ALTER TABLE "SPIREMGR"."EXPORT_LICENCE_APPS" ADD CONSTRAINT "EXPORT_LICENCE_APPS_FK3" FOREIGN KEY ("ELA_GRP_ID")
	  REFERENCES "SPIREMGR"."ELA_GROUPS" ("ID") DEFERRABLE INITIALLY DEFERRED ENABLE;
  ALTER TABLE "SPIREMGR"."EXPORT_LICENCE_APPS" ADD CONSTRAINT "EXPORT_LICENCE_APPS_UREFS_FK" FOREIGN KEY ("ID")
	  REFERENCES "BPMMGR"."UREFS" ("ELA_ID") DEFERRABLE INITIALLY DEFERRED ENABLE;
