--------------------------------------------------------
--  Ref Constraints for Table EXPORT_LICENCES
--------------------------------------------------------

  ALTER TABLE "SPIREMGR"."EXPORT_LICENCES" ADD CONSTRAINT "EXPORT_LICENCES_FK1" FOREIGN KEY ("ELA_GRP_ID")
	  REFERENCES "SPIREMGR"."ELA_GROUPS" ("ID") ENABLE;
  ALTER TABLE "SPIREMGR"."EXPORT_LICENCES" ADD CONSTRAINT "EXPORT_LICENCES_UREFS_FK" FOREIGN KEY ("ID")
	  REFERENCES "BPMMGR"."UREFS" ("EXPORT_LICENCE_ID") DEFERRABLE INITIALLY DEFERRED ENABLE;
