--------------------------------------------------------
--  Ref Constraints for Table EXPORT_LICENCE_DETAILS
--------------------------------------------------------

  ALTER TABLE "SPIREMGR"."EXPORT_LICENCE_DETAILS" ADD CONSTRAINT "EXPORT_LICENCE_DETAILS_FK1" FOREIGN KEY ("ELA_GRP_ID", "L_ID")
	  REFERENCES "SPIREMGR"."EXPORT_LICENCES" ("ELA_GRP_ID", "ID") ENABLE;
  ALTER TABLE "SPIREMGR"."EXPORT_LICENCE_DETAILS" ADD CONSTRAINT "EXPORT_LICENCE_DETAILS_FK2" FOREIGN KEY ("ELA_ID", "ELA_DETAIL_ID")
	  REFERENCES "SPIREMGR"."EXPORT_LICENCE_APP_DETAILS" ("ELA_ID", "ID") ENABLE;
  ALTER TABLE "SPIREMGR"."EXPORT_LICENCE_DETAILS" ADD CONSTRAINT "EXPORT_LICENCE_DETAILS_FK3" FOREIGN KEY ("N_ID")
	  REFERENCES "DECMGR"."NOTIFICATIONS" ("ID") ENABLE;
  ALTER TABLE "SPIREMGR"."EXPORT_LICENCE_DETAILS" ADD CONSTRAINT "EXPORT_LICENCE_DETAILS_FK4" FOREIGN KEY ("OGL_ID")
	  REFERENCES "SPIREMGR"."OGL_TYPES" ("ID") ENABLE;
  ALTER TABLE "SPIREMGR"."EXPORT_LICENCE_DETAILS" ADD CONSTRAINT "EXPORT_LICENCE_DETAILS_FK5" FOREIGN KEY ("DI_ID")
	  REFERENCES "DECMGR"."DOCUMENT_INSTANCES" ("ID") ENABLE;
  ALTER TABLE "SPIREMGR"."EXPORT_LICENCE_DETAILS" ADD CONSTRAINT "EXP_LICENCE_DETAILS_UREFS_FK" FOREIGN KEY ("ID")
	  REFERENCES "BPMMGR"."UREFS" ("ELD_ID") DEFERRABLE INITIALLY DEFERRED ENABLE;
