--------------------------------------------------------
--  Ref Constraints for Table EXPORT_LICENCE_USAGES
--------------------------------------------------------

  ALTER TABLE "SPIREMGR"."EXPORT_LICENCE_USAGES" ADD CONSTRAINT "EXPORT_LICENCE_USAGES_FK1" FOREIGN KEY ("ELL_ID")
	  REFERENCES "SPIREMGR"."EXPORT_LICENCE_LINES" ("ID") ENABLE;
  ALTER TABLE "SPIREMGR"."EXPORT_LICENCE_USAGES" ADD CONSTRAINT "EXPORT_LICENCE_USAGES_FK2" FOREIGN KEY ("MC_ID")
	  REFERENCES "HMRCMGR"."MAIL_CONTROL" ("ID") ENABLE;
  ALTER TABLE "SPIREMGR"."EXPORT_LICENCE_USAGES" ADD CONSTRAINT "EXPORT_LICENCE_USAGES_FK3" FOREIGN KEY ("LD_ID")
	  REFERENCES "SPIREMGR"."EXPORT_LICENCE_DETAILS" ("ID") ENABLE;
