--------------------------------------------------------
--  Ref Constraints for Table FILE_TRANSMISSIONS
--------------------------------------------------------

  ALTER TABLE "PORTALMGR"."FILE_TRANSMISSIONS" ADD CONSTRAINT "FILE_TRANSMISSIONS_FK1" FOREIGN KEY ("TRANSMISSION_TYPE_MNEM")
	  REFERENCES "PORTALMGR"."FILE_TRANSMISSION_TYPES" ("TYPE_MNEM") ENABLE;
  ALTER TABLE "PORTALMGR"."FILE_TRANSMISSIONS" ADD CONSTRAINT "FILE_TRANSMISSIONS_FK2" FOREIGN KEY ("TRANSMISSION_TYPE_CONFIG_ID")
	  REFERENCES "PORTALMGR"."FILE_TRANSMISSION_TYPE_DETAILS" ("ID") ENABLE;
  ALTER TABLE "PORTALMGR"."FILE_TRANSMISSIONS" ADD CONSTRAINT "FILE_TRANSMISSIONS_FK3" FOREIGN KEY ("RETRY_OF_TRANSMISSION_ID")
	  REFERENCES "PORTALMGR"."FILE_TRANSMISSIONS" ("ID") ENABLE;
