--------------------------------------------------------
--  Ref Constraints for Table FILE_FOLDER_TARGETS
--------------------------------------------------------

  ALTER TABLE "DECMGR"."FILE_FOLDER_TARGETS" ADD CONSTRAINT "FILE_FOLDER_TARGETS_FK1" FOREIGN KEY ("FF_ID")
	  REFERENCES "DECMGR"."FILE_FOLDERS" ("ID") ENABLE;
  ALTER TABLE "DECMGR"."FILE_FOLDER_TARGETS" ADD CONSTRAINT "FILE_FOLDER_TARGETS_FK2" FOREIGN KEY ("LOCKED_BY_WUA_ID")
	  REFERENCES "SECUREMGR"."WEB_USER_ACCOUNT_MASTER" ("WUA_ID") ENABLE;
  ALTER TABLE "DECMGR"."FILE_FOLDER_TARGETS" ADD CONSTRAINT "FILE_FOLDER_TARGETS_UREFS_FK" FOREIGN KEY ("ID")
	  REFERENCES "BPMMGR"."UREFS" ("FILE_FOLDER_TARGET_ID") DEFERRABLE INITIALLY DEFERRED ENABLE;
