--------------------------------------------------------
--  Ref Constraints for Table FOOTNOTE_ENTRIES
--------------------------------------------------------

  ALTER TABLE "SDBMGR"."FOOTNOTE_ENTRIES" ADD CONSTRAINT "FOOTNOTE_ENTRIES_FK1" FOREIGN KEY ("FN_ID")
	  REFERENCES "SDBMGR"."FOOTNOTES" ("ID") ENABLE;
  ALTER TABLE "SDBMGR"."FOOTNOTE_ENTRIES" ADD CONSTRAINT "FOOTNOTE_ENTRIES_FK2" FOREIGN KEY ("BATCH_ID")
	  REFERENCES "SDBMGR"."BATCHES" ("ID") ENABLE;
  ALTER TABLE "SDBMGR"."FOOTNOTE_ENTRIES" ADD CONSTRAINT "FOOTNOTE_ENTRIES_FK3" FOREIGN KEY ("FNR_ID")
	  REFERENCES "SDBMGR"."FOOTNOTE_RULES" ("ID") ENABLE;
  ALTER TABLE "SDBMGR"."FOOTNOTE_ENTRIES" ADD CONSTRAINT "FOOTNOTE_ENTRIES_FK4" FOREIGN KEY ("ELA_GRP_ID")
	  REFERENCES "SDBMGR"."APPLICATIONS" ("ELA_GRP_ID") ENABLE;
  ALTER TABLE "SDBMGR"."FOOTNOTE_ENTRIES" ADD CONSTRAINT "FOOTNOTE_ENTRIES_FK5" FOREIGN KEY ("COUNTRY_ID")
	  REFERENCES "BPMMGR"."COUNTRIES" ("ID") ENABLE;
  ALTER TABLE "SDBMGR"."FOOTNOTE_ENTRIES" ADD CONSTRAINT "FOOTNOTE_ENTRIES_FK6" FOREIGN KEY ("MFD_ID")
	  REFERENCES "SDBMGR"."MEDIA_FOOTNOTE_DETAILS" ("ID") ENABLE;
