--------------------------------------------------------
--  Ref Constraints for Table GOODS_INCIDENTS
--------------------------------------------------------

  ALTER TABLE "SDBPUBMGR"."GOODS_INCIDENTS" ADD CONSTRAINT "GOODS_INCIDENTS_FK1" FOREIGN KEY ("ELA_GRP_ID")
	  REFERENCES "SDBPUBMGR"."APPLICATIONS" ("ELA_GRP_ID") ENABLE;
  ALTER TABLE "SDBPUBMGR"."GOODS_INCIDENTS" ADD CONSTRAINT "GOODS_INCIDENTS_FK2" FOREIGN KEY ("BATCH_ID")
	  REFERENCES "SDBPUBMGR"."BATCHES" ("ID") ENABLE;
  ALTER TABLE "SDBPUBMGR"."GOODS_INCIDENTS" ADD CONSTRAINT "GOODS_INCIDENTS_FK4" FOREIGN KEY ("SOURCE_COUNTRY_GRP_ID")
	  REFERENCES "SDBPUBMGR"."COUNTRY_GROUPS" ("ID") ENABLE;
