--------------------------------------------------------
--  Ref Constraints for Table GOODS_INCIDENTS
--------------------------------------------------------

  ALTER TABLE "SDBMGR"."GOODS_INCIDENTS" ADD CONSTRAINT "GOODS_INCIDENTS_FK1" FOREIGN KEY ("ELA_GRP_ID")
	  REFERENCES "SDBMGR"."APPLICATIONS" ("ELA_GRP_ID") ENABLE;
  ALTER TABLE "SDBMGR"."GOODS_INCIDENTS" ADD CONSTRAINT "GOODS_INCIDENTS_FK2" FOREIGN KEY ("BATCH_ID")
	  REFERENCES "SDBMGR"."BATCHES" ("ID") ENABLE;
  ALTER TABLE "SDBMGR"."GOODS_INCIDENTS" ADD CONSTRAINT "GOODS_INCIDENTS_FK3" FOREIGN KEY ("DEST_COUNTRY_ID")
	  REFERENCES "BPMMGR"."COUNTRIES" ("ID") ENABLE;
  ALTER TABLE "SDBMGR"."GOODS_INCIDENTS" ADD CONSTRAINT "GOODS_INCIDENTS_FK4" FOREIGN KEY ("SOURCE_COUNTRY_GRP_ID")
	  REFERENCES "SDBMGR"."COUNTRY_GROUPS" ("ID") ENABLE;
