--------------------------------------------------------
--  Ref Constraints for Table INCIDENTS
--------------------------------------------------------

  ALTER TABLE "SDBMGR"."INCIDENTS" ADD CONSTRAINT "INCIDENTS_FK1" FOREIGN KEY ("BATCH_ID")
	  REFERENCES "SDBMGR"."BATCHES" ("ID") ENABLE;
  ALTER TABLE "SDBMGR"."INCIDENTS" ADD CONSTRAINT "INCIDENTS_FK2" FOREIGN KEY ("ELA_GRP_ID")
	  REFERENCES "SDBMGR"."APPLICATIONS" ("ELA_GRP_ID") ENABLE;
  ALTER TABLE "SDBMGR"."INCIDENTS" ADD CONSTRAINT "INCIDENTS_FK3" FOREIGN KEY ("ELA_ID")
	  REFERENCES "SPIREMGR"."EXPORT_LICENCE_APPS" ("ID") ENABLE;
  ALTER TABLE "SDBMGR"."INCIDENTS" ADD CONSTRAINT "INCIDENTS_FK4" FOREIGN KEY ("LICENCE_ID")
	  REFERENCES "SPIREMGR"."EXPORT_LICENCES" ("ID") ENABLE;
  ALTER TABLE "SDBMGR"."INCIDENTS" ADD CONSTRAINT "INCIDENTS_FK5" FOREIGN KEY ("OGL_ID")
	  REFERENCES "SPIREMGR"."OGL_TYPES" ("ID") ENABLE;
  ALTER TABLE "SDBMGR"."INCIDENTS" ADD CONSTRAINT "INCIDENTS_FK6" FOREIGN KEY ("ELSE_ID")
	  REFERENCES "SPIREMGR"."EXPORT_LICENCE_STATUS_EVENTS" ("ID") ENABLE;
