--------------------------------------------------------
--  Ref Constraints for Table INTENTIONS
--------------------------------------------------------

  ALTER TABLE "BPMMGR"."INTENTIONS" ADD CONSTRAINT "INTENTIONS_FK1" FOREIGN KEY ("ORIGINAL_ID_ID")
	  REFERENCES "BPMMGR"."INTENTION_DETAILS" ("ID") ENABLE;
  ALTER TABLE "BPMMGR"."INTENTIONS" ADD CONSTRAINT "INTENTION_UREFS_FK" FOREIGN KEY ("ID")
	  REFERENCES "BPMMGR"."UREFS" ("INTENTION_ID") DEFERRABLE INITIALLY DEFERRED ENABLE;
