--------------------------------------------------------
--  Ref Constraints for Table MATRIX_FOLDER_ITEMS
--------------------------------------------------------

  ALTER TABLE "DECMGR"."MATRIX_FOLDER_ITEMS" ADD CONSTRAINT "MATRIX_FOLDER_ITEMS_FK1" FOREIGN KEY ("MF_ID")
	  REFERENCES "DECMGR"."MATRIX_FOLDERS" ("ID") ENABLE;
  ALTER TABLE "DECMGR"."MATRIX_FOLDER_ITEMS" ADD CONSTRAINT "MATRIX_FOLDER_ITEMS_FK2" FOREIGN KEY ("PFI_ID")
	  REFERENCES "DECMGR"."PORTAL_FOLDER_ITEMS" ("ID") ENABLE;
