--------------------------------------------------------
--  Ref Constraints for Table NOTE_UREFS
--------------------------------------------------------

  ALTER TABLE "DECMGR"."NOTE_UREFS" ADD CONSTRAINT "NOTE_UREFS_FK1" FOREIGN KEY ("N_ID")
	  REFERENCES "DECMGR"."NOTES" ("ID") ENABLE;
  ALTER TABLE "DECMGR"."NOTE_UREFS" ADD CONSTRAINT "NOTE_UREFS_FK2" FOREIGN KEY ("UREF")
	  REFERENCES "BPMMGR"."UREFS" ("UREF") ENABLE;
  ALTER TABLE "DECMGR"."NOTE_UREFS" ADD CONSTRAINT "NOTE_UREFS_UREFS_FK" FOREIGN KEY ("ID")
	  REFERENCES "BPMMGR"."UREFS" ("NOTE_UREFS_ID") DEFERRABLE INITIALLY DEFERRED ENABLE;
