--------------------------------------------------------
--  Ref Constraints for Table NOTIFICATIONS
--------------------------------------------------------

  ALTER TABLE "DECMGR"."NOTIFICATIONS" ADD CONSTRAINT "NOTIFICATIONS_FK1" FOREIGN KEY ("DP_ID")
	  REFERENCES "DECMGR"."DOCUMENT_PACKS" ("ID") ENABLE;
  ALTER TABLE "DECMGR"."NOTIFICATIONS" ADD CONSTRAINT "NOTIFICATIONS_FK2" FOREIGN KEY ("NS_ID")
	  REFERENCES "DECMGR"."NOTIFICATION_SETS" ("ID") ENABLE;
  ALTER TABLE "DECMGR"."NOTIFICATIONS" ADD CONSTRAINT "NOTIFICATIONS_FK3" FOREIGN KEY ("ORGAN_ID")
	  REFERENCES "DECMGR"."ORGANISATION_UNIT_MASTER" ("ORGAN_ID") ENABLE;
  ALTER TABLE "DECMGR"."NOTIFICATIONS" ADD CONSTRAINT "NOTIFICATIONS_FK4" FOREIGN KEY ("PERSON_ID")
	  REFERENCES "DECMGR"."RESOURCE_PEOPLE" ("ID") ENABLE;
  ALTER TABLE "DECMGR"."NOTIFICATIONS" ADD CONSTRAINT "NOTIFICATIONS_UREFS_FK" FOREIGN KEY ("ID")
	  REFERENCES "BPMMGR"."UREFS" ("NOTIFICATIONS_ID") DEFERRABLE INITIALLY DEFERRED ENABLE;
