--------------------------------------------------------
--  Ref Constraints for Table OGL_BLACKLISTS
--------------------------------------------------------

  ALTER TABLE "SPIREMGR"."OGL_BLACKLISTS" ADD CONSTRAINT "OGL_BLACKLISTS_FK1" FOREIGN KEY ("CA_ID")
	  REFERENCES "SPIREMGR"."COMPLIANCE_ACTIVITIES" ("ID") ENABLE;
  ALTER TABLE "SPIREMGR"."OGL_BLACKLISTS" ADD CONSTRAINT "OGL_BLACKLISTS_FK2" FOREIGN KEY ("OGL_TYPE_ID")
	  REFERENCES "SPIREMGR"."OGL_TYPES" ("ID") ENABLE;
  ALTER TABLE "SPIREMGR"."OGL_BLACKLISTS" ADD CONSTRAINT "OGL_BLACKLISTS_FK3" FOREIGN KEY ("SITE_ID")
	  REFERENCES "SPIREMGR"."SITES" ("ID") ENABLE;
  ALTER TABLE "SPIREMGR"."OGL_BLACKLISTS" ADD CONSTRAINT "OGL_BLACKLISTS_FK4" FOREIGN KEY ("STARTED_BY_WUA_ID")
	  REFERENCES "SECUREMGR"."WEB_USER_ACCOUNT_MASTER" ("WUA_ID") ENABLE;
  ALTER TABLE "SPIREMGR"."OGL_BLACKLISTS" ADD CONSTRAINT "OGL_BLACKLISTS_FK5" FOREIGN KEY ("ENDED_BY_WUA_ID")
	  REFERENCES "SECUREMGR"."WEB_USER_ACCOUNT_MASTER" ("WUA_ID") ENABLE;
