--------------------------------------------------------
--  Ref Constraints for Table PATCH_RUNS
--------------------------------------------------------

  ALTER TABLE "PROMOTEMGR"."PATCH_RUNS" ADD CONSTRAINT "PATCH_RUNS_FK1" FOREIGN KEY ("PATCH_LABEL", "PATCH_NUMBER")
	  REFERENCES "PROMOTEMGR"."PATCHES" ("PATCH_LABEL", "PATCH_NUMBER") ENABLE;
  ALTER TABLE "PROMOTEMGR"."PATCH_RUNS" ADD CONSTRAINT "PATCH_RUNS_FK2" FOREIGN KEY ("PROMOTION_LABEL")
	  REFERENCES "PROMOTEMGR"."PROMOTION_LABELS" ("LABEL") ENABLE;
  ALTER TABLE "PROMOTEMGR"."PATCH_RUNS" ADD CONSTRAINT "PATCH_RUNS_FK3" FOREIGN KEY ("PROMOTION_RUN_ID")
	  REFERENCES "PROMOTEMGR"."PROMOTION_RUNS" ("ID") ENABLE;
