--------------------------------------------------------
--  Ref Constraints for Table PATCH_RUN_STATEMENTS
--------------------------------------------------------

  ALTER TABLE "PROMOTEMGR"."PATCH_RUN_STATEMENTS" ADD CONSTRAINT "PATCH_RUN_STATEMENTS_FK1" FOREIGN KEY ("PATCH_LABEL", "PATCH_NUMBER")
	  REFERENCES "PROMOTEMGR"."PATCHES" ("PATCH_LABEL", "PATCH_NUMBER") ENABLE;
  ALTER TABLE "PROMOTEMGR"."PATCH_RUN_STATEMENTS" ADD CONSTRAINT "PATCH_RUN_STATEMENTS_FK2" FOREIGN KEY ("PATCH_RUN_ID")
	  REFERENCES "PROMOTEMGR"."PATCH_RUNS" ("ID") ENABLE;
