--------------------------------------------------------
--  Ref Constraints for Table PORTAL_FOLDER_ITEMS
--------------------------------------------------------

  ALTER TABLE "DECMGR"."PORTAL_FOLDER_ITEMS" ADD CONSTRAINT "PORTAL_FOLDER_ITEMS_FK1" FOREIGN KEY ("PFA_ID")
	  REFERENCES "DECMGR"."PORTAL_FOLDER_ABSTRACTS" ("ID") ENABLE;
  ALTER TABLE "DECMGR"."PORTAL_FOLDER_ITEMS" ADD CONSTRAINT "PORTAL_FOLDER_ITEMS_FK2" FOREIGN KEY ("DD_IMMUTABLE_ID")
	  REFERENCES "DECMGR"."DOCUMENT_DATA" ("DD_IMMUTABLE_ID") ENABLE;
  ALTER TABLE "DECMGR"."PORTAL_FOLDER_ITEMS" ADD CONSTRAINT "PORTAL_FOLDER_ITEMS_FK3" FOREIGN KEY ("AUTH_REQ_ID")
	  REFERENCES "DECMGR"."AUTHORISATION_REQUESTS" ("ID") ENABLE;
