--------------------------------------------------------
--  Ref Constraints for Table PORTAL_SCHEDULE_INSTANCES
--------------------------------------------------------

  ALTER TABLE "DECMGR"."PORTAL_SCHEDULE_INSTANCES" ADD CONSTRAINT "PORTAL_SCHEDULE_INSTANCES_FK1" FOREIGN KEY ("SCHEDULE_GROUP_ID")
	  REFERENCES "DECMGR"."PORTAL_SCHEDULE_GROUPS" ("ID") ENABLE;
  ALTER TABLE "DECMGR"."PORTAL_SCHEDULE_INSTANCES" ADD CONSTRAINT "PS_INSTANCES_UREFS_FK" FOREIGN KEY ("ID")
	  REFERENCES "BPMMGR"."UREFS" ("PORTAL_SCHEDULE_INSTANCE_ID") DEFERRABLE INITIALLY DEFERRED ENABLE;
