--------------------------------------------------------
--  Ref Constraints for Table PROMOTION_FILES
--------------------------------------------------------

  ALTER TABLE "PROMOTEMGR"."PROMOTION_FILES" ADD CONSTRAINT "PROMOTION_FILES_FK1" FOREIGN KEY ("PROMOTION_RUN_ID")
	  REFERENCES "PROMOTEMGR"."PROMOTION_RUNS" ("ID") ENABLE;
  ALTER TABLE "PROMOTEMGR"."PROMOTION_FILES" ADD CONSTRAINT "PROMOTION_FILES_FK2" FOREIGN KEY ("PROMOTION_LABEL")
	  REFERENCES "PROMOTEMGR"."PROMOTION_LABELS" ("LABEL") ENABLE;
