--------------------------------------------------------
--  Ref Constraints for Table PV_EX_APPLICATIONS
--------------------------------------------------------

  ALTER TABLE "PVEXMGR"."PV_EX_APPLICATIONS" ADD CONSTRAINT "PEA_FK1" FOREIGN KEY ("SDD_ID")
	  REFERENCES "PVEXMGR"."SCHEMA_DEFINITION_DETAILS" ("ID") ENABLE;
  ALTER TABLE "PVEXMGR"."PV_EX_APPLICATIONS" ADD CONSTRAINT "PEA_FK2" FOREIGN KEY ("BASED_ON_PEA_ID")
	  REFERENCES "PVEXMGR"."PV_EX_APPLICATIONS" ("ID") ENABLE;
  ALTER TABLE "PVEXMGR"."PV_EX_APPLICATIONS" ADD CONSTRAINT "PV_EX_APPLICATIONS_UREFS_FK" FOREIGN KEY ("ID")
	  REFERENCES "BPMMGR"."UREFS" ("PEA_ID") DEFERRABLE INITIALLY DEFERRED ENABLE;
