--------------------------------------------------------
--  Ref Constraints for Table REPORT_PARTS_OUTPUTS
--------------------------------------------------------

  ALTER TABLE "REPORTMGR"."REPORT_PARTS_OUTPUTS" ADD CONSTRAINT "REPORT_PARTS_OUTPUTS_FK1" FOREIGN KEY ("RP_ID")
	  REFERENCES "REPORTMGR"."REPORT_PARTS" ("ID") ENABLE;
  ALTER TABLE "REPORTMGR"."REPORT_PARTS_OUTPUTS" ADD CONSTRAINT "REPORT_PARTS_OUTPUTS_FK2" FOREIGN KEY ("DI_ID")
	  REFERENCES "DECMGR"."DOCUMENT_INSTANCES" ("ID") ENABLE;
