--------------------------------------------------------
--  Ref Constraints for Table REPORT_RUNS
--------------------------------------------------------

  ALTER TABLE "REPORTMGR"."REPORT_RUNS" ADD CONSTRAINT "REPORT_RUNS_FK1" FOREIGN KEY ("DOMAIN")
	  REFERENCES "REPORTMGR"."REPORT_DEFINITIONS" ("DOMAIN") ENABLE;
  ALTER TABLE "REPORTMGR"."REPORT_RUNS" ADD CONSTRAINT "REPORT_RUNS_FK2" FOREIGN KEY ("RS_ID")
	  REFERENCES "REPORTMGR"."REPORT_SCHEDULES" ("ID") ENABLE;
  ALTER TABLE "REPORTMGR"."REPORT_RUNS" ADD CONSTRAINT "REPORT_RUNS_UREFS_FK" FOREIGN KEY ("ID")
	  REFERENCES "BPMMGR"."UREFS" ("RPT_RUN_ID") DEFERRABLE INITIALLY DEFERRED ENABLE;
