--------------------------------------------------------
--  Ref Constraints for Table RESOURCES
--------------------------------------------------------

  ALTER TABLE "DECMGR"."RESOURCES" ADD CONSTRAINT "RESOURCES_FK1" FOREIGN KEY ("RES_TYPE")
	  REFERENCES "DECMGR"."RESOURCE_TYPES" ("RES_TYPE") ENABLE;
  ALTER TABLE "DECMGR"."RESOURCES" ADD CONSTRAINT "RESOURCES_UREFS_FK" FOREIGN KEY ("ID")
	  REFERENCES "BPMMGR"."UREFS" ("RESOURCES_ID") DEFERRABLE INITIALLY DEFERRED ENABLE;
