--------------------------------------------------------
--  Ref Constraints for Table RESOURCE_USAGES
--------------------------------------------------------

  ALTER TABLE "DECMGR"."RESOURCE_USAGES" ADD CONSTRAINT "RESOURCE_USAGES_FK1" FOREIGN KEY ("UREF")
	  REFERENCES "BPMMGR"."UREFS" ("UREF") DEFERRABLE INITIALLY DEFERRED ENABLE;
  ALTER TABLE "DECMGR"."RESOURCE_USAGES" ADD CONSTRAINT "RESOURCE_USAGES_FK2" FOREIGN KEY ("RES_ID")
	  REFERENCES "DECMGR"."RESOURCES" ("ID") ENABLE;
