--------------------------------------------------------
--  Ref Constraints for Table RESOURCE_ROLES
--------------------------------------------------------

  ALTER TABLE "DECMGR"."RESOURCE_ROLES" ADD CONSTRAINT "RESOURCE_ROLES_FK1" FOREIGN KEY ("RES_ID")
	  REFERENCES "DECMGR"."RESOURCES" ("ID") ON DELETE CASCADE DEFERRABLE INITIALLY DEFERRED ENABLE;
  ALTER TABLE "DECMGR"."RESOURCE_ROLES" ADD CONSTRAINT "RES_ROLES_UREFS_FK" FOREIGN KEY ("ID")
	  REFERENCES "BPMMGR"."UREFS" ("RESOURCE_ROLES_ID") DEFERRABLE INITIALLY DEFERRED ENABLE;
