--------------------------------------------------------
--  Ref Constraints for Table REVIEW_ADVISOR_SLOT_DETAILS
--------------------------------------------------------

  ALTER TABLE "BPMMGR"."REVIEW_ADVISOR_SLOT_DETAILS" ADD CONSTRAINT "REVIEW_ADVISOR_SLOT_DTLS_FK1" FOREIGN KEY ("RAS_ID")
	  REFERENCES "BPMMGR"."REVIEW_ADVISOR_SLOTS" ("ID") ENABLE;
  ALTER TABLE "BPMMGR"."REVIEW_ADVISOR_SLOT_DETAILS" ADD CONSTRAINT "REVIEW_ADVISOR_SLOT_DTLS_FK2" FOREIGN KEY ("INTENTION_SET_ID")
	  REFERENCES "BPMMGR"."INTENTION_SETS" ("ID") DEFERRABLE INITIALLY DEFERRED ENABLE;
