--------------------------------------------------------
--  Ref Constraints for Table REVIEW_REMOTE_DWNLOAD_CONTENTS
--------------------------------------------------------

  ALTER TABLE "BPMMGR"."REVIEW_REMOTE_DWNLOAD_CONTENTS" ADD CONSTRAINT "REVIEW_REMOTE_DWN_CONTENTS_FK1" FOREIGN KEY ("RRD_ID")
	  REFERENCES "BPMMGR"."REVIEW_REMOTE_DOWNLOADS" ("ID") ENABLE;
  ALTER TABLE "BPMMGR"."REVIEW_REMOTE_DWNLOAD_CONTENTS" ADD CONSTRAINT "REVIEW_REMOTE_DWN_CONTENTS_FK2" FOREIGN KEY ("RA_ID")
	  REFERENCES "BPMMGR"."REVIEW_ADVISORS" ("ID") ENABLE;
  ALTER TABLE "BPMMGR"."REVIEW_REMOTE_DWNLOAD_CONTENTS" ADD CONSTRAINT "REVIEW_REMOTE_DWN_CONTENTS_FK3" FOREIGN KEY ("CREATED_BY_WUA_ID")
	  REFERENCES "SECUREMGR"."WEB_USER_ACCOUNT_MASTER" ("WUA_ID") ENABLE;
