--------------------------------------------------------
--  Ref Constraints for Table REVIEW_REMOTE_UPLOADS
--------------------------------------------------------

  ALTER TABLE "BPMMGR"."REVIEW_REMOTE_UPLOADS" ADD CONSTRAINT "REVIEW_REMOTE_UPLOADS_FK1" FOREIGN KEY ("CREATED_BY_WUA_ID")
	  REFERENCES "SECUREMGR"."WEB_USER_ACCOUNT_MASTER" ("WUA_ID") ENABLE;
  ALTER TABLE "BPMMGR"."REVIEW_REMOTE_UPLOADS" ADD CONSTRAINT "REVIEW_REMOTE_UPLOADS_FK2" FOREIGN KEY ("ADVICE_TYPE")
	  REFERENCES "BPMMGR"."ADVICE_TYPES" ("ADVICE_TYPE") ENABLE;
