--------------------------------------------------------
--  Ref Constraints for Table REVIEW_REMOTE_UPLOAD_SLOTS
--------------------------------------------------------

  ALTER TABLE "BPMMGR"."REVIEW_REMOTE_UPLOAD_SLOTS" ADD CONSTRAINT "REVIEW_REMOTE_UPLOAD_SLOTS_FK1" FOREIGN KEY ("RRUC_ID")
	  REFERENCES "BPMMGR"."REVIEW_REMOTE_UPLOAD_CONTENTS" ("ID") ENABLE;
  ALTER TABLE "BPMMGR"."REVIEW_REMOTE_UPLOAD_SLOTS" ADD CONSTRAINT "REVIEW_REMOTE_UPLOAD_SLOTS_FK2" FOREIGN KEY ("RAS_ID")
	  REFERENCES "BPMMGR"."REVIEW_ADVISOR_SLOTS" ("ID") ENABLE;
