--------------------------------------------------------
--  Ref Constraints for Table REVIEW_REQ_BATCH_ADVICE
--------------------------------------------------------

  ALTER TABLE "BPMMGR"."REVIEW_REQ_BATCH_ADVICE" ADD CONSTRAINT "REVIEW_REQ_BATCH_ADVICE_FK1" FOREIGN KEY ("RREQ_ID")
	  REFERENCES "BPMMGR"."REVIEW_REQUESTS" ("ID") ENABLE;
  ALTER TABLE "BPMMGR"."REVIEW_REQ_BATCH_ADVICE" ADD CONSTRAINT "REVIEW_REQ_BATCH_ADVICE_FK2" FOREIGN KEY ("PERSON_ID")
	  REFERENCES "DECMGR"."RESOURCE_PEOPLE" ("ID") ENABLE;
