--------------------------------------------------------
--  Ref Constraints for Table REVIEW_REQUESTS
--------------------------------------------------------

  ALTER TABLE "BPMMGR"."REVIEW_REQUESTS" ADD CONSTRAINT "REVIEW_REQUESTS_FK1" FOREIGN KEY ("RRUN_ID")
	  REFERENCES "BPMMGR"."REVIEW_RUNS" ("ID") ENABLE;
  ALTER TABLE "BPMMGR"."REVIEW_REQUESTS" ADD CONSTRAINT "REVIEW_REQUESTS_FK2" FOREIGN KEY ("AAC_ID")
	  REFERENCES "BPMMGR"."ADVICE_ADVISORY_COMMUNITIES" ("ID") ENABLE;
