--------------------------------------------------------
--  Ref Constraints for Table REVIEW_ADVISORS
--------------------------------------------------------

  ALTER TABLE "BPMMGR"."REVIEW_ADVISORS" ADD CONSTRAINT "REVIEW_ADVISORS_FK1" FOREIGN KEY ("RREQ_ID")
	  REFERENCES "BPMMGR"."REVIEW_REQUESTS" ("ID") ENABLE;
  ALTER TABLE "BPMMGR"."REVIEW_ADVISORS" ADD CONSTRAINT "REVIEW_ADVISORS_FK2" FOREIGN KEY ("BAS_ID")
	  REFERENCES "BPMMGR"."BUSINESS_ASSIGNMENTS" ("ID") ENABLE;
  ALTER TABLE "BPMMGR"."REVIEW_ADVISORS" ADD CONSTRAINT "REVIEW_ADVISOR_UREFS_FK" FOREIGN KEY ("ID")
	  REFERENCES "BPMMGR"."UREFS" ("REVIEW_ADVISOR_ID") DEFERRABLE INITIALLY DEFERRED ENABLE;
