--------------------------------------------------------
--  Ref Constraints for Table REVIEW_REMOTE_UPLOAD_CONTENTS
--------------------------------------------------------

  ALTER TABLE "BPMMGR"."REVIEW_REMOTE_UPLOAD_CONTENTS" ADD CONSTRAINT "REVIEW_REMOTE_UPL_CONTENTS_FK1" FOREIGN KEY ("RRU_ID")
	  REFERENCES "BPMMGR"."REVIEW_REMOTE_UPLOADS" ("ID") ENABLE;
  ALTER TABLE "BPMMGR"."REVIEW_REMOTE_UPLOAD_CONTENTS" ADD CONSTRAINT "REVIEW_REMOTE_UPL_CONTENTS_FK2" FOREIGN KEY ("RRDC_ID")
	  REFERENCES "BPMMGR"."REVIEW_REMOTE_DWNLOAD_CONTENTS" ("ID") ENABLE;
  ALTER TABLE "BPMMGR"."REVIEW_REMOTE_UPLOAD_CONTENTS" ADD CONSTRAINT "REVIEW_REMOTE_UPL_CONTENTS_FK3" FOREIGN KEY ("CREATED_BY_WUA_ID")
	  REFERENCES "SECUREMGR"."WEB_USER_ACCOUNT_MASTER" ("WUA_ID") ENABLE;
  ALTER TABLE "BPMMGR"."REVIEW_REMOTE_UPLOAD_CONTENTS" ADD CONSTRAINT "REVIEW_REMOTE_UPL_CONTENTS_FK4" FOREIGN KEY ("AAC_ID")
	  REFERENCES "BPMMGR"."ADVICE_ADVISORY_COMMUNITIES" ("ID") ENABLE;
