--------------------------------------------------------
--  Ref Constraints for Table SCAN_TARGETS
--------------------------------------------------------

  ALTER TABLE "DECMGR"."SCAN_TARGETS" ADD CONSTRAINT "SCAN_TARGETS_FK1" FOREIGN KEY ("SEC_ID")
	  REFERENCES "DECMGR"."SCAN_EXCHANGE_CONTEXTS" ("ID") ENABLE;
  ALTER TABLE "DECMGR"."SCAN_TARGETS" ADD CONSTRAINT "SCAN_TARGETS_FK2" FOREIGN KEY ("SCAN_TYPE")
	  REFERENCES "DECMGR"."SCAN_TYPES" ("SCAN_TYPE") ENABLE;
  ALTER TABLE "DECMGR"."SCAN_TARGETS" ADD CONSTRAINT "SCAN_TARGETS_FK3" FOREIGN KEY ("TARGET_UREF")
	  REFERENCES "BPMMGR"."UREFS" ("UREF") ENABLE;
