--------------------------------------------------------
--  Ref Constraints for Table SCAN_PRINT_BATCH
--------------------------------------------------------

  ALTER TABLE "DECMGR"."SCAN_PRINT_BATCH" ADD CONSTRAINT "SCAN_PRINT_BATCH_FK1" FOREIGN KEY ("SP_ID")
	  REFERENCES "DECMGR"."SCAN_PREFERENCES" ("ID") ENABLE;
  ALTER TABLE "DECMGR"."SCAN_PRINT_BATCH" ADD CONSTRAINT "SCAN_PRINT_BATCH_FK2" FOREIGN KEY ("DI_ID")
	  REFERENCES "DECMGR"."DOCUMENT_INSTANCES" ("ID") DEFERRABLE INITIALLY DEFERRED ENABLE;
