--------------------------------------------------------
--  Ref Constraints for Table SCAN_PREFERENCES
--------------------------------------------------------

  ALTER TABLE "DECMGR"."SCAN_PREFERENCES" ADD CONSTRAINT "SCAN_PREFERENCES_FK1" FOREIGN KEY ("SPT_ID")
	  REFERENCES "DECMGR"."SCAN_PREFERENCE_TEMPLATES" ("ID") ENABLE;
  ALTER TABLE "DECMGR"."SCAN_PREFERENCES" ADD CONSTRAINT "SCAN_PREFERENCES_FK2" FOREIGN KEY ("WUA_ID")
	  REFERENCES "SECUREMGR"."WEB_USER_ACCOUNT_MASTER" ("WUA_ID") ENABLE;
  ALTER TABLE "DECMGR"."SCAN_PREFERENCES" ADD CONSTRAINT "SCAN_PREFERENCES_FK3" FOREIGN KEY ("DS_ID")
	  REFERENCES "DECMGR"."DOCUMENT_SETS" ("ID") ENABLE;
