--------------------------------------------------------
--  Ref Constraints for Table SECURITY_OBJECT_RULES
--------------------------------------------------------

  ALTER TABLE "BPMMGR"."SECURITY_OBJECT_RULES" ADD CONSTRAINT "SECURITY_OBJECT_RULES_FK1" FOREIGN KEY ("GRANTEE_UREF_TYPE")
	  REFERENCES "BPMMGR"."UREF_TYPES" ("UREF_TYPE") ENABLE;
  ALTER TABLE "BPMMGR"."SECURITY_OBJECT_RULES" ADD CONSTRAINT "SECURITY_OBJECT_RULES_FK2" FOREIGN KEY ("OBJECT_UREF_TYPE")
	  REFERENCES "BPMMGR"."UREF_TYPES" ("UREF_TYPE") ENABLE;
