--------------------------------------------------------
--  Ref Constraints for Table SPIRE_APPLICANT_DETAILS
--------------------------------------------------------

  ALTER TABLE "SPIREMGR"."SPIRE_APPLICANT_DETAILS" ADD CONSTRAINT "SPIRE_APPLICANT_DETAILS_FK1" FOREIGN KEY ("SA_ID")
	  REFERENCES "SPIREMGR"."SPIRE_APPLICANTS" ("ID") ENABLE;
  ALTER TABLE "SPIREMGR"."SPIRE_APPLICANT_DETAILS" ADD CONSTRAINT "SPIRE_APP_DETAIL_UREFS_FK" FOREIGN KEY ("ID")
	  REFERENCES "BPMMGR"."UREFS" ("SPIRE_AP_DTL_ID") DEFERRABLE INITIALLY DEFERRED ENABLE;
