--------------------------------------------------------
--  Ref Constraints for Table STRUCTURED_CODE_CONTROLS
--------------------------------------------------------

  ALTER TABLE "SPIREMGR"."STRUCTURED_CODE_CONTROLS" ADD CONSTRAINT "STRUCTURED_CODE_CONTROLS_FK1" FOREIGN KEY ("SC_ID")
	  REFERENCES "SPIREMGR"."STRUCTURED_CODES" ("ID") ENABLE;
  ALTER TABLE "SPIREMGR"."STRUCTURED_CODE_CONTROLS" ADD CONSTRAINT "STRUCTURED_CODE_CONTROLS_FK2" FOREIGN KEY ("REFERENCED_SC_ID")
	  REFERENCES "SPIREMGR"."STRUCTURED_CODES" ("ID") ENABLE;
  ALTER TABLE "SPIREMGR"."STRUCTURED_CODE_CONTROLS" ADD CONSTRAINT "STRUCTURED_CODE_CONTROLS_FK3" FOREIGN KEY ("CONTROL_TYPE")
	  REFERENCES "SPIREMGR"."STRUCTURED_CODE_TYPE_CONTROLS" ("CONTROL_TYPE") ENABLE;
  ALTER TABLE "SPIREMGR"."STRUCTURED_CODE_CONTROLS" ADD CONSTRAINT "STRUCTURED_CODE_CONTROLS_FK4" FOREIGN KEY ("SCR_ID")
	  REFERENCES "SPIREMGR"."STRUCTURED_CODE_REVISIONS" ("ID") ENABLE;
