--------------------------------------------------------
--  Ref Constraints for Table STRUCTURED_CODES
--------------------------------------------------------

  ALTER TABLE "SPIREMGR"."STRUCTURED_CODES" ADD CONSTRAINT "STRUCTURED_CODES_FK1" FOREIGN KEY ("SC_TYPE")
	  REFERENCES "SPIREMGR"."STRUCTURED_CODE_TYPES" ("SC_TYPE") ENABLE;
  ALTER TABLE "SPIREMGR"."STRUCTURED_CODES" ADD CONSTRAINT "STRUCTURED_CODES_FK2" FOREIGN KEY ("PARENT_SC_ID", "SC_TYPE")
	  REFERENCES "SPIREMGR"."STRUCTURED_CODES" ("ID", "SC_TYPE") ENABLE;
