--------------------------------------------------------
--  Ref Constraints for Table STRUCTURED_CODE_DETAILS
--------------------------------------------------------

  ALTER TABLE "SPIREMGR"."STRUCTURED_CODE_DETAILS" ADD CONSTRAINT "STRUCTURED_CODE_DETAILS_FK1" FOREIGN KEY ("CODE_VALUE", "SC_TYPE", "SC_ID")
	  REFERENCES "SPIREMGR"."STRUCTURED_CODES" ("CODE_VALUE", "SC_TYPE", "ID") ENABLE;
  ALTER TABLE "SPIREMGR"."STRUCTURED_CODE_DETAILS" ADD CONSTRAINT "STRUCTURED_CODE_DETAILS_FK2" FOREIGN KEY ("SCR_ID", "SCR_STATUS")
	  REFERENCES "SPIREMGR"."STRUCTURED_CODE_REVISIONS" ("ID", "STATUS") DEFERRABLE INITIALLY DEFERRED ENABLE;
