--------------------------------------------------------
--  Ref Constraints for Table STRUCTURED_CODE_TYPE_CONTROLS
--------------------------------------------------------

  ALTER TABLE "SPIREMGR"."STRUCTURED_CODE_TYPE_CONTROLS" ADD CONSTRAINT "STRUCTURED_CODE_TYPE_CTRLS_FK1" FOREIGN KEY ("SC_TYPE")
	  REFERENCES "SPIREMGR"."STRUCTURED_CODE_TYPES" ("SC_TYPE") ENABLE;
  ALTER TABLE "SPIREMGR"."STRUCTURED_CODE_TYPE_CONTROLS" ADD CONSTRAINT "STRUCTURED_CODE_TYPE_CTRLS_FK2" FOREIGN KEY ("REFERENCED_SC_TYPE")
	  REFERENCES "SPIREMGR"."STRUCTURED_CODE_TYPES" ("SC_TYPE") ENABLE;
