--------------------------------------------------------
--  Ref Constraints for Table SURVEY_INSTANCES
--------------------------------------------------------

  ALTER TABLE "SURVEYMGR"."SURVEY_INSTANCES" ADD CONSTRAINT "SURVEY_INSTANCES_FK" FOREIGN KEY ("ST_ID")
	  REFERENCES "SURVEYMGR"."SURVEY_TYPES" ("ID") ENABLE;
  ALTER TABLE "SURVEYMGR"."SURVEY_INSTANCES" ADD CONSTRAINT "SURVEY_INSTANCES_FK2" FOREIGN KEY ("AD_HOC_CREATED_WUA_ID")
	  REFERENCES "SECUREMGR"."WEB_USER_ACCOUNT_MASTER" ("WUA_ID") ENABLE;
  ALTER TABLE "SURVEYMGR"."SURVEY_INSTANCES" ADD CONSTRAINT "SURVEY_INSTANCES_FK3" FOREIGN KEY ("WUA_ID")
	  REFERENCES "SECUREMGR"."WEB_USER_ACCOUNT_MASTER" ("WUA_ID") ENABLE;
  ALTER TABLE "SURVEYMGR"."SURVEY_INSTANCES" ADD CONSTRAINT "SURVEY_INSTANCES_UREFS_FK" FOREIGN KEY ("ID")
	  REFERENCES "BPMMGR"."UREFS" ("SURVEY_INSTANCES_ID") DEFERRABLE INITIALLY DEFERRED ENABLE;
