--------------------------------------------------------
--  Ref Constraints for Table TEMPLATE_CLAUSE_SETS
--------------------------------------------------------

  ALTER TABLE "BPMMGR"."TEMPLATE_CLAUSE_SETS" ADD CONSTRAINT "TEMPLATE_CLAUSE_SETS_FK1" FOREIGN KEY ("CLAUSE_TYPE_ID")
	  REFERENCES "BPMMGR"."CLAUSE_TYPES" ("CLAUSE_TYPE_ID") ENABLE;
  ALTER TABLE "BPMMGR"."TEMPLATE_CLAUSE_SETS" ADD CONSTRAINT "TEMPLATE_CLAUSE_SETS_UREFS_FK" FOREIGN KEY ("ID")
	  REFERENCES "BPMMGR"."UREFS" ("TEMPLATE_CLAUSE_SETS_ID") DEFERRABLE INITIALLY DEFERRED ENABLE;
