--------------------------------------------------------
--  Ref Constraints for Table TFA_REGISTERED_DEVICE_DETAILS
--------------------------------------------------------

  ALTER TABLE "SECUREMGR"."TFA_REGISTERED_DEVICE_DETAILS" ADD CONSTRAINT "TFA_REG_DEVICE_DETAILS_FK1" FOREIGN KEY ("WUA_ID")
	  REFERENCES "SECUREMGR"."WEB_USER_ACCOUNT_MASTER" ("WUA_ID") ENABLE;
  ALTER TABLE "SECUREMGR"."TFA_REGISTERED_DEVICE_DETAILS" ADD CONSTRAINT "TFA_REG_DEVICE_DETAILS_FK2" FOREIGN KEY ("DEVICE_TYPE")
	  REFERENCES "SECUREMGR"."TFA_DEVICE_TYPES" ("DEVICE_TYPE") ENABLE;
  ALTER TABLE "SECUREMGR"."TFA_REGISTERED_DEVICE_DETAILS" ADD CONSTRAINT "TFA_REG_DEVICE_DETAILS_FK3" FOREIGN KEY ("TRD_ID")
	  REFERENCES "SECUREMGR"."TFA_REGISTERED_DEVICES" ("ID") ENABLE;
