--------------------------------------------------------
--  Ref Constraints for Table THIRD_PARTIES
--------------------------------------------------------

  ALTER TABLE "SDBMGR"."THIRD_PARTIES" ADD CONSTRAINT "THIRD_PARTIES_FK1" FOREIGN KEY ("ELA_GRP_ID")
	  REFERENCES "SDBMGR"."APPLICATIONS" ("ELA_GRP_ID") ENABLE;
  ALTER TABLE "SDBMGR"."THIRD_PARTIES" ADD CONSTRAINT "THIRD_PARTIES_FK2" FOREIGN KEY ("COUNTRY_ID")
	  REFERENCES "BPMMGR"."COUNTRIES" ("ID") ENABLE;
  ALTER TABLE "SDBMGR"."THIRD_PARTIES" ADD CONSTRAINT "THIRD_PARTIES_FK3" FOREIGN KEY ("BATCH_ID")
	  REFERENCES "SDBMGR"."BATCHES" ("ID") ENABLE;
