--------------------------------------------------------
--  Ref Constraints for Table TRANSMISSION_CONTENT
--------------------------------------------------------

  ALTER TABLE "PORTALMGR"."TRANSMISSION_CONTENT" ADD CONSTRAINT "TRANSMISSION_CONTENT_FK" FOREIGN KEY ("MAIL_ID")
	  REFERENCES "PORTALMGR"."TRANSMISSION_SET" ("MAIL_ID") ENABLE;
  ALTER TABLE "PORTALMGR"."TRANSMISSION_CONTENT" ADD CONSTRAINT "TRANSMISSION_CONTENT_FK2" FOREIGN KEY ("DI_ID")
	  REFERENCES "DECMGR"."DOCUMENT_INSTANCES" ("ID") ENABLE;
