--------------------------------------------------------
--  Ref Constraints for Table ULTIMATE_END_USERS
--------------------------------------------------------

  ALTER TABLE "SDBPUBMGR"."ULTIMATE_END_USERS" ADD CONSTRAINT "ULTIMATE_END_USERS_FK1" FOREIGN KEY ("ELA_GRP_ID")
	  REFERENCES "SDBPUBMGR"."APPLICATIONS" ("ELA_GRP_ID") ENABLE;
  ALTER TABLE "SDBPUBMGR"."ULTIMATE_END_USERS" ADD CONSTRAINT "ULTIMATE_END_USERS_FK3" FOREIGN KEY ("BATCH_ID")
	  REFERENCES "SDBPUBMGR"."BATCHES" ("ID") ENABLE;
