--------------------------------------------------------
--  Ref Constraints for Table ULTIMATE_END_USERS
--------------------------------------------------------

  ALTER TABLE "SDBMGR"."ULTIMATE_END_USERS" ADD CONSTRAINT "ULTIMATE_END_USERS_FK1" FOREIGN KEY ("ELA_GRP_ID")
	  REFERENCES "SDBMGR"."APPLICATIONS" ("ELA_GRP_ID") ENABLE;
  ALTER TABLE "SDBMGR"."ULTIMATE_END_USERS" ADD CONSTRAINT "ULTIMATE_END_USERS_FK2" FOREIGN KEY ("COUNTRY_ID")
	  REFERENCES "BPMMGR"."COUNTRIES" ("ID") ENABLE;
  ALTER TABLE "SDBMGR"."ULTIMATE_END_USERS" ADD CONSTRAINT "ULTIMATE_END_USERS_FK3" FOREIGN KEY ("BATCH_ID")
	  REFERENCES "SDBMGR"."BATCHES" ("ID") ENABLE;
