--------------------------------------------------------
--  Ref Constraints for Table UREFS
--------------------------------------------------------

  ALTER TABLE "BPMMGR"."UREFS" ADD CONSTRAINT "UREFS_ADVICE_ADVISORY_BODI_FK" FOREIGN KEY ("ADVICE_ADVISORY_BODIES")
	  REFERENCES "BPMMGR"."ADVICE_ADVISORY_BODIES" ("ID") ON DELETE CASCADE DEFERRABLE INITIALLY DEFERRED ENABLE;
  ALTER TABLE "BPMMGR"."UREFS" ADD CONSTRAINT "UREFS_ADVICE_ADVISORY_COMM_FK" FOREIGN KEY ("ADVICE_ADVISORY_COMMUNITY_ID")
	  REFERENCES "BPMMGR"."ADVICE_ADVISORY_COMMUNITIES" ("ID") ON DELETE CASCADE DEFERRABLE INITIALLY DEFERRED ENABLE;
  ALTER TABLE "BPMMGR"."UREFS" ADD CONSTRAINT "UREFS_ADVISORY_BODY_FK" FOREIGN KEY ("ADVISORY_BODY_ID")
	  REFERENCES "BPMMGR"."ADVISORY_BODIES" ("ID") ON DELETE CASCADE DEFERRABLE INITIALLY DEFERRED ENABLE;
  ALTER TABLE "BPMMGR"."UREFS" ADD CONSTRAINT "UREFS_ADVISORY_COMMUNITY_FK" FOREIGN KEY ("ADVISORY_COMMUNITY_ID")
	  REFERENCES "BPMMGR"."ADVISORY_COMMUNITIES" ("ID") ON DELETE CASCADE DEFERRABLE INITIALLY DEFERRED ENABLE;
  ALTER TABLE "BPMMGR"."UREFS" ADD CONSTRAINT "UREFS_APPLICATION_ERRORS_FK" FOREIGN KEY ("APP_ERROR_ID")
	  REFERENCES "FOXMGR"."APP_ERRORS" ("ID") ON DELETE CASCADE DEFERRABLE INITIALLY DEFERRED ENABLE;
  ALTER TABLE "BPMMGR"."UREFS" ADD CONSTRAINT "UREFS_BUSINESS_STAGES_FK" FOREIGN KEY ("BUSINESS_STAGES_ID")
	  REFERENCES "BPMMGR"."BUSINESS_STAGES" ("ID") ON DELETE CASCADE DEFERRABLE INITIALLY DEFERRED ENABLE;
  ALTER TABLE "BPMMGR"."UREFS" ADD CONSTRAINT "UREFS_BUSINESS_UNAVAIL_FK" FOREIGN KEY ("BUSINESS_UNAVAIL_ID")
	  REFERENCES "BPMMGR"."BUSINESS_UNAVAILABLE" ("ID") ON DELETE CASCADE DEFERRABLE INITIALLY DEFERRED ENABLE;
  ALTER TABLE "BPMMGR"."UREFS" ADD CONSTRAINT "UREFS_BUS_ACTIVITIES_FK" FOREIGN KEY ("BUSINESS_ACTIVITY_ID")
	  REFERENCES "BPMMGR"."BUSINESS_ACTIVITIES" ("ID") ON DELETE CASCADE DEFERRABLE INITIALLY DEFERRED ENABLE;
  ALTER TABLE "BPMMGR"."UREFS" ADD CONSTRAINT "UREFS_CLAUSE_TYPES_FK" FOREIGN KEY ("CLAUSE_TYPE_ID")
	  REFERENCES "BPMMGR"."CLAUSE_TYPES" ("CLAUSE_TYPE_ID") ON DELETE CASCADE DEFERRABLE INITIALLY DEFERRED ENABLE;
  ALTER TABLE "BPMMGR"."UREFS" ADD CONSTRAINT "UREFS_COMPLIANCE_ACTS_FK" FOREIGN KEY ("CA_ID")
	  REFERENCES "SPIREMGR"."COMPLIANCE_ACTIVITIES" ("ID") ON DELETE CASCADE DEFERRABLE INITIALLY DEFERRED ENABLE;
  ALTER TABLE "BPMMGR"."UREFS" ADD CONSTRAINT "UREFS_COMPLIANCE_VISITS_FK" FOREIGN KEY ("VISIT_ID")
	  REFERENCES "SPIREMGR"."COMPLIANCE_VISITS" ("ID") ON DELETE CASCADE DEFERRABLE INITIALLY DEFERRED ENABLE;
  ALTER TABLE "BPMMGR"."UREFS" ADD CONSTRAINT "UREFS_COUNTRIES_FK" FOREIGN KEY ("COUNTRY_ID")
	  REFERENCES "BPMMGR"."COUNTRIES" ("ID") ON DELETE CASCADE DEFERRABLE INITIALLY DEFERRED ENABLE;
  ALTER TABLE "BPMMGR"."UREFS" ADD CONSTRAINT "UREFS_COUNTRY_GROUPS_FK" FOREIGN KEY ("COUNTRY_GROUP_ID", "COUNTRY_GROUP_SET_ID")
	  REFERENCES "BPMMGR"."COUNTRY_GROUPS" ("COUNTRY_GROUP_ID", "COUNTRY_SET_ID") ON DELETE CASCADE DEFERRABLE INITIALLY DEFERRED ENABLE;
  ALTER TABLE "BPMMGR"."UREFS" ADD CONSTRAINT "UREFS_COUNTRY_SETS_FK" FOREIGN KEY ("COUNTRY_SET_ID")
	  REFERENCES "BPMMGR"."COUNTRY_SETS" ("COUNTRY_SET_ID") ON DELETE CASCADE DEFERRABLE INITIALLY DEFERRED ENABLE;
  ALTER TABLE "BPMMGR"."UREFS" ADD CONSTRAINT "UREFS_DENIALS_FK" FOREIGN KEY ("DENIAL_ID")
	  REFERENCES "SPIREMGR"."DENIALS" ("ID") ON DELETE CASCADE DEFERRABLE INITIALLY DEFERRED ENABLE;
  ALTER TABLE "BPMMGR"."UREFS" ADD CONSTRAINT "UREFS_DOCUMENT_SETS_FK" FOREIGN KEY ("DOCUMENT_SETS_ID")
	  REFERENCES "DECMGR"."DOCUMENT_SETS" ("ID") ON DELETE CASCADE DEFERRABLE INITIALLY DEFERRED ENABLE;
  ALTER TABLE "BPMMGR"."UREFS" ADD CONSTRAINT "UREFS_ELA_GROUPS_FK" FOREIGN KEY ("ELA_GROUP_ID")
	  REFERENCES "SPIREMGR"."ELA_GROUPS" ("ID") ON DELETE CASCADE DEFERRABLE INITIALLY DEFERRED ENABLE;
  ALTER TABLE "BPMMGR"."UREFS" ADD CONSTRAINT "UREFS_ELA_TEMPLATES_FK" FOREIGN KEY ("ELA_TEMPLATES_ID")
	  REFERENCES "SPIREMGR"."ELA_TEMPLATES" ("ID") ON DELETE CASCADE DEFERRABLE INITIALLY DEFERRED ENABLE;
  ALTER TABLE "BPMMGR"."UREFS" ADD CONSTRAINT "UREFS_EXPORT_LICENCES_FK" FOREIGN KEY ("EXPORT_LICENCE_ID")
	  REFERENCES "SPIREMGR"."EXPORT_LICENCES" ("ID") ON DELETE CASCADE DEFERRABLE INITIALLY DEFERRED ENABLE;
  ALTER TABLE "BPMMGR"."UREFS" ADD CONSTRAINT "UREFS_EXPORT_LICENCE_APPS_FK" FOREIGN KEY ("ELA_ID")
	  REFERENCES "SPIREMGR"."EXPORT_LICENCE_APPS" ("ID") ON DELETE CASCADE DEFERRABLE INITIALLY DEFERRED ENABLE;
  ALTER TABLE "BPMMGR"."UREFS" ADD CONSTRAINT "UREFS_EXP_LICENCE_DETAILS_FK" FOREIGN KEY ("ELD_ID")
	  REFERENCES "SPIREMGR"."EXPORT_LICENCE_DETAILS" ("ID") ON DELETE CASCADE DEFERRABLE INITIALLY DEFERRED ENABLE;
  ALTER TABLE "BPMMGR"."UREFS" ADD CONSTRAINT "UREFS_FILE_FOLDERS_FK" FOREIGN KEY ("FILE_FOLDER_ID")
	  REFERENCES "DECMGR"."FILE_FOLDERS" ("ID") ON DELETE CASCADE DEFERRABLE INITIALLY DEFERRED ENABLE;
  ALTER TABLE "BPMMGR"."UREFS" ADD CONSTRAINT "UREFS_FILE_FOLDER_TARGETS_FK" FOREIGN KEY ("FILE_FOLDER_TARGET_ID")
	  REFERENCES "DECMGR"."FILE_FOLDER_TARGETS" ("ID") ON DELETE CASCADE DEFERRABLE INITIALLY DEFERRED ENABLE;
  ALTER TABLE "BPMMGR"."UREFS" ADD CONSTRAINT "UREFS_FOX_SERVICES_FK" FOREIGN KEY ("FOX_SERVICE_ID")
	  REFERENCES "BPMMGR"."FOX_SERVICES" ("ID") ON DELETE CASCADE DEFERRABLE INITIALLY DEFERRED ENABLE;
  ALTER TABLE "BPMMGR"."UREFS" ADD CONSTRAINT "UREFS_INTENTION_FK" FOREIGN KEY ("INTENTION_ID")
	  REFERENCES "BPMMGR"."INTENTIONS" ("ID") ON DELETE CASCADE DEFERRABLE INITIALLY DEFERRED ENABLE;
  ALTER TABLE "BPMMGR"."UREFS" ADD CONSTRAINT "UREFS_MAPSETS_FK" FOREIGN KEY ("MAPSETS_ID")
	  REFERENCES "ENVMGR"."MAPSETS" ("ID") ON DELETE CASCADE DEFERRABLE INITIALLY DEFERRED ENABLE;
  ALTER TABLE "BPMMGR"."UREFS" ADD CONSTRAINT "UREFS_MISC_DOMAINS_FK" FOREIGN KEY ("MISC_DOMAIN_ID")
	  REFERENCES "BPMMGR"."MISC_DOMAINS" ("ID") ON DELETE CASCADE DEFERRABLE INITIALLY DEFERRED ENABLE;
  ALTER TABLE "BPMMGR"."UREFS" ADD CONSTRAINT "UREFS_NOTES_FK" FOREIGN KEY ("NOTES_ID")
	  REFERENCES "DECMGR"."NOTES" ("ID") ON DELETE CASCADE DEFERRABLE INITIALLY DEFERRED ENABLE;
  ALTER TABLE "BPMMGR"."UREFS" ADD CONSTRAINT "UREFS_NOTE_UREFS_FK" FOREIGN KEY ("NOTE_UREFS_ID")
	  REFERENCES "DECMGR"."NOTE_UREFS" ("ID") ON DELETE CASCADE DEFERRABLE INITIALLY DEFERRED ENABLE;
  ALTER TABLE "BPMMGR"."UREFS" ADD CONSTRAINT "UREFS_NOTIFICATIONS_FK" FOREIGN KEY ("NOTIFICATIONS_ID")
	  REFERENCES "DECMGR"."NOTIFICATIONS" ("ID") ON DELETE CASCADE DEFERRABLE INITIALLY DEFERRED ENABLE;
  ALTER TABLE "BPMMGR"."UREFS" ADD CONSTRAINT "UREFS_NOTIFICATION_SETS_FK" FOREIGN KEY ("NOTIFICATION_SET_ID")
	  REFERENCES "DECMGR"."NOTIFICATION_SETS" ("ID") ON DELETE CASCADE DEFERRABLE INITIALLY DEFERRED ENABLE;
  ALTER TABLE "BPMMGR"."UREFS" ADD CONSTRAINT "UREFS_NOVATIONS_FK" FOREIGN KEY ("N_ID")
	  REFERENCES "PVEXMGR"."NOVATIONS" ("ID") ON DELETE CASCADE DEFERRABLE INITIALLY DEFERRED ENABLE;
  ALTER TABLE "BPMMGR"."UREFS" ADD CONSTRAINT "UREFS_ORG_UNITS_FK" FOREIGN KEY ("ORGANISATION_UNITS_ID")
	  REFERENCES "DECMGR"."ORGANISATION_UNIT_MASTER" ("ORGAN_ID") ON DELETE CASCADE DEFERRABLE INITIALLY DEFERRED ENABLE;
  ALTER TABLE "BPMMGR"."UREFS" ADD CONSTRAINT "UREFS_PORTAL_FOLDERS_FK" FOREIGN KEY ("PORTAL_FOLDERS_ID")
	  REFERENCES "DECMGR"."PORTAL_FOLDERS" ("ID") ON DELETE CASCADE DEFERRABLE INITIALLY DEFERRED ENABLE;
  ALTER TABLE "BPMMGR"."UREFS" ADD CONSTRAINT "UREFS_PORTAL_FOLDER_TYPES_FK" FOREIGN KEY ("PORTAL_FOLDER_TYPE")
	  REFERENCES "DECMGR"."PORTAL_FOLDER_TYPES" ("PORTAL_FOLDER_TYPE") ON DELETE CASCADE DEFERRABLE INITIALLY DEFERRED ENABLE;
  ALTER TABLE "BPMMGR"."UREFS" ADD CONSTRAINT "UREFS_PS_EVENTS_FK" FOREIGN KEY ("PORTAL_SCHEDULE_EVENT_ID")
	  REFERENCES "DECMGR"."PORTAL_SCHEDULE_EVENTS" ("ID") ON DELETE CASCADE DEFERRABLE INITIALLY DEFERRED ENABLE;
  ALTER TABLE "BPMMGR"."UREFS" ADD CONSTRAINT "UREFS_PS_INSTANCES_FK" FOREIGN KEY ("PORTAL_SCHEDULE_INSTANCE_ID")
	  REFERENCES "DECMGR"."PORTAL_SCHEDULE_INSTANCES" ("ID") ON DELETE CASCADE DEFERRABLE INITIALLY DEFERRED ENABLE;
  ALTER TABLE "BPMMGR"."UREFS" ADD CONSTRAINT "UREFS_PS_TYPES_FK" FOREIGN KEY ("PORTAL_SCHEDULE_TYPE_MNEM")
	  REFERENCES "DECMGR"."PORTAL_SCHEDULE_TYPES" ("PORTAL_SCHEDULE_TYPE") ON DELETE CASCADE DEFERRABLE INITIALLY DEFERRED ENABLE;
  ALTER TABLE "BPMMGR"."UREFS" ADD CONSTRAINT "UREFS_PV_EX_APPLICATIONS_FK" FOREIGN KEY ("PEA_ID")
	  REFERENCES "PVEXMGR"."PV_EX_APPLICATIONS" ("ID") ON DELETE CASCADE DEFERRABLE INITIALLY DEFERRED ENABLE;
  ALTER TABLE "BPMMGR"."UREFS" ADD CONSTRAINT "UREFS_REPORT_CATEGORIES_FK" FOREIGN KEY ("REPORT_CAT_MNEM")
	  REFERENCES "REPORTMGR"."REPORT_CATEGORIES" ("MNEM") ON DELETE CASCADE DEFERRABLE INITIALLY DEFERRED ENABLE;
  ALTER TABLE "BPMMGR"."UREFS" ADD CONSTRAINT "UREFS_REPORT_DEFINITIONS_FK" FOREIGN KEY ("REPORT_DEF_ID")
	  REFERENCES "REPORTMGR"."REPORT_DEFINITIONS" ("DOMAIN") ON DELETE CASCADE DEFERRABLE INITIALLY DEFERRED ENABLE;
  ALTER TABLE "BPMMGR"."UREFS" ADD CONSTRAINT "UREFS_REPORT_RUNS_FK" FOREIGN KEY ("RPT_RUN_ID")
	  REFERENCES "REPORTMGR"."REPORT_RUNS" ("ID") ON DELETE CASCADE DEFERRABLE INITIALLY DEFERRED ENABLE;
  ALTER TABLE "BPMMGR"."UREFS" ADD CONSTRAINT "UREFS_RESOURCES_FK" FOREIGN KEY ("RESOURCES_ID")
	  REFERENCES "DECMGR"."RESOURCES" ("ID") ON DELETE CASCADE DEFERRABLE INITIALLY DEFERRED ENABLE;
  ALTER TABLE "BPMMGR"."UREFS" ADD CONSTRAINT "UREFS_RESOURCE_PEOPLE_FK" FOREIGN KEY ("RESOURCE_PEOPLE_ID")
	  REFERENCES "DECMGR"."RESOURCE_PEOPLE" ("ID") ON DELETE CASCADE DEFERRABLE INITIALLY DEFERRED ENABLE;
  ALTER TABLE "BPMMGR"."UREFS" ADD CONSTRAINT "UREFS_RES_ROLES_FK" FOREIGN KEY ("RESOURCE_ROLES_ID")
	  REFERENCES "DECMGR"."RESOURCE_ROLES" ("ID") ON DELETE CASCADE DEFERRABLE INITIALLY DEFERRED ENABLE;
  ALTER TABLE "BPMMGR"."UREFS" ADD CONSTRAINT "UREFS_REVIEW_ADVISOR_FK" FOREIGN KEY ("REVIEW_ADVISOR_ID")
	  REFERENCES "BPMMGR"."REVIEW_ADVISORS" ("ID") ON DELETE CASCADE DEFERRABLE INITIALLY DEFERRED ENABLE;
  ALTER TABLE "BPMMGR"."UREFS" ADD CONSTRAINT "UREFS_REVIEW_BATCH_FK" FOREIGN KEY ("REVIEW_BATCH_ID")
	  REFERENCES "BPMMGR"."REVIEW_BATCHES" ("ID") ON DELETE CASCADE DEFERRABLE INITIALLY DEFERRED ENABLE;
  ALTER TABLE "BPMMGR"."UREFS" ADD CONSTRAINT "UREFS_SCAN_PREF_TEMPS_FK" FOREIGN KEY ("SCAN_PREFERENCE_TEMPLATES_ID")
	  REFERENCES "DECMGR"."SCAN_PREFERENCE_TEMPLATES" ("ID") ON DELETE CASCADE DEFERRABLE INITIALLY DEFERRED ENABLE;
  ALTER TABLE "BPMMGR"."UREFS" ADD CONSTRAINT "UREFS_SITES_FK" FOREIGN KEY ("SITE_ID")
	  REFERENCES "SPIREMGR"."SITES" ("ID") ON DELETE CASCADE DEFERRABLE INITIALLY DEFERRED ENABLE;
  ALTER TABLE "BPMMGR"."UREFS" ADD CONSTRAINT "UREFS_SPIRE_APPLICANTS_FK" FOREIGN KEY ("SPIRE_AP_REC_ID")
	  REFERENCES "SPIREMGR"."SPIRE_APPLICANTS" ("ID") ON DELETE CASCADE DEFERRABLE INITIALLY DEFERRED ENABLE;
  ALTER TABLE "BPMMGR"."UREFS" ADD CONSTRAINT "UREFS_SPIRE_APPLICATIONS_FK" FOREIGN KEY ("SPIRE_APP_ID")
	  REFERENCES "SPIREMGR"."SPIRE_APPLICATIONS" ("ID") ON DELETE CASCADE DEFERRABLE INITIALLY DEFERRED ENABLE;
  ALTER TABLE "BPMMGR"."UREFS" ADD CONSTRAINT "UREFS_SPIRE_APP_DETAIL_FK" FOREIGN KEY ("SPIRE_AP_DTL_ID")
	  REFERENCES "SPIREMGR"."SPIRE_APPLICANT_DETAILS" ("ID") ON DELETE CASCADE DEFERRABLE INITIALLY DEFERRED ENABLE;
  ALTER TABLE "BPMMGR"."UREFS" ADD CONSTRAINT "UREFS_SURVEY_INSTANCES_FK" FOREIGN KEY ("SURVEY_INSTANCES_ID")
	  REFERENCES "SURVEYMGR"."SURVEY_INSTANCES" ("ID") ON DELETE CASCADE DEFERRABLE INITIALLY DEFERRED ENABLE;
  ALTER TABLE "BPMMGR"."UREFS" ADD CONSTRAINT "UREFS_SURVEY_TYPES_FK" FOREIGN KEY ("SURVEY_TYPES_ID")
	  REFERENCES "SURVEYMGR"."SURVEY_TYPES" ("ID") ON DELETE CASCADE DEFERRABLE INITIALLY DEFERRED ENABLE;
  ALTER TABLE "BPMMGR"."UREFS" ADD CONSTRAINT "UREFS_SYSTEM_DOMAINS_FK" FOREIGN KEY ("SYSTEM_DOMAIN_ID")
	  REFERENCES "FOXMGR"."SYSTEM_DOMAINS" ("ID") ON DELETE CASCADE DEFERRABLE INITIALLY DEFERRED ENABLE;
  ALTER TABLE "BPMMGR"."UREFS" ADD CONSTRAINT "UREFS_TEMPLATE_CLAUSES_FK" FOREIGN KEY ("TEMPLATE_CLAUSE_ID")
	  REFERENCES "BPMMGR"."TEMPLATE_CLAUSES" ("ID") ON DELETE CASCADE DEFERRABLE INITIALLY DEFERRED ENABLE;
  ALTER TABLE "BPMMGR"."UREFS" ADD CONSTRAINT "UREFS_TEMPLATE_CLAUSE_SETS_FK" FOREIGN KEY ("TEMPLATE_CLAUSE_SETS_ID")
	  REFERENCES "BPMMGR"."TEMPLATE_CLAUSE_SETS" ("ID") ON DELETE CASCADE DEFERRABLE INITIALLY DEFERRED ENABLE;
  ALTER TABLE "BPMMGR"."UREFS" ADD CONSTRAINT "UREFS_WEB_ORGANISATIONS_FK" FOREIGN KEY ("WEB_ORGANISATION_ID")
	  REFERENCES "PORTALMGR"."WEB_ORGANISATIONS" ("ID") ON DELETE CASCADE DEFERRABLE INITIALLY DEFERRED ENABLE;
  ALTER TABLE "BPMMGR"."UREFS" ADD CONSTRAINT "UREFS_WEB_ROLES_FK" FOREIGN KEY ("PORTAL_PRIVILEGES_ID")
	  REFERENCES "PORTALMGR"."WEB_ROLES" ("ID") ON DELETE CASCADE DEFERRABLE INITIALLY DEFERRED ENABLE;
  ALTER TABLE "BPMMGR"."UREFS" ADD CONSTRAINT "UREFS_WEB_USER_ACCOUNTS_FK" FOREIGN KEY ("WEB_USER_ACCOUNT_ID")
	  REFERENCES "SECUREMGR"."WEB_USER_ACCOUNT_MASTER" ("WUA_ID") ON DELETE CASCADE DEFERRABLE INITIALLY DEFERRED ENABLE;
