--------------------------------------------------------
--  Ref Constraints for Table WEB_ROLES
--------------------------------------------------------

  ALTER TABLE "PORTALMGR"."WEB_ROLES" ADD CONSTRAINT "WBR_WA_FK" FOREIGN KEY ("APP_ID")
	  REFERENCES "PORTALMGR"."WEB_APPLICATIONS" ("ID") ENABLE;
  ALTER TABLE "PORTALMGR"."WEB_ROLES" ADD CONSTRAINT "WEB_ROLES_UREFS_FK" FOREIGN KEY ("ID")
	  REFERENCES "BPMMGR"."UREFS" ("PORTAL_PRIVILEGES_ID") DEFERRABLE INITIALLY DEFERRED ENABLE;
