--------------------------------------------------------
--  Ref Constraints for Table WEB_ORG_PARAMETER_VALUES
--------------------------------------------------------

  ALTER TABLE "PORTALMGR"."WEB_ORG_PARAMETER_VALUES" ADD CONSTRAINT "WO_PARAM_VALAUES_FK2" FOREIGN KEY ("WO_ID")
	  REFERENCES "PORTALMGR"."WEB_ORGANISATIONS" ("ID") ENABLE;
  ALTER TABLE "PORTALMGR"."WEB_ORG_PARAMETER_VALUES" ADD CONSTRAINT "WO_PARAM_VALUES_FK1" FOREIGN KEY ("WO_PARAM_ID")
	  REFERENCES "PORTALMGR"."WEB_ORG_PARAMETERS" ("ID") ENABLE;
