--------------------------------------------------------
--  Ref Constraints for Table WEB_ORGANISATIONS
--------------------------------------------------------

  ALTER TABLE "PORTALMGR"."WEB_ORGANISATIONS" ADD CONSTRAINT "WEB_ORGANISATIONS_UREFS_FK" FOREIGN KEY ("ID")
	  REFERENCES "BPMMGR"."UREFS" ("WEB_ORGANISATION_ID") DEFERRABLE INITIALLY DEFERRED ENABLE;
  ALTER TABLE "PORTALMGR"."WEB_ORGANISATIONS" ADD CONSTRAINT "WO_WOT_FK" FOREIGN KEY ("WOT_ID")
	  REFERENCES "PORTALMGR"."WEB_ORG_TYPES" ("ID") ENABLE;
