--------------------------------------------------------
--  Ref Constraints for Table WORKBASKET_ACTIONS
--------------------------------------------------------

  ALTER TABLE "BPMMGR"."WORKBASKET_ACTIONS" ADD CONSTRAINT "WORKBASKET_ACTIONS_FK1" FOREIGN KEY ("START_OPERATION_ID")
	  REFERENCES "BPMMGR"."CHANGE_OPERATIONS" ("ID") ENABLE;
  ALTER TABLE "BPMMGR"."WORKBASKET_ACTIONS" ADD CONSTRAINT "WORKBASKET_ACTIONS_FK2" FOREIGN KEY ("END_OPERATION_ID")
	  REFERENCES "BPMMGR"."CHANGE_OPERATIONS" ("ID") ENABLE;
  ALTER TABLE "BPMMGR"."WORKBASKET_ACTIONS" ADD CONSTRAINT "WORKBASKET_ACTIONS_FK4" FOREIGN KEY ("BA_ID")
	  REFERENCES "BPMMGR"."BUSINESS_ACTIVITIES" ("ID") ENABLE;
  ALTER TABLE "BPMMGR"."WORKBASKET_ACTIONS" ADD CONSTRAINT "WORKBASKET_ACTIONS_FK5" FOREIGN KEY ("BS_ID")
	  REFERENCES "BPMMGR"."BUSINESS_STAGES" ("ID") ENABLE;
