--------------------------------------------------------
--  Ref Constraints for Table WORKBASKET_UREF_PREFERENCES
--------------------------------------------------------

  ALTER TABLE "BPMMGR"."WORKBASKET_UREF_PREFERENCES" ADD CONSTRAINT "WORKBASKET_UREF_PREFS_FK1" FOREIGN KEY ("WUA_ID")
	  REFERENCES "SECUREMGR"."WEB_USER_ACCOUNT_MASTER" ("WUA_ID") ENABLE;
  ALTER TABLE "BPMMGR"."WORKBASKET_UREF_PREFERENCES" ADD CONSTRAINT "WORKBASKET_UREF_PREFS_FK2" FOREIGN KEY ("UREF")
	  REFERENCES "BPMMGR"."UREFS" ("UREF") ENABLE;
