--------------------------------------------------------
--  Ref Constraints for Table WORKBASKET_ENTRIES
--------------------------------------------------------

  ALTER TABLE "BPMMGR"."WORKBASKET_ENTRIES" ADD CONSTRAINT "WORKBASKET_ENTRIES_FK1" FOREIGN KEY ("WB_ID")
	  REFERENCES "BPMMGR"."WORKBASKETS" ("ID") ENABLE;
  ALTER TABLE "BPMMGR"."WORKBASKET_ENTRIES" ADD CONSTRAINT "WORKBASKET_ENTRIES_FK2" FOREIGN KEY ("WBA_ID")
	  REFERENCES "BPMMGR"."WORKBASKET_ACTIONS" ("ID") ENABLE;
