--------------------------------------------------------
--  Ref Constraints for Table WORKBASKET_ACTION_PREFERENCES
--------------------------------------------------------

  ALTER TABLE "BPMMGR"."WORKBASKET_ACTION_PREFERENCES" ADD CONSTRAINT "WORKBASKET_ACTION_PREF_FK1" FOREIGN KEY ("WBA_ID")
	  REFERENCES "BPMMGR"."WORKBASKET_ACTIONS" ("ID") ENABLE;
  ALTER TABLE "BPMMGR"."WORKBASKET_ACTION_PREFERENCES" ADD CONSTRAINT "WORKBASKET_ACTION_PREF_FK2" FOREIGN KEY ("WUA_ID")
	  REFERENCES "SECUREMGR"."WEB_USER_ACCOUNT_MASTER" ("WUA_ID") ENABLE;
