--------------------------------------------------------
--  Ref Constraints for Table XV_AUTH_REQ_PF_DATA
--------------------------------------------------------

  ALTER TABLE "XVIEWMGR"."XV_AUTH_REQ_PF_DATA" ADD CONSTRAINT "XV_AUTH_REQ_PF_FK1001" FOREIGN KEY ("PF_ID")
	  REFERENCES "DECMGR"."PORTAL_FOLDERS" ("ID") DEFERRABLE INITIALLY DEFERRED ENABLE;
  ALTER TABLE "XVIEWMGR"."XV_AUTH_REQ_PF_DATA" ADD CONSTRAINT "XV_AUTH_REQ_PF_FK999" FOREIGN KEY ("AR_ID")
	  REFERENCES "DECMGR"."AUTHORISATION_REQUESTS" ("ID") DEFERRABLE INITIALLY DEFERRED ENABLE;
