--------------------------------------------------------
--  Ref Constraints for Table XV_AUTH_REQ_DATA
--------------------------------------------------------

  ALTER TABLE "XVIEWMGR"."XV_AUTH_REQ_DATA" ADD CONSTRAINT "XV_AUTH_REQ_FK1001" FOREIGN KEY ("OBJECT_UREF")
	  REFERENCES "BPMMGR"."UREFS" ("UREF") DEFERRABLE INITIALLY DEFERRED ENABLE;
  ALTER TABLE "XVIEWMGR"."XV_AUTH_REQ_DATA" ADD CONSTRAINT "XV_AUTH_REQ_FK1002" FOREIGN KEY ("PFA_PRIMARY_DATA_UREF")
	  REFERENCES "BPMMGR"."UREFS" ("UREF") DEFERRABLE INITIALLY DEFERRED ENABLE;
  ALTER TABLE "XVIEWMGR"."XV_AUTH_REQ_DATA" ADD CONSTRAINT "XV_AUTH_REQ_FK1003" FOREIGN KEY ("EVENT_PRIMARY_DATA_UREF")
	  REFERENCES "BPMMGR"."UREFS" ("UREF") DEFERRABLE INITIALLY DEFERRED ENABLE;
  ALTER TABLE "XVIEWMGR"."XV_AUTH_REQ_DATA" ADD CONSTRAINT "XV_AUTH_REQ_FK999" FOREIGN KEY ("AR_ID")
	  REFERENCES "DECMGR"."AUTHORISATION_REQUESTS" ("ID") DEFERRABLE INITIALLY DEFERRED ENABLE;
