--------------------------------------------------------
--  Ref Constraints for Table XV_BUSINESS_ACT_DATA
--------------------------------------------------------

  ALTER TABLE "XVIEWMGR"."XV_BUSINESS_ACT_DATA" ADD CONSTRAINT "XV_BUSINESS_ACT_FK1001" FOREIGN KEY ("BA_ID")
	  REFERENCES "BPMMGR"."BUSINESS_ACTIVITIES" ("ID") DEFERRABLE INITIALLY DEFERRED ENABLE;
  ALTER TABLE "XVIEWMGR"."XV_BUSINESS_ACT_DATA" ADD CONSTRAINT "XV_BUSINESS_ACT_FK1002" FOREIGN KEY ("BT_ID")
	  REFERENCES "BPMMGR"."BUSINESS_TRANSACTIONS" ("ID") DEFERRABLE INITIALLY DEFERRED ENABLE;
