--------------------------------------------------------
--  Ref Constraints for Table XV_DN_LIC_APPS_DATA
--------------------------------------------------------

  ALTER TABLE "XVIEWMGR"."XV_DN_LIC_APPS_DATA" ADD CONSTRAINT "XV_DN_LIC_APPS_FK1001" FOREIGN KEY ("ELA_ID")
	  REFERENCES "SPIREMGR"."EXPORT_LICENCE_APPS" ("ID") DEFERRABLE INITIALLY DEFERRED ENABLE;
  ALTER TABLE "XVIEWMGR"."XV_DN_LIC_APPS_DATA" ADD CONSTRAINT "XV_DN_LIC_APPS_FK999" FOREIGN KEY ("DD_ID")
	  REFERENCES "SPIREMGR"."DENIAL_DETAILS" ("ID") DEFERRABLE INITIALLY DEFERRED ENABLE;
