--------------------------------------------------------
--  Ref Constraints for Table XV_DOC_PACK_RECIP_DATA
--------------------------------------------------------

  ALTER TABLE "XVIEWMGR"."XV_DOC_PACK_RECIP_DATA" ADD CONSTRAINT "XV_DOC_PACK_RECIP_FK1001" FOREIGN KEY ("DP_ID")
	  REFERENCES "DECMGR"."DOCUMENT_PACKS" ("ID") DEFERRABLE INITIALLY DEFERRED ENABLE;
  ALTER TABLE "XVIEWMGR"."XV_DOC_PACK_RECIP_DATA" ADD CONSTRAINT "XV_DOC_PACK_RECIP_FK1002" FOREIGN KEY ("PERSON_ID")
	  REFERENCES "DECMGR"."RESOURCE_PEOPLE" ("ID") DEFERRABLE INITIALLY DEFERRED ENABLE;
  ALTER TABLE "XVIEWMGR"."XV_DOC_PACK_RECIP_DATA" ADD CONSTRAINT "XV_DOC_PACK_RECIP_FK1003" FOREIGN KEY ("ADDRESS_ID")
	  REFERENCES "DECMGR"."RESOURCE_ADDRESS_FULL_HISTORY" ("ID") DEFERRABLE INITIALLY DEFERRED ENABLE;
