--------------------------------------------------------
--  Ref Constraints for Table XV_DOC_SET_REVIEWS_DATA
--------------------------------------------------------

  ALTER TABLE "XVIEWMGR"."XV_DOC_SET_REVIEWS_DATA" ADD CONSTRAINT "XV_DOC_SET_REVIEWS_FK998" FOREIGN KEY ("FILE_FOLDER_TYPE")
	  REFERENCES "DECMGR"."FILE_FOLDER_TYPES" ("FILE_FOLDER_TYPE") DEFERRABLE INITIALLY DEFERRED ENABLE;
  ALTER TABLE "XVIEWMGR"."XV_DOC_SET_REVIEWS_DATA" ADD CONSTRAINT "XV_DOC_SET_REVIEWS_FK999" FOREIGN KEY ("DS_ID")
	  REFERENCES "DECMGR"."DOCUMENT_SETS" ("ID") DEFERRABLE INITIALLY DEFERRED ENABLE;
