--------------------------------------------------------
--  Ref Constraints for Table XV_DOC_INST_SRC_DATA
--------------------------------------------------------

  ALTER TABLE "XVIEWMGR"."XV_DOC_INST_SRC_DATA" ADD CONSTRAINT "XV_DOC_INST_SRC_FK1001" FOREIGN KEY ("DI_ID")
	  REFERENCES "DECMGR"."DOCUMENT_INSTANCES" ("ID") DEFERRABLE INITIALLY DEFERRED ENABLE;
  ALTER TABLE "XVIEWMGR"."XV_DOC_INST_SRC_DATA" ADD CONSTRAINT "XV_DOC_INST_SRC_FK1002" FOREIGN KEY ("WUA_ID")
	  REFERENCES "SECUREMGR"."WEB_USER_ACCOUNT_MASTER" ("WUA_ID") DEFERRABLE INITIALLY DEFERRED ENABLE;
