--------------------------------------------------------
--  Ref Constraints for Table XV_DOC_PACKS_DATA
--------------------------------------------------------

  ALTER TABLE "XVIEWMGR"."XV_DOC_PACKS_DATA" ADD CONSTRAINT "XV_DOC_PACKS_FK1001" FOREIGN KEY ("DP_ID")
	  REFERENCES "DECMGR"."DOCUMENT_PACKS" ("ID") DEFERRABLE INITIALLY DEFERRED ENABLE;
  ALTER TABLE "XVIEWMGR"."XV_DOC_PACKS_DATA" ADD CONSTRAINT "XV_DOC_PACKS_FK1002" FOREIGN KEY ("DS_ID")
	  REFERENCES "DECMGR"."DOCUMENT_SETS" ("ID") DEFERRABLE INITIALLY DEFERRED ENABLE;
  ALTER TABLE "XVIEWMGR"."XV_DOC_PACKS_DATA" ADD CONSTRAINT "XV_DOC_PACKS_FK1003" FOREIGN KEY ("OU_ID")
	  REFERENCES "DECMGR"."ORGANISATION_UNIT_MASTER" ("ORGAN_ID") DEFERRABLE INITIALLY DEFERRED ENABLE;
  ALTER TABLE "XVIEWMGR"."XV_DOC_PACKS_DATA" ADD CONSTRAINT "XV_DOC_PACKS_FK1004" FOREIGN KEY ("PERSON_ID")
	  REFERENCES "DECMGR"."RESOURCE_PEOPLE" ("ID") DEFERRABLE INITIALLY DEFERRED ENABLE;
