--------------------------------------------------------
--  Ref Constraints for Table XV_DOC_INTS_DATA
--------------------------------------------------------

  ALTER TABLE "XVIEWMGR"."XV_DOC_INTS_DATA" ADD CONSTRAINT "XV_DOC_INTS_FK1001" FOREIGN KEY ("DI_ID")
	  REFERENCES "DECMGR"."DOCUMENT_INSTANCES" ("ID") DEFERRABLE INITIALLY DEFERRED ENABLE;
  ALTER TABLE "XVIEWMGR"."XV_DOC_INTS_DATA" ADD CONSTRAINT "XV_DOC_INTS_FK1002" FOREIGN KEY ("DP_ID")
	  REFERENCES "DECMGR"."DOCUMENT_PACKS" ("ID") DEFERRABLE INITIALLY DEFERRED ENABLE;
