--------------------------------------------------------
--  Ref Constraints for Table XV_ELA_DETAILS_DATA
--------------------------------------------------------

  ALTER TABLE "XVIEWMGR"."XV_ELA_DETAILS_DATA" ADD CONSTRAINT "XV_ELA_DETAILS_FK1100" FOREIGN KEY ("SAR_ID")
	  REFERENCES "SPIREMGR"."SPIRE_APPLICANTS" ("ID") ENABLE;
  ALTER TABLE "XVIEWMGR"."XV_ELA_DETAILS_DATA" ADD CONSTRAINT "XV_ELA_DETAILS_FK1150" FOREIGN KEY ("SITE_ID")
	  REFERENCES "SPIREMGR"."SITES" ("ID") ENABLE;
  ALTER TABLE "XVIEWMGR"."XV_ELA_DETAILS_DATA" ADD CONSTRAINT "XV_ELA_DETAILS_FK999" FOREIGN KEY ("ELA_DETAIL_ID")
	  REFERENCES "SPIREMGR"."EXPORT_LICENCE_APP_DETAILS" ("ID") DEFERRABLE INITIALLY DEFERRED ENABLE;
