--------------------------------------------------------
--  Ref Constraints for Table XV_FOLDER_TYPES_DATA
--------------------------------------------------------

  ALTER TABLE "XVIEWMGR"."XV_FOLDER_TYPES_DATA" ADD CONSTRAINT "XV_FOLDER_TYPES_FK1001" FOREIGN KEY ("SCAN_TYPE")
	  REFERENCES "DECMGR"."SCAN_TYPES" ("SCAN_TYPE") ENABLE;
  ALTER TABLE "XVIEWMGR"."XV_FOLDER_TYPES_DATA" ADD CONSTRAINT "XV_FOLDER_TYPES_FK999" FOREIGN KEY ("FILE_FOLDER_TYPE")
	  REFERENCES "DECMGR"."FILE_FOLDER_TYPES" ("FILE_FOLDER_TYPE") DEFERRABLE INITIALLY DEFERRED ENABLE;
