--------------------------------------------------------
--  Ref Constraints for Table XV_ORG_UNITS_DATA
--------------------------------------------------------

  ALTER TABLE "XVIEWMGR"."XV_ORG_UNITS_DATA" ADD CONSTRAINT "XV_ORG_UNITS_FK1001" FOREIGN KEY ("OD_ID")
	  REFERENCES "DECMGR"."ORGANISATION_UNIT_DETAILS" ("ID") DEFERRABLE INITIALLY DEFERRED ENABLE;
  ALTER TABLE "XVIEWMGR"."XV_ORG_UNITS_DATA" ADD CONSTRAINT "XV_ORG_UNITS_FK1002" FOREIGN KEY ("ORGAN_ID")
	  REFERENCES "DECMGR"."ORGANISATION_UNIT_MASTER" ("ORGAN_ID") ENABLE;
