--------------------------------------------------------
--  Ref Constraints for Table XV_PORTAL_FOLDERS_DATA
--------------------------------------------------------

  ALTER TABLE "XVIEWMGR"."XV_PORTAL_FOLDERS_DATA" ADD CONSTRAINT "XV_PORTAL_FOLDERS_FK1001" FOREIGN KEY ("PF_ID")
	  REFERENCES "DECMGR"."PORTAL_FOLDERS" ("ID") DEFERRABLE INITIALLY DEFERRED ENABLE;
  ALTER TABLE "XVIEWMGR"."XV_PORTAL_FOLDERS_DATA" ADD CONSTRAINT "XV_PORTAL_FOLDERS_FK1002" FOREIGN KEY ("PRIMARY_DATA_UREF")
	  REFERENCES "BPMMGR"."UREFS" ("UREF") DEFERRABLE INITIALLY DEFERRED ENABLE;
  ALTER TABLE "XVIEWMGR"."XV_PORTAL_FOLDERS_DATA" ADD CONSTRAINT "XV_PORTAL_FOLDERS_FK1003" FOREIGN KEY ("FOLDER_TYPE")
	  REFERENCES "DECMGR"."PORTAL_FOLDER_TYPES" ("PORTAL_FOLDER_TYPE") DEFERRABLE INITIALLY DEFERRED ENABLE;
