--------------------------------------------------------
--  Ref Constraints for Table XV_PF_MATRIX_USAGE_DATA
--------------------------------------------------------

  ALTER TABLE "XVIEWMGR"."XV_PF_MATRIX_USAGE_DATA" ADD CONSTRAINT "XV_PF_MATRIX_USAGE_FK1001" FOREIGN KEY ("PF_ID")
	  REFERENCES "DECMGR"."PORTAL_FOLDERS" ("ID") DEFERRABLE INITIALLY DEFERRED ENABLE;
  ALTER TABLE "XVIEWMGR"."XV_PF_MATRIX_USAGE_DATA" ADD CONSTRAINT "XV_PF_MATRIX_USAGE_FK1002" FOREIGN KEY ("MF_ID")
	  REFERENCES "DECMGR"."MATRIX_FOLDERS" ("ID") DEFERRABLE INITIALLY DEFERRED ENABLE;
