--------------------------------------------------------
--  Ref Constraints for Table XV_REVIEW_INV_DETS_DATA
--------------------------------------------------------

  ALTER TABLE "XVIEWMGR"."XV_REVIEW_INV_DETS_DATA" ADD CONSTRAINT "XV_REVIEW_INV_DETS_FK1001" FOREIGN KEY ("PORTAL_FOLDER_ID")
	  REFERENCES "DECMGR"."PORTAL_FOLDERS" ("ID") DEFERRABLE INITIALLY DEFERRED ENABLE;
  ALTER TABLE "XVIEWMGR"."XV_REVIEW_INV_DETS_DATA" ADD CONSTRAINT "XV_REVIEW_INV_DETS_FK999" FOREIGN KEY ("RID_ID")
	  REFERENCES "BPMMGR"."REVIEW_INVITATION_DETAILS" ("ID") DEFERRABLE INITIALLY DEFERRED ENABLE;
