--------------------------------------------------------
--  Ref Constraints for Table XV_REPORT_DEFS_DATA
--------------------------------------------------------

  ALTER TABLE "XVIEWMGR"."XV_REPORT_DEFS_DATA" ADD CONSTRAINT "XV_REPORT_DEFS_FK1001" FOREIGN KEY ("CATEGORY_MNEM")
	  REFERENCES "REPORTMGR"."REPORT_CATEGORIES" ("MNEM") ENABLE;
  ALTER TABLE "XVIEWMGR"."XV_REPORT_DEFS_DATA" ADD CONSTRAINT "XV_REPORT_DEFS_FK1002" FOREIGN KEY ("FILE_TRANSMISSION_TYPE_MNEM")
	  REFERENCES "PORTALMGR"."FILE_TRANSMISSION_TYPES" ("TYPE_MNEM") ENABLE;
  ALTER TABLE "XVIEWMGR"."XV_REPORT_DEFS_DATA" ADD CONSTRAINT "XV_REPORT_DEFS_FK999" FOREIGN KEY ("DOMAIN")
	  REFERENCES "REPORTMGR"."REPORT_DEFINITIONS" ("DOMAIN") DEFERRABLE INITIALLY DEFERRED ENABLE;
