--------------------------------------------------------
--  Ref Constraints for Table XV_RES_TYPE_EDIT_DATA
--------------------------------------------------------

  ALTER TABLE "XVIEWMGR"."XV_RES_TYPE_EDIT_DATA" ADD CONSTRAINT "XV_RES_TYPE_EDIT_FK1001" FOREIGN KEY ("RES_TYPE")
	  REFERENCES "DECMGR"."RESOURCE_TYPES" ("RES_TYPE") DEFERRABLE INITIALLY DEFERRED ENABLE;
  ALTER TABLE "XVIEWMGR"."XV_RES_TYPE_EDIT_DATA" ADD CONSTRAINT "XV_RES_TYPE_EDIT_FK1003" FOREIGN KEY ("GRANTEE_RES_TYPE")
	  REFERENCES "DECMGR"."RESOURCE_TYPES" ("RES_TYPE") DEFERRABLE INITIALLY DEFERRED ENABLE;
