--------------------------------------------------------
--  Ref Constraints for Table XV_SC_PREF_SC_TYPE_DATA
--------------------------------------------------------

  ALTER TABLE "XVIEWMGR"."XV_SC_PREF_SC_TYPE_DATA" ADD CONSTRAINT "XV_SC_PREF_SC_TYPE_FK1001" FOREIGN KEY ("SCAN_TYPE")
	  REFERENCES "DECMGR"."SCAN_TYPES" ("SCAN_TYPE") ENABLE;
  ALTER TABLE "XVIEWMGR"."XV_SC_PREF_SC_TYPE_DATA" ADD CONSTRAINT "XV_SC_PREF_SC_TYPE_FK999" FOREIGN KEY ("SPT_ID")
	  REFERENCES "DECMGR"."SCAN_PREFERENCE_TEMPLATES" ("ID") DEFERRABLE INITIALLY DEFERRED ENABLE;
