--------------------------------------------------------
--  Ref Constraints for Table XV_SPIRE_APPLNTS_DATA
--------------------------------------------------------

  ALTER TABLE "XVIEWMGR"."XV_SPIRE_APPLNTS_DATA" ADD CONSTRAINT "XV_SPIRE_APPLNTS_FK1001" FOREIGN KEY ("OU_ID")
	  REFERENCES "DECMGR"."ORGANISATION_UNIT_MASTER" ("ORGAN_ID") ENABLE;
  ALTER TABLE "XVIEWMGR"."XV_SPIRE_APPLNTS_DATA" ADD CONSTRAINT "XV_SPIRE_APPLNTS_FK1002" FOREIGN KEY ("RP_ID")
	  REFERENCES "DECMGR"."RESOURCE_PEOPLE" ("ID") ENABLE;
  ALTER TABLE "XVIEWMGR"."XV_SPIRE_APPLNTS_DATA" ADD CONSTRAINT "XV_SPIRE_APPLNTS_FK1003" FOREIGN KEY ("RES_ID")
	  REFERENCES "DECMGR"."RESOURCES" ("ID") ENABLE;
  ALTER TABLE "XVIEWMGR"."XV_SPIRE_APPLNTS_DATA" ADD CONSTRAINT "XV_SPIRE_APPLNTS_FK1004" FOREIGN KEY ("FTF_ID")
	  REFERENCES "DECMGR"."FILE_FOLDERS" ("ID") ENABLE;
  ALTER TABLE "XVIEWMGR"."XV_SPIRE_APPLNTS_DATA" ADD CONSTRAINT "XV_SPIRE_APPLNTS_FK999" FOREIGN KEY ("SAD_ID")
	  REFERENCES "SPIREMGR"."SPIRE_APPLICANT_DETAILS" ("ID") DEFERRABLE INITIALLY DEFERRED ENABLE;
