--------------------------------------------------------
--  Ref Constraints for Table XV_WB_ACTIONS_DATA
--------------------------------------------------------

  ALTER TABLE "XVIEWMGR"."XV_WB_ACTIONS_DATA" ADD CONSTRAINT "XV_WB_ACTIONS_FK1001" FOREIGN KEY ("WBA_ID")
	  REFERENCES "BPMMGR"."WORKBASKET_ACTIONS" ("ID") DEFERRABLE INITIALLY DEFERRED ENABLE;
  ALTER TABLE "XVIEWMGR"."XV_WB_ACTIONS_DATA" ADD CONSTRAINT "XV_WB_ACTIONS_FK1002" FOREIGN KEY ("PRIMARY_DATA_UREF")
	  REFERENCES "BPMMGR"."UREFS" ("UREF") DEFERRABLE INITIALLY DEFERRED ENABLE;
  ALTER TABLE "XVIEWMGR"."XV_WB_ACTIONS_DATA" ADD CONSTRAINT "XV_WB_ACTIONS_FK1003" FOREIGN KEY ("BUSINESS_STAGE_UREF")
	  REFERENCES "BPMMGR"."UREFS" ("UREF") DEFERRABLE INITIALLY DEFERRED ENABLE;
  ALTER TABLE "XVIEWMGR"."XV_WB_ACTIONS_DATA" ADD CONSTRAINT "XV_WB_ACTIONS_FK1004" FOREIGN KEY ("WORKBASKET_UREF")
	  REFERENCES "BPMMGR"."UREFS" ("UREF") DEFERRABLE INITIALLY DEFERRED ENABLE;
  ALTER TABLE "XVIEWMGR"."XV_WB_ACTIONS_DATA" ADD CONSTRAINT "XV_WB_ACTIONS_FK1005" FOREIGN KEY ("MSG_ID")
	  REFERENCES "ENVMGR"."MESSAGES" ("ID") DEFERRABLE INITIALLY DEFERRED ENABLE;
  ALTER TABLE "XVIEWMGR"."XV_WB_ACTIONS_DATA" ADD CONSTRAINT "XV_WB_ACTIONS_FK1006" FOREIGN KEY ("SECONDARY_DATA_UREF")
	  REFERENCES "BPMMGR"."UREFS" ("UREF") DEFERRABLE INITIALLY DEFERRED ENABLE;
  ALTER TABLE "XVIEWMGR"."XV_WB_ACTIONS_DATA" ADD CONSTRAINT "XV_WB_ACTIONS_FK1007" FOREIGN KEY ("TERTIARY_DATA_UREF")
	  REFERENCES "BPMMGR"."UREFS" ("UREF") DEFERRABLE INITIALLY DEFERRED ENABLE;
