GRANT SELECT ON "DECMGR"."FILE_VERSIONS" TO "PVEXMGR";
  GRANT SELECT ON "DECMGR"."FILE_VERSIONS" TO "SPIREMGR";
  GRANT UPDATE ON "DECMGR"."FILE_VERSIONS" TO "APPENV";
  GRANT SELECT ON "DECMGR"."FILE_VERSIONS" TO "APPENV";
  GRANT INSERT ON "DECMGR"."FILE_VERSIONS" TO "APPENV";
