CREATE SMALLFILE TABLESPACE NOACCESS DATAFILE
    '/ORCL/NOACCESS.dbf' SIZE 500M REUSE;

CREATE SMALLFILE TABLESPACE TBSBLOB DATAFILE
    '/ORCL/TBSBLOB.dbf' SIZE 500M REUSE;

CREATE SMALLFILE TABLESPACE TBSCLOB DATAFILE
    '/ORCL/TBSCLOB.dbf' SIZE 500M REUSE;

CREATE SMALLFILE TABLESPACE TBSDATA DATAFILE
    '/ORCL/TBSDATA.dbf' SIZE 500M REUSE;

CREATE SMALLFILE TABLESPACE TBSIDX DATAFILE
    '/ORCL/TBSIDX.dbf' SIZE 500M REUSE;

CREATE SMALLFILE TABLESPACE TBSLOGDATA DATAFILE
    '/ORCL/TBSLOGDATA.dbf' SIZE 500M REUSE;
